### ISSUE TITLE
Is there a way to have multiple requests based on model and serializer

### ISSUE THREAD

**Issue by davidu1975** [tfranzel/drf-spectacular#1000]
We have a view that accepts a Model name as a parameter and uses the Model and Serializer dynamically, how can I specify
Currently drf spectacular complains unable to determine serializer
how can I document in UI that request is based on param Model Name?

**Comment by tfranzel** [comment]
you can't directly link a parameter to a output model. OpenAPI 3 does not have such capability. You can only add a parameter manually with `OpenApiParameter` and declare multiple serializers with `PolymorphicProxySerializer` through   the `@extend_schema` decorator:

https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-endpoints-use-different-serializers-depending-on-the-situation

Pleas read up on the documentation for `PolymorphicProxySerializer`. `resource_type_field_name` may be None for easier handling when no code generation is used.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
