### ISSUE TITLE
Is there a way to alter the serializer field's schema when the field is derived from the model field?

### ISSUE THREAD

**Issue by hoefling** [tfranzel/drf-spectacular#1003]
This is rather a question than a bug. Let's say I have the usual boilerplate

```py
from django.db import models
from rest_framework import serializers

class Model(models.Model):
    hostname = models.CharField(...)

class Serializer(serializers.ModelSerializer):
    class Meta:
        model = Model
        fields = ('hostname', )
```
and I want to spec the `OpenApiTypes.HOSTNAME` type in the field. Is there a way to achieve that without explicitly configuring the field in the serializer class? Surely, I could do smth like

```py
HostnameField = utils.extend_field(OpenApiTypes.HOSTNAME)(serializers.CharField)

class Serializer(serializers.ModelSerializer):
    hostname = HostnameField(...)
    ...
```
etc, but maybe there is a better way I don't see yet.

**Comment by tfranzel** [comment]
we have decorator for that use case: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-3-extend-schema-field-and-type-hints

However, don't do it like in your example. You are modifying `serializers.CharField`, which is not what you want. Create a decorated subclass as in the doc.

**Comment by hoefling** [comment]
@tfranzel ah yes, I mistyped `extend_schema_field`, but meant that one. So there is no way to specify custom field type without having the field explicitly declared in serializer class?
