### ISSUE TITLE
Cannot use `@extend_schema_serializer(component_name="...")` with `djangorestframework-dataclasses`

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#1004]
**Describe the bug**

The `component_name` argument to `@extend_schema_serializer` does not work on `DatclassSerializer`s from `djangorestframework-dataclasses`.

**To Reproduce**

```py
from drf_spectacular.utils import extend_schema_serializer
from rest_framework_dataclasses.serializers import DataclassSerializer

@dataclass
class Car:
    name: str


@extend_schema_serializer(component_name="Truck")
class CarSerializer(DataclassSerializer[Car]):
    class Meta:
        dataclass = Car
```

**Expected behavior**

I would expect the generated component name to be `Truck` but it is still `Car`.

### Environment

```
djangorestframework             3.14.0
drf-spectacular                 0.26.2
djangorestframework-dataclasses 1.2.0
```

- Python 3.10.11

**Comment by tfranzel** [comment]
not quite sure what happened here, since this was supposed to be fixed by #839 I believe

**Comment by johnthagen** [comment]
@tfranzel Thanks for confirming that I was at least using this as intended (I wasn't 100% sure).

**Comment by tfranzel** [comment]
the tests cover 2 approaches. one with `ref_name` and one with decoration directly on the `dataclass`. 

https://github.com/tfranzel/drf-spectacular/blob/master/tests/contrib/test_rest_framework_dataclasses.py#L43

decorating on the actual serializer was somehow not covered in the tests. not sure if we had a reason for that. I have to contemplate this, since it was a while ago.

**Comment by johnthagen** [comment]
@tfranzel Thanks for sharing that `@extend_schema_serializer` could go directly on a `dataclass`. Since the name as `_serialier` in the name, I didn't even think to try it on a `dataclass`.

Maybe there would be some way in the docs to also mention that this decorator works on `dataclass`es used with `DataclassSerializer`?

**Comment by tfranzel** [comment]
Closed the gap. I think this just simply got overlooked due to the mainly inline usage of `DataclassSerializer`. However, one would expect this to work, while the dataclass decoration is a nifty but unexpected functionality.
