### ISSUE TITLE
'NoneType' object has no attribute '_meta' when trying to generate an API schema with drf-spectacular

### ISSUE THREAD

**Issue by ruilvo** [tfranzel/drf-spectacular#1005]
I have a project that uses \`drf-spectatular\` to generate an API schema for my API created with DRF.

However, when I try accessing the path for the API schema I get an error:

    Exception Type: AttributeError at /api/schema/
    Exception Value: 'NoneType' object has no attribute '_meta'

I'm really not sure what's causing this. This used to work when I was using Django 3.x, but now I decided to pick this project back, with everything up to date, and it's not working.

The project is [fully open source, so you can take a look](https://github.com/ruilvo/radioamadorismo-website/tree/dev).

Pip information:

    Package                 Version
    ----------------------- --------
    asgiref                 3.7.2
    astroid                 2.15.5
    attrs                   23.1.0
    black                   23.3.0
    click                   8.1.3
    crispy-bootstrap3       2022.1
    dill                    0.3.6
    dj-rest-auth            4.0.1
    Django                  4.2.2
    django-cors-headers     4.0.0
    django-crispy-forms     2.0
    django-extensions       3.2.3
    django-filter           23.2
    djangorestframework     3.14.0
    drf-spectacular         0.26.2
    drf-spectacular-sidecar 2023.6.1
    drf-writable-nested     0.7.0
    inflection              0.5.1
    isort                   5.12.0
    jsonschema              4.17.3
    lazy-object-proxy       1.9.0
    mccabe                  0.7.0
    mypy-extensions         1.0.0
    packaging               23.1
    pathspec                0.11.1
    Pillow                  9.5.0
    pip                     23.1.2
    platformdirs            3.5.3
    psycopg2                2.9.6
    pygraphviz              1.11
    pylint                  2.17.4
    pylint-django           2.5.3
    pylint-plugin-utils     0.8.2
    pyrsistent              0.19.3
    pytz                    2023.3
    PyYAML                  6.0
    setuptools              65.5.1
    sqlparse                0.4.4
    tomlkit                 0.11.8
    uritemplate             4.1.1
    uWSGI                   2.0.21
    wheel                   0.40.0
    whitenoise              6.4.0
    wrapt                   1.15.0

Full log:

    Request Method: GET
    Request URL: http://servicos.mywebsite.pt/api/schema/
    
    Django Version: 4.2.2
    Python Version: 3.11.4
    Installed Applications:
    ['django.contrib.admin',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.messages',
     'whitenoise.runserver_nostatic',
     'django.contrib.staticfiles',
     'rest_framework',
     'dj_rest_auth',
     'corsheaders',
     'django_filters',
     'drf_spectacular',
     'drf_spectacular_sidecar',
     'crispy_forms',
     'crispy_bootstrap3',
     'django_extensions',
     'users',
     'repeaters',
     'aprs']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'corsheaders.middleware.CorsMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware']
    
    
    
    Traceback (most recent call last):
      File "/root/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
        response = get_response(request)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
        return view_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
        return self.dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
        response = self.handle_exception(exc)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
        self.raise_uncaught_exception(exc)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
        raise exc
        ^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
        response = handler(request, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/views.py", line 83, in get
        return self._get_schema_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
        data=generator.get_schema(request=request, public=self.serve_public),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/generators.py", line 268, in get_schema
        paths=self.parse(request, public),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/generators.py", line 239, in parse
        operation = view.schema.get_operation(
                    
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/utils.py", line 410, in get_operation
        return super().get_operation(path, path_regex, path_prefix, method, registry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 95, in get_operation
        operation['responses'] = self._get_response_bodies()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 1348, in _get_response_bodies
        return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 1404, in _get_response_for_code
        component = self.resolve_serializer(serializer, direction)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 1575, in resolve_serializer
        component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 907, in _map_serializer
        schema = self._map_basic_serializer(serializer, direction)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py", line 999, in _map_basic_serializer
        for field in serializer.fields.values():
                     ^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
                                             ^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/serializers.py", line 356, in fields
        for key, value in self.get_fields().items():
                          ^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/serializers.py", line 1051, in get_fields
        info = model_meta.get_field_info(model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/.local/lib/python3.11/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
        opts = model._meta.concrete_model._meta
               ^^^^^^^^^^^

**Comment by ruilvo** [comment]
Looking at the logs, the error seems to have to deal with the login view?

In Django's debug page I see, under `/root/.local/lib/python3.11/site-packages/drf_spectacular/utils.py, line 410, in get_operation `, for the local vars:

<html><body>


__class__ | <class 'drf_spectacular.utils.extend_schema.<locals>.decorator.<locals>.ExtendedSchema'>
-- | --
exclude | False
is_in_scope | <function extend_schema.<locals>.decorator.<locals>.is_in_scope at 0x7f2030100e00>
method | 'POST'
operation | None
path | '/api/auth/login/'
path_prefix | '^/api'
path_regex | 'api/auth/login/'
registry | <drf_spectacular.plumbing.ComponentRegistry object at 0x7f20300d66d0>
self | <drf_spectacular.utils.extend_schema.<locals>.decorator.<locals>.ExtendedSchema object at 0x7f20302aff10>


</body>
</html>

While 2 steps after, on `/root/.local/lib/python3.11/site-packages/drf_spectacular/openapi.py, line 1404, in _get_response_for_code `, I see:

<html><body>


description | ''
-- | --
direction | 'response'
examples | []
headers | {}
media_types | None
self | <drf_spectacular.utils.extend_schema.<locals>.decorator.<locals>.ExtendedSchema object at 0x7f20302aff10>
serializer | Error in formatting: AttributeError: 'NoneType' object has no attribute '_meta'
status_code | '200'


</body>
</html>

**Comment by tfranzel** [comment]
can you drill down on which model and serializer exactly? `dj-rest-auth` is heavily tested on our side, so I'm a bit puzzled.

**Comment by ruilvo** [comment]
Do you have any suggestion on how to do that? I did make a custom user model, but it's the typical 

```py
class User(AbstractUser):
    pass
```

That's done just in case.

**Comment by ruilvo** [comment]
I ran the schema generation on the debugger, the call stack seems to freeze parsing `<dj_rest_auth.serializers.TokenSerializer object at 0x7fcb9bdb64d0>`...

**Comment by tfranzel** [comment]
>  I did make a custom user model, but it's the typical

never had an issue with that

> <dj_rest_auth.serializers.TokenSerializer object at 0x7fcb9bdb64d0>...

the serializer never changed: https://github.com/iMerica/dj-rest-auth/blame/master/dj_rest_auth/serializers.py#L139

and the token model is from DRF and hasn't change in a very long while. 


what a second... `dj-rest-auth` completely changed they settings structure recently. make sure your API still works first! most of their settings were moved, changed. Maybe the `model` is `None` to due a broken setting, and as such `_meta` can't be found on a  defaulting`None`

**Comment by ruilvo** [comment]
I managed to reproduce the issue, it's a problem with this class:

```
root@74d6605783ad:/workspace/backend# python manage.py shell
Python 3.11.4 (main, Jun 13 2023, 15:08:32) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dj_rest_auth.serializers import TokenSerializer
>>> TokenSerializer()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/.local/lib/python3.11/site-packages/rest_framework/serializers.py", line 530, in __repr__
    return representation.serializer_repr(self, indent=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/rest_framework/utils/representation.py", line 77, in serializer_repr
    fields = serializer.fields
             ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/rest_framework/serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
           ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_meta'
>>> 
```

**Comment by ruilvo** [comment]
I'll check the settings structure, otherwise I'm going to complain to dj-rest-auth. Thank you for the time!

**Comment by tfranzel** [comment]
things were changed here: https://github.com/iMerica/dj-rest-auth/releases/tag/3.0.0

we account for that change since [0.26.0](https://github.com/tfranzel/drf-spectacular/releases/tag/0.26.0)

**Comment by ruilvo** [comment]
Ah, I figured the problem I think.

I have:

```py
REST_AUTH = {"TOKEN_MODEL": None}
```

Because [the docs say](https://dj-rest-auth.readthedocs.io/en/latest/configuration.html?highlight=TOKEN_MODEL#token-model):

> If set to `None` token authentication will be disabled. 

I totally forgot I did this.

Now, is it a bug that the token serializer is being scanned during the schema generation?! If yes, by whom?!

**Comment by ruilvo** [comment]
Ah, I figured the problem I think.

I have:

```py
REST_AUTH = {"TOKEN_MODEL": None}
```

Because [the docs say](https://dj-rest-auth.readthedocs.io/en/latest/configuration.html?highlight=TOKEN_MODEL#token-model):

> If set to `None` token authentication will be disabled. 

I totally forgot I did this.

Now, is it a bug that the token serializer is being scanned during the schema generation?! If yes, by whom?!

**Comment by ruilvo** [comment]
Yah, I can confirm that re-enabling token auth fixes the problem. But I shouldn't have to have this enabled to get a schema... Very weird...

**Comment by tfranzel** [comment]
Ahh I see. Well the docs say it, but I would cautiously guess this is a bug on their end, because a `ModelSerializer` without a `Model` is broken by design. If the attribute is set to `None`, the serializer is never supposed to be used, which it was. We wouldn't process it, unless it was actually referenced by the code.

**Comment by tfranzel** [comment]
can I close this? any updates?

**Comment by ruilvo** [comment]
Sorry, no I don't have any more updates. It's weird that the token model is (attempted to be) parsed even when it's set to `None`. Whether this is a spectacular bug, or a DRF bug, goes beyond my expertise, and I couldn't debug it any further in the meanwhile.
