### ISSUE TITLE
Auto schema generation doesn't support pydantic schema

### ISSUE THREAD

**Issue by sydney-runkle** [tfranzel/drf-spectacular#1006]
**Describe the bug**
I currently use `SQLModel` and `Pydantic` to support queries to my database and serialization of said data into json. Pydantic comes with a handy `schema` feature for all BaseModels that generates either a json or dict schema.

When I use a single model with no nested fields and pass in the Model's dict schema to the `@extend_schema` decorator as one o the response params, ex: `responses={200: my_model.schema()}`, this works fine. However, if I have a model with another model as one of its fields (see [here](https://docs.pydantic.dev/1.10/usage/schema/#schema-customization) for an example), the schema generated from that isn't interpreted correctly by `drf-spectacular`.

Specifically, the problem seems to be that `Pydantic` generates its documentation for nested models inside of a `definitions` key. I'm wondering if support could be added to `drf-spectacular` to move anything declared under the `definitions` keyword to the `components/schema` section of the api docs. `Pydantic` does add support for customizing the `$ref` location/prefix for models referenced elsewhere, so this wouldn't be an issue.

**Comment by sydney-runkle** [comment]
An alternative solution (that might already exist) could be - how can I explicitly state that I'd like a schema (serializer) to be included in the `components/schemas` section? If there's a way to do this, I could simply do that with all of the models that are included as fields in the response, then calibrate the generated references to point to that section.

**Comment by tfranzel** [comment]
I see. We accounted for raw schemas on a best effort basis but never really paid attention to this particular case.

I see 2 options (minus a big refactoring, which I am not that keen on):

1. write a postprocessing hook that cleans up, i.e. removing the components from the path and adding them in the components section and inserting a ref instead. https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks

2. only decorate a raw schema with a reference: `{"$ref": "#/components/schemas/XXX"}`  and either use a postprocessing hook or the setting `APPEND_COMPONENTS` to fill in the definition part there with `my_model.schema()`.

I think you can accomplish this with 1-2 helper functions and a bit of tooling. Keep in mind that OpenAPI <3.1 and JSONSchema are not 100% compatible. Usually not an issue, but your mileage may vary

**Comment by sydney-runkle** [comment]
Hi tfranzel,

Thank you very much for these suggestions and your prompt response. They both seem like feasible options. The `APPEND_COMPONENTS` setting will be of great use. 

Is there anywhere that you could point me to with examples of some custom postprocessing hooks? Thanks for the help.

I'll follow up later today to confirm that this worked and close the issue.

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/hooks.py

the second one is pretty basic. please read the above doc section carefully.

I think it might also be possible to write a serializer extension to accommodate this. I'll throw a quick test together later but will most certainly not include it officially, which is okay as you can write/use extensions locally without issue.

**Comment by caarmen** [comment]
Funny there are a couple of us with the same need on the same day 😅 


I tried the postprocessing hook and it seems to work 💪🏻 
Pydantic models (from link above):
```python
class Foo(BaseModel):
    a: int


class Model(BaseModel):
    a: Foo
```

View:
Define a response of the outer model type `Model`:
```python
class MyView(generics.ListAPIView):


    @extend_schema(
        responses={
            200: OpenApiResponse(response=Model.schema())
        }
    )
    def get(self, request, *args, **kwargs):
```

post processing function in `com.myexample` package:
Add the inner model `Foo` to the `definitions`:
```python
def postprocessing(result, generator, request, public):
    definitions = result.setdefault("definitions", {})
    definitions["Foo"] = Foo.schema()
    return result
```

settings:
Declare the post processing hook
```python
    "POSTPROCESSING_HOOKS": ["com.myexample.postprocessing"],
```

**Comment by sydney-runkle** [comment]
Thanks all! I just confirmed - I was able to use the `APPEND_COMPONENTS` strategy to solve the problem as well.

Closing this as both solutions suggested work well.

Thanks team!

**Comment by tfranzel** [comment]
@caarmen, beware that you might want to add the (default on) enum processing back into the mix:

```python
"POSTPROCESSING_HOOKS": [
    "drf_spectacular.hooks.postprocess_schema_enums", "com.myexample.postprocessing", 
],
```

I will try the serializer extension route when I have some spare time and report results here.

**Comment by sydney-runkle** [comment]
Sure thing! Here's what I used for the `APPEND_COMMENTS` route:
```
# views.py

from drf_spectacular.utils import extend_schema
@extend_schema(
        parameters=my_params,
        responses={
            200: {"$ref": "#/components/schemas/Model"}
        }
    )
def get(...)
    ...
```

```
# settings.py
from pydantic.schema import schema

SPECTACULAR_SETTINGS = {
    ...
    'APPEND_COMPONENTS': {
        "schemas": schema(
            [Model], 
            by_alias=True, 
            ref_template="#/components/schemas/{model}"
        )["definitions"]
    }
}
```

I've got tons of `pydantic` models I need to include the schema for in the openapi docs, so I plan to create a module that abstracts away the `pydantic.schema(...)` logic so that I can keep the `settings.py` file clean.

Let me know if you have any additional questions! Nice to work with you all on this.

**Comment by caarmen** [comment]
@sydney-runkle Thanks!

I think my issues are that my pydantic model classes are defined in a package that tries to access some drf code that requires the app being initialized. I assume I could refactor this and move those classes to an isolated module. I didn't try it yet though, but I'll be sure to come back here and check out this snippet if I do get a chance. Thanks again :)

**Comment by tfranzel** [comment]
I attempted to do the serializer extension. Turns out Pydantic has some specifics we do not yet account for. So in the spirit of "eat your own dog food", I fixed 2 minors to allow for proper functionality of this extension:

https://github.com/tfranzel/drf-spectacular/pull/1009/files#diff-5f1057f5cbe9827ecd29bac35d534f40e4beb52a49f53206bae7ad82bc4f2e4d

I added the extension to the blueprint section. Not sure yet whether we should support this officially, but people can at least copy&paste that extension for the time being.

Feedback would be much appreciated because I hastily put this together.

**Comment by caarmen** [comment]
I may be missing something.

* I copied https://github.com/tfranzel/drf-spectacular/blob/9bae4f0cb315feeb422b3c14c9c7ace63727d837/docs/blueprints/pydantic.py to my project (`myapp.schema` module). 
* I updated my `apps.py`, and added `import myapp.schema` to the existing `ready()` method.

I run `python -m manage spectacular --format openapi-json` and with a breakpoint I do see that import being called.

But the extension code itself seems to never be called, and the inner pydantic object's definition isn't in the correct location (this issue).

I'm surely missing something. 😅 Maybe something related to the plumbing changes? I couldn't see how to apply those changes.

**Comment by tfranzel** [comment]
@caarmen, looks like you did everything correctly. That is very weird. 

The plumbing changes just prevent this extensions from throwing errors while processing. You should definitely see errors with the released version. You can install the master branch with `pip install pip install git+https://github.com/tfranzel/drf-spectactular@master`.

> I run python -m manage spectacular --format openapi-json and with a breakpoint I do see that import being called.

please print a debug message in the `ready()` method to make sure the extension is actually imported.  I tested this with both pydantic's `BaseModel` as well as pydantic's `@dataclass` and it worked as expected. We use this extension loading method in a multitude of project and it always works. Not entirely sure what to tell you here. Also do a `print` in `myapp.schema` on the bottom of the file just to be sure.

**Comment by sydney-runkle** [comment]
I think I'm having the same issue.

I've copied the pydantic extension into my main app's `schema.py` file, and imported that within the `ready()` method for said app's config. the import seems to be called, but when I try to generate documentation, I'm getting the following error:

`type object 'MyModel' has no attribute 'partial'`, which seems to be coming from the `plumbing.py` file.

@tfranzel, could you please provide examples of the code that you used that worked properly?

Thanks!

**Comment by sydney-runkle** [comment]
As an aside, the `pydantic` schema that's generated from `MyModel.schema()` versus `schema([MyModel])` differs slightly. I'm currently using the latter of the two, as everything is nested within one `"definitions"` key. When I have a bit more time this coming weekend, I can look into how we might be able to simplify the existing extension based on this advantage.

**Comment by tfranzel** [comment]
> type object 'MyModel' has no attribute 'partial', which seems to be coming from the plumbing.py file.

that is 1 of the 2 issues I fixed in the master branch. Those are required for the extension to work properly. As I said, please install the master branch for those fixes with:

```sh
pip install git+https://github.com/tfranzel/drf-spectacular.git@master
```

Let me know if it now works for you.

**Comment by tfranzel** [comment]
This is the test case I wrote and is working for me. Obviously, the extension will be not below the models outside of a test case. 

```python
from pydantic import BaseModel
from pydantic.dataclasses import dataclass
from rest_framework.decorators import api_view

from drf_spectacular.extensions import OpenApiSerializerExtension
from drf_spectacular.plumbing import ResolvedComponent
from drf_spectacular.utils import extend_schema
from tests import assert_schema, generate_schema


@dataclass
class D:
    id: int


class A(BaseModel):
    name: str


class B(BaseModel):
    name: str
    a: A


class C(BaseModel):
    id: int
    b: B
    d: D


class PydanticExtension(OpenApiSerializerExtension):
    target_class = 'pydantic.BaseModel'
    match_subclasses = True

    def get_name(self, auto_schema, direction):
        return self.target.__name__

    def map_serializer(self, auto_schema, direction):
        def translate_refs(obj, key=None):
            if isinstance(obj, dict):
                return {k: translate_refs(v, k) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [translate_refs(i) for i in obj]
            elif key == '$ref':
                return obj.replace('#/definitions/', '#/components/schemas/')
            else:
                return obj

        # let pydantic generate a JSON schema
        schema = self.target.schema()

        # pull out potential sub-schemas and put them into component section
        for sub_name, sub_schema in schema.pop('definitions', {}).items():
            component = ResolvedComponent(
                name=sub_name,
                type=ResolvedComponent.SCHEMA,
                object=sub_name,
                schema=translate_refs(sub_schema),
            )
            auto_schema.registry.register_on_missing(component)

        return translate_refs(schema)


def test_pydantic(no_warnings):
    @extend_schema(responses=C)
    @api_view(['GET'])
    def pi(request, foo):
        pass  # pragma: no cover

    schema = generate_schema('x', view_function=pi)
    assert_schema(
        schema, 'tests/contrib/test_pydantic.yml'
    )

```

**Comment by tfranzel** [comment]
awesome @sydney-runkle, glad this works now. 🎉 

@caarmen I think once you fix your app loading it should work for you too.

**Comment by caarmen** [comment]
I moved my models into an isolated module. I can now use the `APPEND_COMPONENTS` as mentioned in https://github.com/tfranzel/drf-spectacular/issues/1006#issuecomment-1597273154 👍🏻 

However, using the extension instead of `APPEND_COMPONENTS` results in the original behavior raised in this issue.

>please print a debug message in the ready() method to make sure the extension is actually imported. ...  Also do a print in myapp.schema on the bottom of the file just to be sure.


```
$ python -m manage spectacular --format openapi-json --file "/tmp/openapi.json"
ready
bottom of schema module
```

I'll see if I can debug this and find anything further.

**Comment by tfranzel** [comment]
`APPEND_COMPONENTS` is a measure of last resort and I prefer people not using it because it has caveats that are hard to fully understand.

@caarmen lets try this in the debugger or console (where `C` is your Pydantic model class):

```python
>>> PydanticExtension
<class 'tests.contrib.test_pydantic.PydanticExtension'>
>>> PydanticExtension.target_class
'pydantic.BaseModel'
>>> PydanticExtension._load_class()  # import the string
>>> PydanticExtension.target_class   # check if pydantic base class was loaded properly
<class 'pydantic.main.BaseModel'>
>>> PydanticExtension._matches(C)  # check if the matching mechanics work
True
>>> issubclass(C, PydanticExtension.target_class)    # this is essentially the same and should be true also
True

>>> from drf_spectacular.extensions import OpenApiSerializerExtension
>>> OpenApiSerializerExtension._registry  # should return a list with around a dozen extensions including yours  
```

> I added prints to get_name() and map_serializer() and they don't appear.

seems like the extension is never actually triggered then.

**Comment by caarmen** [comment]
The debug values are all the same, except for the very last one: I only have two extensions loaded:

```
[<class 'drf_spectacular.extensions.OpenApiSerializerExtension'>, <class 'myapp.schema.PydanticExtension'>]
```

I also noticed: the `get_name()` and `map_serializer()` are called if I define the extend schema differently.

Before (functions not called):
```python
responses={200: {"$ref": "#/components/schemas/MyModel" }}
```

or
```python
responses={200: OpenApiResponse(response=MyModel.schema(), description="some description")}
```

What makes it be called:
```python
responses=MyModel
```

But not only does it look like I'm then missing info (can't set a description or map different objects for different http status codes), but also I get errors:
```
AttributeError: type object 'MyModel' has no attribute 'context'
```

I'm guessing there's some part of documentation I missed somewhere :sweat_smile:

**Comment by tfranzel** [comment]
don't do

```python
responses={200: {"$ref": "#/components/schemas/MyModel" }}. # WRONG
responses={200: OpenApiResponse(response=MyModel.schema(), description="some description")} # WRONG
```

You are hiding the pydantic model from the extension by passing a dict! The extension is there to do this for you. use 

```python
responses=MyModel # OR
responses={200: MyModel} # OR
responses={200: OpenApiResponse(response=MyModel, description="some description")}
```

> AttributeError: type object 'MyModel' has no attribute 'context'

that is a new (3rd) issue. this happens because you use it (maybe indirectly) on a `ModelViewSet` `list` method. It should work everywhere except in that case.

**Comment by caarmen** [comment]
> don't do
> 
> ```python
> responses={200: {"$ref": "#/components/schemas/MyModel" }}. # WRONG
> responses={200: OpenApiResponse(response=MyModel.schema(), description="some description")} # WRONG
> ```
> 
> You are hiding the pydantic model from the extension by passing a dict! The extension is there to do this for you. use
> 
> ```python
> responses=MyModel # OR
> responses={200: MyModel} # OR
> responses={200: OpenApiResponse(response=MyModel, description="some description")}
> ```
> 


Thank you for this clarification! 🙏🏻 

> > AttributeError: type object 'MyModel' has no attribute 'context'
> 
> that is a new (3rd) issue. this happens because you use it (maybe indirectly) on a `ModelViewSet` `list` method. It should work everywhere except in that case.

Indeed, I'm using it in a list, but in a `ListAPIView`, not in a `ViewSet`.

Ok, too bad if it doesn't work in a list for now. I have a workaround here: https://github.com/tfranzel/drf-spectacular/issues/1006#issuecomment-1597156152

I'll explore using it in other apis (retrieve, update, etc).

Thanks again!

**Comment by tfranzel** [comment]
getting ambitious here. okay, so I just looked into the issue and it turns out to be a pretty minor change that actually improves robustness. 

With those 3 minor fixes, I believe, we pretty much cleared all blockers to use extensions for non-DRF classes.

@caarmen update the master branch again and I think it will work then.

**Comment by caarmen** [comment]
@tfranzel Excellent! With the new master version, it seems to work well!

I did these changes in my project to generate doc correctly:

```patch
diff --git a/myapp/api/definitions/v1/myview.py b/myapp/api/definitions/v1/myview.py
index df4ca32..652df66 100644
--- a/myapp/api/definitions/v1/myview.py
+++ b/myapp/api/definitions/v1/myview.py
@@ -23,7 +23,7 @@ def get_list_quota_users_view_schema() -> dict:
                 location=OpenApiParameter.PATH,
             ),
         ],
-        responses={200: OpenApiResponse(response=MyModel.schema(), description="Some description")},
+        responses={200: OpenApiResponse(response=MyModel, description="Some description")},
     )   
 
     return {"get": list_schema}
diff --git a/myapp/apps.py b/myapp/apps.py
index 81898f5..432abfb 100644
--- a/myapp/apps.py
+++ b/myapp/apps.py
@@ -20,3 +20,4 @@ class MyAppConfig(AppConfig):
     def ready(self):
 
+        import myapp.schema
diff --git a/myapp/settings.py b/myapp/settings.py
index f8de196..4dde1bb 100644
--- a/myapp/settings.py
+++ b/myapp/settings.py
@@ -264,8 +264,4 @@ SPECTACULAR_SETTINGS = {
     "SCHEMA_PATH_PREFIX": "/v[1-2]",
     "SERVE_INCLUDE_SCHEMA": False,
-    "POSTPROCESSING_HOOKS": [
-        "drf_spectacular.hooks.postprocess_schema_enums",
-        "myapp.common.openapi.postprocessing",
-    ],
 }

```

Thanks!

**Comment by caarmen** [comment]
Will there be updates to support pydantic 2? Looks like the apis are a bit different.
