### ISSUE TITLE
Typing custom `NumberInFilter` django-filter

### ISSUE THREAD

**Issue by radusuciu** [tfranzel/drf-spectacular#1016]
I've got a `NumberInFilter` implemented as recommended in the [`django-filter` docs](https://django-filter.readthedocs.io/en/stable/ref/filters.html#baseinfilter):

```python
class NumberInFilter(BaseInFilter, NumberFilter):
    pass

class F(FilterSet):
    id__in = NumberInFilter(field_name='id', lookup_expr='in')
```

When generating schema, `drf-spectacular` generates the following entry:

```yaml
  - in: query
    name: id__in
    schema:
      type: array
      items:
        type: integer
    description: Multiple values may be separated by commas.
```

However, I don't think this is entirely correct, as this filter and all other such filters that inherit from `BaseInFilter` expect the filter parameters to be passed in as a list of comma separate values, so the actual type should be string.

> This is a base class used for creating IN lookup filters. It is expected that this filter class is used in conjunction with another filter class, as this class only validates that the incoming value is comma-separated. The secondary filter is then used to validate the individual values.

Regarding `BaseInFilter`:
If we attempt to use `extend_schema_field` to wrap the filter class like so: `NumberInFilter = extend_schema_field(OpenApiTypes.STR)(_NumberInFilter)`, or the actual instance in the `FilterSet`, the type becomes a string array -- still not quite accurate.

Is there a better way to force the type of this filter or other filter classes that are based on `BaseInFilter`, ideally just in one place? I know that you can use `extend_schema` on the corresponding `ViewSet` like so:

```python
@extend_schema(
    parameters=[
        OpenApiParameter('id__in', OpenApiTypes.STR)
    ]
)
```

but if you have a lot of viewsets/filters that can become a little tedious to maintain.

Thank you!

**Comment by tfranzel** [comment]
> However, I don't think this is entirely correct, as this filter and all other such filters that inherit from BaseInFilter expect the filter parameters to be passed in as a list of comma separate values, so the actual type should be string.

Don't be mislead by the description, it originates from the django-filter. I think your custom parameter is actually wrong and the commas might be escaped with a proper client.

You also omitted 2 lines of schema that belong to this parameter: `explode` & `form`

OpenAPI has a range of flags to determine encoding of this: https://spec.openapis.org/oas/v3.0.3#style-examples We cover those with `OpenApiParameter(..., explode=?, form=?)`.

SwaggerUI for example will let you add numbers to a list and when creating the example request, it encodes it as a comma-separated list of numbers, exactly as expected.

I don't see anything wrong here. Doesn't this do exactly what it is supposed to? 

![image](https://github.com/tfranzel/drf-spectacular/assets/13507857/4976387d-bb49-453d-92b3-0974ea7fb19e)

**Comment by radusuciu** [comment]
I think I understand your point about client support here and will read about the explode/style parameters you mentioned - thank you!

As for the client, I'm using [`openapi-typescript-codegen`](https://github.com/ferdikoomen/openapi-typescript-codegen), which translates the type of the original filter to `Array<number>`, and [does not correctly format the query parameter](https://github.com/ferdikoomen/openapi-typescript-codegen/issues/654#issuecomment-1100783140).

So I suppose this a client/me issue - thank you for the response.

**Comment by tfranzel** [comment]
Yes the statement in that linked comment is correct. Looks like `explode: false` is not properly honored by openapi-typescript-codegen. It wouldn't be the first issue with that generator. I'm quite confident we are doing the right thing and a fix must be applied upstream.

We are not gonna degrade our schema to make `openapi-generator` work on such a basic thing. We already made a few accommodations for `openapi-generator` in complicated cases, but we have to draw a line somewhere. :smile: 

If you really need to hack it here, I would recommend writing a postprocessing hook that transforms those arrays into plain strings: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks

However, this might still break in the generated client, iff it attemps to urlencode the "comma-separated string".

**Comment by radusuciu** [comment]
Totally makes sense, thanks again for clearing that up! Also just wanted to note for anyone reading this in the future that there's a [PR](https://github.com/ferdikoomen/openapi-typescript-codegen/pull/1426) in `openapi-typescript-codegen` that looks like it would resolve this.

**Comment by tfranzel** [comment]
cheers! I was curious so I checked and realized you are using a different generator.

fyi: 

https://github.com/tfranzel/drf-spectacular/blob/master/helper/generate-client.sh

```
openapitools/openapi-generator-cli 
generator version: 7.0.0-SNAPSHOT
target: typescript-fetch
```
works pretty well for my projects:

```typescript
        if (requestParameters.idIn) {
            queryParameters['id__in'] = requestParameters.idIn.join(runtime.COLLECTION_FORMATS["csv"]);
        }
```

**Comment by radusuciu** [comment]
Yes, `openapi-typescript-codegen` is definitely a little bit less well maintained but I like it because it doesn't bring in a java dependency, the codebase is small, and for me it's basically feature complete... except this one thing lol
