### ISSUE TITLE
Fields with Enum do not display Type

### ISSUE THREAD

**Issue by chgad** [tfranzel/drf-spectacular#1020]
**Describe the bug**
Given the following model

    class MediaObject(models.Model):
        """
        Model for a media object.
        """
        media_format = models.CharField(
            max_length=5,
            choices=(("image", _("image")), ("audio", _("audio")), ("video", _("video")),),
            verbose_name=_("media format"),
        )

The produced schema is missing the `type` of the choices provided :

    MediaObject:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        media_format:
          $ref: '#/components/schemas/MediaFormatEnum'

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

**Expected behavior**
I have read a few closed Issues and suspect that it'S not even possible 
See here #753 

> More recent Django version have a Choice class, but it needs be be unpacked before usage and so the containing class (including it's name) is lost while constructing the serializer. That would be my preferred solution.

But i'd still like to ask: Is it not possible at all or just difficult or ist it more of a "how to detect the 'correct' type?" question?

**Comment by chgad** [comment]
Note:

I tried to implement this via an Extension like so

   class ChoiceFieldExtension(extensions.OpenApiSerializerFieldExtension):
        target_class = "rest_framework.serializers.ChoiceField"

        def map_serializer_field(self, auto_schema, direction):
            schema = auto_schema._map_serializer_field(self.target, direction, bypass_extensions=True)
            field_class = self.target.parent.Meta.model._meta.get_field(self.target.source).__class__
            type_ = None
            if issubclass(field_class, django.db.models.fields.CharField):
                type_ = "string"
            if issubclass(field_class, django.db.models.fields.IntegerField):
                type_ = "integer"
            if issubclass(field_class, django.db.models.fields.FloatField):
                type_ = "float"
            schema["type"] = type_
            return schema

Yet the `"type"` is still not present in the schema.

**Comment by tfranzel** [comment]
> But i'd still like to ask: Is it not possible at all or just difficult or ist it more of a "how to detect the 'correct' type?" question?

I don't understand your issue here. Yes, the enum type is not listed in the field but a reference is found there. The type is in the corresponding `Enum` component. I don't see no justification for having the type there twice

This gets generated for your `media_format` model field, which looks exactly as expected. I don't see anything missing or incomplete here. Btw this also looks fine in SwaggerUI, i.e. the type is properly displayed.

```yaml
    MediaFormatEnum:
      enum:
      - image
      - audio
      - video
      type: string
      description: |-
        * `image` - image
        * `audio` - audio
        * `video` - video
```

**Comment by chgad** [comment]
> I don't understand your issue here. Yes, the enum type is not listed in the field but a reference is found there. The type is in the corresponding Enum component. I don't see no justification for having the type there twice

In essence, this was my point: Is the fact, that the type is not listed twice, a decision by Design (OpenAPI) or by necessity/simplicity?

**Comment by tfranzel** [comment]
> But i'd still like to ask: Is it not possible at all or just difficult or ist it more of a "how to detect the 'correct' type?" question?

This question led me to believe you are not aware that the type is in the enum component, since we do have the correct type detected, just not where you expected it to be.

> In essence, this was my point: Is the fact, that the type is not listed twice, a decision by Design (OpenAPI) or by necessity/simplicity?

Well simplicity I suppose. Unless there is an actual difference why bother randomly duplicating stuff?

Also, just putting `type` besides `$ref` would be strictly cosmetic, as it would be wiped out by the reference expansion anyway.

**Comment by chgad** [comment]
> Also, just putting type besides $ref would be strictly cosmetic, as it would be wiped out by the reference expansion anyway.

The Code i posted above works if someone encounters this "issue". 

This case ultimately was a "My frontend colleagues were to lazy to implement the `$ref` lookup and made me work on it" case.

If you have nothing more to add to this we can close this issue.

**Comment by tfranzel** [comment]
> The Code i posted above works if someone encounters this "issue".

I still don't understand what exactly the issue is. 

you said 

> Fields with Enum do not display Type

what do you mean by "display"? Which UI? SwaggerUI? Because it is shown there as expected. Can you explain where this actually makes a difference?

**Comment by chgad** [comment]
> 
> >     Fields with Enum do not display Type
> 
> what do you mean by "display"? Which UI? SwaggerUI? Because it is shown there as expected.

The schema,

```
MediaObject:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    media_format:
      $ref: '#/components/schemas/MediaFormatEnum'
```
shows the `$ref` for the field `media_format` but does not include the `type` of the referenced `Enum` which confused my frontend-colleague since fields specified in this way would cause errors. Since i wasn't sure whether it is an OpanAPI spec or a
choice by you to not include it or wipe it, I posted the Question (and solved the issue manually).

> Can you explain where this actually makes a difference?

To be honest it's an extreme edge case since the `type` can be parsed from the Enum schema after all .

> >     The Code i posted above works if someone encounters this "issue".
> 
> I still don't understand what exactly the issue is.

In case someone, explicitly, wants the `type` in the schema of a field which has a `$ref`to an Enum, you can make it work with the code i posted in a postprocessing code.

In the end i found the `type` prop in the corresponding Enum schema and you clarified that it's an OpenAPI spec, hence this is solved.

**Comment by tfranzel** [comment]
I see. 

Your frontend-colleague is playing with fire. Any other conforming OpenAPI tool will ignore that additional `type` in the presence of an `$ref`, due to it's replacement mechanics. You are free to do this since it is valid to add it, but it may explode in your face at a later point. you have been warned 😄

**Comment by chgad** [comment]
> You are free to do this since it is valid to add it, but it may explode in your face at a later point. you have been warned smile

Hehe, yeah, i advised him to do his work and implement "Getting the type from the Enum specs!":
