### ISSUE TITLE
OpenApiSerializerExtension is not being used to serialize target class

### ISSUE THREAD

**Issue by austin-agronick** [tfranzel/drf-spectacular#1031]
I am integrating an old project with drf-spectacular which has this py-catalog package dependency: https://github.com/jsatt/python-catalog that causes drf-spectacular to fail, unless I replace [the list hash function in plumbing.py](https://github.com/tfranzel/drf-spectacular/blob/b7f79b775205004edd05ff165523385f88308817/drf_spectacular/plumbing.py#L836) with:
```
def list_hash(lst):
    if type(next(iter(lst))).__name__ == "CatalogMember":
        for i in range(len(lst)):
            elem = lst[i]
            if not isinstance(elem, str):
                lst[i] = {
                    "name": elem.name,
                    "attributes": {
                        key: value for key, value in elem.__dict__.items() if key != "name"
                    },
                }
```
which appears to allow drf-spectacular to parse the catalog objects correctly.

I am trying to resolve this without editing the source code by instead creating a OpenApiSerializerExtension. Please let me know if there is a better way to approach this. The schema.py file which contains my OpenApiSerializerExtension is detected when drf-spectacular starts, but it does not seem to use it on catalog objects. Here is my OpenApiSerializerExtension:
```
class CatalogExtension(OpenApiSerializerExtension):
    target_class = "catalog.Catalog"
    match_subclasses = True

    def get_name(self, auto_schema, direction):
        return self.target.__name__

    def map_serializer(self, auto_schema, direction):
        component_name = self.target.__name__
        schema = {
            "type": "string",
            "enum": [member.value for member in self.target],
            "readOnly": True,
        }

        # Register sub-schemas for each catalog member
        for member in self.target:
            member_schema = ResolvedComponent(
                name=member.name,
                type=ResolvedComponent.SCHEMA,
                object=member.name,
                schema={
                    "type": "object",
                    "properties": {
                        "value": {"type": "string"},
                        "label": {"type": "string"},
                        "name": {"type": "string"},
                    },
                    "readOnly": True,
                },
            )
            auto_schema.registry.register_on_missing(member_schema)
        return schema
```

Here is an example catalog object:
```
    class TicketStatus(Catalog):
        _attrs = "value", "label"
        NEW = "new", "New"
        CLOSED = "closed", "Closed"
```

which produces this schema:
```
    TicketTicketStatusEnum:
      enum:
      - New
      - Closed
      type: string
      description: |-
        * `New` - New
        * `Closed` - Closed
```

**Comment by tfranzel** [comment]
Hi @austin-agronick,

good idea with the extension, but unfortunately the usage of catalog seems outside of that scope. The `list_hash` is used by our postprocessing hook for enums (in the hook itself and in the setting for it). I suspect this can work if you disable the hook, but it is big functionality regression imho.

Looks like the classic fickle `json.dumps`. There is no easy way to fix this. Maybe patch the catalog class so that `list(x)` returns a json serializable list by implementing `__iter__()` and returning py native values (https://stackoverflow.com/a/30554680)

**Comment by austin-agronick** [comment]
I am able to implement this __iter__ method:
```
 def __iter__(self):
        for attr, value in self.__dict__.items():
            yield attr, value
```

which allows me to convert CatalogMember objects into lists.
however, json.dumps fails with `TypeError: Object of type CatalogMember is not JSON serializable` unless I change CatalogMember to inherit from dict as show on the bottom of this page "Inheriting from dict to make class JSON serializable": https://pynative.com/make-python-class-json-serializable/
But I do not want to change the core representation of this object as a lot of code in my project uses this. As discussed in this stackoverflow post (https://stackoverflow.com/questions/3768895/how-to-make-a-class-json-serializable) the only way to do it is with various implementation that require modifying the json.dumps call. If you have a better idea of how this could be implemented that would be great but it seems like aside from modifying the library after install, the json.dumps needs to be able to accept a custom encoder or be provided a custom encoder that will default to a toJson() method or similar.

**Comment by tfranzel** [comment]
How is this class (instance) even getting into the Django/DRF stack, as they only support `list[str]` or `list[tuple[str, str]]` anyways?

Just ensure what you hand over to DRF/Django `choices` parameters are actual strings. It is a known limitation that `json.dump` does not even serialize native `datetime` objects let alone some strange custom enum class.

Sry, I cannot invest time into an abandoned library with 4 stars.

**Comment by austin-agronick** [comment]
It is a list of tuples but the json parser still identifies it as a custom class and therefor non-json serializable. I was able to monkey patch the list_hash function which is a suitable workaround for an abandoned library. Appreciate your time with helping me narrow down the possibilities. I don't see this being a problem worth adapting drf-spectacular for either.
