### ISSUE TITLE
Duplications in endpoints with GenericAPIView and Mixins

### ISSUE THREAD

**Issue by arsanysamuel** [tfranzel/drf-spectacular#1032]
**Describe the bug**
I'm having a class based view using `GenericAPIView`, `RetrieveModelMixin` and `CreateModelMixin` with get() and post() methods overriden. The swagger page has 4 endpoints for it as shown here, only the two in the green box are the expected ones:
![image](https://github.com/tfranzel/drf-spectacular/assets/26636242/1f8b4a25-7465-4092-8f92-380a3a1c2735)

It also shows this warning in the console, I've double checked that there are not any duplications and I've tried changing the `operation_id` and it shows the same warnings:
```
Warning: operationId "transactions_retrieve" has collisions [('/api/v1/transactions/', 'get'), ('/api/v1/transactions/{transaction_id}', 'get')]. resolving with numeral suffixes.
Warning: operationId "transaction_initiate" has collisions [('/api/v1/transactions/', 'post'), ('/api/v1/transactions/{transaction_id}', 'post')]. resolving with numeral suffixes.
```

**To Reproduce**
```
@extend_schema_view(
    retrieve=extend_schema(
        operation_id="transaction_retrieve",
        parameters=[
            OpenApiParameter(
                name="transaction_id",
                type=str,
                location="path",
                required=True,
            ),
        ],
    ),
    post=extend_schema(
        operation_id="transaction_initiate",
    ),
)
class TransactionView(RetrieveModelMixin, CreateModelMixin, generics.GenericAPIView):
    serializer_class = TransactionSerailizer

    def get(self, request, transaction_id: str):
        instance = get_object_or_404(Transaction, transaction_id=transaction_id)
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

    def post(self, request):
        return self.create(request)
```

**Expected behavior**
It should only show the two endpoints inside the green box in the picture above, all I know is that both the `GenericAPIView` and the mixins are providing their own implementations of get() and post() methods but I don't know if this is a normal behavior with drf-spectacular or not and how to get the desired behavior.

**Comment by tfranzel** [comment]
Hi! Your details seem not quite right. 

That `retrieve=` is doing nothing due to `ApiView` and not `Viewset` https://drf-spectacular.readthedocs.io/en/latest/faq.html#using-extend-schema-on-apiview-has-no-effect

Please make sure you are not mounting some other view. There is basically no way this schema could be generated by the view you presented alone. If you test the unwanted endpoints in the SwaggerUI, you will most likely find that they actually work.

**Comment by arsanysamuel** [comment]
@tfranzel Correct, my code isn't right sorry for that.
I replaced `retrieve=` with `get=` and it gives the same behavior, still 4 endpoints in the SwaggerUI as in the screenshot.
Could you reproduce this? Thanks.

**Comment by tfranzel** [comment]
no I could not reproduce it. It generates 2 endpiotns just as expected. Try out the unwanted endpoints in SwaggerUI. Do they `404`? If not, they are there and thus the schema is most likely correct.

I think you have another view somewhere that interferes here. Again, spectacular cannot produce those 4 endpoint from ONE `ApiView` alone.

**Comment by arsanysamuel** [comment]
I've double checked and the fault is mine.
I had this in my `urls.py`:
```
urlpatterns = [
    path("", TransactionView.as_view()),
    path("<str:transaction_id>", TransactionView.as_view()),
]
```

Sorry for this misconception, thanks for your support.
