### ISSUE TITLE
[Question] Allow any JSON / Generic freeform object

### ISSUE THREAD

**Issue by VaZark** [tfranzel/drf-spectacular#1035]
I'm setting up an API for receiving webhook. The body would vary greatly between requests. 

I'd like to define `extend_schema` to accept any data for the moment. I tried using `JSONField` but it naturally throws an error. IHowever, I did kinda succeed as it now allows any data but with the warning `Expected either a serializer or some supported override mechanism. Defaulting to generic free-form object` 

How should one define generic free-form object instead of a serializer ?

**Comment by tfranzel** [comment]
yes, a field is not a valid argument there. 

you can do `@extend_schema(responses=OpenApiTypes.OBJECT)` for example (or `OpenApiTypes.ANY` but object is likely preferable and more obvious).

https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/types.py

**Comment by VaZark** [comment]
That worked perfectly
