### ISSUE TITLE
[Question] How do i show a flattend list of single field objects as an example response

### ISSUE THREAD

**Issue by BeingBright** [tfranzel/drf-spectacular#1043]
I got a `ListCreateAPIView` that returns a flattened list of codes when a GET request is called.
```json
[
   1234,
   5678,
   9123,
   ....
]
```
I make this response by calling the values_list method on the queryset
```py
return Response(status=status.HTTP_200_OK, data=queryset.values_list("code", flat=True))
```

But the open api spec tells me that it returns the following:

```json
[
  {
    "code": 1234,
  },
  {
    "code": 5678,
  },
  {
    "code": 9123,
  },
  ....
]
```

How do i tell the open api spec that it returns the flattened list?

**Comment by tfranzel** [comment]
you need to decorate that endpoint with 

```python
@extend_schema(responses={'type': 'array', 'items': {'type': 'number'}})
```
usually you would pass a `OpenApiTypes.INT` or straight up `int`, but we do currently don't support arbitrary nested types as argument there, so the raw schema approach is the only option for lists at the moment.
