### ISSUE TITLE
[Question] Get spectacular to use custom pagination class defined in the settings

### ISSUE THREAD

**Issue by arsanysamuel** [tfranzel/drf-spectacular#1048]
**Describe the bug**
I have a this custom pagination class:
```
from rest_framework import pagination
from rest_framework.response import Response


class CustomPagination(pagination.PageNumberPagination):
    def get_paginated_response(self, data):
        return Response(
            {
                "count": self.page.paginator.count,
                "next": self.get_next_link(),
                "previous": self.get_previous_link(),
                "data": data,
            }
        )
```
That is set as the default pagination class in `settings.py` as follows:
```
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "core.pagination.CustomPagination",
    ...
```
So the response of the endpoint looks like this:
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "data": [
    ...
```
But in spectacular `OpenAPIExample` it looks like this:
```
{
  "count": 123,
  "next": "http://api.example.org/accounts/?page=4",
  "previous": "http://api.example.org/accounts/?page=2",
  "results": [
    [
```

**Expected behavior**
I wish to know how to modify this example? is there a way to make spectacular use the pagination class used in the settings?
Also how to modify the next and previous url values?

**Comment by arsanysamuel** [comment]
I've found a workaround for this, it's not clear both in spectacular and django rest framework documentation and I've figured it out from `PageNumberPagination` source code.

You can override `get_paginated_response_schema` method like this to modify the pagination examples:
```
class CustomPagination(pagination.PageNumberPagination):

    def get_paginated_response(self, data):
        return Response(
            {
                "count": self.page.paginator.count,
                "next": self.get_next_link(),
                "previous": self.get_previous_link(),
                "data": data,
            }
        )

    def get_paginated_response_schema(self, schema):
        res = super().get_paginated_response_schema(schema)
        res["properties"]["count"]["example"] = 20
        res["properties"]["next"]["example"] = f"base_url/api/v1/application/?page=4"
        res["properties"]["previous"]["example"] = f"base_url/api/v1/application/?page=2"
        res["properties"]["data"] = res["properties"]["results"]
        del res["properties"]["results"]
        return res
```

It's not the best possible solution so if anyone knows of any better solution please post it, otherwise you can close this issue @tfranzel. Thanks

**Comment by tfranzel** [comment]
Hi @arsanysamuel,

> It's not the best possible solution so if anyone knows of any better solution please post it, otherwise you can close this issue

So this was the functionality choosen by the DRF authors and I choose to utilize it instead of creating another extension class, thus duplicating functionality. I actually like that implementation and "description" live near each other. 

This is the recommended way for pagination. Fyi, other classes (auth/filter) use extensions.
