### ISSUE TITLE
AcceptHeaderVersioning isn't applied when a (non-GET) request doesn't need a serializer for input

### ISSUE THREAD

**Issue by PureTryOut** [tfranzel/drf-spectacular#1050]
**Describe the bug**
I have an endpoint which basically just executes an action, it doesn't modify an object in a REST manner. For this it doesn't need POST input, the URL parameters are enough. To document this in the OpenAPI output I set `serializer_class` to `None` (I tried using just `APIView` as the base view class as well, same result). However, no serializer being present makes Spectacular ignore the required header versioning.
The endpoint has `versioning_class = AcceptHeaderVersioning` and any request to it without the header versioning is refused by DRF as expected, but now I can't "try" the endpoint via Swagger any more.

**To Reproduce**

Make a view as follows:

```python
from rest_framework.response import Response
from rest_framework.versioning import AcceptHeaderVersioning
from rest_framework.views import APIView

class SomeView(APIView):
    versioning_class = AcceptHeaderVersioning
    def post(self, request):
        return Response()
```

That view will now be exported to Swagger without the required `Accept` header and thus always fail if executed that way (and no default API version is set).

**Expected behavior**
Spectacular to realize this endpoint still requires an `Accept` header which specifies the version of the endpoint it wants to use, even though no serializer is set.

**Comment by PureTryOut** [comment]
Actually, I see now the problem is in the responses. I have the following schema:

```python
@extend_schema(
    tags=["Orders"],
    description="Cancels an order and notifies the relevant users",
    responses={
        (303): None,
    },
)
```

I've done it this way because the endpoint executes an action and then returns a `Location` header with an endpoint to indicate the client where it should look for an update. As far as I know this is the RESTful way to do it, but extending the schema's response with `(303): None` makes it ignore the header versioning...

**Comment by PureTryOut** [comment]
Ah, this is me just not realizing how the HTTP status 303 works. 303 is also "see other" and is supposed to return a "Location" header with an url that tells the client where to look for the updated status. I was doing that part correctly, my endpoint was indeed modifying the object and then returning 303 with the correct URL, but it means the endpoint from the developer perspective returns whatever the url at the `Location` header returns. In this case a 200 response with a certain serializer.

I guess the only annoying thing here is that this endpoint now needs to know what serializer that other endpoint is using and what status it'll return. The endpoint that the client is supposed to look to is always a GET so the result will always be a 200, but the serializer might chance in future development of this product. A bit annoying that when changing that GET endpoint I also have to remember to edit the serializer on all those other endpoints, which are really unrelated.

**Comment by tfranzel** [comment]
Never really had the need to explicitly model a 30x in any of my APIs. I guess there is nothing to be done here, so I'll close the issue for now. Feel free to respond if you think something needs to be fixed here.
