### ISSUE TITLE
Proposal to further improve docstring handling

### ISSUE THREAD

**Issue by HeinrichAD** [tfranzel/drf-spectacular#1052]
Frist, thank you for the great project.

I would like to suggest to further improve the use of docstrings by parsing them. For example, by using docstring parsers like [docstring_parser](https://github.com/rr-/docstring_parser).

## Current behavior

Let assume we have the following situation:

```python
path("trainings/<str:id>/clients/", view=Training.as_view({"delete": "remove_clients"}), name="training-clients"),
```

```python
class Training(ViewSet):
    """
    Trainings endpoint `/api/trainings`.
    This endpoint is used to create and manage trainings.
    """

    ...

    def remove_clients(self, request: HttpRequest, id: str) -> HttpResponse:
        """
        Remove clients from the list of registered clients for a training.
        This is meant for modification of an already existing training process.

        Args:
            request (HttpRequest):  request object
            id (str):  training uuid

        Returns:
            HttpResponse: 200 Response if clients were removed, else corresponding error code
        """
        ...
```

Currently,the result would be the following:

<details><summary>generated yaml</summary>

```yaml
paths:
  /api/trainings/{id}/clients/:
    delete:
      operationId: trainings_clients_destroy
      description: |-
        Remove clients from the list of registered clients for a training.
        This is meant for modification of an already existing training process.

        Args:
            request (HttpRequest):  request object
            id (str):  training uuid

        Returns:
            HttpResponse: 200 Response if clients were removed, else corresponding error code
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - trainings
      responses:
        '204':
          description: No response body
```

</details>

<details><summary>swagger-ui</summary>

![current-behavior](https://github.com/tfranzel/drf-spectacular/assets/5962361/b6a5ba58-6b66-4a58-acfd-6c7f666be38c)

</details>

## Proposed behavior

I would like to propose to use a docstring parser to:
1. set the main `description` attribute (delete->description) with only the entpoint description and no further information like the arguments,
1. parse the argument information and provide these informations inside the description of the curresponding parameter,
1. maybe also set the default responses description to the text inside the docstring

Furthermore, one could think of using the class docstring as tag description.

<details><summary><del>generated</del> yaml</summary>

```yaml
tags:
  - name: trainings
    description: |-
      Trainings endpoint `/api/trainings`.
      This endpoint is used to create and manage trainings.
paths:
  /api/trainings/{id}/client:
    delete:
      operationId: trainings_clients_destroy
      description: |-
        Remove clients from the list of registered clients for a training.
        This is meant for modification of an already existing training process.
      parameters:
      - in: path
        name: id
        description: training uuid
        schema:
          type: string
        required: true
      tags:
      - trainings
      responses:
        '204':
          description: 200 Response if clients were removed, else corresponding error code
```

</details>

<details><summary>swagger-ui</summary>

![proposed-behavior](https://github.com/tfranzel/drf-spectacular/assets/5962361/44d4d75a-3b86-45ca-b071-9a8be0d7d187)

</details>

**Comment by HeinrichAD** [comment]
Hi @tfranzel. Thank you for the reply.

Here are my thoughts to your comments:

> Parsing the "semi-structured" docstrings is messy and might yield unexpected behavior if anything is formatted weirdly

There exists standards like ReST, Google, Numpydoc-style and Epydoc docstrings. But of course you are not forced to follow these standards as a developer. Nevertheless, there are many developer that follow at least one of these standards.

> That library does not look like it is accepted "consensus" as well as heavily used / battle-proven and i'm not in the business of writing parsers.

That's true and not true at the same time. Firstly, it does not have to be exectly this package. It was just a suggestion. If there is another package which fits better ... one could also look into other librarys like e.g. pdoc and learn from them. However, the disadvantage is that these are usually not ready-made libraries that can be used directly for this task.
But please note, the [docstring_parser](https://github.com/rr-/docstring_parser) package exists since 2018 and is continously maintained since then. See GitHub activities (releases/tags). Also, the pip statistics indicate quite the usage: <https://pypistats.org/packages/docstring-parser>.

> We already have a fully featured API via [decorators](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-2-extend-schema). Could we even translate all our features into the docstring? I would bet no.

I think this shoudn't be the intention. It's more like a fallback. One example would be that in most of the cases the function argument documentation is exactly the same as the parameter description inside the OpenAPI specification.

> Then, what would take precedence when docstrings and decorators are used? The mixture is gonna be messy.

Decorators are and should be the explicit case of setting the content of the OpenAPI specification. So the decorators should always be prefered. Only in the case they are not specified the docstring could be used as fallback. In that case developer with well documented code do not need to also set the same documentation inside the docstring (code documentation) and decorators (OpenAPI specification).

> I'm not that thrilled to maintain that mess. 😅

I completly understand and agree. Maybe it should be an optional feature which can be activated/deactivated. (Or if it's not to much work, maybe the user could define his/her own (callback-) functions to get the exact documentation string.)

In my optionon the main description and parameter description (of a function [docstring]) would be the main take away of this feature. For example, in my case you these two descriptions are always identical with the ones inside the decorators. Therefore the same code/documentation exists twice in my code (docstring and decorators). This is quite ugly and bad to maintain.

**Comment by HeinrichAD** [comment]
I will look into the `AutoSchema` (and [`CustomAutoSchema`](https://drf-spectacular.readthedocs.io/en/latest/blueprints.html?highlight=AutoSchema#drf-rw-serializers)). Maybe this is already the solution for my use case.

**Comment by HeinrichAD** [comment]
@tfranzel Thank you very much.
[`CustomAutoSchema`](https://drf-spectacular.readthedocs.io/en/latest/blueprints.html?highlight=AutoSchema#drf-rw-serializers) was exactly what I was searching for.

----

For documentation purpose, I solved my problem with the following code:

(Note: I purposly added the examples inside the OpenAPI entpoint description.)

<details><summary><code>CustomAutoSchema</code> Code</summary>

```python
from docstring_parser import Docstring, parse, RenderingStyle
from docstring_parser.google import compose
from drf_spectacular.openapi import AutoSchema
from inspect import cleandoc
from typing import List, Optional


class CustomAutoSchema(AutoSchema):

    show_examples = True
    rendering_style = RenderingStyle.CLEAN

    def _get_docstring(self):
        return parse(super().get_description())

    def _get_param_docstring(self, docstring: Docstring, argument: str) -> Optional[str]:
        params = [p for p in docstring.params if p.arg_name == argument]
        if not params:
            return None
        return params[0].description

    def get_description(self):
        docstring = self._get_docstring()
        tmp_docstring = Docstring(style=docstring.style)
        tmp_docstring.short_description = docstring.short_description
        tmp_docstring.long_description = docstring.long_description
        if self.show_examples:
            tmp_docstring.meta.extend(docstring.examples)
        desc = compose(tmp_docstring, self.rendering_style, indent="")
        if self.show_examples and desc.__contains__("Examples:"):
            # customize examples section:
            # - examples should be in a new paragraph (not concatenated with the description)
            # - the examples header should be a h3 title
            desc = desc.replace("\nExamples:\n", "\n\n### Examples:\n\n")
        desc = cleandoc(desc)
        return desc

    def _resolve_path_parameters(self, variables: List[str]):
        parameters = super()._resolve_path_parameters(variables)
        docstring = self._get_docstring()
        for parameter in parameters:
            if "description" not in parameter:
                description = self._get_param_docstring(docstring, parameter["name"])
                if description:
                    parameter["description"] = description
        return parameters
```

Hint: Do not forget to set your CustomAutoSchema in your settings:

```python
...
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "....CustomAutoSchema",
}
...
```

</details>

The result would be as followed:


<details><summary>Example Code</summary>

```python
class Training(ViewSet):

    def remove_clients(self, request: HttpRequest, id: str) -> HttpResponse:
        """
        Remove clients from the list of registered clients for a training.
        This is meant for modification of an already existing training process.

        Args:
            request (HttpRequest):  request object
            id (str):  training uuid

        Returns:
            HttpResponse: 200 Response if clients were removed, else corresponding error code

        Examples:
            A simple example of a request body:

            ```bash
            {
                "clients": ["<uuid1>", "<uuid2>"]
            }
            ```

            A complex example of a request body:

            ```bash
            curl -sS -X POST "<BASE_URL>/api/users/" \\
                -H "Accept: application/json" \\
                -H "Content-Type: application/json" \\
                --data-binary @- << EOF
            {
                "clients": ["<uuid1>", "<uuid2>"]
            }
            EOF
            ```
        """
        ...
```

</details>

<details><summary>generated yaml</summary>

```yaml
paths:
  /api/trainings/{id}/clients/:
    delete:
      operationId: trainings_clients_destroy
      description: |-
        Remove clients from the list of registered clients for a training.
        This is meant for modification of an already existing training process.

        ### Examples:

        A simple example of a request body:

        ```bash
        {
            "clients": ["<uuid1>", "<uuid2>"]
        }
        ```

        A complex example of a request body:

        ```bash
        curl -sS -X POST "<BASE_URL>/api/users/" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data-binary @- << EOF
        {
            "clients": ["<uuid1>", "<uuid2>"]
        }
        EOF
        ```
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: ' training uuid'
      tags:
      - trainings
      security:
      - tokenAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
```

</details>


<details><summary>swagger-ui</summary>

![swagger-ui](https://github.com/tfranzel/drf-spectacular/assets/5962361/d7311f28-a4fc-44e9-afc4-4cfa209ebe06)

</details>

**Comment by tfranzel** [comment]
Excellent @HeinrichAD, glad you found a way. I was imagining something to that effect. 

You should probably be a bit more cautious with the param, in case you have some other parameters than `id` anywhere, but I guess you are aware by now.

**Comment by HeinrichAD** [comment]
To be honest, the only thing I am aware of is that this is not working if the parameter name of the url path is different from the parameter name inside the the docstring.

This **will work**:
```python
path("trainings/<str:training_id>/clients/", view=Training.as_view({"delete": "remove_clients"}))
```
```python
def remove_clients(self, request: HttpRequest, training_id: str) -> HttpResponse:
    """
    ...
    Args:
        training_id (str):  training uuid
    """
```

This **will work**:
```python
path("trainings/<str:id>/clients/<int:n>/", view=Training.as_view({"delete": "remove_clients"}))
```
```python
def remove_clients(self, request: HttpRequest, id: str, n: int) -> HttpResponse:
    """
    ...
    Args:
        id (str):  training uuid
        n (int):   number of ...
    """
```

This **will _not_ work**:
```python
path("trainings/<str:id>/clients/", view=Training.as_view({"delete": "remove_clients"}))
```
```python
def remove_clients(self, request: HttpRequest, training_id: str) -> HttpResponse:
    """
    ...
    Args:
        training_id (str):  training uuid
    """
```

And natually it **will also _not_ work** if the variable name inside the docstring is different:
```python
path("trainings/<str:id>/clients/", view=Training.as_view({"delete": "remove_clients"}))
```
```python
def remove_clients(self, request: HttpRequest, id: str) -> HttpResponse:
    """
    ...
    Args:
        training_id (str):  training uuid
    """
```

Ugly but **will work**:
```python
path("trainings/<str:training_id>/clients/", view=Training.as_view({"delete": "remove_clients"}))
```
```python
def remove_clients(self, request: HttpRequest, id: str) -> HttpResponse:
    """
    ...
    Args:
        training_id (str):  training uuid
    """
```

Short: At least the parameter name of the django url path and the parameter name inside the dostring have to be the same.

**Comment by tfranzel** [comment]
Of course the url param name must match with the docstring (or decoration). We are not in the business of reading minds 😆 

You just need pay attention to which params you are editing. Otherwise this can work.
