### ISSUE TITLE
Unable to properly overwrite list response on ViewSets

### ISSUE THREAD

**Issue by EmilLaursen** [tfranzel/drf-spectacular#1054]
Hello, I have an issue where using `@extend_schema` and related functions to overwrite list endpoint response schemas does not work as expected.

I have a legacy API with some none standard implementation. The response structure does not match the serializer. Everything is wrapped like so:
```json
{
...
"some_meta_data_fields": "123",
"data": schema_from_serializer,
}
```
So for a list serializer, `Serializer(many=True)`, the data field would contains a list of models etc. Here is an example:
```python
from rest_framework import serializers, status, viewsets
from drf_spectacular.utils import (
    extend_schema,
    extend_schema_view,
    inline_serializer,
)
from django.db import models

class MyModel(models.Model):
    id = models.UUIDField(primary_key=True)


class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = "__all__"

custom_serializer = inline_serializer(
    name="CustomMyModel",
    fields = {"data": MyModelSerializer()}
)

custom_list_serializer = inline_serializer(
    name="CustomMyModelList",
    fields = {"data": MyModelSerializer(many=True)}
)

@extend_schema_view(
    list=extend_schema(responses=custom_list_serializer),
)
@extend_schema(
    responses=custom_serializer,
)
class MyModelViewSet(viewsets.ModelViewSet):
    queryset = MyModel.objects.all()
    serializer_class = MyModelSerializer
```

Which generates the following schema for the list endpoint: 
```yaml
  /api/mymodel/:
    get:
      operationId: mymodel_list
      tags:
      - mymodel
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomMyModelList'
          description: ''
```
The issue is the `CustomMyModelList` is embedded in an array. What I expect is this:
```yaml
  /api/mymodel/:
    get:
      operationId: mymodel_list
      tags:
      - mymodel
      responses:
        '200':          
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomMyModelList'
```
Looking at the source, it seems to happen here: https://github.com/tfranzel/drf-spectacular/blob/afe8b3b38945107a3bc389eefad41d83251a990e/drf_spectacular/openapi.py#L1444

I have tried to use `OpenApiSerializerExtension` in different ways to circumvent this branch, but have been unsuccesful.

**Comment by EmilLaursen** [comment]
Thank you very much! I had tried `extend_schema_serializer` but I applied it to the viewset class, which does not have the desired effect.
Following the example in the FAQ works well. For reference this change to the example code fixes the issue:
```python
custom_list_serializer = extend_schema_serializer(many=False)(
    inline_serializer(
        name="CustomMyModelList", fields={"data": MyModelSerializer(many=True)}
    )
)
```
Also, apologies for not reading the FAQ.

**Comment by tfranzel** [comment]
> Also, apologies for not reading the FAQ.

no worries, it is tricky to find the right entry without the right search terms

> I had tried extend_schema_serializer but I applied it to the viewset class, which does not have the desired effect.

well, it has "serializer" in the name, and the first line of the docstring says: "Decorator for the "serializer" kind. Intended for overriding default serializer behaviour that  cannot be influenced through :func:`@extend_schema <.extend_schema>`." :smile:
