### ISSUE TITLE
Referencing class before the class has been completely defined in extend_schema_field

### ISSUE THREAD

**Issue by kahkeong** [tfranzel/drf-spectacular#1057]
Hi, thanks for creating this package! Currently. Im having issue declaring schema for some of my serializers. Im trying to achieve something as below but at the moment it is not working as SerializerA is not fully defined yet when the decorator is being evaluated.
```
class A(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=255)
    parent_from = models.ForeignKey(
        "A",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="child_items",
    )

class SerializerA(serializers.ModelSerializer):
    child_items = serializers.SerializerMethodField() 

    class Meta:
        model = A
        fields = ['price', 'name', 'child_items']  

    @extend_schema_field(SerializerA(many=True))
    def get_child_items(self, obj):
        return SerializerA(obj.child_items.all(), many=True).data
```

Currently, this is the solution Im using

```
class A(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=255)
    parent_from = models.ForeignKey(
        "A",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="child_items",
    )

class SerializerA1(serializers.ModelSerializer):
    class Meta:
        model = A
        fields = ['price', 'name']  

class SerializerA(serializers.ModelSerializer):
    child_items = SerializerA1(many=True) 

    class Meta:
        model = A
        fields = ['price', 'name', 'child_items']  

```
Im wondering is there a better solution out there that can support my use case without me duplicating the serializer ?  Maybe delay the evaluation by allowing lambda expression within extend_schema_field decorator like below.

```
class A(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=255)
    parent_from = models.ForeignKey(
        "A",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="child_items",
    )

class SerializerA(serializers.ModelSerializer):
    child_items = serializers.SerializerMethodField() 

    class Meta:
        model = A
        fields = ['price', 'name', 'child_items']  

    @extend_schema_field(lambda: SerializerA(many=True))
    def get_child_items(self, obj):
        return SerializerA(obj.child_items.all(), many=True).data
```

**Comment by tfranzel** [comment]
Had that circular dep problem in a different situation and wrote a helper for it.

usage:

https://github.com/tfranzel/drf-spectacular/blob/afe8b3b38945107a3bc389eefad41d83251a990e/tests/contrib/test_rest_polymorphic.py#L44

helper (`from drf_spectacular.helpers import lazy_serializer`):

https://github.com/tfranzel/drf-spectacular/blob/afe8b3b38945107a3bc389eefad41d83251a990e/drf_spectacular/helpers.py#L4

I think that should work here too. Let me know

> Maybe delay the evaluation by allowing lambda expression within extend_schema_field decorator like below.

not sure from the top of my head if that interferes with other functionality. Check out above solution first, then we can look further.

**Comment by kahkeong** [comment]
thanks ! Im able to get it work with lazy_serializer.

**Comment by tfranzel** [comment]
awesome. note that you should be able to do 

```python
lazy_serializer('tests.contrib.test_rest_polymorphic.LegalPersonSerializer')(many=True)
```
as you written there. The init should still be delayed properly.
