### ISSUE TITLE
AcceptHeaderVersioning can't be used on endpoints that don't accept or return values

### ISSUE THREAD

**Issue by PureTryOut** [tfranzel/drf-spectacular#1058]
**Describe the bug**
We have an endpoint that currently accepts no JSON body, nor does it return one. It just uses some path parameters (e.g. `/api/users/<id>/is-something-allowed`) and returns an HTTP status, the specific status indicating the result of the call.

We currently can't call this endpoint from the hosted Swagger view as the schema for some reason doesn't indicate the `Accept` header is required, so Swagger doesn't set it and the call fails with a 406. I kind of understand that this happens, the endpoint doesn't require JSON so the `application/json` content type isn't set and just `version=v1` in the `Accept` header isn't valid HTTP, however if I call the endpoint with `application/json; version=v1` anyway using e.g. curl the request goes through fine and is executed properly. I'd probably make the schema indicate the `Accept` header is required anyway even if the content-type would be wrong.

**To Reproduce**
```python
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView


class SomeView(APIView):
    def get(self, request, *args, **kwargs):
        return Response(status=status.HTTP_200_OK)
```

Make sure the versioning scheme used is `AcceptHeaderVersioning` and no default API version has been set.

**Expected behavior**
The `Accept` header to be required according to the exported scheme so Swagger picks it up and sets the version parameter properly.

**Comment by tfranzel** [comment]
That is interesting. not sure how to solve this given the structural restrictions imposed on us by OpenAPI.

So the version is encoded into the `accept` "key" (special headers are not allowed as explicitly listed parameters btw)

You can skip the encoding and just provide `version=v1`, which will be properly used by SwaggerUI. However, the actual problem then is that you need `schema` under it and there is no empty formulation for this, as "empty" is signaled by it missing. When you do `schema: {}` you basically say "anything allowed", which SwaggerUI represents as a string. Not the best solution either.

So as of now, I'm unsure how to properly translate this case into a OpenAPI 3.0.3 schema. Looks like a chicken-egg problem. 

Try it yourself with:

https://editor-next.swagger.io/

```yaml
openapi: 3.0.3
info:
  title: 'test'
  version: 0.0.0
paths:
  /test/:
    post:
      operationId: test
      requestBody:
        content:
          application/json; version=v2:
            schema: {}
      responses:
        '201':
          content:
            application/json; version=v2:
              schema: {}
          description: ''
```
