### ISSUE TITLE
`lookup_field="pk"` shows up as `id` on the schema

### ISSUE THREAD

**Issue by MariaMozgunova** [tfranzel/drf-spectacular#1059]
The `lookup_field` parameter for the viewset inherited from `GenericAPIView` is set to the default value of `pk`. Then, in the OpenAPI schema, the path parameter is shown as `id`:
```
  "in": "path",
  "name": "id",
  "schema": {
      "type": "integer"
  }
```
But requests with the `id` parameter do not work, only the `pk` path parameter works.

I know I can set `parameters=[OpenApiParameter("pk", int, OpenApiParameter.PATH)]` for each view. Is there some other way to specify the path parameter for the whole viewset?

When I explicitly set `lookup_field="some_other_value"`, it is shown in the OpenAPI schema.
So looks like `pk` is coerced to `id`, but the parameter should be named `pk`.

**Comment by tfranzel** [comment]
that makes no sense. the backend cannot distinguish `/persons/<pk>/` from `/persons/<id>`, because request never uses the actual name in case of path parameters, e.g. `/persons/234523433`

**Comment by MariaMozgunova** [comment]
I mean what doesn't work is calling the `django.urls.reverse` with the `id` parameter. `reverse` works only with `pk`: reverse("view-name", kwargs={"pk": instance.pk}).

Is it possible for the OpenAPI schema to list `pk` instead of `id`?

**Comment by tfranzel** [comment]
I see. This is actually a functionality inherited from DRF so this is one of the few settings we pull from `REST_FRAMEWORK`. It is named `SCHEMA_COERCE_PATH_PK`. Set it to false to disable coersion to `id`

**Comment by MariaMozgunova** [comment]
I now understand, thank you for the explanation. I will close the issue.
