### ISSUE TITLE
Document OpenApiAuthenticationExtension `priority` property

### ISSUE THREAD

**Issue by savitmk** [tfranzel/drf-spectacular#106]
I have subclassed `OpenApiAuthenticationExtension` to document an authentication class which subclasses `rest_framework.authentication.TokenAuthentication`.

Because there is an existing authentication extension for `TokenAuthentication` in this codebase - https://github.com/tfranzel/drf-spectacular/blob/fcee218876c4ae4a700cceb09fe3dfaf01238817/drf_spectacular/authentication.py#L27 - there are multiple matches here - https://github.com/tfranzel/drf-spectacular/blob/fcee218876c4ae4a700cceb09fe3dfaf01238817/drf_spectacular/plumbing.py#L506 

It is not documented - https://drf-spectacular.readthedocs.io/en/latest/customization.html#specify-authentication-with-openapiauthenticationextension - that user authentication extensions which conflict with this library's authentication extensions require setting a higher priority.

Alternatively/additionally, the default priority could be 0 while this library's authentication extensions have a negative priority, so that as a user writing an authentication extension, my extension would be preferred _by default_.

Thank you again!

**Comment by tfranzel** [comment]
that should do it. though if subclassing the built-in extensions, you still need to raise the ``-1``. added a info box to the doc for that.
