### ISSUE TITLE
make the list single

### ISSUE THREAD

**Issue by stanhjr** [tfranzel/drf-spectacular#1064]
**Describe the bug**
I want the list viewset method to return one object, it's easy to do, but how can I explain the spectular so that it generates the correct documentation?

I did this, it returns one object in the response, but the swagger shows a list

  @extend_schema(responses=WidgetSettingsSerializer(many=False))
  def list(self, request: Request, *args, **kwargs) -> Response:
      serializer = self.get_serializer(self.get_queryset(), many=False)
      return Response(serializer.data)

or is this impossible and I am forced to do the action?

**Comment by tfranzel** [comment]
Since this keeps coming up, I created a helper function for it. I theory it is also possible to do yourself with `type` and `extend_schema_serializer`, but that creates a warning you cannot simply get rid of.

Also added a new FAQ entry on how to use it.

**Comment by stanhjr** [comment]
thank you very much, this solves my problem
