### ISSUE TITLE
Hi, How are the fields of the uploaded file represented on the interface document

### ISSUE THREAD

**Issue by Cloverxue** [tfranzel/drf-spectacular#1066]
**Describe the bug**

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

**Expected behavior**

**Comment by tfranzel** [comment]
Your question is not clear at all. Please try to come up with a better formulation.

**Comment by Cloverxue** [comment]
Hi, I want to display the field of this uploaded file in request body, what should I do to reflect it in the interface document? Is there such a field type
![1693469083703](https://github.com/tfranzel/drf-spectacular/assets/47838275/a15f0a8b-f4e1-4267-ae96-7c42cb6d1128)

**Comment by Cloverxue** [comment]
I have not find the field type,
![image](https://github.com/tfranzel/drf-spectacular/assets/47838275/aae68fae-6b85-4b50-b965-56da58e28473)

**Comment by Cloverxue** [comment]
![image](https://github.com/tfranzel/drf-spectacular/assets/47838275/40674628-cfc7-490f-adb2-bf8e6fcd8f3a)
![image](https://github.com/tfranzel/drf-spectacular/assets/47838275/30a52a02-14b9-48f0-a142-2e894a505a9c)
tap the 'try it out' , the file field can get this file automatically?

**Comment by Cloverxue** [comment]
Hi @tfranzel

**Comment by tfranzel** [comment]
you cannot represent fields in a file. all you can do is using `"COMPONENT_SPLIT_REQUEST": True` and have the file(field) as `binary`. I'm pretty sure OpenAPI does not support providing a schema for uploaded files.

**Comment by Cloverxue** [comment]
![image](https://github.com/tfranzel/drf-spectacular/assets/47838275/6334efaf-1108-4e5f-808e-d05f21cf86f8)
Hi @tfranzel  What kind of effect can it(the '"COMPONENT_SPLIT_REQUEST": True' ) produce? How is it different from what is written in the document

**Comment by Cloverxue** [comment]
In addition, I would like to ask, does it mean that it is effective for drf_spectacular, and will not affect the orther function of rest_framework and django?

**Comment by tfranzel** [comment]
https://drf-spectacular.readthedocs.io/en/latest/faq.html?highlight=COMPONENT_SPLIT_REQUEST#filefield-imagefield-is-not-handled-properly-in-the-schema
https://drf-spectacular.readthedocs.io/en/latest/settings.html?highlight=COMPONENT_SPLIT_REQUEST#settings

> In addition, I would like to ask, does it mean that it('COMPONENT_SPLIT_REQUEST': True) is effective for drf_spectacular, and will not affect the orther function of rest_framework and django?

Nothing we do factually changes DRF or Django. It is all presentation.
