### ISSUE TITLE
Cannot generate interface documentation for viewsets specific interface when “”versioning_class = NamespaceVersioning” is added to view

### ISSUE THREAD

**Issue by Cloverxue** [tfranzel/drf-spectacular#1068]
**Describe the bug**
Cannot generate interface documentation for viewsets specific interface when “”versioning_class = NamespaceVersioning” is added to view
The interface document for MyViewSet disappears when adding “versioning_class = NamespaceVersioning” to MyViewSet，
for example:
from rest_framework.versioning import NamespaceVersioning
class MyViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
    versioning_class = NamespaceVersioning

**To Reproduce**
A:
class MyViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
   pass
B:
class MyViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
    versioning_class = NamespaceVersioning
A can generate interface documents normally, but  B cannot

**Expected behavior**
Expect normal interface documentation to be generated

**Comment by Cloverxue** [comment]
url('^api-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
 url('^api-doc/', SpectacularRedocView.as_view(url_name='schema'), name='swagger-doc'),
The corresponding interface(versioning_class = NamespaceVersioning) cannot be found when opened using this two url

**Comment by tfranzel** [comment]
https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-get-an-empty-schema-or-endpoints-are-missing

you can do hardcode which version (as explained above) or give a parameter `...../api-ui/?version=v1`

**Comment by Cloverxue** [comment]
Hi ,./manage.py spectacular --api-version 'YOUR_VERSION' can generate interface documents normally, but 
url('^api-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
url('^api-doc/', SpectacularRedocView.as_view(url_name='schema'), name='swagger-doc'),
The corresponding interface(versioning_class = NamespaceVersioning) cannot be found when opened using this two url

**Comment by Cloverxue** [comment]
Ok, it's fine, thank you very much!
