### ISSUE TITLE
Add support for Stoplight Elements

### ISSUE THREAD

**Issue by browniebroke** [tfranzel/drf-spectacular#1073]
This project can already generate docs using Swagger or Redoc. Would it make sense to also add support for [Stoplight Elements](https://stoplight-site.webflow.io/open-source/elements)? 

You can see it in action here: https://elements-demo.stoplight.io/ 

Has anyone done anything around that? Would it be a welcome addition?

**Comment by tfranzel** [comment]
You can generate elements too. We just support the 2 most popular UIs officially, but it is easy to add others:

https://drf-spectacular.readthedocs.io/en/latest/blueprints.html#elements

**Comment by browniebroke** [comment]
Nice! I didn't realise it was documented. Must have not searched hard enough, apologies.
