### ISSUE TITLE
PyJWT Bearer token authentication is not working with drf-spectacular

### ISSUE THREAD

**Issue by rajutechie** [tfranzel/drf-spectacular#1076]
I am using PyJWT for bearer token Auth in my Django project, CustomAuthSchema is not working for PyJWT with drf-spectacular. How to integrate bearer token auth in DRF-Speculator swagger for PyJWT?

PyJWT==2.8.0
drf-spectacular==0.26.4
drf-spectacular-sidecar==2023.9.1
Django==4.2.5
djangorestframework==3.14.0

**Comment by tfranzel** [comment]
Please show your CustomAuthSchema? What is your authentication class? your extension needs to refer to that authentication class.

Have you followed https://drf-spectacular.readthedocs.io/en/latest/customization.html#specify-authentication-with-openapiauthenticationextension ?

**Comment by rajutechie** [comment]
Thank you, the above link resolved my problem.
