### ISSUE TITLE
These three interfaces are accessible in a development environment, but not in an environment deployed through docker

### ISSUE THREAD

**Issue by Cloverxue** [tfranzel/drf-spectacular#1077]
**Describe the bug**
swagger_url = [
        url('^schema/', SpectacularAPIView.as_view(api_version='v1'), name='schema'),
        url('^api-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
        url('^api-doc/', SpectacularRedocView.as_view(url_name='schema'), name='swagger-doc'),
    ]
These three interfaces are accessible in a development environment, but not in an environment deployed through docker

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

**Expected behavior**
Expect normal access to all three interfaces

**Comment by Cloverxue** [comment]
![1695031541753](https://github.com/tfranzel/drf-spectacular/assets/47838275/8366dea9-8041-4fad-ad19-497b53c83db7)
tab f12, and ut have not response

**Comment by tfranzel** [comment]
it is your responsibility to have the proper settings inside your docker container too. same goes for your proxy settings.

**Comment by Cloverxue** [comment]
oh, But my backend server log returned 200, How should I set it up? Is there a case link you can send me for reference,

**Comment by Cloverxue** [comment]
![1695032069511](https://github.com/tfranzel/drf-spectacular/assets/47838275/b63785b7-9cdb-41ac-a607-2fbef316b009)

**Comment by tfranzel** [comment]
@Cloverxue please learn how to write proper github issues. Our issue template is there for a reason. It is impossible to give you feedback with the given information.
**This is not StackOverflow**. 

For the future:

- Take your time and write 1 self-contained post!
- Don't post 1 sentence every 10 minutes
- Use proper github code formatting
- Provide a reproduction **or** at the very least write a very detailed tracing of the issue. Not just useless screenshots.
