### ISSUE TITLE
Format nullable object body parameter represented by nested serializer

### ISSUE THREAD

**Issue by schew2381** [tfranzel/drf-spectacular#1078]
**Describe the bug**
I'm trying to generate an OpenAPI request body by using serializers in the `request=` kwarg of the `@extend_schema` decorator. I'd like to generate a body parameter that represents a nullable object with a description attached to it. The field should look like:
```JSON
"schema":{
    "type":"object",
    "properties":{
        "rateLimit":{
            "type":"object",
            "description":"Some text.",
            "properties":{
                "count":{
                    "type":"integer",
                    "minimum":0,
                    "nullable":true
                },
                "window":{
                    "type":"integer",
                    "maximum":86400,
                    "minimum":0,
                    "nullable":true
                }
            },
            "nullable":true
        }
    }
}
```
To represent the body param as an object, I tried using a nested serializer like so:
```Python
class RateLimitSerializer(serializers.Serializer):
    """
    Some text.
    """
    count = serializers.IntegerField(min_value=0, required=False, allow_null=True)
    window = serializers.IntegerField(min_value=0, required=False, allow_null=True)

class KeySerializer(serializers.Serializer):
    rateLimit = RateLimitSerializer(
        required=False,
        allow_null=True,
    )
```
However, having instantiating RateLimitSerializer with `allow_null=True` leads to the `rateLimit` parameter being formatted as an `allOf` field for some reason
```JSON
"rateLimit":{
    "allOf":[
        {
            "type":"object",
            "description":"Some text.",
            "properties":{
                "count":{
                    "type":"integer",
                    "minimum":0,
                    "nullable":true
                },
                "window":{
                    "type":"integer",
                    "maximum":86400,
                    "minimum":0,
                    "nullable":true
                }
            }
        }
    ],
    "nullable":true
}
```
The nullable is also outside the `allOf`. When I exclude `allow_null=True`, the JSON is rendered as expected minus the nullable of course.

**To Reproduce**
Build the JSON based on the following code, and also try without`allow_null=True` when instantiating the `ChildSerializer`
```Python
from drf_spectacular.utils import extend_schema
from rest_framework import serializers

class ChildSerializer(serializers.Serializer):
   test = serializers.IntegerField(required=False, allow_null=True)

class BaseSerializer(serializers.Serializer):
    someField = ChildSerializer(allow_null=True)
    
@extend_schema(operation_id="Bug", parameters=[], request=BaseSerializer, responses=None)
def put():
    pass
```

**Comment by tfranzel** [comment]
Hi @schew2381 

> However, having instantiating RateLimitSerializer with allow_null=True leads to the rateLimit parameter being formatted as an allOf field for some reason

This is done for practical reasons. 

```python
{
     'someField': {
         'allOf': [{'$ref': '#/components/schemas/Child'}], 
         'nullable': True
    }
}
```

without the `allOf`, the `$ref` expansion will wipe out the scope in which it is located, essentially removing the `nullable`. This construction is to prevent that by opening another nested scope. Without `allow_null=True`, this wrapping is not needed, as there is nothing to wipe out (only a `$ref` and nothing else), and so it is not applied.

Also there is only one location where to put the `nullable` (next to `someField`). Anywhere else would be wrong.

Is there a reason you don't want that? Is something broken because of it, or is it just "looks"?

**Comment by schew2381** [comment]
Thanks for the fast reply! We had an issue with our internal docs tool displaying the body param, but if the behavior is expected then we'll fix it on our end :thumbsup:

**Comment by tfranzel** [comment]
Yes, it is actually the recommended and only way to model this properly. You are in good company though, it is a common issue in OpenAPI implementations if you google `allOf` and `nullable`.
