### ISSUE TITLE
API readability

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#108]
Following on from the docstring issues (https://github.com/tfranzel/drf-spectacular/issues/107), a fun new direction would be to measure the readability of the docstrings, and similarity among the docstrings esp. if duplicates are not rejected.

https://github.com/cdimascio/py-readability-metrics is nice, but I would want to guard it with a check to see if the data files already exist, and obviously dont fail if missing.  i18n/l10n issues abound, but that just makes life interesting.

I would expect this to be implemented as a [`checks.py`](https://docs.djangoproject.com/en/3.0/topics/checks/), probably able to be entirely disabled with a setting.

A spectacular API is more than just endpoints and field classes.  The `description` are what makes it truely 'spectacular' :p

**Comment by tfranzel** [comment]
not a bad idea at all. since this mainly cosmetics and may be only of interest to some i would prefer it as a blueprint. PR welcome

**Comment by tfranzel** [comment]
this looks stale. if you have a something for a blueprint please feel free to create a PR.
