### ISSUE TITLE
Schema is not Generated for ListAPIView filterset_class 

### ISSUE THREAD

**Issue by iamMHZ** [tfranzel/drf-spectacular#1086]
**Describe the bug**
Schema for the `filterset_class` of a `ListAPIView` is not generated.

**To Reproduce**
Add `filterset_class` to a `ListAPIView` and open the swagger URL, then you see that schema is not generated for filters.

**Comment by tfranzel** [comment]
cannot reproduce. works as expected for me when declared as required. please provide a reproduction.

**Comment by tfranzel** [comment]
the added test in [f7f75a9](https://github.com/tfranzel/drf-spectacular/commit/f7f75a9671aa12a97f19005a5b81f80c3947ee26) proves that this works as expected. I suspect that you forgot to add `filter_backends`. feel free to follow up with a reproduction.
