### ISSUE TITLE
There's a way to add a main description to a section on API documentation?

### ISSUE THREAD

**Issue by vancasti** [tfranzel/drf-spectacular#1089]
**Describe the bug**
I want to include a description text bellow the main title of each section on the API documentation generated with the library. 

**To Reproduce**
I've tried to use different parameters with the tag **extend_schema** as I see in the library documentation. Using the tag **extend_schema_view** description only allows to include a text description for each API endpoint but not in the upper level.

**Expected behavior**
In case that the library doesn't offer this function, I'd like to propose to include a new parameter to cover this necessity. 

![Captura de pantalla 2023-10-18 a las 15 02 19](https://github.com/tfranzel/drf-spectacular/assets/4975494/fb51cd74-ba8e-4236-8000-50aab14f07ba)

**Comment by tfranzel** [comment]
that screenshot does not have enough context. what UI is that? which UI segment? 

where should this description string be represented in the schema?

if i understand your question correctly, the [path object](https://spec.openapis.org/oas/v3.0.3#paths-object) itself has no overarching description string, only each individual item (e.g. "brand card list")

**Comment by vancasti** [comment]
![Captura de pantalla 2023-10-18 a las 15 44 02](https://github.com/tfranzel/drf-spectacular/assets/4975494/7276a65c-9ac8-40ac-a1a6-3ac59c829b23)
The UI is an API documentation with redocs. 
Could you see better now? I only want to include a description bellow the main title of each section... there's a way to do that o currently it is impossible?

**Comment by tfranzel** [comment]
ahh I see.... those string to not come directly from the operation/path objects, but rather from added global tags. so `@extend_schema` is the wrong tool. It is in the global settings.

You can reproduce this by setting our setting `TAGS`. Just make sure the auto-generated tag name in the operation matches your hand-written tag name in the global section.

https://github.com/Redocly/redoc/blob/main/demo/swagger.yaml#L54

https://github.com/tfranzel/drf-spectacular/blob/c68d3b21242e073f0a05e661c7d3218ecd0f44a7/drf_spectacular/settings.py#L194-L195

https://github.com/tfranzel/drf-spectacular/blob/c68d3b21242e073f0a05e661c7d3218ecd0f44a7/tests/test_meta.py#L31-L34

**Comment by vancasti** [comment]
Thank you for your attention! I've resolved the problem :)
