### ISSUE TITLE
Unclear in docs how to include example values for redoc view left 

### ISSUE THREAD

**Issue by dashdanw** [tfranzel/drf-spectacular#1091]
In redoc view, the documentation includes a number of different example values for things like `email` and `uuid`, it would be nice to be able to simply provide values for items such as phone numbers (ie `+15555555555`) and names (ie `first_name: John`, `last_name: Doe`).

working example:
![image](https://github.com/tfranzel/drf-spectacular/assets/1347347/be33c109-db2c-4d4a-bb5c-b86114d143e3)

via 
![image](https://github.com/tfranzel/drf-spectacular/assets/1347347/a2dcb87f-88e9-4f0a-8ed4-8c3600464ab6)

as it stands if I defined a field ie.
```python
phone_number = serializers.CharField(max_length=10)
```
there is no clear way to define a sample value ie.
```json
{
  "phone_number": "+15555555555"
}
```
and it will instead show as something like 
```json
{
 "phone_number": "string"
}
```

**Comment by Kangaroux** [comment]
Is this the same as #1018

**Comment by tfranzel** [comment]
Sry this kind of fell of the waggon. I don't think it is possible to provide singular examples for individual serializer fields for several reasons:

1. DRF does not allow to add "unknown" extra parameters to serializer fields. I tried that, it just bails. So no chance injecting an `example` parameter there.
2. It is very awkward decorating `phone_number = serializers.CharField(max_length=10)`

OpenAPI does allow for individual field examples, but we have not good way of providing it in DRF. For that reasons we opted for 2 approaches. Either decorate the serializer or the endpoint with a full example for the whole serializer/endpoint. That way, SwaggerUI should make use of it.

https://github.com/tfranzel/drf-spectacular/blob/b65ae61c748710b86304ad83dfddfe76f24649ee/tests/test_examples.py#L47-L62

or view (or endpoint like list/retrieve)

https://github.com/tfranzel/drf-spectacular/blob/b65ae61c748710b86304ad83dfddfe76f24649ee/tests/test_examples.py#L188-L196

But I suppose the serializer route would be better in terms of reusability in this context.

**Comment by dashdanw** [comment]
Just as an aside, in using the `extend_schema_serializer` decorator, it does not seems like the examples on the right hand side are affected, for instance

```@extend_schema_serializer(
    examples=[
        OpenApiExample(
            "Serializer C Example RO",
            value={"some_field": "cba"},
            response_only=True,
        ),
        OpenApiExample(
            "Serializer C Example WO",
            value={"some_field": "abc"},
            request_only=True,
        ),
    ],
)
class SomeSerializer(serializers.Serializer):
    some_field = serializers.CharField()
    ...
```
the example still shows only the fields parsed automatically and does not include the specified examples?

**Comment by tfranzel** [comment]
@dashdanw 

>  it does not seems like the examples on the right hand side are affected, for instance

what do you mean? not sure what right hand side means.

> the example still shows only the fields parsed automatically and does not include the specified examples?

not sure what you mean here either. proving an example to the serializer will make it show up on the endpoint for me.

```python
@extend_schema_serializer(
    examples=[
        OpenApiExample('XXX', value={'field': 11,'phone_number': "+123 555 3333" }),
    ]
)
class BSerializer(serializers.Serializer):
    field = serializers.IntegerField()
    phone_number = serializers.CharField(max_length=10)

...
    @extend_schema(request=BSerializer, responses=BSerializer)
    def create(self, request, *args, **kwargs):
        super().create(request, *args, **kwargs)  # pragma: no cover
```

<img width="670" alt="Screenshot 2024-02-24 at 01 17 52" src="https://github.com/tfranzel/drf-spectacular/assets/13507857/9eb43f46-1120-41b5-943c-8fc8fb3bc71c">

**Comment by dashdanw** [comment]
> what do you mean? not sure what right hand side means.
sorry, to be more clear, the examples on the right hand side for redoc do not show details added with `extend_schema_serializer` when the serializer in question is set as a field

ie.
```
@extend_schema_serializer(...)
class SomethingSerializer(serializers.Serializer):
    ...

class SomethingResponseSerializer(serializers.Serializer):
    somethings = SomethingSerializer(many=True)
    ...
```

it also does not seem to work to decorate a field declared as a class with `extend_schema_field`

ie.
```
@extend_schema_field(...):
class SomeField(serializers.Field):
    ...
```

**Comment by dashdanw** [comment]
So we ended up figuring out a fairly decent solution to providing examples for a serializer class by using `build_basic_type`

example
```python
@extend_schema_field(
    dict(
        example=100,
        **build_basic_type(int),
    )
)
class CustomIntegerField(...):
   pass
```
this actually works fairly well for our use-cases, happy to close the ticket (I think I have another ticket open that's extremely similar as well)

**Comment by tfranzel** [comment]
Glad it worked for you! That is an interesting usage of the the raw schema feature. 😲 😄 

The reason, if I remember correctly, for not supporting "singular field example" is that we have a derivation/override logic for example lists just as `@extend_schema` does. Supporting this on top would have exploded the complexity of parsing it and thus we refrained from adding this seemingly trivial feature.
