### ISSUE TITLE
JSONField uses dict schema but can be any json primitive

### ISSUE THREAD

**Issue by Kangaroux** [tfranzel/drf-spectacular#1095]
**Describe the bug**
When using a `JSONField` in the serializer, the generated schema is for an object. However, [DRF](https://www.django-rest-framework.org/api-guide/fields/#jsonfield) describes it as being any json primitive: strings, numbers, booleans, etc. The current implementation seems more appropriate for [DictField](https://www.django-rest-framework.org/api-guide/fields/#dictfield), not JSONField

**To Reproduce**
```python
from rest_framework import serializers

class MySerializer(serializers.Serializer):
  json_field = serializers.JSONField()
```

**Expected behavior**
The generated type should be `OpenApiTypes.ANY`.

**Comment by tfranzel** [comment]
excellent point, a string or number would be possible too.
