### ISSUE TITLE
How to append extra serializer to resulting swagger file?

### ISSUE THREAD

**Issue by mintyPT** [tfranzel/drf-spectacular#1097]
I've looked for a big and tried a couple of things. When so far as to start looking into the component registry but did not find what I needed:

Without going into details, I have a serializer that I'd like to add to my swagger file. This serializer is not and will not be connected to any view.

So, how do I take a serializer, convert it to a schema, and append it to the resulting swagger?

**Comment by tfranzel** [comment]
Sounds weird and is almost certainly a sign of bad design but I digress. 

Postprocessing hooks are the way to go. Unfortunately, the processing scope is gone at that point in time, so you need to create a dummy view that allows you to run the machinery again.

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks

```python
from drf_spectacular.settings import spectacular_settings

class ZSerializer(serializers.Serializer):
    foo = serializers.IntegerField()

def custom_postprocessing_hook(generator, result, **kwargs):
    mock_view = build_mocked_view("GET", '/DUMMY', extend_schema(), generator.registry)

    for direction in ["request", "response"]:
        component = mock_view.schema.resolve_serializer(ZSerializer, direction)
        generator.registry.register_on_missing(component)

    result['components'] = generator.registry.build(spectacular_settings.APPEND_COMPONENTS)
    return result
```

**Comment by mintyPT** [comment]
> Sounds weird and is almost certainly a sign of bad design but I digress.

No arguments there. You are right but as always every story has nuance. The reason why I need to add it to swagger is because I generate ts types from my swagger file to use in the frontend so for a particular situation, I need to add this extra serializer because in the frontend the data comes from a non drf endpoint. 

btw, yesterday I kept at it and here's what I ended up doing



```python
# If you need to add an extra serializer to the swagger so you can generate
# types for it, add it here.
EXTRA_SERIALIZERS_TO_INCLUDE = [
    "xxx.ZSerializer"
]


def _hash(cls):
    return hashlib.md5(cls.encode("utf-8")).hexdigest()

def extra_serializers_preprocessing_hook(endpoints: list[Any]) -> list[Any]:
    for cls in EXTRA_SERIALIZERS_TO_INCLUDE:
        slug = _hash(cls)
        s = import_string(cls)

        class View(RetrieveAPIView):
            serializer_class = s

        endpoints.append((f"/{slug}", slug, "GET", View.as_view()))
    return endpoints


def extra_serializers_postprocessing_hook(
    result: dict, generator: SchemaGenerator, request: HttpRequest, public: bool
):
    for cls in EXTRA_SERIALIZERS_TO_INCLUDE:
        slug = _hash(cls)
        del result["paths"][f"/{slug}"]
    return result

```

**Comment by tfranzel** [comment]
> No arguments there. You are right but as always every story has nuance. The reason why I need to add it to swagger is because I generate ts types from my swagger file to use in the frontend so for a particular situation, I need to add this extra serializer because in the frontend the data comes from a non drf endpoint.

I assumed something of the sort

ahh that works too but is a bit more involved. glad that it worked out.
