### ISSUE TITLE
Pydantic extension blueprint produces empty schema for models

### ISSUE THREAD

**Issue by devanubis** [tfranzel/drf-spectacular#1105]
**Describe the bug**
I've followed #1006  and tried using [the extension blueprint for Pydantic 2](https://drf-spectacular.readthedocs.io/en/latest/blueprints.html#pydantic) to generate a schema for some pydantic models we use (as both request and response objects).

But the resultant object definitions in swagger are just an object name and then an empty definition:

```
C{
}
```
But the actual YAML schema does appear to include the properties:
```yaml
components:
  schemas:
    C:
      $defs:
        C:
          properties:
            id:
              title: Id
              type: integer
            b:
              $ref: '#/components/schemas'
            d:
              $ref: '#/components/schemas'
          required:
          - id
          - b
          - d
          title: C
          type: object
      allOf:
      - $ref: '#/components/schemas'
```

**To Reproduce**
I used the example test model and view from [this comment](https://github.com/tfranzel/drf-spectacular/issues/1006#issuecomment-1598961285).

The example generated is just
```
"string"
```
And the object schema definition is just:
```
C{
}
```

**Expected behavior**

I'd expect to see the fields from the pydantic model `C`, ideally working with nested pydantic models.

**Comment by devanubis** [comment]
I also noticed that the blueprint extension isn't hit if I use:

```python
    @extend_schema(
        request=OpenApiRequest(request=MyPydanticModel),
    )
```

That hits the warning about `could not resolve request body`.

But the extension is used (and results in the above empty schema) if I use:
```python
    @extend_schema(
        request=MyPydanticModel,
    )
```

It's a bit weird, as it doesn't seem to have a problem with using `OpenApiResponse`:
```python
    @extend_schema(
        responses={
            "201": OpenApiResponse(
                response=MyResponseModel,
                description="Some description here",
            ),
```

I can open a separate issue for that, it's probably unrelated to why I'm not seeing the full schema for my pydantic models.

**Comment by devanubis** [comment]
Maybe this is just swagger not knowing what to do with the schema def...

**Comment by devanubis** [comment]
Ah I've just seen https://github.com/tfranzel/drf-spectacular/pull/1030

**Comment by devanubis** [comment]
OK the schema seems to be correct with the version of the extension from #1030 :tada: 

Still the bug with the `OpenApiRequest(request=MyPydanticModel)` not hitting the extension, so I'll open a separate issue just for that.

**Comment by tfranzel** [comment]
I'm a rubber-duck enthusiast myself 😆

I'll have a look at the  `OpenApiRequest` issue.
