### ISSUE TITLE
Pydantic extension blueprint not working with OpenApiRequest object

### ISSUE THREAD

**Issue by devanubis** [tfranzel/drf-spectacular#1106]
**Describe the bug**
Using
```python
    @extend_schema(
        request=OpenApiRequest(request=MyPydanticModel),
    )
```
Doesn't appear to hit the `PydanticExtension` blueprint, and triggers the warning:
```
Warning [MyView]: could not resolve request body for POST /url/path. Defaulting to generic free-form object. (Maybe annotate a Serializer class?)
```

But it works fine with just
```python
    @extend_schema(
        request=MyPydanticModel,
    )
```
But that doesn't allow for adding descriptions or examples.

It _does_ appear to work OK with defining responses with `OpenApiResponse` though.
```python
    @extend_schema(
        responses={
            "200": OpenApiResponse(
                response=MyResponseModel,
                description="Some description here",
            ),
        }
    )
```

**To Reproduce**
```python
from pydantic import BaseModel
from pydantic.dataclasses import dataclass
from rest_framework.decorators import api_view

from drf_spectacular.utils import extend_schema
from drf_spectacular.utils import OpenApiRequest


@dataclass
class D:
    id: int


class A(BaseModel):
    name: str


class B(BaseModel):
    name: str
    a: A


class C(BaseModel):
    id: int
    b: B
    d: D


# Works as expected
# @extend_schema(request=C)
# Doesn't work
@extend_schema(request=OpenApiRequest(request=C))
@api_view(["POST"])
def pydantic_view(request, _):
    pass

```

**Expected behavior**

The `PydanticExtension` to be used to generate a schema for `C` and it's fields from the `OpenApiRequest` object.

**Comment by tfranzel** [comment]
So this is actually a general bug and not specific to any extension. `OpenApiRequest` was added very late and you are hitting a specific case, that was simply forgotten to be dealt with. Curious this was not encountered before. Probably because this is a relatively new feature and you use it slightly differently than the use-case it was added for.

Working on a solution.
