### ISSUE TITLE
Combined result of AutoSchema's get_override_parameters + @extend_schema(parameters=[...])

### ISSUE THREAD

**Issue by crimoniv** [tfranzel/drf-spectacular#111]
This might not be actually a bug but a help-needed / enhancement request. It can be workarounded with `filter_backends` but we would like to know if there are any other ways to make it work.

**Describe the bug**

When using a custom schema class to add parameters, any view decorated with `@extend_schema(parameters=[...])` [will ignore](https://github.com/tfranzel/drf-spectacular/blob/b64e915ae95a8909fa5262fdb0798857d2c8f5d7/drf_spectacular/utils.py#L162-L165) the `AutoSchema`'s `get_override_parameters()` method.

**To Reproduce**

1. Inherit from `AutoSchema` and return an `OpenApiParameter` in `get_override_paramers()`.
2. Decorate a view with `@extend_schema(parameters=[...])`.
3. Any parameter given in step 1 won't appear in the generated schema.

**Expected behavior**

To have a combined parameters list.

**Comment by tfranzel** [comment]
hi! you make a good points there. the behavior of  `parameters` is currently "replacement". indeed, "extending" would be a valid  choice too. all other other `@extend_schema` parameters only make sense in the "replacement" mode. the other mode for `parameters` simply did not occur to me yet. i'll have to think about it a bit. 

in the meantime i think you could do this. it is not pretty but might do the trick.

```python
class YourAutoSchema(AutoSchema):
   def _process_override_parameters(self):
      params = super()._process_override_parameters() 
      # do your thing
      params.append(build_parameter_type(XYZ)
```

**Comment by crimoniv** [comment]
Hi @tfranzel! I'm glad you found this enough interesting to think a bit about it. We were not really confident but thought this could be useful to other projects.

Regarding your proposed solution, it is working flawlessly! May not be the prettiest, but we will use it by now.

Thank you so much @tfranzel 🍻

**Comment by tfranzel** [comment]
@crimoniv this should fix the issue. 

there is one caveat though. your custom `AutoSchema` needs to be globally set in the settings as recommended in the README. i discovered there is a non-trivial "bug" that does not allow setting the schema class **locally** in the view as attribute **and** using `@extend_schema`.  i don't believe you were doing this, but just so that you know.

**Comment by crimoniv** [comment]
Nice! I tried the new version and I can now see the extended parameters list. Fortunately the `AutoSchema` was already set as specified in the README, so we completely avoided that bug -we will take it into account, though-.

Thanks for your fast support @tfranzel!
