### ISSUE TITLE
Customize ViewSet.list action to return a json-object instead of a list.

### ISSUE THREAD

**Issue by Alkalit** [tfranzel/drf-spectacular#1115]
**Describe the bug**
I have a viewset that looks like this:

```python
class CadastreView(ReadOnlyModelViewSet):
    pagination_class = PageNumberPagination
    filterset_class = CadastreFilterSet
    serializer_class = TableSerializer

    def list(self, request, *args, **kwargs) -> Response:
        ...
```

for which spectacular renders this very cute scheme (example value) in swagger:

```json
{
  "count": 123,
  "next": "http://api.example.org/accounts/?page=4",
  "previous": "http://api.example.org/accounts/?page=2",
  "results": [
    {
      "header": [
        {
          "id": 0,
          "title": "string",
          "editable": false,
          "type": "string"
        }
      ],
      "body": [
        [
          {
            "id": 0,
            "value": "string",
            "type": "string",
            "comment": "string",
            "column_id": 0
          }
        ]
      ]
    }
  ]
}
```

The problem here is that I don't need the results to return a list of objects. I want it to return an object. Like this:

```python
{'count': 1,
 'next': None,
 'previous': None,
 'results': {'header': [{'id': None,
                         'title': 'Период',
                         'editable': False,
                         'type': 'year'},
                        {'id': None,
                         'title': 'Субъект РФ',
                         'editable': False,
                         'type': 'federation_subject'},
                        {'id': 1, 'title': 'Кокс', 'editable': True, 'type': 'indicator'}],
             'body': [[{'id': 1,
                        'value': '2000',
                        'type': 'year',
                        'comment': None,
                        'column_id': None},
                       {'id': 1,
                        'value': 'Москва',
                        'type': 'federation_subject',
                        'comment': None,
                        'column_id': None},
                       {'id': 1,
                        'value': '381.704671695895',
                        'type': 'indicator',
                        'comment': 'jYuSUDmInUAL',
                        'column_id': 1}]]}}
```

like with `forced_singular_serializer`, but with preserving all that pagination stuff

**Comment by tfranzel** [comment]
okay so this is kind of an edge case. DRF usually only uses pagination on the list response of `list()`. We only use the pagination class when we detect something as a list, which we need to do for several reasons. You want to break this basic assumption. 

First I thought you should use an envelope, which is kind of what you have here, but it also forcefully turns of the list (just as `forced_singular_serializer`) and so the outcome is the same (no pagnination). This is basically a common use-case quick fix. (FAQ: https://drf-spectacular.readthedocs.io/en/latest/faq.html#how-do-i-wrap-my-responses-my-endpoints-are-wrapped-in-a-generic-envelope)

This hack has limitations though and so you lose access to pagination, which is what you asked for. HOWEVER, there is actually a correct way to do this.

1. Create a custom `ListSerializer` and `to_representation`
2. use with DRF's `list_serializer_class`
3. Write an extension dealing with you custom list serializer.

Example implementation:

https://github.com/tfranzel/drf-spectacular/blob/82c00f8018249aae7433e098f0ab49cc251b564b/tests/test_extensions.py#L188

That is pretty much exactly what you are doing. Having a differently shaped (nested) list serializer that is essentially a nested list. That should work seamlessly with pagination.

**Comment by Alkalit** [comment]
Thank you for your help. Unfortunately that extension hook didn't work for some reasons. I checked out that unittest and registered the extension at my apps.py with no effect so I came up with 

```
class TableSerializer(serializers.Serializer):
    header = HeaderCellSerializer(many=True)
    body = serializers.ListSerializer(child=CellSerializer(), many=True)


class EnvelopeTableSerializer(serializers.Serializer):
    count = serializers.IntegerField()
    next = serializers.CharField()
    previous = serializers.CharField()
    results = TableSerializer()
```

```
    @extend_schema(responses=forced_singular_serializer(EnvelopeTableSerializer))
    def list(self, request, *args, **kwargs) -> Response:
```

That should work for some time. Cheers!

**Comment by tfranzel** [comment]
you have followed this, right? https://drf-spectacular.readthedocs.io/en/latest/faq.html#where-should-i-put-my-extensions-my-extensions-are-not-detected 

sure that works too if nothing else helps.
