### ISSUE TITLE
Add sorting disable for list of values

### ISSUE THREAD

**Issue by DTeltsov** [tfranzel/drf-spectacular#1118]
Hi, 
**Describe the bug**
I have problem: I add django filters to my view. Filters are choicefields where choices are specifically ordered queryset and in generated swagger choices in another order. I check with debugger, when filter init queryset is ordered correctly.

**To Reproduce**
Create django filter choicefield with queryset specifically ordered and add them to view that has swagger schema 

**Expected behavior**
Choices in order that i choose

**Comment by tfranzel** [comment]
Hi,

we never sort choices and they come out as provided to the field. Please provide a reproduction.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
