### ISSUE TITLE
django-queryable-properties causes schema request to fail

### ISSUE THREAD

**Issue by stefanofusai** [tfranzel/drf-spectacular#1119]
**Describe the bug**
I'm using [django-queryable-properties](https://django-queryable-properties.readthedocs.io/en/stable/) to _"Write Django model properties that can be used in database queries."_. Everything works well except for the integration with drf-spectacular, which doesn't seem to recognize them resulting in the following error upon requesting the drf-spectacular schema: `<queryable_property: api.models.MyModel.date> is not a module, class, method, or function.`. Given that I can't drop support of django-queryable-properties, is there anything I can do to fix this error?

Trying to remove the MyModel's urls from the router in urls.py results in other models with queryable_property returning the same error, which makes me think it's an issue with the integration of drf-spectacular and django-queryable-properties and not MyModel itself, but I would appreciate some input on what's causing it exactly and how it can be solved (either on drf-spectacular's end or on django-queryable-properties's end).

Please let me know if I can provide any additional useful information.

**To Reproduce**
```py
# models.py
class MyModel(models.Model):
    ...

    objects = QueryablePropertiesManager()


    @queryable_property
    def date(self) -> str | None:
        ...

    @date.annotater
    @classmethod
    def date(cls) -> models.CharField:
        ...

# serializers.py
class MyModelSerializer(serializers.ModelSerializer[MyModel]):
    class Meta:
        model = MyModel
        fields = [
            ...,
            "date",
            ...
        ]

# urls.py
router.register(r"mymodels", MyModelViewSet, basename="mymodels")
```

**Expected behavior**
Docs loading successfully.

**Comment by tfranzel** [comment]
I did not yet have time to look at this, but would have been defensive about these intricate mechanics anyway.

Could you share your fix here, if relevent, so others could benefit? thanks.

**Comment by stefanofusai** [comment]
Hey, sorry for not providing a comment. I just decided to switch from using d-q-p to custom model managers with annotations in get_queryset. Although slightly more verbose this lets me stick to core Django and it did in fact solve the issue I was having with drf-spectacular.

**Comment by tsepulvedacaroca01** [comment]
In case anyone needs a possible solution. An AutoSchema must be generated and the `_map_response_type_hint` method overridden

```py
class AutoSchema(openapi.AutoSchema):
    ....
    def _map_response_type_hint(self, method):
        # ---------- START NEW CODE ---------- 

        hint = None
       
        # Check if it has the get_annotation method, if so get the type
        if hasattr(method, 'get_annotation') and callable(method.get_annotation):
            hint = get_type_hints(method.get_annotation).get('return', None)

        if hint is None:
            hint = get_override(method, 'field') or get_type_hints(method).get('return')

        # ----------  END NEW CODE ---------- 

        if is_serializer(hint) or is_field(hint):
            return self._map_serializer_field(force_instance(hint), 'response')
        if isinstance(hint, dict):
            return hint

        try:
            schema = resolve_type_hint(hint)
        except UnableToProceedError:
            warn(
                f'unable to resolve type hint for function "{method.__name__}". Consider '
                f'using a type hint or @extend_schema_field. Defaulting to string.'
            )
            return build_basic_type(OpenApiTypes.STR)

        description = get_doc(
            method.func if isinstance(method, functools.partial) else method
        )
        if description:
            schema['description'] = description

        return schema
```
