### ISSUE TITLE
drf-querystringfilter

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#112]
https://pypi.org/project/drf-querystringfilter/ query arguments do not come through in the API.

It isnt [very popular](https://pypistats.org/packages/drf-querystringfilter), and there are many alternatives, but it is one of the simpler ones to implement as it doesnt need any filter creation or sub-classing.

Probably want to collate a few prominent query arg filter apps and find one complex one which works well with drf-spectacular, and one basic one.  Then new projects that care about openAPI will likely start with those selected, and avoid re-inventing this wheel.

**Comment by tfranzel** [comment]
last commit 2018 on that repo and only a few stars. would be up for a "popular" query param lib though.
