### ISSUE TITLE
Add additional type constants for plumbing.ResolvedComponent

### ISSUE THREAD

**Issue by sergei-maertens** [tfranzel/drf-spectacular#1128]
`drf_spectacular.ResolvedComponent` currently supports two constants for the `type` key:

https://github.com/tfranzel/drf-spectacular/blob/eea552d23c07858abccf183f565812937a4e4142/drf_spectacular/plumbing.py#L678

`ResolvedComponent.SCHEMAS` and `ResolvedComponent.SECURITY_SCHEMA`

The [OpenAPI spec](https://swagger.io/specification/v3/#components-object) supports more keys, so the following properties could be added to make it easier to work with spec-defined types and avoid downstream projects accidentally using a `type` value that is not part of the spec:

Proposed additions:

```py
class ResolvedComponent:
    ...

    RESPONSE = 'responses'
    PARAMETER = 'parameters'
    EXAMPLE = 'examples'
    REQUESTBODY = 'requestBodies'
    HEADER = 'headers'
    LINK = 'links'
    CALLBACK = 'callbacks'
```

Note that OpenAPI 3.1 also includes `pathItems` in there.

**Comment by tfranzel** [comment]
Hey, sure we could extend the list in `ResolvedComponent`. The reason there are only 2 is because that is all we support and it will most likely stay that way. I do not intent to do any major structural changes. However, it might be interesting for people writing extensions or hooks, so why not. 👍

**Comment by sergei-maertens** [comment]
That's exactly how we use it :) I will ensure a PR gets made
