### ISSUE TITLE
How can i use use @extend_schema to generate nested tag? is it possible to achive this with this decorator or another methods?

### ISSUE THREAD

**Issue by fazialnjd** [tfranzel/drf-spectacular#1130]
How can i use use @extend_schema to generate nested tag? 
Is it possible to achive this with this decorator or another methods?

**Comment by tfranzel** [comment]
Seems like OpenAPI does not support it and SwaggerUI is the same. Nothing we can do about it.

https://github.com/swagger-api/swagger-ui/issues/5969
https://github.com/OAI/OpenAPI-Specification/issues/1367
