### ISSUE TITLE
Unable to authenticate with OAuth2 with Authorization Header in Swagger UI

### ISSUE THREAD

**Issue by jiaulislam** [tfranzel/drf-spectacular#1131]
I'm trying to authenticate user with Swagger UI. But getting error saying `Auth ErrorError: Unauthorized, error: invalid_client` when using `Client credentials location: Authorization header` (though working in postman). But when I select `Request Body` it's authenticated successfully. I'm using the same configuration for my other project it was working in old version `v0.26.5`. But in latest `v0.27.0` I tried to use `OAS_VERSION=3.1.0` and same oauth2 configurations as my old project but no luck. Any idea what could be the issue.

OS: Windows 11
Python=3.12.1
Django=5.0
drf_spectacular=0.27.0
django-oauth-toolkit=2.3.0 

```python
SETTINGS_METADATA = {
    'OAS_VERSION': '3.1.0',
    "TITLE": "Bancassurance System RestAPI",
    "DESCRIPTION": "Welcome to Bancassurance RestAPI Service.",
    "VERSION": "1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
    'CAMELIZE_NAMES': False,
    'COMPONENT_SPLIT_REQUEST': True,
    "SWAGGER_UI_SETTINGS": {
        "swagger": "2.0",
        "deepLinking": True,
        "filter": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "SERVERS": [
        {"url": "http://localhost:8080", "description": "LOCAL"},
    ],
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
        'drf_spectacular.hooks.postprocess_schema_enums'
    ],
    "OAUTH2_FLOWS": ["password"],
    "OAUTH2_TOKEN_URL": "o/oauth2/token/",
    "OAUTH2_REFRESH_URL": "o/oauth2/token/",
    "OAUTH2_SCOPES": "openid create update read groups",
    "SWAGGER_UI_OAUTH2_CONFIG": {
        "clientId": "pQejbuRCRS9vH2pX65evFd5WS7w57tk8pCzyjMg6",
        "clientSecret": "django-insecure---b$0zr(k2y1z^a1plhi3#5q)ssx@q6*+_^v-h+%mxvd*!^#m(",
        "appName": "frontend-app",
    },
}
```

**Comment by tfranzel** [comment]
Hi, are you sure this is not due to changes on your end between the projects? I'm pretty sure we have basically changed nothing between `0.26.5` and `0.27.0` with regards to SwaggerUI or auth.

https://github.com/tfranzel/drf-spectacular/compare/0.26.5...0.27.0

And setting OAS 3.1 changes nothing auth related, just some optional type null constructions.
