### ISSUE TITLE
application/pdf 

### ISSUE THREAD

**Issue by stanhjr** [tfranzel/drf-spectacular#1143]
**Describe the bug**
so if I add this decorator 
```
    @extend_schema(responses={(200, "application/pdf"): OpenApiTypes.BINARY})
    @action(methods=("get",), detail=True, url_path="pdf-report")
    def pdf_report(...)
```

I get the following error
`{
  "type": "client_error",
  "errors": [
    {
      "code": "not_acceptable",
      "detail": "Could not satisfy the request Accept header.",
      "attr": null
    }
  ]
}`

without extend_schema, the swagger works everything correctly, in postman, of course, everything works too

Did I not indicate some important performance setting?

Otherwise, thanks for the library, it's wonderful :)

**Comment by tfranzel** [comment]
Hi, that makes sense. You make a change in the schema, but DRF still thinks differently. You probably only `Accept` via `renderer_classes` JSON and so on. Thus requesting `application/pdf` will be rejected by DRF as it is not in the acceptable list. Maybe you need a small custom renderer class to signify that.  Not sure exactly, but this might also work with a plain APIView (not viewset)

https://www.django-rest-framework.org/api-guide/renderers/#accepted_media_typenone

spectacular only deals with the schema and does not alter your API itself.

**Comment by stanhjr** [comment]
yes, I already found this solution, thanks
