### ISSUE TITLE
Examples in request and response

### ISSUE THREAD

**Issue by Niccolum** [tfranzel/drf-spectacular#115]
Is it possible to pass example in request or response in APIView to create example request with swagger and see examle response?

**Comment by tfranzel** [comment]
that is currently not supported. would be a nice feature addition though. it would probably be another parameter to `@extend_schema`

**Comment by KimSoungRyoul** [comment]
@tfranzel 

how about these code to support example feature?


~~~Python    
@extend_schema_serializer(
 example={.  # expected new feature
    "username":"aaa1233",
    "password":"1234"
 },
 exclude_fields = ("date_joined",)
)
class UserSerializer(serializer.ModelSerializer):
     
   class Meta:
        model = User
        fields = ("username","passwod", "date_joined")

~~~

**Comment by tfranzel** [comment]
feature was added via #208 and #231
