### ISSUE TITLE
Creating a custom ENUM/Preserving an ENUM that is no longer used in the model

### ISSUE THREAD

**Issue by elam91** [tfranzel/drf-spectacular#1153]
Hi, so I had a model that had choices set, and then we decided we dont want to limit it on the DB level, so the admin can change it from the admin panel, now besides the concern of whether thats good practice or not, we still wanted the Enum in the frontend so its easier for the frontend developer to use, but removing it from the model removed it from the schema.

this is the workaround I did:
```python
    @extend_schema_field(serializers.ChoiceField(choices=PositionKeys.choices))
    def get_key(self,obj):
        return obj.key
```

But I was wondering if there is a more straightforward way to do this, without a SerializerMethodField, just telling the schema, create this Enum, I dont care if a serializer/model uses it

PositionKeys is a TextChoices enum, and Position is the model.

**Comment by tfranzel** [comment]
`SerializerMethodField` will make it readonly. Sure there is an easier way. Just override automatically generated field in the serializer with your customized choice field. 

```python
class FooSerializer(ModelSerializer):

    your_model_field_name = serializers.ChoiceField(choices=PositionKeys.choices))

    class Meta:
        model = Position
        fields = ...
```

This is how simple field customizations are usually done.

**Comment by elam91** [comment]
That makes so much sense. Thank you!
