### ISSUE TITLE
Request: Make it possible override the "required" attribute to False on readonly fields

### ISSUE THREAD

**Issue by kendallzhu** [tfranzel/drf-spectacular#1155]
Some projects have fields that are readonly but not required. Currently, drf-spectacular ignores "required=False" when explicitly set for readonly fields, whenever COMPONENT_NO_READ_ONLY_REQUIRED is not set. I would like an explicit specification of "required=False" to be always respected, so that a project can explicitly specify readonly fields as not required.

The full context here is that a project has many readonly fields, a few of which are not required but many of which are. We don't want to change the default, but we want to be able to explicitly set certain fields to not required.

Here is the relevant line of code that currently ignores the explicit setting:
https://github.com/tfranzel/drf-spectacular/blob/a616766528b9a97516b03496354a56755762f914/drf_spectacular/openapi.py#L1031

Thank you!

**Comment by tfranzel** [comment]
So `required` is somewhat loosely defined in DRF. It is only enforced on requests and I think it is not really defined for responses.

What we do is apply a heuristic that does the right thing most of the time. In DRF. read-only fields a basically always present in the response. If you don't like that heuristic, you can turn if off with `COMPONENT_NO_READ_ONLY_REQUIRED` and then we only consider the fields `required` attribute and nothing else.

I'm not exactly sure what you are asking. Turning off that feature will give you exactly what you asked for. 

Also note that we cannot distinguish manually set `required` attributes from the default that DRF generates for you.

**Comment by kendallzhu** [comment]
Apologies, I was hoping we could distinguish between a manually set "required=False" and a default False. In that case that we cannot, nothing can be done here.
