### ISSUE TITLE
OpenApiYamlRenderer cannot dump OrderedDict

### ISSUE THREAD

**Issue by timothymctim** [tfranzel/drf-spectacular#1158]
The `renderers.OpenApiYamlRenderer` renderer cannot dump `collections.OrderedDict` objects. This is the case because the `Dumper` class inside the `render` function is inherited from `yaml.SafeDumper`, which doesn’t support `collections.OrderedDict` (`yaml.Representer` does).

**To Reproduce**
This bug is triggered in my setup when sending an OPTIONS request to the URL for the `SpectacularAPIView`. I am not entirely sure if this is caused in every setup or if this is specific to my setup.

Making an OPTIONS request, causes the `OpenApiYamlRenderer.render` function to receive a `collections.OrderedDict` type, causing the exception `yaml.representer.RepresenterError`.

**To Fix**
One of the approaches to address this issue is to add the `represent_ordered_dict` dumper from `yaml.Representer` in `OpenApiYamlRenderer.render` function, e.g.,
```
Dumper.add_representer(collections.OrderedDict, yaml.Representer.represent_ordered_dict)
```

**Unrelated note:** you might also want to change the parameter name `media_type` to `accepted_media_type`, since it is called that way in <https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py>. This was observed by `Pyright`, see also <https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIncompatibleMethodOverride>.

**Comment by tfranzel** [comment]
Hey,

so since OrderedDict is a native type we should cover it imho, even though it not happening during normal usage. 

I didn't know that the OPTIONS request actually uses the renderer (here yaml) of the view. On first sight, this feels like a DRF design flaw.

> Unrelated note: you might also want to change the parameter name media_type to accepted_media_type

👍

**Comment by timothymctim** [comment]
Thanks for the quick fix! Can confirm this fixes the issue I’ve had! :tada:
