### ISSUE TITLE
Description in response

### ISSUE THREAD

**Issue by Niccolum** [tfranzel/drf-spectacular#116]
Is it possible to pass description in every type of response in dict?

**Comment by tfranzel-cashlink** [comment]
can you to clarify what you mean by that exactly?

**Comment by Niccolum** [comment]
Of course.
https://swagger.io/docs/specification/describing-responses/
description field.

For example:
```
    responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an integer and larger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '5XX':
          description: Unexpected error.
```

**Comment by tfranzel** [comment]
currently there is no mechanism for that. i think it is related to #101.  in case you want to solve those this via `APIExceptions` , #101 would give you the code and description automatically from listing the possible exceptions in `@extend_schema` it would not allow for the `200` description but you describe it via the serializer description or summary.

**Comment by Niccolum** [comment]
Yep, this is that i need. Thanks!
Will be great, if this will be in docs.
So, i have inswer and close issue)

**Comment by tfranzel** [comment]
awesome. i already started on #101 but was missing the time to complete it. will happen very soon.
