### ISSUE TITLE
Inheriting OpenApiParameters from parent mixin functions

### ISSUE THREAD

**Issue by callumgare** [tfranzel/drf-spectacular#1165]
I'm a bit new to python, Django and drf-spectactular so I might just be doing something silly. But I'm struggling to work out how to include parameters defined by a mixin.

Say I have a ModelViewSet class and that class inherits a mixin that defines and uses `param-2`
```python
from rest_framework import viewsets
from drf_spectacular.utils import (
    OpenApiParameter,
    OpenApiTypes,
    extend_schema,
)

class TestMixin():
    @extend_schema(
        parameters=[
            OpenApiParameter("param-2", OpenApiTypes.BOOL, OpenApiParameter.QUERY),
        ],
    )
    def list(self, request, *args, **kwargs):
        param_1 = request.query_params.get("param-1")
        param_2 = request.query_params.get("param-2")
        return Response(f"returned from mixin - param-1: {param_1} - param-2: {param_2}")


class FooBarViewSet(TestMixin, viewsets.ModelViewSet):
    queryset = models.FooBar.objects.all()
    serializer_class = serialisers.FooBarSerialiser
```

The schema generated for a list endpoint with `FooBarViewSet` as the view will include the `param-2` param as expected. However as soon as I add a list method to FooBarViewSet that overrides the mixin's list method but calls it via `super()` then `param-1` is no longer defined.

```python
    # Added to FooBarViewSet
    def list(self, request, *args, **kwargs):
        print("param-1", request.query_params.get("param-1"), flush=True)
        return super().list(request, *args, **kwargs)
```

If I define a new parameter `param-1` in the list method of FooBarViewSet then I'll see `param-1` in the schema but still no `param-2`
```python
    # Decorates list method in FooBarViewSet
    @extend_schema(
        parameters=[
            OpenApiParameter("param-1", OpenApiTypes.BOOL, OpenApiParameter.QUERY),
        ],
    )
```

I know I could just define both params in FooBarViewSet but that would seem to reduce the modularity of the mixin. I want to be able to add my mixin to a number of different views and have that mixin just automatically consume a new param to use that to modify the request in some way but also I want the mixin in to declare a OpenApiParameter so that new param gets picked up by drf-spectacular. Is that possible?

**Comment by tfranzel** [comment]
No it is not possible, and also makes very little sense. When you override the `list` you are changing it, thus it makes no sense to pick-up previous decorations. It is just coincidental that this is your expectation. What would you do if you actually didn't want to have `param-2` because it was superseded?  It would be tricky to remove it.

**Comment by callumgare** [comment]
What if extend_schema had a param called something like “inherit_from_super” that defaulted to false but could be set to true to def-spectacular that your method would be calling it’s parents methods and so you want it’s schema to be inherited too?

**Comment by tfranzel** [comment]
conceptually (and also technically) possible, but I do not intend to make the mechanics even more complicated as they already are. Also, I don't think the use-case warrants the added complexity. As a user unfamiliar with what was done prior, this may also behave in unexpected ways and feels not very pythonic imho. 

Thats a pass from me, but I appreciate you bringing it up.

**Comment by callumgare** [comment]
Understandable, thanks for the consideration :)
