### ISSUE TITLE
Error in SpectacularSwaggerView

### ISSUE THREAD

**Issue by danilocastelhano1** [tfranzel/drf-spectacular#117]
When I try to open my SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui' 
in my browser, i got the error: Reverse for 'schema' not found. 'schema' is not a valid view function or pattern name.

my urls.py: 
url(r'^my_schema/$', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

Full error:
django.urls.exceptions.NoReverseMatch: Reverse for 'schema' not found. 'schema' is not a valid view function
or pattern name.

my Django version:
Django==3.0.4

**Comment by tfranzel-cashlink** [comment]
hi! as the readme states implicitly, you need the schema AND UI endpoint. the template from the UI endpoint will request the schema endpoint. you assign ``SpectacularAPIView`` a name and then tell it to SpectacularSwaggerView like that:

```
path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema')),
```

**Comment by danilocastelhano1** [comment]
sorry, it worked fine.

**Comment by nuest** [comment]
Just in case someone else ends up here: I had to add the app name prefix for this to work in my app_

```python
app_name = "myapp"

urlpatterns = [
    path("api/", include("publications.api")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='myapp:schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='myapp:schema'), name='redoc'),

```
