### ISSUE TITLE
Example on how to add multiple security headers using the following method

### ISSUE THREAD

**Issue by AnshMSD** [tfranzel/drf-spectacular#1173]
https://github.com/tfranzel/drf-spectacular/blob/473d2d803b9e8ae986ea60292ec0ebfb0ff2d601/drf_spectacular/extensions.py#L49

Please can you state an example on how can i return multiple security headers such as api-key, Auhtorization, etc for my custom Authentication class using the method 

i am trying this but this aint working can you point where i am wrong
```
class MyAuthenticationScheme(OpenApiAuthenticationExtension):
    target_class = 'api.auth.cognito.CognitoAuthentication'  # full import path OR class ref
    name = 'CognitoAuthentication'  # name used in the schema

    def get_security_definition(self, auto_schema):
    
        return [{
                'type': 'apiKey',
                'name': 'x-user-id',
                'in': 'header'
            }]
```

**Comment by tfranzel** [comment]
You mean a auth method requires multiple parameters? The trick ist to give a list for `name`, and then return a list in `get_security_definition`
https://github.com/tfranzel/drf-spectacular/blob/473d2d803b9e8ae986ea60292ec0ebfb0ff2d601/tests/test_extensions.py#L164-L172

**Comment by AnshMSD** [comment]
okay got it thanks a lot!!!
Also i want to make sure these security keys are used in my APIView so how should i make use of them so that they are present in the request body in the extend_schema decorator. can you pls help

**Comment by tfranzel** [comment]
use your `api.auth.cognito.CognitoAuthentication` on that APIView and it should show up in the schema. It is not part of the body. Those are headers. No need for `@extend_schema` for this.
