### ISSUE TITLE
`extend_schema_view` of a custom `@action`

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#1176]
I was wondering if something like the following is/could be supported:

```py
class MyCreateMixin:
    @action(methods=[HTTPMethod.POST], detail=False, url_path="my-url")
    def my_action(self, request: Request) -> Response:
        ...

@extend_schema_view(
    my_action=extend_schema(...)
)
class MetalNetEdgeViewSet(MyMixin, ModelViewSet):
    ...
```

The rationale is to allow custom mixin's to provide `@action`s to a `Viewset` but still be able to customize the schema generated.

I can't simply:

```py
class MyCreateMixin:
    @action(methods=[HTTPMethod.POST], detail=False, url_path="my-url")
    def my_action(self, request: Request) -> Response:
        ...


class MetalNetEdgeViewSet(MyMixin, ModelViewSet):
    @extend_schema(...)
    def my_action(self, request: Request) -> Response:
        ...
```

because then HTTP 405 errors are returned because the `ViewSet` `my_action` is not decorated with `@action`. This leads to a situation where I need to duplicate both decorators for each instatiaon of my `@action` if I want the schema to be correct:

```py
class MyCreateMixin:
    def my_action(self, request: Request) -> Response:
        ...


class MetalNetEdgeViewSet(MyMixin, ModelViewSet):
    @extend_schema(...)
    @action(methods=[HTTPMethod.POST], detail=False, url_path="my-url")
    def my_action(self, request: Request) -> Response:
        return super().my_action(request)
```

**Comment by tfranzel** [comment]
hey,

have you tried your fist snippet? This is a deliberate feature and should already work and it should be covered by the tests.

The intended primary use-case of `@extend_schema_view` is to **not** force you to build things like in your 3rd snippet.

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/blob/473d2d803b9e8ae986ea60292ec0ebfb0ff2d601/tests/test_regressions.py#L2634-L2648

that should be exactly what you wanted, minus the mixin, but I don't see that as an issue.

**Comment by johnthagen** [comment]
@tfranzel 🤦 The first couple times I tried it, I must have had some other mistakes as it wasn't working and then I assumed that it might not be supported since it was not called our explicitly in the docs (and I also thought that my custom `url_path` might have somehow been messing it up.

Anyway, I tried it again with confidence and of course it worked.

Would you accept a PR to update the docs to make it clear that even custom user `@action`s are supported?

**Comment by tfranzel** [comment]
glad it worked. A PR would be very welcome. I always struggle where to put all this information in a digestible manner.

I'm quite sure you would be surprised, if you went through all the +500 tests. There are some wild features in there that you likely would've never expected, but are to fringe to properly document.
