### ISSUE TITLE
Overidden `to_representation()` Schema Generation

### ISSUE THREAD

**Issue by rui-antunes** [tfranzel/drf-spectacular#1177]
Hey,

Just came across `drf-spectacular` and so I'm still trying to understand how to use it on my project.

I've overidden `to_representation()` on some of my serializers such that an instance would be serialized to something like:

```
{
    "type" : "...",
    "id" : 4,
    "attributes" : {
        "attribute-1" : "...",
        "attribute-2" : "...",
        "attribute-3" : "...",
        ...
    }
}
```

I understand schema generation does not consider what I've done in `to_representation()`, only the serializers fields.

Other than providing a schema to `@extend_schema(response=raw schema dict)`, how am I able to generate the schema for these kinds of serializers?

Thank you

**Comment by tfranzel** [comment]
Hi!

As you correctly noticed, we cannot guess what happens in a custom `to_representation`. We have 2 workarounds currently. We call this construction an "envelope". Searching the repo with that keyword will show you a couple of things.

1. A function that lets you build an envelope for easy one-off usage: https://drf-spectacular.readthedocs.io/en/latest/faq.html#how-do-i-wrap-my-responses-my-endpoints-are-wrapped-in-a-generic-envelope

2. Same outcome as 1., but in a more structured re-usable way with extensions: https://github.com/tfranzel/drf-spectacular/blob/f9f0336b2e69d6b8427cace2f903035c32b1b9e5/tests/test_extensions.py#L234
  You would mark the serializer with a signal mixin, for which the extension will be triggered. Would make sense to put the `to_represetation` in the mixin. 

    extensions are registered like so: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

**Comment by rui-antunes** [comment]
@tfranzel I believe, you're suggesting something like this?

```
class EnvelopeFix(OpenApiSerializerExtension):
    target_class = EnvelopeMixin
    ...
    def map_serializer(self, auto_schema, direction):
        ...
        return build_object_type(
            properties={
                'type': build_basic_type(OpenApiTypes.STR),
                'attributes': component.ref,
            }
        )
```

**Comment by tfranzel** [comment]
@rui-antunes yes, exactly like that. Depending on how your setup works, I would like likely use an import string instead of the actual class for `target_class`.

also make sure you follow: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

**Comment by rui-antunes** [comment]
@tfranzel Integrated my extension according to the documentation you mentioned and also considered using an import string for `target_class`.

Do you have any advice against setting `target_class` with my custom serializer class, instead of `EnvelopeMixin`?

```
class EnvelopeFix(OpenApiSerializerExtension):
    target_class = CustomSerializer
```

**Comment by tfranzel** [comment]
1. I recommend import strings because they are more fool-proof. Using the classes directly requires an import, and that has created problem for some users due to import loops. Never mind if that is not a problem for you. Both options are functionally identical. 

2. When people use envelopes, they usually do it more than once, thus the mixin recommendation. Otherwise you would need to write a extension for every serializer.
    if you use the mixin route, make sure to enable subclass matching:

```python
class EnvelopeFix(OpenApiSerializerExtension):
    target_class = EnvelopeMixin
    match_subclasses = True
```

**Comment by rui-antunes** [comment]
Indeed (2) makes it modular and decoupled, I've applied it.

Thank you @tfranzel, for your support and for making this package available, has been of great help to me.
