### ISSUE TITLE
Docstring of ViewSet parent classes is shown for APIs description

### ISSUE THREAD

**Issue by alyahmady96** [tfranzel/drf-spectacular#1182]
I have a Mixin which I inherit all my ViewSets from. I set a docstring in Mixin class to describe it's purpose, but it's shown for all my ViewSet APIs in Swagger UI.

To disable this behavior, I need to decorate all actions in ViewSet with `extend_schema` and 

This code will use the Mixin docstring:
```python
class AllowedOptionsMixin:
    """ To expose OPTIONS method for all actions (specially in Swagger) """
    pass


class CreateListAdViewSet(AllowedOptionsMixin, GenericViewSet):
    @action(detail=False, methods=["GET"])
    def my_ads_list(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
```
![image](https://github.com/tfranzel/drf-spectacular/assets/129692127/2fe4d82e-1e59-4419-8f2e-8b682f28a33d)

To disable this unexpected behavior, I need to use `extend_schema`. It also gets annoying, when I don't need to override default actions.
```python
class AllowedOptionsMixin:
    """ To expose OPTIONS method for all actions (specially in Swagger) """
    pass


class CreateListAdViewSet(AllowedOptionsMixin, GenericViewSet):
    @extend_schema(description="My Description")
    @action(detail=False, methods=["GET"])
    def my_ads_list(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
```
![image](https://github.com/tfranzel/drf-spectacular/assets/129692127/a315171a-c884-44b9-83a7-f74552b7f003)

It's expected for Swagger UI to use the ViewSet classes' docstring of itself, instead of using docstring of parent classes or Mixins of it.
And if there is not docstring for ViewSet, shows nothing for description, instead of a wrong one.

**Comment by tfranzel** [comment]
Hi, we have a setting dedicated exactly for this case:

https://github.com/tfranzel/drf-spectacular/blob/b65ae61c748710b86304ad83dfddfe76f24649ee/drf_spectacular/settings.py#L127-L128

Just define your own function, call the lib one and add your mixin classes to it:

https://github.com/tfranzel/drf-spectacular/blob/b65ae61c748710b86304ad83dfddfe76f24649ee/drf_spectacular/plumbing.py#L190

**Comment by alyahmady96** [comment]
I should have read the docs, better.
Great. Thanks for your amazing library.
