### ISSUE TITLE
`drf-spectacular` does not see fields added as annotations on custom manager

### ISSUE THREAD

**Issue by radusuciu** [tfranzel/drf-spectacular#1183]
This is more of a question that a bug. I've got a model that uses a custom default manager which adds a field that is dynamically generated through a call to `annotate()`. In my case this is a nice way to add in some functionality in one place and it works everywhere transparently -- except it doesn't work with `drf-spectacular` without sprinkling `extend_schema` everywhere where I might want to use this field.

This is tangentially related to https://github.com/tfranzel/drf-spectacular/issues/1119, and I'm basically describing the work-around that @stefanofusai mentioned:

>  I just decided to switch from using d-q-p to custom model managers with annotations in get_queryset. Although slightly more verbose this lets me stick to core Django and it did in fact solve the issue I was having with drf-spectacular.

He did not mention how this solved his issue with `drf-spectacular`, but I imagine that he used `extend_schema` or similar. What I'm hoping to find is a solution where I can annotate the fact that `display_name` exists as well as type, in one place.

## Example Code

```python
from django.db import models, Case, When, TextField, F


class FooManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .annotate(
                display_name=Case(
                    When(cool_name__isnull=False, then=F('cool_name')),
                    default=F('name'),
                    output_field=TextField(),
                )
            )
        )

class Foo(models.Model):
    objects = FooManager()

    name = TextField(unique=True)
    cool_name = TextField(null=True)
```

**Comment by radusuciu** [comment]
In the course of writing this issue I found a solution, but I just wanted to document it here and maybe someone can poke holes in my solution or suggest alternatives. Feel free to close any time, and thanks again for your work on this indispensable project.

## Example Code

```python
from django.db import models, Case, When, TextField, F


class FooManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .annotate(
                display_name=Case(
                    When(cool_name__isnull=False, then=F('cool_name')),
                    default=F('name'),
                    output_field=TextField(),
                )
            )
        )

class Foo(models.Model):
    objects = FooManager()

    name = TextField(unique=True)
    cool_name = TextField(null=True)
```

## The Solution

One solution that satisfies my requirement is to add a property by the same name to `Foo`:

```python
class Foo(models.Model):
    objects = FooManager()

    name = TextField(unique=True)
    cool_name = TextField(null=True)
    
    @property
    def display_name(self) -> str:
        return self.cool_name or self.name
```

This works as far as `drf-spectacular` is concerned, but now you can't query based on `display_name` as you hit this error: 

```
> Foo.object.filter(display_name='foo')
AttributeError: property 'display_name' of 'Foo' object has no setter.
```

So what if we just add a no-op setter?


```python
    # rest of model definition omitted

    @property
    def display_name(self) -> str:
        return self.cool_name or self.name

    @display_name.setter
    def display_name(self, value: str) -> None:
        pass
```

now we're in business! Let's make one more tweak to the property so we avoid extra queries in some situation (TBH I'm not 100% sure if this is necessary...):

```python
class Foo(models.Model):
    objects = FooManager()

    name = TextField(unique=True)
    cool_name = TextField(null=True)
    
    @property
    def display_name(self) -> str:
        return getattr(self, 'display_name', self.cool_name or self.name)

    @display_name.setter
    def display_name(self, value: str) -> None:
        pass
```

**Comment by stefanofusai** [comment]
Sorry for not providing an insight in how I solved my issue.
What I'm doing in my project is using @extend_schema on all my API views to provide insights into the available parameters and the responses; for each response I link a serializer which then serializes the models, something like:
```py

@extend_schema(
    operation_id="...",
    parameters=[
        OpenApiParameter(
            name="...",
            type=OpenApiTypes.STR,
            location=OpenApiParameter.QUERY,
            description="...",
        ),
    ],
    summary="...",
    responses={200: GoodResponseSerializer, 400: BadResponseSerializer},
)
def my_view(request: Request, ...) -> Response:
    ...

class GoodResponseSerializer(serializers.Serializer):
    pagination = PaginationSerializer()
    facets = FacetSerializer(many=True)
    results = MyModelSerializer(many=True)
```

MyModelSerializer then contains the various attributes needed, including the field annotated via the model manager's `get_queryset` method (exactly like you did!)

```py
class MyModelSerializer(serializers.ModelSerializer[MyModel]):
    ...
    my_annotated_field = serializers.FloatField()
    ...

    class Meta:
        model = MyModel
        fields = [
            "...",
            "my_annotated_field",
            "..."
        ]
```

No properties on the model are needed on my end at all, I do everything via the model's manager and serializer. Let me know if this helps you out

**Comment by tfranzel** [comment]
Hey,

so I agree with @stefanofusai 

@radusuciu,  I see no reason to do funky stuff with properties here. If you look at the `ModelSerializer` DRF generates from that model, you can see that **DRF is also not aware of `display_name`**. Forget about the schema for a second, `display_name` is also missing from your API.

```python
class FooSerializer(serializers.ModelSerializer):
    class Meta:
        fields = '__all__'
        model = Foo

# repr(FooSerializer())
FooSerializer():
    id = IntegerField(label='ID', read_only=True)
    name = CharField(style={'base_template': 'textarea.html'}, validators=[<UniqueValidator(queryset=Foo.objects.all())>])
    cool_name = CharField(allow_null=True, required=False, style={'base_template': 'textarea.html'})
```

Once you add your annotated field to the serializer like @stefanofusai did, it will show up in the actual serializer API request/response and subsequently also in the schema.

**Comment by radusuciu** [comment]
@tfranzel Thanks for the comment. I didn't realize that, but perhaps that's because I don't use `fields = '__all__'`? So for me the following was sufficient and worked with the property hack:

```python
class FooSerializer(serializers.ModelSerializer):
    class Meta:
        fields = ('id', 'name', 'cool_name', 'display_name')
        model = Foo
```

I agree with you and @stefanofusai though, this is cleaner and sufficiently DRY:

```python
class FooSerializer(serializers.ModelSerializer):
    display_name = serializers.CharField(readonly=True)

    class Meta:
        fields = ('id', 'name', 'cool_name', 'display_name')
        model = Foo
```

What I missed was that `@extend_schema` isn't necessary...

Thanks to both of you!

**Comment by tfranzel** [comment]
awesome! Just one more thing. Even if you explicitly listed the `fields = ('id', 'name', 'cool_name', 'display_name')`, DRF will raise an exception on usage (without the property on the model **or** without the explicit serializer field).

Regardless of drf-spectacular, this is simply not supported by DRF and thus adding it on our side would make it a bug.

**Comment by radusuciu** [comment]
Another alternative is the [newly introduced `GeneratedField`](https://docs.djangoproject.com/en/5.0/releases/5.0/#database-generated-model-field).

There are different tradeoffs, but overall I think it is better than a custom manager for me as it also works in cases where you're accessing the model instance through an instance of a related model.
