### ISSUE TITLE
Custom actions that override `http_method_names` can be skipped

### ISSUE THREAD

**Issue by mikaraunio** [tfranzel/drf-spectacular#1184]
**Describe the bug**

If a custom action uses an HTTP method not listed in the ViewSet's `http_method_names`, overriding `http_method_names` to allow this method, drf-spectacular will not include that action in the schema.

**To Reproduce**

Consider the following `ModelViewSet` which provides a read-only view of Items, but allows users to favorite them by POSTing to `.../{id}/favorite/`:

```python
class ItemReadonlyViewSet(viewsets.ModelViewSet):
    http_method_names = ['get', 'options', 'head']

    @action(
        detail=True,
        methods=['post'],
        http_method_names=['post'],
    )
    def favorite(self, request, pk=None):
        self.get_object().add_as_favorite(user=request.user)
        return Response()
```

This works fine in DRF, but drf-spectacular skips the `.../favorite/` endpoint.

**Expected behavior**

I would expect the custom action to be included in the schema.

**Comment by tfranzel** [comment]
Hi, that indeed looks like a bug. This case was ignored in the original DRF implementation.  Thanks for raising it.

Just out of curiosity, why do you choose this convoluted way of removing the `post`? Why not just use `viewsets.ReadOnlyModelViewSet` as base class and remove all that `http_method_names` silliness?

**Comment by mikaraunio** [comment]
Hi, thanks for the quick fix.

The convoluted example is mainly for the sake of presenting  the problem clearly and simply  ;)

My actual code could probably benefit from a rewrite to `ReadOnlyModelViewSet` too, though.
