### ISSUE TITLE
Example Value in Swagger is coming "string".

### ISSUE THREAD

**Issue by arik555** [tfranzel/drf-spectacular#1186]
**The example value is not populated even after passing serializer class to the request parameter, in the DRF APIView.**
I have created a django rest framework project where I have APIview class and DRF Serializer class, I am passing the serializer class in the request parameter inside the @extend_schema decorator, but in the swagger UI, the example value is coming "string".

For some of the views and serializers they work just fine, in the same project.

### **_I want them to generate automatically based on the Serializer Class._**

**Here are few of the code & settings**

Installed Apps:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/81f6e83d-b1cb-43a9-a05e-8e024071074f)

Requirements:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/ad95c9d5-c5d8-4175-907a-2880efa68c6b)

Swagger Settings:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/5cc274eb-2ec9-4bc6-989f-dde67273d3ff)

Rest Framework Settings:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/40209208-5816-4d5c-a319-702e3b18cd9a)

Swagger URL settings:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/3a640a55-0c20-4cff-b943-ccd521b0f6f1)

APIView Class:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/f7925bd8-1b21-40ef-b30e-157cb063fe3f)

DRF Serializer Class:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/24427764-7c0e-4d65-941e-6d6a52dce880)

URLs:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/88736d94-0ca9-4fc8-a683-48fd9b27347c)

Swagger UI for the above View:
![image](https://github.com/tfranzel/drf-spectacular/assets/26118556/d7fc5714-e626-45b8-8840-5e519c42421b)

Why is the Example Value in the Swagger UI is coming "string". ?
There are other views and serializers, they are displaying the example value correctly, when using the same way.

**Comment by tfranzel** [comment]
Hi, please don't mix drf-yasg and drf-spectacular. At best it is confusing, at worst it interferes with each other.


* `get_schema_view()` is from drf-yasg. That is not our SwaggerUI endpoint. Please follow the README. 
* `schem_path_func` is not a spectacular setting

Your decoration looks okay, but I think you are looking at the wrong SwaggerUI.

**Comment by Ezenwankwo** [comment]
I have been battling with this same issue for 2days now. For some endpoints, the requests and responses are correct, for some others, it just displays "string". I am using DRF Spectacular in Django cookie cutter. I have been working on the project for four months and then this issue just appeared 2days ago.

**Comment by tfranzel** [comment]
@shreyanssuraliya that is a clear indication what swagger ui might be broken currently. we use the lastest version by default.
@AlexMorra @Ezenwankwo nothing changed for a while backend-wise. Neither django, DRF nor us released in the last couple of weeks.

use our setting `SWAGGER_UI_DIST` to pin to a working version. maybe someone can report the lastest working version.

```diff
SPECTACULAR_SETTINGS = { 
- 'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest', 
+ 'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@X.X.X',
}
```

https://www.jsdelivr.com/package/npm/swagger-ui-dist

**Comment by AlexMorra** [comment]
> @shreyanssuraliya that is a clear indication what swagger ui might be broken currently. we use the lastest version by default. @AlexMorra @Ezenwankwo nothing changed for a while backend-wise. Neither django, DRF nor us released in the last couple of weeks.
> 
> use our setting `SWAGGER_UI_DIST` to pin to a working version. maybe someone can report the lastest working version.
> 
> ```diff
> SPECTACULAR_SETTINGS = { 
> - 'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest', 
> + 'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@X.X.X',
> }
> ```
> 
> https://www.jsdelivr.com/package/npm/swagger-ui-dist
> 
> The plot is getting thicker. Released 3 days ago: https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.8

everything works with:
`'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.0.0',`

**Comment by arik555** [comment]
I guess, it is solved for now. thanks everyone for your time. much appreciated.
