### ISSUE TITLE
The work of versions is not clear!

### ISSUE THREAD

**Issue by ElveeBolt** [tfranzel/drf-spectacular#1189]
First of all, I would like to thank the authors for this wonderful module...)

**Describe the bug**
I don't quite understand the behavior of this module specifically in my case.
I write my API with the following architecture:

![Снимок экрана 2024-02-29 092940](https://github.com/tfranzel/drf-spectacular/assets/116059713/fc3dad36-1f50-4c47-b9c2-c75c616a8c05)

The endpoints are available at the following addresses:
- path('api/v1/', include('api.urls_v1'))
- path('api/v2/', include('api.urls_v2'))

**Main urls file**
```
urlpatterns = [
    path('api/v1/', include('api.urls_v1')),
    path('api/v2/', include('api.urls_v2')),
    path('api/schema/', SpectacularAPIView.as_view(api_version='v1'), name='schema_v1'),
    path('api/doc/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
```

**My settings file**
```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
}
```

And generated swagger scheme.
![Снимок экрана 2024-02-29 094551](https://github.com/tfranzel/drf-spectacular/assets/116059713/82d7771a-50c9-43b8-81a0-e311cb1c0e3c)

**Expected behavior**
I expect to get endpoints that are broken down by application. Now I have them all mixed up in a block with the name api (apparently this is the name of the project name)

**Comment by tfranzel** [comment]
Hi @ElveeBolt, thx! 

So you want to set  `SCHEMA_PATH_PREFIX ` to `'/api/v[0-9]'`, which would generate tags user and token here.

Since you have `/token` there is no common denominator, and thus the default estimated prefix is `""`. The tag is taken from the first item in the path (minus the prefix).

But you can always customize too with `@extend_schema(tags=['foo'])` in the view for example.

https://github.com/tfranzel/drf-spectacular/blob/f9344b266db01a90ebcba9e541721034a5b739c3/drf_spectacular/settings.py#L8-L13

**Comment by ElveeBolt** [comment]
I can only guess, but something tells me that you are referring to 2 different `custom_settings`

**Comment by tfranzel** [comment]
> I can only guess, but something tells me that you are referring to 2 different custom_settings

nobody mentioned `custom_settings`.

>     'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',

this is not how this works. you are not doing URL path versioning. you should be using `NamespaceVersioning` for this with. 

```
urlpatterns = [
        path('v1/', include('users.urls', namespace='v1')),
        path('v2/', include('users.urls', namespace='v2'))
]
```

**Comment by ElveeBolt** [comment]
I got confused with the `drf_yasg `module, because out of the box, the breakdown by application works without specifying `'SCHEMA_PATH_PREFIX': '/api/v[0-9]'`

I think that this point should be specified in the documentation for the module or as a separate question and answer on the FAQ page
[drf-spectacular.readthedocs.io](https://drf-spectacular.readthedocs.io/en/latest/faq.html)

Thanks for your help =)
