### ISSUE TITLE
DRF exception handling

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#119]
When the value of setting `REST_FRAMEWORK.EXCEPTION_HANDLER` is the default, the responses for each end-point should include response types for the exceptions it handles.

https://github.com/encode/django-rest-framework/blob/82c2b5c3e75debe047eebd8a17b50c1e17594663/docs/api-guide/exceptions.md

This includes many of the 400s, notably doesnt include 500s.

Also it would be lovely if the extension framework here was used so that custom values of REST_FRAMEWORK.EXCEPTION_HANDLER loaded any extension targetting that class, so that e.g. `drf-problems` can be supported, but there are many others commonly used like `drf-friendly-errors`.

**Comment by jayvdb** [comment]
https://github.com/ivlevdenis/drf_pretty_exception_handler#features has a nice summary of the very varied response payloads that default DRF emits.

**Comment by jayvdb** [comment]
A possible (temporary?) solution would to create a post-processing hook to append the following to every path.

```yaml
      responses:
        ...
        default:
          insert_ref_here_to_a_component_broadly_describing_of_all_drf_possible_responses
```

**Comment by tfranzel** [comment]
related to #101 and #116

**Comment by jayvdb** [comment]
Closing in favour of https://github.com/tfranzel/drf-spectacular/issues/101 , with a comment there for some considerations.
