### ISSUE TITLE
UnconfiguredHashIdSerialField - django-hashid

### ISSUE THREAD

**Issue by radudum10** [tfranzel/drf-spectacular#1193]
Hello, 
I am using django-hashid-field, which has a class called UnconfiguredHashidSerialField (https://github.com/nshafer/django-hashid-field/blob/master/hashid_field/rest.py#L13C7-L13C36) and I see this warning being raised by many views:

```shell
could not resolve serializer field "UnconfiguredHashidSerialField(read_only=True)". Defaulting to "string"
```

Those views have nested serializers that don't directly contain the hashid field, but their parents/bases do.

#### package versions
- Django==4.2.10
- djangorestframework==3.14.0
- django-hashid-field==3.4.0
- drf-spectacular==0.27.1

Any ideas how I can fix this?

Thanks!

**Comment by tfranzel** [comment]
Hi,

that library creates custom serializer fields that are unknown to drf-spectacular. I am not familiar with this library, but custom behavior is modeled with extensions: 

https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-field-output-with-openapiserializerfieldextension

Our built-in extensions use exactly the same facilites as the extensions you can create yourself.

Here are some examples: https://github.com/tfranzel/drf-spectacular/blob/master/docs/blueprints/drf_extra_fields.py

**Comment by radudum10** [comment]
thanks, that did the job, should this issue be closed?

**Comment by tfranzel** [comment]
awesome! we only offer native support for heavily used libs (due to maintenance burden), but you could add your solution to the blueprint section of the docs if you like. PR would be welcome. I'll close this for now.
