### ISSUE TITLE
Add support for djangorestframework-deepserializer

### ISSUE THREAD

**Issue by enzofrnt** [tfranzel/drf-spectacular#1201]
[djangorestframework-deepserializer](https://github.com/Horou/djangorestframework-deepserializer) is a great serializer that help to easly create nested model.
Maybe great to get full support of it, with great description in the schema.

refer to [this issue](https://github.com/Horou/djangorestframework-deepserializer/issues/5)

**Comment by tfranzel** [comment]
has anyone tested this? It might just mostly work out of the box depending on the the lib is build internally.

However, the lib is not popular enough for official support (and the corresponding maintenance burden). You might create extensions for it in the meantime:

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

**Comment by enzofrnt** [comment]
Ok, we will take a look on our side.
