### ISSUE TITLE
Unable to use enveloped Model of Pydantic V2

### ISSUE THREAD

**Issue by jiaulislam** [tfranzel/drf-spectacular#1202]
**Describe the bug**
Well this is not a bug I think. I would have put this in the Discussion area. But couldn't found. Don't know if anyone tried to implement pydantic inside of Django. But for some reason I needed to. I was trying to envelope a Pydantic type Model as extend_schema response as below. Is there any way I can get it to work ?

```python
def pydantic_enveloper(model_class: Type[BaseModel], many: bool):
    component_name = f"Enveloped{model_class.__name__}{'List' if many else ''}"

    @extend_schema_serializer(many=False, component_name=component_name)
    class EnvelopeSerializer(serializers.Serializer):
        status = serializers.ChoiceField(
            choices=[("success", "Success"), ("error", "Error")]
        )
        code = serializers.IntegerField(help_text="Valid HTTP status code")
        data = serializers.ListField(
            child=List[model_class] if many else model_class # here it's getting error ,
            required=True,
            allow_empty=many,
        )
        message = serializers.CharField(allow_null=True, required=False)

    return EnvelopeSerializer
```

**Comment by tfranzel** [comment]
Nice try, but nope sry this cannot work. You cannot mix a DRF serializer with pydantic like that. `ListField` has special magic that needs DRF fields.

I mean you can mix it in some ways (type hints, individual fields overrides), but not with DRF-native mechanics like `ListField`. It is not possible.

**Comment by jiaulislam** [comment]
thank you for the suggestion.
