### ISSUE TITLE
Support for SSE with Django event stream

### ISSUE THREAD

**Issue by enzofrnt** [tfranzel/drf-spectacular#1203]
Here is the link of the project.
[pyi](https://pypi.org/project/django-eventstream/)

**Comment by tfranzel** [comment]
We can't support concepts that are not covered by the OpenAPI specification. Upstream support needs to happen first. At the end of the day we just generate a OpenAPI schema. 

https://github.com/OAI/OpenAPI-Specification/issues/396

**Comment by enzofrnt** [comment]
I understand. However, perhaps we could enhance support for this module by working within the current OpenAPI standards, incorporating text in the description to clarify that the request endpoint is compatible with SSE. This would be beneficial because, ultimately, we will need to articulate through text that certain endpoints are compatible with SSE.

Did you understand ?

**Comment by tfranzel** [comment]
I don't think it is worth the effort adding a detection mechanism just to add a string warning about SSE.

Nothing is preventing you from just adding this to your own description texts.

**Comment by enzofrnt** [comment]
> I don't think it is worth the effort adding a detection mechanism just to add a string warning about SSE.
> 
> 
> 
> Nothing is preventing you from just adding this to your own description texts. 

Indeed everyone going's to do it anyway.. I don't thinks that useless to add it.

**Comment by enzofrnt** [comment]
So what do you think ?

**Comment by tfranzel** [comment]
not worth the effort, maintenance burden and added complexity, given this is a 3rd party app and we are unable to provide actual support except for some warning.

this decision is final until the upstream situation in the swagger specification changes.
