### ISSUE TITLE
Unable to hide Schemas section

### ISSUE THREAD

**Issue by stefanofusai** [tfranzel/drf-spectacular#1204]
Dear support team,
I was wondering if there was a way to hide the Schemas section in the docs.

After implementing [drf-standardized-errors](https://github.com/ghazi-git/drf-standardized-errors) I found myself with dozens of repetitive schemas, but regardless of this I would prefer my docs page to not include the Schemas section.

Is there anything I can do to hide/not render it? I saw a similar issue (#638) but was unable to understand how to disable the Schemas section globally and not on a per-serializer approach.

Thank you, as always, for the help

<img width="1490" alt="image" src="https://github.com/tfranzel/drf-spectacular/assets/46556949/5fbf8ce6-c616-4ec9-83e5-7c1c788f82cd">

**Comment by stefanofusai** [comment]
Well, looks like it was simply a matter of setting `"defaultModelsExpandDepth": -1` (as per [https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/)) in my `"SWAGGER_UI_SETTINGS"`.

If you don't mind I'll wait for your confirmation that this solves my request with no issues before marking this as closed.
Thank you!

**Comment by tfranzel** [comment]
SwaggerUI settings are out of scope for drf-spectacular. 

There is no way to completely remove the schemas (component) section, which would make the whole schema broken.
`defaultModelsExpandDepth` just collapses expandable items in the UI.
