### ISSUE TITLE
how add a password to swagger? 

### ISSUE THREAD

**Issue by stanhjr** [tfranzel/drf-spectacular#1207]
how add a password to swagger? I want the swagger to be password protected, with a custom username and password (without creating a user)

**Comment by tfranzel** [comment]
I believe there is a option in swagger-ui to inject credentials but I am not sure. This is not an drf-spectacular issue. 

use our setting to inject swagger-ui settings: https://github.com/tfranzel/drf-spectacular/blob/06d3b47775c766b6b53a578de11c260a77bed844/drf_spectacular/settings.py#L67
