### ISSUE TITLE
`required=False` and `read_only=True` marks the field required on the generated swagger

### ISSUE THREAD

**Issue by 42454** [tfranzel/drf-spectacular#1210]
**Describe the bug**
When a field in the serializer has `required=False` and `read_only=True`, on the generated swagger the field name goes to the required fields.

**To Reproduce**
```
class Test(serializers.Serializer):
    field = serializers.IntegerField(required=False, read_only=True)
```

**Expected behavior**
The field should be optional. It is logical to have a field that is only for the response and also optional.

**Comment by tfranzel** [comment]
The thing is DRF does not cleanly define this. However, in practice `required` only relates to the request. ReadOnly fields are virtually always present on response even if they are not required. That is the heuristic we chose and that is how DRF behaves absent modifications.

**Comment by 42454** [comment]
Thank you. I use a custom `AutoSchema,` can't I modify that to handle this case?

**Comment by tfranzel** [comment]
If you can accept doing this globally you can enable this setting: `COMPONENT_NO_READ_ONLY_REQUIRED`.
