### ISSUE TITLE
Enum field type incompatible with ENUM_NAME_OVERRIDES

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#122]
dj-stripe has its own enum field type.
https://github.com/dj-stripe/dj-stripe/blob/master/djstripe/enums.py has the type and all of the uses of it.

https://github.com/search?o=desc&q=django+enum&s=stars&type=Repositories for others like it.

```py
SPECTACULAR_SETTINGS = {
    ...
    'ENUM_NAME_OVERRIDES': {
        'SubscriptionStatus': 'djstripe.enums.SubscriptionStatus',
    },
}
```

```py
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 44, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/generators.py", line 165, in get_schema
    result = hook(result=result, generator=self, request=request, public=public)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 578, in postprocess_schema_enums
    overrides = load_enum_name_overrides()
  File "/usr/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 546, in load_enum_name_overrides
    overrides[list_hash(list(dict(choices).keys()))] = name
TypeError: 'EnumMetaClass' object is not iterable
```

If I try `'SubscriptionStatus': 'djstripe.models.billing.Subscription.status.choices',` I see:

Warning #5: unable to load choice override for SubscriptionStatus from ENUM_NAME_OVERRIDES. please check module path string.

Seems a bit hard to debug using that warning.

Luckily I know how to get it out of the field, as this does work:

```py
_fields = [f for f in Subscription._meta.fields if f.name == 'status']
SubscriptionStatus = _fields[0].choices
```

**Comment by tfranzel** [comment]
i see what you did there. nice idea but as you figured its tricky getting info out of models like that. 

you had it almost right. the logic allows you to go one step into the "enum" classes via `getattr`. you could simply do 

```
{'SubscriptionStatusEnum': 'djstripe.enums.SubscriptionStatus.choices',}
```

**Comment by jayvdb** [comment]
My third guess, mentioned above, works fine, is already committed.  I am not seeking help.  I am giving usability feedback.

If you don't see room/reason for improvement, please close.

**Comment by tfranzel** [comment]
because it was not immediately obvious to you i added something to the doc for those cases. the code works fine. imho it was just under-documented. thx.
