### ISSUE TITLE
Apply global headers to all routes except some modules

### ISSUE THREAD

**Issue by Archana-Airbase** [tfranzel/drf-spectacular#1229]
Hi @tfranzel 

Currently I have two modules public and internal APIs as part of the same project. Internal endpoints requires 2 additional headers for all requests but public APIs don't. How should I go about customising schema for both set of endpoints? 

Is it possible to set schema by subclassing the SpectacularAPIView ?

Updating DEFAULT_SCHEMA_CLASS  to custom AutoSchema gets applied to all the endpoints so the approach mentioned [here](https://github.com/tfranzel/drf-spectacular/issues/804#issuecomment-1234469766) overrides the behaviour for public endpoints too.

**Comment by tfranzel** [comment]
Hi, 

so if those headers are for auth, i would try to attach it to the authentication class probably:

https://drf-spectacular.readthedocs.io/en/latest/customization.html#specify-authentication-with-openapiauthenticationextension

you can also do multiple headers there. endpoints are marked automatically then with the required headers.

https://github.com/tfranzel/drf-spectacular/blob/a79bc5d68af5461157bd229429cbb6c1a926ba8b/tests/test_extensions.py#L164

That is if you are able to mark the two sets of endpoints with an individual `authentication_classes` accordingly. The extension can then target those classes. Fyi, they dont need to be different, just an empty subclass would suffice (to make the difference detectable)

If hat that is too complicated, you can also just write a postprocessing hook and attach the headers manually but I would recommend at least trying the first option

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks

**Comment by Archana-Airbase** [comment]
Thanks @tfranzel the first solution worked out.
