### ISSUE TITLE
The URL path is being requested incorrectly.

### ISSUE THREAD

**Issue by saJaeHyukc** [tfranzel/drf-spectacular#1233]
**Describe the bug**

Hello, I'm using drf-spectacular well. I found a bug while using it. 
If I end up sending multiple paths parameter  in the Swagger UI, I'm not getting the correct value. I don't understand.
When I send the request, Django return the NotFound.

**To Reproduce**

```python
# settings.py
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "drf-spectacular API Document",
    "DESCRIPTION": "drf-spectacular API Document",
    "VERSION": "1.0.0",
}

```

```python
# urls.py
urlpatterns = [
    path("<int:post_id_1>/<int:post_id_2>/<int:post_id_3>/", PostListAPI.as_view()),
]
```

```python
# views.py
class PostListAPI(APIView):
    @extend_schema(
        tags=["Post"],        
    )
    def get(self, request, post_id_1, post_id_2, post_id_3):
        return Response(data={"message": "Hello, World!"}, status=status.HTTP_200_OK)
```
![image](https://github.com/tfranzel/drf-spectacular/assets/104830931/84128f9c-6dbb-4ed6-bda4-0a59a289d952)
![image](https://github.com/tfranzel/drf-spectacular/assets/104830931/7cd7b82b-7282-4d20-abbc-994048f256a7)

```plane text
# schema
{
  'operationId': 'posts_retrieve', 
  'parameters': [
    {
      'in': 'path', 
      'name': 'post_id_1', 
      'schema': {'type': 'integer'}, 
      'required': True
    }, 
    {
      'in': 'path', 
      'name': 'post_id_2', 
      'schema': {'type': 'integer'}, 
      'required': True
    }, 
    {
      'in': 'path', 
      'name': 'post_id_3', 
      'schema': {'type': 'integer'}, 
      'required': True
      }
    ], 
  'tags': ['Post'], 
  'security': [
    {'jwtAuth': []}, {}
  ], 
  'responses': {
    '200': {'description': 'No response body'}
  }
}
```
**Expected behavior**
The correct request should be sent, such as `http://127.0.0.1:8000/posts/1/1/1/`.

**Comment by saJaeHyukc** [comment]
I've looked at this and found out that this is a problem with the Swagger UI CDN. If you want to fix it, disconnect the Swagger UI. The `drf-spectacular` has a library that separates it as `drf-spectacular [sidecar]`.


https://drf-spectacular.readthedocs.io/en/latest/readme.html#license:~:text=Self%2Dcontained%20UI,%EF%83%81

**Comment by tfranzel** [comment]
hi! yes, that looks like a swagger-ui issue. However, you don't need to use the sidecar for this. You can also pin the CDN version if you want (instead of latest):

https://github.com/tfranzel/drf-spectacular/blob/9730d39ac48d105cb76d768e63abc099008da17d/drf_spectacular/settings.py#L83

**Comment by saJaeHyukc** [comment]
@tfranzel Thank you for letting me know :) Have a great day!
