### ISSUE TITLE
Different enums for the same field name resolution

### ISSUE THREAD

**Issue by emilgadjzhiev** [tfranzel/drf-spectacular#1234]
**Describe the bug**
I have a choice field which is called assign_to in multiple serializers. This field has different choices in different serializers depending on logic. However, the drf-spectacular throws the warning.
Warning: enum naming encountered a non-optimally resolvable collision for fields named "assign_to". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "AssignToDb2Enum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.
Warning: enum naming encountered a non-optimally resolvable collision for fields named "assign_to". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "AssignTo06dEnum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.

**To Reproduce**
The code related two both serializers:

```python
class FirstSerializer(Serializer):
    assign_to = serializers.ChoiceField(
        label=_("Assign to"),
        choices=FirstChoiceClass.choices,
        required=True
    )
    
class SecondSerializer(Serializer):
    assign_to = serializers.ChoiceField(
        label=_("Assign to"),
        choices=SecondChoiceClass.choices,
        required=True
    )
```
    
 
<img width="682" alt="image" src="https://github.com/tfranzel/drf-spectacular/assets/108130174/4f0bf5ad-a5e8-40ef-b6b9-3c2dea526a9d">
<img width="557" alt="image" src="https://github.com/tfranzel/drf-spectacular/assets/108130174/c4bb44ed-4904-468e-b389-a86260bd96d6">

**Expected behavior**
I would like to resolve the enums properly. I have already tried something like:

```python
    'ENUM_NAME_OVERRIDES': {
        'AssignToDb2Enum': 'some.path.to.first.class',
        'AssignTo06dEnum': 'some.path.to.second.class'
    }
```

Despite the fact that errors are gone it still generates the same documentation where instead of meaningful enums name I have AssignToDb2Enum and AssignTo06dEnum. So is there any way to resolve it and give the proper name to enums? Like AssignToFirstEnum and AssignToSecondEnum?

**Comment by tfranzel** [comment]
Oh... the override names are there for you choice. 

```python
    'ENUM_NAME_OVERRIDES': {
        'YourCategoryNameEnum': 'path.to.FirstChoiceClass',
        'YourOtherCategoryNameEnum': 'path.to.SecondChoiceClass'
    }
```

The `AssignToDb2Enum ` was our name resolution. The override is there to give your custom names. The warning goes away if an override was found for that choice.

**Comment by emilgadjzhiev** [comment]
Thank you, it's exactly what I wanted to achieve
