### ISSUE TITLE
Is it possible to generate a component schema directly from a serializer class? 

### ISSUE THREAD

**Issue by james-mchugh** [tfranzel/drf-spectacular#1238]
**Describe the bug**
My project currently uses DRF Spectacular for generating an OpenAPI spec and Swagger Docs page. Thank you for making that very easy.

What I would like to be able to do now though is get a component schema for an individual serializer class. For example, something like this

```python
serializer_component_schema = to_schema(MySerializerClass)
```

Is that possible?

I tried doing something like,

```python
a = AutoSchema()
a.registry = ComponentRegistry()

component = a.resolve_serializer(MySerializerClass, "response)
```

But it was unhappy that no view was set.

Sorry if this is already somewhere in the docs, but I did try looking for it, going through issues, and exploring the code to see how this could be done prior to opening this issue.

Thank you!

**Comment by tfranzel** [comment]
Hi, spectacular is not designed to be executed standalone on a serializer. There is a lot of stuff happening in the background with regards to paths, methods, direction, views, querysets, etc. The task is somewhat underspecified, if you want to do it right. This will give you something, but with no guarantees. Your mileage may vary.

```python
    insp = AutoSchema()
    insp.registry = ComponentRegistry()
    insp.view = APIView()
    insp.view.request = build_mock_request("GET", "/", insp.view, None)
    insp.resolve_serializer(MySerializerClass, "request")
    schema = insp.registry.build({})
```
