### ISSUE TITLE
Pydantic 2 @computed_field not detected

### ISSUE THREAD

**Issue by andreasnuesslein** [tfranzel/drf-spectacular#1258]
Hi there!,

first of: thanks so much for this package :)

So, I'm using the `@extend_schema_field` and everything works fine except  `@computed_field` is not detected

**To Reproduce**
```python
from pydantic import BaseModel
class TestModel(BaseModel):
    number: int

    @computed_field
    @property
    def twice(self) -> bool:
        return number * 2
```

The resulting schema.yaml will not include "twice"

If it helps, I can try to create a PR.

Cheers

**Comment by tfranzel** [comment]
Hi @andreasnuesslein 

So we actually don't do that much with pydantic. We use the schema generated by pydantic and just shape it a bit. But you're welcome to investigate why exactly this does not show up. Here is the code handling pydantic:

https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/contrib/pydantic.py

Let me know what you find out even if you decide not to do a PR. thanks

**Comment by andreasnuesslein** [comment]
Hi @tfranzel  thanks for your response!

so I investigated a bit and the solution seems simple.

According to this: https://github.com/pydantic/pydantic/discussions/6298#discussioncomment-6315361

it'd be:
```diff
- schema = model_json_schema(self.target, ref_template="#/components/schemas/{model}")
+ schema = model_json_schema(self.target, mode='serialization', ref_template="#/components/schemas/{model}")
```

which for me yields in this case the right result (difference):
![image](https://github.com/tfranzel/drf-spectacular/assets/320080/cd104e07-ab74-4d95-80cc-6bf3ff6c7373)

However I dont really know if the implications are bigger than just that...

**Comment by tfranzel** [comment]
thanks for investigating @andreasnuesslein.

So as a matter of fact we already have an open PR (#1156) for this change, even though for a different reason. 

I think with your point on top, it now makes it so that the benefits outweigh the potential issues of the change.

**Comment by andreasnuesslein** [comment]
@tfranzel ps: which cableway site is that in your buddy icon? reminds me a bit of Rossau.

**Comment by tfranzel** [comment]
hehe, that picture was taken in Niederweimar near Marburg.

**Comment by andreasnuesslein** [comment]
🤙 okay, yeah have not been there :see_no_evil:
