### ISSUE TITLE
Error when open Redocs

### ISSUE THREAD

**Issue by danilocastelhano1** [tfranzel/drf-spectacular#127]
Morning guys, it's me again lol
I'm trying to see my redocs, but when i type in url the path to my redocs, open as JSON

My urls.py:
```
    url(r'^swagger/', SpectacularSwaggerView.as_view(url_name='schema-swagger-json'), name='schema-swagger-ui'),
    url(r'^swagger2.yaml$', SpectacularAPIView.as_view(), name='schema-swagger-yaml'),
    url(r'^', SpectacularJSONAPIView.as_view(), name='schema-swagger-json'),
    url(r'^redocs/', SpectacularRedocView.as_view(url_name='schema-swagger-yaml'), name='schema-redoc'),
```
When i open 127.0.0.1:800/swagger/ it's OK
When i open 127.0.0.1:800/redocs/ Open as JSON

Thx again

![image](https://user-images.githubusercontent.com/52941839/87548201-88b78c80-c682-11ea-93e6-3b56691ad8ea.png)

**Comment by danilocastelhano1** [comment]
Fixed, for some reason the  patter has to be the last url in my patterns, don't me ask why lol
```
    # Optional UI:
    url(r'^swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    url(r'^redocs/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    # YOUR PATTERNS
    url(r'^', SpectacularJSONAPIView.as_view(), name='schema'),
```

**Comment by tfranzel** [comment]
@danilocastelhano1 that makes sense. i was surprised by the problem. that is in fact a Django thing and has nothing to do with drf-spectacular.  pretty sure `r'^'` functions as a catch-all before `^redocs/` is even tried.
