### ISSUE TITLE
How is it possible to close all groups at Swagger's opening? 

### ISSUE THREAD

**Issue by amirhoseinbidar** [tfranzel/drf-spectacular#1271]
Maybe it's a silly question, but how can I inform DRF-Spectacular to make all groups closed when opening Swagger? It seems that every time I request Swagger, it opens all groups, and since I have a lot of APIs, navigation becomes a real disaster. Is there any setting?

Thanks for your great module. Best regards.

**Comment by amirhoseinbidar** [comment]
I found out that it can be disabled in setting.

SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_SETTINGS": {"docExpansion": "none"},
}

Isn't it better to make it as default setting?

**Comment by tfranzel** [comment]
Hi,

I think that is just your preference and others might see it differently. Apart from that we use the defaults that SwaggerUI provides as they decide what a good base setup is. I don't really see the need to impose my particular preferences onto our users. If you think this should be the default, maybe raise this issue upstream with SwaggerUI. 

But thanks for your kinds words and consideration.
