### ISSUE TITLE
Need help in creating a Swagger for tastypie APIs with Django version 1.7

### ISSUE THREAD

**Issue by sjaiswal03** [tfranzel/drf-spectacular#1274]
Hi team,
I am struggling to integrate a swagger with Django version 1.7. We are using tastypie APIs and we are limited to django version 1.7.
We explored a couple of open-source tools like drf-yasg, drf-spectacular, and tastypie-django-swagger. 
Here are the details from our findings in short.
drf-yasg and drf-spectacular tools require a minimum Django version of 1.11. However, our codebase currently supports Django 1.7, which is outdated. We do not have an immediate plan to upgrade. Despite attempting to use the earliest version of the tools and employing version hacks, we encountered multiple issues that persisted through several iterations and may require substantial effort to resolve. Additionally, a significant challenge arises from the fact that the REST framework utilized in our codebase is tastypie, which operates differently from Django Rest Framework. Consequently, it may not be able to generate the schema for tastypie-based resources due to differences in definition formats or serializers.

Any help or documentation from your team will be of great help to us. 
Thanks in Advance!!!

**Comment by tfranzel** [comment]
Hi,

Django version 1.7 is almost 10 years old and probably unsupported for ~8 years. Too much of Django internals have changes in this time. Also, `drf-spectacular` is 100% `Django REST Framework` dependant. There was never any tastiepie support nor will there be.

Sorry to say but this is thoroughly out of scope and you are unfortunately on your own with this.
