### ISSUE TITLE
Extra suffix added to URL paths in OpenAPI schema with GenericViewSet and HTTP methods

### ISSUE THREAD

**Issue by dsuleimenov** [tfranzel/drf-spectacular#1276]
Hello!

**Describe the bug**

When using a `GenericViewSet`, the OpenAPI schema incorrectly appends HTTP method suffixes to the URL paths, resulting in the following formats:

```
https://{host}/{path}/get/
https://{host}/{path}/post/
https://{host}/{path}/patch/
https://{host}/{path}/put/
https://{host}/{path}/delete/
```

However, the actual API endpoints can be accessed without these suffixes, as shown below:

```
https://{host}/{path}/
```

**To Reproduce**

Here’s a minimal example to reproduce the issue:

```
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.routers import DefaultRouter
from rest_framework.viewsets import GenericViewSet


class BookViewSet(GenericViewSet):

    @action(methods=['get'], detail=False)
    def get(self, *args, **kwargs) -> Response:
        ...

    @action(methods=['post'], detail=False)
    def post(self, *args, **kwargs) -> Response:
        ...

    @action(methods=['patch'], detail=False)
    def patch(self, *args, **kwargs) -> Response:
        ...

    @action(methods=['put'], detail=False)
    def put(self, *args, **kwargs) -> Response:
        ...

    @action(methods=['delete'], detail=False)
    def delete(self, *args, **kwargs) -> Response:
        ...


router = DefaultRouter()
router.register(r'books', BookViewSet, basename='books')
```

**Expected behavior**
The URL paths in the OpenAPI schema should match the actual API paths, without appending extra method suffixes like `/get/`, `/post/`, `/patch/`, `/put/`, or `/delete/`.

**Comment by tfranzel** [comment]
Hi! That is exactly what your view there does, so the **schema is indeed correct**. 

I understand what you ask for, but your view does not do what you think it does. The `action` decorator is not needed and actually makes this wrong; and the methods should be called `list`, `retrieve`, ... instead of `get`, `post`, .... .  
`get`, `post`, etc are for use with `GenericAPIView`.

This sounds to me that you are missing the basics on how DRF works. You should probably do a DRF tutorial first.

**Comment by dsuleimenov** [comment]
Hi @tfranzel!

I need to implement the `update` or `partial_update` methods in Django REST Framework (DRF) without using a `lookup_field`. In my case, each account has only one associated dashboard view setting, so the URL path should not include the `dashboard_view_setting_id`.

Instead of this:

```
PUT /api/v1/accounts/{account_id}/dashboard_view_settings/{dashboard_view_setting_id}/
```

I need the endpoint to look like this:

```
PUT /api/v1/accounts/{account_id}/dashboard_view_settings/
```

Since setting `lookup_field = ''` doesn't work in DRF, I plan to use the `patch` or `put` methods in GenericAPIView to handle this.
