### ISSUE TITLE
Not satisfied with generated schema

### ISSUE THREAD

**Issue by sau0409** [tfranzel/drf-spectacular#1279]
Hi, I am working on integrating drf-spectacular with my code-base, only problem I am having is I am not satisfied with the generated schema. Is there a flow to update the schema manually ?

**Comment by MattyCZ** [comment]
You can use extensions, the whole customization process is very well [documented](https://drf-spectacular.readthedocs.io/en/latest/customization.html). You can hook into serializers, fields and many more things
