### ISSUE TITLE
Reverse isn't working with configuration from documentation

### ISSUE THREAD

**Issue by mglowinski93** [tfranzel/drf-spectacular#1281]
**Describe the bug**
I can't make `reverse` working with configuration provided from documentation.

```python
api_swagger_urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"
    ),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

api_urlpatterns = [
        path(
            "",
            include(api_swagger_urlpatterns),
        ),
       path("some-other-api/", include((some_other_urls, "some_other_apis"), namespace="some_other_apis")),
]

urlpatterns = [
    path("health-check/", health_check, name="health-check"),
    path("api/", include(api_urlpatterns)),
]
```

It says that neither `pattern` nor `url name` are found.

**To Reproduce**
Configure it like in upper snippet and try to use

```python
from django.urls import reverse

reverse("swagger-ui")
```

**Expected behavior**
It would be great to have in documentation a working example of URL which can be reversed.

**Comment by tfranzel** [comment]
Hi, unfortunately I cannot reproduce your issue.

```python
urlpatterns += [
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]

from rest_framework.reverse import reverse

print(reverse("schema"))
print(reverse("swagger-ui"))

from django.urls import reverse

print(reverse("schema"))
print(reverse("swagger-ui"))

```

returns just as expected

```
backend-1        | Watching for file changes with StatReloader
backend-1        | /api/schema/
backend-1        | /api/schema/swagger-ui/
backend-1        | /api/schema/
backend-1        | /api/schema/swagger-ui/
backend-1        | System check identified no issues (0 silenced).
```

As a control I checked for an unknown route and it throws:

```
print(reverse("error"))

django.urls.exceptions.NoReverseMatch: Reverse for 'error' not found. 'error' is not a valid view function or pattern name.
```

Please try again to make it reproducible.

**Comment by mglowinski93** [comment]
@tfranzel Please notice, that you added path directly to `urlpatterns`.
In my case, it's kind of nested.

Seems like that is the issue.

**Comment by tfranzel** [comment]
have you tried using the DRF version and not the Django version of `reverse`?

```python
urlpatterns.append(
    path("api/", include(urlpatterns_for_schema))
)
```

Works the same for me with or without the nesting. 

I not sure this is an issue on our side, since our views do nothing special in that regard. Your `reverse` not finding them may indicate issues within your project setup and not with drf-spectacular in general.

**Comment by mglowinski93** [comment]
Yes, I tried.

Strange, in my case it can't be found.
I'm using Django 5 and DRF 3.X.

Ok, if you say so, it might be. Nevertheless, I have exactly the configuration which I posted here.

**Comment by tfranzel** [comment]
I see. My example ran with `Django=5.1.0` and `DRF=3.15.2`. Sorry, but "works on my machine" 😄 

If you can make it reproducible with a minimal self-contained example we can look at it again.  I can't do much without it.

**Comment by mglowinski93** [comment]
Sorry for losing your time!

I found the root cause.
It occurred, that `overwriting_settings` does not reload the settings.

After I did it manually, it worked.

Thank you one more time.
