### ISSUE TITLE
False positive duplicate Serializer warning when `DataclassSerializer` used both as top level Serializer and nested within another dataclass

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#1288]
**Describe the bug**

For code reuse, it's often useful to expose endpoints for the same data at different layers within the overall tree of data. If a `DataclassSerializer` is used for both a parent `@dataclass` and a child `@dataclass` a warning is printed.

**To Reproduce**

```py
from dataclasses import dataclass

from drf_spectacular.utils import extend_schema
from rest_framework.decorators import api_view
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework_dataclasses.serializers import DataclassSerializer


@dataclass
class Person:
    name: str
    age: int


@dataclass
class Party:
    person: Person
    num_persons: int


class PartySerializer(DataclassSerializer[Party]):
    class Meta:
        dataclass = Party


class PersonSerializer(DataclassSerializer[Person]):
    class Meta:
        dataclass = Person


@extend_schema(responses=PartySerializer)
@api_view()
def party(request: Request) -> Response:
    pass


@extend_schema(responses=PersonSerializer)
@api_view()
def person(request: Request) -> Response:
    pass
```

Results in a warning when the OpenAPI spec is queried:

```
views/api/test.py: Warning [person > PersonSerializer]: 
Encountered 2 components with identical names "Person" and different classes <class 'views.api.test.PersonSerializer'> and <class 'rest_framework_dataclasses.serializers.DataclassSerializer'>. 
This will very likely result in an incorrect schema. Try renaming one.
```

But, in this case, we _do_ want to represent the same original `@dataclass` in both endpoints and have them generate the same `Person` object in the OpenAPI spec (i.e. we wouldn't want to generate two types in the API when really we mean a single type that we want clients to use interchangeably).

Also, as far as I can tell, the actual OpenAPI spec _is_ generated correctly, the warning is the only issue. But of course if this is not documented/tested behavior of `drf-spectacular` that would give me pause, thus why I wanted to report the issue.

The code in question is located at

https://github.com/tfranzel/drf-spectacular/blob/2b4d5abec7326b415df7247a1f09b6d977ba7bd7/drf_spectacular/plumbing.py#L756-L761

**Expected behavior**

No warning printed.

**Environment**

- Python 3.11.8

```
drf-spectacular                 0.27.2
djangorestframework-dataclasses 1.3.1
djangorestframework             3.15.2
```

**Comment by tfranzel** [comment]
Hi @johnthagen,

I see the problem. In the beginning when we had only actual serializers this made perfect sense. If you have a different serializer class under the same name that is likely gonna be an issue. Here, `Person` will get converted to a serializer twice (one directly and one indirectly) and those are different, albeit functional identical classes and so the check give a false positive.

The object check in the registry would need to compare the `Person` dataclass instead of the generated serializer to make this correct. I think we can do this.

**Comment by johnthagen** [comment]
@tfranzel Wanted to check back in on this. I see some commits referencing this issue in `main`. If this issue should be fixed in `main` I'm happy to test that out prior to the next release.  Thanks.

**Comment by tfranzel** [comment]
Hi! As far as I am concerned, this is done and working. I have been trying to find time to do a release. If you want to validate this fix prior to release, I recommend doing it soon.

**Comment by johnthagen** [comment]
@tfranzel I tested out `master` using

```
python -m pip install git+https://github.com/tfranzel/drf-spectacular.git
```

And confirmed the warning is gone in our production application that exhibited this symptom.

Thanks!

**Comment by tfranzel** [comment]
Hey John, sry this takes so long. I will see to it that I get this done soon. Just have to fix this one open thing.

**Comment by johnthagen** [comment]
@tfranzel Wanted to confirm that 0.28 fixed this issue in our application. Thanks! ❤️

**Comment by mattiabaldari** [comment]
@tfranzel just to let you know that we are still facing this issue with

* Python                 `3.12.7`
* drf-spectacular                 `0.28.0`
* djangorestframework-dataclasses `1.3.1`
* djangorestframework             `3.15.2`

**Comment by tfranzel** [comment]
@mattiabaldari please provide a reproduction, as this was tested and confirmed working by @johnthagen and myself.

here is the working test: https://github.com/tfranzel/drf-spectacular/pull/1290/files#diff-66b971a5c6120dc55ecf8b2607a4eff45b543916ea59860a6e952217acc2d24d

the tests ran for `1.3.1` and all other versions you specified.
