### ISSUE TITLE
extend_schema_field to self

### ISSUE THREAD

**Issue by zamoosh** [tfranzel/drf-spectacular#1301]
Hello, I have my models like:

```py
class File(models.Model):
    # ...
    parent = ForeignKey("self", on_delete=models.DO_NOTHING, null=True)
    # ...
```

I wanted to generate schema swagger for this model to contain the field parent (not as int or string).

Here is what I've done:
```py
class ReadFileSerializerAdmin(serializers.ModelSerializer):
    class Meta:
        model = File
        fields = ["id", "owner", "name", "path", "full_path", "uuid", "type", "created_at", "updated_at", "file_group", "parent"]

    parent = serializers.SerializerMethodField()

    @extend_schema_field("self")
    def get_parent(self, obj: File):
        if obj is None:
            return None

        return ReadFileSerializerAdmin(obj).data
```

Description: 
in `get_parent`, I'm returning `ReadFileSerializerAdmin`. But when I want to use `@extend_schema_field` with `field` to "self", drf_spectacular says:

Warning [FileApi > ReadFileSerializerAdmin]: unable to resolve type hint for function "get_parent". Consider using a type hint or @extend_schema_field. Defaulting to string.

Is there any way to use `extend_schema_field` to self? 

note: I know it's just a warning, but I want to generate ti as well... and thank you any way!🙏

**Comment by tfranzel** [comment]
Hi, I don't think the decorator is necessary actually. How about

```python
...
parent = serializers.SerializerMethodField()

def get_parent(self, obj: File) -> "ReadFileSerializerAdmin":
...
```

that should be picked up correctly. `@extend_schema_field` does not take strings. You might use our helper 

```python
@extend_schema_field(lazy_serializer("path.to.ReadFileSerializerAdmin"))
```

but I would prefer the type annotation.

**Comment by zamoosh** [comment]
Oh I see!

Thanks a lot @tfranzel. The `type annotation` just worked! I would use `type annotation` rather than `@extend_schema_field` for future!🙏
