### ISSUE TITLE
OAS 3.1.0 output: `maxLength` constraint not saved to schema for nullable string field

### ISSUE THREAD

**Issue by bartvanandel** [tfranzel/drf-spectacular#1302]
**Describe the bug**
We have several string fields in our API that are nullable (i.e., optional), but also have a max length. When using OAS 3.0.3 as the target schema version, this works fine, however with OAS 3.1.0, no `maxLength` is stored. For non-nullable fields, `maxLength` is stored properly.

I expect more constraints (e.g., `minLength` should be obvious) are also dropped from the schema. Format specifiers (such as `type: email`), `readOnly`, `writeOnly` and probably other specs work fine for nullable fields across OpenAPI versions, so there must be something special about constraint handling.

**To Reproduce**

Python code:
```py
# Inside some model:
class Team(models.Model):
    phone_number = models.CharField(null=True, blank=True, max_length=40)
```

Excerpt from generated OAS 3.0.3 schema:
```openapi
    TeamRequest:
      type: object
      properties:
        phone_number:
          type: string
          nullable: true
          maxLength: 40
```

Same excerpt from generated OAS 3.1.0 schema:
```openapi
    TeamRequest:
      type: object
      properties:
        phone_number:
          type:
          - string
          - 'null'
```

**Expected behavior**
Expected output should include `maxLength` constraint.
If I understand the OpenAPI specs correctly (hints taken from [this OpenAPI Spec question](https://github.com/OAI/OpenAPI-Specification/issues/3148)), this concise form should be fine:
```openapi
    TeamRequest:
      type: object
      description: Team info
      properties:
        phone_number:
          type:
          - string
          - 'null'
          maxLength: 40
```

If you want to be more explicit, this should work as well:
```openapi
    TeamRequest:
      type: object
      description: Team info
      properties:
        phone_number:
          oneOf:
          - type: string
            maxLength: 40
          - 'null'
```

**Comment by bartvanandel** [comment]
Thanks for picking this up, your fix looks fine to me.

Is there something up with Codecov though? That one task has been pending for over 9 days now on your commit.

**Comment by tfranzel** [comment]
codecov stalls sometimes. I have updated the GH action and did a fresh setup procedure. It worked a couple of times but it is still not 100% right. idk, this has worked flawlessly for years. we certainly didn't change anything.

**Comment by bartvanandel** [comment]
Excuse the pause. I've just tested this locally, with our actual API, and your fix works fine indeed.

Excerpt from before the fix:

```yaml
website:
  type:
  - string
  - 'null'
  format: uri
```

With fix applied:

```yaml
website:
  type:
  - string
  - 'null'
  format: uri
  maxLength: 250
```

So, clear for take-off I guess! 🚀
