### ISSUE TITLE
Decimal and multipleOf

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#131]
multipleOf is [defined as](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.2.1)

> The value of "multipleOf" MUST be a number, strictly greater than 0.
> A numeric instance is valid only if division by this keyword's value results in an integer. 

And number is defined as whole numbers, distinct from floats.

The [use of](https://github.com/tfranzel/drf-spectacular/blob/67d638d/drf_spectacular/openapi.py#L523) this for decimal `.decimal_places` results in invalid OpenAPI schemas.  A regex validator would be the way to achieve this.

**Comment by tfranzel** [comment]
not exactly sure how to read this. the json-schema also specifies this:

> String values MUST be one of the six primitive types ("null", "boolean", "object", "array", "number", or "string"), or "integer" which matches any number with a zero fractional part.

"integers are numbers with zero fractional part" indicates the opposite. so i'm not so sure if numbers are actually defined as whole numbers as you say. my understanding is that `number` contain both integers and floats.
However, the usage of `multipleOf` in conjunction with below zero numbers clearly violates the schema. that's for sure. 

maybe the best course of action is simply removing the `multipleOf`.

**Comment by jayvdb** [comment]
Ah, sorry, yes "And number is defined as whole numbers, distinct from floats." was very muddled up, and unnecessary for this context.

**Comment by tfranzel** [comment]
so just to clarify. you do also agree to remove `multipleOf`as the most sensible solution, right?

**Comment by jayvdb** [comment]
Removal of these `multipleOf` is mandatory, it seems.

Above I suggested using a regex validator in its place.  i.e. a `pattern`

**Comment by tfranzel** [comment]
i opted for removal without a custom regex for simplicity's sake. please close if that works for you. thanks.

**Comment by jayvdb** [comment]
:+1:
