### ISSUE TITLE
Exclude `readOnly` fields from requests

### ISSUE THREAD

**Issue by salomvary** [tfranzel/drf-spectacular#1318]
I do not see any reason why `readOnly` fields should be part of schemas that are exclusively used for requests, like `PatchedX`:

For example: https://github.com/tfranzel/drf-spectacular/blob/master/tests/test_basic.yml#L218-L242

I have not found tests for `readOnly` fields in `XRequest` schemas when `COMPONENT_SPLIT_REQUEST=True` but I assume `readOnly` fields should be excluded there too.

(Happy to attempt a pull request if this change is considered to be useful/acceptable.)

**Comment by tfranzel** [comment]
Hi,

> I do not see any reason why readOnly fields should be part of schemas that are exclusively used for requests, like PatchedX

Interesting. So Patched is a bit special in that it is not used for responses, that is true. Afais it is the one exception to the rule.

> I have not found tests for readOnly fields in XRequest schemas when COMPONENT_SPLIT_REQUEST=True but I assume readOnly fields should be excluded there too.

This is kind of the definition of `COMPONENT_SPLIT_REQUEST=True`. There should never be a `readOnly` on a `XRequest` serializer as they are removed in the process of creating the component.

> (Happy to attempt a pull request if this change is considered to be useful/acceptable.)

I don't think the patched case warrants complicating the implementation. It should make little to no difference in practice. If you really care about accurate serializers and proper `readOnly`/`writeOnly`/`required` markers, you have to turn on  `COMPONENT_SPLIT_REQUEST` anyway.

**Comment by salomvary** [comment]
> I don't think the patched case warrants complicating the implementation.

Cool, thanks for the response! I only had a brief look at the implementation, and this change did not seem trivial indeed (although I am not familiar with the internals at all).

Because I've spent about an hour trying to clear some confusion from the consumers of the API I am building, I added a postprocessor as a workaround, so that I don't have to explain this again to anyone :)

(And because almost all of our "update" endpoints are PATCH, not PUT as the latter seems to be implemented with non-strict semantics that was closer to PATCH).

```python
def postprocess_remove_read_only_from_request(result, **_kwargs):
    """
    Remove readOnly properties for schemas that are only used for request bodies.
    """
    schemas = result.get("components", {}).get("schemas", {})

    for schema_name, schema in schemas.items():
        if (
            _used_for_request_only(schema_name)
            and schema.get("type") == "object"
            and schema.get("properties")
        ):
            schema["properties"] = {
                prop_name: prop
                for prop_name, prop in schema["properties"].items()
                if not prop.get("readOnly")
            }

    return result


_PATCHED_RE = re.compile(r"^Patched.+")


def _used_for_request_only(schema_name):
    # We could be more clever and see if the schema is used as part
    # of a response body, but it gets complicated
    # as schemas can be nested, and we would need to traverse
    # the entire schema tree. For now we only skip
    # patch request body schemas, which can be determined by the schema name.
    return bool(_PATCHED_RE.match(schema_name))
```

**Comment by salomvary** [comment]
As a companion to this, when `COMPONENT_SPLIT_REQUEST=True`, _response_ schemas should ideally not contain `writeOnly: true` fields at all.

**Comment by tfranzel** [comment]
> (And because almost all of our "update" endpoints are PATCH, not PUT as the latter seems to be implemented with non-strict semantics that was closer to PATCH).

In general, PUT is meant to fully replace an existing resources, while PATCH targets individual fields on that resource and leaves the rest untouched. Just as a clarification. That is why we remove the `required` list from the dedicated PATCH serializers.

> As a companion to this, when COMPONENT_SPLIT_REQUEST=True, response schemas should ideally not contain writeOnly: true fields at all.

Pretty sure we remove `writeOnly` on responses when `COMPONENT_SPLIT_REQUEST=True`.  I don't think there are any exceptions. Please provide an example or reproduction as we would consider this a bug.

**Comment by salomvary** [comment]
> > (And because almost all of our "update" endpoints are PATCH, not PUT as the latter seems to be implemented with non-strict semantics that was closer to PATCH).
> 
> In general, PUT is meant to fully replace an existing resources, while PATCH targets individual fields on that resource and leaves the rest untouched. Just as a clarification. That is why we remove the `required` list from the dedicated PATCH serializers.

Yep, that's clear to me. What I mean by non-strict semantics is the DRF behavior of allowing nullable fields and fields with default values to be absent from PUT and POST responses. Whether that is correct/desired depends on one's opinion, but it is correctly documented by DRF spectacular. (One might want POST and PUT requests bodies to include all fields, including ones that are nullable, not trivially possible with DRF as far as I know.)

Anyway, this is not closely related to the problem I was outlining here, just the reason for our preference for PATCH as opposed to PUT.

> 
> > As a companion to this, when COMPONENT_SPLIT_REQUEST=True, response schemas should ideally not contain writeOnly: true fields at all.
> 
> Pretty sure we remove `writeOnly` on responses when `COMPONENT_SPLIT_REQUEST=True`. I don't think there are any exceptions. Please provide an example or reproduction as we would consider this a bug.

I've double checked this and there are indeed no `writeOnly` fields included in responses.
