### ISSUE TITLE
Swagger-ui template not working after Swagger-UI version: 3.30.1

### ISSUE THREAD

**Issue by demmojo** [tfranzel/drf-spectacular#132]
**Describe the bug**
When opening a path that is in a tag “group”, it disappears and then reappears underneath the default tag.

The issue has been reported in swagger-ui [#6249](https://github.com/swagger-api/swagger-ui/issues/6249) and in fastapi [#1762](https://github.com/tiangolo/fastapi/issues/1762)

**To Reproduce**

1. Go to a path in a tag “group”
2. Click on the path item
3. See error: the path item will disappear and reappear under a new default tag group.
4. The path item under the default tag will sit and spin.

**Expected behavior**
The path item should open in place.

**Screenshot**
![image](https://user-images.githubusercontent.com/30584067/88169078-19aeda80-cc24-11ea-9771-faa7d255e71f.png)

**Potential fix**
We could pin the swagger-ui unpkg URL to 3.30.0 in the [swagger_ui.html](https://github.com/tfranzel/drf-spectacular/blob/5679b0af329106ec1f5da5cb279584190106be96/drf_spectacular/templates/drf_spectacular/swagger_ui.html) found inside drf-spectacular's templates.

**Comment by tfranzel** [comment]
@demmojo thanks for bringing that up! PR looks good. it is likely severe enough to do a new package release, but i'll have to write release notes first because there is a small breaking change in there. will do later today.

**Comment by demmojo** [comment]
Thanks for the quick response @tfranzel! 

If anyone needs something that works until the PR is accepted you can do the following:

1. Save the updated [swagger_ui.html](https://github.com/demmojo/drf-spectacular/blob/master/drf_spectacular/templates/drf_spectacular/swagger_ui.html) template file somewhere in your project (example code below stores in 'project/templates' folder). 

2. Add the saved template directory to settings.py
```
TEMPLATES = [
    {    

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'project/templates')], 
        ...
```
3. Subclass **SpectacularSwaggerView** like below in project's urls.py:


```
class CustomSpectacularSwaggerView(SpectacularSwaggerView):

    template_name = 'swagger_ui.html'

```

**Comment by demmojo** [comment]
Thanks for the quick response @tfranzel! 

If anyone needs something that works until a release is made you can do the following:

1. Save the updated [swagger_ui.html](https://github.com/demmojo/drf-spectacular/blob/master/drf_spectacular/templates/drf_spectacular/swagger_ui.html) template file somewhere in your project (example code below stores in 'project/templates' folder). 

2. Add the saved template directory to settings.py
```
TEMPLATES = [
    {    

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'project/templates')], 
        ...
```
3. Subclass **SpectacularSwaggerView** like below in project's urls.py:


```
class CustomSpectacularSwaggerView(SpectacularSwaggerView):

    template_name = 'swagger_ui.html'

```

**Comment by tfranzel** [comment]
@demmojo drf-spectacular 0.9.12 is released and includes the fix.

**Comment by demmojo** [comment]
Can confirm that it work! Thanks @tfranzel  so much for getting a release out so quick! Closing the issue now.
