### ISSUE TITLE
Many=True paginates by default

### ISSUE THREAD

**Issue by yoelfme** [tfranzel/drf-spectacular#1321]
**Describe the bug**
Hey, thank you for this amazing project, my issue is that when I define a endpoint with the extended schema like this:

```python
    @extend_schema(
        responses={
            200: MenuItemSerializer(many=True),
        }
    )
    @action(["get"], url_path="menu-items", detail=False)
    def get_menu_items(self, request, *args, **kwargs):
        services = Service.objects.filter(
            property=self.request.property
        )
        serializer = MenuItemSerializer(services, many=True)
        return Response(serializer.data)
```

This is the serializer:
```python
class MenuItemSerializer(serializers.Serializer):
    url = serializers.CharField(read_only=True)
    text = serializers.CharField(read_only=True)
    icon = serializers.CharField(read_only=True)
```

The generated example response in the Swagger UI is :

![Screenshot 2024-10-27 at 11 53 02 PM](https://github.com/user-attachments/assets/d0f89c4d-fe5a-45c9-86dd-214ef5f0ed6c)

And the real response is this one:
![Screenshot 2024-10-28 at 12 01 51 AM](https://github.com/user-attachments/assets/f99a8b82-292e-4828-8421-ea2bbfa5694a)

I don't know how is detecting the pagination by default, or how to diable it? I'm just passing `Serializer(many=True)` does that means that it will paginate by default?

**Expected behavior**
I expect the example response is just a list of objects, like this:

```json
[
    {
      "url": "string",
      "text": "string",
      "icon": "string"
    }
  ]
```
The screenshots are from a test project.

**Comment by tfranzel** [comment]
Hi, thanks.  Since you likely have pagination on the view, it is assumed to be applied also on the custom actions. If that is not desired,
you can tell DRF this does not apply here by telling it to `@action` with `pagination_class=None`. It basically reverts what was set in the view prior.

https://github.com/tfranzel/drf-spectacular/blob/27ae6f293a6e8731649216d62ba2a5c8d65691e6/tests/test_regressions.py#L1227-L1237

**Comment by yoelfme** [comment]
Hey @tfranzel, thank you for yor answer, it helped me a lot :D

**Comment by adamJLev** [comment]
I could not get this to work no matter how hard I tried, no matter what - my non paginated endpoint would show up as paginated even when passing `pagination_class=None` to the @action.

So in case this helps anyone else, I ended up adding this to my viewset:

```
    @property
    def pagination_class(self):
        # Workaround to make swagger docs more accurate
        if self.action == "list":
            return ApiPagination
        return None
```

I tried exactly what you showed above and also read all the FAQs related to pagination but no luck.
cheers

**Comment by tfranzel** [comment]
@adamJLev if you post a reproduction, I can have a look. Though, I am pretty confident this works as described, unless you do something special here. 

Every endpoint will get it's own copy instance of the view, and passing `pagination_class=None` to `@action` will reset that class attribute on that particualar instance. If nothing else is going on, the `pagination_class` cannot be found anymore on that instance, so in theory it is impossible to happen then.
