### ISSUE TITLE
Weird issue when generating the schema

### ISSUE THREAD

**Issue by yoelfme** [tfranzel/drf-spectacular#1326]
**Describe the bug**
I'm having a hard time but when I generate the schema from the Swagger UI, I got the correct schema (that includes the filter fields that I defined in a FilteSet class). 
![Screenshot 2024-11-07 at 1 53 15 AM](https://github.com/user-attachments/assets/82821e89-e79e-4eab-9db0-cfb34447c1b8)

Then also the Swagger UI gives me a snippet to make the requests, but when I do the request the schema is different, and I don't really know what is happening.

![Screenshot 2024-11-07 at 1 50 56 AM](https://github.com/user-attachments/assets/7f59ea1d-c419-42ab-baef-ae4c48b8d078)

**To Reproduce**
Try to add a Filter class to a View and get the schema from the UI (check the schema generated), and then copy the snippet provided by the Swagger UI, save the curl response and compare the schemas, they are different.

**Expected behavior**
I expect the schema file should be the same if I get it from the Swagger UI, than doing a curl request.

Thank you so much for your help, and for this amazing project.

**Comment by yoelfme** [comment]
Oh I see, the issue is that if I log into the `admin`, and then I refresh dhe Swagger UI, fhe filters are shown in the UI, but if I'm not logged in doesn't show anything.

**Comment by tfranzel** [comment]
In theory, both routes should create the same schema. There is very little difference there except for some optional settings overrides and such.

In case you have `SERVE_PUBLIC` set to false, the schema is dependent on the requesting user. This might be the source for the difference, if one request is authenticated and the other is not. If you are not logged in via swagger (but with a django cookie), swagger UI cannot be aware of that and will not reload the page automatically.

**Comment by yoelfme** [comment]
I didn't modify the default values, so `SERVE_PUBLIC` is `True`, I have a permission_class in that Viewset maybe that's the issue. I fixed the issue by adding this:

```python
@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(name='param_1', description='Filter by param 1', required=False, type=OpenApiTypes.DATE)
        ],
    )
)
```

**Comment by tfranzel** [comment]
I see. In that case it should be equal because everybody will get the same schema, authed, unauthed, it does not matter. `permission_classes` should be considered in the schema, but should never make some things disappear.

Unless you can provide a reproduction, there is not really much I can do about it.

**Comment by yoelfme** [comment]
The issue with filters not appearing for unauthenticated users in Swagger UI was due to the `get_queryset` method in the viewset, which initially depended on `self.request.user`. This caused the queryset to vary between authenticated and unauthenticated states, leading to inconsistencies in the OpenAPI schema generation.

In the original code, the `get_queryset` method filtered results based on the currently authenticated user:

```python
def get_queryset(self):
    # Filters objects based on the authenticated user
    queryset = SomeModel.objects.filter(
        some_related_field__in=self.request.user.some_related_objects.all()
    ).select_related(
        'related_field1', 'related_field2'
    ).prefetch_related('prefetch_field1', 'prefetch_field2')

    return queryset.order_by('-some_date_field')
```

Since `self.request.user` is only available when authenticated, the schema generation differed based on whether the user was logged in or not. This discrepancy resulted in the filters only appearing when authenticated.

**Solution:**

To resolve this, I modified `get_queryset` to return an empty queryset (`SomeModel.objects.none()`) if the user is not authenticated:

```python
def get_queryset(self):
    if self.request.user.is_authenticated:
        queryset = SomeModel.objects.filter(
            some_related_field__in=self.request.user.some_related_objects.all()
        ).select_related(
            'related_field1', 'related_field2'
        ).prefetch_related('prefetch_field1', 'prefetch_field2')

        return queryset.order_by('-some_date_field')

    return SomeModel.objects.none()
```

This ensures a consistent schema is generated, allowing the filters to appear in the Swagger UI documentation for both authenticated and unauthenticated users.

**Comment by tfranzel** [comment]
Ahh now it makes sense. Yes that is somewhat expected. We do not always call `get_queryset`, but sometimes there is no way around it. 

We have a FAQ entry for this issue: https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-get-queryset-depends-on-some-attributes-not-available-at-schema-generation-time

I would recommend doing this instead, which guarantees identical behavior.

Also, I believe this should have raised some exceptions which are logged to the console as warnings. You should have a look there, as the warnings are usually very helpful.

**Comment by yoelfme** [comment]
Yes, that was the thing it didn't generate the warning and I saw that there is one in the source code.
