### ISSUE TITLE
Custom ordering of endpoints within a viewset

### ISSUE THREAD

**Issue by zyiology** [tfranzel/drf-spectacular#1332]
I wanted to find a way to order custom endpoints within a viewset. The default behaviour is that it's alphabetically sorted by url. I came up with a way it could be implemented, but I'm not sure if it's a good way.

This is what my code looks like.

```
class CustomViewSet(viewsets.ViewSet):
    OPERATION_ORDER = {
        'upload_pdfs': 1,
        'list_pdfs': 2,
        'process_pdfs': 3,
        'get_cropped_images': 4,
        'serve_cropped_image': 5
    }

    ...
    def upload_pdfs(self, ...):
    def list_pdfs(self, ....):
    ....
    @classmethod
    def get_extra_actions(cls):
        """
        Get the methods that are marked as an extra ViewSet `@action`.
        """
        return [_check_attr_name(method, name)
                for name, method
                in getmembers_custom(cls, _is_extra_action)]

def getmembers_custom(object, predicate=None):
    """Return all members of an object as (name, value) pairs sorted by name.
    Optionally, only return members that satisfy a given predicate."""
    if isclass(object):
        mro = (object,) + getmro(object)
    else:
        mro = ()

    order_dict = object.OPERATION_ORDER
    if not order_dict or not isinstance(order_dict, dict):
        raise AttributeError
    results = []
    processed = set()

    ... <UNCHANGED> ...

    results.sort(key=lambda pair: order_dict[pair[0]])
    print("results", results)
    return results

def getmro(cls):
    "Return tuple of base classes (including cls) in method resolution order."
    return cls.__mro__

```

Essentially, the user can define an OPERATION_ORDER that maps the endpoint functions to an order number, then override get_extra_actions() from ViewSetMixin with a custom get_members() that sorts the members by the OPERATION_ORDER.

Was just wondering if there's any value to having this functionality? Or am I using viewsets wrongly... Thanks!

**Comment by tfranzel** [comment]
Hi, there are 2 possible solutions here. Users have different needs for sorting so there is no universal solution apart from basic alphanumeric sorting. If that is not sufficient for you, you can implement your custom sorting scheme:

1. custom sorter function. overwrite this settings with a import path string to your custom function:

https://github.com/tfranzel/drf-spectacular/blob/27ae6f293a6e8731649216d62ba2a5c8d65691e6/drf_spectacular/settings.py#L110-L114

default implementation as example:

https://github.com/tfranzel/drf-spectacular/blob/27ae6f293a6e8731649216d62ba2a5c8d65691e6/drf_spectacular/plumbing.py#L680

You can make use of `callback.cls.OPERATION_ORDER` to your needs.

 ---

2. sorting via https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-7-preprocessing-hooks
   and disabling the default sorting mechanism

I would first try to the approach 1 as it is cleaner imho.

**Comment by zyiology** [comment]
ahh I see, thanks for the solutions, I'll try it out!
