### ISSUE TITLE
Can't define only part of example data?

### ISSUE THREAD

**Issue by danielmcquillen** [tfranzel/drf-spectacular#1346]
I have a Building serializer that nests a UtilityBill serializer. In the UtiltyBillSerializer, I want to provide some reasonable example data for a `bill_start_date` and `bill_end_date` to suggest what a real bill would have for the start and then end of a month.

I see this is possible with the the `extend_schema_serializer` decorator. (Unfortunately, I think I can't define it for just the two fields, so I have to provide manual examples for every field in the serializer.)  For example...

```
@extend_schema_serializer(
    examples=[
        OpenApiExample(
            "Valid utility bill example 1",
            value={
                "fuel_type": "ELECTRIC_GRID",
                "bill_start_date": "2024-12-01",
                "bill_end_date": "2024-12-31",
                "consumption": 45000,
                "unit": "KWH",
                "cost": 5400,
            },
            request_only=True,  
        ),
    ],
)
class UtilityBillDetailSerializer(serializers.ModelSerializer):
...
```

That works for docs created for this endpoint, but when this serializer is nested in the BuildingSerializer, the generated example doesn't include this modification. It uses the default '2024-12-06' for both fields, which doesn't really make sense for the use case of a utility bill.

<img width="341" alt="image" src="https://github.com/user-attachments/assets/a20bca83-2f1f-487e-bddf-15dd6a3f1808">

...and it doesn't seem to be possible to use `@extend_schema_serializer` on my BuildingSerializer to provide example data for *just* the utility_bills field.

So it seems I have to provide a custom example for the **entire** BuildingSerializer, which is kind of brittle since that means manual updates to the example anytime anything in the serializer (or child serializers) changes.

Is there any way to define example data that flows through to each use of a field or serializer, even if nested?

(Thanks for this really helpful library!)

**Comment by tfranzel** [comment]
Hi,

> I see this is possible with the the extend_schema_serializer decorator. (Unfortunately, I think I can't define it for just the two fields, so I have to provide manual examples for every field in the serializer.) For example...

yes, only full examples.

> So it seems I have to provide a custom example for the entire BuildingSerializer, which is kind of brittle since that means manual updates to the example anytime anything in the serializer (or child serializers) changes.

So in contrast to `@extend_schema` itself, examples are not layered and stacked onto each other as with everything else. We decided for this simpler mechanic, to not generate mismatching and confusing examples. Giving examples will replace all previously given examples on purpose.

As you hinted, just nesting stuff might just not what you are after and untangling that stuff again is cumbersome. We, as a library, cannot really judge what semantically makes sense for you, so we went the defensive route. However, you can store your example dict close to the serializer and reuse it when integrating it into another serializer as a field. Then it is explicit what you want and you pretty much do not have any duplication.

**Comment by danielmcquillen** [comment]
Hi @tfranzel thanks for such a quick response!

Ok, so it seems like then if we want to update some properties of a child serializer that appears nested down in a parent serializer, we have to update the complete example in the parent. We'll go with that. Thanks.

**Comment by tfranzel** [comment]
You can be smart about it without it being brittle. Just define some example dicts and reuse where appropriate:

```python
UTILITY_BILL_ELECTRIC_EXAMPLE = {
    "fuel_type": "ELECTRIC_GRID",
    "bill_start_date": "2024-12-01",
    "bill_end_date": "2024-12-31",
    "consumption": 45000,
    "unit": "KWH",
    "cost": 5400,
}

@extend_schema_serializer(
    examples=[
        OpenApiExample(
            "Valid utility bill example 1",
            value=UTILITY_BILL_ELECTRIC_EXAMPLE,
            request_only=True,
        ),
    ],
)
class UtilityBillDetailSerializer(serializers.ModelSerializer):
    pass

@extend_schema_serializer(
    examples=[
        OpenApiExample(
            value={
                "foo": "bar",
                "utility_bill": UTILITY_BILL_ELECTRIC_EXAMPLE,
            },
            request_only=True,
        ),
    ],
)
class BuildingSerializer(serializers.ModelSerializer):
    pass
```

**Comment by danielmcquillen** [comment]
@tfranzel But if I use examples, doesn't that automatically make me responsible for creating the *entire* example. If BuildingSerializer has, say 30 properties, and maybe two other embedded serializers (each with their own 30 props), as soon as I add that "examples" b/c I want special values for UtilityBillSerializer, now I have to manually create the complete example for BuildingSerializer (manually created with values for all 30 props, plus nested dictionaries ... )

Apologies I could be misunderstanding how `examples` works. My current understanding after working with it is it's "all or nothing" ... you can't define just one property to replace.

**Comment by danielmcquillen** [comment]
@tfranzel Sorry I could be misunderstanding something. 

As soon as I add that decorator to BuildingSerializer, I lose the entire generated example for that endpoint. The schema now only shows exactly what I put in value (which in your example is an example value for "foo" and one for "utility_bill").

If BuildingSerializer has 30 properties, and three nested serializers, each of which have 30 properties, I now I have to create the entire example from scratch with all those properties, and remember to update it manually when anything in that structure changes (whereas before drf-spectacular was automating that for me). 

That's manageable, but it would be nice if the OpenApiExample allowed partial updates so I could say "here's a custom value for "utility_bill" but auto-generate everything else.

But again I could be misunderstanding something...

**Comment by tfranzel** [comment]
> (whereas when I don't define examples drf-spectacular automates that for me).

That is not really true. spectacular does not generate examples for you. SwaggerUI will try to make an example from the given field types. Once you create your own explicit examples, we will attach them to the schema and SwaggerUI will use that instead of guessing an example.

If you are happy with the SwaggerUI-guessed examples, that is perfectly fine. If you look at the schema, you will not find any examples, unless explicitly written by you.

If you want domain-specific sensible examples, you have to write them yourself, as we have no crystal ball for guessing your intent. For that reason it is all or nothing when it comes to examples. Mixing and matching your examples on our side will just create a mess and so we refrain from it.

**Comment by danielmcquillen** [comment]
Ok @tfranzel thanks for explaining!
