### ISSUE TITLE
[ReDoc UI] - Payload must have fields: [object Object] 

### ISSUE THREAD

**Issue by 50-Course** [tfranzel/drf-spectacular#1348]
When the server `runserver` is spinned up, either in local or production, the ReDoc UI does not loads up - reporting 
an error: `Payload must have fields: [object Object]`. See image below.

![Screenshot from 2024-12-09 11-58-00](https://github.com/user-attachments/assets/fa019de5-60f2-41f3-8031-6abeab4f6359)

To identify this issue, I attempted a few things:

- Tried to validate the schema with: `python manage.py spectacular --fail-on-warn` flag
which resulted in the following output:

```sh
(superpool-py3.11) ➜  api git:(fix-openapi-redoc-documentation) ✗ python manage.py spectacular --fail-on-warn
...
Warning: enum naming encountered a non-optimally resolvable collision for fields named "product_type". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "ProductType47eEnum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.

Schema generation summary:
Warnings: 2 (2 unique)
Errors:   0 (0 unique)

SchemaGenerationError: Failing as requested due to warnings
```

- Moved from CDN UI to self-contained UIs with `drf-spectacular-sidecar`
- Resolved all schema-compliant errors

Error remained the same, and unfortunately I couldn't get descriptive logs to help trobuleshoot further.

**Comment by tfranzel** [comment]
This is likely not a spectacular schema issue and so the warnings on the schema are not really relevant.

Maybe Redoc changed something from 2.1.5 to 2.2.0 that broke our html template. The sidecar now also contains that version. Try to fix the CDN version to something before 2.2.0. That might narrow it down.

**Comment by 50-Course** [comment]
thank you very much i had suspected as much - and was going to downgrade the version. Would make changes and revert here with progress before closing this out 😀

**Comment by 50-Course** [comment]
downgrading did turned out well - thanks!
