### ISSUE TITLE
Choices and blank=True

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#135]
**Describe the bug**
When there is a charfield with choices, and `blank=True`, the empty string (`''`) is a valid value, unrelated to the field being required or not, or nullable or not.

However drf-spectacular creates an enum of the choices without an option for the empty string.

**To Reproduce**
django-oscar-api UserAddressSerializer, BillingAddressSerializer, ShippingAddressSerializer, all include a `title` that has a choices of Mr, Mrs, Dr, etc, and `blank=True`

**Expected behavior**
The enum needs to include the empty string, or some other schema structure that allows the empty string.  

IMO it would be preferrable that the enum in components doesnt include the empty string, as this would mean two fields using the same choices but different `blank` values would require two enums.  And having two enums would result in more clashes, component renames, and those enum names are now appearing in peoples ENUM_NAME_OVERRIDES .

**Comment by tfranzel** [comment]
oh thats a tricky one. you are absolutely right about the possible duplication. on the other hand it is a valid input. we have to investigate how to solve that in the least invasive way.

**Comment by tfranzel** [comment]
sry that commit is unrelated. typed the wrong number

**Comment by tfranzel** [comment]
@jayvdb not sure if you were notified of the mention in the PR. would be awesome if you could check out the solution proposal.

**Comment by gabn88** [comment]
I'm not sure if this is related, but when using CharField choices and blank=True, the '' (which is valid to set it empty) does not come up in the Enum that is created.

@tfranzel Do you have any suggestion on how to circumvent this?

**Comment by tfranzel** [comment]
@gabn88 please re-check. this is heavily tested and should work, if  `'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': True,` (the default)

It will however not be part of the enum, as it belongs to the field and not the enum itself. You might use that enum with AND without the blank, and thus is has to be combined:

https://github.com/tfranzel/drf-spectacular/blob/aeca119ba7a9057935e03b9731af031406165558/tests/test_postprocessing.yml#L55-L60

this will be performed for model `blank`, serializer `allow_blank`, and explicit mention of `''` in the choices. If you find a bug, please open a new issue. thx
