### ISSUE TITLE
Utility function resolve_basic_type removed after version 0.8.5

### ISSUE THREAD

**Issue by jjmurre** [tfranzel/drf-spectacular#143]
We are using the utility function `types.resolve_basic_type`, however, it seems that this function has been removed. Is there a specific reason for the removal? We could easily copy the function to our own codebase, but we want to make sure it was not accidentally removed.

**Comment by tfranzel** [comment]
it is still heavily used. the function has been slightly renamed and moved to `plumbing`:

https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/plumbing.py#L169
