### ISSUE TITLE
ViewSet.filter_queryset() not being honored, extra parameters

### ISSUE THREAD

**Issue by jtsay362** [tfranzel/drf-spectacular#147]
**Describe the bug**
I have these filter backends enabled by default on my DRF settings:
django_filters.rest_framework.DjangoFilterBackend, rest_framework.filters.SearchFilter,
rest_framework.filters.OrderingFilter

But I don't want those applied to non-list views and their presence is adding multiple undesired parameters to the API schema, so I override ViewSet.filter_queryset() to return the argument queryset unchanged if the action is not "list". This seems to disable these filters for non-list views.

However, when I run drf-spectacular, these query parameters remain in the documentation. It does not seem like filter_queryset() is being called during introspection.

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

In settings.py:

    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',
                                'rest_framework.filters.SearchFilter',
                                'rest_framework.filters.OrderingFilter',),

Add this method to your viewset:

    def filter_queryset(self, qs):
        """
        Don't apply filterset classes on non-list views, it's unnecessary.
        Maybe one day it will remove the OpenAPI documentation for the
        filter parameters on these methods, but it doesn't seem to work yet.
        """

        logger.debug(f"filter_queryset, {self.action=}")

        if self.action == 'list':
            return super().filter_queryset(qs)
        else:
            return qs

Then run drf-spectacular to generate the schema. "ordering" and "search" are documented as query parameters on the non-list endpoints.

**Expected behavior**
"ordering" and "search" should not appear as query parameters on the non-list endpoints.

**Comment by tfranzel** [comment]
hi @jtsay362 . that was one of the last pieces of legacy code. filters were indeed applied everywhere. now it should only apply to list views and work as expected.

fyi and independent of the bug: i also added improved typing support for `django_filters`. you can use the patched backend `drf_spectacular.contrib.django_filters.DjangoFilterBackend`

let me know if that works for you. cheers!

**Comment by tfranzel** [comment]
as far as i am concerned, this issue is resolved. @jtsay362 please inform me if that is not the case and i'll reopen. thx

**Comment by jtsay362** [comment]
@tfranzel I am sorry I did not have a chance to respond. I am fairly new to python, so I had some trouble installing your package from Github. Thank you very much for doing this work. I will for sure give you some feedback when this makes it into the next release.

**Comment by tfranzel** [comment]
hey @jtsay362, no worries. ideally we should confirm fixed before releases :smile: i'm glad though it works for you. 

for the next issue consider this. that gives you the current master state for testing. 
```
pip uninstall drf-spectacular
pip install git+https://github.com/tfranzel/drf-spectacular 
```
