### ISSUE TITLE
Annotate SlugRelatedField

### ISSUE THREAD

**Issue by ADR-007** [tfranzel/drf-spectacular#15]
Hi!

Is there a way to annotate SlugRelatedField?

**Comment by tfranzel** [comment]
Hey! As these serializer relations are DRF native, i think we should support it. i will prob look at it tomorrow.

**Comment by ADR-007** [comment]
Thanks!
Currently, I do like this:
```
@extend_schema_field(serializers.ChoiceField(Gender))
class GenderSlugRelatedField(serializers.SlugRelatedField):
    def __init__(self, **kwargs):
        super().__init__(slug_field='gender', **kwargs)
```

**Comment by tfranzel** [comment]
so i added the related serializer fields. A `SlugRelatedField` is gonna be a simple string though.  

I think your usage of the `SlugRelatedField` with fixed choices is not what it was originally intended for. imho its more like a arbitrary "sluggified" string describing a related object. So you still have to do something custom if you want to have it with a choices `enum` like that.

**Comment by tfranzel** [comment]
@ADR-007 closing this for now. reopen if you think this does not sufficiently solve the problem.

**Comment by ADR-007** [comment]
OK. Thanks!
