### ISSUE TITLE
django-filters filter spanning foreign key relationships results in FieldDoesNotExist error

### ISSUE THREAD

**Issue by sennierer** [tfranzel/drf-spectacular#150]
**Describe the bug**
When using django-filter and adding filters similar to ```{'FKfield__FKprop': ['exact', 'icontains'}}``` to the Meta class of a GenericViewset drf-spectacular throws an ```MODEL has no field named FKfield__FKprop``` error

**Expected behavior**
Fields and properties should be splitted similar as django-filter does to follow the FKs to the field that is filtered on

**Comment by tfranzel** [comment]
@sennierer i tried to pull the improvement discussed in #151 into the core and reuse them for `django-filter`. could you check out the `django_filter` branch (PR #153) and tell me if that works for you? thanks!

**Comment by sennierer** [comment]
Yes, thats working! Thanks for fixing it!

**Comment by tfranzel** [comment]
my pleasure! thanks again for raising the issue and helping to find a good working fix!
