### ISSUE TITLE
Questions: Does this project use semver? Should we version pin?

### ISSUE THREAD

**Issue by bmbouter** [tfranzel/drf-spectacular#152]
We use `drf-spectacular` as a dependency and we love it! We ship a dependency line like `drf-spectacular>=0.9.12` but there were backwards incompatible changes with `0.9.13` so our users broke. To guard against that we are now pinning with something like `drf-spectacular==0.9.13`. Happy to continue doing that but it will slow our users uptake of new `drf-spectacular` versions.

Does the project want to adopt semver which would limit breaking changes to only y-releases while < 1.0?
Should we version pin (aka are there more breaking changes in z-stream to come)?

I want to find a way for us to use it safely and still stay up to date. Again, love using the project. Thank you!

**Comment by bmbouter** [comment]
Someone on irc pointed out that since it's less than < 1.0 breaking changes are allowed in z-stream also. I think we'll have to version pin then.

**Comment by tfranzel** [comment]
Hi @bmbouter! thank you so much, that is very appreciated. i actually thought about doing a 1.0.0 with this release, but the date was 9/13 and i couldn't resist doing a 0.9.13. :smile: 

the amount of incoming bugs decreased a lot and i think its fairly stable now. i would say that it's reasonable to do a stable release (1.0.0) now. the only things that bugs me a bit is how to define a "breaking change" here. any **change** in the schema (which is kind of a public API) could be considered that and thus would require a x-stream increment. at the end of the day fixing buggy behavior like leaking var names in `operationId` is something people rely on to be stable and thus should be considered a breaking change. additions would go in the y-stream and the z-stream be pretty much unused.

so i guess releases would be mainly x-stream with the occasional y-stream release. what do you think?

**Comment by tfranzel** [comment]
@bmbouter i gave it some more thought. as even minor changes to the generated output could be classified as a breaking change and thus would warrant a x-stream increment, we would very likely need an x-stream increment on almost every release. i suppose this would have very little benefit compared to staying <1.0.

i consider the library fairly stable and i don't expect crazy changes to happen anymore, but there will be changes that may break some people. we may go >1.0 at some point, but i would hold that off a while longer. 

for that reason i recommend pinning the version and inspecting the diff on upgrade to prevent any surprises.

**Comment by bmbouter** [comment]
> @bmbouter i gave it some more thought. as even minor changes to the generated output could be classified as a breaking change and thus would warrant a x-stream increment, we would very likely need an x-stream increment on almost every release. i suppose this would have very little benefit compared to staying <1.0.
> 
> i consider the library fairly stable and i don't expect crazy changes to happen anymore, but there will be changes that may break some people. we may go >1.0 at some point, but i would hold that off a while longer.
> 
> for that reason i recommend pinning the version and inspecting the diff on upgrade to prevent any surprises.

Sorry for the long delay in responding. This sounds fine to me. What would be ideal if the version pinning recommendation was somewhere in the docs and also indicating that semver is not used. Any policy is ok as long as users know. We love using this library; thank you for all the hard work you put into it.
