### ISSUE TITLE
type error in  view.schema.get_operation() 

### ISSUE THREAD

**Issue by sennierer** [tfranzel/drf-spectacular#156]
**Describe the bug**
When deploying our locally working instance to production we get the following error:
```
File "/drf-spectacular/drf_spectacular/generators.py", line 153, in parse
    operation = view.schema.get_operation(path, path_regex, method, self.registry)
TypeError: get_operation() takes 3 positional arguments but 5 were given
```

As this happens only on the server it is hard to trace, but I guess the error is due to our reverse proxy setup that passes X-Headers-* on and proxies requests from http to https.

**Comment by tfranzel** [comment]
i have a different theory because that error feels way too familiar. @sennierer do you have a different config in production? i would guess your production config is missing 

```python
REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
```

**Comment by sennierer** [comment]
found out just a minute after posting, on the servers we still had an old settings running ;)
sorry for that, cloding the issue!

**Comment by tfranzel** [comment]
no problem. it happened to me a couple of times. since the root cause is not that obvious i'll add an error message that points new users in the right direction.

**Comment by stefanpl** [comment]
I got the same error when calling 

`manage.py generateschema --file …`

 instead of 
 
 `manage.py spectacular --file …`
 
 🙈

**Comment by tfranzel** [comment]
@stefanpl, yes that is the second way to get this error.

`generateschema` will start the DRF's default schema generator, which has nothing to do with us.
