### ISSUE TITLE
$ref with other fields

### ISSUE THREAD

**Issue by ADR-007** [tfranzel/drf-spectacular#16]
Hi!

Currenlty it doesn't work (the "readonly" is ignored):
![image](https://user-images.githubusercontent.com/7348960/77745798-9ccc7500-7024-11ea-85c8-d8af6d8fd846.png)

Fix:
Change this:
https://github.com/tfranzel/drf-spectacular/blob/9daf0adc73bee707c80ca8d3df999e907316171a/drf_spectacular/plumbing.py#L236
to:
```python
        return {'allOf': [{'$ref': f'#/components/{self.type}/{self.name}'}]}
```

Result (inheritance with overriding):
![image](https://user-images.githubusercontent.com/7348960/77746016-f634a400-7024-11ea-80ad-969fb45d1358.png)

(it doesn't look like the correct way to fix it. so, it is just example)

**Comment by ADR-007** [comment]
my workaround:
```python
    def _map_serializer_field(self, method, field):
        field = super()._map_serializer_field(method, field)

        if '$ref' in field:
            all_of = field.setdefault('allOf', [])
            all_of.append({'$ref': field.pop('$ref')})

        return field
```

**Comment by tfranzel** [comment]
that was a good catch. the spec is not 100% clear, if that is actually behaves as intended. at least its more valid than before :grin: Also SwaggerUI properly recognizes it so that should be good enough here.
