### ISSUE TITLE
drf-spectacular Swagger-UI would not cache JWT 

### ISSUE THREAD

**Issue by KimSoungRyoul** [tfranzel/drf-spectacular#160]
<img width="1025" alt="스크린샷 2020-10-03 오후 4 13 41" src="https://user-images.githubusercontent.com/24240623/94985680-9dc1fe80-0593-11eb-9a46-b14aea00ebdf.png">

#### After: command + R (refresh browser)

<img width="1086" alt="스크린샷 2020-10-03 오후 4 13 46" src="https://user-images.githubusercontent.com/24240623/94985683-9f8bc200-0593-11eb-850a-5a197873175d.png">

is this bug? or spec?  

if these case is the former  , i will fix it

the latter,  can you tell me how can i cache the token to Swagger UI

~~~Python

# settings.py

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_spectacular",
    "qwerty5656",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}


~~~

**Comment by tfranzel** [comment]
hi @KimSoungRyoul, i suppose this is neither bug nor spec, but the default behavior of swagger-ui. the OpenAPI schema itself makes no assumptions on how the auth credentials are stored. also, we only use the "vanilla" swagger-ui from CDN.

others have raised similar issues: https://github.com/DarkaOnLine/L5-Swagger/issues/120

What you can do is customize your swagger-ui, by locally overriding the template (`swagger_ui.html`) in one of your own apps (`YOURAPP/templates/drf_spectacular/swagger_ui.html`, YOURAPP must come before spectacular in `INSTALLED_APPS`).
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/templates/drf_spectacular/swagger_ui.html

there is indeed a setting (https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#authorization) which i quickly tested. unfortunately, it had no effect for me. credentials disappeared on reload. may be an upstream bug

**Comment by tfranzel** [comment]
`persistAuthorization: true` does indeed work. it is a new feature and we were pinned to `3.30.0` due to an upstream bug. updated the pinning. you should be able to persists your auth as outlined now. 

meanwhile i will think about whether we should make that the default. i'm not sure that everyone would like to have that turned on by default.

**Comment by KimSoungRyoul** [comment]
@tfranzel  thank you for your feedback 

I forget  SWAGGER-UI config's existence

 I think it's not a good idea pin the configuration`persistAuthorization: true` 

 drf-yasg support swagger config with `settings.py`
https://drf-yasg.readthedocs.io/en/stable/settings.html#swagger-settings

why don't we add new feature `support swagger-ui config` like a `drf-yasg's swagger-settings`?

I want to convert `drf-yasg` to `drf-spectacular `  with my company project

due to `disappear Maintainer` , `support OAS 3.0`

swagger-UI configuration with `settings.py` is needed 

I want to contribute your project with  **swagger-UI configuration with `settings.py`**

like a 

~~~Python

SWAGGER_SETTINGS = {
    "PERSIST_AUTH": False,  # support swagger-ui configuration  Default: False

    "APPEND_COMPONENTS": {
      ....
    },
    "SECURITY": ....,
}

~~~

#### I want ask  your opinion these new feature

**Comment by tfranzel** [comment]
you're welcome. i appreciate contributions very much! i think it is a good idea.

i would like to do it a bit differently than `drf-yasg`. there are a lot of potential settings (https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) and i don't want to hand them through individually. 

we already do support a lot of settings similar in `drf-yasg`, just not the `swagger-ui` part.  i think we should do a catch-all setting for `swagger-ui` like maybe:

```python
SPECTACULAR_SETTINGS = {
    'SCHEMA_PATH_PREFIX': r'api/',
    'SWAGGER_UI_CONFIG': '''
        deepLinking: true,
        persistAuthorization: true,
        displayOperationId: true,
        filter: true,
        defaultModelsExpandDepth: 2,
    """
}
```
and replace that in the swagger template. that way people can configure almost all `swagger-ui` settings on their own without us having to model every single one explicitly.  what do you think?

**Comment by KimSoungRyoul** [comment]
oh that's the simplest way to develop this feature ,  i will try this .

In Korea, today is Sunday evening ,  perhaps I can make time only weekend or during the weekday evening

I will request to review as soon as possible

**Comment by tfranzel** [comment]
awesome! it does not have to be exactly like suggested. feel free to come up with a better solution if you like. the only thing i want to prevent is handing through ~30 parameters by hand.
