### ISSUE TITLE
Question regarding renderer_classes

### ISSUE THREAD

**Issue by errrken** [tfranzel/drf-spectacular#161]
Hi,

Lets say I have a custom renderer class for a view:
```

class XLSXRenderer(renderers.BaseRenderer):
    media_type = 'application/xlsx'
    format = 'xlsx'

    def render(self, data, media_type=None, renderer_context=None):
        return data      
```

The Schema correctly says:
RESPONSE SCHEMA: application/xlsx

However, the default serializer is still shown in the response schema. How would I go about to only show the Response schema? I tried to use a empty serializer in the @extend_schema responses parameter but then nothing is shown. Any idea?

Thanks

**Comment by tfranzel** [comment]
Hi @errrken,

the empty serializer has no content and thus it is omitted from the schema as you noticed. i believe the correct annotation would be 

```python
@extend_schema(responses=OpenApiTypes.BINARY)
```

which would would produce

```yaml
      responses:
        '200':
          content:
            application/xlsx:
              schema:
                type: string
                format: binary
          description: ''
```

i guess binary is appropriate for xlsx files.

**Comment by errrken** [comment]
@tfranzel Thanks!

**Comment by Alir3z4** [comment]
I understand this is closed, but would appreciate if there was a way to apply this globally.

In my application there are many `@action` endpoint that export CSV and xlsx (_using [drf-excel](https://github.com/wharton/drf-excel) and [django-rest-framework-csv](https://github.com/mjumbewu/django-rest-framework-csv)_), the generated schema correctly uses the `media_type` on the Renderer classes

For XLSX, makes sense to be binary, but for the CSV file, it would be much better to return 

```csv
HEADER_1,HEADER_2,...
Lorem,ipsum,...
```

```python
from drf_excel.renderers import XLSXRenderer
from rest_framework_csv.renderers import CSVRenderer

def csv_sample(renderer: Type[CSVRenderer]) -> None:
    lines = ','.join(renderer.labels.values())
    lines += ','.join(renderer.labels.keys())

    return headers

@extend_schema(
    responses={
        ('200', 'text/csv'): OpenApiTypes.STR,
        ('200', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'): OpenApiTypes.BINARY
    },
    examples=[
        OpenApiExample(
            "CV Representation",
            value=csv_sample(ItemSerializer),
            media_type="text/csv",
            response_only=True,
        ),
    ],
)
@action(
    methods=["get"],
    detail=False,
    serializer_class=ItemSerializer,
    renderer_classes=(CSVRenderer, XLSXRenderer),
    pagination_class=None,
)
def export(self, request: Request, *args, **kwargs) -> Response:
    ...
```

While this is OK for couple of endpoints to be hardcoded, it will be tons of boilerplate when we have more than 50 of such places. 

What approach would you recommend to handle such cases?

**Comment by tfranzel** [comment]
Hi @Alir3z4,

you are right that is kind of repetitive. I think this could be approached with an [OpenApiViewExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#replace-views-with-openapiviewextension), but it might be tricky to get it correct in a generic sense.

I would probably (without knowing the frequency and variance) write a more capable helper function like you did with `csv_sample`.

```python
def spectacular_csv_helper(serializer, renderer_classes):
    return {
        "responses": {
            ('200', 'text/csv'): OpenApiTypes.STR,
            ('200', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'): OpenApiTypes.BINARY
        },
        "examples": [
            OpenApiExample(
                "CV Representation",
                value=csv_sample(serializer),
                media_type="text/csv",
                response_only=True,
            ),
        ]
    }


@extend_schema(**spectacular_csv_helper(ItemSerializer), ...)
@action(
    methods=["get"],
    detail=False,
    serializer_class=ItemSerializer,
    renderer_classes=(CSVRenderer, XLSXRenderer),
    pagination_class=None,
)
def export(self, request: Request, *args, **kwargs) -> Response:
    ...
```

I would adapt this to fit most of your cases and then you only have a 1 line decoration in addition to the action decoration.  `spectacular_csv_helper` could be made arbitrarily flexible.

In essence if you would go the extension route, your extension would basically attach `spectacular_csv_helper` to the view automatically. 

sidenote: changing spectacular to accommodate this automatically is tricky imho. I would say this is due to 2 reasons. 
(1) renderer/parser classes have a very minimalistic interface from which there is not much info to extract. 
(2) OpenAPI is not really designed to provide structure for anything other than json and yaml

**Comment by Alir3z4** [comment]
@tfranzel thanks for the suggestion.

I agree with you on making a 1 liner seems to be a better approach here. I checked the code base to make it generic either by subclassing/extending some part of the drf-spectacular or writing extensions and I noticed it would take more time on my end and wasn't sure it would result in what I'd want as the end-result.

I made this to facilitate it.

```python
from typing import Any, Callable

from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import OpenApiExample, extend_schema
from rest_framework.renderers import BaseRenderer
from rest_framework_csv.renderers import CSVRenderer


def _generate_csv_example_value(renderer: CSVRenderer | BaseRenderer) -> str:
    """Makes a simple example string of for the CSV renderer."""
    lines = ",".join(renderer.labels.values())
    lines += ",".join(renderer.labels.keys())

    return lines


def export_view(view: Callable[..., Any]) -> Callable[..., Any]:
    """
    Used as a decorator on Export views/actions to extend the generated OpenAPI schema by DRF-Spectacular
    for supporting CSV and XLSX response types.

    Usage:

    @export_view
    @action(
        methods=["get"],
        detail=False,
        serializer_class=ItemSerializer,
        renderer_classes=(CSVRenderer, XLSXRenderer),
        pagination_class=None,
    )
    def export(self, request: Request, *args, **kwargs) -> Response:
        ...
    """
    if kwargs := getattr(view, "kwargs", None):
        renderer_classes: list[BaseRenderer] = kwargs["renderer_classes"]
    else:
        raise AttributeError(f"Cannot extend export schema for {view}.")

    responses: dict[tuple[str, str], OpenApiTypes] = {}
    examples: list[OpenApiExample] = []

    for renderer_class in renderer_classes:
        # TODO: Raise error if there's unrecognized media type.
        if renderer_class.media_type == CSVRenderer.media_type:
            response_type = OpenApiTypes.STR
            examples.append(
                OpenApiExample(
                    "default",
                    value=_generate_csv_example_value(renderer_class),
                    media_type=renderer_class.media_type,
                    response_only=True,
                )
            )
        else:
            response_type = OpenApiTypes.BINARY
            examples.append(
                OpenApiExample(
                    "default",
                    value="the file content in binary...",
                    media_type=renderer_class.media_type,
                    response_only=True,
                )
            )

        responses[("200", renderer_class.media_type)] = response_type

    return extend_schema(responses=responses, examples=examples)(view)
```
