### ISSUE TITLE
The 'MyViewSet' object has no attribute 'get'

### ISSUE THREAD

**Issue by ngocngoan** [tfranzel/drf-spectacular#166]
When I set urls are:
```
path('api/openapi3', SpectacularAPIView.as_view(), name='openapi3'),
path('api/openapi3/docs', SpectacularSwaggerView.as_view(url_name='openapi3'), name='swagger-ui'),
```
Then it raise errors in when access them in the browser

`AttributeError: 'MyViewSet' object has no attribute 'get'`

I have checked the error location at the line
[generator line 89](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/generators.py#L89)

The settings:

```
SPECTACULAR_SETTINGS = {
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "SECURITY": [{"bearerAuth": [], }],
}
```

Note: I am using [DRF with mongoengine](https://github.com/umutbozkurt/django-rest-framework-mongoengine)

My viewset declaration:
```
from rest_framework_mongoengine import viewsets


class MyViewSet(viewsets.ModelViewSet):
    ...
```

**Comment by KimSoungRyoul** [comment]
@tfranzel 

it might be skip IF Condition, 
caused by view does not rest_framework's GenericViewSet  (instead mongoengine's GenericViewSet)

~~~Python
class SchemaGenerator(BaseSchemaGenerator):
     ....

    def create_view(self, callback, method, request=None):
          ....
          
          if isinstance(view, viewsets.GenericViewSet) or isinstance(view, viewsets.ViewSet):
             # mongoengine viewsets.ModelViewSet does not flow in this IF Condition
             ....

~~~~

**Comment by tfranzel** [comment]
@ngocngoan @KimSoungRyoul, i believe there was a specific reason not do this. let me get back to you in a short while. i have to search for the reason.

**Comment by tfranzel** [comment]
that `if` was meant as a safeguard for people using crazy unsupported libraries and getting exceptions that are hard to understand. 

i did a quick test with one of their examples and was surprised how well it worked with drf-spectacular. that was not at all obvious, given that they changed quite a few things. however, your mileage may vary depending on how much dynamic stuff you have. 

this is what i used to clean up the schema a little bit. you may have to do a bit more depending on your codebase but that should get you started. you may even contribute to the blueprint section if you like. 

```python
class FixMongoEngineObjectId(OpenApiSerializerFieldExtension):
    target_class = 'rest_framework_mongoengine.fields.ObjectIdField'

    def map_serializer_field(self, auto_schema, direction):
        return build_basic_type(OpenApiTypes.STR)


def get_mongoengine_extended_doc_excludes():
    from rest_framework_mongoengine import viewsets, serializers
    return get_lib_doc_excludes() + [
        serializers.DocumentSerializer,
        serializers.EmbeddedDocumentSerializer,
        viewsets.ModelViewSet,
        viewsets.GenericViewSet,
        viewsets.ReadOnlyModelViewSet
    ]

SPECTACULAR_SETTINGS = {
    GET_LIB_DOC_EXCLUDES: 'YOUR_IMPORT_PATH.get_mongoengine_extended_doc_excludes'
}

```
