### ISSUE TITLE
Error:  namespace versioning path resolution failed for {url}. path will be ignored.

### ISSUE THREAD

**Issue by ruscooler** [tfranzel/drf-spectacular#168]
While generating scheme, the following error appears in the logs:
`Error #0: namespace versioning path resolution failed for /v1/accounts/{parent_lookup_account_transactions}/transactions/{id}/. path will be ignored.`

I use drf-extensions for Nested Routes. 
URL Pattern for url "/v1/accounts/{parent_lookup_account_transactions}/transactions/{id}/." 
is 
`^accounts/(?P<parent_lookup_account_transactions>[^/.]+)/transactions/(?P<pk>[^/.]+)/$`

I noticed, [detype_pattern](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/plumbing.py#L685) function [transform](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/plumbing.py#L714) my URLPattern to another one, but if I have more than one path parameter, it will return me unexpected result:

URL Pattern `"^accounts/(?P<parent_lookup_account_transactions>[^/.]+)/transactions/(?P<pk>[^/.]+)/$"` transforn to 
`"^accounts/(?P<parent_lookup_account_transactions>[^/.]+)/$"`

I suppose it's a mistake in regular expression

**Comment by tfranzel** [comment]
hey @ruscooler, that is indeed a bug in the regex. lazy is the way to go :smile: thanks for fixing it. 

your proposed change is a significant improvement, although i just noticed that there are still ways to break it. like trying to match a literal paranthesis `\)` ([regexr](//regexr.com/5each)) in the pattern. however i'm assuming that this is a lot less frequent than having 2 or more variables.

i will merge it as is but if you want to come up with an even better regex i'm all for it.
