### ISSUE TITLE
Response codes must be in string format

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#17]
At the moment it is incorrect format:
https://github.com/tfranzel/drf-spectacular/blob/master/tests/test_extend_schema.yml#L53
Must be like "200"

Details:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#patterned-fields-1

**Comment by tfranzel** [comment]
actually i stumbled upon this before but the the schema validation never complained about it (which runs for every test). fyi if you did not see this yet: ``./migrate.py spectacular --file schema.yaml  --validate``

I didn't notice this in the spec though:
``This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.``

easy fix. i'll do it right now.
