### ISSUE TITLE
Automatic tags detection

### ISSUE THREAD

**Issue by max-wittig** [tfranzel/drf-spectacular#172]
In drf-yasg, tags were automatically assigned based on the django app name. Is this something `drf-spectacular` also wants to support?

E.g.
![image](https://user-images.githubusercontent.com/6639323/96834541-79df3380-1442-11eb-8a96-eceba19b181e.png)
![Uploading image.png…]()

**Comment by max-wittig** [comment]
If not, how do I tag a viewset?

**Comment by tfranzel** [comment]
hi @max-wittig! i was not aware they are using the app name. as far as i know, drf-yasg is doing something very similar to get the tags. what i believe they do is subtract the common path prefix and then use the first path item. we currently don't do the automatic "common denominator" thing but you can set it explicitly (https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/settings.py#L9)

regarding overrides: `@extend_schema(tags=['foo'])` on the view method will definitely work. decorating the view may work too but i'm not sure.

**Comment by max-wittig** [comment]
Hii @tfranzel thanks for creating this fork. It's really cool!

And you're right `drf-yasg` also uses the path for this

I actually had to use `method_decorator` and decorate every single method in the viewset, but I will take a look at the `schema-path-prefix` setting. Thank you for the tip!

```python
@method_decorator(
    name="list",
    decorator=extend_schema(
        tags=["my-tag"],
    ),
)
class SomeViewSet(viewsets.GenericViewSet, viewsets.mixins.ListModelMixin):
```

**Comment by tfranzel** [comment]
thanks @max-wittig! sry that you had to bend backwards for that. it should be easier. if i only have to decorate i usually do 

```python
class SomeViewSet(viewsets.GenericViewSet, viewsets.mixins.ListModelMixin):
    @extend_schema(tags=['my-tag'])
    def list(self, request, *args, **kwargs)
         return super().list(request, *args, **kwags)
```

- `@extend_schema` is supposed to also work on views (with applicable args). i will check out why it does not work. although main use-case is decorating methods usually.
- usually `SCHEMA_PATH_PREFIX': r'/api/',` (its a regex) is already sufficient for most people. i think we should attempt auto-detection when it is not set. that would be a feature addition.

**Comment by max-wittig** [comment]
I think more people are going to switch to `drf-spectacular`, so it might make sense to use the default from `drf-yasg`, which is `"SCHEMA_PATH_PREFIX": "/api/v[0-9]",` and which works very nicely! 👍 

I just somehow missed this setting
