### ISSUE TITLE
Remove inline script to comply with `self` CSP

### ISSUE THREAD

**Issue by max-wittig** [tfranzel/drf-spectacular#173]
CSP doesn't really like inline scripts.

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 
```

We should move this to a separate script: https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/templates/drf_spectacular/swagger_ui.html#L15

**Comment by tfranzel** [comment]
@max-wittig as you said, CSP 'self' does not allow inline scripts in its default setting. i haven't considered this yet. to mitigate this, i moved the init script into an extra request. please test it and close if it works as expected.

**Comment by tfranzel** [comment]
@max-wittig can you confirm that this works for you now?

**Comment by max-wittig** [comment]
There are a few more CSP issues with the remote js etc. For now I've just disabled CSP for this site. I will test it later this week again and give you a heads up

**Comment by tfranzel** [comment]
switched back to single request view by default. however, the CSP version is still available with `SpectacularSwaggerSplitView`. the change created more problems than expected with routing. 

closing this for now but feel free to open a new issue

**Comment by theoden-dd** [comment]
This is not compatible with the [Django CSP defaults](https://django-csp.readthedocs.io/en/latest/configuration.html) at least.

Without `unsafe-inline` in `CSP_SCRIPT_SRC` it does not work at all.
Here's part of the config which works (probably not minimal):
```
CSP_SCRIPT_SRC = ("'self'", 'ajax.googleapis.com', "'unsafe-inline'")
```

Please note, that drf-yasg for example does not need this `unsafe-inline` policy for a Swagger-UI to be working.

**Comment by tfranzel** [comment]
To anyone landing here, please follow: https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-swagger-ui-and-or-redoc-page-is-blank
