### ISSUE TITLE
Only works if you have BrowsableAPIRenderer set for DEFAULT_RENDERER_CLASSES

### ISSUE THREAD

**Issue by keithkraker** [tfranzel/drf-spectacular#178]
In production, I disable the BrowsableAPIRenderer by adding the following lines to my settings.py file. This causes the schema, docs, and redoc views to no longer work.

```python
REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
        "rest_framework.renderers.JSONRenderer",
    )
```

Shouldn't these views work independent of the browsable API? I have been using drf-yasg prior to switching and it worked fine with this setting disabled in production. Any information or direction you can point me in to get this resolved would be much appreciated. Thanks!

**Comment by tfranzel** [comment]
hey @keithkraker. that seems very odd. we have exactly the same setting in production and this has never created any issues. spectacular does not even make use of the `BrowsableAPIRenderer`, in fact it gets explicitly excluded.

 can you provide a stacktrace or error to get to the bottom of this?

**Comment by keithkraker** [comment]
Thanks for the quick reply! It turns out it wasn't due to this setting. I deployed again and the views function properly now. I must have made additional changes when I was debugging this issue.
