### ISSUE TITLE
Retrieve extend_schema responses

### ISSUE THREAD

**Issue by fletcheaston** [tfranzel/drf-spectacular#179]
Is there a way to retrieve the extend_schema responses in a unit test?

I'd like to validate the actual data coming out of the API with the schema displayed on the generated documents. For example, if I have a test suite to generate new users, and the endpoint has something like this...
```
@extend_schema(
    responses={
        201: NewUserSerializer,
        400: ErrorSerializer,
    },
)
```

I'd love to write a test that uses the library like this...

```
from drf_spectacular.utils import reverse

schema = reverse("users-create")

assert schema.responses[200] == NewUserSerializer
```

This is just a toy example, but I hope it demonstrates what I'm looking for.

**Comment by tfranzel** [comment]
i think i get what you ask for, but unfortunately this is not how the library works. these are the steps drf-spectacular goes through:

1: annotation
2: pre-processing
3: main processing (utilizing extensions modifying schema aspects)
4: (global) post-processing 

so even if you get the sub-schema for one endpoint, it could still be manipulated by the global post-processing. only testing the complete schema after the last step would yield a guaranteed stable result.

for testing i think the best you can do is this:

```python
def test_foo():
    from drf_spectacular.generators import SchemaGenerator
    schema = SchemaGenerator().get_schema(request=None, public=True)
    assert schema['paths']['/api/foo/']['get']
```
you can generate a subschema with 
```python 
schema = SchemaGenerator(
     patterns=[path('api/foo/', FooView.as_view())]
).
```
but as i said, this may not be stable as endpoints may influence each other (e.g. enum substitution post-processing) 

i hope that answers your question.

**Comment by fletcheaston** [comment]
Gotcha, that makes sense. Thanks so much for the quick response!
