### ISSUE TITLE
SerializerMethodField - dict with known keys

### ISSUE THREAD

**Issue by jmaslanka** [tfranzel/drf-spectacular#184]
Hey, let's assume we have this field in a serializer:

```
field = SerializerMethodField()

def get_field(self, obj):
    return {
        "type": "some_type",
        "data": OtherSerializer(obj.objects, many=True).data,
        ...
    }
```
 Is there a way to represent it as:
```
{
    "type": "some_type",
    "data": {
        <serializer data>
    },
    ....
}
```
I've tried:
- using `typing.TypedDict` as type hint to `get_field`  - results in "Unknown type hint"
- `@extend_schema_field` accepts only either serializer or `OpenApiTypes`. I don't see a way to edit `additionalProperties` for `OpenApiTypes.OBJECT`.

Seems like a common problem to me. Any ideas?

**Comment by tfranzel** [comment]
hi @jmaslanka, indeed that still incomplete. better type hint resolution is still a todo. it currently only support `Optional`, basic types, and `OpenApiTypes`.

**Comment by jmaslanka** [comment]
Hey @tfranzel , thanks for the response. I ended up creating simple serializer, like:
```
class FieldData(serializers.Serializer):
    type = CharField()
    data = OtherSerializer(many=True)
```
and linked it using `extend_schema_field`.

**Comment by tfranzel** [comment]
@jmaslanka good stuff! luckily there multiple ways to achieve this. better type hint parsing is definitely on my list.

**Comment by tfranzel** [comment]
fyi: you could have also done this:

```python
from drf_spectacular.utils import extend_schema_field, inline_serializer

@extend_schema_field(inline_serializer(
    name='FieldData',
    fields={
        "type": CharField(),
        "data": OtherSerializer(many=True),
    }
))
def get_field(self, obj):
     pass
```

also we improved type hint functionality including basic `TypedDict`. however mixing type defintions with Serializers and Serializer fields may look ok, but are probably wrong according to mypy. so my above example is probably the "cleanest" solution. `TypedDict` with arbitrarily mixed basic types should work now.
