### ISSUE TITLE
HTTP OPTIONS operations are missing

### ISSUE THREAD

**Issue by Debakel** [tfranzel/drf-spectacular#189]
We use the [HTTP `OPTIONS`](https://tools.ietf.org/html/rfc7231#section-4.3.7) method to allow our clients to determine the user's access rights on a resource and to retrieve file limitations for an upload endpoint. 

DRF supports this by adding a [custom meta data class](https://www.django-rest-framework.org/api-guide/metadata/#custom-metadata-classes) or by overriding the viewsets `options` method.

However, the `OPTIONS` operations are missing in the generated OpenAPI-Spec. Does this have a reason? Is there a way to add them to the documentation? 

I tried to explicitly extend the schema using the `@extend_schema` decorator:
```
class AssetOptions(BaseMetadata):
    def determine_metadata(self, request, view):
        """
        Return a dictionary of metadata about the view.
        Used to return responses for OPTIONS requests.
        """
        perms = AssetPermission(request.user)
        return {
            'allowed_mime_types': settings.ALLOWED_MIME_TYPES,
            'permissions':
                {'user_can_create': perms.can_create,
                 'user_can_delete': perms.can_delete}
        }


class AssetViewSet(ModelViewSet):
    queryset = Asset.objects.all()
    serializer_class = AssetSerializer
    metadata_class = AssetOptions

    @extend_schema(description='Retrieve resource information')
    def options(self, request, *args, **kwargs):
        return super().options(request, *args, **kwargs)
```

**Comment by tfranzel** [comment]
hi @Debakel, the original DRF implementation explicitly excluded `OPTIONS` and you are the first person to ask for it. i simply haven't invested time there and since this is a lesser used feature i focused on other things first. 

but you are right. we should provide a way to include this in the schema. i did a quick test and some things broke in a weird way, namely the descriptor protocol for the late-binding schema injection. this is magic living in DRF. those pieces are quite complicated and it might take a moment to figure it out.

**Comment by tfranzel** [comment]
Closing this for lack of demand and time constraints on my side. Also, DRF behaves kind of special wrt to OPTIONS. Adding this  to spectacular may not even be possible.

**Comment by darioackermann** [comment]
Hey @Debakel , have you found any workaround for this? Would be interested in that too and was wondering whether you found a solution for it.

**Comment by tfranzel** [comment]
@darioackermann i'm quite confident this feature will never happen for several reasons. However, if you have a somewhat consistent OPTIONS over all endpoints, I would recommend writing a postprocessing hook. Attaching some recurring snippet to all endpoints is rather easy with a hook. Should only take a couple of lines I think.

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks
