### ISSUE TITLE
Extend tags support

### ISSUE THREAD

**Issue by TmLev** [tfranzel/drf-spectacular#192]
Currently, tags creation is based on the first word of URL/action or
they can be specified while inheriting from `AutoSchema` and overwriting tags using `get_tags()`.
It would be nice to add more ways to tag views – for example, `schema_tags` field in view classes:
```python3
class SomeView(APIView):
    queryset = SomeModel.objects.all()
    serializer_class = SomeModelSerializer
    schema_tags = ["model", "list"]
```

**Comment by tfranzel** [comment]
hi @TmLev, i try to not mix schema declarations into the class for clarity. at least that is what i try to do unless absolutely necessary.

the following snippet has also been working for some time now. however there are unreleased (but on master) fixes that improve support for mixing and matching `@extend_schema` on the view AND the view methods.

```python
@extend_schema(tags=["model", "list"])
class SomeView(APIView):
    queryset = SomeModel.objects.all()
    serializer_class = SomeModelSerializer
```

does that address your use-case?

**Comment by TmLev** [comment]
Yeah, totally! Sorry if it was mentioned in the docs and I've missed it somehow.

**Comment by tfranzel** [comment]
sure no problem. it is not advertised in the docs, because it has had some issues till recently. now i think its safe to show more prominently.
