### ISSUE TITLE
Serving the Swagger UI over HTTPS fails

### ISSUE THREAD

**Issue by lysnikolaou** [tfranzel/drf-spectacular#193]
Hey hey,

thanks for the awesome work you've been doing :rocket:. We have encountered an error, that we think is related to how `drf-spectacular` serves the schema as HTML.

**Describe the bug**
Trying to access the Swagger UI on our staging system, which can only be accessed through HTTPS, fails with
```
Errors
 
Fetch errorFailed to fetch http://<URL>/schema
Fetch errorPossible mixed-content issue? The page was loaded over https:// but a http:// URL was specified. Check that you are not attempting to load mixed content.
```

**Expected behavior**
We'd expect that we could deploy our docs and serve it over HTTPS without problems.

**Comment by tfranzel** [comment]
hey! this was likely introduced due to #173 . i will have a look later today.

**Comment by tfranzel** [comment]
@lysnikolaou can you confirm that this works for you? pretty sure it should. would do a minor release afterwards

**Comment by lysnikolaou** [comment]
Hey @tfranzel, thanks for the quick response! Unfortunately, `pip install`ing the master here does not resolve the issue.

**Comment by tfranzel** [comment]
thanks for checking it out so quickly. i'm a bit puzzled here. i made all rendered urls relative so no http/s mixing should be going on for swagger ui. are you certain your install has the most-recent master?

```
pip install git+git://github.com/tfranzel/drf-spectacular.git@26273bb9ae33c6865bd0df9fa07ad19daa45175a
```
to be sure but `pip install -U ....@master` should be the same (+1 unrelated commit).

**Comment by lysnikolaou** [comment]
Yup, it must have been some wrong configuration on my part. Upgrading to 0.11.1 fixes this. Thanks a bunch for the quick fix.
