### ISSUE TITLE
Issue with cached properties?

### ISSUE THREAD

**Issue by tonioo** [tfranzel/drf-spectacular#198]
**Describe the bug**
If I include a ``cached_property`` decorated method in a ModelSerializer, drf-spectacular seems unable to detect the type, even if I include a type hint. If I replace the decorator by the regular ``@property``, then it works as expected.

**To Reproduce**
```python
@cached_property
def dns_status(self) -> dict:
    """Return information about current DNS status."""
    result = {}
    # stuff
    return result
```
Here is the console warning I see:
```  
Warning #1: could not resolve field on model <class 'modoboa.admin.models.domain.Domain'> with path "dns_status". this is likely a custom field that does some unknown magic. maybe consider annotating the field/property? defaulting to "string". (Exception: Domain has no field named 'dns_status')
```
**Expected behavior**
Type hint detected.

**Comment by tfranzel** [comment]
can you confirm this works for you? note that this only support `django.utils.functional.cached_property` and not the generic python version

**Comment by tonioo** [comment]
@tfranzel Yes it works now. Thank you.
