### ISSUE TITLE
What type int must I use?

### ISSUE THREAD

**Issue by tonioo** [tfranzel/drf-spectacular#199]
I have a field represented by a ``SerializerMethodField`` which returns a list of string. I have tried different things to indicate the type (using the @extend_schema and a type hint) but I always receive the same warning:
```
Warning #0: type hint for function "get_domains" is unknown. consider using a type hint or @extend_schema_field. defaulting to string.
```
Any help appreciated :)

**Comment by tfranzel** [comment]
hi @tonioo, so the type hint support is currently very minimal (basic py types & Optional[]). so no lists/dicts supported yet. i suppose #198 suffers from the same problem. this feature is simply not complete yet. let me provide a patch to extend the support. i will have a look there.

**Comment by tfranzel** [comment]
i overlooked that you used `@extend_schema`, which is not applicable here. it is for views, view methods but not serializer methods. the correct decorator would be `@extend_schema_field`, just as the warning says. :smile: have a look at those examples:

https://github.com/tfranzel/drf-spectacular/blob/master/tests/test_extend_schema.py#L55

but the type hints needed work anyway. with this fix, type hint resolution covers a lot more cases now including dict, list, tuple, and so on.

**Comment by tfranzel** [comment]
@tonioo can you confirm the fix solves your issue?

**Comment by tonioo** [comment]
@tfranzel I confirm it works now, the type hint is correctly recognized!
