### ISSUE TITLE
Support deprecated parameter

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#2]
I think it should look like an extension of `@extend_schema` decorator
Example
```python
@extend_schema(deprecated=True)
...
```

**Comment by tfranzel-cashlink** [comment]
i see what you mean. i would even go further and say that all ``operation object`` properties should be accessible via ``@extend_schema``.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#operation-object

i'll have a look at it.

**Comment by tfranzel** [comment]
closed by #3
