### ISSUE TITLE
django-mongoengine basic compatibility

### ISSUE THREAD

**Issue by last-partizan** [tfranzel/drf-spectacular#200]
Hi, i'm trying to use drf-spectacular with django-mongoengine, and this line of code is getting in the way:

https://github.com/tfranzel/drf-spectacular/blob/05e4b9021582da45c75d4b9fb56126ce115fd900/drf_spectacular/openapi.py#L353

I must write [ugly monkey-patching](https://github.com/MongoEngine/django-mongoengine/commit/463eb03db54cd79820f5cc360fc10b672a787f53) to get around of this.

Could you please change this check, to something like `looks_like(model_field)`?

Something like `hasattr(model_field, "get_internal_type")` would do, if this check is really required. But, for me it works fine without it. Maybe even just delete that line?

I can write PR if you suggest changes. Or maybe you can suggest less ugly way to fool isinstance.

**Comment by tfranzel** [comment]
hi @last-partizan,

yes that's an ugly hack for sure. :smile:  so initially the purpose of this line was to make sure the assumptions hold and there is no crazy usage with hard to understand stacktraces. at the time i was not aware of alternate model implementations. yes i think this could be changed with little impact. the question i ask myself is whether this one line will be sufficient to support `MongoEngine`.

I'm not sure if you noticed the `MongoEngine` PR we currently have: #181 .  It is still missing tests, for which i provided a sample in the comments. Though, I have not heard back from the PR author @ngocngoan. 

According to this PR it looks like other things need to (slightly) change too. I see you are the maintainer of `MongoEngine`, so i guess you have a lot more insight into what would be required for good support on our side. What do you think?

**Comment by last-partizan** [comment]
@tfranzel no, i didn't noticed that PR. Looks nice.

But, that's for raw `mongoengine` and `djangorestframework-mongoengine` and i don't familiar with it enough.

I am maintaining `django-mongoengine`, and it is slightly different beast, it tries to imitate django behaviours on top of mongoengine, so it can work with forms, views and django admin.

I'm using raw Serializers, with custom save/update methods, so for my case, just changing that line would be enough. And adding some methods like `get_internal_type` for fields in django-mongoengine, which i already done.

**Comment by last-partizan** [comment]
No need for any changes, i subclassed AutoSchema instead of my ugly hack.

https://github.com/MongoEngine/django-mongoengine/commit/2ef9529e330d482957acf582a56ac7aeabe853c6

**Comment by tfranzel** [comment]
i'm glad the PR pointed you in the right direction. if you have trouble down the line, we can certainly can come back and do the change.
