### ISSUE TITLE
Add non-serializer based response on extend_schema responses parameter

### ISSUE THREAD

**Issue by matheussouza9** [tfranzel/drf-spectacular#201]
I would like to use non-serializer response types like django's `django.http.FileResponse`.
Currently is there a way to do this? According to the `extend_schema` docstring, it only accepts `Serializer` classes. https://github.com/tfranzel/drf-spectacular/blob/8ce31452e3ee6bb4be3ebfbcd9907045107577c8/drf_spectacular/utils.py#L104-L112

**Comment by tfranzel** [comment]
hi, yes we kind of do support this,however it is not fully documented:

```python
@extend_schema(responses=OpenApiTypes.BINARY)
```
the problem i see is the `media_type`. it gets extracted from the `APIVIew` via the `renderer_classes` and is ususally `application/json`, which would not fit that well here. maybe we do need an option to override it in `extend_schema` as having a mocked `Renderer` class with a different `media_type` seem kind of weird.

**Comment by matheussouza9** [comment]
If I have this case, the `media_type` depending on http status, the option would need be solved in each `response` item.
```
@extend_schema(
    responses={
        200: OpenApiTypes.BINARY,
        500: ErrorSerializer,
    }
)
```

**Comment by tfranzel** [comment]
@matheussouza9, yes exactly. thanks for pointing that out. added a feature to extend_schema to account for this

```python
@extend_schema(
    responses={
        (200, 'application/pdf'): OpenApiTypes.BINARY,
        500: ErrorSerializer,
    }
)
```

with that, specific responses can have a custom media_type. multiple usage is supported too, i.e. multiple tuples for one code with differing content types.

please check if that works for you as expected

**Comment by matheussouza9** [comment]
@tfranzel Works like a charm :) Thanks!
