### ISSUE TITLE
@extend_schema_view not customising the default rendered schema.

### ISSUE THREAD

**Issue by haccks** [tfranzel/drf-spectacular#203]
I wanted to change the name of `operation_id `, add a description and summary. I tried this:

```
@extend_schema_view(
    list=extend_schema(
        description='Returns user activity list',
        summary='List summary',
        operation_id='Activity list',
    ),
    create=extend_schema(
        description='Create a user activity',
        summary='Create summary',
        operation_id='Activity create',
    ),
)
class ActivityListView(generics.ListCreateAPIView):
    # rest of the code goes here
```

But this does nothing to the schema. I am serving schema directly from the API. 

What I am getting right now:

**activity**
 -- Nothing appear here
**activity_list**                                            
 -- Nothing appear here  

My expected output:

**activity**
Everything about user activities                       # <--- Description for the tag

**Get list of user activities**                             # <--- Change the operation id
Get a list of all activities of a particular user.  # <--- Summary for the operation

**Comment by tfranzel** [comment]
it does nothing because `list` and `create` are not correct here. They apply to `Viewset`s only . `ListCreateAPIView` on the other hand has `get` and `post`. 

Sidenote: those methods do exist in `ListCreateAPIView`, but they are not the entry points DRF is using. Decoration needs to happen on the proper entry points.

**Comment by haccks** [comment]
@tfranzel Yes. You are right. I was following the documentation and I completely forgot it should ge `get` and `post` for `CreateListAPIView`. Thanks a lot for helping out. Is this behaviour mentioned in the doc anywhere or any place I can read?

**Comment by haccks** [comment]
One more thing, I am getting **"api"** tag along with my APIs tags. It has just one endpoint: `/api/schema/`. Is that expected behaviour or somehow I can remove it?

**Comment by tfranzel** [comment]
it is not explicitly mentioned anywhere. 

please have a look at the settings:
https://drf-spectacular.readthedocs.io/en/latest/settings.html

```
'SERVE_INCLUDE_SCHEMA': False,
```
to disable the schema in the spec. tag extraction can be controlled with 
```
# path prefix is used for tagging the discovered operations.
# use '/api/v[0-9]' for tagging apis like '/api/v1/albums' with ['albums']
'SCHEMA_PATH_PREFIX': r'',
```

**Comment by haccks** [comment]
> please have a look at the settings:
> https://drf-spectacular.readthedocs.io/en/latest/settings.html
> 
> ```
> 'SERVE_INCLUDE_SCHEMA': False,
> ```

Worked like a charm! Thanks  a lot. 




> tag extraction can be controlled with
> 
> ```
> # path prefix is used for tagging the discovered operations.
> # use '/api/v[0-9]' for tagging apis like '/api/v1/albums' with ['albums']
> 'SCHEMA_PATH_PREFIX': r'',
> ```

Tried this
`'SCHEMA_PATH_PREFIX': r'/api/v0',

And now I have no idea how this is going to work.

**Comment by tfranzel** [comment]
this is a regex. all it does is stripping a matching prefix for tag extraction. only the first url item is used.

`'SCHEMA_PATH_PREFIX': r'/api/v[0-9]'` with endpoint `/api/v1/foo/{id}/bar` would simply generate the tag `foo`

`'SCHEMA_PATH_PREFIX': r''` with endpoint `/api/v1/foo/{id}/bar` would generate the tag `api`

nothing more to it.

**Comment by haccks** [comment]
I think I got it. I am following this documentation for reference and I will get back to you if need any further help. I am closing this issue. Apart from that, I think documentation needs some more work and examples. Once I will have some good idea about using this tool then I would like to contribute to the documentation.
