### ISSUE TITLE
A (somewhat complex) type hint doesn't work

### ISSUE THREAD

**Issue by jacobian** [tfranzel/drf-spectacular#207]
**Describe the bug**

I've got a `SerializerMethodField` that returns a moderately complex object of the form:

```json
[
  {
    "component": "component 1",
    "counts": {
        "cat1": 1,
        "cat2": 2,
        ...
    }
  },
  {
    "component": "component 2",
    "counts": {
        "cat1": 1,
        "cat2": 2,
        ...
    }
  },
  ...
]
```

So, I did this:

```python
class RatingSummary(TypedDict):
    component: str
    counts: Dict[str, int]

class ContractorSerializer(serializers.HyperlinkedModelSerializer):
    rating_summary = serializers.SerializerMethodField()

    def get_rating_summary(self, contractor: Contractor) -> List[RatingSummary]:
        ...
```

But, it doesn't work; I get this error message:

```Warning #0: could not resolve type for "<class 'xxx.rest.serializers.RatingSummary'>". defaulting to "string"```

**To Reproduce**

It looks like the specific part that makes it fail is having the return type be `List[ < any complex type >]` -- that is, `List[int]` or `List[string]` works correctly, but `List[Dict[str, str]]`, or any non-primitive type, fails.

**Expected behavior**
I'd love for this to work!

**Workaround**
There is an OK workaround, which is to define a serializer rather than the type hint, and annotate that on with `@extend_schema_field` - e.g.:

```python
class RatingSummarySerializer(serializers.Serializer):
    component = serializers.CharField()
    counts = serializers.DictField(child=serializers.IntegerField())

class ContractorSerializer(serializers.HyperlinkedModelSerializer):
    @extend_schema_field(RatingSummarySerializer)
    def get_rating_summary(self, contractor: Contractor) -> List[RatingSummary]:
        ...

```

This isn't perfect because `RatingSummarySerializer` isn't actually a serializer -- it's really just there for schema generation -- so that makes the code slightly confusing. But it's an acceptable workaround, IMO.

**Comment by tfranzel** [comment]
hi @jacobian, nice catch! brand new feature and people are already pushing the limits :smile: that bug was a small oversight. added your case to the test cases. it should now work as expected

fyi: sometimes there is no getting around a one off serializer for complicated situations (not here tough). in those cases you can prevent having a misleading schema serializer laying around by using this:

```python
@extend_schema_field(inline_serializer(
        name='RatingSummarySerializer',
        fields={
            'component': serializers.CharField(),
            'counts': serializers.DictField(child=serializers.IntegerField())
        }
))
def get_rating_summary(self, contractor: Contractor):
    ....
````

**Comment by jacobian** [comment]
Wow, that was super-fast -- thank you!

And thanks for the note on `@inline_serializer` - I'm sure that'll be helpful in other cases.

**Comment by tfranzel** [comment]
you're welcome. please close the issue if all works out fine

**Comment by jacobian** [comment]
Yup, verified that it works in my specific case -- thank you again!
