### ISSUE TITLE
[Feature Request] tag operations with django app name

### ISSUE THREAD

**Issue by elonzh** [tfranzel/drf-spectacular#210]
Usually our apis are organized by django apps, so it is reasonable to tag operations with django app name.

Moreover, we can add settings for app level tags, like:

```python
SPECTACULAR_SETTINGS = {
    ...
    "ADD_APP_NAME_TAG": True,
    "APP_TAGS": {
        "<app>": ["tag1", "tag2"]
    }
}
```

**Comment by tfranzel** [comment]
hi @elonzh,

tags are a very opinionated topic and everyone has a different interpretation on what the tags should be. what you describe certainly makes sense for you, but there is a multitude of ways to do this and i don't want to add a couple of parameter for every flavor there is. 

In my opinion this one of the few areas where the user should formalize their requirements themselves. We tried to make this as easy as possible. Subclass `AutoSchema` (and add it in the settings) and override this method:

https://github.com/tfranzel/drf-spectacular/blob/9e29f150d495adb54ffd3c8daf2207f6631797d0/drf_spectacular/openapi.py#L246-L250

**Comment by tfranzel** [comment]
glad you agree. closing this
