### ISSUE TITLE
Replace query parameters

### ISSUE THREAD

**Issue by Debakel** [tfranzel/drf-spectacular#212]
Using the `@extend_schema` decorator as below will append `foo` to the list of auto-discoverd query parameters. Is it instead possible to _replace_ the list with the given values (so that `foo` will be the only paramter)?

```
class FooBarView(CreateAPIView):
    @extend_schema(
        parameters=[OpenApiParameter(name="foo")],
    )
    def post(self, request, *args, **kwargs):
        return Response(data={"foo": "bar"})
```

Thank you! :-)

**Comment by tfranzel** [comment]
Hi @Debakel,

this is a design choice, because it is by far the most common use case: adding additionals to the discovered parameters. 

usually, the discovered parameters (path, filter, pagination, format) are pretty solid and they are just missing manual ones fetched in the body with `request.GET.get('foo')`. if something got detected incorrectly, you can fix it by overriding it in the `extend_schema` parameters list. i could imagine a `OpenApiParameter('foo', exlude=True)` to explicitly disable a param. 

can you give an example why you need this?

**Comment by Debakel** [comment]
My endpoints `GET` method is built using django batteries, but the `POST` method contains some complex custom logic. Most of the auto-discovered parameters are not available for the POST endpoint, so i would like to be able to overwrite the auto-discovered values and describe the schema manually.

Maybe like this:

     @extend_schema(additional_parameters=[...])

     @extend_schema(replacement_parameters=[...])

**Comment by tfranzel** [comment]
i see what you mean. we have to find a way to add this functionality without breaking the interface or making it harder to understand.

a plus for `exclude` is that we use the exclusion idiom already in other locations. would my proposal be feasible for you, i.e. adding `OpenApiParameter('foo', exclude=True)` explicitly for the non-applicable parameters? that way the interface stays the same, we have a exclusion option, and nothing changes for the main use case. i get that this is not optimal for you, but we have to weigh the options.

**Comment by tfranzel** [comment]
added the exclusion feature as outlined. it should get the job done for your use case, even if slightly inconvenient to use.

can you confirm that this works for you?

**Comment by sommelon** [comment]
Hey,
My custom AutoSchema adds the `query` parameter to all views, but I don't want it in one particular case.
I wanted to use the `exclude` parameter and I'm getting this error.
```
File "...\backend\.venv\lib\site-packages\drf_spectacular\openapi.py", line 194, in _get_parameters
    del parameters[key]
KeyError: ('query', 'query')
```

**Comment by tfranzel** [comment]
looks like it works to me. you are trying to remove a parameter `query, query` (name and type identical). maybe you have not properly added that parameter in the first place. what is ``query_param`` exactly? 

but this is not supposed to throw so i added a bugfix, but i'm not sure your problem will go away from it.

**Comment by sommelon** [comment]
Sorry, the query param is this
```
query_param = OpenApiParameter(name='query', description='''
Allows for selecting which fields to include in the response.\n
The full documentation is available at: [RESTQL](https://django-restql.yezyilomo.com)
''')
```
I added the check before `del`, but that didn't help. Any idea where the problem can be?
I don't know if that's related, but I'm using [RecursiveField](https://github.com/heywbj/django-rest-framework-recursive) in the view serializer.
```
class UnitTreeSerializer(serializers.ModelSerializer):
    attributes = UnitTreeAttributesSerializer(source='*', read_only=True)
    children = serializers.ListField(source='get_children', read_only=True, child=RecursiveField())
```

**Comment by sommelon** [comment]
Did some debugging and the `overriden_parameters` get removed in the `path_variables` [L#183](https://github.com/tfranzel/drf-spectacular/blob/f23de89dd94fc3238650334725aa2bcd1ace73e2/drf_spectacular/openapi.py#L183) and since it's not in `parameters`, but is in `excluded_parameters` the error gets raised.

**Comment by tfranzel** [comment]
very good observation @sommelon! i did not anticipate that scenario. i will give it some thought but your example will be the most likely result, as it is simply broken right now.

**Comment by tfranzel** [comment]
@sommelon, i believe this will finally fix this. restructured some details for more consistency. could you confirm this works now as expected?

**Comment by sommelon** [comment]
I'm gonna need your help on this one. I've never done something like this. I'm assuming I have to pip install from git. If I do this `pipenv install git+https://github.com/tfranzel/drf-spectacular`, will I be able to rollback to the latest release in case something goes wrong just by doing `pipenv install drf-spectacular`?

**Comment by tfranzel** [comment]
looks good to me. to restore the release version you will probably have to uninstall and install it again via pipenv to purge the master version.

**Comment by sommelon** [comment]
I had to add `#egg=drf-spectacular` to the command.
Everything seems to be working fine now. Thank you very much for your work!

**Comment by sommelon** [comment]
@tfranzel Hey, I pushed the Pipfile and Pipfile.lock with the git version to our repo and my colleagues can't install it. `pipenv install` only installs the latest version of drf-spectacular from pypi even though `drf-spectacular = {git = "https://github.com/tfranzel/drf-spectacular"}` is in the Pipfile and Pipfile.lock. Do you, by any chance, know if there is a way to force pipenv to install the git version? Don't bother searching for the solution if you don't know. I will rollback the changes and wait for the pypi release if necessary.

**Comment by tfranzel** [comment]
not from the top of my head, because i'm not a pipenv user. we switched to poetry. i will definitely do a release this week.
