### ISSUE TITLE
Parameters from serializer

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#215]
Currently the only way to define `query parameters` for `function-based views` is to use
```py
@extend_schema(
    methods=["GET"],
    parameters=[
        OpenApiParameter(name="year", type=int, required=True),
        OpenApiParameter(name="month", type=int, required=True),
        OpenApiParameter(name="day", type=int, required=False),
    ]
)
@api_view(["GET"])
def data_from_date(request: Request):
    ser = QueryParamSerializer(data=request.query_params)
    ...
```

Since we're migrating from `drf-yasg` (due to OpenApi Schema 3), we're used to doing
```py
@swagger_auto_schema(
    method="GET",
    query_serializer=QueryParamSerializer
)
@api_view(["GET"])
def data_from_date(request: Request):
    ser = QueryParamSerializer(data=request.query_params)
    ...
````

this way we don't have to duplicate serializer data to `parameters`.

Is there any plans to support parameters from serializer also?

**Comment by tfranzel** [comment]
Hi @HansAarneLiblik,

have you tried just putting in a serializer? i believe we support this for quite some time now. we have no test for function-based views here, but it should be functionally identical to this test with an action:

https://github.com/tfranzel/drf-spectacular/blob/a8a1caaf4455351f671a07b6eddf97eff5ff0813/tests/test_extend_schema.py#L134-L138

**Comment by HansAarneLiblik** [comment]
Wow, thanks! It indeed worked. 👍 

Previously tried `parameters=QueryParamSerializer`, but it had to be a list `parameters=[QueryParamSerializer]`

I suggest you update apidoc for the decorator also :)

Thank you!

**Comment by tfranzel** [comment]
yes i will add some more docs and type hints. good suggestion

**Comment by KimSoungRyoul** [comment]
check this PullRequest & Could you close this issue?
https://github.com/tfranzel/drf-spectacular/pull/225
