### ISSUE TITLE
String response definition

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#217]
**Describe the bug**
Unable to have `str` as response

**To Reproduce**
```py
@extended_schema(
    responses={200: "Done"}
)
@api_view(["POST"])
def do_it(request):
    return Response("Done")
```

>Warning #0: could not resolve "Done" for POST /api/do-it. Expected either a serializer or some supported override mechanism. defaulting to generic free-form object.

**Expected behavior**
Schema should have "Done" as response.

**Probable cause**
```py
def is_basic_type(obj, allow_none=True):
    if not isinstance(obj, Hashable):
        return False
    if not allow_none and (obj is None or obj is OpenApiTypes.NONE):
        return False
    return obj in OPENAPI_TYPE_MAPPING or obj in PYTHON_TYPE_MAPPING
```

should be 
```py
return obj in OPENAPI_TYPE_MAPPING or type(obj) in PYTHON_TYPE_MAPPING
```
or to allow for `responses={200: str}`
```py
return obj in OPENAPI_TYPE_MAPPING or obj in PYTHON_TYPE_MAPPING or type(obj) in PYTHON_TYPE_MAPPING
```

**Comment by tfranzel** [comment]
hi @HansAarneLiblik, `responses={200: "Done"}`  is not supported as it is a concrete value (aka examples, which we currently work on). giving types however should be supported.

what currently works is this: `responses={200: OpenApiTypes.STR}`, but i will have a look at the raw types.

**Comment by tfranzel** [comment]
as it turns out `{'200': str}` is already supported. added a test for the main variations. this should do it i think.
