### ISSUE TITLE
Extended support for the version parameter

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#219]
**Describe the bug**
When I use versioning endpoint, the version of my swagger(`SPECTACULAR_SETTINGS.VERSION`) will not updated. I get version from my SPECTACULAR_SETTINGS.VERSION

**Expected behavior**
The parameter  `SPECTACULAR_SETTINGS.VERSION` must depend on  should versioning endpoint

p.s Thanks for best package 😄

**Comment by tfranzel** [comment]
Thanks @MissiaL! long time no see. you make a valid point. however i'm not 100% sure of the semantics of the `VERSION` string.

you may have versions/iterations of an API even in the presence of versioning classes (`v1`, `v2`). For example when an endpoints is added to both you could do `1.0.0` -> `1.1.0`. i consider the `v1`/`v2` as scoped projections of the root schema. so i believe both could have a meaning at the same time.

what do you think about this? having the version `1.0.0` there and a scope `v1`:

```yaml
openapi: 3.0.3
info:
  title: ''
  version: 1.0.0 (v1)
paths:
```

**Comment by MissiaL** [comment]
It looks interesting
How will schema versioning work in this case?

**Comment by MissiaL** [comment]
I resolved this issue by postprocessing hook

My solution
```
def set_schema_version(
    result: dict, generator: SchemaGenerator, request: Request, public: bool
) -> dict:
    version = getattr(request, 'version', settings.LATEST_API_VERSION)
    result['info']['version'] = version
    return result
```
