### ISSUE TITLE
DRF generic error response in schema

### ISSUE THREAD

**Issue by tomas-hanzlik** [tfranzel/drf-spectacular#220]
I would like to have the structure of generic DRF errors in the generated schema but so far no success. Specifically, show the structure of `ValidationError` with a custom description like `List of validation errors not related to any field`.

Basically the same as here: https://github.com/axnsan12/drf-yasg/issues/224

Is there a way how to do it? Thank you!

**Comment by tfranzel** [comment]
Hi! error declaration is not yet supported but on the my roadmap. i think #101 more generally addresses this.

**Comment by thanzlik** [comment]
Hi @tfranzel , thank you for your time and for the clarification! :)

**Comment by tfranzel** [comment]
duplicate of #101

**Comment by sourabhtkd** [comment]
add NON_FIELD_ERRORS_KEY in settings.py as per https://www.django-rest-framework.org/api-guide/exceptions/.
For 500 or any unexpected errors write a custom exception handler, when exception is raised then log the exception and return your generic response
