### ISSUE TITLE
Multiple schemas support

### ISSUE THREAD

**Issue by konkab** [tfranzel/drf-spectacular#221]
Since the app uses settings to get OpenAPI data like `title`, `version`, `description`, `servers` and so on, it's not possible to implement two different schemas with different settings out of the box. It would be nice to have this.

Is there any workaround for this?

**Comment by konkab** [comment]
Ok, so in the workaround I subclassed `SchemaGenerator` and in `get_schema` method I change `spectacular_settings` on the fly based on request path.

"app".generators.py:
```python
from drf_spectacular.generators import SchemaGenerator
from drf_spectacular.settings import spectacular_settings


class SchemaGenerator(SchemaGenerator):
    def get_schema(self, request=None, public=False):
        if '/api/doctors/schema/' in request.path:
            spectacular_settings.TITLE = 'Doctors API'
        elif '/api/patients/schema/' in request.path:
            spectacular_settings.TITLE = 'Patients API'

        return super().get_schema(request=request, public=public)
```

**Comment by MissiaL** [comment]
I think you can try postprocessing hook
see https://github.com/tfranzel/drf-spectacular/issues/219

**Comment by konkab** [comment]
> I think you can try postprocessing hook
> see #219

Yes, this a more elegant solution. Thanks.

**Comment by KimSoungRyoul** [comment]
Swagger.3.x.  support  https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

if we are use  these feature(`oneof-anyof-allof`)

 multi response can be supported

<img width="1750" alt="스크린샷 2020-12-06 오후 9 32 48" src="https://user-images.githubusercontent.com/24240623/101280132-a391c580-380a-11eb-83d2-9d6cff72e696.png">


@tfranzel   
#### what do you think  about  reflect this swagger spec(`oneof-anyof-allof`) to drf-spectacular?

I'm going to make sure you follow your opinion completely

be willing?   (if you willing this, I try this feature)
be unwilling?
priority low (fix bud first)?





#### FYI
 these spec(`oneof-anyof-allof`) has problem to strictly type language(Java) with swagger code-gen

[Swagger-Codegen Issue Not Resolved - (oneOf or allOf or anyOf would generate spring or java model empty class)](https://github.com/swagger-api/swagger-codegen/issues/9720)

**Comment by tfranzel** [comment]
@konkab i suppose this feature would be hard to reasonably generalize. i think a postprocessing hook is suited the best just as @MissiaL said.

@KimSoungRyoul not sure this addresses the issue. what you propose though is already available here: https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.PolymorphicProxySerializer

**Comment by tfranzel** [comment]
i guess this issue is resolved. @konkab feel free to comment again if there is still something missing. closing for now.
