### ISSUE TITLE
Overload example value ?

### ISSUE THREAD

**Issue by eLvErDe** [tfranzel/drf-spectacular#222]
Hello,

I'm not sure if I mis-understood the documentation but it seems the only solution to override payload response object is to use extend_schema and provide a custom serializer. Fair enough, but how do I set "example" field (per OpenAPI specification), as there is no such optional available in Django serializer ?
Is there any way to do that ? Would you consider adding such feature otherwise ?

Thanks in advance,

**Comment by tfranzel** [comment]
Hi @eLvErDe, we have PR #208 for the examples feature. it is basically done but i have still some polishing to do. most likely in the next couple of days.

**Comment by eLvErDe** [comment]
Sorry I missed this PR, indeed it looks awesome, would be delighted to have this :-)

**Comment by yovelcohen** [comment]
@tfranzel not sure if this is the way it was intended, I tried a workaround of supplying a List Field and a nested Dict Field.
 `   
 score = serializers.ListField(child=serializers.DictField(),
                                  default=serializers.DictField(default={"score_of_group1": 0,
                                                                         "date": "2020-12-13",
                                                                         "score_of_group2": 0},
                                                                read_only=True
                                                                ))
`


But taking a look at the swagger example response: 
`{
  "score": [
    {}
  ]
}` 

it's missing the default I specified

**Comment by tfranzel** [comment]
hi @yovelcohen, i'm unsure whether this is even supported in DRF. i was under the assumption that default values need to be concrete values like: 
```
score = serializers.ListField(child=serializers.DictField(), default=[{"score_of_group1": 0, "date": "2020-12-13", "score_of_group2": 0}], read_only=True)
```

written like this, it then shows up in the swagger ui autogenerated example.

**Comment by tfranzel** [comment]
feature was added via #208 and #231
