### ISSUE TITLE
Define DRF Default APIException like 400,404,401,403, 500 to Swagger Schema & Customizing with drf-spectacular settings

### ISSUE THREAD

**Issue by KimSoungRyoul** [tfranzel/drf-spectacular#223]
#220  
#101 

you discussed about how to  handle drf error to  swagger schema

---
[This is what @tfranzel  was mentioned in  #220](https://github.com/tfranzel/drf-spectacular/issues/101#issuecomment-647440115)
##### this needs some investigating on how to do error handling in a flexible and generic way.

* this might be best located in the responses section of the schema
* do wildcards like 40X work with client generator? mayne this needs to be demultiplexed
* is there a a good schema representation for the errors with a payload? i believe ValidationError can take multiple forms.
* is this always application/json or are the view's renderer classes honored?
* how to handle custom error exceptions in addition to the DRF's native ones?
* do we need another argument to @extend_schema or can this be folded into responses?
---

I think this feature would be reflected to drf-spectacular for better quality.

so I suggest how to handle error with schema

#### it' just my opinion  after reading your discussions

i want your feedback  @tfranzel  @jayvdb 

If there's no work in progress, I want implement this feature

~~~Python
# drf-spectacular.settings.py

SPECTACULAR_DEFAULTS= {
   # ...
  "ENABLE_USE_DEFAULT_RESPONSE": True,  

  "DEFAULT_RESPONSE_CLASS" : {
         "404":  "rest_framework.exception.NotFound",
         "401":  "rest_framework.exception.NotAuthenticated",
         "403":  "rest_framework.exception.PermissionDenied",
          ....  
          # set drf default APIException
   }
}
~~~

And... 

~~~Python
# users_django_project.settings.py

SPECTACULAR_SETTINGS= {
   # .....
   # if True ,  ALL API use DEFAULT_RESPONSE_CLASS to Response Swagger Schema    

  "ENABLE_USE_DEFAULT_RESPONSE" : False,  
  "DEFAULT_RESPONSE_CLASS" :  {
         "404":  "users_django.custom_exceptions.CustomNotFound",
          # can customize what they want
   },

}
~~~

~~~Python
# users_django.views.py

...

class AModelViewSet(ModelViewSet):
     
    @extend_schema(
         # even if settings.SPECTACULAR_SETTINGS["ENABLE_USE_DEFAULT_RESPONSE"]
         #  we can use DEFAULT_RESPONSE ,  below value is True
         enable_default_response=True  
     )
    def list(request, *args, **kwrags):
          return super().list(request,*argw, **kwargs)

~~~

**Comment by tfranzel** [comment]
@KimSoungRyoul thanks for having a look at this. as a matter of fact i already have a work in progress, but i have not gotten around finishing it. you have interesting ideas there. i'll try to incorporate them. 

sry i have not finished the examples yet. i had unexpected things happening, which i had to take care of. will resume work shortly. priority list: examples, 2-3 bugs and then exceptions.

**Comment by KimSoungRyoul** [comment]
that's a. good news.   i will close this issue 

& 

never mind  about not finished yet

**Comment by KimSoungRyoul** [comment]
by the way 

could you tell me 
What are the high priority issues that do not have an assignee ?
