### ISSUE TITLE
support @extend_schema_filterset

### ISSUE THREAD

**Issue by KimSoungRyoul** [tfranzel/drf-spectacular#224]
~~~Python
@extend_schema_parameter(
   # something to customize.  
)
class UserFilterSet(filters.FilterSet):
     
    class Meta:
         model = User
         fields = ("username","email") 

~~~
#115

**Comment by tfranzel** [comment]
hey @KimSoungRyoul, before you invest time here let me re-evaluate this. i actually had a `OpenApiFilterExtension` as a potential feature. i have not fully investigated, what makes the most sense. let me figure that out first so that you do not waste time.
