### ISSUE TITLE
Parameters no longer show their defaults

### ISSUE THREAD

**Issue by chaosk** [tfranzel/drf-spectacular#226]
Hello!

Starting with 0.9.14, all parameters ignore certain attributes, such as `default`. Previously this only affected path parameters (since they must be required, a default value doesn't make much sense). 

Describing defaults for query params seems very useful to show how API behaves when not provided with a parameter value.

Would it be possible to bring back previous behavior, or at least make it easier to customize?

**Comment by tfranzel** [comment]
hey @chaosk, there was no intended change there as far as i remember. i'll have to investigate.

**Comment by chaosk** [comment]
From the looks of it, it was this change: https://github.com/tfranzel/drf-spectacular/commit/50eff74ead8a4240622ead17b8955dbcd5304d45#diff-d727722caf6fe5f5507940c9efbcbe843fcca1dec9ac64402f074b08dd1c294fR250

**Comment by tfranzel** [comment]
ahh thx, good catch. i'll try to remedy that.

**Comment by tfranzel** [comment]
@chaosk the original behavior should be largely restored with that change.

**Comment by chaosk** [comment]
Thank you for quick fix!
