### ISSUE TITLE
Can we keep the parameters order as defined?

### ISSUE THREAD

**Issue by wonderbeyond** [tfranzel/drf-spectacular#228]
https://github.com/tfranzel/drf-spectacular/blob/4b53cea1f369f5b71e8781b766595bf46cdc6358/drf_spectacular/openapi.py#L165-L184

At line 184, the parameters are ordered by name. Can we return the values directly to just keep the dict's insertion order?

> `return list(parameters.values())`

**Comment by tfranzel** [comment]
hi @wonderbeyond, pretty much everything else is also sorted alphabetically and this was chosen for consistency and schema stability. the insertion order might not even be meaningful as there are multiple sources coming together. however, you can easily change this behavior by subclassing `AutoSchema`.

**Comment by wonderbeyond** [comment]
Thanks @tfranzel I define the filter items in a meaningful order, and I keep related items together, also I don't want the filter parameters and pagination parameters are mixed. So the insertion order to me is important.

**Comment by tfranzel** [comment]
i would refrain from introducing a new setting for now as this is a typical case of taste preference. in the past people requested that those lists should be sorted and i agreed. 

of course you can simply subclass `AutoSchema` in your code and override `_get_parameters` for now. that function is very stable and not subject to planned changes (except for bugfixes).

if this thing comes up again in the future we can have a look again. for now i'll close the issue if you don't mind.
