### ISSUE TITLE
Component re-registration warning when two paginated list endpoints use the same serializer

### ISSUE THREAD

**Issue by Lucidiot** [tfranzel/drf-spectacular#233]
**Describe the bug**

When two or more paginated list endpoints use the same response serializers, a warning appears when generating the schema:

```
Warning #0: trying to re-register a schemas component with name PaginatedFooList. this might lead to a incorrect schema. Look out for reused names
```

**To Reproduce**

Create two list endpoints with the same serializer, and set a default pagination class in the settings (or add one in `pagination_class` on each endpoint).

```python
class FirstList(ListAPIView):
    serializer_class = FooSerializer
    ...

class SecondList(ListAPIView):
    serializer_class = FooSerializer
    ...
```

**Expected behavior**

The same component gets reused without a warning.

Maybe [this check](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/plumbing.py#L440) could be modified to not warn when the two components are the same, not just by key? Or should [this part](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L946) check whether the exact same component already exists before registering?

**Comment by tfranzel** [comment]
hey @Lucidiot, yes that looks like a bug. the warning is unwarranted in most circumstances.  i'll refine that spot to catch problems and not emit false positives.

**Comment by tfranzel** [comment]
that should do it. please confirm and close the issue

**Comment by ShaheedHaque** [comment]
I'm not sure if you would consider this the same issue, but (using the 0.12.0 release), I see this:
```
Warning #0: Encountered 2 components with identical names "PaginatedEmployeeList" and different classes <class 'api.employee.EmployeeSerializer'> and <class 'rest_framework.serializers.ListSerializer'>. This will very likely result in an incorrect schema. Try renaming one.
```
even though the ListSerializer (implicitly, via `many=True`) specifies the EmployeeSerializer as its child:
```
@extend_schema_view(
    ...
    employees=extend_schema(..., responses={HTTP_200_OK: EmployeeSerializer(many=True)}),
    ...
)
```
Or perhaps I am not using `extend_schema` as expected?

**Comment by tfranzel** [comment]
hey @ShaheedHaque, i think you are doing it right and i missed a case. the test case did only cover multiple viewsets and not actions. i can see how this happened. i'll investigate. the schema however should still be correct i believe.

**Comment by tfranzel** [comment]
@ShaheedHaque i extended the test. should now behave as expected. schema was unaffected, only a false positive warning.

**Comment by ShaheedHaque** [comment]
Excellent.

And, as a newbie to (both drf and) drf-spectacular, I'd like to say thank
you for the excellent software.

**Comment by Lucidiot** [comment]
Just updated and I no longer see any warnings. Thank you very much!
