### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by krmozejko** [tfranzel/drf-spectacular#236]
#208 introduced a very useful feature. Actually, it is a thing which made me interested in replacing drf-yasg with drf-spectacular. Is there a plan to make a next release soon, so we could leverage that feature without being forced to use master branch in our dependencies? :grin:

**Comment by tfranzel** [comment]
hi @krmozejko, yes it is already underway. probably happening today. still fixing up some loose ends.

**Comment by krmozejko** [comment]
@tfranzel that is awsome, thank you very much :)

**Comment by tfranzel** [comment]
released `0.12.0`
