### ISSUE TITLE
request/response serializers dependent on request method

### ISSUE THREAD

**Issue by NANASHI0X74** [tfranzel/drf-spectacular#237]
I'm exploring wether code generation is viable to generate a client to an existing django-rest-api...
Now I've come across a view method that I need that looks like this:

```python
    @action(methods=['get', 'post'], detail=True)
    def protocols(self, request, pk):
        if request.method == 'GET':
            return self.get_protocols(request, pk) #requests nothing, returns with protocolListSerializer
        elif request.method == 'POST':
            return self.post_protocols(request, pk) #requests ProtocolEditSerializer, returns with ProtocolEditSerializer
```

It doesn't look like the extend_schema decorator covers that scenario at first glance...
Is there a way to deal with this sort of scenario? 
Would this be worth adding as a feature if not? (i.e. I guess the request and response parameters of extend_schema would accept dicts with mappings from Method -> serializer or another dict with status -> serializer)

**Comment by tfranzel** [comment]
hey, yes this should already be covered. `extend_schema` is scope-able to the method (default: all). see the corresponding tests:

https://github.com/tfranzel/drf-spectacular/blob/c3a128eb2f7b95aa380221bbc7d2d70f81b3cc3a/tests/test_regressions.py#L193-L202

https://github.com/tfranzel/drf-spectacular/blob/c3a128eb2f7b95aa380221bbc7d2d70f81b3cc3a/tests/test_regressions.py#L290-L304

**Comment by NANASHI0X74** [comment]
thanks, guess I'm just blind 🤦‍♂️ :D

**Comment by NANASHI0X74** [comment]
may I ask for help once more? :S Is it possible to define filtersets in extend_schema or through some other mechanism for function-based views?
I see that spectacular apparently finds filterset_class members in class-based views and adds the fields as query parameters in the resulting spec, which is great 😄 but can this be done for view functions as well?

**Comment by tfranzel** [comment]
well, this is not really intended. `@api_view` is just syntactic sugar for ``class X(APIView):`` so you could inject a filter backend manually like this:

```python
    @extend_schema(responses=SimpleSerializer(many=True))
    @api_view(['GET'])
    def pi(request):
        pass  # pragma: no cover
    
    # simple filter backend
    pi.cls.filter_backends = (SearchFilter,)

    # or django-filters
    pi.cls.filter_backends = (DjangoFilterBackend,)
    pi.cls.queryset = Product.objects.all()
    pi.cls.filterset_class = ProductFilter
```

but it is hacky and your mileage may vary as this is only intended for ``GenericAPIView`` and not ``APIView``.

**Comment by NANASHI0X74** [comment]
hmm I was mistaken, it's actually not a function-based view in this case, but an `@action` in a ModelViewSet that just deals with a different queryset and filterset than the base class. But thanks for the hack 😁

**Comment by tfranzel** [comment]
in that case it should be alot easier. you can pass `filter_backend` and the likes into `@action` as parameter to override.

**Comment by NANASHI0X74** [comment]
it looks like I can't do that for filterset_class:
```
 TypeError: CompanyViewSet() received an invalid keyword 'filterset_class'
```
it doesn't complain for serializer_class and filter_backends though
this is the decorator now:
```python
     @action(
        methods=['get'],
        detail=True,
        url_path='active-questionnaires',
        filter_backends=[DjangoFilterBackend],
        serializer_class=CompanyQuestionnaireListSerializer,
        filterset_class=CompanyQuestionnaireFilter
    )
```

**Comment by tfranzel** [comment]
ahh right. that is a safeguard that check if the class attribute is existing. it may help to either set ``filterset_class = None`` on the class or create a subclass with that attribute.

**Comment by NANASHI0X74** [comment]
I feel like I should have thought of that... Setting filterset_class to None on the class gets rid of the typeerror, but the generated spec doesn't contain the filters as query parameters like it does for class-based views
```yaml
  /companies/{id}/active-questionnaires/:              
    get:                                    
      operationId: companies_active_questionnaires_retrieve
      description: ''                                  
      parameters:             
      - in: path   
        name: id                                       
        schema:       
          type: integer
        description: A unique integer value identifying this company.
        required: true
      tags:     
      - companies
      security:   
      - tokenauth: []        
      - cookieAuth: []
      responses:                                         
        '200':           
          content:  
            application/json:
              schema:                 
                $ref: '#/components/schemas/CompanyList'
          description: ''
```
actually it looks like none of the overrides end up in the generated schema... This is the action decorator now:
```python
    @action(
        methods=['get'],
        detail=True,
        url_path='active-questionnaires',
        filter_backends=[DjangoFilterBackend],
        serializer_class=CompanyQuestionnaireListSerializer,
        filterset_class=CompanyQuestionnaireFilter,
        queryset=CompanyQuestionnaire.objects.all()
    )
```

**Comment by tfranzel** [comment]
well... ``serializer_class=CompanyQuestionnaireListSerializer,`` is probably this: `CompanyQuestionnaireListSerializer = serializers.ListSerializer(child=CompanyQuestionnaireSerializer()) ` which cannot work as this is not a class but an object.

```python
    @extend_schema(responses=CompanyQuestionnaireSerializer(many=True))
    @action(
        methods=['get'],
        detail=True,
        url_path='active-questionnaires',
        filter_backends=[DjangoFilterBackend],
        filterset_class=CompanyQuestionnaireFilter,
        queryset=CompanyQuestionnaire.objects.all()
    )
```

worked for me.

**Comment by NANASHI0X74** [comment]
actually, ```serializer_class=CompanyQuestionnaireListSerializer,``` is a class:
```class CompanyQuestionnaireListSerializer(serializers.ModelSerializer): #...```

But anyway, what I was hoping for is that the filterset_class override would result in the filterset_fields of that filter class ending up in the spec as query params, like they do for example for this class:
```python
class QuestionnaireViewSet(viewsets.ModelViewSet):
    permission_classes = (QuestionnairePermission,)
    filterset_class = QuestionnaireFilter
    def get_queryset(self):
         #...
    def get_serializer_class(self):
         #...
```
<details>
  <summary>resulting yaml</summary>
  
```yaml
  /questionnaires/:
    get:
      operationId: questionnaires_list
      description: ''
      parameters:
      - name: activate_by_default
        required: false
        in: query
        description: activate_by_default
        schema:
          type: string
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      - name: questionnaire_type
        required: false
        in: query
        description: questionnaire_type
        schema:
          type: string
      tags:
      - questionnaires
      security:
      - tokenauth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionnaireList'
          description: ''
```
</details>

**Comment by NANASHI0X74** [comment]
ok maybe I see another reason why that might not work... the class above also produces an endpoint in the scheme that retrieves a single questionnaire, and that doesn't contain the query params. Maybe specatacular assumes that the other endpoint is also supposed to only return one object... I just tried naively setting detail=False but that doesn't work either and also then the {id} in `/companies/{id}/active-questionnaires/` is lost 😅

**Comment by NANASHI0X74** [comment]
right, I finally figured it out 🤦🏻 so yeah, I had the extend_schema annotation, but forgot to specify `many=True`. With that it works. I feel pretty dumb 😅
Thanks for putting in the time to support users of your package, that's really nice of you :)
