### ISSUE TITLE
improve decimal handling 

### ISSUE THREAD

**Issue by tfranzel** [tfranzel/drf-spectacular#24]
decimals can be both string and number. utilize ``COERCE_DECIMAL_TO_STRING`` to detect the case

implement funtionality comparable to https://github.com/encode/django-rest-framework/commit/603aac7db10671dea1975ea3023b5488815aa1ca

**Comment by gujacob** [comment]
Hi,
I see this is closed for a long time, but i think there is still a small issue on this:

When using SerializerMethodField with TypeHiting, it generates Decimal fields as number, even with COERCE_DECIMAL_TO_STRING=True

```
class TestSerializer(serializers.Serializer):
    properties = serializers.SerializerMethodField()

    def get_properties(self, obj) -> List[Decimal]:
        return [Decimal(0), Decimal(1)]

```
And the generated schema:
```
Test{
properties*	[
readOnly: true
number($double)]
}
```

This is also happening with TypedDicts as the Type Hinting for the SerializerMethodField function.

Shouldn't it be handled the same way DecimalSerializer is handled, and the generated schema should be String?

Thanks

**Comment by tfranzel** [comment]
Hi,

I think this is the correct behavior. `COERCE_DECIMAL_TO_STRING` is a DRF setting and only applies to instances of `DecimalField`. The `SerializerMethodField` is unaffected by this.

I'm pretty certain your API will in fact return a JSON `number` and not a `string` if used like that. DRF's `JSONEncoder` will make it a `float`. You would need to do the string conversion yourself here (and use `-> List[str]`).

**Comment by gujacob** [comment]
Actually I have overridden drf Json encoder to coerce it to string and not
float, so every decimal in Jason fields of my api are coerced to string,
and I don't have to do it manuallyi ft is is the correct approach, I'll use
str as type hint, but this way I don't have the regex for numbers on it.

Thanks anyway

**Comment by tfranzel** [comment]
I see, but your change does not reflect the default behavior of DRF and so I suppose there is nothing to fix. spectacular cannot know what you change inside your `JSONEncoder`. 

>  but this way I don't have the regex for numbers on it.

yeah that is a tradeoff. If you are hard set on that detail your would need to subclass `AutoSchema` and override `_map_response_type_hint`.

**Comment by gujacob** [comment]
I'll have a look into this.

Thanks for the prompt replies.

And congratulations for the great job you've been doing!!

**Comment by gujacob** [comment]
Hi,

Sorry to bother you again with this, but while looking into override
_map_response_type_hint I bumped on another method that should be affected
by this  _resolve_typeddict.

Digging deeper, and as i have a custom JSONEncoder and all my Decimals are
being rendered as strings, if there was a way for me to override
 OPENAPI_TYPE_MAPPING
or get_openapi_type_mapping it would do the trick, but I could not find a
way to do this. Do you think it is possible?

Thanks again!!

**Comment by XF-FW** [comment]
Hey @gujacob . I found this thread while googling for a solution for a similar problem. Since I didn't find anything I sketched this field class, which I think has all the correct behaviors, including the correct generated schema:
```
class DecimalSerializerMethodField(s.DecimalField, s.SerializerMethodField):
    def __init__(
        self,
        max_digits: int | None,
        decimal_places: int | None,
        **kwargs: Any,
    ):
        try:
            method_name = kwargs.pop("method_name")
        except KeyError:
            method_name = None

        s.DecimalField.__init__(self, max_digits, decimal_places, **kwargs)
        s.SerializerMethodField.__init__(self, method_name=method_name, **kwargs)

    def to_representation(self, value: Any) -> Any:
        method_result = s.SerializerMethodField.to_representation(
            self, value  # type: ignore
        )
        decimal_result = s.DecimalField.to_representation(
            self, method_result  # type: ignore
        )

        return decimal_result
```

I've tried to fix the `type: ignore`, but I don't think it's 100% trivial. I think the stubs might require a small correction, by adding the type parameters to the `Field` [here](https://github.com/typeddjango/djangorestframework-stubs/blob/master/rest_framework-stubs/fields.pyi#L688). This is only relevant, if you, like me, have an unhealthy relationship with mypy :)  

Any updates / fixes to this snippet are appreciated, although it's working fine for my use-case.

Let me just finish, by apologizing to @tfranzel for putting this here, when this is not directly related to `drf-spectacular`.
