### ISSUE TITLE
Exclude endpoints from generated schema

### ISSUE THREAD

**Issue by yousef-soliman** [tfranzel/drf-spectacular#240]
Hello, 
i have 2 app in my Django project,  i am using the `include('apps.urls')` i want drf-spectacular to exclude schema of the specific app's endpoint 
an Example
```
path("api/v1/", include("v1_api.urls")),
path("api/v2/", include("v2_api.urls")),
```
i want to generate swagger for only `api/v2`
how can i do that  with drf-spectacular?
Thanks

**Comment by tfranzel** [comment]
hi, there are multiple ways to do this. ``SpectacularAPIView`` can be versioned itself **or** you can hard-code the version it is supposed to deliver like so:

https://github.com/tfranzel/drf-spectacular/blob/208429b7ace8c37a79e5e51bd8532dfaa8e0c853/tests/test_versioning.py#L187-L188

the tests (in the above file) show multiple ways of approaching versioning.
