### ISSUE TITLE
Using `@extend_schema` causes a custom `schema` implementation to be ignored

### ISSUE THREAD

**Issue by rvinzent** [tfranzel/drf-spectacular#241]
**Describe the bug**
Using `@extend_schema` causes a custom `schema` implementation to be ignored entirely. I would like to subclass `AutoSchema` to adjust/fix some other issues with the documentation, but using `@extend_schema` is still convenient to override certain properties in some cases. 

**To Reproduce**
```python
class CustomSchema(AutoSchema):
    def get_operation_id(self):
        # this is never called for the "post" method
        print(f"doing some custom thing for {self.method}")
        super().get_operation_id()

class MyViewSet(viewsets.ModelViewSet):
    http_allowed_methods = ["post", "path"]
    schema = CustomSchema()
    
    @extend_schema(parameters=[...some custom parameters on create only...])
    def create(self, request, **kwargs):
        ...
```
**Expected behavior**
I would expect `@extend_schema` to overwrite some properties, but continue to call methods on my custom `AutoSchema` subclass.

**Comment by tfranzel** [comment]
as far as i understand you, this is the expected an actual behavior.

`@extend_schema` makes use of DRF's `DEFAULT_SCHEMA_CLASS` (if nothing else is available).

https://github.com/tfranzel/drf-spectacular/blob/208429b7ace8c37a79e5e51bd8532dfaa8e0c853/drf_spectacular/utils.py#L174-L183

you can freely change things on your customized `AutoSchema` and it will be used, if not overridden by `extend_schema`. You just have to set `DEFAULT_SCHEMA_CLASS` to your customized class. that is how this is supposed to work. if not, we may have a bug.

**Comment by rvinzent** [comment]
> `@extend_schema` makes use of DRF's `DEFAULT_SCHEMA_CLASS` (if nothing else is available).

There is something else available. `CustomSchema` in this example. 

> you can freely change things on your customized AutoSchema and it will be used, if not overridden by extend_schema

yea, I think this is the bug. I change things on my `AutoSchema` and those overrides are ignored for view methods decorated with `extend_schema`. 

Note the distinction here is that decorating the viewset _class_ works perfectly fine, and using `extend_schema` will correctly use `CustomSchema` as the base class (line 176). This does not appear to be the case when a _method_ (line 178?) is decorated with `extend_schema`, or when the viewset is decorated with `extend_schema_view`.

**Comment by tfranzel** [comment]
thank you for the kind words. i would have asked for a reproduction to make it absolutely clear, but you already edited it in. thanks for that. this issue may also be related to #218.

as you probably noticed, the conceptual design of `extend_schema` and `AutoSchema` in general is quite simple: just a bunch of stacked derived `AutoSchema` classes. However, the realization of that design gets tricky at some points. I will investigate those 2 issues, but it might take me a moment to get around doing it. 

as a sidenote: i have not actually checked it, but if you can manage to bake your changes into a global `CustomSchema` (via `DEFAULT_SCHEMA_CLASS` and not set on the view class), it would most likely bypass the described bug. just as an idea for a intermediate solution.

**Comment by tfranzel** [comment]
this is an issue i forgot about. by using `@extend_schema` you kind of applied an accidental bugfix to it.

the root cause was that `CustomSchema` is (mostly) not available when `extend_schema` is applied to a view method. this is not entirely true for `extend_schema_view`, but it simulates what direct annotation would have done. so it comes back to the same problem. the outer `extend_schema` does some magic that fixes that issue.

the fix rearranges the class hierarchy at a later point in time to get the expected result (similar to above mentioned magic). please check if it works for you.

**Comment by rvinzent** [comment]
@tfranzel I pulled the latest master to test, but I've run into what looks like an unrelated issue with filter parameters.

This occurs on all of my `FilterSet` parameters that do not directly map to a model field.
```
....
  File "./env/src/drf-spectacular/drf_spectacular/openapi.py", line 186, in _get_parameters
    **dict_helper(self._get_filter_parameters()),
  File "./env/src/drf-spectacular/drf_spectacular/openapi.py", line 353, in _get_filter_parameters
    parameters += filter_extension.get_schema_operation_parameters(self)
  File "./env/src/drf-spectacular/drf_spectacular/contrib/django_filters.py", line 42, in get_schema_operation_parameters
    schema=auto_schema._map_model_field(model_field, direction=None),
  File "./env/src/drf-spectacular/drf_spectacular/openapi.py", line 373, in _map_model_field
    assert isinstance(model_field, models.Field)
AssertionError
```

At a glance it looks like it's expecting all the fields on my `FilterSet` class to be model fields, but I have a custom filter parameter that is not on the model, so 
- `model_field` is probably the `dummy_property` returned in `follow_field_source`; I would expect it to be unable to find a model field for this parameter
- naturally `dummy_property` is not an instance of `models.Field`

-----

After commenting out all of my `filterset_class`, I can confirm the fix worked! My custom `AutoSchema` classes are now used to generate schema when `@extend_schema_view`/`@extend_schema` on a view method is used!

**Comment by tfranzel** [comment]
filterset issue should be gone. could you test again and close? thanks

**Comment by rvinzent** [comment]
@tfranzel working, thanks!
