### ISSUE TITLE
how to exclude shown methods of ModelViewSet endpoint

### ISSUE THREAD

**Issue by warnabas** [tfranzel/drf-spectacular#242]
Hi!
I want GET method only to be shown, trying to figure it out in docs, but can't... examples are very few and simple.

**Comment by tfranzel** [comment]
Hi! this is not nearly enough information to help you out. Are you talking about `ApiView`, `ViewSet`, auto-detection, or `extend_schema`?

**Comment by warnabas** [comment]
Hi, sry, I have ModelViewSet, but all methods are not allowed except next:
"get" in main endpoint
and there is extra action inside this view with POST and DELETE methods.

**Comment by tfranzel** [comment]
so it sounds strange to have a `ModelViewSet` and not showing all the supported methods in the schema. if nobody uses them you might want to use `GenericViewset` with list and retrieve mixins.

however you can do this:

```python

@extend_schema_view(
    delete=extend_schema(exclude=True),
    create=extend_schema(exclude=True),
    action_name=extend_schema(exclude=True),
)
class yourmodelviewset(ModelViewSet):
   ....
```

**Comment by warnabas** [comment]
thanks a lot. <br>
yeah, I know, it sounds strange. it was used because of logic inside. there is action inside which use post and delete, so that's why used ModelViewSet.
smth like this
```api/basic/id/extra_action```

**Comment by warnabas** [comment]
btw, one small thing, `delete` is `destroy`

**Comment by tfranzel** [comment]
@warnabas then i guess it made sense.  yeah typo because i typed it from memory.

i suppose this issue is solved then. i'll close it but feel free to come back to this if something is broken.
