### ISSUE TITLE
[feature request] ViewSet level tags definition

### ISSUE THREAD

**Issue by wonderbeyond** [tfranzel/drf-spectacular#247]
By using [extend_schema](https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.extend_schema) decorator, We can only define tags for only one endpoint a time. Can we introduce a feature that allow us to define ViewSet-level tags, maybe like below:

```python
class XViewset(mixins.ListModelMixin, mixins.CreateModelMixin, viewsets.GenericViewSet):
    swagger_tags = ["X"]
    ...
```

**Comment by tfranzel** [comment]
that feature does already exist:

```python
@extend_schema(tags=["X"])
class XViewset(mixins.ListModelMixin, mixins.CreateModelMixin, viewsets.GenericViewSet):
     ....
```

**Comment by wonderbeyond** [comment]
Oh sorry, it really works.
