### ISSUE TITLE
setting queryset in @action decorator may break self.get_object

### ISSUE THREAD

**Issue by NANASHI0X74** [tfranzel/drf-spectacular#248]
So, I've been slowly getting the hang of spectacular and now got to the point where the code that gets generated in the end works for my purposes and if not I understand how to use the customization workflow to correct the generated schema and with it, the code. 
However, now that we've started reviewing the code for merging into our master branch in the backend, we've noticed a problem:
We have code in some places that frequently uses `self.get_object()` and that seems to break when I set the queryset via the `@action` decorator - an exception is thrown at runtime when the endpoint processes a request. But if I don't set it the scheme generation runs into an exception.

An example of where this happens - we have code that looks something like the following:
```python
class (AModelViewset):
    queryset = AModel.objects.all()

    @extend_schema(responses=ModelBListSerializer(many=True))
    @action(
        methods=['get'],
        detail=True,
        url_path='blah',
        queryset=BModel.objects.all(), #this breaks the endpoint
        filterset_class=BModelFilter,
        filter_backends=[DjangoFilterBackend]
    )
    def related_bs(self, request, pk):
        a_object = self.get_object()
        b_objects_qs = a_object.b_objects.filter(...)
        b_objects = BModelFilter(request.GET, queryset=b_objects_qs).qs
        serializer = ModelBListSerializer(b_objects, many=True)
        return Response(serializer.data)
```

If we run django with that and use this endpoint, we get an exception like this:
```AttributeError at /amodels/1/blah/
'ModelB' object has no attribute 'b_objects'
```

On the other hand if I don't set the queryset in the action decorator, I get an exception when I run manage.py spectacular:
```
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 50, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 188, in get_schema
    paths=self.parse(request, public),
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 165, in parse
    operation = view.schema.get_operation(path, path_regex, method, self.registry)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/utils.py", line 158, in get_operation
    return super().get_operation(path, path_regex, method, registry)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 59, in get_operation
    parameters = self._get_parameters()
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 176, in _get_parameters
    **dict_helper(self._get_filter_parameters()),
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 339, in _get_filter_parameters
    parameters += filter_backend().get_schema_operation_parameters(self.view)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/contrib/django_filters.py", line 17, in get_schema_operation_parameters
    filterset_class = self.get_filterset_class(view, model.objects.none())
  File "/usr/local/lib/python3.8/site-packages/django_filters/rest_framework/backends.py", line 64, in get_filterset_class
    assert issubclass(queryset.model, filterset_model), \
AssertionError: FilterSet model <class 'bapp.models.BModel'> does not match queryset model <class 'amodel.models.AModel''>
```

**Comment by NANASHI0X74** [comment]
I accidentally submitted the issue before I was done writing it down and investigating 😅 Now that I look at the exception thrown during scheme generation I see that the issue arises when using with filterset_class in the action decorator (used to let the scheme generation infer url query parameters in this case)

**Comment by NANASHI0X74** [comment]
I think we will switch to the objects.get via pk...
Would it make sense to add an override for queryset/filterset to the extend_schema decorator though or does that sound stupid? 😄

**Comment by tfranzel** [comment]
hey @NANASHI0X74, yes that is probably the limit of what we can do. what you are doing is "technically" correct. it is interesting that `queryset=BModel.objects.all()` does not override the `AModel` queryset even though this is how stuff is overridden generally in DRF. i would have to dig deep into why this does not work, but on the other hand this is hacky and unsupported magic anyway. 

the simplest solution would be to just annotate the parameters **manually** with `@extend_schema(parameters=[OpenApiParameter(...),...])`. If you use this feature a lot maybe you can recycle the contents of `DjangoFilterExtension` directly (with some minor modifications), which would free you of having to add the hacky stuff.

i hope this helps you because i currently lack the time for implementing this.

**Comment by NANASHI0X74** [comment]
> it is interesting that `queryset=BModel.objects.all()` does not override the `AModel` queryset even though this is how stuff is overridden generally in DRF. 
I think you might have misread what I was saying here 😅 setting the queryset does work... which seems to be a problem in itself because it breaks this self.get_object() method, so we have to instead use `AModel.objects.get(pk=pk)`. Which is only a minor inconvenience, but it still feels a bit awkward that we have to modify the code that actually runs when it serves a request.
The assertionerror that says the filterset doesn't match the queryset gets thrown on running spectacular _if I don't set the queryset_, which makes sense of course.
So then later I thought it might be a possibility to give the option of setting the queryset and/or filterset in the extend_schema decoration instead of the action one, but I'd understand if you'd say that's a dumb idea and wouldn't be worth the effort 😅
Thinking about it now maybe it would suffice to catch the assertionerror and ignore it 🤔 but then I imagine that wouldn't give the djangofilterbackend the chance to infer query params.

After some thinking about this though, I think getting the object via pk seems preferable anyway because it more explicitly states what's happening- get_object looks a bit like magic really. But I'm not very involved with our backend code and have rather little experience with drf and django.
I feel a bit awkward when I'm asking for help here because of that to be honest 😅
Thanks a lot for this piece of software though. It's amazing how well it does work 😁👍

**Comment by tfranzel** [comment]
thanks! i think i partially misunderstood, but now i think i get it. however this is an edge case at the end of the day and i can't really see anything we could reasonably change in the core/contrib mechanics to cater to that. however, i'm open to suggestions.

i hope you'll figure it out. i'll close this for now but feel free to address this issue again if you like.
