### ISSUE TITLE
Models with custom PKs not called `id` throw errors on schema generation.

### ISSUE THREAD

**Issue by keyz182** [tfranzel/drf-spectacular#25]
When grabbing a models "ID", should probably be using `model.pk` - https://docs.djangoproject.com/en/dev/ref/models/instances/#the-pk-property.
A models `id` field is accessable through `.pk`, as the models PK is always accessible there. When dealing with custom PKs, this causes drf-spectacular to fall over a `AttributeError: type object 'MethodCall' has no attribute 'id'` error. 

For example, I have a model as follows:
```
class MethodCall(models.Model):
    transaction = models.OneToOneField('Transaction', primary_key=True, on_delete=models.CASCADE)
    ...
```

As the `transaction` field has `primary_key=True`, Django doesn't generate a `.id` field. However `transaction` is still accessable via `.pk`.

This is where it's an issue for me:
- https://github.com/tfranzel/drf-spectacular/blob/bca26d3a731b0b16543d854a118aaa6a6d11bdc5/drf_spectacular/openapi.py#L359

It _may_ also be an issue here:
- https://github.com/tfranzel/drf-spectacular/blob/bca26d3a731b0b16543d854a118aaa6a6d11bdc5/drf_spectacular/openapi.py#L399

**Comment by tfranzel** [comment]
good catch! i'll have a look at it.

**Comment by tfranzel** [comment]
@keyz182 i removed all references to id. it took a moment to get it right as `pk` is behaving slightly different from `id`, but on most cases there was a more elegant solution which i didn't see before.

can you confirm the issue is resolved?

**Comment by keyz182** [comment]
@tfranzel Sorry - not been in a position to test the changes as I've had to work on other things. Thank you for the fix though, I'll let you know if/when I get a chance to test.

**Comment by tfranzel** [comment]
no problem, just trying to clean up the issue page. feel free to reopen if the fix is not sufficient.
