### ISSUE TITLE
Question: How to separate apps?

### ISSUE THREAD

**Issue by sommelon** [tfranzel/drf-spectacular#254]
Hey,

I've got multiple apps: `users` and `dashboard` which contains more apps, such as `common`.
`urls.py` in the project root folder contains this
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('apps.core.users.urls', namespace='users')),
    path('api/', include('apps.core.dashboard.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
```

The Swagger view displays this:

![image](https://user-images.githubusercontent.com/57922071/104110469-4f31a800-52d8-11eb-93b2-f91d368d2fbb.png)

As you can see `api` is the only main collapsable element and it contains all the endpoints.
Is there a way I can separate the endpoints into multiple collapsable elements, so it looks something like this?

![image](https://user-images.githubusercontent.com/57922071/104110763-1941f300-52db-11eb-886d-7f9fc637e1e2.png)

It doesn't have to be exactly like that, I just want it to be separated.

Thanks in advance.

**Comment by tfranzel** [comment]
with separation you probably mean grouping by tags.

https://drf-spectacular.readthedocs.io/en/latest/settings.html

settings `SPECTACULAR_SETTINGS={'SCHEMA_PATH_PREFIX': r'/api/',} would achieve this. generally the default tag is the first segment of the `SCHEMA_PATH_PREFIX` stripped url (e.g. permission_group, common, etc). for more intricate tagging you would need to override `AutoSchema.get_tags()`.

**Comment by tfranzel** [comment]
how to structure the yaml/tags to have **nested** collapsable segments i don't know. never had that case before.

**Comment by sommelon** [comment]
Thank you for the quick response. The nested segments would be nice, but this will surely do. Thanks again.
