### ISSUE TITLE
[Feature] Allow normal APIView has filter parameters.

### ISSUE THREAD

**Issue by wonderbeyond** [tfranzel/drf-spectacular#255]
I have a normal APIView (i.e not GenericAPIView), it does not respond a list of objects, but its behavior is affected by some url query parameters.

```python
class TaskCostsView(APIView):
    filterset_class = TaskCostsFilter
    filter_backends = [DjangoFilterBackend]
    serializer_class = TaskCostsResponse

    @swagger_auto_schema(
        operation_id="task-costs",
        responses={status.HTTP_200_OK: TaskCostsResponse}
    )
    def get(self, request):
        """Get tasks' coretime in total or grouped into buckets (by task type)."""
        queryset = Task.objects.all()
        filterset = self.filterset_class(
            data=request.query_params,
            queryset=queryset,
            request=request,
        )

        if not filterset.is_valid():
            raise translate_validation(filterset.errors)

        qs = filterset.qs
        groupby_field = filterset.data.get('group_by')

        resp_data = {}

        if groupby_field:
            qs = qs.values(groupby_field)
            bucketed_coretime = qs.annotate(
                coretime=Sum('coretime')
            ).order_by()
            resp_data["buckets"] = bucketed_coretime
        else:
            total_coretime = qs.aggregate(total=Sum('coretime'))
            resp_data["coretime"] = total_coretime["total"]

        return Response(resp_data)
```

I have tried using a FilterSet to define the view's parameters, and it works well. drf-yasg can also generate the expected OpenAPI parameters with some tweak.

However, It stopped working with drf-spectacular. By inspecting the code, I found the relevant part:

https://github.com/tfranzel/drf-spectacular/blob/6febe8ff92d015cec6d552c2cc95a441a6eccac4/drf_spectacular/openapi.py#L343-L356

Is my use case reasonable?

**Comment by wonderbeyond** [comment]
I've made a workaround like this:

```python
class TaskCostsView(APIView):
    swagger_tags = ["Task costs"]
    filterset_class = TaskCostsFilter
    filter_backends = [DjangoFilterBackend]
    serializer_class = TaskCostsResponse
    # See https://github.com/tfranzel/drf-spectacular/issues
    action = 'list'
    ...
```

**Comment by tfranzel** [comment]
@wonderbeyond i get you need but this is way outside the bounds of feasible introspection.

there is one more thing that is possible. override list detection by using `extend_schema_serializer`
```python
    @swagger_auto_schema(
        operation_id="task-costs",
        responses={status.HTTP_200_OK: extend_schema_serializer(many=False)(TaskCostsResponse)}
    )
```
this is as far as i can give support on this issue.

**Comment by henribru** [comment]
Why is it necessary to skip filter parameters for non-list views? It seems like this would simply work if `if not self._is_list_view(): return []` was removed, but I assume there's some reason it was added in the first place.
