### ISSUE TITLE
shema generation breaking with filterset_fields

### ISSUE THREAD

**Issue by RoganEndresDenstu** [tfranzel/drf-spectacular#256]
**Describe the bug**
Hi there, hope I am not missing something blatantly obvious, 

I am getting the following error, when attempting to run

```
./manage.py spectacular --file schema.yml
```
or accessing /schema endpoint 

Error:
```
python3.7/site-packages/django_filters/filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: client, tenant_id, subtenant_id, data_stream_id
```

**Update**
Workaround:
If I remove the filterset_fields entirely, the schema renders perfectly. however, it seems that the filterset_fields are actually referencing fields within another Parent model referenced by ForeignKey that are not specified directly as fields on the model class. 

example model: 
```
class DataSteam(models.Model):
    """Class for DataSteam Model."""
    a = models.CharField(max_length=200)
    b = models.CharField(max_length=200)
    c = models.CharField(max_length=200)

class subModel(models.Parent):
    """Class for storing linked datastream records."""
    ds = models.ForeignKey(DataStream, on_delete=models.CASCADE) 

```

**To Reproduce**
My project has the following specs: 
```
Python                3.7.2
Django                3.0.2    
django-filter         2.2.0    
django-rest-framework 0.1.0    
djangorestframework   3.12.1   
drf-spectacular       0.12.0 
```

Viewset example:
```
class DataStreamViewSet(viewsets.ModelViewSet):
    """Standard ViewSet for the DataStream Model."""
    queryset = DataStream.objects.all()
    serializer_class = DataStreamSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['a', 'b', 'c',]
```
Serializer example:
```
class DataStreamSerializer(serializers.ModelSerializer):
    """Class to validate an uploaded DataStream."""

    class Meta:
        """Nested Meta Class."""

        model = DataStream
        fields = '__all__'
```
urls.py
```
...
path("schema/", SpectacularAPIView.as_view(), name="schema"),
path(
        "docs/",
        SpectacularSwaggerView.as_view(
            template_name="swagger-ui.html", url_name="schema"
        ),
        name="swagger-ui",
    ),
```

**Expected behavior**
Possibly that when generating the schema, `drf-spectacular` takes into account the DjangoFilterBackend filterset_fields which are specified?

**Comment by tfranzel** [comment]
> TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: client, tenant_id, subtenant_id, data_stream_id

1: from the look of the error message, i would assume the the filterset construction is faulty. have you tried querying that filter and it works as expected?

2: the reproduction had some error and the sub model was unused. also, the way it was did not produce an error for me. adding `related_name` and `ds` to `filterset_fields` worked also.
```python
def test_foo(no_warnings):
    class DataStream(models.Model):
        """Class for DataSteam Model."""
        a = models.CharField(max_length=200)
        b = models.CharField(max_length=200)
        c = models.CharField(max_length=200)

    class SubModel(models.Model):
        """Class for storing linked datastream records."""
        ds = models.ForeignKey(DataStream, on_delete=models.CASCADE, related_name='ds')

    class DataStreamSerializer(serializers.ModelSerializer):
        """Class to validate an uploaded DataStream."""

        class Meta:
            """Nested Meta Class."""

            model = DataStream
            fields = '__all__'

    class DataStreamViewSet(viewsets.ModelViewSet):
        """Standard ViewSet for the DataStream Model."""
        queryset = DataStream.objects.all()
        serializer_class = DataStreamSerializer
        filter_backends = [DjangoFilterBackend]
        filterset_fields = ['a', 'b', 'c', 'ds']

    schema = generate_schema('x', DataStreamViewSet)
```

3. fyi: there are some improvements on master also, but i checked against `0.12.0` and it worked.

**Comment by RoganEndresDenstu** [comment]
Hi @tfranzel , indeed, I think the issue was with the original filterset construction. 

It seems we had some additional middleware that was applying the filtering for those fields, and not the filterset itself, so I was under the impression the filterset fields were working as expected. But alas, I was wrong. :D 

Thanks for the speedy feedback. It is greatly appreciated. Really loving `drf-spectacular`, nice, neat, and nifty to say the least!
