### ISSUE TITLE
Request: Add support for drf-action serializer in generated swagger docs

### ISSUE THREAD

**Issue by alichass** [tfranzel/drf-spectacular#261]
Hi, to start with - great package. 

I was wondering if it would be possible to add support for https://github.com/gregschmit/drf-action-serializer and similar self implemented serializers (changes depending on GET/POST/DELETE) for the generated swagger schemas. 

Using this package's implementation of the browsable api already seems to support this so thanks for that :+1:

**Comment by alichass** [comment]
my bad seems to have been fixed in an update

**Comment by tfranzel** [comment]
Hi @alichass , thank you!

for these cases we have extensions: 
https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-serializer-magic-with-openapiserializerextension
this is also used here: 
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/contrib/rest_polymorphic.py

we have to policy to only add extensions to core if they are at least semi-popular, which seems not be the case yet. we have a blueprint section for those cases: https://drf-spectacular.readthedocs.io/en/latest/blueprints.html. feel free to contribute there.

> Using this package's implementation of the browsable api already seems to support this so thanks for that

not quite sure what you are referring to here.

**Comment by tfranzel** [comment]
looks resolved to me. closing for now
