### ISSUE TITLE
usage of django_filters.filters.OrderingFilter raises a Warning

### ISSUE THREAD

**Issue by ticosax** [tfranzel/drf-spectacular#263]
**Describe the bug**

Usage of `django_filters.filters.OrderingFilter` warns.

**To Reproduce**

For given filterset definition.

```python
class BaseModelFilterSet(FilterSet):
    o = filters.OrderingFilter(fields=(('id', 'id'),), field_labels={'id': 'ID'}))
```

```
python manage.py spectacular --fail-or-warn
```
exit with code 1

```
Warning #11: could not resolve field on model <class 'xxxx.xxxx.XxxxxXxx'> with path "o". this is likely a custom field that does some unknown magic. maybe consider annotating the field/property? defaulting to "string". (Exception: XxxxxXxx has no field named 'o')
```

**Expected behavior**
`django_filters.filters.OrderingFilter` usage shouldn't warn.

**Comment by tfranzel** [comment]
i see... that library is a rabbit hole :smile:, the fix is easy though. i'll try and see if there are more cases missing.

**Comment by ticosax** [comment]
I confirm it is Fixed ! :tada: 
Thanks a lot, that's a great library you made here.

**Comment by tfranzel** [comment]
awesome. thank you very much!
