### ISSUE TITLE
Issue: Incorrect schema generation for custom action with detail=false

### ISSUE THREAD

**Issue by christiaan-dockbite** [tfranzel/drf-spectacular#268]
**Describe the bug**
A function in a viewset decorated with `@action(detail=False)` generates a schema as if it were `@action(detail=True)`. Pagination parameters and filter parameters are not included.

**To Reproduce**
*Versions:*
-django: 3.1.3
-djangorestframework: 3.12.1
-django-filter: 2.4.0
-drf-spectacular: 0.11.1

*Model:*
```Python
class Infections(models.Model):
  date_reported = models.DateTimeField()
  municipality_code = models.CharField(max_length=6, null=True, blank=True)
  municipality_name = models.CharField(max_length=100, null=True, blank=True)
  province = models.CharField(max_length=30)
  total_reported = models.IntegerField()
  new_since_previous = models.IntegerField()
  hospital_admissions = models.IntegerField()
  deceased = models.IntegerField()
  now_contagious = models.IntegerField()
```

*Serializer:*
``` Python
class InfectionsSerializer(serializers.ModelSerializer):
	class Meta:
		model = Infections
		fields = '__all__'
```

*Filter:*
``` Python
class InfectionsFilter(FilterSet):
	class Meta:
		model = Infections
		fields = {
			'date_reported': ['lte', 'gte']
			}
```

*Viewset:*
``` Python
class InfectionsViewSet(viewsets.ModelViewSet):
	"""
	API endpoint that allows infections to be viewed or edited
	"""
	queryset = Infections.objects.all().order_by('id')
	serializer_class = InfectionsSerializer
	filter_class = InfectionsFilter
	
	def get_queryset(self):
		queryset = super().get_queryset()
		
		if self.action == 'list_last':
			latest_dates = Infections.objects.values('municipality_code').annotate(date_reported=Max('date_reported'))
			filter = Q()
			for item in latest_dates:
				filter |= Q(**item)
			
			queryset = queryset.filter(filter)
		
		return queryset
	
	@action(detail=False)
	def list_last (self, request, *args, **kwargs):
		return self.list(request, *args, **kwargs)
```
The list_last method lists the latest infections for each municipality.

*Settings:*
``` Python
REST_FRAMEWORK = {
	'DEFAULT_SCHEMA_CLASS'          : 'drf_spectacular.openapi.AutoSchema',
	'DEFAULT_PERMISSION_CLASSES'    : ('rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',),
	'DEFAULT_PAGINATION_CLASS'      : '<app name>.pagination.StandardModelPagination',
	'DEFAULT_FILTER_BACKENDS'       : ['django_filters.rest_framework.DjangoFilterBackend', ],
```
(The app name was removed for privacy)

*Generated schema:*
![schema_wrong](https://user-images.githubusercontent.com/70575686/105337007-367b9900-5bda-11eb-8984-6b4c2fd3af8c.png)

**Expected behavior**
A schema similar to the list view, including filter and pagination parameters:
![schema_right](https://user-images.githubusercontent.com/70575686/105337888-34fea080-5bdb-11eb-9991-78d1c0aad41f.png)

**Comment by tfranzel** [comment]
hi @christiaan-dockbite , this is actually not a bug and has come up before. `@action` is undefined in terms of list/retrieve. `detail` true only says where the endpoint is attached, not what it returns. you will have to use `@extend_schema(response=XSerializer(many=True))` to signal that information. see other issue for more information:

https://github.com/tfranzel/drf-spectacular/issues/190#issuecomment-722011215

**Comment by christiaan-dockbite** [comment]
Thank you for your fast reaction! After reading the comment I got the point. Is it also noted in the documentation somewhere?

**Comment by tfranzel** [comment]
now there is :smile: 

https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-m-using-action-detail-false-but-the-response-schema-is-not-a-list
