### ISSUE TITLE
Response Description

### ISSUE THREAD

**Issue by eilst** [tfranzel/drf-spectacular#272]
https://github.com/tfranzel/drf-spectacular/blob/f23de89dd94fc3238650334725aa2bcd1ace73e2/drf_spectacular/openapi.py#L1006

Can we still add a custom description for a Response?
I tried and it is displayed in the schema of the response and not in the main Response description.

**Comment by tfranzel** [comment]
the key question here is: how and where should it be added? it isn't clear to me. 

we use `description` for operations, components and some other places. that specific `description` is on a status code level. i can see that this may be useful for error description, but that is supposed to be solved with a different feature in the future.

**Comment by tfranzel** [comment]
the key question here is: how and where should it be added? it isn't clear to me. 

we use `description` for operations, components and some other places. that specific `description` is on a status code level. i can see that this may be useful for error description, but that is supposed to be solved with a different feature in the future.

**Comment by eilst** [comment]
I found that is is possible  to add an example (examples= [OpenApiExample...) with a description and linked it to a specific status_codes. So that was enough for me.

For a simple error description it can be helpful like you said to be able to do it.

**Comment by tfranzel** [comment]
sounds good! i'll close this because you found a way, and we may more structured approach once the error feature is implemented (#101)
