### ISSUE TITLE
Allow Swagger UI pre-authorization

### ISSUE THREAD

**Issue by nlarusstone** [tfranzel/drf-spectacular#278]
When developing locally on an API that has token or API key based authentication, I would like to not have to fill in my API Key every time I use Swagger UI.

Swagger provides this using the preauthorizeApiKey (I believe), but it doesn't seem possible to do locally:
https://stackoverflow.com/questions/45199989/how-do-i-automatically-authorize-all-endpoints-with-swagger-ui/50181701#50181701

**Comment by tfranzel** [comment]
i was not aware of this feature. we currently do not support call-back setttings for swagger ui, just simple settings. 

https://drf-spectacular.readthedocs.io/en/latest/settings.html#example-swaggerui-settings

however, there is the SwaggerUI setting `persistAuthorization: true` which will remember the auth on reload. so you only need to do it once, which is probably close enough for you.

**Comment by tfranzel** [comment]
sry... i mistyped the issue number. this is unrelated

**Comment by nlarusstone** [comment]
Yup, `persistAuthorization` works for my usecase, thanks!

**Comment by callumgare** [comment]
Another option for anyone who comes across this issue is automatically configuring the session cookie authentication if a user has logged in: https://github.com/tfranzel/drf-spectacular/issues/1099#issuecomment-1920345459
