### ISSUE TITLE
Request: Ability to disable sorting of parameters

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#281]
Currently in `AutoSchema` class in `openapi.py#38` in `_get_parameters#176` method as a last step parameters for a endpoint are sorted by `name` 
```py 
... 
return sorted(parameters.values(), key=lambda p: p['name'])
```

This requires us to override this method just to replace it with 
```py
...
return list(parameters.values())
```

because we would like to keep our parameters to be grouped **logically** together as we defined them, as one would do for perhaps function parameters.

Could this perhaps be a thing that is toggleable in settings?

**Comment by tfranzel** [comment]
i can see how this makes sense. will do

**Comment by intgr** [comment]
Thank you for implementing this feature so quickly. I can confirm that `SORT_OPERATION_PARAMETERS` works for me.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
