### ISSUE TITLE
Allow us to specify response headers

### ISSUE THREAD

**Issue by sergei-maertens** [tfranzel/drf-spectacular#283]
I'm on `drf-spectacular==0.12.0` - and looking at the code it seems it's not currently possible to document [response headers](https://swagger.io/docs/specification/describing-responses/#headers)

It's also not listed in the 0.13.x release notes, so I don't think it exists :-)

Is this planned? If not, I could probably make a PR.

**Comment by tfranzel** [comment]
@sergei-maertens, nobody has ever asked for it and i didn't need it yet but it certainly makes sense to support it. 

i imagine folding those parameters into `@extend_schema(parameters=[...])`. I would recycle `OpenApiParameter` as it already provides everything that is needed (except for a `response` parameter with default `False`).  we handled this in a similar fashion in `OpenApiExample`. 

very doable with a small set of changes. feel free to do a PR, we would certainly include this feature. :+1:
