### ISSUE TITLE
Union typing on model property

### ISSUE THREAD

**Issue by LukasBerka** [tfranzel/drf-spectacular#284]
**Describe the bug**
The _resolve_type_hint_ method inside _plumbing.py_ does not recognize a hint in form:

```py
def my_model_method(self) -> Union[None, OtherType]:
    pass
```

because the _resolve_type_hint_ checks specifically for `isinstance(None, args[1])`. 
_on line 834._

so the same method with switched types in Union does work as expected

```py
def my_model_method(self) -> Union[OtherType, None]:
    pass
```

Using 
Python 3.9
drf-spectacular == 0.13.1
djangorestframework == 3.12.2

**Expected behavior**
I would assume that the order of types in Union does not matter as Python documentation says. 
https://docs.python.org/3/library/typing.html#typing.Union

**Comment by tfranzel** [comment]
certainly a bug or rather incomplete parsing. the rationale behind it was that this gets automatically translated `Optional[OtherType] -> Union[OtherType, None]`.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
