### ISSUE TITLE
Request: Template 'title' should be configurable

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#288]
Please make `title` in templates (swagger_ui.html, redoc.html) configurable

**Usecase**
We have 2 APIDOC endpoints - `public` and `internal` - and we would like them to have different `title`s

Currently I have overridden the templates to accept it as a token and provide the token in the `get` method in corresponding view ( `SpectacularSwaggerView` or `SpectacularRedocView` )

This perhaps could be also provided as a override in url mapping
```
    path("", SpectacularSwaggerView.as_view(title="Public APIDOC"), name="apidoc"),
    path("internal", SpectacularSwaggerView.as_view(title="Not so public APIDOC"), name="apidoc-internal"),
```

I could make a PR for this if needed

**Comment by tfranzel** [comment]
Hey @HansAarneLiblik, i'm hesitant to break `get_schema` with an additional argument. this request comes up too rarely to justify it. currently i would prefer to leave it as is, but i'm still open to it if more people would like to have it.

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks may have been an easier solution.

**Comment by hugokernel** [comment]
Hi, I have exactly the same need: 2 APIs, one public and one private and it would have been interesting to be able to define a title based on the defined configuration (just like `django-yasg` I migrated from recently allowed us to do).

**Comment by HansAarneLiblik** [comment]
We ended up using a custom hook to change the returned schema based on the `instanceof` of `generator`
