### ISSUE TITLE
warnings when using django-restql NestedField

### ISSUE THREAD

**Issue by sommelon** [tfranzel/drf-spectacular#289]
Hello,
I mentioned previously that I'm using [django-restql](https://github.com/yezyilomo/django-restql) for nested serializers. I have to define my serializers like this
```
class BankAccountSerializer(DynamicFieldsMixin, NestedModelSerializer):
    bank_address = NestedField(AddressSerializer, required=False, allow_null=True, accept_pk_only=True)
```
The problem is, that the schema gets generated incorrectly. It repeats the same nested serializer for every `NestedField` there is.
```
{
  "id": 0,
  "contact_info": {
    "id": 0,
    "street": "string",
    "city": "string",
    "postcode": "string",
    "country": "AF",
    "state": "string",
    "address_line": "string",
    "latitude": "string",
    "longitude": "string"
  },
  "business_detail": {
    "id": 0,
    "street": "string",
    "city": "string",
    "postcode": "string",
    "country": "AF",
    "state": "string",
    "address_line": "string",
    "latitude": "string",
    "longitude": "string"
  },
...
}
```
In the example above, my `AddressSerializer` is replacing the `ContactInfoSerializer` and `BusinessDetailSerializer`. I think it's because the `AddressSerializer` is used in my first view in the project.
To fix this, I added `ref_name` to each serializer. It works, but I get a lot of warnings.
```
Warning #34: Encountered 2 components with identical names "PermissionGroup" and different classes <class 'apps.core.users.serializers.PermissionGroupSerializer'> and <class 'django_restql.fields.NestedFieldWraper.<locals>.NestedSerializer'>. This will very likely result in an incorrect schema. Try renaming one.
```
Their [implementation](https://github.com/yezyilomo/django-restql/blob/2b83b1a5200065852deaa0a9ad2bc3cc75013586/django_restql/fields.py#L352) uses a wrapper that returns a serializer.

Is there a way I can get rid of the warnings and, possibly, the need to define `ref_name` on every serializer?

**Comment by tfranzel** [comment]
hi @sommelon, most warning don't have an impact on the schema. they are just supposed to signal that something is fishy.

we do not support `django-restql` at this moment. nobody tells you not to use `drf-spectacular`, but ther are no guarantees and your mileage may vary. the highly dynamic nature may prove tricky to properly map. it may be possible to get quite far with writing [OpenApiSerializerFieldExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-field-output-with-openapiserializerfieldextension) and OpenApiSerializerExtension. we did something similar with `django-polymorphic`. currently i don't have the time to implement this (or even try to). feel free to upstream this though, if you attempt to do it.

**Comment by sommelon** [comment]
The problem I have with the warnings is that it's hard to see if something new is being reported (errors or a different kind of warning).

I will try to fix it using an extension, thanks.

**Comment by sommelon** [comment]
I tried SerializerField and Serializer extensions, but couldn't get them to work.
Instead I overrode `_get_serializer_name()` in my custom schema. Probably not the best solution, but it will do it for me.
```
    def _get_serializer_name(self, serializer, direction):
        name = super()._get_serializer_name(serializer, direction)
        if serializer.__class__.__name__ == 'NestedSerializer':
            name += 'Nested' + str(randint(1,99999))
        return name
```

**Comment by sommelon** [comment]
I ended up monkey-patching the `drf_spectacular.plumbing.warn` name in the projects `__init__.py`.
```py
import drf_spectacular.plumbing
import drf_spectacular.drainage

def __suppressed_warn(msg):
    if 'components with identical' in msg and '<locals>.Nested' in msg:
        return
    drf_spectacular.drainage.warn(msg)

drf_spectacular.plumbing.warn = __suppressed_warn
```
