### ISSUE TITLE
Get the PK of a newly created object instance

### ISSUE THREAD

**Issue by frague59** [tfranzel/drf-spectacular#292]
**Describe the bug**

I cannot get the PK of a created instance

**To Reproduce**

On server side, I use spectacular with DRF - The schema is generated and I can build my client with the java version of `openapi-generator-cli`, to a python package. This package is used from another project, which needs to create some `PrintProject` instances... (This works fine)

I've used the examples provided in the generated docs. I've to create an instance of `Project` object

```python
# serializer: 
class PrintProjectCreateSerializer(serializers.ModelSerializer):
    pk = serializers.IntegerField(  # Or not ?
        read_only=True,
    )
    class Meta:
        model = models.PrintProject
        fields = (
            "pk",  # or not ? 
            "title",
            "description",
            "hierarchy",
            "validator",
            "due_at",
        )

# Create View 
class PrintProjectCreateAPIView(generics.CreateAPIView):
    queryset = models.PrintProject.objects.all()
    serializer_class = PrintProjectCreateSerializer
```

**Expected behavior**
I need to create some other model instances to the `PrintProject`, I need the pk of the `PrintProject` object. 
The other objects have a `print_project` foreign key bound to the `PrintProject` model.

If I add the pk field into the serializer, it is needed to create the `PrintProject` instance - which is not an option. If I do not add it, I cannot get the `pk` from the `PrintProject` instance.

I''ve tryed to use the `@extend_schema`, adding both request and responses, using alternative serializers, bit it does not work...

Thanks for your help!

**Comment by tfranzel** [comment]
this is a common and solved problem with the code generators. the docs specifically address this

https://drf-spectacular.readthedocs.io/en/latest/client_generation.html#component-issues

**Comment by frague59** [comment]
Thanks, I'll try this tomorrow...

**Comment by frague59** [comment]
It works !
