### ISSUE TITLE
Default response doesn't change after adding extend_schema

### ISSUE THREAD

**Issue by amitkbiswas01** [tfranzel/drf-spectacular#293]
**settings.py**
```python
...
REST_FRAMEWORK = {
    ...
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
...
SPECTACULAR_SETTINGS = {
    "TITLE": "Mutual Fund API",
    "LICENSE": {"name": "MIT"},
    "VERSION": "0.0.0",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "SWAGGER_UI_DIST": "//unpkg.com/swagger-ui-dist@3.35.1",
}
```

**urls.py**
```
path("schema/", SpectacularAPIView.as_view(), name="schema"),
path(
        "api/v1/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
path("api/v1/otp/send/", MyAPIView.as_view(), name="view_name"),
```

**views.py**
```
class MyAPIView(generics.CreateAPIView):
    serializer_class = MySerializer

    @extend_schema(
        responses={
            201: {
                "type": "object",
                "properties": {"detail": {"type": "string"}},
                "example": {"detail": "Created"},
            },
        },
    )
    def create(self, request, *args, **kwargs):
        super().create(request, *args, **kwargs)
        return Response(
            data={"message": "Created"},
            status=status.HTTP_201_CREATED,
        )
```

**serializers.py**
```
class MySerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = ["phone_no", "email",]
```
But in the generated schema, the output is,

```
...
responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyModel'
          description: ''
```

why is that? shouldn't there be a 201 field instead in the schema?

**Comment by tfranzel** [comment]
hi, this is a common problem that has come up before a couple of times. added a FAQ entry for it:

https://drf-spectacular.readthedocs.io/en/latest/faq.html#using-extend-schema-on-apiview-has-no-effect

**Comment by amitkbiswas01** [comment]
Thanks for the FAQ. So if I understand correctly, extend_schema won't work with generic views? As the generic views get `create`, `list` etc from the mixins, `get` will be the entrypoint always?
I used generic views mostly everywhere, is there any way to make this work without changing all the generics to APIView or Viewsets?

**Comment by amitkbiswas01** [comment]
Thanks for the FAQ. So if I understand correctly, extend_schema won't work with generic views when I use the mixins methods like `create` or `update`? I just changed my method from `create` to `post` and it works as expected.

Whats a good pattern in this case if I don't want to change CreateAPIView to APIView? Override the `create` or `update` method from the mixins for custom behavior and just add extend_schema to post like this ?

```
@extend_schema(
        responses={
            201: {
                "type": "object",
                "properties": {"detail": {"type": "string"}},
                "example": {"detail": "Created"},
            },
        },
    )
def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

def create(self, request, *args, **kwargs):
        super().create(request, *args, **kwargs)
        return Response(
            data={"message": "Created"},
            status=status.HTTP_201_CREATED,
        )
``` 

or just not use create at all and do everything inside post? 
Sorry I am new in using DRF and this library so the ques might be wrong . Any suggestion is highly appreciated :)

**Comment by tfranzel** [comment]
> So if I understand correctly, extend_schema won't work with generic views when I use the mixins methods like create or update?

no. `extend_schema` will always work, it just has to be attached to the entrypoint, e.g. create for viewset and post for apiview.

you can use a convenience feature to have one less override method:

```python
@extend_schema_view(
    post=extend_schema(
        responses={
            201: {
                "type": "object",
                "properties": {"detail": {"type": "string"}},
                "example": {"detail": "Created"},
            },
        },
    )
)
class MyAPIView(generics.CreateAPIView):
    serializer_class = MySerializer

```

or simply 

```python
    @extend_schema(...)
    def post(self, request, *args, **kwargs):
       # the overridden post only contains a call to create
        super().create(request, *args, **kwargs)
        return Response(
            data={"message": "Created"},
            status=status.HTTP_201_CREATED,
        )
```

**Comment by amitkbiswas01** [comment]
Thank you very much. I am closing the issue as I got the answer I needed :)
