### ISSUE TITLE
0.13.2 dont resolve parameters with `source=` and `@property`

### ISSUE THREAD

**Issue by lsaavedr** [tfranzel/drf-spectacular#296]
**Describe the bug**

## with `@property`
for example if `MyModel` has some property defined with:
```python
    @property
    def foo(self):
        return None
```
and the serializer has:
```python
    foo = PrimaryKeyRelatedField(...)
```
`drf-spectacular` fail with:
```console
django.core.exceptions.FieldDoesNotExist: MyModel has no field named 'foo'
```

## with `source=`
for example if my model has some parameters child like:
```python
>>> from myapp.models import MyModel
>>> mc = MyModel.objects.first()
>>> mc.childName1.childName2 != None
True
```
then if the serializer has:
```python
    foo = PrimaryKeyRelatedField(source="childName1.childName2", ...)
```
`drf-spectacular` fail with:
```console
django.core.exceptions.FieldDoesNotExist: TrackerLog has no field named 'childName1.childName2'
```

**To Reproduce**
puts that kind of parameters (there exist anothers?)

**Expected behavior**
works like 0.13.1

**Comment by tfranzel** [comment]
hi @lsaavedr, so the only thing that changed was this bugfix here #275 from issue #274 

i feared something like that would happen, as this code section is a whack-a-mole. i have trouble reproducing your exact issue though (only had time for testing`@property` verison). can you build a breaking example for both (ideally like in `test_regressions.py`)? that would help a lot

**Comment by tfranzel** [comment]
@lsaavedr so the solution looks easier than it actually is. the source issue was indeed broken by another bugfix and should now be working for all the cases, hopefully. 

the property examples provokes no error in your provided test. afais it works as expected without warning.

**Comment by lsaavedr** [comment]
fixed!!! thanks!!!
