### ISSUE TITLE
How to set Redirect response

### ISSUE THREAD

**Issue by KStenK** [tfranzel/drf-spectacular#297]
Hello,

I'm using DRF APIView and I want to show 301 redirects and redirect location in swagger-ui.

I can add a status code like this:

`
@extend_schema(responses={301: None})
`

But how can I set the response header and add the header: `Location: /`.

I thought i can do something like this:

`
@extend_schema(responses={301: {"headers": {"Location": "/"}}
`

To get schema something like this:

```
responses:
  '301':
    headers:
      Location: /
```

But that does not work.

Is there any way I can do that or how should I customize responses to set headers/cookies with extend_schema?

**Comment by tfranzel** [comment]
@KStenK that feature is not implemented yet. there is currently no direct access for this. we will definitely add this

@sergei-maertens has volunteered to implement this feature in #283. are you still working on this?

**Comment by sergei-maertens** [comment]
It's still on my todo list, but I've been swamped with more urgent things. I'll plan some time at the end of the day to get a PR going!

**Comment by tfranzel** [comment]
@KStenK feature is now available. see here for usage: https://github.com/tfranzel/drf-spectacular/blob/d76c31056a009e30d802537af2dfcfca3310486b/tests/test_extend_schema.py#L108-L114

**Comment by KStenK** [comment]
I don't know what I do wrong, but for me, it does not work.

Here is what have I tried:
![image](https://user-images.githubusercontent.com/53740661/108196103-5e024a80-7121-11eb-901d-dced2104276e.png)

Schema generated:
```
    get:
       . . .
      responses:
        '301':
          description: No response body
```
Swagger UI:
![image](https://user-images.githubusercontent.com/53740661/108196323-a7eb3080-7121-11eb-90b2-6ae14c88fc99.png)

**Comment by tfranzel** [comment]
@KStenK but now it should work. we did not account for the empty body case.

**Comment by KStenK** [comment]
Now looks fine for me :)
![image](https://user-images.githubusercontent.com/53740661/108223283-52734b80-7142-11eb-9b90-c4bdefc94df3.png)

**Comment by KStenK** [comment]
Is there a new version with that feature out too at pip soon?

**Comment by tfranzel** [comment]
i have to fix 2 other issues first. next release is probably next week.
