### ISSUE TITLE
extend_schema_field does not seem to accept raw dicts

### ISSUE THREAD

**Issue by Lucidiot** [tfranzel/drf-spectacular#298]
**Describe the bug**

[The docs for extend_schema_field](https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.extend_schema_field) state it accepts a raw dict as the `field` argument, but it does not seem to be the case.

**To Reproduce**

Create a custom field, extend it with a `dict`, and use the field somewhere:

```python
from drf_spectacular.utils import extend_schema_field

@extend_schema_field({
    'oneOf': [
        {'type': 'string'},
        {'type': 'boolean'}
    ]
})
class MyCustomField(serializers.Field):
    pass

class MySerializer(serializers.Serializer):
    le_field = MyCustomField()
```

Generating the schema then causes two warnings:

```
Warning #0: unable to extract field metadata from field "{'oneOf': [{'type': 'string'}, {'type': 'boolean'}]}" because it appears to be neither a Field nor a Serializer. Proper handling may require an Extension or @extend_serializer_field. Skipping metadata extraction. 
Warning #1: could not resolve serializer field "{'oneOf': [{'type': 'string'}, {'type': 'boolean'}]}". defaulting to "string"
```

Also note that the first warning mentions `extend_serializer_field` when the decorator is now called `extend_schema_field`.

**Expected behavior**

The schema should be overriden with the dict as it is, just like what `OpenApiParameter`'s `type` does.

This causes fields that could use `allOf`, `oneOf` or other constructs that cannot be reproduced by a custom serializer or a `PolymorphicProxySerializer` require a separate field extension.

**Comment by tfranzel** [comment]
hey @Lucidiot, i made a regression test for this and i cannot reproduce the problem.

```python
def test_foo(no_warnings):
    @extend_schema_field({
        'oneOf': [
            {'type': 'string'},
            {'type': 'boolean'}
        ]
    })
    class CustomField(serializers.Field):
        pass

    class XSerializer(serializers.Serializer):
        field = CustomField()

    @extend_schema(request=XSerializer, responses=XSerializer)
    @api_view(['POST'])
    def view_func(request, format=None):
        pass  # pragma: no cover

    schema = generate_schema('x', view_function=view_func)
```

but i'm sure it has also already been covered by: https://github.com/tfranzel/drf-spectacular/blob/f219b6eb587197a3ab541028f0d62270836a0467/tests/test_extend_schema.py#L303

this warning occurs only when the `CustomField` is not an instance of `serializers.Field`, which it is here. so i would say your example does not quite match your real problem. can you break that down for me?

the typo i will correct of course.

**Comment by Lucidiot** [comment]
I spent about an hour trying to narrow down the issue, then I found out I had v0.12 and installing 0.13.2 fixed the issue. :man_facepalming: Sorry about that!
