### ISSUE TITLE
Add `additionalProperties` to keys that do not discard the resolved serializer

### ISSUE THREAD

**Issue by sergei-maertens** [tfranzel/drf-spectacular#299]
Mostly creating this as a self-reminder for a PR to create, but, the following code:

https://github.com/tfranzel/drf-spectacular/blob/f219b6eb587197a3ab541028f0d62270836a0467/drf_spectacular/openapi.py#L1073

triggers whether a resolved serializer component is kept in the schema or not. The logic has some support for the typical polymorphic properties (`oneOf`, `anyOf`, `allOf`) and also explicit schemas - i.e. the `properties` key is set and the schema actually has a pre-defined shape.

However, we're in a highly dynamic use case, see our [polymorphism](https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/api/polymorphism.py) implementation.

1. Schema is polymorphic, and the base serializer is composed of itself + an extra serializer, mapped via the discriminator field value.
2. Our "empty" discriminator value maps to a _dynamic_ serializer, meaning that we don't know the schema statically
3. To build the runtime serializer, we fetch the form definition from an external system, and map the appropriate serializer fields. This works fine, also in the context of the parent polymorphic serializer.
4. However, for the schema generation, we're essentially dealing with a hashmap here, for which `additionalProperties: true` is typically used in OpenAPI
5. The serializer class does not have any field declarations, so `resolve_serializer` discards it. Because it's discarded, the empty string discriminator value is discarded as well, so the whole dynamic form serializer doesn't show up in the schema.

I've solved this by generating a `ResolvedComponent` in the polymorphic serializer extension, however this is a pattern that will be used outside of polymorphic serializers as well.

The clean solution would be to have a base serializer, e.g. `class HashMapSerializer(serializers.Serializer): pass`, and all the dynamic run-time behaviour can be in subclasses (in the `__new__` class method for example). Then, we can write an `OpenApiSerializerExtension` targeting that class, which generates an object_type:

```yaml
type: object
additionalProperties: true
```

`resolve_serializer` then also needs to _keep_ the schema if `additionalProperties` is found in the schema, and everyone is happy :-)

**Comment by tfranzel** [comment]
hi @sergei-maertens, took me some time to get around this again.

 this isssue is related to #395 and #351 and was fixed with f824bf1 (at least i'm pretty confident that it did)

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
