### ISSUE TITLE
@silk_profile

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#30]
Using `silk_profile` from https://pypi.org/project/django-silk/ produces

> WARNING #285: Unable to guess serializer for wrapped_target. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. ignoring view for now.

The code causing this is probably my own.  While I can workaround this by expanding these to use GenericAPIView, using these decorators from core drf allows for very small handlers.  I only have 8 of these warnings, so it isnt a high priority for me, but worth finding a solution for as long as `@api_view` is still core part of drf.

```py
@api_view(['POST'])
@silk_profile(name='Update user info')
@authentication_classes((JSONWebTokenAuthentication,))
def update_user_info(request, format=None):
    ...
```

This occurs with silk 3 and silk 4

```py
git grep --context 3 wrapped_target
silk/profiling/dynamic.py-    decorator = silk_profile(name, _dynamic=True)
silk/profiling/dynamic.py-    func_name = func
silk/profiling/dynamic.py-    cls, func = _get_func(module, func_name)
silk/profiling/dynamic.py:    wrapped_target = decorator(func)
silk/profiling/dynamic.py-    if cls:
silk/profiling/dynamic.py:        setattr(cls, func_name.split('.')[-1], wrapped_target)
silk/profiling/dynamic.py-    else:
silk/profiling/dynamic.py:        setattr(module, func_name, wrapped_target)
silk/profiling/dynamic.py-
silk/profiling/dynamic.py-
silk/profiling/dynamic.py-def _get_parent_module(module):
--
silk/profiling/profiler.py-
silk/profiling/profiler.py-    def __call__(self, target):
silk/profiling/profiler.py-        if self._should_meta_profile:
silk/profiling/profiler.py:            def wrapped_target(*args, **kwargs):
silk/profiling/profiler.py-                request = DataCollector().request
silk/profiling/profiler.py-                if request:
silk/profiling/profiler.py-                    start_time = timezone.now()
--
silk/profiling/profiler.py-                    result = target(*args, **kwargs)
silk/profiling/profiler.py-                return result
silk/profiling/profiler.py-
silk/profiling/profiler.py:            return wrapped_target
silk/profiling/profiler.py-        return target
silk/profiling/profiler.py-
silk/profiling/profiler.py-
--
silk/profiling/profiler.py-
silk/profiling/profiler.py-    def __call__(self, target):
silk/profiling/profiler.py-        if self._silk_installed():
silk/profiling/profiler.py:            def wrapped_target(*args, **kwargs):
silk/profiling/profiler.py-                with silk_meta_profiler():
silk/profiling/profiler.py-                    try:
silk/profiling/profiler.py-                        func_code = target.__code__
--
silk/profiling/profiler.py-                        self._finalise_queries()
silk/profiling/profiler.py-                return result
silk/profiling/profiler.py-
silk/profiling/profiler.py:            return wrapped_target
silk/profiling/profiler.py-        else:
silk/profiling/profiler.py-            Logger.warning('Cannot execute silk_profile as silk is not installed correctly.')
silk/profiling/profiler.py-            return target
```

It may be that silk isnt doing the wrapping "properly" in the modern way to facilitate introspection of the underlying object, and the issue needs to be raised upstream.

**Comment by tfranzel** [comment]
it seems like silk is certainly interfering with the way things are discovered. i consider this low priority because its a profiling app.

on a general note, ``@api_view`` is nothing more than sytactic sugar for an ``APIView``. The problem with ``APIView`` is that it provides nothing to introspect, therefore nothing to pick up by spectacular. In those cases it is usually advisable to use ``@extend_schema(request=XXX, response=XXX)`` to advice spectacular what to use (where it is under your control). this removes the get_serializer warning by overriding serializer discovery. ``@extend_schema`` should work with ``@api_view``. somehow i forgot to add a test for it.

**Comment by tfranzel** [comment]
@jayvdb small correction on my part:
```
@extend_schema(xxx)
@api_view()
def foo(request):
    pass
```
was in fact broken. not that it makes a difference here, but my statement was incorrect. fixed in f084890

**Comment by tfranzel** [comment]
@jayvdb: there is nothing wrong here. you have to annotate the type because it cannot be extracted from ``@api_view`` by itself. nothing special here for `silk`.

```
@extend_schema(request=OpenApiTypes.OBJECT, responses=OpenApiTypes.OBJECT)
@api_view(['POST'])
@silk_profile(name='XXX')
def test(request, format=None):
    pass
```

works for me and behaves as expected.

**Comment by tfranzel** [comment]
i haven't tried viewing the silk ui, but ``@extend_schema`` should be transparent to silk, as it does not wrap the `api_view` but rather just patches some schema related attributes.
