### ISSUE TITLE
inline_serializer does not work as expected and "No response body" is shown

### ISSUE THREAD

**Issue by Wissperwind** [tfranzel/drf-spectacular#300]
I have a view that does custom stuff and does not use a serializer to assemble the response.
The response is application/json.
I am trying to use a inline_serializer to tell swagger how my response looks like. See here:

```
responses={(200, 'application/json'): inline_serializer("CPU Info",
                   fields={"cpu_load_percent": OpenApiTypes.DOUBLE}),
                   (403, 'text/plain'): OpenApiTypes.STR},
```

But on the swagger page "No response body" is shown.

I would expect that it shows something, and especially somathing like:

```
{
"cpu_load_percent": double
}
```

**Comment by tfranzel** [comment]
hi! `inline_serializer` actually constructs a real serializer, thus the fields need to be real fields.  you need to do e.g. `fields={"cpu_load_percent": serializers.FloatField()}`. 

alternatively you can go full raw with a dict instead of `inline_serializer`

**Comment by Wissperwind** [comment]
Ok, did not know that.
So how is the syntax for going full raw?
I tried:
```
responses={(200, 'application/json'): {"cpu_load_percent": "double"},
                    (403, 'text/plain'): OpenApiTypes.STR},
```

And it diesplays now a black box with "(no example available)"
How can I make it display '{"cpu_load_percent": "double"}'?

**Comment by tfranzel** [comment]
> {"cpu_load_percent": "double"}

that is not a OpenAPI 3.0.3 compliant component object.

just use my example which should work as expected. full raw has several drawbacks and you should only use it of nothing else works.

**Comment by Wissperwind** [comment]
Ok, so no I have:
```
{
  "cpu_load_percent": 0
}
```
What might be more conform to the rules that "double".
Thanks

**Comment by Wissperwind** [comment]
By th way: I figured out that if I provide an example, it is diesplayd at the field of the 200 response.
is it possible to provide an example for the 403 case, wehre my error message is displayed?

**Comment by Wissperwind** [comment]
And is it possible to provide examples for text/plain responses?
I noticed that the example is displayed only, if I type in "application/json" in the response field.

**Comment by tfranzel** [comment]
Please study the interface and documentation.

general example usage:

https://github.com/tfranzel/drf-spectacular/blob/f219b6eb587197a3ab541028f0d62270836a0467/tests/test_examples.py#L88

content type for example

https://github.com/tfranzel/drf-spectacular/blob/f219b6eb587197a3ab541028f0d62270836a0467/drf_spectacular/utils.py#L84

**Comment by Wissperwind** [comment]
Ah, thats usuefull. Sorry, wasn't able to proceed with the information on reed the docs and didn't expect to find examples in the tests folder.

**Comment by snake-py** [comment]
I am running into the same issue. I don't have a serializer for some of my endpoints. So I thought I can use a simple dictonary:
(I also tried setting up a inline_serializer, which did not do the trick as well)
```   
    @extend_schema(tags=['Purchase'],
    request={"name": rest_serializer.FloatField()},
    responses={202: ('id', rest_serializer.UUIDField())}
    )
    
 ```
 
 Could someone point me in the correct direction? Currently, the response and request body is empty in the swagger ui. What am I doing wrong?

**Comment by tfranzel** [comment]
your usage is incorrect. those accept either `Serializer` or ``OpenApiType`, not serializer fields. usage is documented here :https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.extend_schema

inline_serializer work to my knowledge:
https://github.com/tfranzel/drf-spectacular/blob/243445f719e574ef8b292428070f93d62e647ddd/tests/test_regressions.py#L956-L975

**Comment by snake-py** [comment]
This looks really helpful! Thank you!
