### ISSUE TITLE
A serializer is required for delete actions with schema overrides

### ISSUE THREAD

**Issue by Lucidiot** [tfranzel/drf-spectacular#308]
**Describe the bug**

OpenAPI does not allow request bodies for `delete` operations, and both DRF and Spectacular return a `204` with no response body by default, so a serializer in a `DestroyAPIView` with no other methods should not be required or used. Generating the schema for a `DestroyAPIView` without a serializer works, but causes this error when `@extend_schema` or `@extend_schema_view` is used:

```
Error #0: Exception raised while getting serializer from Nuke. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Nuke' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.)
```

Adding `responses={204: None}` to `extend_schema`, or adding any serializer causes the error to go away.

**To Reproduce**

Create any `DestroyAPIView` with a queryset, without a serializer and with `extend_schema` or `extend_schema_view` on it, then generate the schema and watch it go boom.

```python
@extend_schema(tags=['explosives'])
class Nuke(DestroyAPIView):
    queryset = MyModel.objects.none()
```

**Expected behavior**

No error, and a valid schema for `DestroyMyModel` with no request body and a 204 response with no body.

**Comment by tfranzel** [comment]
i acknowledge that this is a ridiculously easy thing to ask, but unfortunately the solution is pretty tricky :disappointed_relieved: 

`DestroyApiView` is a `GenericApiView`, which generally is supposed to have a `serializer_class` specified. of course it is not needed here, but the processing is not aware of that. in theory it is easy to fix, but not without breaking other things. The core issue is that these hybrid classes lie somewhere in between a `Viewset` and a `ApiView`. 

the easiest quickfix i can offer is this. it jumps the serializer estimation by explicit override and thus circumvents the warning 
```python
@extend_schema_view(delete=extend_schema(responses=None))
class Nuke(DestroyAPIView):
    queryset = MyModel.objects.none()
```
i'll keep this in mind, maybe a good solution will hit me.

**Comment by tfranzel** [comment]
As a matter of fact, this is the only case where this problem occurs. `CreateAPIView`, `RetrieveAPIView`,  `ListAPIView`, etc all need a `serializer_class` to work. `DestroyAPIView` is the singular exception.

**Comment by tfranzel** [comment]
I decided that this will most likely not be fixed due to consistency reasons. The annotation fix is reasonably easy and the inconsistency in DRF does not warrant further complicating our processing logic.
