### ISSUE TITLE
extend_schema is always return object list in ViewSet.list action

### ISSUE THREAD

**Issue by elonzh** [tfranzel/drf-spectacular#311]
**Describe the bug**
`extend_schema` is always return object list in `ViewSet.list` action.

**To Reproduce**

```python
class UserProfileViewSet(viewsets.ViewSet):

    @extend_schema(responses=UserProfileSerializer)
    def list(self, request):
		...
```

schema 

![image](https://user-images.githubusercontent.com/8749411/108648040-274b7c00-74f5-11eb-96d8-e8999a27989a.png)

**Expected behavior**

single object response schema as `extend_schema` required.

**Comment by tfranzel** [comment]
this is what `list` is supposed to do in Viewsets. you need to tell spectacular that you are deviating from the default

```python
class UserProfileViewSet(viewsets.ViewSet):

    @extend_schema(responses=extend_schema_serializer(many=False)(UserProfileSerializer))
    def list(self, request):
```

if you use the serializer somewhere else again (in a listing situation), i would suggest doing this as the decorator modified the serializer. however, this may lead to a duplicate component.

```python
@extend_schema_serializer(many=False)
class MeUserProfileSerializer(UserProfileSerializer):
    pass
```
