### ISSUE TITLE
Missing swagger_fake_view attribute

### ISSUE THREAD

**Issue by d2718nis** [tfranzel/drf-spectacular#321]
Hi. I'm using drf-spectacular with [drf-nested-routers](https://github.com/alanjds/drf-nested-routers) and faced an issue: whenever I'm raising Http404 inside `get_queryset` or before the method call, for example if the nested object does not exist, I get this warning when accessing Swagger schema view:

```
UserWarning: <ViewSet> not compatible with schema generation
```

I know that drf-yasg has a mechanism to distinguish a real view from the schema-generated one described in this issue https://github.com/axnsan12/drf-yasg/issues/267:

```python
if getattr(self, 'swagger_fake_view', False):
   return Offer.objects.none()
```

Unfortunately I wasn't able to find something like that for drf-spectacular. Maybe I'm missing something or this could be a feature request. Thanks!

**Comment by tfranzel** [comment]
Hi! i was hesitant to do this before as it felt like a cop-out, but i realize now that sometimes you are simply stuck there and all other option are worse. i mean we do generate mock requests with an anon user, but apparently that is not enough the cover all cases. 

so added the feature finally. :rocket:

**Comment by d2718nis** [comment]
This is just wonderful, thank you very much!
