### ISSUE TITLE
Show scopes per view in swagger UI

### ISSUE THREAD

**Issue by krzysieqq** [tfranzel/drf-spectacular#324]
Hi,
I need to show in swagger oauth2 scope per view. In my view I declarated `required_scopes = ['custom_scope']`, but In Swagger, I don't see any information about it. 

Redoc correctly showing me a line with ```AUTHORIZATIONS: oauth2 (custom_scope)```

Can swagger or redoc views shows defined class permission fg. `permission_classes = [IsModerator]` or I need to use scope for showing that in swagger/redoc UI?

**Comment by tfranzel** [comment]
hi, i suppose this happens because scopes are listed in the views, but not declared in the security section. currently, there is no collection happening here. only pre-defined values are used.

by setting `oauth2_provider.settings.oauth2_settings.SCOPES` you can pre-populate the security section and scopes should show up as expected.

fyi: the schema is identical for redoc and swagger views.

**Comment by krzysieqq** [comment]
I know thath schema is the same, so why swagger doesn't show me oauth2 scope when redoc shows. Screens bellow
![image](https://user-images.githubusercontent.com/13196622/110210737-5f5aa380-7e93-11eb-8feb-19c92e3fecf7.png)
![image](https://user-images.githubusercontent.com/13196622/110210788-9b8e0400-7e93-11eb-8a14-703e1ea1e54b.png)

I've defined scopes before use. When I import in shell `from oauth2_provider.settings import oauth2_settings` `oauth2_settings.SCOPES` shows scopes defined in settings:
```
{'read': 'Reading scope',
 'write': 'Writing scope',
 'operator': 'operator'}
```


my spectacular settings in admin:
```
SPECTACULAR_SETTINGS = {
    "VERSION": API_VERSION,
    "SERVE_PUBLIC": True,
    "SERVE_INCLUDE_SCHEMA": False,
    "CAMELIZE_NAMES": True,
    "OAUTH2_FLOWS": ["password"],
    # 'OAUTH2_AUTHORIZATION_URL': f"{SERVER_NAME}/users/auth/authorize/",
    "OAUTH2_TOKEN_URL": f"{SERVER_NAME}/users/auth/token/",
    "OAUTH2_REFRESH_URL": f"{SERVER_NAME}/users/auth/token/",
    # "OAUTH2_SCOPES": ['read', 'write', 'operator', 'animator', 'supplier'], # OAUTH2_PROVIDER['SCOPES'],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "displayOperationId": True,
        "showExtensions": True,
        "showCommonExtensions": True,
        "persistAuthorization": True,
    },
    # Split components into request and response parts where appropriate
    'COMPONENT_SPLIT_REQUEST': True,
    # Aid client generator targets that have trouble with read-only properties.
    # 'COMPONENT_NO_READ_ONLY_REQUIRED': False,
    # Create separate components for PATCH endpoints (without required list)
    'COMPONENT_SPLIT_PATCH': False,
    # Adds "blank" and "null" enum choices where appropriate. disable on client generation issues
    # 'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': True,
}
```

Spectacular version 0.13.2

**Comment by tfranzel** [comment]
so you have the correct settings as far as i can tell and also redoc is showing the scopes as expected, then this looks like a feature request/bug for Swagger UI https://github.com/swagger-api/swagger-ui . we only use the swagger UI without modification.

i'm not aware on how to make swagger UI show the required scopes.

**Comment by krzysieqq** [comment]
I see that there is a request feature at swagger UI https://github.com/swagger-api/swagger-ui/issues/5062 

The last comment in the issue (https://github.com/swagger-api/swagger-ui/issues/5062#issuecomment-747972244) shows a workaround that works as expected when implemented in spectacular.
