### ISSUE TITLE
Scoping documentation based on access level - or - permission classes

### ISSUE THREAD

**Issue by tiholic** [tfranzel/drf-spectacular#325]
I want to expose docs for handful of APIs (1) to all our users - include in public documentation.
And expose docs for complete set of APIs to staff users (2) - these APIs are mostly specific to UI and security related ones like managing auth tokens.

I could achieve **(1)** using `exclude: True` using `extend_schema`. But this suppresses **(2)**

This could also help us in generating 2 different JS SDKs - one to be open-sourced and another to be consumed in our own UI.

**Comment by tfranzel** [comment]
currently you can do this by 

```python
path('api/internal/schema/', SpectacularAPIView.as_view(urlconf=urlpatterns_public))
path('api/external/schema/', SpectacularAPIView.as_view())  # all
```
but that means you have to have a splitted `urlpatterns` in `urls.py`

**Comment by tiholic** [comment]
That's a way to go, but we would need to split some views for that!

Can you point me in a direction where we can add a function `is_authorized` / or list of `authentication classes` at schema extraction level! I can create a PR for the same.

**Comment by tfranzel** [comment]
> Can you point me in a direction where we can add a function is_authorized / or list of authentication classes at schema extraction level! I can create a PR for the sam

@tiholic i don't quite understand what you mean. maybe this is what you are after: we have a settting `'SERVE_PUBLIC': False, (default True)` that should filter down the schema based on the permissions of the requesting user. however that will only work with the view and not the CLI obviously. this should work, but i just found that we do not have a test case for this. must have been overlooked

another solution would be scoping via extend_schema, but that does not look like an ideal solution either.

**Comment by tfranzel** [comment]
i see what you mean. unfortunately would mean you have to apply extend_schema to everything. we could think about this more thoroughly though.

have you tried using `'SERVE_PUBLIC': False` this should filter down schema based on the permissions of the requesting user for each and every endpoint? or is that approach to coarse?

**Comment by tiholic** [comment]
Yes, I'm already using `SERVE_PUBLIC: False`. Not what solves my need, though.

Anyways I'm extending schema for all my views to have a custom operation IDs for better SDK generation and don't mind adding an extra argument on a few.

**Comment by tfranzel** [comment]
ok.. bummer. i would prefer to not introduce a change here unless there is more pressure from the users. 

generally there is also the option for post- and preprocessing hooks.  you can also look into that. enum handling is a postprocessing hook

**Comment by alxvallejo** [comment]
>i see what you mean. unfortunately would mean you have to apply extend_schema to everything

@tfranzel as opposed to what? I thought applying `extend_schema` was generally the go-to for any view-level specification that goes beyond the auto-schemas generated (in my case it's just about every single view). I'm surprised this isn't more universally supported - documenting permissions for api routes seems like a pretty standard use case.
