### ISSUE TITLE
Wrong lock icon for endpoints

### ISSUE THREAD

**Issue by discover59** [tfranzel/drf-spectacular#328]
Swagger UI shows private endpoints with unlocked icon and public endpoints with locked icon.
This is confusing for user. It should use locked icon for private endpoints.

Python 3.7
Django 2.2.18
drf-spectacular 0.13.2

**Comment by tfranzel** [comment]
well, the icon is a design decision of Swagger UI https://github.com/swagger-api/swagger-ui and is out of the scope of drf-spectacular. we merely provide a thin wrapper around the upstream project.

**Comment by discover59** [comment]
Ah, I should have checked this issue on swagger ui first. It's wrong on their end.

**Comment by heckad** [comment]
[I just leave it here.](https://github.com/swagger-api/swagger-ui/issues/4402)
