### ISSUE TITLE
django-phonenumber-field

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#33]
https://pypi.org/project/django-phonenumber-field/ 2.0.1 (unfortunately locked to that by current django-oscar & django-oscar-api & django-oscar-api-checkout):

`could not resolve serializer field ModelField(help_text='In case we need to call you about your order', model_field=<phonenumber_field.modelfields.PhoneNumberField: phone_number>, required=False, validators=[<function validate_international_phonenumber>, <django.core.validators.MaxLengthValidator object>]). defaulting to "string"`

The `master` versions should let me update to django-phonenumber-field v3, but poetry is making that difficult to upgrade with git (https://github.com/python-poetry/poetry/issues/2336).  Doing a fresh install to get around that.

**Comment by tfranzel** [comment]
not quite sure what to do here.

can't find ``ModelField`` in https://github.com/stefanfoulis/django-phonenumber-field. 

not sure, but i believe https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/serializerfields.py#L8 should work because its is based on a ``CharField``.

**Comment by jayvdb** [comment]
The `ModelField` invocation is in https://github.com/django-oscar/django-oscar/blob/a22f4991b036890b2d90839cd2c4a03e22258255/src/oscar/apps/address/abstract_models.py

I've managed to do a build with oscar "master", which uses django-phonenumber-field v3, and the warning has disappeared,  so I suspect this only occurs in django-phonenumber-field v2.

However, the datatype when using django-phonenumber-field v3 remained as "string", which is a sane and possibly even correct datatype for this field, so this is almost a non-issue except for the annoyance.  I do not intend to be using oscar "master" in production, so until they do a release I guess I live with the warning or add a helper to mask the warning.  Feel free to close if django-phonenumber-field v2 isnt worth supporting.

**Comment by tfranzel** [comment]
i understand. i don't plan on introducing hacks for specific libraries, but maybe this gets solved through some other generalization or introspection improvements. i'll leave it open for now but make it low prio. please close if you notice that the issue disappeared. thanks!

**Comment by tfranzel** [comment]
problem was that the old model class was `class PhoneNumberField(models.Field)` and the new class is `class PhoneNumberField(models.CharField)`. 

https://github.com/stefanfoulis/django-phonenumber-field/commit/fe946db5bb59740150cd7e1b05c1e39ee7f291bb#diff-497bc1cf2ee9e2f3444d450019a283c4L43

code is now more graceful for the old variant by trying to use `get_internal_type` before bailing.
