### ISSUE TITLE
How to use extend schema with custom enpoints

### ISSUE THREAD

**Issue by fvukojevic** [tfranzel/drf-spectacular#330]
This is simple issue I just wanted to reach out, maybe I'm not reading the docs correct.

But I have this super simple example that is working (custom responses)
```
    @extend_schema(
        responses={
            200: PatientSerializer,
            401: OpenApiTypes.OBJECT,
            500: OpenApiTypes.OBJECT,
        },
        examples=[UNAUTHORIZED_RESPONSE, INTERNAL_SERVER_ERROR_RESPONSE],
    )
    def list(self, request: Request, *args: Any, **kwargs: Any) -> Response:
        return super().list(request, *args, **kwargs)
```

I would love to do the same, for a custom endpoint (let's call it test)
```
    @extend_schema(
        responses={
            200: PatientSerializer,
            401: OpenApiTypes.OBJECT,
            500: OpenApiTypes.OBJECT,
        },
        examples=[UNAUTHORIZED_RESPONSE, INTERNAL_SERVER_ERROR_RESPONSE],
    )
    @action(detail=False, methods=["post"], url_name="test", url_path="test")
    def test(self, request: Request) -> JsonResponse:
        ....
```

In here extend schema fails, and swagger gives an exception that this isn't a part of `AutoSchema`. I tried extending it but the AutoSchema mappings look like this:
```
    method_mapping = {
        'get': 'retrieve',
        'post': 'create',
        'put': 'update',
        'patch': 'partial_update',
        'delete': 'destroy',
    }
```

And my post would now be a list with ['create', 'test'] which isnt' supported.

Maybe I am missing something, but is there  a way to extend schema, and response examples for custom endpoints?

**Comment by tfranzel** [comment]
please provide the exact error. this is supposed to work and is already covered extensively in the tests. touching the `method_mapping` is not the right thing to do.

https://github.com/tfranzel/drf-spectacular/blob/4115ed4ca6b44e91ff9978c919350adda5a8905c/tests/test_extend_schema.py#L137-L144

the only thing that looks out of place for me now is ` -> JsonResponse`. we need more context.

**Comment by fvukojevic** [comment]
This is the exact example I recreated it with test route 

```
    @extend_schema(
        responses={
            200: PatientSerializer,
            401: OpenApiTypes.OBJECT,
            404: OpenApiTypes.OBJECT,
            500: OpenApiTypes.OBJECT,
        },
        examples=[
            UNAUTHORIZED_RESPONSE,
            NOT_FOUND_RESPONSE,
            INTERNAL_SERVER_ERROR_RESPONSE,
        ],
    )
    @action(detail=False, methods=["post"], url_name="test", url_path="test")
    def test(self, request: Request) -> JsonResponse:
           {some logic}
```

And it prompts me with this error 

`AssertionError: Incompatible AutoSchema used on View <class 'test.testresources.v1.test.TestViewSet'>. Is DRF's DEFAULT_SCHEMA_CLASS pointing to "drf_spectacular.openapi.AutoSchema" or any other drf-spectacular compatible AutoSchema?
`

Once I remove the `@extend_schema` then it works, but only shows 200 status code in swagger, I need those others as well

**Comment by fvukojevic** [comment]
Nevermind you can resolve this,

The problem ended up being with one `Patch` method that was calling this one liek 

`test.mapping.patch`

And because it didn't have the same extend schema, it was failing. Now it's working, and thanks for the help
