### ISSUE TITLE
Request: non-zero exit codes when errors or optionally warnings occur

### ISSUE THREAD

**Issue by rvinzent** [tfranzel/drf-spectacular#333]
Hi, I have the docs generation hooked up to my CI pipeline and I noticed that jobs would still pass even when errors occurred. It looks like the `spectacular` management command will `exit 0` no matter what.

It would be nice if the commands exit 1 when errors occur, and it would be nice if we could enable some kind of strict mode that would exit 1 even when a warning occurs/

Thanks!

**Comment by rvinzent** [comment]
I can see this is already a feature 🙂  sorry about that!

**Comment by tfranzel** [comment]
actually quite an old feature.

as reference for the next person https://drf-spectacular.readthedocs.io/en/latest/client_generation.html

``./manage.py spectacular --file schema.yaml --validate --fail-on-warn``
