### ISSUE TITLE
I have installed drf-spectacular, and it's working great. The problem I've got is that it's a big app, and has a huge amount of endpoints and for each endpoint it repeats the /api/v1/ e.g /api/v1/jobs/.  So I thought it would be a good idea to separate the pattern out i.e just /jobs

### ISSUE THREAD

**Issue by Fyp89** [tfranzel/drf-spectacular#336]
**Describe the bug**

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

**Expected behavior**

**Comment by tfranzel** [comment]
please describe the problem in more detail. "separating patterns" is could mean several things.

**Comment by Fyp89** [comment]
> please describe the problem in more detail. "separating patterns" is could mean several things.

Thanks for reaching out. I have attached screenshot for reference. I would like to not include api/v1/ when showing endpoints. For example first endpoint under jobs should be displayed /jobs/ .
<img width="1440" alt="Screen Shot 2021-03-15 at 1 43 44 PM" src="https://user-images.githubusercontent.com/6915445/111212026-bac41a00-8594-11eb-8f28-511fbe1d1ce2.png">

**Comment by mohannad-musleh** [comment]
@Fyp89 

try to add `SCHEMA_PATH_PREFIX` to `SPECTACULAR_SETTINGS`

with this setting, all endpoints prefixed with `/api/v[ANY_NUMBER]` will be handled as the URL prefix

```python
SPECTACULAR_SETTINGS = {
    # other settings
    "SCHEMA_PATH_PREFIX": r"/api/v[1-9][0-9]*"
}
```

**Comment by tfranzel** [comment]
that is partially correct. `SCHEMA_PATH_PREFIX` deals with tag extration, it does not modify the route. i'm working on a setting to remove the prefix from the route.

**Comment by Fyp89** [comment]
@mohannad-musleh Thanks for the reply. I am already using it and as @tfranzel said it works for separating endpoints by tags as you can see in the screenshot attached above the endpoints are under jobs.

**Comment by tfranzel** [comment]
@Fyp89  `SCHEMA_PATH_PREFIX_TRIM` is the new setting for this. set to `True` for removing the prefixes from the operation path.

**Comment by Fyp89** [comment]
Just downloaded the code and checked, works like a charm. Thank you so much for this enhancement @tfranzel . How soon can this change be released ?

**Comment by tfranzel** [comment]
this will be a y-stream release because i had to break an internal interface that some people may use. i have 2-3 more things that would need a y-stream release, which i want bundle together. likely next week.
