### ISSUE TITLE
Adding docstring or @extend_schema to create/update doesn't take any effect

### ISSUE THREAD

**Issue by krzysieqq** [tfranzel/drf-spectacular#338]
When I add any docstring or `@extend_schema` to the method like create or update in using APIViews it doesn't render in swagger UI.  I think it could work the same as adding docstring or `@extend_schema` to post/put/patch methods. Am I doing something wrong or it is the intended behavior?

**Comment by tfranzel** [comment]
This works without an issue. However this has to be taken into consideration: https://drf-spectacular.readthedocs.io/en/latest/faq.html#using-extend-schema-on-apiview-has-no-effect

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
