### ISSUE TITLE
wrong Enum type generated when choices have named groups.

### ISSUE THREAD

**Issue by elonzh** [tfranzel/drf-spectacular#339]
**Describe the bug**
According to [Django document](https://docs.djangoproject.com/en/3.1/ref/models/fields/#field-choices-named-groups:~:text=into-,named%20groups), `choices` supports named groups but drf-spectacular can not generate right schema.

**To Reproduce**

For example:
```python
MEDIA_CHOICES = [
    ('Audio', (
            ('vinyl', 'Vinyl'),
            ('cd', 'CD'),
        )
    ),
    ('Video', (
            ('vhs', 'VHS Tape'),
            ('dvd', 'DVD'),
        )
    ),
    ('Unknown', 'Unknown'),
]
```

will be generated as:

```json
	schema:
          enum:
          - Audio
          - Unknown
          - Video
          type: string
```

**Expected behavior**

generates the right schema.

**Comment by tfranzel** [comment]
wasn't aware of that django feature. yes we should account for that. the right schema would then be `enum: ['vinyl', 'cd', 'vhs', 'dvd']`, right?

**Comment by elonzh** [comment]
@tfranzel Yes you are right.

**Comment by tfranzel** [comment]
@elonzh so there is indeed a small bug in `ENUM_NAME_OVERRIDES`, but in any case i was unable to produce a schema like stated above. the DRF/Django field mechanics do this transformation automatically. at least that is what i'm observing at the moment. 

how did you use `MEDIA_CHOICES` in field to produce that schema?

**Comment by elonzh** [comment]
Sorry, It's my mistake, My choices are generated and I can't reproduce this issue now.
