### ISSUE TITLE
Types embedded in url paths

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#34]
https://github.com/django-oscar/django-oscar-api/blob/e57b34b/oscarapi/urls.py says `basket_pk` has type `int`

However I get warnings
```
WARNING #130: could not derive type of path parameter "basket_pk" because model "<class 'oscar.apps.basket.models.Line'>" did contain no such field. consider annotating parameter with @extend_schema. defaulting to "string".
...
WARNING #144: could not derive type of path parameter "basket_pk" because model "<class 'oscar.apps.basket.models.LineAttribute'>" did contain no such field. consider annotating parameter with @extend_schema. defaulting to "string".
```

`OscarHyperlinkedModelSerializer` from https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/serializers/utils.py uses `rest_framework.serializers.HyperlinkedModelSerializer`, but the problem seems to be a customisation 
[`extra_url_kwargs`](https://github.com/django-oscar/django-oscar-api/search?q=extra_url_kwargs)

**Comment by tfranzel** [comment]
url path and query parameters are a tricky business. spectacular already tries reasonable hard to find those, but everything that is manually handled in method bodies is more or less impossible to extract. there are only heuristics for possibly finding the right thing in the model.

there might be cases that can be improved but given the other issues i will assign this low prio and pick it up once the other issues are resolved

**Comment by tfranzel** [comment]
@jayvdb at least the format suffix is DRF native, so i added something reasonable for that (although not 100% perfect): 60625c4

also, i was curious yesterday and set up the example oscar-api app. i got 22 unique warnings after that. not too bad i suppose. however, some of those warnings are not resolvable without an additional override mechanism.

**Comment by jayvdb** [comment]
`<int:x>` is DRF native also.

**Comment by tfranzel** [comment]
with native i meant a more or less static DRF feature virtually always to be a string.

you make a good point with `<int:x>`. that could be leveraged, but the DRF path traversal strips this i think. worth looking into though.

**Comment by tfranzel** [comment]
@jayvdb implemented said feature. turned out quite nice imho. this is pretty much the limit of what can extracted from the path.

**Comment by jayvdb** [comment]
Awesome!
