### ISSUE TITLE
Custom Filter fails on warn

### ISSUE THREAD

**Issue by fvukojevic** [tfranzel/drf-spectacular#340]
When running 

```
poetry run python3 manage.py spectacular --format openapi --file docs/openapi.yaml --fail-on-warn
```

it fails on one of my custom filters with the following error 
```
Warning #0: could not resolve field on model <class 'pds.pds_app.models.test.Test'> with path "test_search". this is likely a custom field that does some unknown magic. maybe consider annotating the field/property? defaulting to "string". (Exception: Test has no field named 'test_search')
```

Where a `test_search` is defined like:

```
    test_search = SearchVectorFilter[Test](
        SearchVector("field1", "field2", config="simple"),
        search_type="plain",
    )
```

I have other filters (not custom made) like 
```
    id_in = UUIDInFilter(field_name="id", lookup_expr="in")
```

And that works just fine

Any help here?

**Comment by tfranzel** [comment]
`SearchVectorFilter` is not part of `unambiguous_mapping`, nor has a hinted method. this warning occurs in the fallback branch. spectacular simply cannot estimate the filter type for a class with an unknown base class. 

you may have to subclass `DjangoFilterExtension` (with priority=1).

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
