### ISSUE TITLE
How to set SERVERS from request?

### ISSUE THREAD

**Issue by grigandal625** [tfranzel/drf-spectacular#343]
I don't get the `servers` field in the schema

How can I specify in the settings that the generator receives it from the request? 

I didn't see it in the [documentation](https://drf-spectacular.readthedocs.io/en/latest/settings.html)

**Comment by grigandal625** [comment]
Sorry, `host` is depricated

I mean `servers`

Now i did that:

```
class SpectacularHAPIView(SpectacularAPIView):
    def _get_schema_response(self, request):
        generator = self.generator_class(urlconf=self.urlconf, api_version=self.api_version)
        res = generator.get_schema(request=request, public=self.serve_public)
        res['servers'] = [{'url':f"{request.META['wsgi.url_scheme']}://{request.META['HTTP_HOST']}", 'description': 'Main host'}]
        return Response(res)
```

**Comment by tfranzel** [comment]
currently, there is only a static list for `SERVERS` in the settings. by default there is no server section and SwaggerUI will use the host it was loaded from, which is basically what you patched in there by hand. also this wouldn't account for reverse proxies. 

what exactly is the benefit of doing that?

**Comment by grigandal625** [comment]
> currently, there is only a static list for `SERVERS` in the settings. by default there is no server section and SwaggerUI will use the host it was loaded from, which is basically what you patched in there by hand. also this wouldn't account for reverse proxies.
> 
> what exactly is the benefit of doing that?

This is useful when I develop the front and host it on a different port (like 3000).)

So I want to dynamically load the schema and generate the client-this action requires servers because my API is hosted on port 8000

**Comment by grigandal625** [comment]
I would also like to know what to use instead request.META['wsgi. url_scheme'] in case I deploy a django application using daphne, which does not give me this field in META

**Comment by tfranzel** [comment]
afaik serving SwaggerUI without the server section will not only use the serving host, but also use the port of the request it was made from.

i don't see what this adds to the default handling, which should already cover this.

**Comment by grigandal625** [comment]
> afaik serving SwaggerUI without the server section will not only use the serving host, but also use the port of the request it was made from.
> 
> i don't see what this adds to the default handling, which should already cover this.

@tfranzel it didn't work for me

i used [this generator](https://www.npmjs.com/package/openapi-client-axios) and it makes request on `/`, not on port of my django developing app

**Comment by tfranzel** [comment]
not sure if i can be of any further help here. closing this for now
