### ISSUE TITLE
Different schemas based on query parameters

### ISSUE THREAD

**Issue by saska** [tfranzel/drf-spectacular#344]
Hey,
I have a use case where I want to either 

a) return a url to a nested resource, i.e. the response would be

```
{
    "name": "example",
    "nested": "https://example.com/resources/2"
}
```

or b) fetch it in the same request with e.g. `?expand=true`

```
{
    "name": "example",
    "nested": {
        "there": "are",
        "more": "fields here"
    }
}
```

Is this possible? If it is, it's not obvious to me. I'm not sure openapi has a default way of dealing with this all that well either, but e.g. having `expand_schema` take an iterable of things to responses (i.e. `{200: (Serializer1, Serializer2)}` and creating an openapi `oneOf` would at least produce something valid that indicates there are multiple possible schemas.

**Comment by tfranzel** [comment]
hi @saska, we have a solution for this: `PolymorphicProxySerializer`.  however it is a bit more effort that a plain list like mentioned above.

https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-endpoints-use-different-serializers-depending-on-the-situation

https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.PolymorphicProxySerializer

**Comment by saska** [comment]
Hey! I assumed that `resource_type_field_name` needs to exist in the django model (or perhaps serializer output), is this not the case?

**Comment by tfranzel** [comment]
it does not need to be from the model. it can be a property on the serializer too. if you provide a dict instead of a list it is not even checked and taken at face value.

theoretically a simple `oneOf` (without the discriminator) could do here, but client generation would not be able to distinguish the cases. we left out this trivial solution to prevent holes in feet.

**Comment by tfranzel** [comment]
@saska added the feature to turn off the discriminator here: 8b9d0cafe856d6219cf4f5c4ab04bf5e9ca21268

https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.PolymorphicProxySerializer

> Setting `resource_type_field_name` to `None` will remove the discriminator altogether. This may be useful in certain situations, but will most likely break client generation.

i would consider this issue done now but feel free to comment if anything is missing.
