### ISSUE TITLE
Camelize serializer fields only in response, not in request body

### ISSUE THREAD

**Issue by smit2909** [tfranzel/drf-spectacular#346]
Hi, 

The camelize_serializer_fields post processing hook is actually camelizing request and response schema both. Is there a way to only camelize the response?

Regards,

**Comment by tfranzel** [comment]
hi @smit2909, `camelize_serializer_fields` is supposed to handle `djangorestframework_camel_case` behavior. afais the library is also all or nothing. however it should be rather easy to write a modified version, though this is outside the scope of core spectacular.

**Comment by smit2909** [comment]
Hi @tfranzel ,

Oh .okay, I am not sure if this is right platform to ask but could you point me in the right direction as to how shall I write this post processing hook myself?

Regards,

**Comment by tfranzel** [comment]
we have documentation that shall get you started.

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks

start from the existing hook and modify:

https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/contrib/djangorestframework_camel_case.py
