### ISSUE TITLE
Setting to exclude list of views?

### ISSUE THREAD

**Issue by mblayman** [tfranzel/drf-spectacular#348]
First, this is a great project! Thanks for helping make the lives of DRF developers better.

I work at Doctor On Demand, and we're working toward getting hundreds of REST endpoints into an OpenAPI schema. The team has a lot of `APIView` endpoints and other issues that generate hundreds of errors/warnings out of the `./manage.py spectacular` command.

I would love to enable `--fail-on-warn` early in the process to prevent any new errors and warnings from creeping into the generated output. Since we already have a lot of errors/warnings, that's a tricky proposition. I think I can make each endpoint use `@extend_schema(exclude=True)` to individually hide the other errors/warnings until we're ready to fix them (that dawned on me this Saturday morning when I'm writing this issue).

As a feature suggestion, it would be nice to exclude a list of endpoints via the settings. I think this would be quite a bit easier to manage than individually decorating each endpoint that is generating warnings.

I recognize that this is probably a niche use case for teams with a huge list of pre-existing endpoints that want to adopt this package. Thanks for some consideration!

**Comment by tfranzel** [comment]
hi @mblayman, thank you very much! 

the intended workflow was CLI runs and iterations till no warning are left and then have CI with that flag afterwards to prevent introduction of problems, but i can see that this does not map to everyone.

this would be indeed a niche feature. for those kind of things we have generic pre/post hooks: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-7-preprocessing-hooks . you can list all endpoints and then filter out the problemtic ones. we might even add that to the blueprints section in the docs.

**Comment by mblayman** [comment]
ok, thanks for the quick feedback! I figured it didn't hurt to ask. I'll check out the hooks and see what I can do.

I'll go ahead and close this issue. As a maintainer myself, I often feel burdened with feature requests and some level of guilt for not implementing things. I don't want to add to your plate needlessly.

**Comment by tfranzel** [comment]
we have a similar hook in the package. it removes `{format}` suffix endpoint duplicates. from there and the example above you shouldn't have much trouble.

https://github.com/tfranzel/drf-spectacular/blob/cb810dbe90caf52b876efdf607cac7eba60f63bb/drf_spectacular/hooks.py#L146
