### ISSUE TITLE
Not working properly if not installed on top of drf-yasg

### ISSUE THREAD

**Issue by acedia3** [tfranzel/drf-spectacular#349]
So I tried migrating from drf-yasg to spectacular. It worked great when used to top of `drf-yasg` like so:

```
    # drf-yasg
    path('schema/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema'),
    # drf-spectacular
    path('swagger/', SpectacularSwaggerView.as_view(), name='swag'),
```

But when my `schema/` endpoint is set to be the one from spectacular (like shown in the documentation), the whole UI is messed up: it won't detect apps and split endpoints into categories (they become grouped under 'api' tag), the schemas for custom `@action` are wrong as well (but fine with drf-yasg). The weird thing is that when used 'on top of drf-yasg' so to speak, it fixes all the issues I had with yasg, but without it it just won't function.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/75124544/112725592-cd4a3600-8f3a-11eb-984d-05985950b8ed.png">

my `settings.py`

```

INSTALLED_APPS = [
    'huey.contrib.djhuey',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'drf_yasg',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'apps.users.apps.UsersConfig',
    'apps.achievements.apps.AchievementsConfig',
    'apps.events.apps.EventsConfig',
    'apps.landing.apps.LandingConfig',
    'drf_spectacular',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES'    : [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES'      : [],
    'DEFAULT_THROTTLE_RATES'        : {
        'throttle_per_day'   : '10000/day',
        'throttle_per_hour'  : '1000/hour',
        'throttle_per_minute': '30/min',
    },
    'DEFAULT_FILTER_BACKENDS'       : [
        'django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS'      : 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE'                     : 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

SPECTACULAR_SETTINGS = {
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
}

```

my `urls.py` is set up according to the drf-spectacular docs (which basically is the cause of the problem from what I see):

```

api_urlpatterns = [
    path('users/', include(user_router.urls)),
    path('achievements/', include(achievement_router.urls)),
    path('events/', include(event_router.urls)),
    path('landing/', include(landing_router.urls)),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('schema/swagger-ui/',
         SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'),
         name='redoc'),

]


urlpatterns += [path('api/', include(api_urlpatterns))]

```

**Comment by acedia3** [comment]
Tried: full uninstall of drf-yasg with following code base cleanup from it's code usage

**Comment by tfranzel** [comment]
hi. yasg and spectacular should have no interaction whatsoever.

you are aware that the yasg decorators do not work for spectacular? we have similar but different decorators:

https://drf-spectacular.readthedocs.io/en/latest/drf_yasg.html

if tagging does not work as expected you should set a prefix with `SCHEMA_PATH_PREFIX`:  https://drf-spectacular.readthedocs.io/en/latest/settings.html


sidenote: you should turn this of when both SPLIT options are active.
```'COMPONENT_NO_READ_ONLY_REQUIRED': True,```

**Comment by acedia3** [comment]
> hi. yasg and spectacular should have no interaction whatsoever.
> 
> you are aware that the yasg decorators do not work for spectacular? we have similar but different decorators:
> 
> https://drf-spectacular.readthedocs.io/en/latest/drf_yasg.html
> 
> if tagging does not work as expected you should set a prefix with `SCHEMA_PATH_PREFIX`: https://drf-spectacular.readthedocs.io/en/latest/settings.html
> 
> sidenote: you should turn this of when both SPLIT options are active.
> `'COMPONENT_NO_READ_ONLY_REQUIRED': True,`

Hey! Thanks a lot, it seems like I misunderstood what 'SCHEMA_PATH_PREFIX' does. It fixed the grouping issue.
