### ISSUE TITLE
Add get_schema_view() function for create Schema view for different endpoints

### ISSUE THREAD

**Issue by Mopsan** [tfranzel/drf-spectacular#35]
In drf_yasg I can create different schema views for different endpoints. Can you implement the same functionality?

`from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version="v1",
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
)

urlpatterns = [
   url(r"^swagger(?P<format>\.json|\.yaml)$", schema_view.without_ui(cache_timeout=0), name="schema-json"),
]`

**Comment by MissiaL** [comment]
We are also exploring this issue here https://github.com/tfranzel/drf-spectacular/issues/22

**Comment by tfranzel** [comment]
@MissiaL sry that #22 is taking so long. it is a bit more complicated than anticipated. i'm working on it and have it almost done. 

@Mopsan: i believe we can accommodate that once #22 is there.

**Comment by Mopsan** [comment]
@tfranzel #22 describes the need for different versions:
Ex:
api/v1/test-app
api/v2/test-app

If need to create multiple applications with schema with the same version, how to proceed?
Ex:
api/v1/example-1-app
api/v1/example-2-app

**Comment by tfranzel** [comment]
i don't yet completely understand what you are after.

- we have a schema serving view: https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/views.py
- if you don't use versioning, ``v1`` is just a static path and everything should work.
- do you want to serve a subset of the schema? that can be done with https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/settings.py#L17
- or do you want to serve multiple subsets of the API?

**Comment by Mopsan** [comment]
@tfranzel I want to serve multiple subsets of the API

**Comment by tfranzel** [comment]
now i understand. we need to add a parameter to SpectacularApiView. then you can manually set each subset with its own URLCONF. good catch, i'll do it.

**Comment by tfranzel** [comment]
@Mopsan that should do it for you. have a look at 

https://github.com/tfranzel/drf-spectacular/blob/1016850dab17f0a4193186a2502861479f23dfdb/tests/test_view.py#L20-L25

on how to use it. the test uses it for "version" but you can use it for your case too.

@MissiaL: nowwe have at least a "ghetto" versioning until we can do it right in #22

**Comment by Mopsan** [comment]
@tfranzel ooh, that's looks good, thank you very much
