### ISSUE TITLE
extend_schema modifies passed callable 

### ISSUE THREAD

**Issue by saska** [tfranzel/drf-spectacular#352]
When passing a callable to the decorator returned by `utils.extend_schema` the callable itself gets modified. This is bad if that callable is inherited or otherwise reused, which can become an issue when e.g. modifying classes after declaration.

If I have a subclass `MyViewSet` of `rest_framework.viewset.GenericViewSet` which does not define `.list` and I call `extend_schema(**kwargs)(MyViewSet.list)`, `rest_framework.mixins.ListModelMixin.list` (which might be used by many others) gets modified, leading to weirdess that could be avoided if a temporary callable like the original was created before modification & return.

**Comment by tfranzel** [comment]
apart from that i would argue that using `extend_schema_view` is cleaner anyway. nobody prevents your from explicitly using the decorators but your mileage may vary as you are circumventing a few safeguards.

**Comment by saska** [comment]
When decorating classes outside of where they're defined (or if they're dynamically defined with `type`), the syntax becomes `viewset = extend_schema_view(list=extend_schema(**kwargs))(viewset)`, which does work. It's not immediately obvious to me what the line does though. I'd at least document this behaviour (+ that it modifies the callable) and warn against using it as a non-decorator. The assumption tends to be that decorating with `@` is syntactic sugar without any behavioural gotchas - here it happens to ensure that the function is actually defined on the class.

**Comment by tfranzel** [comment]
> I'd at least document this behaviour (+ that it modifies the callable) and warn against using it as a non-decorator.

yes probably a good idea.

> When decorating classes outside of where they're defined, 

just in case you didn't know. we have `OpenApiViewExtension` exactly for the purpose of patching views that are buried in inaccessible library code:  https://drf-spectacular.readthedocs.io/en/latest/customization.html#replace-views-with-openapiviewextension .  does not not work for dynamically defined `type` views though.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
