### ISSUE TITLE
get django-filter filters inside postprocessing hook.

### ISSUE THREAD

**Issue by aristidebm** [tfranzel/drf-spectacular#354]
# Access django-filter filters names inside a post-processing hook.

Want to know if it is possible to access django-filter filters inside drf_spectacular `post-processing hook`. I have checked the `result` dict but can't find filters inside. Need some help if it is possible.

**Comment by tfranzel** [comment]
the postprocessing hooks receive the already rendered schema. parameters must therefore also be in there.

**Comment by aristidebm** [comment]
OK! Thanks
