### ISSUE TITLE
djangorestframework-camelcase support

### ISSUE THREAD

**Issue by sayeghr** [tfranzel/drf-spectacular#355]
I use djangorestframework-camelcase but the example JSON responses on drf-spectacular is showing the responses in snake case. The readme for the project states that djangorestframework-camelcase is supported. Is there something specific I need to do to turn on that support?

**Comment by tfranzel** [comment]
yes, you need to explicitly enable this by adding the hook to the `POSTPROCESSING_HOOKS` setting.

```python
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
    ],
```


apart from that you may also use `'CAMELIZE_NAMES': True` for consistency.

**Comment by tfranzel** [comment]
This is a setting like the hooks. The documentations contains more details

https://drf-spectacular.readthedocs.io/en/latest/settings.html

**Comment by sayeghr** [comment]
Oh, thanks! I actually put them in the REST_FRAMEWORK dict and it seemed to work. I'll move it over to the spectacular settings instead. Appreciate the help.
