### ISSUE TITLE
ReDoc generation does not understand MinValueValidator with Decimals

### ISSUE THREAD

**Issue by AlexDaniel** [tfranzel/drf-spectacular#357]
**Describe the bug**
When using `MinValueValidator(Decimal('0.01'))` redoc generation fails with:

```
yaml.representer.RepresenterError: ('cannot represent an object', Decimal('0.01'))
```

Same issue with MaxValueValidator, obviously.

**To Reproduce**
Add a MinValueValidator to any field:
```python
amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01')), MaxValueValidator(1_000)])
```
_(Unrelated to this ticket: yes, in that example max_digits allows a lot more than what MaxValueValidator allows, API docs should use the value in MaxValueValidator instead.)_

**Expected behavior**
Should just work. Swagger output has no issues and the validators are interpreted correctly:
![image](https://user-images.githubusercontent.com/5507503/113461358-ec5a3380-9424-11eb-8d36-01dfb713133d.png)

**Comment by tfranzel** [comment]
the yaml serialization issue should have been fixed in `0.14.0`. can you conform you are using the latest version?

**Comment by AlexDaniel** [comment]
@tfranzel yes, using 0.14.0.

```
[[package]]
name = "drf-spectacular"
version = "0.14.0"
description = "Sane and flexible OpenAPI 3 schema generation for Django REST framework"
category = "main"
optional = false
python-versions = ">=3.6"
```

**Comment by AlexDaniel** [comment]
Sorry, actually my dependencies were stuck a bit. It does work now! Thank you ♥
