### ISSUE TITLE
Empty security schema for action views

### ISSUE THREAD

**Issue by tobiwankenobii** [tfranzel/drf-spectacular#361]
**Describe the bug**
There is an empty object (`- {}`) in security definitions for `action` views.

**To Reproduce**
I have such viewset:
```python
class SomeViewSet(viewsets.ViewSet):
    """Foo."""

    serializer_class = None

    @extend_schema(responses={(200, "application/json"): SomeSerializer})
    @action(detail=False)
    def baz(self, request: Request) -> Response:
        """Baz."""
        return Response({"xyz": True)
```
And some auth class in set as default in settings:
```
"DEFAULT_AUTHENTICATION_CLASSES": ("path.to.MyAuthentication",),
```
Of course there is `OpenApiAuthenticationExtension` created for this class (and it works properly).

**Expected behavior**
Security section in schema.yml should look like this:
```
security:
  - myAuth: []
```
But for some reason it looks like so:

```
security:
  - myAuth: []
  - {}
```
I have tons of other views but this happens only for those with `@action` decorator.
A workaround for this is to extend the `auth` for the view:
```python
@extend_schema(responses={(200, "application/json"): SomeSerializer}, auth=[{"myAuth": []}])
```
But it's not a very "satisfying" one.
Am I doing anything wrong?

**Comment by tfranzel** [comment]
Hi! so `{}` means basically no auth required and for your case it means: "request may be auth'ed with `myAuth` or unauthed". this has nothing to do with the auth method itself but rather the permissions (and method in some cases).

https://github.com/tfranzel/drf-spectacular/blob/8496012dad60406ef3b8e23199b397a186c3aa07/drf_spectacular/openapi.py#L259-L263

these are the conditions that are somehow met for you. it has little to do with `action`, it might just be just accidental.

**Comment by tobiwankenobii** [comment]
`If not specified, this setting defaults to allowing unrestricted access:`
```
'DEFAULT_PERMISSION_CLASSES': [
   'rest_framework.permissions.AllowAny',
]
```
darnit, didn't notice permission class defaulted after i removed the custom one...
thanks for the hint tho! issue can get closed

**Comment by tfranzel** [comment]
sure thing. it's nice to discover bugs/discrepancies by having an unexpected schema. actually found a couple of bugs myself that way.
