### ISSUE TITLE
Allow PolymorphicProxySerializer to used with @extend_schema_field

### ISSUE THREAD

**Issue by jtsay362** [tfranzel/drf-spectacular#362]
In a serializer I want have a field that has different shapes depending on the value of a column. I want to do this:

 
```
class TaskSerializer(serializers.HyperlinkedModelSerializer):
    @extend_schema_field(PolymorphicProxySerializer(
          component_name='ExecutionMethodCapability',
          serializers=cast(dict[str, Union[serializers.Serializer, Type[serializers.Serializer]]], {
              'AWS ECS': AwsEcsExecutionMethodCapabilitySerializer,
              'Unknown': UnknownExecutionMethodCapabilitySerializer
          }),
         resource_type_field_name='type'
    ))
    
    def get_execution_method_capability(self, obj: Task):
          if obj.type == 'AWS ECS':
               return AwsEcsExecutionMethodCapabilitySerializer(obj).data
          ...
```

Curiously, extend_schema_field takes a PolymorphicProxySerializer as the first argument, but when I run schema generation,
I get:

```
Got TaskViewSet: TaskSerializer: unable to extract field metadata from
field "<drf_spectacular.utils.PolymorphicProxySerializer object at
0xdeadbeef>" because it appears to be neither a Field nor a
Serializer. Proper handling may require an Extension or
@extend_schema_field. Skipping metadata extraction.
```

Am I using the library incorrectly? Or is this something that you want to support in the future?

Thanks as always for this great tool.

**Comment by tfranzel** [comment]
hey @jtsay362, actually this is supported, it just throws an incorrect warning. if you look at the schema, it should be as expected. 

when you decorate a field class directly there is no warning (in the tests). this particular case when decorating a `serializermethodfield` method slipped through wrt the warnings. should be an easy fix. +98% coverage and still cases slipping through :disappointed:

**Comment by jtsay362** [comment]
Actually it doesn't seem to work for me. The OpenAPI yml generated has references to ExecutionMethodCapability like this:

```
        execution_method_capability:
          allOf:
          - $ref: '#/components/schemas/ExecutionMethodCapability'

```

But ExecutionMethodCapability is not defined in components.schemas. When Swagger UI and ReDoc display the execution_method_capability, they says the type is a simple string.

**Comment by tfranzel** [comment]
62874de fixes some special cases wrt ``PolymorphicProxySerializer``

> But ExecutionMethodCapability is not defined in components.schemas.

i was unable to reproduce a missing component though. however, the fix may have also fixed your problem. let me know if it is resolved. otherwise we have to dig deeper.

**Comment by jtsay362** [comment]
It works with https://github.com/tfranzel/drf-spectacular/commit/8b9d0cafe856d6219cf4f5c4ab04bf5e9ca21268 (latest commit as of now)! I tried both using a discriminator map:

```
    @extend_schema_field(PolymorphicProxySerializer(
          component_name='ExecutionMethodCapability',
          serializers=cast(dict[str, Union[serializers.Serializer, Type[serializers.Serializer]]], {
              'AWS ECS': AwsEcsExecutionMethodCapabilitySerializer,
              'Unknown': UnknownExecutionMethodCapabilitySerializer
          }),
          resource_type_field_name='type'
    ))
```

and a list of Serializers:

```

 @extend_schema_field(PolymorphicProxySerializer(
          component_name='ExecutionMethodCapability',
          serializers=cast(list[Union[serializers.Serializer, Type[serializers.Serializer]]], [
              AwsEcsExecutionMethodCapabilitySerializer,
              UnknownExecutionMethodCapabilitySerializer
          ]),
          resource_type_field_name='type'
    ))
```

And they both result in 

```
    ExecutionMethodCapability:
      oneOf:
      - $ref: '#/components/schemas/AwsEcsExecutionMethodCapability'
      - $ref: '#/components/schemas/UnknownExecutionMethodCapability'
      discriminator:
        propertyName: type
        mapping:
          AWS ECS: '#/components/schemas/AwsEcsExecutionMethodCapability'
          Unknown: '#/components/schemas/UnknownExecutionMethodCapability'
```

which exactly what I hoped. Redoc looks good too, though a bit confusing (there's a dropdown for the type that is buried within the properties of AwsEcsExecutionMethodCapability).

Thank you so much for fixing this! I'll be using PolymorphicProxySerializers quite a bit!

**Comment by tfranzel** [comment]
awesome! that last commit now also allows you to the drop discriminator by setting `resource_type_field_name=None` as an option. for good client generation, it is however required to have a discriminator.

indeed, redoc displays this information somewhat hidden and convoluted but at least its there.
