### ISSUE TITLE
SpectacularAPIView return yaml by default please change at next build for redoc implement.

### ISSUE THREAD

**Issue by bboyadao** [tfranzel/drf-spectacular#363]
I got an error.
<img width="1366" alt="Screen Shot 2021-04-09 at 16 42 16" src="https://user-images.githubusercontent.com/25122065/114162118-ff07c780-9952-11eb-8fcb-f6c4e82821d6.png">

Then i found this on template.
<img width="1016" alt="Screen Shot 2021-04-09 at 16 42 28" src="https://user-images.githubusercontent.com/25122065/114162146-04651200-9953-11eb-925f-a0a81d4bdc3f.png">
I add format query then it's work. But i don't think this is the good way
<img width="1020" alt="Screen Shot 2021-04-09 at 16 42 48" src="https://user-images.githubusercontent.com/25122065/114162388-40987280-9953-11eb-9456-ab1a3bc51f26.png">

**Comment by tfranzel** [comment]
hi @bboyadao, very interesting. this has worked flawlessly for a long time, but i have not tested it recently. their README says this:

> specOrSpecUrl is either JSON object with specification or an URL to the spec in JSON or YAML format

so this should work for the default YAML response. i will have a look. its either an upstream bug or they changed their interface.

**Comment by tfranzel** [comment]
redoc released `v2.0.0-rc.52` which fixes the regression.
