### ISSUE TITLE
Spectacular returns empty schema

### ISSUE THREAD

**Issue by abreumatheus** [tfranzel/drf-spectacular#366]
**Describe the bug**
I followed all the instructions in the doc, set `drf_spectacular` in installed_apps and added the `DEFAULT_SCHEMA_CLASS`, but when i try to generate the schema via CLI or using the provided views it just returns/serves an empty yaml or a redoc page with no endpoints.

```yaml
openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths: {}
components: {}

```

**To Reproduce**
Just follow the basic instructions on the readme, with Django 3.2 and DRF 3.12.4.

**Expected behavior**
Working schema generation.

**Comment by tfranzel** [comment]
it could very well be be versioning. can you check this comment here?

https://github.com/tfranzel/drf-spectacular/issues/364#issuecomment-818776038

**Comment by abreumatheus** [comment]
@tfranzel Thanks, man! That was it. Maybe we should add this to the docs, cause versioning apis is very common.
