### ISSUE TITLE
input request on schema generator shadows actual required request

### ISSUE THREAD

**Issue by sergei-maertens** [tfranzel/drf-spectacular#370]
https://github.com/tfranzel/drf-spectacular/blob/8b9d0cafe856d6219cf4f5c4ab04bf5e9ca21268/drf_spectacular/generators.py#L185

Note that this is untested on the current master branch, but I believe the same problem exists since the method signature hasn't really changed from 0.12.0 (which I'm on):

```py
def parse(self, request, public):
        """ Iterate endpoints generating per method path operations. """
        result = {}
        self._initialise_endpoints()

        for path, path_regex, method, view in self._get_paths_and_endpoints(None if public else request):
            if not self.has_view_permissions(path, method, view):
                continue

            # mocked request to allow certain operations in get_queryset and get_serializer[_class]
            # without exceptions being raised due to no request.
            if not request:
                request = spectacular_settings.GET_MOCK_REQUEST(method, path, view, request)

            view.request = request
```

This is causing our generated API spec (interactively) to be wrong, because of the different request serializer class based on HTTP method:

```py
    def get_serializer(self, *args, **kwargs):
        if self.request.method == "PATCH":
            return UpdateZaakDocumentSerializer(*args, **kwargs)
        return AddZaakDocumentSerializer(*args, **kwargs)
```

When you generate the schema from the CLI, a mock request is present with the correct method, from:

```py
for path, path_regex, method, view in self._get_paths_and_endpoints(None if public else request):
```

However, if you are using the schema view (hooked up in `urls.py`), then `request` in 

```py
def parse(self, request, public):
```
is actually the GET request to `/api` in our case, i.e. the request that fetches/renders the schema.

So, we have a mismatch here, because of:

```py
            if not request:
                request = spectacular_settings.GET_MOCK_REQUEST(method, path, view, request)

            view.request = request
```

-> `method` is `PATCH`, but `request.method` is `GET`

This causes the API schema to pick up the `AddZaakDocumentSerializer` instead of the `UpdateZaakDocumentSerializer`. Of course, we can fix this with `@extend_schema`, but that's a bit of a shame.

Is there a reason we cannot always use the mock request for schema generation?

**Comment by sergei-maertens** [comment]
Looks like #250 might fix this, I'll try it out first

**Comment by tfranzel** [comment]
most recent release should also be fine for testing this, as master does not contain any related changes.

at least it looks like #250 addressed this issue. i believe there are still ways to break it so we may have to still iterate.

**Comment by sergei-maertens** [comment]
Tested on 0.15.1 and this version does not fix it, unfortunately :( it is using the `input_request` instead.

**Comment by sergei-maertens** [comment]
It's a tricky one, since you want the input request with the actual authenticated user if you only want to display API documentation they have access to.

Perhaps you could grab the `input_request`, clone it, and alter the relevant attributes: `method` and `path`?

**Comment by tfranzel** [comment]
haha, wishful thinking didn't help. :smile: 

> Perhaps you could grab the input_request, clone it, and alter the relevant attributes: method and path?

the solution is most likely something to that effect. i'll also look into it.


fyi: you should update in any case as we had dozens of fixes/features since `0.12.0`

**Comment by sergei-maertens** [comment]
I've edited by previous comment, but it seems that we're roughly on the same line :)

> fyi: you should update in any case as we had dozens of fixes/features since 0.12.0

done that just now, and it went pretty smooth thanks to `swagger_fake_view` :)

**Comment by tfranzel** [comment]
@sergei-maertens the change was a bit more involved, but overall reduced complexity imho. this should now behave exactly as one would supect.

- `GET_MOCK_REQUEST` is now always called no matter what. 
- most headers are carried over
- authenticated user is carried over

please check if that works for you.

**Comment by tfranzel** [comment]
@sergei-maertens did you have time to give this a try? i would like to have someone else check this before i do a release.

**Comment by sergei-maertens** [comment]
I haven't had time yet! Maybe next week I can try it out, but no guarantees since I'm involved with other projects atm :P

**Comment by sergei-maertens** [comment]
@tfranzel just checked out 0.16.0 locally and it appears to work as intended! I'll create a new issue if I spot any new bugs :)
