### ISSUE TITLE
Request and request_only examples are not generated

### ISSUE THREAD

**Issue by DeSerg** [tfranzel/drf-spectacular#371]
Hello!

I am trying to describe a request with a Serializer class and it seems to not to be generated. The same appears when I am adding and OpenApiExample with request_only set to True.

```
class MySerializer(serializers.ModelSerializer)
  field1 = serializers.CharField()
  field2 = serializers.IntegerField()

  class Meta:
    model = models.MyModel
    fields = ('field1', 'field2')

@extend_schema(
  request=MySerializer,
  examples=[
    OpenApiExample(
      'Request',
      value={'field1': 'blah', 'field2': 123},
      request_only=True,
   )]
)
def patch(self, request, pk):
  return Response()
```

With this extend_schema example I am expecting Request section of the method to contain MySerializer information and example described by OpenApiExample. But Request section is not there at all.

Thank you very much!

**Comment by tfranzel** [comment]
hi! does `MySerializer` only have `write_only` fields? then the response is empty by definition. are you sure you want `responses=MySerializer,`? looks like you much rather want `request=MySerializer, responses=MySerializer`.

**Comment by DeSerg** [comment]
I am sorry, I messed up the words Response and Request. Edited the issue. The question is about a Request, not about Response, Response works just fine.

**Comment by tfranzel** [comment]
testing this worked fine for me 

```python
    class MySerializer(serializers.ModelSerializer):
      field1 = serializers.CharField()
      field2 = serializers.IntegerField()

      class Meta:
        model = SimpleModel
        fields = ('field1', 'field2')

    class XViewset(generics.GenericAPIView):
        @extend_schema(
          request=MySerializer,
          examples=[
            OpenApiExample(
              'Request',
              value={'field1': 'blah', 'field2': 123},
              request_only=True,
           )]
        )
        def patch(self, request, pk):
            return None
```

since your example was imcomplete i can't tell for sure but it seems to be this problem: https://drf-spectacular.readthedocs.io/en/latest/faq.html#using-extend-schema-on-apiview-has-no-effect

for `ViewSet` you must annotate `partial_update` and for `APIView` based views its `patch`. that would be my best guess as this usually works perfectly.
