### ISSUE TITLE
Missing documentation for handling annotations in QuerySet?

### ISSUE THREAD

**Issue by mblayman** [tfranzel/drf-spectacular#372]
This might be more of a discussion than a  problem so I apologize if this is the wrong forum for this topic. I also have to keep this a bit vague on the details because this is proprietary code, but I'll do my best to rename things appropriately. Anyway, here's the situation:

I'm working on one of my company's `ListAPIView`s and trying to resolve warnings related to fields added with `MyModel.objects.annotate(...)` in the `get_queryset` method. This is an example warning.

```
Warning #0: SomeListAPIView: could not resolve field on model <class 'app.models.TheModel'>
with path "some_annotated_name".
This is likely a custom field that does some unknown magic. Maybe consider annotating the field/property?
Defaulting to "string". (Exception: TheModel has no field named 'some_annotated_name')
```

A sketch of the code is roughly like:

```python
class SomeSerializer(serializers.Serializer):
    some_annotated_name = serializers.IntegerField()
    # other fields

class SomeListAPIView(ListAPIView):
    queryset = TheModel.objects.none()
    serializer_class = SomeSerializer
    # other irrelevant attributes

    def get_queryset(self):
        # Some code here that drf-spectacular can't resolve
        # because the db data isn't right at schema generation time.
        return TheModel.objects.annotate(some_annotated_name=Subquery(...))
```

I've read through all the documentation and I'm unclear on what the best solution available is for this situation. I *think* the best (only?) option available to me is to switch the `IntegerField` to a `SerializerMethodField` and decorate the serializer method with `extend_schema_field`.

Does this sound accurate? Is there some to override the `IntegerField` that I'm not aware of. I appreciate consideration of this more complicated view scenario.

**Comment by mblayman** [comment]
Follow up: there might be a bug related to this stuff. I tried to go ahead with the `SerializerMethodField` idea and got the same warning. I confirmed with the unit tests that this was, behaviorally, the same functional code. Here is the updated serializer (reworded to match the example):

```python
class SomeSerializer(serializers.Serializer):
    some_annotated_name = serializers.IntegerField()

    @extend_schema_field(OpenApiTypes.INT)
    def get_some_annotated_name(self, obj: TheModel) -> int:
        """Get the some annotated name.

        This method is necessary because some_annotated_name is an annotation
        and spectacular can't determine the type for the OpenAPI schema.
        """
        return obj.some_annotated_name
```
I've not stepped through the schema generation to determine why method field decorator is seemingly ignored, but I plan to do that next.

**Comment by tfranzel** [comment]
hi! i'm afraid you abstracted away the actual problem. that warning is generated by `follow_field_source()` which is only called for `serializers.PrimaryKeyRelatedField` and `serializers.ReadOnlyField` (or with `django-filter`). the code should never be able to get there for `IntegerField`. generally, we try to avoid calling `get_queryset` unless its absolutely necessary.

can you leak a bit more info? i can't really give good advice just based on the available info.

is `some_annotated_name` generated automatically from a `ModelSerializer` an not really a `IntegerField`?

sidenote: you can prevent get_queryset from throwing with this trick, but i guess this will not solve the issue at hand.
```python
    def get_queryset(self):
        if getattr(self, 'swagger_fake_view', False):
             return TheModel.objects.none()
        return TheModel.objects.annotate(some_annotated_name=Subquery(...))
```

**Comment by mblayman** [comment]
Oops... sorry! I didn't write this particular API so I'm trying to get the relevant details to the best of my understanding.

> is `some_annotated_name` generated automatically from a `ModelSerializer` an not really a `IntegerField`?

No, `some_annotated_name` is an actual `IntegerField` on the serializer.

I can add that `django-filter` *is* used in this case. Here's a more expanded view of the view:

```python
class SomeFilter(django_filters.rest_framework.FilterSet):
    some_annotated_name = django_filters.NumberFilter(field_name='some_annotated_name')
    # other filter fields

class SomeListAPIView(ListAPIView):
    queryset = TheModel.objects.none()
    serializer_class = SomeSerializer
    filter_backends = [OrderingFilter, django_filters.rest_framework.DjangoFilterBackend]
    filter_class = SomeFilter
    # other irrelevant attributes

    def get_queryset(self):
        # Some code here that drf-spectacular can't resolve
        # because the db data isn't right at schema generation time.
        return TheModel.objects.annotate(some_annotated_name=Subquery(...))
```
Thanks for your flexibility as I'm forced to obfuscate the real code. Hopefully, I've got enough of the real details captured now.

**Comment by tfranzel** [comment]
hehe, well thats a whole different issue now and i understand where the warning is coming from. `get_queryset` is called because `NumberFilter` is partially underspecified by definition. the code is trying to get the exact type of `NumberField` and defaults to basic number, due to the exception. 

schema wise that should be only a minor inconvenience as its already pretty close. the warning is pesky though.

you may bypass that code path by going the method route instead. not a fan of changing hot code paths but it is all i can offer at the moment. this is also covered in the test for `django-filter`

```python
class SomeFilter(django_filters.rest_framework.FilterSet):
    some_annotated_name = django_filters.NumberFilter(method='filter_method_typed')
    # other filter fields

    # this int annotation below is picked up by spectacular
    def filter_method_typed(self, queryset, name, value: int):
        return queryset.filter(some_annotated_name=value)

```

**Comment by mblayman** [comment]
Thank you for going above and beyond with looking at this. What you've described makes good sense to me. Is there anything worth documenting here? I could craft a PR if you're interested, but I don't know if you think this is worth highlighting anywhere.

If there's nothing to add, I can close out the issue.

**Comment by tfranzel** [comment]
sure, no problem. generally a good idea to document those things but it seems rather special and i wouldn't even know where to put it. FAQ maybe if you would like to do it. you can close the issue if you want.

**Comment by mblayman** [comment]
Yeah, I thought about this more, and I agree that it's probably too specific to document. Hopefully, there are enough breadcrumbs in this issue thread for anyone else who may run into a similar problem in the future.
