### ISSUE TITLE
Add / update OA endpoint for intellij

### ISSUE THREAD

**Issue by Goldziher** [tfranzel/drf-spectacular#376]
Hi there,

Recently I tried setting up intellij idea to consume OA docs from the generic schema endpoint provided by drf-spectacular.  Although I can download the schema file correctly,  intellij is not able to read the specs from the OA URL. I assume intellij is expecting a json response, but its getting  multipart or octet stream etc. I would therefore like to ask that either the implementation of the endpoint is updated or is made more easily configurable. 

Here are the pertinent intellij docs: https://www.jetbrains.com/help/idea/openapi.html

**Comment by Goldziher** [comment]
I'll give it a go 😃

**Comment by Goldziher** [comment]
Hmm, neither of these work with intellij. I don't think its on this package though - afaik you are providing all the functionalities that should be there.

**Comment by tfranzel** [comment]
i just confirmed that above example really does what i claimed it does. in my experience new jetbrains features often are a bit flaky in the  beginning.

i'll close this issue as everythings works as expected. feel free to circle back though if anything is missing.
