### ISSUE TITLE
Swagger execute button not working

### ISSUE THREAD

**Issue by LondonAppDev** [tfranzel/drf-spectacular#377]
**Describe the bug**
When I have a read only field set in my ModelSerializer, the **Execute** button becomes unresponsive when testing the API in the Swagger site.

**To Reproduce**
I've created a full Django project demonstrating the issue here: [github.com/LondonAppDev/Swagger-Execute-Issue](https://github.com/LondonAppDev/Swagger-Execute-Issue).

To re-produce, clone that project and run the follow:

**If using Docker Compose**

```shell
docker-compose up
```

**If running directly on your machine**

Ensure Python 3.9 is installed and run the following:

```shell
python -m venv env
source env/bin/activate
pip install -r requirements.txt
python app/manage.py migrate
python app/manage.py runserver 0.0.0.0:8001
```

Once running, follow the steps below:

 1. Navigate to [http://127.0.0.1:8001/api/docs/#/sample/sample_create](http://127.0.0.1:8001/api/docs/#/sample/sample_create)
 2. Select **Try it out**
 3. Choose **multipart/form-data** from the dropdown
 4. Enter a value in `description`
 5. Click **Execute**

The problem occurs when using this serializer:

```python
class SampleSerializer(serializers.ModelSerializer):
    """Sample serializer to demonstrate issue."""

    class Meta:
        model = models.SampleModel
        fields = ['id', 'description']
        read_only_fields = ['id']
```

If I change it to this, the problem goes away:

```python
class SampleSerializer(serializers.ModelSerializer):
    """Sample serializer to demonstrate issue."""

    class Meta:
        model = models.SampleModel
        fields = [''description']
```

**Expected behaviour**

Should be able to hit Execute to test the API

Thank you for taking time to read this.

**Comment by tfranzel** [comment]
hi @LondonAppDev,

yes that looks like a bug, but you're barking up the wrong tree. :smile: the request is simply not going out for multipart, which is entirely in the realm of swagger-ui. i found a related issue there: swagger-api/swagger-ui/issues/6250


i just saw that you created swagger-api/swagger-ui/issues/7242 so you found out yourself apparently

**Comment by LondonAppDev** [comment]
Hey @tfranzel

Thanks for the response and for sharing that other issue. 

Yes, I did more testing this morning and discovered the bug is with swagger-ui and not drf-spectacular. I was just about to close off this ticket :)

Cheers,
Mark
