### ISSUE TITLE
Support for Polymorphic Lists

### ISSUE THREAD

**Issue by avere001** [tfranzel/drf-spectacular#382]
I have tried this a few ways, but there seems to be no way to get polymorphic lists. For example, I can't find a way to document the content property of something like this:

```json
{
  "type": "page",
  "content": [
    {
      "type": "article",
      "title": "...",
      "body": "..."
    },
    {
      "type": "image",
      "url": "...",
      "alt_text": "..."
    }
  ]
}
```

For me, the natural thing was to annotate the field with `PolymorphicProxySerialzier(many=True, ...)` but that doesn't work.

Is there any way to do this without using django-polymorphic / django-rest-polymorphic?

**Comment by tfranzel** [comment]
hi!

> Is there any way to do this without using django-polymorphic / django-rest-polymorphic?

that is exactly the purpose of `PolymorphicProxySerializer`. it simulates what those libraries would do without having to use them. as a matter of fact you wouldn't use `PolymorphicProxySerializer` with those libraries, as instances of `PolymorphicSerializer` would get picked up automatically.

regarding your question. if the field is readOnly this is the easiest solution:

https://github.com/tfranzel/drf-spectacular/blob/1f7cf5d8342f5ed3f619afcf92fb43e3b4ff26cb/tests/test_polymorphic.py#L122

for read/write, you have to subclass the field and annotate that class. a `pass` will suffice as you just need something to attach the annotation to.

https://github.com/tfranzel/drf-spectacular/blob/1f7cf5d8342f5ed3f619afcf92fb43e3b4ff26cb/tests/test_polymorphic.py#L98

sidenote:
maybe we could extend `extend_schema_serializer` to additionally allow field overrides. that would eliminate that awkward annotation exercise. definitely something to look into.

**Comment by avere001** [comment]
Hi @tfranzel, thank you for the response.

The example you gave me only works when a single object is being returned, e.g.:
```python
@extend_schema_field(
    PolymorphicProxySerializer(
        component_name='MetaPerson',
        serializers=[LegalPersonSerializer, NaturalPersonSerializer],
        resource_type_field_name='type',
    )
)
def get_field(self, request):
    return LegalPersonSerializer(...).data. # or NaturalPersonSerializer(...).data
```

What I want is the schema for a list of objects of varying types being returned such as below:
```python
@extend_schema_field(
    PolymorphicProxySerializer(
        component_name='MetaPerson',
        serializers=[LegalPersonSerializer, NaturalPersonSerializer],
        resource_type_field_name='type',
        many=True,  # <--- This doesn't work
    )
)
def get_field(self, request):
    return [
        LegalPersonSerializer(...).data,
        NaturalPersonSerializer(...).data,
        ...
    ]
```

**Comment by greenled** [comment]
I'm looking for a solution to this problem too

**Comment by tfranzel** [comment]
@avere001 now i get where you are coming from. this is indeed a missing feature. 

now that i think of it there are ways to get `PolymorphicProxySerialzier` into "many mode" (via annotation of a viewsets's `list`) but there is currently no way to do it explicitly. certainly an unnecessary limitation.

good catch! i'll figure something out.

**Comment by avere001** [comment]
Cool, thank you @tfranzel!

**Comment by tfranzel** [comment]
please test if that fix works for you guys. cheers!

**Comment by avere001** [comment]
Just tested it and it is exactly what I was looking for. I appreciate your time on this, @tfranzel!

**Comment by unrealsolver** [comment]
@avere001 ,  do you have a full example for the usage? I am trying to do something very similar.  Spectacular part is clear, but DRF is not.
