### ISSUE TITLE
[Help needed] Migrate from drf_yasg

### ISSUE THREAD

**Issue by cristianoccazinsp** [tfranzel/drf-spectacular#386]
Hello,

I have read through the documentation and yet I'm failing to do a proper migration.  Currently, we use drf_yasg very lazily, basically just creating a custom schema that generates most of the operations so we don't need to decorate every single serializer/view.

Our custom schema generation looks like this:

```python
class CustomSwaggerAutoSchema(SwaggerAutoSchema):

    def get_default_responses(self):

        # Set a few defaults
        res = {
            200: 'UNDOCUMENTED',
            400: 'See error docs / validation error / {code: str, detail: {} | [] | str}',
            401: 'Unauthenticated / Auth required / Auth expired',
            403: 'Permission Denied',
            404: 'Not Found',
            405: 'Method not allowed',
            500: 'Internal Error',
            429: 'Throttled'
        }

        if hasattr(self.view, 'get_responses'):
            for code, data in self.view.get_responses().items():
                res[code] = (self.serializer_to_schema(data()) if is_serializer_class(data) else data) or ''

        return res

    def get_filter_parameters(self):
        fields = []

        if self.should_filter():
            for filter_backend in getattr(self.view, 'filter_backends'):
                fields += self.probe_inspectors(self.filter_inspectors, 'get_filter_parameters', filter_backend()) or []

        # Add our custom query_params fields
        if hasattr(self.view, 'get_action_query_params'):
            params = self.view.get_action_query_params()

            if is_serializer_class(params):
                fields += self.serializer_to_parameters(params(), in_=openapi.IN_QUERY)
            else:
                for param in params:
                    if is_serializer_class(param):
                        fields += self.serializer_to_parameters(param(), in_=openapi.IN_QUERY)

                    else:
                        fields.append(
                            openapi.Parameter(
                                param[0],
                                in_=openapi.IN_QUERY,
                                description=param[1],
                                type=openapi.TYPE_STRING,
                                required=param[2]
                            )
                        )

        return fields
```

Basically, it provides default responses and allows serializers to be used as query parameters.  We do this since we rarely use model views. So we also have this additional mixin to define helpful props at the view level:

```python
class ViewSetSerializerMixin:
    '''
    Mixin in order to allow ViewSet classes to define it's own serializer class
    and query string params per method/action so auto-docs (swagger)
    and others can work, and request info is added to context.

    Do NOT use with GenericAPIView since that class already implements everything required for docs
    or make the mixin the last class if using it.

    Usage:

    Mixin this class and define on the class:

    # For serializer classes, where name is the method/action name
    action_serializers = {
        'name': class
    }

    # For query string params, where name is the method/action name
    action_query_params = {
        'name': [(param_name, param_desc, required)] OR Serializer class or [Serializer classes]
    }

    # For response documentation
    responses = {
        code: str/desc or Serializer class
    }

    self.get_serializer can be used to use the defined class
    to avoid duplication
    '''

    def get_serializer(self, *args, **kwargs):
        serializer_class = self.get_serializer_class()

        kwargs.setdefault('context', {}).update({
            'request': self.request
        })

        # Return a dummy serializer to avoid a DRF bug that doesn't check for None
        return serializer_class(*args, **kwargs) if serializer_class else serializers.Serializer()


    def get_serializer_class(self):
        try:
            return self.action_serializers[self.action]
        except (KeyError, AttributeError):
            try:
                return super().get_serializer_class()
            except (KeyError, AttributeError):
                return None


    def get_action_query_params(self):
        try:
            query_params = self.action_query_params[self.action]
        except (KeyError, AttributeError):
            return []

        return query_params


    def get_responses(self):
        try:
            responses = self.responses[self.action]
        except (KeyError, AttributeError):
            return {}

        return responses
```

Looking at the docs, it seems that this "lazy" approach is no longer possible, and we need to decorate every single view method with `@extend_schema`. 

Is it possible to extend `AutoSchema` to support something similar to the above? Basically, call `extend_schema` automatically on every view action to set the actual parameters so we don't need to decorate every view method.

Thanks!

**Comment by tfranzel** [comment]
Hi @cristianoccazinsp,

forgive me for not going though your example in full detail, but i think i get the gist of it. having a way to specify error cases seems related to the pending #101. i have to gotten around completing this though.

for now, your solution for `drf_yasg` could be similar for spectacular by subclassing the `AutoSchema` and overriding `get_request_serializer`/``get_response_schema`. Those methods can return a `dict` with items just as you can provide them to `@extend_schema`. caveat would be that usage of `@extend_schema` on top would override your custom implementation.

fyi. you don't need to annotate with `extend_schema` on every method. you can annotate the view with `extend_schema_view()`.  have a look [here](https://drf-spectacular.readthedocs.io/en/latest/customization.html?highlight=extend_schema_view#step-2-extend-schema). this may also help you out with an approximate solution.

in any case there is no silver bullet for this at the moment.

**Comment by cristianoccazinsp** [comment]
@tfranzel thank you for the tips.

That was not still exactly what we need, since our goal is to not have to decorate any view/serializer, or anything at all. This is because all our views inherit from a mixin that already sets the serializer and query string parameter for each operation.

I managed to achieve the same behaviour with something like this:

```
class CustomAutoSchema(AutoSchema):

    def get_default_responses(self):

        # Set a few defaults
        res = {
            200: {'description':'UNDOCUMENTED'},
            400: {'description':'See error docs / validation error / {code: str, detail: {} | [] | str}'},
            401: {'description':'Unauthenticated / Auth required / Auth expired'},
            403: {'description':'Permission Denied'},
            404: {'description':'Not Found'},
            405: {'description':'Method not allowed'},
            500: {'description':'Internal Error'},
            429: {'description': 'Throttled'}
        }

        if hasattr(self.view, 'get_responses'):
            for code, data in self.view.get_responses().items():
                if is_serializer_class(data):
                    res[code] = self._get_response_for_code(data, code)
                else:
                    res[code] = {'description': data or ''}

        return res

    def _get_response_bodies(self):
        return self.get_default_responses()

    def get_override_parameters(self):
        fields = super().get_override_parameters()

        # Add our custom query_params fields
        if hasattr(self.view, 'get_action_query_params'):
            params = self.view.get_action_query_params()

            if is_serializer_class(params):
                fields.append(params)
            else:
                for param in params:
                    if is_serializer_class(param):
                        fields.append(param)

                    else:
                        fields.append(
                            OpenApiParameter(
                                param[0],
                                type=OpenApiTypes.STR,
                                location=OpenApiParameter.QUERY,
                                description=param[1],
                                required=param[2]
                            )
                        )

        return fields
```

With the above, we still support custom responses and custom query string parameters without having to decorate any class.

However, this seems to generate a huge amount of warnings due to the lack of model views:

```
Warning #50: ThreatsController: failed to obtain model through view's queryset due to raised exception. Prevent this either by setting "queryset = Model.objects.none()" on the view, having an empty fallback in get_queryset() or by using @extend_schema. (Exception: 'ThreatsController' object has no attribute 'get_queryset')

Warning #51: ThreatsController: could not derive type of path parameter "id" because because it is untyped and obtaining queryset from the viewset failed. 
Consider adding a type to the path (e.g. <int:id>) or annotating the parameter type with @extend_schema. Defaulting to "string".
```

Any way I can silence these easily? Adding a `get_queryset` to every view is not an option, nor adding `@extend_schema`.  The `id` of the path comes from DRF and SimpleRouter and is not something that can be customized neither.

**Comment by tfranzel** [comment]
i see. this only happens because spectacular is unable to infer path variable `<id>` for retrieve etc. there are 4 ways around this:

1. set explicit path with e.g. `xxx/<int:pk>` so lookup does not even need to happen.
2. somehow inject/annotate `OpenApiParameter('id', OpenApiTypes.INT, OpenApiParameter.PATH)`, so lookup does not even need to happen.
3. put some dummy `get_queryset()` into your code that only does something when schema is generated.
    ```python
       def get_queryset(self):
           if getattr(self, 'swagger_fake_view', False):
               return SomeFillerModelWithMatchingIdType.objects.none()
           return super().get_queryset()
   ```
4. turn off the warnings with the settings `DISABLE_ERRORS_AND_WARNINGS`

**Comment by tfranzel** [comment]
regarding option 2:

you can override `get_override_parameters` on `AutoSchema` and inject that `OpenApiParameter`. you just need to be smart when do return it. you can  look at `self.path` to decide that. this is proably your best option.

**Comment by cristianoccazinsp** [comment]
Option 2 worked just fine.

Still getting a bunch of other warnings, I'm really against disabling errors as they show that there's something wrong, but for some I may have no other way around it.

Warnings like this are still around:

```
Warning #7: RisksController: UpdateRiskSerializer: could not resolve serializer field "ObjectField(help_text='List of safeguards ids, invalid ones will be 
ignored, do not send to skip changing this.', required=False, validators=[<tra.api.serializers.risks.ObjectFieldValidator object>])". Defaulting to "string"
```
This one is due to a custom serializer. Is it possible to add a property or something to it so the warning is removed and it defaults to str? It is actually a JSON field that we have some special handling to support both str and json.


```
Warning #12: encountered multiple names for the same choice set (ResidualLikelihoodEnum). This may be unwanted even though the generated schema is technically correct. Add an entry to ENUM_NAME_OVERRIDES to fix the naming.
```
We have a bunch of enums within many models, most of them with the same name, but scoped to the class. 

I think after the above warnings are resolved, we should have a successful migration.

Thanks a lot for the help!

**Comment by tfranzel** [comment]
> Warning #7: RisksController: UpdateRiskSerializer: could not resolve serializer field

either annotate `ObjectField` with `extend_schema_field` or create an extension: https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-field-output-with-openapiserializerfieldextension

> Warning #12: encountered multiple names for the same choice set 

https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-get-warnings-regarding-my-enum-or-my-enum-names-have-a-weird-suffix

**Comment by cristianoccazinsp** [comment]
Thanks, `extend_schema_field` worked fine.

For warning 12, I don't think it's good for us to create dependencies from the settings file into every enum.  I think we will disable these last warnings for now and accept them.  We use swagger mostly for developers to manually test the API endpoints and not really rely on schema generation.

Thanks again! It's like the 4th time we have to migrate our swagger framework.

**Comment by tfranzel** [comment]
sure, no problem. hopefully the last time :smile: 

> For warning 12, I don't think it's good for us to create dependencies from the settings file into every enum

you don't need to have a hard dependency there. this works perfectly fine with import strings. ``'CountryEnum': 'app.choices.CountryChoices'`` will do just fine. what is found gets resolved or nothing happens. no real dependency there.
