### ISSUE TITLE
jwt Authentication class compatibility with drf-spectacular

### ISSUE THREAD

**Issue by usefss** [tfranzel/drf-spectacular#387]
there is a very strange behavior of drf-spectacular when defining Authentication classes from simple-jwt when you declare JWTAuthentication as default_authentication_class swagger UI authorize button works correctly but when you declare JWTTokenUserAuthentication as default_authentication_class swagger UI authorize button disappears and can not set Bearer token.  
Steps to reproduce:  
first, create a Django project with rest framework and drf-spectacular and simple jwt installed and configured with documentation guidance.  
now go to /api/schema/swagger-ui/ everything works fine
then change authentication classes to:
```
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTTokenUserAuthentication',

    )
```
and refresh boom!! there is no authorize button at all!!! it looks like if you subclass JWTAuthentication class it goes wrong.
I did not know where to post this issue but so posted it on both, can anybody help me to fix drf-spectacular with this authentication class?

**Comment by tfranzel** [comment]
hi, you found yourself a bug. simple oversight. the shipped auth extension does not account for that second class. easy fix

**Comment by usefss** [comment]
ok I delete the duplicate issue from simple-jwt

**Comment by usefss** [comment]
@tfranzel when do you think you can fix this?

**Comment by tfranzel** [comment]
please confirm this is working and close the issue. fix will be in the next release

**Comment by usefss** [comment]
yes, it works flawlessly, you are awesome thank you!

**Comment by usefss** [comment]
@tfranzel Hi, can you inform me when do you want to release this bug fix??

**Comment by tfranzel** [comment]
@usefss i was/am pretty swamped at the moment. will do it definitely in the next couple of days.
