### ISSUE TITLE
Add common OpenApiParameter used in path

### ISSUE THREAD

**Issue by tiger-mc** [tfranzel/drf-spectacular#393]
Apologies if this is covered in the docs, I have searched but can't find anything that is suitable.

I use an account_uid parameter in the path of almost every URL in the API, is there a way to define this in a DRY manner, or is it necessary to manually decorate every view with extend_schema in this scenario?

Thanks

**Comment by tfranzel** [comment]
hi @tiger-mc,

this has been asked before and i answered it recently in an issue which i cannot find anymore. anyway, DRY solution would be to use a custom AutoSchema. we made this modification pretty simple.`extend_schema` annotated parameters are added on top.

```python
    class CustomAutoSchema(AutoSchema):
        def get_override_parameters(self):
            # there is also self.path_regex available
            if 'account_uid' in self.path:
                return [
                    OpenApiParameter('account_uid', type=OpenApiTypes.UUID, location=OpenApiParameter.PATH),
                ]
            return []
```

this should be one of the few instances where it is the easiest to customize `AutoSchema`. does that work for you? of cource you have to change the `DEFAULT_SCHEMA_CLASS`.

**Comment by tiger-mc** [comment]
This is brilliant, thank you for your time and the great library!
