### ISSUE TITLE
spectacular not discovering custom auth extension classes

### ISSUE THREAD

**Issue by jerinpetergeorge** [tfranzel/drf-spectacular#394]
drf-spectacular is not automatically discovering the ***`target`*** components that are defined as ***string*** (ie, `path.to.mod.Klass`)

I think this is somehow related to https://github.com/tfranzel/drf-spectacular/issues/391.

_______________________

### Create a custom auth class
```python
# custom_jwt/authentication.py
from rest_framework_simplejwt.authentication import JWTAuthentication as JWTA


class CustomJWTAuthentication(JWTA):
    pass
```
### Create custom extension class
```python
# spectacular/auth_extension.py
from drf_spectacular.contrib.rest_framework_simplejwt import SimpleJWTScheme


class SimpleJWTTokenUserScheme(SimpleJWTScheme):
    name = "CustomJWTAuth"
    target_class = "custom_jwt.authentication.CustomJWTAuthentication"
```
### Connect things in `settings,py`
```python
# DRF
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "custom_jwt.authentication.CustomJWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
```

Then open browser and head to swagger-ui page. You won't see the ***Authentication Button**** :sob: 

I have created a repo [here- (branch-`auth-extension-target-error`)](https://github.com/jerinpetergeorge/drf-spectacular-example/tree/auth-extension-target-error), which can be used to reproduce the issue!!!

________________________
I think the **`SimpleJWTTokenUserScheme`** not getting initialized during the server startup and thus creating this situation.

as a workaround, we can use the ***actual class*** for `target_class` attribute as,

```python
# spectacular/auth_extension.py
from drf_spectacular.contrib.rest_framework_simplejwt import SimpleJWTScheme

from custom_jwt.authentication import CustomJWTAuthentication


class SimpleJWTTokenUserScheme(SimpleJWTScheme):
    name = "CustomJWTAuth"
    target_class = CustomJWTAuthentication
```

**Comment by tfranzel** [comment]
hi! thanks for the detailed issue. interesting! this has never made any problems until now. it can only be a path issue i suppose, like missing the root folder. i will have a look

fyi: if `custom_jwt` is added as an DRF app in the settings, there will be a warning on broken imports otherwise it is silently ignored.  otherwise all supported but unused contrib apps would issue warnings.

**Comment by pablodgonzalez** [comment]
Hi @tfranzel @jerinpetergeorge , in most case there is no problem, but the extension should be declared inner a file which the app surelly goes to use. If you declare your extension in isolated file then it won't load at startup. If you did it then you must import the extension in some another file which the interpreter can load it.

**Comment by jerinpetergeorge** [comment]
I suspected that before!!

I did this,

```python
# settings.py

# other settings

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "custom_jwt.authentication.CustomJWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
from spectacular.auth_extension import SimpleJWTTokenUserScheme
```

This worked!!! :partying_face: 


But, I did this too, (`SPECTACULAR_SETTINGS` after extension class import)
```python
# DRF
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "custom_jwt.authentication.CustomJWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
from spectacular.auth_extension import SimpleJWTTokenUserScheme

# DRF Spectacular Settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Test APIs",
    "DESCRIPTION": "Various APIs for Test service",
    "VERSION": "1.0.0",
}
```
At this time, I have got the ***auth button***, but, the `SPECTACULAR_SETTINGS` settings values didn't reflect in the swagger UI


@pablodgonzalez @tfranzel

**Comment by tfranzel** [comment]
@pablodgonzalez thanks for clarifying. i assumed this was not the problem since it supposedly worked with the class.

https://drf-spectacular.readthedocs.io/en/latest/faq.html#where-should-i-put-my-extensions-my-extensions-are-not-detected

please follow that advice and don't put the import in `settings.py`, as it may bite you. anywhere else is fine, e.g. urls.py

@jerinpetergeorge again `SPECTACULAR_SETTINGS` is something that normally works perfectly. is it not working or are we done here?

**Comment by pablodgonzalez** [comment]
Well, I really I don't sure about it, maybe the spectacular setting after the import makes spectacular initialize after ignoring it.
Is better if you import it in CustomJWTAuthentication class declaration instead of the setting, futhermore it is more clear about for what reason the schema is.

**Comment by jerinpetergeorge** [comment]
> @jerinpetergeorge again SPECTACULAR_SETTINGS is something that normally works perfectly. is it not working or are we done here?

it is working, but not under this special situation that I mentioned [here](https://github.com/tfranzel/drf-spectacular/issues/394#issuecomment-845114697), and now I realize it is not good practice to import things into `settings.py` :rofl: 


Yes, this section, ([*Where should i put my extensions? / my extensions are not detected*](https://drf-spectacular.readthedocs.io/en/latest/faq.html#where-should-i-put-my-extensions-my-extensions-are-not-detected)) makes perfect sense to this situation :partying_face: ✌️

**Comment by tfranzel** [comment]
@jerinpetergeorge awesome! please close the issue if we are done here.

@pablodgonzalez :+1: very possible. 

the extension autoloading was meant to be easy, but has sadly created a lot of confusion. the idea was taken from automatic celery task registration.

**Comment by jerinpetergeorge** [comment]
> the idea was taken from automatic celery task registration.

I had the same issue for celery tasks too :rofl: that's too because of my

**Comment by tfranzel** [comment]
i should have known better. even though it is a convenient feature i shot myself in the foot several times with celery because of that. and because i have not learnt from it i included that here too. :sweat_smile:

**Comment by jerinpetergeorge** [comment]
> i shot myself in the foot several times with celery because of that

I know how that feels :rofl:
