### ISSUE TITLE
Is there a way to force schema to output a Dict instead of an Array?

### ISSUE THREAD

**Issue by pablodgonzalez** [tfranzel/drf-spectacular#395]
**Describe the bug**
Hi, I've changed the default list_serializer_class by an DictSerializer but I have not found a way to change the schema according it. Maybe there is some way to do it but i don't know. I tried with extension schemas, and fileds and custom serializerextensions without success.

```python
class BrandDictSerializer(serializers.ModelSerializer)
    Meta:
        model = Brand
        fieds = (id, name)
        list_serializer_class = DictSerializer

class DictSerializer(serializers.ListSerializer):
    dict_key = id

    @property
    def data(self):
        ret = super(serializers.ListSerializer, self).data
        return ReturnDict(ret, serializer=self)

    def to_representation(self, data):
        items = super(DictSerializer, self).to_representation(data)
        return {item[self.dict_key]: item for item in items}
```

**Expected behavior**
I expect the schema get an object type with additionalProperties of type Brand

```
"BrandDic": {
      "type": "object",
      additionalProperties:
      "properties": {
                    "id": {
                        "type": "integer",
                        "readOnly": true
                    },
                    "brand": {
                        "$ref": "#/components/schemas/Brand"
                    }
  }

```

**Comment by tfranzel** [comment]
Hi! DRF is certainly a customization rabbit hole. never seen it being modified there. pretty ingenious!

`SerializerExtension` is the right thing to do. the reason the extension is not called is that `ListSerializer` contains magic meta-programming and has a special place in spectacular's processing. the list gets unwrapped before the extension can be called (link below). It would work if `DictSerializer` would not be derived from `ListSerializer`

https://github.com/tfranzel/drf-spectacular/blob/abff8b315718c380c3a26abef3b8a74a639f9a36/drf_spectacular/openapi.py#L946

this issue is partially related to #391 (and by association #351)

**Comment by pablodgonzalez** [comment]
Thanks @tfranzel , So, If I understood you I need change DictSerializer (or better BrandDictSerializer) to receive the array values but no using it with "many=True". Is it possible???

**Comment by tfranzel** [comment]
not even sure if i would call this a bug. you derive from `serializers.ListSerializer` but then make it so that it is not a list anymore. that is basically the violated assumption that spectacular makes.

SerializerExtensions at the moment work for everything except `ListSerializer` (and `ListField` as it doing the same thing)

If you copy the contents of `serializers.ListSerializer` to `DictSerializer` and make it **not** derived from `ListSerializer`, the extension should work. 

as you already, know `XXX(many=True)` is just syntactic sugar for `list_serializer_class(child=XXX)`. so the `many=True` is not the problem but the `isinstance(DictSerializer(child=BrandDictSerializer()), ListSerializer) == True`

**Comment by pablodgonzalez** [comment]
hi @tfranzel, How are you? I think now, need your help.
Well I he changed a little my implementation but, right now drf-spectacular needs some "fix". You should see it.

```
class DictSerializer(serializers.BaseSerializer):

    dict_key = 'id'
    child = None
    many=True

    def __init__(self, *args, **kwargs):
        self.child = kwargs.pop('child', copy.deepcopy(self.child))
        self.dict_key = kwargs.pop('dict_key', 'id')
        assert self.child is not None, '`child` is a required argument.'
        assert not inspect.isclass(self.child), '`child` has not been instantiated.'
        super().__init__(*args, **kwargs)
        self.child.bind(field_name='', parent=self)

    def get_initial(self):
        if hasattr(self, 'initial_data'):
            return self.to_representation(self.initial_data)
        return {}

    def get_value(self, dictionary):
        """
        Given the input dictionary, return the field value.
        """
        # We override the default field access in order to support
        # dict in HTML forms.
        if html.is_html_input(dictionary):
            return html.parse_html_dict(dictionary, prefix=self.field_name)
        return dictionary.get(self.field_name, empty)

    @property
    def data(self):
        """
        Overriden to return a ReturnDict instead of a ReturnList.
        """
        ret = super().data
        return ReturnDict(self.data, serializer=self)

    def to_representation(self, data):
        """
        Converts the data from a list to a dictionary.
        """
        items = serializers.ListSerializer(data=data, child=self.child).to_representation(data)
        return {item[self.dict_key]: item for item in items}

class DictModelSerializer(serializers.ModelSerializer):

    @classmethod
    def many_init(cls, *args, **kwargs):
        is_dict = kwargs.pop('dict', False)
        dict_key = kwargs.pop('dict_key', 'id')
        if not is_dict:
            return super().many_init(cls,*args, **kwargs)

        child_serializer = cls(*args, **kwargs)
        list_kwargs = {
            'child': child_serializer,
            'dict_key': dict_key
        }
        list_kwargs.update({
            key: value for key, value in kwargs.items()
            if key in serializers.LIST_SERIALIZER_KWARGS
        })
        meta = getattr(cls, 'Meta', None)
        dict_serializer_class = getattr(meta, 'list_serializer_class', DictSerializer)
        return dict_serializer_class(*args, **list_kwargs)

class ContainerSerializer(serializers.Serializer):
  brands = BrandSerializer(source='*', dict=True, many=True)
  other = OtherSerializer()

class BrandSerializer(DictModelSerializer):
  class Meta:
    model = Brand
    fields = ('id', 'country')
```
I get this output
```
"Container": {
        "brands": {
            "1": {
                "id": 1,
                "country": 10
            },
            "3": {
                "id": 3,
                "country": 10
            }
        },
     "other": "other"
    }
```
The output is what i expect but the schema don't
I expect the below schema
```
Container:
  type: object
      properties:
        other:
          type: string
          readOnly: true
        brands:
          $ref: '#/components/schemas/BrandDict'

BrandDict:
   type: object
   additionalProperties:
      $ref: '#/components/schemas/Brand'

Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        country:
          type: string
```
Instead Of I get just
```
Container:
  type: object
      properties:
        other:
          type: string
          readOnly: true
```
And the issue is in the the resolve_serializer method

https://github.com/tfranzel/drf-spectacular/blob/2684fdae7c2c02d289fe8856d7f35a6d634b4a09/drf_spectacular/openapi.py#L1183-L1193

I think Just need add 
```
and not component.schema.get('additionalProperties')
```
What do you think?

**Comment by tfranzel** [comment]
@pablodgonzalez ahh i'm really sry. this one fell of the waggon and i totally forgot about it. 

that code is pretty new and not even release yet. we inverted the logic from "keep this" to "discard this". of course we missed a case. :smile: it should also account for `additionalProperties` easy fix.

**Comment by pablodgonzalez** [comment]
@tfranzel I know it is a new code, in the old logic has not `additionalProperties` either, but yeah! we going to ahead. I will waiting for this change. Thanks so much!

**Comment by tfranzel** [comment]
@pablodgonzalez that should do it. would be great if you could test that this satisfies your use-case.

**Comment by pablodgonzalez** [comment]
@tfranzel Yes!!! I have test it already. My question is about to if it is the only place where the change is needs if it is.
Thanks in advance!

**Comment by tfranzel** [comment]
from my current understanding this should be it. everything else should work just the same. components will not be removed so easily anymore. `Extensions` need no changes. was that your question?

**Comment by pablodgonzalez** [comment]
Yes! All is right then! Thanks for your support!

**Comment by tfranzel** [comment]
fyi: there is now a mechanism to modify `ListSerializer` behavior by writing a `OpenApiSerializerExtension` (https://github.com/tfranzel/drf-spectacular/commit/68e2b1b68d5d9157735f0ce9700e36182dd662ba)

**Comment by pablodgonzalez** [comment]
Greate! Thanks @tfranzel for remember this thread. Good work!
