### ISSUE TITLE
Decorator alternatives

### ISSUE THREAD

**Issue by KStenK** [tfranzel/drf-spectacular#396]
Hi there,

Good job with the project.

I've used that library for a while now.

But I've noticed one annoying thing. When I'm using ViewSets and want to extend schema descriptions, add examples, etc.. then my viewset.py file grows pretty big and it gets pretty hard to navigate between different ViewSets when there are 80+ lines big decorator on top of my ViewSet class.

Is it possible to add those docs or decorators to the docs.py file or something?

Maybe create a proxy to those extended schema decorators or something.. so there is only one line decorator on my ViewSet class.

Any ideas on how I could accomplish it or any other ideas on how to make writing those docs more maintainable?

**Comment by tfranzel** [comment]
Hey @KStenK, thank you very much.

i noticed that too in our codebase. the decorator can get quite big. i have shifted recurring things like docstrings, parameters and examples into a `schema.py` from which i import the parameters to `@extend_schmema`. that considerably slims down the decorator for me. your could even do `@extend_schema(**schema.some_view_params)`, i used that once or twice.

generally i find the idea interesting. the challenge would be to do this transparently without surprises, ideally without complicating the code too much.

**Comment by KStenK** [comment]
Thank you for the idea.

I got it working using dictionaries and it works for me at this moment.

Example:

```
foo_extend_schema_view = {
    "create": extend_schema(
        description="foo"
    ),
    "destroy": extend_schema(
        description="foo"
    )
}

@extend_schema_view(**foo_extend_schema_view)
class FooViewSet(viewsets.ModelViewSet):
    pass
```

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
