### ISSUE TITLE
Allow json/yaml schema response selection via query parameter

### ISSUE THREAD

**Issue by valentijnscholten** [tfranzel/drf-spectacular#397]
When using ReDoc or SwaggerUI it could be helpful if users could view the json and yaml schema in the browser. Currently the `/schema` url selects the response format bases on content negotiation. I am not sure how browsers handle this and what the defaults are, for me chrome seems to default to yaml. I prefer json and in general I think it would be good to be able to choose the format via a query parameter. Similar to what was possible in `drf-yasg`.

I know DRF has some possiblity to append a `.json` suffix, but I couldn't get it to work for the root/schema url.

Or maybe spectacular could use the default based the DRF settings:
``` 
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
```

**Comment by valentijnscholten** [comment]
Just found it already works, it's just not shown on the swagger-ui page. This can be achieved by the (ugly?) way below:
```
url(r'^api/v2/oa3/swagger-ui/' , SpectacularSwaggerView.as_view(url='api/v2/oa3/schema/?format=json'), name='swagger-ui_oa3'),
```

**Comment by tfranzel** [comment]
swagger and redoc are fixed to one schema. this is a upstream choice we have no control over. but you can add those two links to the schema description if you like. then users can visit what they want themselves.
