### ISSUE TITLE
How to define multiple request serializers used in union

### ISSUE THREAD

**Issue by tiger-mc** [tfranzel/drf-spectacular#398]
Sorry it's me again!

I have several views that use a model serializer for the request, but also use a second serializer to parse query parameters that are used for filtering, as these are common across many views.

I have tried using extend_schema and PolymorphicProxySerializer , but I am not sure if the PolymorphicProxySerializer supports this scenario, as both serializers are used at once rather than one or the other.

I would like to avoid having to write a combined serializer for each of these views if I can!

Thanks

**Comment by tfranzel** [comment]
i think this is what you are looking for. define `parameters` in addition to `request`/`responses`. 

https://github.com/tfranzel/drf-spectacular/blob/812d3ffd39347241ea9ac38793d6801cc6b17136/tests/test_extend_schema.py#L151-L154

you can also experiment with `OpenApiParamters(..., style='form', explode=True)`

**Comment by tiger-mc** [comment]
That works perfectly thank you. I think I need more coffee, that is so apparent in the documentation after another look...thanks again.

**Comment by tiger-mc** [comment]
Reopening as this is still closely related to the original question. I have one other scenario where I am using two different serializers to get data from the request body in several views. It is a custom permission that is not using DRF permissions, due to requiring a heavy database query.

I would ideally like to be able to declare something like `request=[SerializerA, SerializerB]` and for all of those fields to appear in `requestBody`. It looks like it is possible to add additional params to query, path, header and cookie, but not body.

Not sure if maybe `inline_serializer` could be used here and get all fields from both serializers.

**Comment by tfranzel** [comment]
there is no mechanism to meld two serializers. nothing like that exists in DRF. what you can do is `oneOf` with `PolymorphicProxySerializer` to signal that the endpoint either returns A or B. 

If you want all fields from A and B, you would need to do `class C(A, B)` + plus some `Meta` merging, but that would be outside of drf-spectacular's scope i'm afraid.

**Comment by tiger-mc** [comment]
Okay thank you!
