### ISSUE TITLE
Hide serializer field in inline serializer

### ISSUE THREAD

**Issue by t-pohl** [tfranzel/drf-spectacular#400]
Hey, I'm trying to use part of serializer as a field. I know of the existence of `extend_schema_serializer` and the `exclude_fields` options but I cannot manage to use it as a field of a different serializer.

Example:
```        
responses=extend_schema_serializer(many=False)(
    inline_serializer(
        name="getHeartBeatsResponse",
        fields={
            "count": serializers.IntegerField(),
            "page_count": serializers.IntegerField(),
            "results": serializers.ListField(child=DeviceHeartbeatSerializer()),       # Here I want a exclude a field from DeviceHeartbeatSerializer
        },
    )
),
```

I tried 
```
responses=extend_schema_serializer(many=False)(
    inline_serializer(
        name="getHeartBeatsResponse",
        fields={
            "count": serializers.IntegerField(),
            "page_count": serializers.IntegerField(),
            "results": serializers.ListField(
                child=extend_schema_serializer(exclude_fields="device")(
                    DeviceHeartbeatSerializer()
                )
            ),
        },
    )
),
```
but it does not seem to work. Does this feature simply not exist or I am I using the library in a wrong way?

Pardon me, if the answer is simply but I could not find it in the docs.

**Comment by tfranzel** [comment]
hi, i found 2 mistakes

- `exclude_fields` is a list
- `()`should be outside of `extend_schema_serializer`

but there is one more problem here. `extend_schema_serializer` actually modifies `DeviceHeartbeatSerializer` inplace. that change propagates to other usages of that serializer. that was a design mistake i made. maybe we should finally fix this.

```python
        responses=extend_schema_serializer(many=False)(
            inline_serializer(
                name="getHeartBeatsResponse",
                fields={
                    "count": serializers.IntegerField(),
                    "page_count": serializers.IntegerField(),
                    "results": serializers.ListField(
                        child=extend_schema_serializer(exclude_fields=["device"])(
                            DeviceHeartbeatSerializer
                        )()
                    ),
                },
            )
        )
```

**Comment by t-pohl** [comment]
Marvelous, thank you very much that worked!
Does the inplace modification of `DeviceHeartbeatSerializer` now has any consequences anymore if I use the code that you proposed?

**Comment by tfranzel** [comment]
yes that does still apply. i thought about it more. `extend_schema_serializer` has 3 params. 

-  `exclude_fields` -> actually not a bug
- `many` -> bug
- `examples` -> bug

the issue is that you would have 2 serializers/components named `DeviceHeartbeat` that differ in their fields. we only have one name available and thus there would be a collision. if you only use the one without device exposed, it is ok to be used like that.

**Comment by t-pohl** [comment]
Okay, so in that case I create a second a special serializer just for the heartbeat without the device and use that. Not beautiful but should be the safe route and maybe this will be changed in some upcoming release :)

**Comment by tfranzel** [comment]
this is the way. 

i'm afraid this is a conceptual limitation. we would have 2 "different" serializer and only one name for it. unless we would attach ugly suffixes like `DeviceHeartbeat2` this cannot be resolved.

**Comment by t-pohl** [comment]
Okay, I can happily live with the workaround as long as I know about the limitation. Thank you very much for clarifying and helping me out!
