### ISSUE TITLE
[need help]can't put type=list() in to OpenApiParameter

### ISSUE THREAD

**Issue by jasonham** [tfranzel/drf-spectacular#406]
I want accept list for a param, when i put this into extend_schema, i got AttributeError: 'list' object has no attribute 'items'
`OpenApiParameter(name='teacher_ids', description='teacher ID list', required=True, type=list()),`
need help
thx

**Comment by tfranzel** [comment]
good thinking but we do not support combined types there. the question would be "list of what?". i know that `type: any = str` is a bit vague but its tricky to write a type annotation here that covers all the cases. 

`OpenApiParameter` is a little less flexible than the other decorators/methods. it accepts basic types (int, str, bool, etc), `OpenApiTypes.*` and raw schema. in case of list you have to do it manually at the moment: 

```python
type={'type': 'array', 'items': {'type': 'integer'}}
```

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
