### ISSUE TITLE
Using PolymorphicProxySerializer not taking input from two serializers mentioned.

### ISSUE THREAD

**Issue by ashwinisd25** [tfranzel/drf-spectacular#408]
**Describe the bug**
Using PolymorphicProxySerializer to pass two serializers so that in swagger UI I can get request body(Example Value) combining both serializer data.
But in schema it is taking oneOf the 2 serializer mentioned,
how can I set both serializersin Example Value

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

**Expected behavior**

**Comment by tfranzel** [comment]
i'm sorry but i don't understand your question.

**Comment by ashwinisd25** [comment]
Hi,
I am documenting my API using drf-spectacular.
I have a PUT end point to update the data, so I have 2 serializers for that.
I am passing these 2 serializers using PolyMorphicpProxySerialzer,
But in swagger ui the request body taking only the first serializer fields
from the list of serializers
How to add both serializer fields into request body???


And in schema its showing (choosing) oneOf 2 serializers how to make it
allOf???


Please help with this..

Thank you

**Comment by tfranzel** [comment]
i believe i answered this question here: https://github.com/tfranzel/drf-spectacular/issues/398#issuecomment-846028685

PolymorphicProxySerializer can only signal that the endpoint will either return A or B. fusing together A and B into one serializer is a concept unknown to DRF.

**Comment by ashwinisd25** [comment]
Thank you for the clarification.
