### ISSUE TITLE
Cannot find a way to remove pagination from schema for a custom action.

### ISSUE THREAD

**Issue by mmx86** [tfranzel/drf-spectacular#412]
**Describe the bug**
Pagination params appear in schema where not needed.

**To Reproduce**
```
class DatasetViewSet(ModelViewSet):
    queryset = Dataset.objects.order_by('-id')

    serializer_class = DatasetSerializer
    custom_serializers = {  # Used in custom "get_serializer_class" method
        'download_data': DataSerializer,
    }

    @extend_schema(
        responses={200: DataSerializer(many=True)},
    )
    @action(detail=True, methods=['get'])
    def download_data(self, request, pk=None):
        try:
            dataset = Dataset.objects.get(pk=pk)
        except Dataset.DoesNotExist:
            raise exceptions.NotFound()

        queryset = Data.objects.filter(dataset=dataset)
        serializer = self.get_serializer(queryset, many=True)

        response = HttpResponse(serializer.data, content_type='application/json')
        response['Content-Disposition'] = f'attachment; filename="{dataset.name}.json"'
        return response
```

**Expected behavior**
Endpoint `download_data` is supposed to return all data fragments, contained in the dataset to download as a file without any pagination (pagination is sill required for regular `list` enpoint of this viewset). But `many=True` in `extend_schema` decorator forces pagination to appear.

Is there a sane way to customize it and remove pagination from schema for single endpoint?

**Comment by tfranzel** [comment]
hi! this has come up before and is not that obvious. added a FAQ entry for it.

https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-action-is-erroneously-paginated-or-has-filter-parameters-that-i-do-not-want

that should answer your question i believe.

**Comment by mmx86** [comment]
Yes. Thank you very much!
