### ISSUE TITLE
Adding examples to auto created parameters

### ISSUE THREAD

**Issue by elvirTatarevic** [tfranzel/drf-spectacular#414]
Hello,

Is there any way to add an examples list to parameters that have already been auto-generated?

Basically, at this point, the only way I can see adding an example to a parameter is by extending the schema using extend_schema or by modifying it in the Post Processing Hooks. I would like to avoid creating my own parameters since the auto-generated ones are pretty good as is and doing it in the post-processing hook would then move the examples to different parts of the code causing confusion. 

I would prefer to do it in the extend_schema function but I'm not quite sure how that would look. My only thought currently is to add a parameters_extension field which is a list that has fields just like parameters that will overwrite or add to the auto-generated parameters once they have been created. 

Any other thoughts or ideas for some sort of workaround?

Thank you.

**Comment by tfranzel** [comment]
hey @elvirTatarevic, took me a while but finally got around doing it. 

you should now be able to attach examples everywhere a matching parameter defined (or is automatically generated). you only need to provide a `name, location` tuple and the machinery should take care of the rest.

```python
    @extend_schema(
        examples=[
            OpenApiExample(
                "Example ID 2",
                value=2,
                parameter_only=('id', OpenApiParameter.PATH)  # <--- the new part
            )
        ]
    )
```

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
