### ISSUE TITLE
Support mark field deprecated

### ISSUE THREAD

**Issue by elonzh** [tfranzel/drf-spectacular#415]
See https://spec.openapis.org/oas/v3.1.0#parameter-object

**Comment by tfranzel** [comment]
parameter:
https://github.com/tfranzel/drf-spectacular/blob/a31a9e40f52933dfa6ca19d591828ddc456e1e9c/drf_spectacular/utils.py#L142

operation:
https://github.com/tfranzel/drf-spectacular/blob/a31a9e40f52933dfa6ca19d591828ddc456e1e9c/drf_spectacular/utils.py#L193

however it looks like we are missing a way to mark a field as deprecated.

**Comment by elonzh** [comment]
Yep, marking a field as deprecated is just what I need. 🤣

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by marianhlavac** [comment]
> feel free to comment if anything is missing or not working and we will follow-up.

Documenting this feature would be nice. Haven't found any resource on how to use this, apart from reading the commit diff.

**Comment by tfranzel** [comment]
it is documented here: https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.extend_schema_serializer

Other than that, is is difficult to document every single feature in spectacular with an example. I would count that one as one of the self-documenting ones.
