### ISSUE TITLE
Is there a way to pass custom HTTP headers to the underlying view?

### ISSUE THREAD

**Issue by AqeelAT** [tfranzel/drf-spectacular#419]
We use multiple extra HTTP headers in our requests. Is it possible to use `@extend_schema` to pass these headers and their values, which in turn would be added to the request?

**Comment by tfranzel** [comment]
the tests do cover all kinds of parameter variations. here are header params for request and response.

https://github.com/tfranzel/drf-spectacular/blob/226d45067e1b3ff2241940f56e5204a70db09eb1/tests/test_extend_schema.py#L82-L123

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
