### ISSUE TITLE
extend_schema(operation=XXX) does nothing

### ISSUE THREAD

**Issue by tfranzel** [tfranzel/drf-spectacular#421]
Hey @tfranzel. First, thanks for the great library :)

Have been trying for days now to get this manual override to work without luck. My initial idea was to do like this:

    extend_schema(operation={
        "operationId": "upload_endpoint",
        "description": "fallback mechanism where we can go all out",
        "tags": ["manual_tag"],
        "requestBody": {
            "content": {
                "application/json": {
                    "schema": {"$ref": "#/components/requestBodies/Route"}
                },
            },
        },
        "responses": {
            "200": {
                "content": {
                    "application/json": {
                        "schema": {"$ref": "#/components/schemas/RouteV3Model"}
                    }
                },
            },
        }
    })
    @action(detail=false, methods=["POST"])
    def upload(self, request, *args, **kwargs):

But this does nothing. It just fails silently without telling me whats wrong and the endpoint ends up having its normal description, request etc, without any of the data specified in the extended schema annotation. Next thing i tried was to specify the response and the request body directly in the extended schema annotation but this also did nothing. So:

1) Why does this fail ?

2) Where exactly is the schema.yaml supposed to be located in the project and is there anything special i need to do before it can be referenced from the extended schema annotations ? (In my Django project i have it located directly in the src folder which is where it was generated when i ran the command ./manage.py spectacular --file schema.yaml --validate --fail-on-warn)

3) In the normal non-manual way, that you posted on the 7th of march in this thread isn't there a way to reference the components section in the schema.yaml file? Something like below:

@extend_schema(
    examples=[
        {"$ref": "#/components/examples/MyExample"}
    ],
    responses={
         {"$ref": "#/components/schemas/MyModel"}
    }
    request={
          {"$ref": "#/components/requestBodies/MyRequestBody"} #(this request body uses the MyExample and the MyModel)
    },
)

_Originally posted by @AndersJensenBikemap in https://github.com/tfranzel/drf-spectacular/issues/279#issuecomment-857491737_

**Comment by tfranzel** [comment]
hi @AndersJensenBikemap,

i took the liberty to put this in a fresh issue, since its not directly related to `@api_view`. thank you by the way :smile: 

> But this does nothing. It just fails silently without telling me whats wrong and the endpoint ends up having its normal description,

that sounds odd. i'll check this but the tests do cover this and i assumed this worked. 

> 1. Why does this fail ?

we would need to dig in deeper. it is not supposed to fail silently.

> 2. Where exactly is the schema.yaml supposed to be located in the project and is there anything special i need to do before it can be referenced from the extended schema annotations ? (In my Django project i have it located directly in the src folder which is where it was generated when i ran the command ./manage.py spectacular --file schema.yaml --validate --fail-on-warn)

the schema is always generated on the fly. the written file is never again read. therefore it does not matter where you write it. you need to tell spectacular what you want before the generation.

> 3. In the normal non-manual way, that you posted on the 7th of march in this thread isn't there a way to reference the components section in the schema.yaml file? Something like below:

you can usually only reference existing/previously generated component `refs`. there is no direct way to manipulate the `component` section when doing this. this is exactly the reason why the raw schema via `operation=` is supposed to be a matter of last resort if nothing else works. what you can do is use the `'APPEND_COMPONENTS': {}` setting to inject the components that you `ref` in your raw schema, but as i tried to say, this is cumbersome and probably error-prone.


what does prevent you from using the proper way (everything except `operation=`)?

**Comment by tfranzel** [comment]
```python
@extend_schema(
examples=[
{"$ref": "#/components/examples/MyExample"}
],
responses={
{"$ref": "#/components/schemas/MyModel"}
}
request={
{"$ref": "#/components/requestBodies/MyRequestBody"} #(this request body uses the MyExample and the MyModel)
},
)
```

this is generally not what we support. your need to use the facilities we provide. correct usage would look more like

```python
@extend_schema(
    examples=[OpenApiExample(...), OpenApiExample(...)],
    responses={
        "200": Your(Output)SerializerClass(Instance)
    },
    request=Your(Input)SerializerClass(Instance)),
)
```

**Comment by AndersJensenBikemap** [comment]
Well what prevents me from doing it the right way, is that we've got serializers with fields implemented in a bit of a hacky way at the moment. For example a field that is a SerializerMethodField and will therefore not be included in the request body because it is a read-only field, but in reality you can actually post to it and should post to it. The correct solution would probably be to first refactor this field to a field that will be picked up by the schema generator and added to the request body.
Also some of the data that can be submitted to the endpoint is not data that is part of the serializer and there doesn't seem to be a way to add extra custom fields through the decorator to the serializer.

**Comment by tfranzel** [comment]
now i understand better. with that you are in fact in the "i know what i'm doing"-territory.

we cannot provide those modifications in the "regular" decorator interface as there are too many possibilities for that (well except for `operation=` as you know)

i see 2 routes for you

1.  you can probably leverage `OpenApiSerializerExtension` ([docs](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-serializer-magic-with-openapiserializerextension)) we use that for handling [polymorphic serializers](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/serializers.py). It is basically excactly for that case: having serializers that do some non-standard magic. You have a lot more control there. you can inject components into the registry (`auto_schema.registry.register_on_missing()`) and handle your fields semi-manually there too. it might be a bit tricky to get it working, but then you could cover all serializers that do this magic. you should have a mixin on the serializer (maybe empty just to mark those cases) to catch that case with the extension's `target_class`
2. `@extend_schema(operation=XXX)` and `'APPEND_COMPONENTS'`. this should still work. i have no clue why this is not working for you there. we could dig into that.

**Comment by AndersJensenBikemap** [comment]
I'd like to avoid the operation=XXX route as much as possible, so if its possible then i'd much rather get it to work properly, i.e refactor the serializerfield to something else. Probably JsonField or something along those lines. 

But i still have the problem that there are certain fields in the request body that are not present in the serializer, but which should be part of all requestbodies using that serializer. Using your example, some pseudo code im imagining would be

@extend_schema_serializer(
    exclude_fields=('single',) # schema ignore these fields
    additional_fields({"app_version", string}, {"app_type", string})
)
class AlbumSerializer(serializers.ModelSerializer):


Hope you can see what im trying to do in the example above. 
If this is not possible would it then be possible to do in the post_processor ? Or is this a thing one shouldn't do ?

**Comment by tfranzel** [comment]
> I'd like to avoid the operation=XXX route as much as possible, 

good to hear 

> But i still have the problem that there are certain fields in the request body that are not present in the serializer, but which should be part of all requestbodies using that serializer. Using your example, some pseudo code im imagining would be

so your proposal is certainly something we can talk about. i just have to think a bit about the implications. alternatively, this again would be something that could be approached with a `OpenApiSerializerExtension`. you would just hook into `map_serializer`. do the regular resolution and then piggy-back some more fields onto the `ResolvedComponent`.

`POSTPROCESSING_HOOK` would also be possible. the hooks are there for users to modify at their discretion. so absolutely possible, but doing an extensions would give you more structure. when doing a hook you would go into the registry, patch the `ResolvedComponents`an be done with it. conceptually this would be the doing the same thing as the extension solution, just later in the pipeline and with maybe less safeguards.

i can't really tell you what makes the most sense for you, since i don't know your codebase. we employ both extensions and hooks in our codebase. it depends when one makes more sense than the other. a one-off is probably easier in postprocessing hooks, while recurring things are likely better handled in extensions.

**Comment by AndersJensenBikemap** [comment]
Hey again tfranzel, hope you're having a good friday :)

So i went with the post processing hook route and it works nicely now. And in addition to this im gonna refactor the serializermethodfields we have, but which need to be included in the request body, to another type that will get picked up by the generator.

However im still missing a nice clean way of adding examples and reusing them. In your documentation you seem to put emphasis on using the OpenAPIExample like below for example (taken from your docs):

               examples=[
                    OpenApiExample(
                        'Example 1',
                        summary='short optional summary',
                        description='longer description',
                        value='1993-08-23'
                    ),

I am however still wondering how to reuse examples in a nice and clean way. Some of my request body examples can be really long and take up a lot of screen space, so i dont want to have to add it to each and every operation. Instead it would be nice to reference the example somehow (but still avoiding the usage of the operation=XXX).
Is it for example possible to add examples using the APPEND_COMPONENTS and then reference it with OpenAPIExample ? Something like this:

               examples=[
                    OpenApiExample("$ref": "components.examples.myExample" ),

**Comment by tfranzel** [comment]
hi! glad to hear. 

i agree there is a tendency for duplication. what i do myself is create a `schema.py` file and collect often used things like `OpenApiParameter` and `OpenApiExample`. you can simply reuse those. sure you have the duplication in the schema but that shouldn't matter all that much.

```python
COMMON_EXAMPLES = [
    OpenApiExample(...), OpenApiExample(...) OpenApiExample(...)
]

@extend_schema(examples=[OpenApiExample(...), *COMMON_EXAMPLES])
def retrieve(): ...
```

you can add anything you like to `APPEND_COMPONENTS`. there is no limitation there. however, there is currently no way to reference those as you written in your example. it would be certainly possible to add this but you would still have boilerplate code and you would need to make sure the `$ref` target is always correct. my proposal seems less brittle imho.

**Comment by AndersJensenBikemap** [comment]
Beautiful and elegant solution <3

I made the Common_Examples a dictionary so you can see what example you are referencing :) I really like this solution for now. Lets see if we run into any more problems down the road, but for now this issue is solved :+1:
