### ISSUE TITLE
How do we add more properties to a custom serializer field's schema?

### ISSUE THREAD

**Issue by foucdeg** [tfranzel/drf-spectacular#424]
If I understand the doc correctly, `@extend_schema_field` seems only to allow overriding the `type` property of the schema.

Using base DRF, in order to customize the output of a custom serializer field `PrettyChoiceField`, we would use the following code in a `map_field` function on our custom Schema:

```python
if isinstance(field, PrettyChoiceField):
    data = {"type": "string", "enum": [c[1] for c in field.choices]
```

Using drf_spectacular, `@extend_schema_field` only seems to allow us to change the `type` property, not set the `enum`. How should we do this?

**Comment by tfranzel** [comment]
i'm missing the context for your snippet. not sure where this lives.

`@extend_schema_field` allows for a raw schema dict of the given options are not enough.

generally it should not be necessary to patch the `AutoSchema`. if you need more control there are extensions available for this: https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-field-output-with-openapiserializerfieldextension

those are the two options for custom field behavior.

**Comment by foucdeg** [comment]
Ok thanks, this raw schema dict option for `@extend_schema_field` doesn't seem to be documented unless I read too fast.

**Comment by hosseinmp76** [comment]
@foucdeg Can you give an example of usage of raw schema dict? I can't find any document

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/blob/b136568b81e6566289456d6f1366334b870321c3/tests/test_extend_schema.py#L81

`@extend_schema_field` also lists this option in its doctstring.
