### ISSUE TITLE
OpenApiParameter constructor does not allow `schema` argument?

### ISSUE THREAD

**Issue by foucdeg** [tfranzel/drf-spectacular#425]
According to OpenAPI 3.0.3 [specification](https://swagger.io/specification/#parameter-object), the OpenAPI Parameter object accepts a `schema` property.

The `OpenApiParameter` class in this library does not seem to.

Here is what I wanted to do:

```python
@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                name="created_after",
                required=False,
                location=OpenApiParameter.QUERY,
                description="if the object was created after this date",
                schema={"type": "string", "format": "date-time"},
            ),
            OpenApiParameter(
                name="created_before",
                required=False,
                location=OpenApiParameter.QUERY,
                description="if the object was created before or at this date",
                schema={"type": "string", "format": "date-time"},
            ),
        ]
    )
)
```

and I get the following error: 

> Unexpected keyword argument 'schema' in constructor call

**Comment by tfranzel** [comment]
our interface is close to OpenAPI naming but not identical. please consult the docs and look at the actual parameters it supports. what you want with `schema` is called `type` because its supports multiple things, not just a raw schema.

**Comment by foucdeg** [comment]
ok, I admit I didn't think of trying `type` instead of `schema`, but I assumed `type` wouldn't allow me to set `format` because in OpenAPI they are two different properties.

Beyond the `Any` type hint which I missed, I fail to see where this is documented. But thanks for the answer and for your time.

**Comment by tfranzel** [comment]
i agree that the `Any` is sub-optimal. it's been tricky writing a good hint for these few cases. i'll add some more text as i can see how this can be confusing at first.

**Comment by tfranzel** [comment]
improved the type with 9819424
