### ISSUE TITLE
Default Response Code for post is 200?

### ISSUE THREAD

**Issue by li-darren** [tfranzel/drf-spectacular#428]
**Describe the bug**
When annotating a generics.createAPIView or generics.ListCreateAPIView, it seems as if the default response code for post responses is 200. Should it be 201? I am using drf spectacular auto schema and generator.

**To Reproduce**
Create a class that derives from generics.ListCreateAPIView and look at the post method response.

**Expected behavior**
The default response should be 201.

**Comment by tfranzel** [comment]
hi! you are absolutely right. generally its tricky do guess the right response code, but here it's rather straight-forward. thanks for reporting.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by li-darren** [comment]
Hey I was wondering, is there a release schedule or if you know when we can expect to be able to use this new feature?

**Comment by tfranzel** [comment]
this has been released a month ago
