### ISSUE TITLE
Request serializer is not shown with delete method

### ISSUE THREAD

**Issue by KStenK** [tfranzel/drf-spectacular#431]
**Describe the bug**
When setting request serializer to delete method, then it is not appearing to Swagger UI.

**To Reproduce**
```
# views.py

class TestView(RetrieveDestroyAPIView):

    @extend_schema(request=DeleteSerializer)
    def delete(self, request, *args, **kwargs):
        # doing things
        return super().delete(request, *args, **kwargs)
```

**Expected behavior**
The request body is shown on the Swagger UI docs page.

**Comment by tfranzel** [comment]
Request body for DELETE is undefined, but generally it is not forbidden. however, OpenAPI does not support `requestBody` for methods with undefined behaviors. https://swagger.io/specification/#operation-object / https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.5 

>   A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request.

this might also be interesting: https://github.com/OAI/OpenAPI-Specification/issues/1801 i think i tried it before and schema validation failed.

**Comment by KStenK** [comment]
All right, thanks for the information.

Then I have to write some details to the description field.
