### ISSUE TITLE
ModelMultipleChoiceFilter - wrong field format in request url

### ISSUE THREAD

**Issue by lderlecki** [tfranzel/drf-spectacular#433]
Hi,

I am using ```django-filters``` ```ModelMultipleChoiceFilter```. I am running into a problem where values from the input field are not correctly converted to the django-filters format, i.e. ```filter_field=value_1&filter_field=value_2&...```. The value from the input field is treated as one value (none of the separators seem to work, the format of query params in request is like ```filter_field=value_1,value_2,...```). 

The filter that I have looks something like this:

``` python
from django_filters import rest_framework as filters
from django.contrib.auth.models import User

class TeamFilterSet(filters.FilterSet):
    members = filters.ModelMultipleChoiceFilter(
        label=_('Filter by member IDs'),
        field_name='members',
        queryset=User.objects.all(),
    )
```

Is it possible to obtain the expected format in the request url or do I have to override the actual filter to get the proper values from the request?

**Comment by tfranzel** [comment]
hi! i believe the test do contain this and i think it works as expected.

https://github.com/tfranzel/drf-spectacular/blob/deb83250f078ed4bce17b12972e098409ac69ec9/tests/contrib/test_django_filters.py#L98

https://github.com/tfranzel/drf-spectacular/blob/deb83250f078ed4bce17b12972e098409ac69ec9/tests/contrib/test_django_filters.yml#L76-L86

which swagger UI translates to `https://editor.swagger.io/products/?model_multi_cat=A&model_multi_cat=B`. isn't this what you expected?

**Comment by lderlecki** [comment]
Thank You for the quick reply! 
Yes, that is what I expect, but in this case you are using the category field, which is an enum field. 
https://github.com/tfranzel/drf-spectacular/blob/deb83250f078ed4bce17b12972e098409ac69ec9/tests/contrib/test_django_filters.py#L45-L50
The problem in this case is that I am using a FK field in ```ModelMultipleChoiceFilter``` which out of the box is translated into 
```yaml
parameters:
    - name: owner_id
      required: false
      in: query
      description: Filter by owner IDs
      schema:
          type: string
```
To ilustrate the example, when I have such model for team
```python
class Team(models.Model):
    owner = models.ForeignKey(to='User', on_delete=models.CASCADE())
```
and I want to filter teams by owner ID:
```python
class TeamFilterSet(filters.FilterSet):
    owner_id = filters.ModelMultipleChoiceFilter(
        label=_('Filter by owner IDs'),
        field_name='owner_id',
        queryset=User.objects.all(),
    )
```
I have tried using different variations of queryset, like ```User.objects.values_list('id', 'username')``` to get the "enum representation" of User model, but none of them worked. 
After spending some more time I found the [#267](https://github.com/tfranzel/drf-spectacular/issues/267#issuecomment-764068843) issue, which helped me solve the problem by decorating the class based view like this:
```python
@method_decorator(name='get', decorator=extend_schema(
    parameters=[OpenApiParameter(
        name='owner_id',
        type={'type': 'array', 'items': {'type': 'number'}},
        location=OpenApiParameter.QUERY,
        required=False,
        style='form',
        explode=True,
    )]
))
class TeamListAPIView(ListAPIView):
    queryset = Team.objects.all()
    serializer_class = TeamListSerializer
    filterset_class = TeamFilterSet
```

**Comment by tfranzel** [comment]
so i was about to say that we also have the non-enum case with `model_multi_cat_relation` in both the same yaml and test files. as you can see this also has not "enum" and that is on purpose.

i have not realized you wanted the enum listing for FK relations. we do not allow that because it would leak your whole database into the schema. by default this is definitely not desirable.

**Comment by lderlecki** [comment]
we did not understand each other. I didn't wat to have the enum listing for FK relation, I only mentioned it to show the solutions I tried. 

Oh, I didn't notice the ```model_multi_cat_relation``` field, but , I don't know why, but it is not working in my case. The field in schema is generated as a ```string_field```. The only difference I can see between my views and the tests is that I am using DRF generic ```APIViews```. I had the same problem with ```BooleanFilter```, I had to manually override parameters directly in the view class, otherwise all parameters were generated as ```string_field```.

In my case it is as follows:
```python
from django_filters import (
    rest_framework as filters,
    BooleanFilter,
    ModelMultipleChoiceFilter
)

class Team(models.Model):
    name = models.CharField(max_length=255)    
    owner = models.ForeignKey(to='User', blank=True, null=True, on_delete=models.CASCADE())


class TeamFilterSet(filters.FilterSet):
    owner_id = filters.ModelMultipleChoiceFilter(
        label=_('Filter by owner IDs'),
        field_name='owner_id',
        queryset=User.objects.all(),
    )
    has_owner = BooleanFilter(
        field_name='owner',
        label=_('Filter teams with owner.'),
        lookup_expr='isnull',
        exclude=True,
    )

    class Meta:
        model = Team
        fields = {
            'name': ['iexact', 'icontains']
        }


class TeamListSerializer(serializers.ModelSerializer):
    class Meta:
        model = Team
        fields = ('id', 'name', 'owner')


class TeamListAPIView(ListAPIView):
    queryset = Team.objects.all()
    serializer_class = TeamListSerializer
    filterset_class = TeamFilterSet
```
I want docs to be generated inside team module and only for that module, so the ```urlpatterns``` looks like this:
```python
urlpatterns = [
    path('team/list/', TeamListAPIView.as_view(), name='team_list_api'),
    path('team/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('team/docs/', SpectacularSwaggerView.as_view(url_name='team:schema'), name='swagger_ui'),
]
```
and in my settings file I have:
```python
SPECTACULAR_SETTINGS = {
    'TITLE': 'API',
    'DESCRIPTION': 'Docs',
    'VERSION': None,
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_URLCONF': 'team.urls',
}
```

**Comment by lderlecki** [comment]
Okay, I found a reason for this behavior.
The problem was that I have implemented by own ```FilterBackend```. I'm not sure why, but when i leave my custom filter backend like:
```python
class MyFilterBackend(filters.DjangoFilterBackend):
    pass
```
and my ```drf_settings```:
```python
'DEFAULT_FILTER_BACKENDS': [
    'rest_framework.filters.OrderingFilter',
    'filters.MyFilterBackend',
],
```
this causes the filters to be incorrectly translated into the schema
After changing it to this:
```python
'DEFAULT_FILTER_BACKENDS': [
    'rest_framework.filters.OrderingFilter',
    'django_filters.rest_framework.DjangoFilterBackend',
],
```
everything works fine. Is this the expected behavior?

**Comment by tfranzel** [comment]
ahh now i get it!  the schema you receive comes from `django-filter` itself. they generate a filter schema themselves but that is pretty much useless almost all of the time because they don't have the introspection tooling we have.

our extension does not active as it is a different class. we can match subclasses but it is safer not to by default when you do custom stuff. 

simply define a new extension based on the existing one. this should do it for you

```python
from drf_spectacular.contrib.django_filters import DjangoFilterExtension

class CustomDjangoFilterExtension(DjangoFilterExtension):
   target_class = 'django_filters.rest_framework.DjangoFilterBackend'
   priority = 1
   match_subclasses = True
```

**Comment by lderlecki** [comment]
Yes, this solution works! Thank you so much for your help!
