### ISSUE TITLE
allOf enums

### ISSUE THREAD

**Issue by NANASHI0X74** [tfranzel/drf-spectacular#434]
Hi, I'm trying to switch to a new dart code generator (because of dart's new null safety fratures). That code generator has problems with the way enum fields are modeled with allOf by this scheme generator, e.g.
```yaml
components:
  schemas:
    CategoryEnum:
      enum:
      - Gloves
      - Clothes
      - Shoes
      - mask
      type: string
    SomeModel:
      type: object
      properties:
        category:
          allOf:
          - $ref: '#/components/schemas/CategoryEnum'
          nullable: true
```
The reason why the problems come up is that the new generator generates enums differently, as actual enums instead of regular classes with a bunch of static members of itself. The enum methods for conversion etc. have to be referenced differently than other types though, but when the model's enum field is included via an allOf construct, it's not recognized as an enum but as another model. So the generated code is wrong.

Now my question is what's the prupose of this modelling/ why does spectacular do it this way? And can it be turned off? :D

**Comment by tfranzel** [comment]
hi! this is a quirk of OpenAPI. if there would not be a `allOf`, the `$ref` replacement would wipe out the `nullable` as it is hosted in the same scope. we automatically add this "scope guard" if there are additional fields like `nullable`.

as this is a OpenAPI limitation we cannot really do anything about it. you can turn off enum extraction by removing the `postprocessing_hook` from the default setting, but that is not good solution either.

**Comment by NANASHI0X74** [comment]
Do you have a suggestion on how to handle this in a vode generator? :D I've fixed a few other issues that I had already, but this is a bit trickier... I was thinking of parsing the jsonSchema in the openapi-generators correctInternals phase and checking if it's an allOf ConposedSchema containing a single enum and if so, set isEnum on the property to true.
I've just not found out what part of the generator parses json specs to schema objects yet 😅

**Comment by tfranzel** [comment]
hehe... the `openapi-generator` has been cryptic to me too. i also have a hard time locating stuff in that codebase. i don't really have a tip for you here. all i can say is that some generator targets have a higher quality / completeness than others.

as i mentioned, you can try to disable enum generation in spectacular and see if that gets you further. the enums are then all inlined so your mileage may vary depending on how smart that target is.

**Comment by NANASHI0X74** [comment]
I might as well try that then... What would be the problem(s) with inline enums? Is it that they get nondescriptive names in that case?

**Comment by tfranzel** [comment]
yes, most likely.

**Comment by NANASHI0X74** [comment]
I hacked something into the code generator to treat schemas of this kind as enums.
The maintainer pointed out that nullable is apparently removed and replaced by type arrays in OAS 3.1: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

**Comment by tfranzel** [comment]
yes indeed. OpenAPI 3.1 is fully based on JSON Schema in contrast to OpenAPI 3.0.3. once support is ramping up, we will look at this again. right now tooling support is just not fully there yet and thus this fix would probably create more issues than it solves.

the way we do it right now is the one and only "correct" way to do in 3.0.3. i'll be happy to change this in the future.
