### ISSUE TITLE
Custome PAGINATION_CLASS

### ISSUE THREAD

**Issue by mituso89** [tfranzel/drf-spectacular#437]
Not really a bug.

This is default result of spectacular
```
{
  "count": 123,
  "next": "http://api.example.org/accounts/?page=4",
  "previous": "http://api.example.org/accounts/?page=2",
  "results": [ ]
}
```
For now i want to custom it How can I overwrite PAGINATION_CLASS in  spectacular

For example: 
```
{
  "count": 123,
  "page": 3
  "next": "http://api.example.org/accounts/?page=4",
  "previous": "http://api.example.org/accounts/?page=2",
  "items": [ ],
  "extras": {}
}
```
```
pls give any idea to resolve that. Thanks you so much

**Comment by tfranzel** [comment]
you probably have a custom `PAGINATION_CLASS`. 
it contains a pre-packaged schema that we use by calling `get_paginated_response_schema`. you need to customize this in your own pagination class implementation.

For query parameters you can override `get_schema_operation_parameters`. In that case we also do support extensions (`OpenApiFilterExtension`) but i believe implementing those two methods directly is the best course of action.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
