### ISSUE TITLE
Pre-populating OAuth Client ID

### ISSUE THREAD

**Issue by jfach** [tfranzel/drf-spectacular#438]
Is it possible to pre-populate the OAuth Client ID when clicking the Authorize button?

In DRF YASG, I'm able to accomplish this by specifying the following configuration in the `SWAGGER_SETTINGS` dict:

```
"OAUTH2_CONFIG": {"clientId": "my_client_id_here"}
```
 Is there a way to do this with DRF Spectacular?

**Comment by tfranzel** [comment]
hi! i added the config `SWAGGER_UI_OAUTH2_CONFIG` for this. it should work as with yasg. could you test this on master? thanks.

**Comment by jfach** [comment]
Hi @tfranzel ! I really appreciate the speedy resolution to this issue, thank you! I just tested it out and it works perfectly, there was a little typo in the `swagger_ui.js` file when performing a check to see if oauth2 settings were provided. I have submitted this in a PR.

Thanks again for your help!

**Comment by tfranzel** [comment]
you're welcome. glad it worked out. thanks for fixing that typo! it will be part of the next release, however that might take a moment as i usually wait for 2-3 things to pool before doing a release. just so you know.
