### ISSUE TITLE
How do I set required=False to SerializerMethodField?

### ISSUE THREAD

**Issue by li-darren** [tfranzel/drf-spectacular#443]
Right now, I have a read only field where I am trying to create a serializer method field and set required=False. It is currently both read only as a field property and in the list of required for the schema. When I set other values like allow_blank or blank, it says the keyword is not recognized. When I set required=False in the serializer, there are no errors, but in the schema, it seems to show up as required still and also read only. Using read_only_fields in Meta doesn't seem to change behaviour either, as the field is both required and read only. Do you know why this may be the case? Is it even possible to have both read_only and required field set to true for a serializermethodfield?

I'm using Django==2.2.22

**Comment by tfranzel** [comment]
hi! this is the behavior of DRF. `SerializerMethodField` is always present (thus `required` in schema) and always read-only by definition. manual field declarations always supersede `Meta.read_only_fields`. 

> When I set other values like allow_blank or blank, it says the keyword is not recognized.

this is how DRF chose to handle the parameters. nothing to do with us specifically.

see this example from the tests:
https://github.com/tfranzel/drf-spectacular/blob/cd8f73c34412cf1613d7dbffed6eb6a004945af6/tests/test_basic.py#L33
https://github.com/tfranzel/drf-spectacular/blob/cd8f73c34412cf1613d7dbffed6eb6a004945af6/tests/test_basic.yml#L258

you can only influence the return type via type hint, but the `read-only` and `required` are fixed by DRF.

**Comment by li-darren** [comment]
hmmm that's interesting... What if we generate this SerializerMethodField in the serializer rather than having it as a parameter passed into the endpoint in the request? Would it be confusing for API consumers to see this as a required field then, as we generate the field for them?
What do you mean by "always present"?
Is there no way to change the required field at all then?

**Comment by tfranzel** [comment]
`required` can be changed, just not for `SerializerMethodField`.

required and readonly do work together according to OpenAPI3. if a field is read-only it is by definition only required on responses and NOT on request. some client generators do not honor that. for those cases we have specific settings. we genereally recommend `"COMPONENT_SPLIT_REQUEST": True` as it yields the most accurate schema (also wrt `required`). 

```python
    # Split components into request and response parts where appropriate
    'COMPONENT_SPLIT_REQUEST': False,
    # Aid client generator targets that have trouble with read-only properties.
    'COMPONENT_NO_READ_ONLY_REQUIRED': False,
```

**Comment by li-darren** [comment]
Wouldn't these be mutually exclusive then?
For example if I want my SerializerMethodField to only be in the output and not the input, then I would set read-only to be true. But then, SerializerMethodField have required=True by default. Wouldn't that mean that it is expecting this field to be present in deserialization?

**Comment by tfranzel** [comment]
`COMPONENT_SPLIT_REQUEST=True` is best imho, but you end up with 2 components (req/resp) for each serializer. it's the most accurate. 

`COMPONENT_NO_READ_ONLY_REQUIRED=True` is when you need to fix `required` without splitting (req/resp) the serializers. 

these are not 100% mutually exclusive but generally it makes only sense using one of those. on very rare occasions you may need both, but you will know for sure when it comes to that.
