### ISSUE TITLE
Values in schema examples instead of "string"

### ISSUE THREAD

**Issue by elvirTatarevic** [tfranzel/drf-spectacular#447]
Hello,

We would like to be able to set the value on a CharField that is required so that it displays a value we want instead of simply saying "string". ![image](https://user-images.githubusercontent.com/81384128/124162006-46d25280-da5b-11eb-829e-6cb004a57ccb.png)

In other fields, this happens by default or if we have a default set it will work. 

So my question to you, is there a way that we can achieve this?

Thank you.

**Comment by tfranzel** [comment]
Hi,

Swagger UI will try to do something reasonable based on the schema. The schema itself does not make such statements, except for when you declare explicit examples.

We do support specifying examples, but not a field level at the moment. you would need to create a `OpenApiExample` instance and inject it via one of the decorators, e.g. `@extend_schema`, `@extend_schema_serializer`

```python
@extend_schema_serializer(examples=[OpenApiExample(....)])
class XSerializer(Serializer):
    .....
```

have a look at the tests for different ways on how to use it: https://github.com/tfranzel/drf-spectacular/blob/master/tests/test_examples.py

**Comment by elvirTatarevic** [comment]
Thank you for the response, and since you mention the examples let me ask another question. 

We tried to apply something like this to our viewSet.

```python
@extend_schema_serializer(
		many=True,
		examples=[
			OpenApiExample('Body',
			value={
				"sample1": "sample1",
				"sample2": "sample2",
				"sample3": "sample3",
				"sample4": "sample4",
				"sample5": "sample5",
			},
			status_codes=['201'])
		]
	)(
		inline_serializer(
			name="SampleSerializer",
			fields={
				"sample1": serializers.CharField(required=True),
				"sample2": serializers.CharField(required=True),
				"sample3": serializers.CharField(required=True),
				"sample4": serializers.CharField(
					required=False, allow_blank=True, allow_null=True
				),
				"sample5": serializers.DateTimeField(required=True),
			},
			many=True,
		),
	),
```	

It worked well when the inline_serializer did not have many set to True. However, when it was set to True the example did not show up. Any thoughts on that?

**Comment by tfranzel** [comment]
this looks a bit weird to me. `extend_schema_serializer` is for decorating serializer classes. you cant really use it views. for that we have `@extend_schema`. see the test file above for reference. almost all valid use cases should be in there.

also it should not be necessary to have to put `many=True` both in the decoration and the serializer. one should suffice.

can you put that in a small viewset for example? its easier to reason about.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
