### ISSUE TITLE
Ability to choose file from UI

### ISSUE THREAD

**Issue by nlarusstone** [tfranzel/drf-spectacular#455]
Hey @tfranzel,

First of all, thanks for the great library! 

I'd like to get a file picker to show up on the Swagger UI (I believe this is possible, but if not then let me know). My understanding was that I should be able to do that using the `FileUploadParser` and `extend_schema`. However, when I try to get it it just seems to think the field is a string field.

Here's the relevant part of my code:
```
class SamplesheetSerializer(Serializer):
    file = serializers.FileField()

class SamplesheetView(APIView):
    parser_classes = [FileUploadParser]

    @extend_schema(request=SamplesheetSerializer)
    @action(detail=False, methods=['post'])
    def post(self, request: Request, filename: Optional[str] = None):
         ...
```

And here's the Swagger it generates:
<img width="1362" alt="Screen Shot 2021-07-12 at 1 57 49 PM" src="https://user-images.githubusercontent.com/7347808/125354855-276bdd00-e319-11eb-8007-c7da2ae931e3.png">

Any help/hints would be greatly appreciated!

**Comment by tfranzel** [comment]
hi and thanks! so there are two problems i think. 

1. duality req/resp: https://drf-spectacular.readthedocs.io/en/latest/faq.html#filefield-imagefield-is-not-handled-properly-in-the-schema . this is simply a limitation of OpenAPI and you would need to use the req/resp component split to differentiate the 2 cases.
2. `FileUploadParser` generates `*/*` which is not recognized by swagger ui. when using `MultiPartParser` (`multipart/form-data`) this looks fine for me in swagger ui.

**Comment by nlarusstone** [comment]
So I changed to `MultiPartParser`: `parser_classes = [MultiPartParser]` and updated the settings: 
```
SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,
    ...
```

But I'm still not getting what I expect in the UI:

<img width="1368" alt="Screen Shot 2021-07-13 at 8 56 59 AM" src="https://user-images.githubusercontent.com/7347808/125485114-3f715b31-e0cb-444e-9d63-a5543e769644.png">

**Comment by tfranzel** [comment]
click "try it out" :grin: select file should show up then. i tested it earlier

**Comment by nlarusstone** [comment]
Oooh you're right -- that's my bad. Thanks so much for your help!
