### ISSUE TITLE
Private endpoints or hide schema?

### ISSUE THREAD

**Issue by li-darren** [tfranzel/drf-spectacular#459]
Is there any way to hide the schema generation for a view all together? I know you can set exclude=True for specific http methods, but can it be done for an entire url?

**Comment by tfranzel** [comment]
```python 
    @extend_schema(exclude=True)
    class TestViewSet(viewsets.ModelViewSet):
        queryset = SimpleModel.objects.all()
        serializer_class = SimpleSerializer
```

**Comment by li-darren** [comment]
am I mistaken to think that for views, @extend_schema_view must be used?

**Comment by tfranzel** [comment]
ok i can see how this is confusing with all the magic going on. consider it a shortcut. generally you want to use `@extend_schema_view`, but here it is simply more concise to not do it.

- `@extend_schema` on views applies to all endpoints in that view.
- `@extend_schema_view` on views apply to that specific endpoint mentioned in the `kwargs`
- `@extend_schema` on view methods or `@api_view` applies to that specific endpoint only

furthermore these decorators can be stacked on top of each other (layered).

**Comment by li-darren** [comment]
thanks for the info :)
