### ISSUE TITLE
View without serializer_class

### ISSUE THREAD

**Issue by AqeelAT** [tfranzel/drf-spectacular#464]
Hi,

I have some views that do not have serializer_class variables, but I kept getting an error even I have `@extend_schema` with a response serializer. Is there a way around that?

```
Error #0: MyAPIView: exception raised while getting serializer. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'MyAPIView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.)

```

Thanks

**Comment by tfranzel** [comment]
hi @AqeelAT, spectacular attempts to fetch the serializer for requests and responses where neccecary. if you have a POST request but no `@extend_schema(request=XXX, responses=XXX)` it will still try to get the serializer for these parts. adding also `request=XXX` should remove the warning.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
