### ISSUE TITLE
Schema collision bug

### ISSUE THREAD

**Issue by AqeelAT** [tfranzel/drf-spectacular#465]
I'm getting this collision, even though both APIs have different views and serializers

The warning:
```
Warning #0: operationId "orders_shipments_list" has collisions [('/api/orders/{id}/shipments/', 'get'), ('/api/orders/shipments/', 'get')]. resolving with numeral suffixes.
```

the URL file:
```
path('shipments/', ShipmentListApi.as_view(), name="shipment_list"),
...
path('<int:pk>/shipments/', OrderShipmentListApi.as_view(), name="order_shipments_list"),
```

Shouldn't they be: `orders_order_shipments_list` and `orders_shipments_list_api`? 

Is this a bug or is this the intended behavior since they're similarly named?

**Comment by tfranzel** [comment]
1. the variable names are stripped in name generation. so this is expected to happen in this case.
2. the fact that the `order_` prefix is missing can have 2 reasons. the prefix finder determined that all endpoints in the API are `/api/orders/` prefixed. this will dissapear once you have something else in the API that is prefixed differently. you can also manually influence this with: https://github.com/tfranzel/drf-spectacular/blob/f7f539ba64e6806cc3f513562676bd583c9afebd/drf_spectacular/settings.py#L12

i would recommend resolving the naming issue by using `@extend_schema(operation_id=XXX)` on one of those `ListApiViews`. something like

```python
   @extend_schema_view(get=extend_schema(operation_id="your_custom_name_list"))
    class XView(generics.ListAPIView):
        serializer_class = XSerializer
```

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
