### ISSUE TITLE
Customize bearer token in authorization header

### ISSUE THREAD

**Issue by tombra4ril** [tfranzel/drf-spectacular#467]
Hi,
I am using simplejwt for authentication. To authorize users for a particular endpoint the authorization header should contain the bearer token (JWT) followed by the access token but spectacular uses bearer as the default even after specifying `"AUTH_HEADER_TYPES": ("JWT",)` in simple_jwt configuration in my `settings.py` file.

**Headers sent**
curl -X POST "http://localhost:8000/api/v1/auth/test" -H  "accept: */*" -H  "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI3Mjc0MTYzLCJqdGkiOiIwMjU2NjAyOWViZDg0NDk4OWU2Y2QyMTgwNzc0YTczZ..." -H  "X-CSRFToken: lioQLVfM4CLuI2cSVXE1MtXRBeAHYHH6FnlmUGqkKpnqd2PmNFQ9Yrop323tOu6q" -d ""

**Expected headers**
curl -X POST "http://localhost:8000/api/v1/auth/test" -H  "accept: */*" -H  "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI3Mjc0MTYzLCJqdGkiOiIwMjU2NjAyOWViZDg0NDk4OWU2Y2QyMTgwNzc0YTczZ..." -H  "X-CSRFToken: lioQLVfM4CLuI2cSVXE1MtXRBeAHYHH6FnlmUGqkKpnqd2PmNFQ9Yrop323tOu6q" -d ""
Thanks for your response in advance.

**Comment by tfranzel** [comment]
Hi,

so we do use the `AUTH_HEADER_TYPES`: 
https://github.com/tfranzel/drf-spectacular/blob/0c1fe0eeedbb4bb24c80ca74e472dc46ca80b7d5/drf_spectacular/contrib/rest_framework_simplejwt.py#L66

Do you use a custom version of `rest_framework_simplejwt.authentication.JWTAuthentication`? the extension might not be used by default then.

**Comment by tombra4ril** [comment]
Thanks for your quick response.
I am using the standard `rest_framework_simplejwt`, only customizing my own `TokenObtainPairView` class to obtain the access token and refresh token.

**Comment by tfranzel** [comment]
this is indeed a bug. same thing was fixed for DRF's TokenAuthentication but it was forgotten here. 

however, the solution to this is not perfect. OpenAPI3 does not directly support customizing "Bearer". When you use non-"Bearer", you will need to put the whole shabang into SwaggerUI, i.e. `JWT 1234deadbeef` and not just the token. A comment however will document this. 

preparing a fix right now.

**Comment by tombra4ril** [comment]
Thanks alot.
Adding a non-bearer authentication header type such as `JWT` before the access token, the swagger ui (drf_spectacular) always prefixed the authorization header with `Bearer` which will make the authorization header fail because it is now `Bearer JWT 1234deadbeef...`.
So, I just reverted back to using Bearer as the `AUTH_HEADER_TYPES` in SIMPLE_JWT configuration in `settings.py` file.  This can as well do the job while I wait for the fix.
Thanks alot.

**Comment by tfranzel** [comment]
@tombra4ril yes that was the problem. with this commit "Bearer" is not prefixed anymore, iff it is some other value like "JWT".

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by tombra4ril** [comment]
@tfranzel sorry for the delay. Was able to install this fix commit and the authorization bug has been fixed, thanks a lot.

**Comment by tfranzel** [comment]
Hi @SidneyNiccolson, so `bearerFormat: ` is actually non-functional and purely for documentation purposes. it **does not** specify the the prefix keyword in the header. this certainly confused me the first go round.

the documentation suggests this and SwaggerUI actually implements it like that. afaik there is no way to specify a hard-coded prefix in OpenAPI 3.0.3 other than `Bearer`. That workaround is the only working solution i am aware of. 

you can try this yourself with https://editor.swagger.io/. the last time i tried fiddling around with `bearerFormat`, it had zero effect. feel free to suggest a better solution :smile:

**Comment by deepakkumhar** [comment]
hello,
how can i change name of security (exmple-jwtauth to breareauth) in Django swagger spectacular

**Comment by tfranzel** [comment]
@deepakkumhar it depends on which lib you are using: `rest_framework_jwt` or `rest_framework_simplejwt`. generally you would override the existing extension with higher priority and change the name. just put that extension where the interpreter sees it at least once.

```python

from drf_spectacular.contrib.rest_framework_simplejwt import SimpleJWTScheme

class CustomSimpleJWTScheme(SimpleJWTScheme):
    name = 'breareauth'
    priority = 1
```

or 

```python

from drf_spectacular.contrib.rest_framework_jwt import JWTScheme

class CustomJWTScheme(JWTScheme):
    name = 'breareauth'
    priority = 1
```

**Comment by deepakkumhar** [comment]
how can i remove auto genrate 

> @deepakkumhar it depends on which lib you are using: `rest_framework_jwt` or `rest_framework_simplejwt`. generally you would override the existing extension with higher priority and change the name. just put that extension where the interpreter sees it at least once.
> 
> ```python
> from drf_spectacular.contrib.rest_framework_simplejwt import SimpleJWTScheme
> 
> class CustomSimpleJWTScheme(SimpleJWTScheme):
>     name = 'breareauth'
>     priority = 1
> ```
> 
> or
> 
> ```python
> from drf_spectacular.contrib.rest_framework_jwt import JWTScheme
> 
> class CustomJWTScheme(JWTScheme):
>     name = 'breareauth'
>     priority = 1
> ```

thank you 👍

**Comment by deepakkumhar** [comment]
@tfranzel 
how can i remove or hide auto generate schema in drf_spectacular  like my enum field generating separate schema  so i want to remove it.
,i am using Django rest framework for api

**Comment by deepakkumhar** [comment]
how can i remove or hide auto generate schema in drf_spectacular like my enum field generating separate schema so i want to remove it.
,i am using Django rest framework for api
