### ISSUE TITLE
Using a custom django model field with ArrayField

### ISSUE THREAD

**Issue by tiholic** [tfranzel/drf-spectacular#470]
**Describe the bug**
A nested array schema is created for a custom field that is used as a child of ArrayField:

![image](https://user-images.githubusercontent.com/14252381/127285732-fbec854d-56a4-4f02-b36e-d685c4f9b42b.png)

**To Reproduce**
requirements.txt
```
django-relativedelta==1.1.2
```

model
```py
from relativedeltafield import RelativeDeltaField

class MyModel:
    allowed_frequencies = ArrayField(RelativeDeltaField(), null=True)
```

It goes to `openapi.py#567` > `openapi.py#686` with child field > and in `openapi.py#400` `build_field` will return data for the parent field as the model and field name point to `MyModel.allowed_frequencies`. Nested model fields need special handling.

**Expected behavior**
Expect the schema to be an array of string

**Comment by tfranzel** [comment]
hi! we do not support arbitrary django extensions. some are natively supported, some may just work, and others break some internal assumptions.

here, it looks like the latter. i assume you need to write a `SerializerFieldExtension` for the corresponding DRF field.

**Comment by tiholic** [comment]
Okay! Can you share any references on how to? I can't seem to find any.

**Comment by tiholic** [comment]
Created a custom field with annotation as mentioned here, and it works good.
https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-3-extend-schema-field-and-type-hints
