### ISSUE TITLE
SERVE_AUTHENTICATION seems not working

### ISSUE THREAD

**Issue by masb3** [tfranzel/drf-spectacular#471]
I have DRF settings with Auth classes as following: 
`REST_FRAMEWORK = {
       "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema"
}`

However in schema I would like to expose only `TokenAuthentication`. For that I add settings 
`SPECTACULAR_SETTINGS = {
    "SERVE_AUTHENTICATION": ["rest_framework.authentication.TokenAuthentication"],
}`
But output schema still has `basicAuth` and `tokenAuth` under `securitySchemes` and in all endpoints under `security`. 
Any idea how to serve only `TokenAuthentication`?

**Comment by tfranzel** [comment]
Hi,

`SERVE_AUTHENTICATION` only applies to the auth mechanism under which the schema is served (e.g. `SpectacularApiView`). it has not effect on the schema itself.

i believe your request is a duplicate of #326

given that this was now requested by several people, i think a setting is the most appropriate solution.

**Comment by masb3** [comment]
Thank you @tfranzel that exactly I was looking for!
