### ISSUE TITLE
How can I disable schema for patch requests across all APIs

### ISSUE THREAD

**Issue by tiholic** [tfranzel/drf-spectacular#473]
Currently I'm using this on all my viewsets:

```
@extend_schema_view(
    partial_update=extend_schema(exclude=True),
)
class MyViewSet(...):
  ...
```

Any better suggestions?

**Comment by tfranzel** [comment]
there is no mechanism at the moment to do this everywhere. i would suggest patching `AutoSchema`

**Comment by tiholic** [comment]
Okay! Will try that. Thanks.
