### ISSUE TITLE
Issue due to minor bump to version 0.18.0

### ISSUE THREAD

**Issue by casellimarco** [tfranzel/drf-spectacular#484]
When bumping from 0.17.3 to 0.18.0 in the docker container we got this error:
```
SystemCheckError: System check identified some issues:

 ERRORS:
 ?: (drf_spectacular.E001) Schema generation threw exception "Invalid URL 'http:///api/openapi': No host supplied"

```
Rolling back solved the issue. Sorry for not being able to give more context.

**Comment by casellimarco** [comment]
Just run tests with version `0.18.1` and no `SILENCED_SYSTEM_CHECKS` and it worked fine! Many thanks for the patch!

**Comment by tfranzel** [comment]
awesome!
