### ISSUE TITLE
Unknown command: 'spectacular'

### ISSUE THREAD

**Issue by gillerst1** [tfranzel/drf-spectacular#493]
**Describe the bug**

Install drf-spectacular using Pipfile on my docker image(python 3.8)
Unknown command: 'spectacular' appears when set as written in the document and command is entered
What am I supposed to do?

**Comment by gillerst1** [comment]
using 

Django 3.2.7
Django Rest Framework 3.12.4

**Comment by tfranzel** [comment]
looks like the app is not registered in the project. Django only discovers commands for registered apps. please follow all the steps to make it work. 

```python
INSTALLED_APPS = [
    # ALL YOUR APPS
    'drf_spectacular',
]
```

**Comment by tfranzel** [comment]
are you running `./manage.py spectacular`? please post the console output. I can't really help like that

**Comment by gillerst1** [comment]
This screenshot is connect to docker bash and command error occurred

![Screen Shot 2021-09-01 at 10 48 11 PM](https://user-images.githubusercontent.com/47441670/131683551-0756c93e-8fff-4a09-a8ef-e47fffae9e0c.png)

If you want my project file, I can invite you to a private repo.

**Comment by gillerst1** [comment]
Oh my gosh, That's right

I separated the setting files(for env), and when I entered another command, I put in the --settings= option.

I wasn't thinking about this. I'm sorry.

Thank you very much for your answer.
