### ISSUE TITLE
@extend_schema_view or @extend_schema not working

### ISSUE THREAD

**Issue by megazza** [tfranzel/drf-spectacular#494]
Hi

Nice work on drf-spectacular first of all.   

We have a piece of work ongoing where we have an old app with a non strategic look and feel from an API documentation perspective being moved to a new app which simply sets up the new urls/views and redirects logic back to the old app models and business logic.

We are therefore not using serializers and deal with model updates via our code (be it right or wrong :)).

We can make our new api/v2 endpoints appear, but when we try and use @extend_schema on the @action or @extend_schema_view on the  view class, it is not rendering our override in swagger.

I have created a simplified version shown below:

# base/urls.py

```
app_name = 'base'

router = DefaultRouter(trailing_slash=False)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v2/', include('pet.urls', namespace='v2-pet')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger')
]
```

# pet/urls.py

```
app_name = 'pet'

router = SimpleRouter(trailing_slash=False)

urlpatterns = router.urls + [
    path('dog/<str:dog_id>/groom', GroomViewSet.as_view({"put": "groom"}))
]
```

# pet/serializers.py 

we did this so swagger presented what we want in the request documentation for the PUT body - we also end up seeing this in the response which we expected our @extend_schema implementation to allow us to override.  Not  using modelSerializer as we do not want any model serialization/deserialization

```
class GroomSerializer(serializers.Serializer):
    order = serializers.CharField(max_length=15)
    cutSize = serializers.CharField(max_length=15)
```

# pet/views.py

simple update expecting our resposne docuemntation to be reflected - but it appears not to work and we only see our serializer information

```
@extend_schema_view(
    update=extend_schema(description='my repsonses', responses={
        200: OpenApiResponse(response=str, description='chekcing this works.'),
        400: None,
        501: int,
    })
)
class GroomViewSet(viewsets.ModelViewSet):

    serializer_class = GroomSerializer

    @action(methods=["put"], detail=True)
    def groom(self, request, *args, **kwargs):
        return get_groom(kwargs['dog_id'])

    
def get_groom(dog_id):

    return Response('yeah', status=status.HTTP_200_OK)
```

# swagger UI render

The result is no override and our default serializer being rendered:

![swagger](https://user-images.githubusercontent.com/10231323/131704674-9fc67362-4294-4e0e-8eca-402bd1a12a43.PNG)

Would you expect the @extend decorators to work here?  I read they support @action.

**Comment by tfranzel** [comment]
Hi @megazza, thanks :smile: 

`extend_schema_view` is a convenience shortcut, but you have to target the proper action. you changed the `PUT /api/v2/dog/{dog_id}` on the viewset, not the `groom` action.  

decorating actions is also supported, so your usage of `extend_schema_view` was kind of unnecessary. its mainly targeted to overriding things like `list` in `ModelViewsets`, where you have no method to attach the decorator to.

have a look at this test, which contains a bunch of variations:

https://github.com/tfranzel/drf-spectacular/blob/58c13dfb04f41527ec4f685720a116ed6435e696/tests/test_extend_schema_view.py#L24-L46

this convenience breaks if you have an action with multiple methods. in that case have a look here:

https://github.com/tfranzel/drf-spectacular/blob/58c13dfb04f41527ec4f685720a116ed6435e696/tests/test_regressions.py#L341-L360

**Comment by megazza** [comment]
Thanks @tfranzel  - the issue I had was a custom decorator was not returning the changed data through. I reordered them and it now works.
