### ISSUE TITLE
How can I exclude_fields only requestBody?

### ISSUE THREAD

**Issue by gillerst1** [tfranzel/drf-spectacular#495]
This is my serializer code

```
@extend_schema_serializer(
    examples=[swagger_schemas.user_login_request_example, swagger_schemas.user_login_response_example]
)
class UserLoginSerializer(serializers.ModelSerializer):
    user_token = UserLoginTokenSerializer(required=False, write_only=True)
    token = serializers.ReadOnlyField()

    class Meta:
        model = User
        fields = ["id", "email", "nickname", "username", "phone_number", "password", "user_token", "token"]
        extra_kwargs = {
            "id": {"required": False},
            "password": {"write_only": True},
            "email": {"required": False},
            "nickname": {"required": False},
            "phone_number": {"required": False},
        }

```

This is my request / response example

```
user_login_request_example = OpenApiExample(
    name="user login example",
    value={
        "username": "username(email, nickname, phone_number)",
        "password": "password",
    }, request_only=True
)

user_login_response_example = OpenApiExample(
    name="SUCCESS",
    value={
        "id": 1,
        "email": "test@email.com",
        "username": "username",
        "nickname": "nickname",
        "phone_number": "11122233333",
        "token": {
            "access": "access token",
            "refresh": "refresh token"
        }
    }, response_only=True
)

```

This is swagger page in requestBody's schema 

![Screen Shot 2021-09-02 at 10 58 22 AM](https://user-images.githubusercontent.com/47441670/131769188-8e6d520b-e4ae-43ce-bea0-681f3be5f8c1.png)

extend_schema_serializer's extend_fields option is exclude all of request and response.
I want only request's exclude fields exclude 

Is there option's for example's request exclude field way?

**Comment by tfranzel** [comment]
hi, the image does not reflect the code (`id` missing and so on).

your feature request does not exist in that way, however we have mechanisms that get close. 

you can use `'COMPONENT_SPLIT_REQUEST': True` to have splitted request/response. if you then properly tag all fields `read_only` (!!!) and `write_only`, you have that requested outcome.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
