### ISSUE TITLE
Missing title property for SerializerMethodField fields

### ISSUE THREAD

**Issue by chgad** [tfranzel/drf-spectacular#498]
**Describe the bug**

The introduced meaningful title (Version 0.15.0) is not generated if a field is manually specified as SerializerMethodField in a Serializer.

**To Reproduce**
```python
from django.utils.translation import ugettext_lazy as _
class Author(models.Model):
    search_words = ArrayField(default=[], verbose_name=_(Search categories))

class AuthorSerializer(serializers.ModelSerializer):
    search_words = serializers.SerializerMethodField()
    
    def get_search_words(self, obj):
        return ", ".join(obj.search_words)
```

It does not really matter what I do in the "get_<field_name>" method at all.
 The schema lacks the `title` property for each field where I define a SerializerMethodField. 

**Expected behavior**
The title should be populated with the specified verbos_name from the model.

**Comment by tfranzel** [comment]
Hi! 

i think i get what you are trying to achieve, but i disagree that this should work as you requested. by using `SerializerMethodField` you add a layer of indirection that is decoupling the serializer field from the actual model field.  Introspection-wise we  have no idea what you are actually doing inside that function body. 

it would be a very brittle assumption to establish that connection solely based on the string `search_words`. other than this arbitrary name, there is nothing actually linking `Author.search_words` with `AuthorSerializer.search_words`

**Comment by chgad** [comment]
Thank you for your quick reply!

What would you suggest for a solution?
Would a custom, non-SerializetMethodField, Field be the way to go or a custom model field?

**Comment by tfranzel** [comment]
for type only you can use type annotations

```python
    def get_search_words(self, obj) -> str:
        return ", ".join(obj.search_words)
```

for more doc

```python
    @extend_schema_field(serializers.CharField(label='foo', help_text='bar'))
    def get_search_words(self, obj):
        return ", ".join(obj.search_words)

your suggestion also works. really depends on how often you use it and the amount of effort involved.

**Comment by chgad** [comment]
Since we build one of our Frontendcomponenta solely from the api-spec it's crucial to get the `verbose_name` as `title` and i'd like to avoid to duplicate this "string" unneccesarryly (as stated in your second example).

**Comment by tfranzel** [comment]
you can use `@extend_schema_field` on a serializer field subclass definition.  then you only have to do it once. 

i'll close this issue as there is nothing to fix here atm.

**Comment by chgad** [comment]
For anybody visiting this Issue in the Future.

If you need a non-standart SerializerField to create your response AND give the correct `title` property (in accordance with a defined `verbose_name`in the model):

1. Define a custom Subclass of your desired field type.
2. Implement your custom `to_representation()` method
3.  Overwirte the `bind()` metod as follows :
        def bind(self, field_name, parent):
            super(ListVerboseField, self).bind(field_name, parent)
            self.label = self.parent.Meta.model._meta.get_field(self.field_name).verbose_name

This show the correct behavior in the shema.
