### ISSUE TITLE
How can i convert GET-params to camel case

### ISSUE THREAD

**Issue by AlexElizard** [tfranzel/drf-spectacular#499]
I used the settings for the djangorestframework_camel_case package. And also used the middleware from [djangorestframework-camel-case #68](https://github.com/vbabiy/djangorestframework-camel-case/pull/68).
How can I convert GET parameters to camel style?

**Comment by tfranzel** [comment]
hi! we can't really support this unless this feature is part of their release. 

in theory you would adapt the postprocessing hook we already have by adding another modification step. you can write your own postprocessing hooks without a problem.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
