### ISSUE TITLE
Support for static ReadOnlyField?

### ISSUE THREAD

**Issue by jalaziz** [tfranzel/drf-spectacular#503]
**Describe the bug**

One of the simpler ways to add a static field to serialized output is to use `ReadOnlyField` with a `default`. However, type detection fails to detect the "missing" property on the model and generates a warning.

**To Reproduce**
```
class ThingSerializer(serializers.Serializer):
    purpose = serializers.ReadOnlyField(default='a_purpose')
```

**Expected behavior**

Since a default is provided, it would be great if type detection treated this returning a string or `Literal` type and did not generate a warning.

**Comment by tfranzel** [comment]
this should be equivalent to `serializers.CharField(read_only=True, default='a_purpose')` where the type is explicitly declared. `ReadOnlyField` is mainly targeted to exposing model fields via `source`. 

i don't think `Literal` does cover the potential cases it can be used for. It does default to string, but that is still an assumption thus the warning. 

i recognize this is not ideal, but i feel like making any further assumptions here might lead to an potentially incorrect schema.

**Comment by jalaziz** [comment]
> this should be equivalent to `serializers.CharField(read_only=True, default='a_purpose')` where the type is explicitly declared. `ReadOnlyField` is mainly targeted to exposing model fields via `source`.
> 
> i don't think `Literal` does cover the potential cases it can be used for. It does default to string, but that is still an assumption thus the warning.
> 
> i recognize this is not ideal, but i feel like making any further assumptions here might lead to an potentially incorrect schema.

Fair enough. I've been on the fence about using `CharField`. Using a `ReadOnlyField` is slightly nicer since it ends up being fewer characters and it's lighter weight (barely).

I can definitely see the argument that using a field where the type is known is the way to go to appease type hinting.

**Comment by tfranzel** [comment]
i do get the motivation and it is a perfectly fine ask. however, sometimes we simply have not enough information to make the schema better. building a  decoration around `ReadOnlyField` would in the end be more complicated that simply using the typed field. i'll close this issue then, but good that we had a talk about it.
