### ISSUE TITLE
Field "BinaryField" has no mapping in ModelSerializer

### ISSUE THREAD

**Issue by jtamm-red** [tfranzel/drf-spectacular#505]
BinaryField is purpose to use raw content. (looks like bytes)

https://docs.djangoproject.com/en/3.2/ref/models/fields/#binaryfield

`model field "BinaryField" has no mapping in ModelSerializer. It may be a deprecated field. Defaulting to "string`

Schema type should be 'string', becuase content is encoded as base64.

**Comment by tfranzel** [comment]
closed with #506
