### ISSUE TITLE
Support pagination for @action without @extend_schema.

### ISSUE THREAD

**Issue by ngnpope** [tfranzel/drf-spectacular#523]
**Describe the bug**
When using `@action(..., detail=False, serializer_class=SimpleSerializer)`, I would have thought that the output would be paginated. Currently we need to use `@extend_schema(responses={'200': SimpleSerializer(many=True)})`

**To Reproduce**

```python
    class XViewset(viewsets.ReadOnlyModelViewSet):
        queryset = SimpleModel.objects.all()
        serializer_class = SimpleSerializer
        pagination_class = pagination.LimitOffsetPagination

        @action(methods=['GET'], detail=False, serializer_class=SimpleSerializer)
        def custom_action(self):
            pass
```

**Expected behavior**

The above should detect pagination without needing `@extend_schema`. If we have `detail=False` and `serializer_class` defined we can so `SimpleSerializer(many=True)` automatically.

**Comment by tfranzel** [comment]
that is a common misconception.

https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-m-using-action-detail-false-but-the-response-schema-is-not-a-list

fyi: `@extend_schema(responses=SimpleSerializer(many=True))` is enough. the dict is optional if you want to default code.

**Comment by ngnpope** [comment]
Hah! I somehow missed that entry in the FAQ. 🤦🏻‍♂️ Thanks.
