### ISSUE TITLE
Document multiple routes to the same view

### ISSUE THREAD

**Issue by tduhautb** [tfranzel/drf-spectacular#525]
Hi,

I started using drf-spectacular on a project, and I am facing an issue with multiple routes leading to the same view. I hope I'm asking the question at the right place.

I have two routes defined in my `urls.py` : one `books/` route which lists all the books of the database, and one `books/byEntity/<uuid:uuid>/` which lists only the books owned by the given entity, identified by its UUID. We did this this way to make use of the standard UUID filter `<uuid:uuid>` instead of using a regexp.
Because the goal is to list the books in both cases, both routes point to the same view, which derives from `mixins.ListModelMixin` and `generics.GenericAPIView`. The `get_queryset` method is used to filter the queryset based on the `kwargs` which may or may not have a `uuid` parameter, depending on the route used.

```python
# views.py
from rest_framework import mixins
from rest_framework import generics

class BookList(mixins.ListModelMixin, generics.GenericAPIView):
    serializer_class = my_serializer

    def get_queryset(self):
        queryset = ... # adapt the queryset based on the kwargs
        return queryset

    def get(self, request, *args, **kwargs):
        """
        Documentation extracted for both routes
        """"
        return self.list(request, *args, **kwargs)

# urls.py
urlpatterns = [
    path('books/', views.BookList.as_view(), name="book-list"),
    path('books/byEntity/<uuid:uuid>/', views.BookList.as_view(), name="book-list-filter"),
    # ...
]
```

The problem I have is that because the same class is used, there is only one documentation for the  `get` method, so in the generated doc, both routes are extracted with the same documentation. Soi the question is, is there a way to separate the documentation for these different routes, and if so, how ? If not, is there a "standard" way to do so ?

Thanks in advance for your help !

**Comment by tfranzel** [comment]
Hi, there is not really a standard way to do this. the "right thing" would be covering both cases in that docstring. it is the same `view.method` after all.

however your could circumvent that with this construction. not that nice but should get the job done.

```python
@extend_schema_view(
    get=extend_schema(description='Your other description')
)
class BookListFiltered(BookList):
    pass

# urls.py
urlpatterns = [
    path('books/', views.BookList.as_view(), name="book-list"),
    path('books/byEntity/<uuid:uuid>/', views.BookListFiltered.as_view(), name="book-list-filter"),
    # ...
]
```

**Comment by tduhautb** [comment]
Thanks for the answer and for the suggestion, that's a nice trick. We'll see which option we'll take, but I think it's great to have an option to separate the documentation.
