### ISSUE TITLE
raw schema dict renders incorrect response schema

### ISSUE THREAD

**Issue by pydo** [tfranzel/drf-spectacular#528]
**Describe the bug**
According to these [API docs](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/utils.py#L223) I should be able to pass in a raw schema dict. I tried a few formats as I couldn't find any examples.
However the swagger ui always interprets the response dict as a string.

**To Reproduce**
```python
class APIDoTheThing(APIView):
    @extend_schema(responses={201: {'test': 'value'}},
                   methods=['POST'])
    def post(self, request, external_id, format=None):
            return Response(
                {'sender': 'blbla'
                 'receiver': 'sdfdas'
                , status=201)
```

**Expected behavior**
The swagger-ui should document the response parameters as {"string": "string"}

**Actual behavior**
The swagger-ui documents the response parameters as "string"
![screenshot-1632018694](https://user-images.githubusercontent.com/10181884/133913483-64b7306e-2ffe-4bd5-abd0-7e2226421ed2.png)

Is there any way to explicitly define my response schema without using a serializer?
Thanks

**Comment by pydo** [comment]
It seems that whatever values I use, they all get interpreted as strings.

**Comment by pydo** [comment]
Looks like I needed to combine responses with examples to get what I wanted.

```python
@extend_schema(responses={201: OpenApiTypes.OBJECT},
                   methods=['POST'],
                   examples=[OpenApiExample(
                       name='_',
                       value={'sender': {'name': 'blabla'}, 'receiver': {'name': 'blalas'}},
                       response_only=True
                   )])
```

I guess this issue could be filled as a documentation bug, as it doesn't look like a raw schema dict is supported (or explicitly defined for that matter).

**Comment by tfranzel** [comment]
hi @pydo

this does indeed work. when you look at the generated schema instead of swagger-ui, it's clearly there. the problem is that swagger-ui does not understand your malformed OpenAPI schema `{'test': 'value'}` and probably defaults to string because of that. if you want to use raw schema you have to understand OpenAPI syntax first.

this would have been the correct raw schema to write
```python
{
  'type': 'object', 
  'properties': {'sender': {'type': 'string'}, 'receiver': {'type': 'string'}}, 
  'required': ['receiver', 'sender']
}
```


you could have also used

```python
class APIDoTheThing(APIView):
    @extend_schema(responses={
        201: inline_serializer(
            name='YourName',
            fields={
                'sender': serializers.CharField(),
                'receiver': serializers.CharField(),
            },
        )
    })
    def post(self, request, external_id, format=None):
            return Response({'sender': 'blblar', 'receiver': 'sdfdas'}, status=201)

```

your example approach also works but is sub-optimal given just a generic schema.

**Comment by pydo** [comment]
Thanks for the detailed answer, I didn't know that  the raw schema referred to json/openapi schema.
