### ISSUE TITLE
Integration with django-oauth-toolkit

### ISSUE THREAD

**Issue by adlmtl** [tfranzel/drf-spectacular#531]
Hi there, 

I'm migrating from simplejwt to oauth-toolkit, I have a password flow and have added the appropriate settings based on the documentation (settings shown below). When authorizing in the swagger ui, I can see that my token endpoint is being called and a token is being successfully returned, however when I then make further requests in the ui, the token is not being passed in the headers.

Is there something else I am missing?

Thanks

` # DRF Spectacular (OpenAPI 3.0 schema)
    SPECTACULAR_SETTINGS = {
        'COMPONENT_SPLIT_REQUEST': True,
        'SCHEMA_PATH_PREFIX': r'/api/v1',
        'SERVE_PUBLIC': True,
        'CAMELIZE_NAMES': True,
        'SWAGGER_UI_SETTINGS': {
            'persistAuthorization': True,
        },
        'POSTPROCESSING_HOOKS': [
            'drf_spectacular.hooks.postprocess_schema_enums',
            'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
        ],
        'OAUTH2_FLOWS': ['password'],
        'OAUTH2_TOKEN_URL': '/api/v1/token/',
        'OAUTH2_REFRESH_URL': '/api/v1/token/',
    }`

**Comment by tfranzel** [comment]
hey

- do you have 
```
      security:
      - oauth2:
        - some_scope
```
in your schema? 

- is the little lock on the right side of the operation black and locked?

**Comment by adlmtl** [comment]
Hi no I do not, in the schema it says

`security:
      - cookieAuth: []`

**Comment by adlmtl** [comment]
seems like its not picking up my drf default

`'DEFAULT_AUTHENTICATION_CLASSES': (
            'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        ),`

**Comment by tfranzel** [comment]
looks like your views do not have the proper auth classes. either set it in `REST_FRAMEWORK` or on a view basis

```python
class TokenHasReadWriteScopeViewset(mixins.ListModelMixin, viewsets.GenericViewSet):
    serializer_class = XSerializer
    authentication_classes = [OAuth2Authentication]
    permission_classes = [TokenHasReadWriteScope]
```

you also need the `permission_classes` to make this work

**Comment by adlmtl** [comment]
Yes ok I see thanks.
