### ISSUE TITLE
Multiple API Keys

### ISSUE THREAD

**Issue by kalosisz** [tfranzel/drf-spectacular#537]
Hi,

I was wondering if the library supported multiple API keys for authentication as described [here](https://swagger.io/docs/specification/authentication/api-keys/).

**Comment by tfranzel** [comment]
Hi @kalosisz 

interesting ask. this has not come up before. do you have a "public" auth library that does this or is it internal to you? In either case you would implement a `OpenApiAuthenticationExtension` [(doc)](https://drf-spectacular.readthedocs.io/en/latest/customization.html#specify-authentication-with-openapiauthenticationextension) for your `authentication_classes` entry.  You would need to override `get_security_requirement` to return a dict with 2 entries.

so in theory we could do it, but there might be a small feature we need to implement to support this fully. namely `get_security_definition` to support returning a list also and not just one definition.

**Comment by tfranzel** [comment]
> I was wondering if the library supported multiple API keys for authentication as described here.

now it does

**Comment by kalosisz** [comment]
Thank you very much! It is indeed an internal feature for me.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
