### ISSUE TITLE
Bravo

### ISSUE THREAD

**Issue by MichelML** [tfranzel/drf-spectacular#538]
Just wanted to say this package is amazing. Praise to the team and you should add a financial sponsor/support call to action somewhere in the Readme.

Cheers

(Close this anytime)

**Comment by tfranzel** [comment]
Hi! Thank you very much for the kind words. After using OSS for a long time, I'm just happy to be able to contribute something useful back to the community.  I'll think about your suggestion, but I have not felt the need yet. Cheers!
