### ISSUE TITLE
@extend_schema for simple JSON reponses

### ISSUE THREAD

**Issue by hnataraj** [tfranzel/drf-spectacular#543]
Hi:

I have a simple JSON response in code like below:

`return Response({'message':  "this is a message"}, status=status.HTTP_400_BAD_REQUEST)`

The above line generates the following HTTP response:

```
HTTP 400
...
{message : "this is a message"}
```
How do I use @extend_schema annotation to document this in OpenAPI format?

**Comment by tui95** [comment]
There are multiple ways to represent response via `@extend_schema` besides explicitly define a serializer and use it as a response. 

One way is to use helper function called `inline_serializer` as shown here.
```python
@extend_schema(
    responses={
        400: inline_serializer(
            name='Your schema name',
            fields={
                'message': serializers.CharField(),
            },
        ),
    },
)
# your view method
```

Another way is to define raw schema dict as can be seen in the docstring of `@extend_schema` decorator.

https://github.com/tfranzel/drf-spectacular/blob/273311705fc08ad00f4b969153c167b3cb2675e7/drf_spectacular/utils.py#L233-L235

In this case, raw schema dict refers to an openapi schema (reference can be found [here](https://swagger.io/docs/specification/data-models/dictionaries).)

In your example, the schema can be defined as shown below.
```python
@extend_schema(
    responses={
        400: {
            'title': 'Your schema name',  # optional
            'type': 'object',
            'properties': {
                'message': {
                    'type': 'string',
                },
            },
            'example': {  # optional. if you want to provide example
                'message': 'this is a message',
            },
        },
    },
)
# your view method
```

**Comment by hnataraj** [comment]
Thanks much!

Are there examples on how to specify JWT auth scheme using @extend_schema?

**Comment by tui95** [comment]
I'm not sure about the reason behind having to specify JWT auth schema via `@extend_schema` since it will only affect that particular view method. 

I think what you want is to specify JWT auth schema globally for the project. An example can be found in the documentation [here](https://drf-spectacular.readthedocs.io/en/latest/customization.html#specify-authentication-with-openapiauthenticationextension).
