### ISSUE TITLE
(critical) wrong dist for redoc

### ISSUE THREAD

**Issue by Leikaab** [tfranzel/drf-spectacular#546]
in https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/views.py
there is a bug:

on line 203:
`return spectacular_settings.SWAGGER_UI_DIST`

should be
`return spectacular_settings.REDOC_DIST`

**Comment by Leikaab** [comment]
Quick temp work around:

´´´python
from drf_spectacular.views import SpectacularRedocView
from drf_spectacular.settings import spectacular_settings


class SpectacularRedocViewFix(SpectacularRedocView):
    def _redoc_dist(self):
        return spectacular_settings.REDOC_DIST


urlpatterns += [
    #path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    #replace with
    path('redoc/', SpectacularRedocViewFix.as_view(url_name='schema'), name='redoc'),
]
´´´

**Comment by tfranzel** [comment]
of course this detail was not tested before. :disappointed:   will do a release asap.

**Comment by Leikaab** [comment]
Know the feel :)
Thank you for fixing it, and thank you for your work!!!

**Comment by tfranzel** [comment]
`0.20.1` is released
