### ISSUE TITLE
djangorestframework-camelcase per-view support

### ISSUE THREAD

**Issue by georgy-komarov** [tfranzel/drf-spectacular#548]
In djangorestframework-camelcase there is an opportunity to set per-view camelcase support via 
```python
class MyView(APIView):
    ...
    parser_classes = (CamelCaseJSONParser,)
    renderer_classes = (CamelCaseJSONRenderer,)
    ...
```
Is there any way to implement per-view camelcase for schema? Default hook does not provide this functionality
The implementation can be based on checking if CamelCase*** is in `parser_classes` or `renderer_classes`
However I can't imagine where to put these checks.

It may be useful if I have some views with snake_case fields (for example OAuth2-compliant authentication methods)

**Comment by tfranzel** [comment]
Hey @georgy-komarov, this has been asked before in #478

here is my previous answer: https://github.com/tfranzel/drf-spectacular/issues/478#issuecomment-891999371

it is a reasonable ask for sure! however its tricky to implement. differentiating on a view level would mean we would need to generate the components in multiple versions (regular&camelized). that breaks a very fundamental assumption we are making and would likely require serious refactoring of the code base. not sure at the moment how we could do this with minimal impact.

**Comment by georgy-komarov** [comment]
I somehow managed to miss that issue. Now I understand all the difficulties.
I will try to fix it for me with postprocessing hook customization.
