### ISSUE TITLE
Feature request (or help if exists)

### ISSUE THREAD

**Issue by Leikaab** [tfranzel/drf-spectacular#549]
Hi, and again thank your for your great work!

We've been looking into creating code snippets for consumption of our api, but it quickly became complicated.
Typically like this:
https://stripe.com/docs/api?lang=python
or this:
https://developers.google.com/docs/api/how-tos/lists
We found some examples in regards to drf-yasg, there is also some option to use similar logic that is used for OpenApiExample, but is there any intended way to do this, or examples of this being solved using drf-spectacular?

**Comment by tfranzel** [comment]
Hi @Leikaab

I see what you mean. Can you provide a link to how yasg is handling this? As far as I am concerned, this is not part of standard OpenAPI. 

Luckily we recently introduced support for vendor extensions. Redoc seems have have vendor extensions with regards to this feature: [doc](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#operation-object-vendor-extensions)

I think it would look something like this for Redoc:

```python

    @extend_schema(
        extensions={'x-codeSamples': [{
            "lang": "JavaScript",
            "source": "console.log('Hello World');"
        }]},
    )
   def retrieve():
       ...
```

Here are more examples how you can inject extensions with spectacular:
https://github.com/tfranzel/drf-spectacular/blob/master/tests/test_specification_extensions.py

**Comment by Leikaab** [comment]
Hi!

Thank you this works like a charm and solves what we were looking for!
I will let you know and share code if we implement something fancier down the line :)
