### ISSUE TITLE
[Request] Special handling for JSON in multipart data

### ISSUE THREAD

**Issue by VaZark** [tfranzel/drf-spectacular#550]
I've noted that when using nested serializers with many=True in a multipart form, the array is handed as normal, i.e., separated by a comma. It would be more JSON-like if the generated data is represented within array brackets. This will make it simpler for the serializers to parse it as a json string directly without additional manipulations.

**Comment by tfranzel** [comment]
hi! please provide 2 example snippets for the schema (how it is and how it should be) so it is easier to talk about.

**Comment by VaZark** [comment]
For a serializer of the format,

```
class DemandePretSerializer(serializer.ModelSerializer):
    vehicle = VehicleStateSerializer(source='demande_vehicle', many=True)
```

when the request param in swagger is
![image](https://user-images.githubusercontent.com/11616688/136191742-749a0880-a09a-4d98-a5ea-5e01c7d3ff06.png)

The generated curl request

```
curl -X 'POST' \
  'http://localhost:8000/api/demande/details/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'X-CSRFToken: BrXN9Q8fsHaXid7G5ZOBhXCoLmVbmlXdB8DnNqaNO19bMAuZltK6Hct24p9VgjId' \

  -F status={
  "bubble_id": "string",
  "request_id": "string",
},{
  "bubble_id": "string",
  "request_id": "string",
}\
-F ....
```

It would be cleaner if the generated curl is of the following format so that it can still be a valid json

```
status=[{
  "bubble_id": "string",
  "request_id": "string",
},{
  "bubble_id": "string",
  "request_id": "string",
}]
```

**Comment by tfranzel** [comment]
The curl request is generated by SwaggerUI. This is outside of our jurisdiction. We only generate the OpenAPI schema and hand it over to SwaggerUI.  As far as I understand, we generate a correct schema here. 

Assuming the schema is correct, you would need to open an issue with SwaggerUI.

**Comment by VaZark** [comment]
Ah. I'll be closing this then
