### ISSUE TITLE
Post Processing Authn/Authz Filtering?

### ISSUE THREAD

**Issue by megazza** [tfranzel/drf-spectacular#553]
Hi

I am using the preprocessing hook to hide api's I do not want to show to customers.   But I also want to hide them if 

a) they are not authenticated yet 
b) they are not authorized to the endpoint permissions

For the authn, I notice the postprocessing hook provides a request object, I was hoping to see request.auth populated once I had imput my bearer token - but its not.   Is there any way to determine you are authenticated at that stage?

For the authz, is there a variable in  the post processing hook variable I can modify that reflects the django permission class on the views?  If there was, I was then going grab the claims out of the bearer token authn above, but I don't have that :(

Would you expect the request object passed into postprocessing hook to reflect and authenitcated session?

Thanks
Gareth

**Comment by tfranzel** [comment]
This should also work for a custom auth. On `SpectacularAPIView` we do nothing special wrt. auth. On the generator we use DRF's auth check. Nothing special there either. The mocked request gets a copy of the original request's auth in `build_mock_request`. as far as I'm concerned, this is supposed to work. 

the tests do cover this : https://github.com/tfranzel/drf-spectacular/blob/2eaac13889624bffef208c7a401c33a8a472b194/tests/test_mock_request.py#L85

permission check for exclusion: https://github.com/tfranzel/drf-spectacular/blob/2c91cbd4c95ac8ac15085ab570a879adb2691e04/drf_spectacular/generators.py#L208

**Comment by tfranzel** [comment]
what i am reading is that your custom auth does a little bit extra stuff , e.g. setting `session` on the request. that looks like non-standard behavior we cannot know about. So your custom auth does not behave transparently and thus you may have to adapt the request mock method to your changes.

have a look at the default one: https://github.com/tfranzel/drf-spectacular/blob/16eb3275ca55fa821e283a2a20bffc61c9e2d6a2/drf_spectacular/plumbing.py#L1041

augment that function and set it in the settings: https://github.com/tfranzel/drf-spectacular/blob/6bc1d2e24730bcc40803c74a2505592db86907d2/drf_spectacular/settings.py#L102
