### ISSUE TITLE
Support for adding description to tags

### ISSUE THREAD

**Issue by kirankumargmrur** [tfranzel/drf-spectacular#558]
Hi, 

We can group the API endpoints using tags and we can set description at the operation level as of now. It would be really nice if we have the feasibility of setting description for tags hence we can explain the purpose of grouping.

**Comment by MT-Cash** [comment]
In case somebody needs an example how this can look like:

```
    "TAGS": [
        {
            "name": "Foo",
            "description": "Foo description",
        },
        {
            "name": "Bar",
            "description": "Bar description",
        },
    ],
```

**Comment by haccks** [comment]
If using `TAGS=[]` in `SPECTACULAR_SETTINGS` then to group API endpoints to one global tag I have to annotate all the views. Is there any shortcut?
