### ISSUE TITLE
Set an url prefix if Django is not mounted under / in production

### ISSUE THREAD

**Issue by Wissperwind** [tfranzel/drf-spectacular#567]
Hi,

The plugin identifies all urls correctly from djangos point of view.
But in production django has to be mounted in to a webserver. And under / is usually the folder for static files for the website.
So I mounted django under /backend. So an endpoint that is /getInfo in django is now /backend/getInfo in reality.

Is there an option to tell this to drf spectacular?
If not I would like to request this feature.
Thanks!

**Comment by tfranzel** [comment]
Hi,

since Django does not know about this, you need to set `SERVERS` in the spectacular settings.

```python
'SERVERS': {'url': 'https://example.com/backend'}
```

**Comment by ngnpope** [comment]
I achieved this automatically by adding a post-processing hook:

```python
from urllib.parse import urljoin

def set_request_server(result, generator, request, public):
    if request:
        url = urljoin(request.path, ".").rstrip("/")
        url = request.build_absolute_uri(url)
        result.setdefault("servers", []).append({"url": url})
    return result
```

This example works where my schema is hosted at, e.g. `https://api.example.com/path/to/schema.json` and I want the base to be `https://api.example.com/path/to/`. You can tweak this to suit your needs. Not sure whether you'd like to adopt something like this in the FAQ?

**Comment by Wissperwind** [comment]
Ah, ok. Now something works.
I can add:
```
    'SERVERS': [
        {
            "url": "/backend",
        }
    ],
```
And it adds the prefix to each call and uses still automatic the current host.
The server url can be specified from the customer and I don't know it here.

But there is still a problem. The prefix is not displayed to each URL. So if I show swagger page to the developers they will see /api/login and think, OK, let's call localhost:8000/api/login. But that will not work. They have to call localhost:8000/backend/api/login. Sure I can to explain it to them. But some will forget it sometimes. How about a real prefix setting?

**Comment by Wissperwind** [comment]
Ok, so can this issue be clodes now?
Is this already in a public release?

**Comment by tfranzel** [comment]
yes its released in 0.20.2. it can be closed.

**Comment by Skyfox64** [comment]
> I achieved this automatically by adding a post-processing hook:
> 
> ```python
> from urllib.parse import urljoin
> 
> def set_request_server(result, generator, request, public):
>     if request:
>         url = urljoin(request.path, ".").rstrip("/")
>         url = request.build_absolute_uri(url)
>         result.setdefault("servers", []).append({"url": url})
>     return result
> ```
> 
> This example works where my schema is hosted at, e.g. `https://api.example.com/path/to/schema.json` and I want the base to be `https://api.example.com/path/to/`. You can tweak this to suit your needs. Not sure whether you'd like to adopt something like this in the FAQ?

Hi Nick, where would one place this post-processing hook?

**Comment by tfranzel** [comment]
it does not matter where. you just need to set in the import path in the setting `POSTPROCESSING_HOOKS`. make sure you don't forget to add the enum postprocessing hook back in to the list.

see doc for more details: 

https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks
