### ISSUE TITLE
Add swagger_schema_field equivalent to "From drf-yasg to OpenAPI 3" docs

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#568]
I found #517 after doing some searching through the issues. Would it be possible to add a reference/example to how one would port from `drf-yasg` [`swagger_schema_field`](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#serializer-meta-nested-class) to the [From drf-yasg to OpenAPI 3](https://drf-spectacular.readthedocs.io/en/latest/drf_yasg.html) docs? I think as more and more people port, this will come up more often.

> Side note. Using `drf-spectacular` has been **great**! The built in SimpleJWT support, built in django-filters support, sidecar... it's all been awesome to work with. So far we've been able to *remove* more lines than we're adding porting from `drf-yasg` to `drf-spectacular`! ❤️

**Comment by ngnpope** [comment]
Hah! I did have some conversions of `swagger_schema_fields`, but lost the will when enhancing the migration guide to include an example of this. It would be nice to have though if you can come up with something @johnthagen.
