### ISSUE TITLE
Add integration with django-enumfields

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#570]
[`django-enumfields`](https://github.com/hzdg/django-enumfields) allows using "real" Python [`Enum`](https://docs.python.org/3/library/enum.html)s within Django Models.

We've used these extensively within Django/DRF to provide a more expressive internal API to work with.

We've hit some related to #482 during our porting to `drf-spectacular` that can be summarized in the following example:

```py
from enum import Enum, unique

from django.db import models
from enumfields import EnumField

@unique
class CarType(Enum):
    Sports = "sports"
    Bus = "bus"

class Car(models.Model):
    type = EnumField(CarType)

@unique
class AnimalType(Enum):
    Mammal = "mammal"
    Reptile = "reptile"

class Animal(models.Model):
    type = EnumField(AnimalType)
```

When we build the schema for this contrived example (`ModelSerializer`, `ViewSet` derived from this), we get generated OpenAPI enums that look like:

- Type000Enum
- Type001Enum

With a warning:

```
Warning #0: enum naming encountered a non-optimally resolvable collision for fields named "type". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "TypeF93Enum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.
...
```

But it seems like it should be possible to introspect the actual Python `Enum` that is used and use that as a way to name the generated OpenAPI enums?

I believe that FastAPI does something similar to this.

**Comment by auvipy** [comment]
django by default now provide enumfield, so why not using that instead?

**Comment by johnthagen** [comment]
@auvipy That is a good point. I hadn't realized that until digging in more that `Choices` actually does derive from `Enum`, so it is a true Python `Enum`.  That had been my hesitation in the past about using it. I opened a Django ticket to improve the docs: https://code.djangoproject.com/ticket/33193

It would be better to support something that is officially part of Django.

**Comment by johnthagen** [comment]
> That said, it contains quite a bit of magic that likely requires quite a few small changes. Also, imho it is partially superseded by more recent Django versions. At the moment I'm leaning more towards not including it.

@tfranzel Totally understand and I tend to agree as well. Once I understood `"ENUM_NAME_OVERRIDES"` more, it was not difficult to add in a little config to get `django-enumfields` `EnumFields` into the schema properly.

> @johnthagen afaik hzdg/django-enumfields#111 (comment) is not an issue anymore with e.g. TextChoices. It contains a little extra magic that deals with that "serialization" issue mentioned there.

I'll have to play with it some more myself and see if `Enum` instances come out now or just `str` still.

Please feel free to close this issue as Won't Fix. I think most Django users will be happy enough with the `Choices` enhanced `CharField`.
