### ISSUE TITLE
Create Direction type to allow more type-safe usage of direction

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#582]
When writing an extension, I found an area that could be improved to help down stream developers that use type checking or IDEs (such as PyCharm) that support type annotations:

https://github.com/tfranzel/drf-spectacular/blob/59f9749086d5bf5d359ef7f8496bd39c88267721/drf_spectacular/extensions.py#L61

https://github.com/tfranzel/drf-spectacular/blob/59f9749086d5bf5d359ef7f8496bd39c88267721/drf_spectacular/plumbing.py#L113

Usage of `direction` throughout the codebase could be augmented with the use of a dedicated `Direction` [`Enum`](https://docs.python.org/3/library/enum.html#enum.Enum) or [`Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) type:

```py
@unique
class Direction(Enum):
    Request = "request"
    Response = "response"
```

Or

```py
from typing import Literal

Direction = Literal["request", "response"]
```

The `Literal` type was added in Python 3.8, so for supporting older versions, they [`typing-extensions`](https://pypi.org/project/typing-extensions/) package backports these in a PyPI package.

Resulting code base would look like:

```py
def map_serializer(self, auto_schema: 'AutoSchema', direction: Direction): 
```

**Comment by tfranzel** [comment]
Hey @johnthagen,

very good point. Unfortunately using an `Enum` could break existing users. I therefore opted for the `Literal` solution. We recently added `typing-extensions` as explicit dep anyway.
