### ISSUE TITLE
X-CSRFToken header causes CORS error when used with `openIdConnect` security definition

### ISSUE THREAD

**Issue by georgy-komarov** [tfranzel/drf-spectacular#588]
**Describe the bug**
X-CSRFToken header causes CORS error when used with `openIdConnect` security definition
![image](https://user-images.githubusercontent.com/13136992/139171412-0afcd66c-c03f-4f34-8ce6-0b6cacca7ecf.png)

**To Reproduce**
I'm using custom scheme for Keycloak OpenID auth ([more info here](https://swagger.io/docs/specification/authentication/openid-connect-discovery/))
For simplicity let's assume we need only `profile` scope for all the endpoints
```python
class KeycloakAuthScheme(DjangoOAuthToolkitScheme):
    target_class = 'mozilla_django_oidc.contrib.drf.OIDCAuthentication'
    name = 'keycloak'

    def get_security_requirement(self, auto_schema):
        return {self.name: ['profile']}

    def get_security_definition(self, auto_schema):
        return {
            'type':             'openIdConnect',
            'openIdConnectUrl': f'{settings.KEYCLOAK_SERVER}/auth/realms/{settings.KEYCLOAK_REALM}/.well-known/openid-configuration'
        }
```
When we open swagger-ui, it fails to get OpenID configuration due to rather specific `X-CSRFToken` header which most Keycloak servers deny. And, of course there is no way to contact admins to change their CORS policy.

It seems like it happens because of requestInterceptor here

https://github.com/tfranzel/drf-spectacular/blob/31e769832881d00d9ce0ceb49e9ee10379b31499/drf_spectacular/templates/drf_spectacular/swagger_ui.js#L11-L14

As far as I understand it is added for Django session authentication. But I am not sure it is the only reason.
~~And I am not really sure if I can override this behaviour~~

**UPD: Workaround**
I managed to find some workaround. Thanks to [this commit](https://github.com/tfranzel/drf-spectacular/commit/0ed0b80294c9646d4cde1443c728082b3d01f4fc) I can set `requestInterceptor` to `undefined`. This seems to work, however it's quite dirty hack.
UPD2: Setting `requestInterceptor` to `undefined` was not a good idea as it brakes something in the UI itself. More safe way is to set `"requestInterceptor": (request) => request`

```python
'SWAGGER_UI_SETTINGS':      '''{
        "deepLinking": true, 
        "oauth2RedirectUrl": `${window.location.protocol}//${window.location.host}/api/static/drf_spectacular_sidecar/swagger-ui-dist/oauth2-redirect.html`,
        "requestInterceptor": (request) => request
    }''',
```

**Expected fix**
This can be fixed if we do not set requestInterceptor globally.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
