### ISSUE TITLE
Schema generation for multiple apps

### ISSUE THREAD

**Issue by CaptainArni** [tfranzel/drf-spectacular#590]
In our project we have multiple apps with URLs like this:
/backend/<app-name>/api/...

so for example
- /backend/abc/api/...
- /backend/opq/api/...
- /backend/xyz/api/...

We created a SCHEMA_PATH_PREFIX like so:
"SCHEMA_PATH_PREFIX:": r'(/backend/abc/api|/backend/opq/api|/backend/xyz/api)
This way our endpoints are at least grouped and not one big cluster.

Now to my question:
Is it possible to create Schema pages for each of our apps?
Something like this:
- path("backend/abc/api/schema", SpectacularAPIView.as_view(), name="abc_schema")
- path("backend/opq/api/schema", SpectacularAPIView.as_view(), name="opq_schema")
- path("backend/xyz/api/schema", SpectacularAPIView.as_view(), name="xyz_schema")

Can I tell **SpectacularAPIView.as_view()** somehow to only display /backend/abc/api for example?

Cheers
Arni

**Comment by tfranzel** [comment]
Hi, yes it's possible but a little bit cumbersome. I achieved the same goal for versioning like this:

```python
urlpatterns_v1 = [path('api/v1/pi/', pi)]
urlpatterns_v1.append(
    path('api/v1/schema/', SpectacularAPIView.as_view(urlconf=urlpatterns_v1))
)
```

`SpectacularAPIView` takes a `urlconf` which is a `urlpatterns` list. If you structure your `urls.py` similiar to this

```python
urlpatterns_xyz = [...]
urlpatterns_xyz.append(
    path(...., SpectacularAPIView.as_view(urlconf=urlpatterns_xyz), name="xyz_schema")
)
urlpatterns_abc = [...]
urlpatterns_abc.append(
    path(...., SpectacularAPIView.as_view(urlconf=urlpatterns_abc), name="abc_schema")
)
urlpatterns = urlpatterns_abc + urlpatterns_xyz

```

then you can scope `SpectacularApiView` into groups. 


After that you can either do 3 swagger views with `SpectacularSwaggerView.as_view(url_name='abc_schema')` or you can  can use the swagger-ui topbar (standalone) to switch between schemas

```python
    'SWAGGER_UI_SETTINGS':  '''{
        deepLinking: true,
        urls: [{url: "/backend/abc/api/schema", name: "abc"}, {url: "/backend/xyz/api/schema", name: "xyz"}],
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
    }''',
```

**Comment by CaptainArni** [comment]
I cannot get the swagger-ui topbar to work, but the solution with the 3 swagger views is working perfectly. Thank you :)

**Comment by tfranzel** [comment]
> the 3 swagger views is working perfectly

awesome! 

> I cannot get the swagger-ui topbar to work

that is weird, because i just dropped those exact (different url of course) `SWAGGER_UI_SETTINGS` into my local setup and it worked like charm.


![Untitled](https://user-images.githubusercontent.com/13507857/139649283-9098334a-3b6b-4875-9b28-00af8bbc8195.png)

**Comment by CaptainArni** [comment]
When I copied your SWAGGER_UI_SETTINGS, I am getting a blank page and if I open the browser console I see this:
`Uncaught TypeError: Cannot read properties of undefined (reading 'getLocalConfig')
    at m (swagger-ui-bundle.js:2)
    at Jr (swagger-ui-bundle.js:2)
    at 127.0.0.1/:25`
![pic](https://user-images.githubusercontent.com/15674064/139650729-8450ecf5-7535-4a39-8cd5-323bb4b231b0.png)

**Comment by tfranzel** [comment]
that is really weird! are you using the most recent spectacular (`0.20.2`)? we changed swagger-ui from `3.52.3` to `latest`.

having a wrong schema url will produce a different error with a `404`, so that is definitely not the problem.

these are the exact settings I used:

```python
SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_INCLUDE_SCHEMA": False,
    "VERSION": "0.0.1",
    "TITLE": "Fooo API",
    "DESCRIPTION": "Foooo",
    "SWAGGER_UI_SETTINGS": '''{
        deepLinking: true,
        urls: [{url: "/api/schema/", name: "abc"}, {url: "/api/schema", name: "xyz"}],
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
    }''',
}
```

**Comment by CaptainArni** [comment]
Oh it is working perfectly now with your settings. Thank you very much. :)

**Comment by tfranzel** [comment]
perfect. must have been a typo somewhere. all other settings do have zero impact on swagger.
