### ISSUE TITLE
`extend_schema` with `OpenApiResponse` results in `description: null` in generated schema

### ISSUE THREAD

**Issue by eviltwin** [tfranzel/drf-spectacular#591]
**Describe the bug**
When using `extend_schema` to add examples to an endpoint, if you do not give a value for the `OpenApiResponse`'s `description` parameter then it will produce a schema with `description: null` rather than `description: ''`. This is invalid according to the [specification](https://swagger.io/specification/#response-object).

This prevents the schema from being used by `openapi-python-client` to generate client libraries.

I think this is because the default value in `OpenApiResponse.__init__` is `None` when it should be `''`.

Obviously, there is a workaround of simply providing `description=''` to `OpenApiResponse` (or, you know, an actual description).

**To Reproduce**
```
class WidgetViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows widgets to be viewed or edited.
    """

    queryset = Widget.objects.all()
    serializer_class = WidgetSerializer
    permission_classes = [permissions.IsAuthenticated]

    @extend_schema(
        responses={
            200: OpenApiResponse(
                response=WidgetSerializer,
                examples=[
                    OpenApiExample(
                        "Undamaged Widget",
                        value={
                            "is_damaged": False,
                            "damage_reason": "",
                        },
                    ),
                    OpenApiExample(
                        "Damaged Widget",
                        value={
                            "is_damaged": True,
                            "damage_reason": "Someone broke it.",
                        },
                    ),
                ],
            )
        }
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)
        
```

**Expected behavior**
The schema should contain `description: ''` when no description parameter is passed to `OpenApiResponse`, just like it does by default when not using `extend_schema`.

**Comment by tfranzel** [comment]
@eviltwin thx! yes, that was a momentary lapse in judgement that resulted in a regression. should be fixed now.

**Comment by eviltwin** [comment]
thanks! change looks like it will do the right thing so I'll close this :)
