### ISSUE TITLE
Wrong Decimal representation patatter

### ISSUE THREAD

**Issue by kalosisz** [tfranzel/drf-spectacular#596]
**Describe the bug**

Django can't save decimal fields with empty string. Hoever, drf-spectacular generated the following patter for decimal
```
string or null <decimal> ^\d{0,3}(?:\.\d{0,5})?$
```
https://stackoverflow.com/questions/8114192/nullable-decimalfield-returns-this-value-must-be-a-decimal-number-when-blank/8168598

**To Reproduce**
Define a decimal field in a serializer or a model.

**Expected behavior**
The expected behavious for this patter should be 
```
string or null <decimal> ^\d{1,3}(?:\.\d{0,5})?$
```

**Comment by tfranzel** [comment]
hey @kalosisz, I see! good catch. However, your suggestion seems not to be bulletproof either. I have not tested this but a value of `.1` would be rejected by your proposal. Not sure if the fields does accept it though.

**Comment by kalosisz** [comment]
You point is totally valid. I guess the best way to deal with empty strings is to build custom field in django for representing it as none.

**Comment by tfranzel** [comment]
not saying this cannot be achieved. i'll reopen and have a look when i can find some time. this can certainly be modeled with an RE, but we have to pay attention that it only uses ECMA-RE compatible features. (e.g. back reference)
