### ISSUE TITLE
Could not resolve request body even though it is defined

### ISSUE THREAD

**Issue by mourad1081** [tfranzel/drf-spectacular#604]
**Describe the bug**
We expect to have parameters well defined in the generated schema, however a warning is thrown instead and the resulted schema is wrong.

**To Reproduce**
```py
    @extend_schema(
        request=[
            OpenApiParameter(name='username', type=str, location=OpenApiParameter.QUERY, required=True),
            OpenApiParameter(name='password', type=str, location=OpenApiParameter.QUERY, required=True),
        ],
        responses={status.HTTP_200_OK: PrivateUserSerializer, status.HTTP_400_BAD_REQUEST: None}
    )
    @action(detail=False, url_path='login', methods=['post'], permission_classes=[permissions.AllowAny])
    def login(self, request):
        # ...
```

**Expected behavior**
I expect no warning and correct schema generation. Instead, this is what is generated and the result in console:

```sh
Warning #0: UserViewSet: could not resolve request body for POST /api/users/login/. Defaulting to generic free-form object. (Maybe annotate a Serializer class?)
```

```yml
  /api/users/login/:
    post:
      operationId: api_users_login_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: {}
              description: Unspecified request body
```

**Comment by ngnpope** [comment]
Please see the [documentation](https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.extend_schema) for `@extend_schema`. The `request` argument is used for the request body. The `parameters` argument is used for parameters that are in the query string, headers, path, or a cookie.

If you are expecting to pass these values in the query string you'd have to use `parameters` instead of `request`.
If you want them in the request body, then you'll most likely want pass a serializer as the `request` argument.

**Comment by mourad1081** [comment]
> If you are expecting to pass these values in the query string you'd have to use `parameters` instead of `request`. If you want them in the request body, then you'll most likely want pass a serializer as the `request` argument.

I have seen the documentation. However, the issue when I try to do that is that openapi-generator creates a wrapper around the object in typescript:

```ts
export interface ApiUsersLoginCreateRequest {
    credentials: Credentials;
}
```

I do not want that wrapper. 
I want to generate this:

```ts
export interface ApiUsersLoginCreateRequest {
    username: string;
    password: string;
}
```

**Comment by tfranzel** [comment]
As @ngnpope  said, you used `extend_schema` incorrectly.

```python
# wrong !
@extend_schema(request=[OpenApiParameter,...])`

# correct
@extend_schema(parameters=[OpenApiParameter,...])`
```

But that would give you QUERY parameters on the endpoint. It has nothing to do with the body. Your second example actually targets the request body by using `request=inline_serializer(...)`. I'm pretty sure your crendentials should go into the body. 

How your typescript generator handles that is out of the scope for spectacular. They usually put parameters directly in the call signature and the body is wrapped. That a choice the generator makes and has nothing to do with the schema.
