### ISSUE TITLE
Schema defined in Serializer.to_representation() is not recognized

### ISSUE THREAD

**Issue by liuning89757** [tfranzel/drf-spectacular#605]
**Describe the bug**
I am trying to make all response format to be something like  `{ 'duration': xx, 'data': {'id': 1, 'name': 'tom'} }`, which model data is the value of "data" field, and "duration" is the request cost time  which is computed and modified by a middleware. At first i write two serializer，one is classical model serializer and another is  a wrapper serializer（with "duration" and "data" field）used only for `extend_schema(response=xx) `decorator to indicate swagger-ui show the right response. This approach works but i have to add decorator to all view function clumsily. Then i  switch to use` to_representation` method to rewrite deserialize result, does not need a wrapper serializer any more but seems swagger-ui can not recognize the schema define here. E.g : 
```
class FooSerializer(ModelSerializer):
    def to_representation(self, instance):
        ori_data = super().to_representation(instance)
        return {'duration': 100, 'data': ori_data}
```
in swagger-ui still only shows the Foo model's field, without "duraition" and "data" fields.

**To Reproduce**
rewrite to_representation function in a ModelSerializer

**Expected behavior**
swagger-ui shows the restructured  response body schema 

Am i on the wrong way ? Any suggestions are appreciated.

**Comment by tfranzel** [comment]
hi! this cannot work for multiple reasons. 

1. we cannot run `to_representation` as we have no `instance` at schema generation time.
2. even if we had an `instance`, we could not guess the types for `duration` and `data` reliably.

You need to go the extra mile when writing meta serializers in order do help spectacular discover the proper fields. I suppose you need to adapt `get_fields` to inject the proper fields at runtime. 

Take this example. it uses dynamic fields to prevent recursion issues, but the same concept applies.
 
https://github.com/tfranzel/drf-spectacular/blob/812d3ffd39347241ea9ac38793d6801cc6b17136/tests/test_recursion.py#L25-L33

If that is too complicated you can always define the response explicitly with 

```python
@extend_schema(
    responses=inline_serializer(
        'FooBar', 
        fields={'duration': serializers.IntegerField(), 'data': BarSerializer()}
    )
)
```

**Comment by liuning89757** [comment]
Thanks a lot for your reply! I will take a look at get_fields to see if can make some progress.

**Comment by liuning89757** [comment]
Seems can not  to make `get_fields` works as expected. I would like to  close this issue and use the wrapper serializer instead.

**Comment by tfranzel** [comment]
you're welcome. `get_fields` may have some pitfalls, but it should work as our tests show. fyi other users have used this mechanism for custom meta serializers as well. `inline_serializer` is nice but can become repetitive.
