### ISSUE TITLE
Send Object in OpenApiParameter.QUERY

### ISSUE THREAD

**Issue by L0llipop** [tfranzel/drf-spectacular#608]
How can I get this construction in query params using Swagger
![image](https://user-images.githubusercontent.com/47249598/145027016-62d3d6a3-3b4c-4023-a87b-82656b441cc5.png)

I am trying set type=dict in OpenApiParameter for GET request, but dict just unpacks and I get this 
![image](https://user-images.githubusercontent.com/47249598/145027707-9e906d2b-2815-410b-8810-955d902d1928.png)

Thanks!

**Comment by tfranzel** [comment]
Hi! I dont't think OpenAPI lets you do that. There are several choices for formatting, but I don't think you can get a "raw" json there. 

https://swagger.io/docs/specification/serialization/
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#style-examples

We do provide `OpenApiParameter` with `form` and `explode`, so everything that is valid in OpenAPI can be specified.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
