### ISSUE TITLE
Prepend base path when passing custom URLconfs

### ISSUE THREAD

**Issue by niccolomineo** [tfranzel/drf-spectacular#618]
Hi, given the following URL structure project-wide

```
                           ___ / uri-1 (myapp1.urls)
base / path (myproj.urls) /
                          \___ / uri-2 (myapp2.urls)
```

Given I want to pass myapp1.urls as a custom urlconf to the default API documentation view, how can I do so that "base / path" is prepended to the Swagger UI endpoint tryout calls? I couldn't find an automatic way of doing that and at the moment I am replicating the base path definition in the separate urlconf (which is not ideal), else the tryouts don't work at all.

Shouldn't in fact prepending  the base path when passing a custom urlconf be Spectacular's default behaviour?

**Comment by tfranzel** [comment]
Hi, that is specific to your project and might not reflect all cases, even though it is probably the most common one. 

are you serving multiple `SpectacularAPIViews`? we have a PR #365 in the works that allows for individual settings overrides. Would that work for you? feedback is welcome

**Comment by niccolomineo** [comment]
> Hi, that is specific to your project and might not reflect all cases, even though it is probably the most common one. 
> 
> 
> 
> are you serving multiple `SpectacularAPIViews`? we have a PR #365 in the works that allows for individual settings overrides. Would that work for you? feedback is welcome

I am serving only one `SpectacularAPIView` but I have endpoints sharing the same base path which I don't want to be taken into account.

The PR is super useful but in my case I would still need to move the base path to the myapp1.urls (as a path) and add it to the custom_settings param, thus having to manage it in two different locations.

It really seems to me that prepending the base path should be the default. Those not wanting a base path should include the desired urlconf in the root urlconf.

Am I missing anything?

**Comment by tfranzel** [comment]
if i understood correctly there are two options for you:

1. use `myproj.urls` and filter what you do not want with a [preprocessing hook](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-7-preprocessing-hooks)
2. use `myapp1.urls` and attach the common basepath to server with `'SERVERS': [{'url': 'https://example.com/BASE_PATH', 'description': 'Text'}, ...]`. caveat: it will be used by the "tryout" but the base path is not directly visible on the swagger endpoint listing.

does that make sense? I personally would go with option 1.

sidenote: spectacular does interpret the `urlconf` as the root of your server. i certainly can see where you are coming from, but changing this is a big break in compatibility for a lot of users. Also i can how both versions could be useful. I think we are stuck with this solution for better or worse.

**Comment by niccolomineo** [comment]
1. Preprocessing the urlconf simply moves the duplication issue to the hook.
2. I would still need to maintain the base path in two places: in the `SERVERS` custom setting and in the root urlconf.

I would much rather have the ability to pass a `prepend_urlconf_base_path` boolean value to the `SpectacularAPIView` - which would also work around the backward compatibility issues you were mentioning.

**Comment by tfranzel** [comment]
there is a third option I just forgot there:

```python
SPECTACTULAR_SETTINGS = {
    'SERVE_URLCONF': "app1.urls", # same as setting urlconf directly on view
    'SCHEMA_PATH_PREFIX_INSERT': '/your/base/path',
}
```

also, with the `custom_settings` PR you can set a base path manually with `SCHEMA_PATH_PREFIX_INSERT` on `SpectacularAPIView`. kind of forgot about that feature. this should then be identical to your `prepend_urlconf_base_path` flag.

**Comment by niccolomineo** [comment]
Yes, that was the solution I lobbied for in the issue related to your PR, but it is not as DRY as a boolean.

**Comment by tfranzel** [comment]
ahh sry for the confusion. I didn't notice that you were the same poster as in that PR. I was kind of in a rush.

since the functionality is basically there and your feature ask would require a non-trivial refactoring, i would decline the feature for now.
