### ISSUE TITLE
How to use x-tagGroups to generate high-level grouping?

### ISSUE THREAD

**Issue by Neyoui** [tfranzel/drf-spectacular#619]
Hi,

I'm interested in high-level grouping in Redoc, but I cannot achieve it. x-tagGroups is supported in the community version of Redoc: https://github.com/Redocly/redoc#customization-options

What I also found in the documentation for redocly is an x-tagGroups example in YAML/JSON: https://redoc.ly/docs/api-reference-docs/specification-extensions/x-tag-groups/

I tried to use the "EXTENSIONS_INFO" setting but couldn't achieve the desired result.

My settings.py in Django:
```
"TAGS": [{"name": "Firewall", "description": "Foo"}, ],
"EXTENSIONS_INFO": {
  "x-tagGroups": [
    {
      "name": "Firewall",
      "tags": ["General", "Rules", "Log", "Report"],
    },
  ],
}
```

Did someone else dig into that and can help me out?

Thanks!

**Comment by tfranzel** [comment]
Hi,

`TAGS` is a declaration list. In itself it does nothing yet, except providing an extra description. The tag must also be used by the respective endpoints. It is either tagged automatically (via `SCHEMA_PATH_PREFIX`), or it can be manually annotated with `extend_schema`.

The settings itself look good and should be part of the schema. please confirm this. If that is all good an well, I think it comes down to above statement.

**Comment by Neyoui** [comment]
Hi,

Thanks for the speedy response.

I checked the generated schema.yaml and found out that SpectacularAPIView appends the "x-tagGroups" into the "info" section, but x-tagGroups needs to be at the main level.

How can I move x-tagGroups to a different level?

Example - Redoc navigation generation incorrect
```
openapi: 3.0.3
info:
  title: ''
  version: 1.0.0
  x-tagGroups:
    - name: Foo
      tags:
        - Dummy
        - Bar
```

Example - Redoc navigation generation correct
```
openapi: 3.0.3
info:
  title: ''
  version: 1.0.0
x-tagGroups:
  - name: Foo
    tags:
      - Dummy
      - Bar
```

**Comment by tfranzel** [comment]
was not possible before. i was unaware of extensions at the root level. added a new setting `EXTENSIONS_ROOT` for this case.

**Comment by Neyoui** [comment]
Thank you very much! x-tagGroups is working fine with the new EXTENSIONS_ROOT setting :)
