### ISSUE TITLE
[Modified value]

### ISSUE THREAD

**Issue by xavierrigau** [tfranzel/drf-spectacular#623]
**Describe the bug**
When using and element from an enum in a parameter the example defaults to "Modified value"
![image](https://user-images.githubusercontent.com/93787631/146972079-d59fb62e-72ac-42b0-bbad-fb761c1b623f.png)
 

**To Reproduce**
constants.py
```
channel_types = [CHANNEL_TYPE_PUSH, CHANNEL_TYPE_SMS, CHANNEL_TYPE_EMAIL]
```
swagger.py
```
channel_type_param = OpenApiParameter(
    "channel_type",
    type=str,
    enum=constants.channel_types,
    required=True,
    examples=[
        OpenApiExample(
            "Push channel",
            parameter_only=("channel_type", "query"),
            value=constants.channel_types[0],
        )
    ],
)

```

**Expected behavior**
![image](https://user-images.githubusercontent.com/93787631/146972263-f61bbbe6-c29c-44bd-896d-0b0f99b58679.png)

If I comment the enum line like:
```
channel_type_param = OpenApiParameter(
    "channel_type",
    type=str,
    # enum=constants.channel_types,
    required=True,
    examples=[
        OpenApiExample(
            "Push channel",
            parameter_only=("channel_type", "query"),
            value=constants.channel_types[0],
        )
    ],
)
```
this doesn't happen but obviously I lost the enum.

**Comment by tfranzel** [comment]
I believe that is rather a SwaggerUI "bug". It will select the first enum item by default. This first item has no corresponding  example, so it counts as `modified value`. Beware that we sort the enum list for consistency. If you make that one example the first in the **sorted** list (`CHANNEL_TYPE_EMAIL`) it will show up as you expect. 

Sidenote: `parameter_only=("channel_type", "query"),` is not necessary when you use examples inside `OpenApiParameter`. spectacular will infer where this example belongs to. this is only required if you add that example on the root level to `@extend_schema(examples=...)`
