### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by xavierrigau** [tfranzel/drf-spectacular#625]
How do you describe an endpoint that returns only 200 + the string "ok"? Like Django's health endpoint.

I am having trouble doing the schema so it shows correctly. It show a JSON object as `{"ok": "some string"}` instead of just `"ok"`.

```
    @extend_schema(
        tags=["health"],
        summary=f"Service Health. ({__file__})",
        description='This endpoint responds with 200 + {"ok"}',
        responses={
            status.HTTP_200_OK: OpenApiResponse(
                response=inline_serializer(
                    "Health OK", fields={"ok": serializers.CharField()}
                ),
                description="Ok means I am alive 😎",
                examples=[OpenApiExample("I a cool as a 🥒", value="ok")],
            ),
        },
    )
```
![image](https://user-images.githubusercontent.com/93787631/147141485-97795750-453d-4022-85ec-937e5185f637.png)

![image](https://user-images.githubusercontent.com/93787631/147141338-ba2af0de-2333-42e3-98c4-f9a29c14ff39.png)

**Comment by tfranzel** [comment]
well you defined an object with a field named `ok`. you likely wanted something like 

```
@extend_schema(
    responses=str,  # no need for a dict if 200
    examples=[OpenApiExample("🥒", "ok")],
    ...
)
```

**Comment by xavierrigau** [comment]
> OpenApiExample("🥒", "ok")

That is just the example. My issue is with the schema.

![image](https://user-images.githubusercontent.com/93787631/147154036-a3459762-a78e-40d0-855b-d47c930adc7e.png)

**Comment by xavierrigau** [comment]
Thanks @tfranzel 😎👍🏻

**Comment by tfranzel** [comment]
`@extend_schema(responses=str)` == `@extend_schema(responses={200: str})` ==  `@extend_schema(responses={200: OpenApiTypes.STR})`

its all the same.... returning a plain string
