### ISSUE TITLE
could not resolve authenticator JWTCookieAuthenticator

### ISSUE THREAD

**Issue by aabanaag** [tfranzel/drf-spectacular#626]
I'm seeing an error, could not resolve authenticator <class 'dj_rest_auth.jwt_auth.JWTCookieAuthentication'>. There was no OpenApiAuthenticationExtension registered for that class. Try creating one by subclassing it. Ignoring for now.

my default auth classes are below:
`    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ),`

**Comment by aabanaag** [comment]
Found an article that might solve my issue, so I'll close this now apologies for not looking at the docs properly.. :D

**Comment by tfranzel** [comment]
Hi, no that issue was legitimate. This extension was missing for `dj_rest_auth`. Which article are you referring to? 

You can copy&paste this extension until the next release.
