### ISSUE TITLE
Json $Ref Error in response

### ISSUE THREAD

**Issue by pranto157** [tfranzel/drf-spectacular#628]
Hello I'm getting this error in my swagger UI. Anyway to fix this? 
![kson](https://user-images.githubusercontent.com/195230/147967208-22f2e05a-22e9-441c-aefd-dd4a19f3f26e.png)

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/issues/378#issuecomment-1004288446

you reference definitions that are nested inside a component? I don't know if that is even legal. Apparently SwaggerUI looks for definitions in a different location. This is not part of drf-spectacular functionality anyway.

https://swagger.io/docs/specification/using-ref/

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
