### ISSUE TITLE
TITLE support for serializers / schemas

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#629]
**Describe the bug**
We're using drf-spectacular with RapiDoc and one of our API endpoints has `one-of` type serializer. Everything works great, but the UI is missing unique identificators

We have extended our view like
```py
@extend_schema(
    methods=["PUT"],
    request=PolymorphicProxySerializer(
        component_name="AnimalSerializerVariations",
        serializers=[
            DogAnimal,
            CatAnimal,
        ],
        resource_type_field_name=None,
    ),
    parameters=[
        OpenApiParameter(
            "animal_type",
            location=OpenApiParameter.PATH,
            enum=["dog", "cat"],
            description="Type of animal being modified",
        ),
    ],
)
```

and the UI looks like
![image](https://user-images.githubusercontent.com/5418540/148546526-63cb80fc-5023-46db-b986-bb70ebcf4bf4.png)

It is kinda understandable, but it would be better if we could somehow give a `title` to the serializer/schema.
When I modify the schema manually and add
```yaml
CatSchema:
  title: Cat       # <- this line
  type: object
  properties:
    ...
DogSchema:
  title: Dog       # <- this line
  type: object
  properties:
    ...
```

Then the UI looks a lot understandable

![image](https://user-images.githubusercontent.com/5418540/148546914-e660ded1-bbda-49ba-b8e9-8f877c767068.png)

**Expected behavior**
Ability to provide `title` to serializers, either via `@extend_schema` decorator on view or `@extend_schema_serializer` decorator on serializer (Or any other decorator)

EDIT: 
RapiDoc has example of this: https://mrin9.github.io/RapiDoc/examples/oneof.html?ref=https://githubhelp.com#get-/one-of/schema
And this should be a valid schema, because this field is described in OA3 Spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#properties

**Comment by tfranzel** [comment]
Hi, so I had a quick look and its an interesting proposal. First of all the only location it could be added would be `@extend_schema_serializer`. `@extend_schema` would be the wrong scope as it is targeted to views mainly.

I usually consider SwaggerUI the ground truth as it is the most complete solution imho.

- SwaggerUI: shows the `title` and falls back to component name (`CatSchema`) if no title is present.
- Redoc: Does not show a name with or without `title`. However uses discriminator for schema selection which has a name associacted with it. (you turned that off though with `resource_type_field_name=None`)
- RapiDoc: only shows the name with explicit `title`

Although doable with `@extend_schema_serializer`, not sure if this is important enough to further complicate the interface. The user would need to differentiate between the `component_name` argument and `title`. 

Have you considered opening a feature request with RapiDoc to mirror the SwaggerUI functionality? It would really make sense imho. I don't see a good reason why you wouldn't use the component name from `$ref` for this.

fyi: with the current version, you could do this easy with a simple postprocessing hook.

**Comment by HansAarneLiblik** [comment]
Solved with postprocessing-hook.

Added `_apidoc_title` to serializer `Meta` class and will loop over the serializers in the hook and add the `title` attribute to schema manually. 

Thanks for the tip

**Comment by chgad** [comment]
Hi, i know it's not a best practice to reply to closed Issues but I'm at the exact same problem.
@HansAarneLiblik could you please show your solution with the postprocessing-hook?
Feel free to contact me via mail if you don't want to share it here.

**Comment by HansAarneLiblik** [comment]
@chgad Sure!

I added `_apidoc_title` attr to serializer `Meta` class, where I need the title (Polymorphic serializers were my usecase)

```py
class MySerializerSerializer(Serializer):
    data = serializers.ListField(child=serializers.CharField())

    class Meta:
        _apidoc_title = "My Title"     # <--- THIS
        model = MyModel 
```

Then I added a postprocessing-hook

```py
def add_title_to_schema(
    result: PostProcessingHookResult, generator: SchemaGenerator, **_kwargs: Any
) -> PostProcessingHookResult:
    """
    Adds title to schema based on `_apidoc_title` attr in serializer Meta class
    """

    for name, schema in result["components"]["schemas"].items():
        if "title" not in schema:
            component_key: tuple[str, str] = (name, ResolvedComponent.SCHEMA)
            try:
                component: ResolvedComponent = generator.registry[component_key]
            except KeyError:
                continue

            ser: Serializer = component.object
            ser_meta: SerializerMetaclass | None = getattr(ser, "Meta", None)
            if ser_meta and (title := getattr(ser_meta, "_apidoc_title", None)):
                schema["title"] = title

    return result
```

and then I defined this hook in my settings

```py
SPECTACULAR_SETTINGS = {
    ...
    "POSTPROCESSING_HOOKS": [
        ... 
        "apidoc.hooks.add_title_to_schema",
    ]
}
```

**Comment by chgad** [comment]
Please excuse me for answering again on the issue but i found a different solution to the aforementioned problem.

In case you use a Base class for your searilizers in question you can use OpenApiSerializer Extension as follows:

``` python
    class TitleSerializerExtension(OpenApiSerializerExtension):
        target_class = "path.to.YourBaseSerializer"
        match_subclasses = True

        def map_serializer(self, auto_schema, direction):
            schema = auto_schema._map_serializer(self.target, direction, bypass_extensions=True)
            ser_meta = getattr(ser, "Meta", None)
            if ser_meta and (title := getattr(ser_meta, "_apidoc_title", None)):
                schema["title"] = title
            return schema
```

**Comment by thalida** [comment]
Commenting for the next person who may need it...
I found this simple postprocessing hook to set the schema title to the schema name helpful when using Stoplight Elements.
```py
# in docs/hooks.py
def assign_schema_name_to_title(result, generator, **_kwargs):
    for name, schema in result["components"]["schemas"].items():
        if "title" not in schema:
            schema["title"] = name

    return result
```

```py
# in settings.py
SPECTACULAR_SETTINGS = {
    [...],
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "docs.hooks.assign_schema_name_to_title",
    ],
}
```

| Before | After |
|-------|-------|
|<img width="400" alt="Screenshot 2024-06-29 at 23 57 32" src="https://github.com/tfranzel/drf-spectacular/assets/3401715/6c6ef313-3eb3-4156-b080-f24445bf677c">|<img width="400" alt="Screenshot 2024-06-30 at 00 03 46" src="https://github.com/tfranzel/drf-spectacular/assets/3401715/c5c8f018-6c92-4900-8877-bd3bd54d4955">|

**Comment by tfranzel** [comment]
@thalida thank you for sharing. Your postprocessing seems like the best solution. It is small an concise and gets the job done.
