### ISSUE TITLE
Change Accept header in curl request

### ISSUE THREAD

**Issue by Lusmft** [tfranzel/drf-spectacular#632]
Hi! I need to change standard Accept Header 'application/json' to another, and then send this header with every request (I mean curl request). How can I do this? I've tried to add OpenApiParameter with location=Header and named 'Accept', but it's not working.

**Comment by tfranzel** [comment]
Hi! Not a bad idea but unfortunately this does not work. The `Accept` header is implicit in OpenAPI. `Accept` and `Authorization` headers are the only headers that should not be explicitly used with `OpenApiParameter`.

If it is a one-off you can use 

```python
@extend_schema(
   request={'application/xml': XSerializer}
   responses={(200, 'application/xml'): XSerializer}
)
```

If this is a common thing for you I recommend subclassing Renderer and Parsers for this and setting the `media_type` attribute. Then you set `renderer_classes` and `parser_classes` on your views, which get picked up automatically by spectacular. This is the cleanest approach and also reflects exactly what your API is doing

**Comment by Lusmft** [comment]
Thanks for your fast answer! I will try to use your advices and then will give you a feedback.

**Comment by Lusmft** [comment]
> If this is a common thing for you I recommend subclassing Renderer and Parsers for this and setting the `media_type` attribute. Then you set `renderer_classes` and `parser_classes` on your views, which get picked up automatically by spectacular. This is the cleanest approach and also reflects exactly what your API is doing

I've made this and it's works! Now I can choose Accept Header in media type attribute in Swagger-ui. Thank you very much!

**Comment by tfranzel** [comment]
awesome!

 fyi you can make your choice default with the DRF settings `DEFAULT_RENDERER_CLASSES` and `DEFAULT_PARSER_CLASSES`
