### ISSUE TITLE
Enum order is inconsistent in generated schema.

### ISSUE THREAD

**Issue by ford-carta** [tfranzel/drf-spectacular#633]
Enum order is inconsistent in generated schema.

The following list is out of order
`        CeleryTaskStateEnum:
      enum:
      - SUCCESS
      - RECEIVED
      - PENDING
      - RETRY
      - STARTED
      - REVOKED
      - FAILURE
      type: string`
 

**Expected behavior**
This is the sorted list generated after I made the following changes to the `postprocess_schema_enums` hook

`    CeleryTaskStateEnum:
      enum:
      - FAILURE
      - PENDING
      - RECEIVED
      - RETRY
      - REVOKED
      - STARTED
      - SUCCESS`

## Added function in drf_spectacular.hooks
`def sort_enum_schema(schema):
    schema["enum"] = sorted(schema["enum"]);
    return schema
`

## Consumed function in drf_spectacular.hooks
    ```def create_enum_component(name, schema):
        component = ResolvedComponent(
            name=name,
            type=ResolvedComponent.SCHEMA,
            schema=sort_enum_schema(schema),
            object=name,
        )
        generator.registry.register_on_missing(component)
        return component```

**Comment by tfranzel** [comment]
Hi,

so this was actually a deliberate choice:

https://github.com/tfranzel/drf-spectacular/blob/e905ee5306a39be9868e59f433085a3b7bc8c581/drf_spectacular/plumbing.py#L340-L341

Users may have intentions behind the enum ordering or alphanumeric ordering simply would be really weird (e.g. ["one", "two" "three"]). We do sort a lot of places but only skip this for serializer fields (where it might originate from a model field).

However, I can see how that choice might be intransparent or even inconsistent to a user. Maybe we should add a setting for this

**Comment by ford-carta** [comment]
I totally agree that it makes sense to leave the decision of ordering to the user, but I'm wondering why it's inconsistent. Meaning I can run the command twice and get different schema enum order's each time. Though come to think of it, maybe the inconsistency exists in the serializer creation (before it hits drf spectacular) and this is my improper use of the tool. Can you confirm that there is no unintended randomization in drf-spectacular or put another way the ordering is preserved to what the user feeds in?

**Comment by ford-carta** [comment]
The randomness was coming from the fact that we were using celery tasks states which for some reason celery implemented with a frozenset that has no order 🤷‍♂️ .

**Comment by tfranzel** [comment]
thanks for clarifying. drf-spectcular actually guarantees a reproducible schema without any randomness. everything else would be crazy :smile: any changes to the schema, without any code changes, would be considered a bug.

I mean we do sort the majority of lists with that notable exception. Not sure if we could have prevented the frozenset issue as it sounds like that randomization happened before spectacular gets a hold of it.
