### ISSUE TITLE
Question: Is it possible to document a custom response so that drf-spectacular uses it with a minimal `extend_schema`?

### ISSUE THREAD

**Issue by TheCodeSummoner** [tfranzel/drf-spectacular#634]
Apologies for asking a question as an issue, but I couldn't find any discussion boards.

As for the question, consider a simple `extend_schema` decoration:

```python
@extend_schema(responses=[SuccessResponse])
def foo():
    return SuccessResponse("Bar")
```
with the `SuccessResponse` being:
```python
from rest_framework.response import Response

class SuccessResponse(Response):
    def __init__(self, message: str):
        super().__init__(data={"message": message}, status=200)
```

Right now the generated schema (looked it up quickly via swagger) will suggest something like this as a response:
```
{
  "additionalProp1": "string",
  "additionalProp2": "string",
  "additionalProp3": "string"
}
```
whereas what I'd like it to say (or something similar) is:
```
{
  "message": "string"
}
```

So the question is if I can somehow document `SuccessResponse` so that `drf-spectacular` picks up the information automatically? I don't want to specify examples or return types with every method - just the responses. Ideally, I should document the response class with something along the lines of "for a response with code 200 you will get this data structure".

**Comment by tfranzel** [comment]
Hi @TheCodeSummoner, spectacular cannot process `Response` because it is not introspectable. Usually you want a serializer there. Here are the valid inputs for `responses`:

https://github.com/tfranzel/drf-spectacular/blob/67af2ebbb62c5f9d7d63bd181893a740af6fe74f/drf_spectacular/utils.py#L223

you likely want this

```python
@extend_schema(
        responses=inline_serializer(
            name='SuccessResponse',
            fields={'message': serializers.CharField()}
        )
    )
    @api_view(['GET'])
    def one_off(request, foo):
        pass  # pragma: no cover
```

`inline_serializer` is useful for one-off serializers. Create an explicit serializer if you are reusing this. If you need multiple responses use a dict: 

```python
@extend_schema(responses={200: XSerializer, 203: YSerializer})
```

FYI: Also pay attention to warnings on the console (easiest to read when CLI is used). Your usage of `Response` should have triggered a warning about an incorrect argument.

**Comment by tfranzel** [comment]
doc for more info: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-2-extend-schema

**Comment by TheCodeSummoner** [comment]
Thanks!

It's not ideal, but it's a reasonable solution. For reference, I'm defining my response as follows:

```python
class SuccessResponse(BaseResponse):
    """
    This is kinda like the class shared in the initial post,
    but copied directly from my code instead (I'm lazy).
    """

    serializer = inline_serializer(
        name="SuccessResponse",
        fields={
            "message": CharField()
        }
    )

    def __init__(self, message: str, **kwargs):
        super().__init__(message, 200, **kwargs)
```

and using it like so:

```python
@extend_schema(responses={
    200: SuccessResponse.serializer,
    400: ExceptionThrownResponse.serializer
})
@action(detail=False, methods=["GET"], name="FooBar")
def foo(self, request, *_, **__):
    self.bar()
```

works like a charm so far :)

**Comment by tfranzel** [comment]
I actually think this is quite neat and most likely the cleanest solution for using `Response`. very nice!
