### ISSUE TITLE
Fix AcceptHeaderVersioning support in Swagger interactive Try It Out

### ISSUE THREAD

**Issue by szymonhab** [tfranzel/drf-spectacular#637]
**Describe the bug**
Currently for DRF AcceptHeaderVersioning the Swagger UI Try It Out box does not work correctly - underlying swagger schema does not contain proper Media Type with version parameter

This is generated schema for `SpectacularAPIView().as_view(api_version="2")`
```
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductV2'
```    
How it should look alike:
```
  responses:
    '200':
      content:
        application/json;version=2:
          schema:
            $ref: '#/components/schemas/ProductV2'
```    

**To Reproduce**
Just create simpliest GET endpoint with two different serializers and AcceptHeaderVersioning. Only `REST_FRAMEWORK.DEFAULT_VERSION` will be supported because Media Type in `content:` has only application/json part

I see that there is already code responsible for generator request versioning:
```
def modify_for_versioning(patterns, method, path, view, requested_version):
<...>
    elif issubclass(view.versioning_class, versioning.AcceptHeaderVersioning):
        # Append the version into request accepted_media_type.
        # e.g "application/json; version=1.0"
        # To allow the AcceptHeaderVersioning negotiator going through.
        if not hasattr(view.request, 'accepted_renderer'):
            # Probably a mock request, content negotation was not performed, so, we do it now.
            negotiated = view.perform_content_negotiation(view.request)
            view.request.accepted_renderer, view.request.accepted_media_type = negotiated
        media_type = _MediaType(view.request.accepted_media_type)
        view.request.accepted_media_type = (
            f'{media_type.full_type}; {view.versioning_class.version_param}={requested_version}'
        )
```
But it isn't supported in openapi.py:
```
    def map_renderers(self, attribute):
        <...>
 ````
 
 How it should look in UI after fix:

![image](https://user-images.githubusercontent.com/10489428/150554869-29100980-4050-47dd-8d42-243000302adb.png)

**Proposed solution**
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L1253
here we should concatenate media_type var with {version_param}={requested_version}
though i am not sure if we have access to requested_version param in this scope

**Comment by tfranzel** [comment]
Hey @szymonhab, excellent find! 

> I see that there is already code responsible for generator request versioning

yes that code is responsible for massaging mocked requests for CLI usage. It does what we would likely need here also, but is tailored to a different use-case.

Another consideration is whether it is legal according to OpenAPI, but looks fine on first sight. I will look into it.

**Comment by szymonhab** [comment]
@tfranzel Thank you very much! It works like a charm. Also: this works correctly after i totally remove `REST_FRAMEWORK.DEFAULT_VERSION` param :+1:
