### ISSUE TITLE
How to hide schemas in swagger page?

### ISSUE THREAD

**Issue by goldentoaste** [tfranzel/drf-spectacular#638]
This anyway to hide certain schemas on the swagger pages? See the sample below, "Coffee" is a django model  and this is the only thing i want to be displayed. 'CoffeeSerialNoId' and 'ResponseSerial' are 2 serializers I wrote just for documentation purpose, and 'PatchedCoffee' is probably generated by drf-spectacular. 

![image](https://user-images.githubusercontent.com/59712548/150660741-74eb0feb-a208-4f8b-8273-59ca2a7843f1.png)

**Comment by tfranzel** [comment]
Hi @goldentoaste. Spectacular works on the basis of serializers (not models directly), If you nest serializers, they will be used, unless explicitly excluded like so:

```python
    @extend_schema_serializer(exclude_fields=['hidden1', 'hidden2'])
    class CoffeeSerializer(serializers.Serializer):
        integer = serializers.IntegerField()
        hidden1 = serializers.IntegerField()
        hidden2 = CoffeeSerialNoId() # for example
```

``PatchedCoffee`` is there because your endpoint allows `PATCH` and that is slightly different from `Coffee`, thus the derivative.

**Comment by goldentoaste** [comment]
Hi, thanks for the reply. I was able to hide the serializers I have created, by excluding all fields. Like so: 
```py
@extend_schema_serializer(
    exclude_fields=['status', 'message']
)
class ResponseSerial(Serializer):
    status = IntegerField()
    message = CharField()
```

Could you explain the 'PATCH' behaviour too? and how should I hide these patched schemas?

(on a side note, I am somewhat new to github etiquette still, is asking questions about the repo in the issues section generally okay?)

**Comment by tfranzel** [comment]
This certainly feels weird to me. There are valid reasons for hiding, but generally it is kind of an anti-pattern. Your would rather tighten down your API to reflect what the API contract should look like. Exposing endpoint that show up nowhere might be forgotten about while posing increased attack surface. I generally would recommend not doing this too much.

>  by excluding all fields. Like so:

excluding everything is easier. you can do this on the view method 

```python
@extend_schema(exclude=True)
def list(self, request, *args, **kwargs):
```

or on the view class

```python
@extend_schema_view(
    list=extend_schema(exclude=True),  # <-------
    retrieve=extend_schema(description='overridden description for child only'),
    raw_action=extend_schema(summary="view raw action summary"),
)
class ZViewSet(XViewSet):
```

> Could you explain the 'PATCH' behaviour too? and how should I hide these patched schemas?

patch is a partial update, so not all fields are required, hence a slightly different schema. Why would you hide this in the schema? if you don't want to offer it then don't expose it with the viewset (or `@extend_schema_view(patch=extend_schema(exclude=True))`)

> (on a side note, I am somewhat new to github etiquette still, is asking questions about the repo in the issues section generally okay?)

It's okay after a certain amount of research and consulting the documentation. My time for this is limited though.

**Comment by goldentoaste** [comment]
Great, thanks for all your help!
