### ISSUE TITLE
Use serializer as a field of inline serializer

### ISSUE THREAD

**Issue by pkariz** [tfranzel/drf-spectacular#642]
I can't find any info on 2 questions that i have, so i'm opening this issue, sorry if that's not appropriate.

1.  Is it possible to specify serializer as a field, so something like this? 
```
@extend_schema_field(inline_serializer(
    name='StatsInfoInlineSerializer',
    fields={
        **{
            prop: InfoSerializer(many=True),
            for prop in Stats.objects.values_list('name', flat=True)
        },
        'extra: serializers.CharField(),
    },
))
```
2.  How can i expand an existing serializer which uses `SerializerMethodField` without losing schemas for it? Imagine that `InfoSerializer` has field `a` which is `SerializerMethodField`, then in the example bellow `extend_schema_field` for `a` is lost. I have quite a few cases where I want to extract only specific fields from an existing serializer, so that's where i've tried the code bellow
```
@extend_schema_field(inline_serializer(
    name='InfoExtendedInlineSerializer',
    fields={
        **{
            k:v for k,v in InfoSerializer().get_fields().items()
            if k in ['a', 'b', 'c']
        },
        'extra: serializers.CharField(),
    },
))
```

Thanks in advance for the help and also for writing this awesome package!

**Comment by tfranzel** [comment]
Hi @pkariz, thanks! 

1. We only make use of the models and not the actual database. Nothing is preventing you from doing this, however the decorators are applied only once and thus when the interpreter hits this statement, the database needs to be available and your `StatsInfoInlineSerializer` is basically frozen at that point in time. To make this dynamic over multiple requests to `SpectacularSchemaView`, you would need to make use of the view's `get_serializer_class()` and generate a fresh (decorated) serializer on the fly each time.

2. I see. `SerializerMethodField` is special in that it consists of two parts. The field declaration and the actual method. You only set the field declaration and are missing the method. To make this work you would likely need a more complicated method of iterating the contents of `InfoSerializer` which accounts for the special case. This likely more complicated than just doing

```python
@extend_schema_serializer(exclude_fields=['x', 'y', 'z'])
class InfoExtendedInlineSerializer(InfoSerializer):
    extra = serializers.CharField()

@extend_schema_field(InfoExtendedInlineSerializer)
def foo():
```

**Comment by pkariz** [comment]
Thanks for the answers!
last question: is there a way to pass serializer as a path, for example as a tuple (serializer_path, serializer_args, serializer_kwargs)?

**Comment by tfranzel** [comment]
https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.inline_serializer

`**kwargs` to `inline_serializer` will be used for the constructor, e.g. `inline_serializer(name=..,fields=..., many=True)`

> is there a way to pass serializer as a path, for example as a tuple (serializer_path, serializer_args, serializer_kwargs)

i'm not exactly sure what you mean by that. i don't know what serializer path is supposed to mean.

**Comment by pkariz** [comment]
> i'm not exactly sure what you mean by that. i don't know what serializer path is supposed to mean.

Let's say i want to do `extend_schema_field(SerializerA(many=True))` but i can't import `SerializerA` in this file because i would have circular import, so i would like to do something like this: `extend_schema_field(('other.api.serializers.SerializerA', [], {'many': True}))`. I've somehow managed to achieve something like this with `extend_schema_field`, but i don't see how to do it with `inline_serializer`.

**Comment by tfranzel** [comment]
i see now. we do have something for those kind of issues: https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/helpers.py

however, this might still fail with `inline_serializer` because `lazy_serializer` imports at usage time (e.g. __init__) and `inline_serializer` will init the class with the `kwargs` as the last step. thus the import is delayed but not enough to break the import cycle i suspect

`inline_serializer` was designed as a convenient short-hand. it was not made for complicated recursive/dynamic setups, thus your mileage may vary. 

your setup sounds quite non-standard and that issue has not come up before on several large/complicated codebases. writing your own dynamic/lazy `inline_serializer` seems necessary for your use-cases.

**Comment by pkariz** [comment]
I see, thanks for all the help, really appreciate it!
