### ISSUE TITLE
Spectacular Swagger-UI view (doesn't render in browser)

### ISSUE THREAD

**Issue by jd-dev-pneu** [tfranzel/drf-spectacular#645]
I am attempting to get the swagger-ui to render using SpectacularSwaggerView.as_view(), but when I access the URL in the browser it just downloads the spec and doesn't render the Swagger-UI,

I am defining my schema routes as follows,

    re_path(r"^(?P<version>(v2))/schema/$", SpectacularAPIView.as_view(), name='schema'),
    re_path(r"^(?P<version>(v2))/schema/swagger-ui/$", SpectacularSwaggerView.as_view(url_name='schema'), name="swagger-ui"),

When I hit the ../schema/ endpoint it generates and downloads the spec as I would expect, but when I hit the
../schema/swagger-ui/ endpoint I would expect it to render the swagger-ui and instead it downloads the schema much like the /schema route does.  I was wondering if I'm doing something wrong with my path definitions.

**Comment by tfranzel** [comment]
> I was wondering if I'm doing something wrong with my path definitions.

must be. this has worked (and is working) flawlessly for hundreds of people for an extended period of time. `SpectacularSwaggerView` is supposed to return a basic html page.

we would need a reproduction with browser version, HTTP headers/body for request and response.

**Comment by jd-dev-pneu** [comment]
Figured it out.

**Comment by theoden-dd** [comment]
For those who find this by "white screen" or "does not render" keywords.

This could be the CSP policy: https://github.com/tfranzel/drf-spectacular/issues/173#issuecomment-1154466855

**Comment by christiansicari** [comment]
> Figured it out.

Probably, saying what was wrong might help more than "figured it out"

**Comment by tfranzel** [comment]
@kostasgian to my knowledge this is almost always due to CSP headers (e.g. `django-csp` or manually via nginx). Your browser console should have error messages regarding csp violations.

If that is the case, the solution is here: https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-swagger-ui-and-or-redoc-page-is-blank

**Comment by kostasgian** [comment]
@tfranzel I have checked those headers and the link before. The problem remained even if I added them in settings. 
Moreover, I don't see anything going on in the browser's console nor in network. Everything looks normal but instead of opening the swagger page it downloads the yaml file.

**Comment by tfranzel** [comment]
@kostasgian I see. Not exactly sure how it is possible to get the schema and not the swagger HTML, if you do a request on `SpectacularSwaggerView`'s url. It is hard to debug from here without more information.

All I can say is that it is most likely not a bug but rather a misconfiguration somewhere on your part. 

P.S. the versioning in the original question should not play a relevant role here, unless there is a schema response but is has no endpoints. Blank white screen is a different issue from swagger ui with all endpoints missing

**Comment by kostasgian** [comment]
@tfranzel thanks for the comments. Agree that most probably it's something in my configuration. I hope I'll find this at some point and update here as well.

**Comment by P-Baracz** [comment]
> @tfranzel thanks for the comments. Agree that most probably it's something in my configuration. I hope I'll find this at some point and update the thread as well.

Have you found the solution? I have the same problem and also already checked CSP and it doesn't help.

**Comment by P-Baracz** [comment]
> @P-Baracz what does the browser console say? blank screen? server request log?

I oppened new issue:
https://github.com/tfranzel/drf-spectacular/issues/1172

**Comment by tfranzel** [comment]
To anyone coming here. There are 2 main reasons this happens.

1. You have some kind of CSP and the request cannot go through. Look in your browser console for clues
2. You changed `path` to `re_path` and broke routing priority, as they have different mechanics. Consider one of the following:
    * properly terminate (`$`) the RE to let other entries match too: `"^api/schema/$"`
    * put the schema (shortest prefix) last and the UI first in the list.
    * use `path` instead of `re_path`


@kostasgian try out the suggestions for issue 2.

@P-Baracz thanks for providing enough context to let us finally figure the other reason.

I will add reason 2. to the FAQ: https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-swagger-ui-and-or-redoc-page-is-blank
