### ISSUE TITLE
OpenAPI spec generation has collisions (operationId)

### ISSUE THREAD

**Issue by jd-dev-pneu** [tfranzel/drf-spectacular#646]
I ran into an issue generating an openapi spec using the manage.py spectacular tooling, it generates the spec but gives me the following warning which I'm not sure how to resolve,

Warning #0: operationId "api_v2_carriers_retrieve" has collisions [('/api/v2/carriers/', 'get'), ('/api/v2/carriers/{id}/', 'get')]. resolving with numeral suffixes.

It seems like the tooling should generate different operationId's for these to endpoints, but isn't so its complaining they are duplicated.  It appears to resolve them as stated by the warning, but was wondering if this is a bug or there is something I need to extend on the schema using the extend_schema decorator

**Comment by jd-dev-pneu** [comment]
Resolved this by overriding the auto generated operationId and specifying unit ones for each of these operations.

**Comment by tfranzel** [comment]
It seems like the tooling should generate different operationId's for these to endpoints,

it does. it just tells you the names aren't perfect.

a viewset would normally generate `api_v2_carriers_retrieve` and `api_v2_carriers_list`. If you do this kind of stuff manually by hand (e.g. APIView), there is no list detection and thus you must use `@extend_schema` to resolve that conflict manually.
