### ISSUE TITLE
Request for clarification about how to use drf_spectacular.utils classes.

### ISSUE THREAD

**Issue by TauPan** [tfranzel/drf-spectacular#652]
So I'm happily continuing to convert our api docs to drf-spectacular and I decided to tackle the hard problems first which require the least modification in our code in order to get the lay of the land...

So of course we use a very peculiar pagination class:

~~~python
from rest_framework import pagination
from rest_framework.views import Response


class LinkHeaderPagination(pagination.CursorPagination):
    ordering = "created"

    def get_paginated_response(self, data):
        next_url = self.get_next_link()
        previous_url = self.get_previous_link()

        if next_url is not None and previous_url is not None:
            link = '<{next_url}>; rel="next", <{previous_url}>; rel="prev"'
        elif next_url is not None:
            link = '<{next_url}>; rel="next"'
        elif previous_url is not None:
            link = '<{previous_url}>; rel="prev"'
        else:
            link = ''

        link = link.format(next_url=next_url, previous_url=previous_url)
        headers = {'Link': link} if link else {}

        return Response(data, headers=headers)

    def get_paginated_response_schema(self, schema):
        return schema
~~~

(`get_paginated_response_schema` needs to be overridden because otherwise it's being rendered with `prev` and `next` in the response schema.)

And I wanted the parameters to render correctly so I tried the following:

~~~python
class FixLinkHeaderPagination(OpenApiFilterExtension):

    target_class = 'sis.pagination.LinkHeaderPagination'

    def _broken_get_schema_operation_parameters(self, auto_schema, *args, **kwargs):
        return [
            openapi.OpenApiParameter(
                name='cursor',
                type=openapi.OpenApiTypes.URI,
                location=openapi.OpenApiParameter.QUERY,
                description=LINK_HEADER_PAGINATION_DESCRIPTION)]

    def get_schema_operation_parameters(self, auto_schema, *args, **kwargs):
        return [
            {'name': 'cursor',
             'in': 'query',
             'type': 'string',
             'format': 'uri',
             'description': LINK_HEADER_PAGINATION_DESCRIPTION}]
~~~

(`LINK_HEADER_PAGINATION_DESCRIPTION` is a bit longer and points at https://2.python-requests.org/en/master/user/advanced/#link-headers as well as https://developer.github.com/v3/#pagination)

This actually works if I use the second method, but the documentation at https://drf-spectacular.readthedocs.io/en/latest/drf_yasg.html seems to imply that I should use the `OpenApiParameter`, `OpenApiTypes` etc. classes.

Also https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.OpenApiParameter seems to tell me that I'm supposed to use this class and I see that it's used internally in drf-spectacular, but I get `OpenApiParameter object is not iterable` when I try it (because it's not a dictionary).

**Comment by TauPan** [comment]
Thanks for the clarifications!

> `get_schema_operation_parameters` and `get_paginated_response_schema` are interfaces defined by DRF, which we only reuse. We pass these through "without" modification, which is why this is rather basic.
[...]
> The spectacular interface itself is quite well typed, so you should be able to see what is allowed/expected via the types (and the doc). Yes, we require `OpenApiParameter` (or a serializer) for all parameters in **our** API. We generally recommend/require using the types in `util`.

I'll try to pay more attention to the types.

> 
> The exception, as you found out, is this method. It is an unmodified raw schema dict because the interface originated from DRF and extensions are a bit more low level than the rest. But I can see the potential for confusion there.

> I'm open to the idea of transforming `OpenApiParameter` there on the fly.

I don't have a clear idea what that would mean. I certainly would appreciate a more consistent api but now I know how to use the existing one, I think.

> other extensions have used build_parameter_type from plumbing for a slightly more robust interface.

I have looked at that function and how it's used in code and again I don't have a clear idea how that would help in my particular case.

**Comment by tfranzel** [comment]
> I don't have a clear idea what that would mean. I certainly would appreciate a more consistent api but now I know how to use the existing one, I think.

nevermind. I thought about it again and I think it's ok the way it is. it is consistent, but the reasoning behind it is not always obvious. just think like this:
- Decorators and the likes are our high level fully-typed interface. 
- Extensions on the other hand is our second level interface and as such requires a bit more flexibility. All extension methods only return basically raw schema types. The extensions system is thus consistent with itself.

> I have looked at that function and how it's used in code and again I don't have a clear idea how that would help in my particular case.

it's just a little more structured than writing a raw dict by hand, possibly preventing typos.

**Comment by TauPan** [comment]
Ok... I think what you did in https://github.com/tfranzel/drf-spectacular/commit/27ac1ca9f288c154ba2110d5ef8b828a0501ed60 should cover that.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
