### ISSUE TITLE
Cant get docs for any of my endpoints

### ISSUE THREAD

**Issue by danilocubrovic** [tfranzel/drf-spectacular#653]
Need a little help.
Cant get docs for any of my andpoints on swager-ui except default  /api/schema/ and several endpoints from djoser library.

I have created file with one simple service like:

def auth2(request):
    json_dict = dict(
        _id='2',
        toc='xyztoc',
        name='John',
        mail='john@mail.com',
        perm='rwx',
        important='true',
        moretok='mrt'
    )

    return JsonResponse(json_dict)

and in urls:

    path('someaction/',   atest.auth2),

and this service works from browser but not listed on swagger-ui page
If I add to explorer /someaction/
I got on page error data

_

> Unable to render this definition
> The provided definition does not specify a valid version field.
> 
> Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

_

I can see in browser console that this service is accessed and get expected json response but something there not supported so I need a little help to see if this config/service/whatever issue so I can move on to more complex examples.

**Comment by tfranzel** [comment]
this is not a DRF view. we only support DRF

https://www.django-rest-framework.org/api-guide/views/#api_view

use `@extend_schema(responses=...)` decorator since function bodies cannot be inspected.

the schema should never be invalid, but the error message is not enough to bugfix this. post the actual schema.
