### ISSUE TITLE
Exclude a path (so that it won't be visible in Swagger)

### ISSUE THREAD

**Issue by mamazu91** [tfranzel/drf-spectacular#655]
Hi!

I'm pretty sure this questions was raised like a hundred times, but somehow I'm having a hard time understanding how to solve it.

When I generate OpenAPI schema with drf-spectacular, I have the following paths in it:
- **/api/v1/auth/**
- /api/v1/shops/
- /api/v1/goods/
- etc.

How can I exclude a specific path, like the path **/api/v1/auth/** in this case, so that it won't end up in the schema, and thus won't be visible in Swagger?

In my understanding this should be achievable by writing a custom preprocessing hook, but somehow I cannot get it working. I tried creating **openapi.py** file in my project's root folder with the following code:
```python
def custom_preprocessing_hook(endpoints):
    path_to_exclude = 'auth'
    return [
        (path, path_regex, method, callback)
        for path, path_regex, method, callback in endpoints
        if not (path.endswith(path_to_exclude) or path.endswith(path_to_exclude + '/'))
    ]
```

And then putting the import statement to the **settings.py** file:
```python
SPECTACULAR_DEFAULTS = {
    "PREPROCESSING_HOOKS": ["shop_backend.openapi.custom_preprocessing_hook"],
}
```

Alas, I still see the path in Swagger.

Could you please point me to what I'm doing wrong exactly?

**Comment by tfranzel** [comment]
Hi @mamazu91 

decorate the view or function with `@extend_schema(exclude=True)`. You can search the tests for usages. every use-case is covered there.

using extensions for just a handful of exclusions of your own views is overkill. also it's `SPECTACULAR_SETTINGS` and not `SPECTACULAR_DEFAULTS`

**Comment by tfranzel** [comment]
> Thank you for the reply! Yes, I'm aware of that option, and I do use it to hide some of my views, but the problem with /api/v1/auth/ in particular is that it's the default Django view,
> So I thought in this case overkill would be to override the whole function just to put @extend_schema(exclude=True) 

then its fine.  the general rule of thumb is: 

your code: decoration
(inaccessible) library code: extension and/or hooks

There must me something wrong on your side here. These hooks do work and are used in production. The settings structure looks fine and the function itself is also ok. The only thing that might be broken is the import path of you function. otherwise this looks good.

Here is a shipped function that is used in both production and tests:

https://github.com/tfranzel/drf-spectacular/blob/812d3ffd39347241ea9ac38793d6801cc6b17136/drf_spectacular/hooks.py#L146-L156

**Comment by mamazu91** [comment]
> There must me something wrong on your side here.

I was able to figure it out this morning. So the first issue was that I was using `SPECTACULAR_DEFAULTS` instead of `SPECTACULAR_SETTINGS`, like you said. And the second one was that after I changed it to `SPECTACULAR_SETTINGS` it didn't work because I already had `SPECTACULAR_SETTINGS` declared down below the new one.

Thank you for your help!
