### ISSUE TITLE
@extend_schema is not working when used on generic API view method

### ISSUE THREAD

**Issue by Saymmic** [tfranzel/drf-spectacular#656]
**Describe the bug**
Extend schema decorator is not working when used on generic API View method.

**To Reproduce**
1. Create eg. ListAPIView from generics
2. Extend schema using decorator on `list` method

**Expected behavior**
Works fine when extended schema on `get`. I believe it should work on the `list` method too.

**Comment by tfranzel** [comment]
Hi @Saymmic,

this is as intended because only the actual DRF entrypoint is considered, which in this case is `get`. For `APIView`-based views `list` is wrapped syntactic sugar

https://drf-spectacular.readthedocs.io/en/latest/faq.html#using-extend-schema-on-apiview-has-no-effect

**Comment by Saymmic** [comment]
Okay. Sorry, I somehow missed this in the documentation. Thanks!
