### ISSUE TITLE
How do I convert my url

### ISSUE THREAD

**Issue by hanbinloop** [tfranzel/drf-spectacular#659]
^api/v1/tenant/(?P<parent_lookup_tenant>[^/.]+)/user/

covert

/api/v1/tenant/{parent_lookup_tenant}/user/

I need this function

![image](https://user-images.githubusercontent.com/16644654/154456459-fe5134fe-b6f4-42a3-8591-0bd1053ff9a2.png)

**Comment by tfranzel** [comment]
i don't understand your question. please be more specific

**Comment by hanbinloop** [comment]
^api/v1/tenant/(?P<parent_lookup_tenant>[^/.]+)/user/   to  /api/v1/tenant/{parent_lookup_tenant}/user/

**Comment by hanbinloop** [comment]
> i don't understand your question. please be more specific

^api/v1/tenant/(?P<parent_lookup_tenant>[^/.]+)/user/ to /api/v1/tenant/{parent_lookup_tenant}/user/

**Comment by hanbinloop** [comment]
I don't need to automatically convert, I need to convert an address myself

**Comment by tfranzel** [comment]
this is not how OpenAPI works. you cannot have regex in the path in OpenAPI. it would be invalid.

**Comment by hanbinloop** [comment]
> this is not how OpenAPI works. you cannot have regex in the path in OpenAPI. it would be invalid.

django url 本来是正则的，但是openapi却把正则去掉了，我想知道怎么去，我要重现这个过程。

**Comment by hanbinloop** [comment]
> this is not how OpenAPI works. you cannot have regex in the path in OpenAPI. it would be invalid.

Djangos URLS are regular, but OpenAPI has removed the re. I want to know how to do that, and I want to recreate the process.

**Comment by hanbinloop** [comment]
> this is not how OpenAPI works. you cannot have regex in the path in OpenAPI. it would be invalid.

![image](https://user-images.githubusercontent.com/16644654/154474291-ea5e293d-43e3-4923-9261-d83ef6675cf0.png)

**Comment by hanbinloop** [comment]
> this is not how OpenAPI works. you cannot have regex in the path in OpenAPI. it would be invalid.

![image](https://user-images.githubusercontent.com/16644654/154474349-22ecaba6-14b9-4f6f-bbb8-855bb50ef04d.png)

**Comment by tfranzel** [comment]
now i understand. the code is mainly in DRF but we do some improvements.

https://github.com/tfranzel/drf-spectacular/blob/0fff18a3e6b94e6a7f53d3f8a1f47d0b66b1f489/drf_spectacular/generators.py#L61

https://github.com/tfranzel/drf-spectacular/blob/0fff18a3e6b94e6a7f53d3f8a1f47d0b66b1f489/drf_spectacular/generators.py#L42-L46

**Comment by hanbinloop** [comment]
thank you.I see. That's it
