### ISSUE TITLE
AttributeError: 'ManualSchema' object has no attribute 'get_operation'

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#66]
Probably very ill-advised, I am testing https://github.com/and3rson/drfbro , and have some unrelated mods to get it semi-functional, and no `settings` related to it, but I am seeing the following when running dj admin command `spectacular. (i.e. not when using drfbro with spectacular)

`ManualSchema` is coming from django-rest-framework, rather than from drfbro itself.  I have not yet checked whether the use of `.schema` in their view is reasonable or not; if it isnt, maybe this is just a unfortunate conflict.  Ill dig more into it - just capturing the problem atm.

```py
Traceback (most recent call last):
  File "manage.py", line 46, in <module>
    main()
  File "manage.py", line 42, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 44, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/lib/python3.8/site-packages/drf_spectacular/generators.py", line 153, in get_schema
    paths=self.parse(request, public),
  File "/usr/lib/python3.8/site-packages/drf_spectacular/generators.py", line 133, in parse
    operation = view.schema.get_operation(path, path_regex, method, self.registry)
AttributeError: 'ManualSchema' object has no attribute 'get_operation'
```

**Comment by tfranzel** [comment]
unmaintained lib with last commit 3 years ago. `ManualSchema` comes from DRF coreapi which is deprecated and will soon be removed. Also `ManualSchema` is a `ViewInspector` which is in contradiction with our AutoSchema.

btw we have 2 views for UI: swagger and redoc. i don't see the need.

**Comment by tfranzel** [comment]
closing because this seems like a general lib conflict. would need more input on how to solve those issues in a generic way.

**Comment by KevinTurnbull** [comment]
I'm having the same problem. To me - it looks like this issue is because DRF isn't deferring to the schema from it's settings - potentially it might be a DRF bug. 

My includes of note are as follows: 

```'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'oauth2_provider',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_gis',
 'corsheaders',
 'drf_spectacular',
 'django.contrib.gis',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit```

**Comment by tfranzel** [comment]
hey @KevinTurnbull. i did a quick example wagtail project. the schema is generated successfully. 

have you set the `AutoSchema` in your `settings.py` as stated in the README?

```
REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
```

however the schema does not look very useful like that. it is likely similar to `oscar` where the lib writes the views in a way that is not automatically parse-able.  you may need to do some extensions to get mileage out of this. examples: https://drf-spectacular.readthedocs.io/en/latest/blueprints.html#django-oscar-api

generally have a look at https://drf-spectacular.readthedocs.io/en/latest/customization.html
