### ISSUE TITLE
How can I use it with generated yaml.

### ISSUE THREAD

**Issue by danilocubrovic** [tfranzel/drf-spectacular#662]
How can i set it up to use generated schema file instead of auto schema.
So after I generate schema with spectacular 
./manage.py spectacular --file schema.yml
I want to use it but need help how to configure in url patterns that this schema is used by swagger ...

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

Any pointers for that?

**Comment by tfranzel** [comment]
Hi,

there is no hard-coded schema serving. All endpoints generate the schema on-the-fly. If you want to serve a static pre-generated file, just write a basic view function and serve that file yourself. Why would you want to do this anyway?

**Comment by danilocubrovic** [comment]
api_view annotaion make our services unusable so i want to generate schema and disable api_view and use generated schema.
And to regenerate schema when needed.

How can I say SpectacularSwaggerView to use that view let call it  AppSchemaStaticView?
path('api/schemafile/', AppSchemaStaticView.as_view()),

???

**Comment by tfranzel** [comment]
I see, just refer `url_name` to your view (via route `name`)

```python
path('api/schema/', AppSchemaStaticView.as_view(), name='schema_static'),
# Optional UI:
path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema_static'), name='swagger-ui'),
path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema_static'), name='redoc'),
```

**Comment by danilocubrovic** [comment]
Thanks for help but somethings still missing.
Now all three endpoints just shows my schema.yml content.
Only thing that differs is that I use function based view to generate yaml.

path('api/schema/', util.schema_file, name='schema_static'),

path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema_static'), name='swagger-ui'),
path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema_static'), name='redoc'),


and

def schema_file(request):
    try:
        with open(BASE_DIR + '/schema.yml', 'rb') as f:
            return HttpResponse(f.read(), content_type="text/yaml")
    except IOError:
        raise Http404

**Comment by danilocubrovic** [comment]
Fixing it by inspecting current schema and setting  content type to
application/vnd.oai.openapi; charset=utf-8
Thank you very much. Moving to next challenges.
