### ISSUE TITLE
Callback/webhook schema generation

### ISSUE THREAD

**Issue by Jusstas** [tfranzel/drf-spectacular#665]
I want to document my callbacks/webhooks as shown in the [Petstore example](https://redocly.github.io/redoc/#operation/newPet). I am using serializers to serialize data and post it to some external URLs. Is there any way I can generate some of the schema required to achieve this? I know I can use postprocessing hooks to insert webhook callback operation, but I do not know how to get the schema from the serializer to use in it or if it is some better approach to this.

**Comment by tfranzel** [comment]
I see. This is in fact a missing feature and has not come up that often before. I'll have a look on how to integrate this.

In the meantime, postprocessing hooks can be a bit complicated but everything you need is indeed there. You have access to
`def custom_postprocessing_hook(result, generator, request, public)` where the complete schema is in `result` and all parsed serializer components are in `generator.registry._components`.

**Comment by tfranzel** [comment]
callback interface proposal in PR #666

**Comment by tfranzel** [comment]
closed by #666

**Comment by Jusstas** [comment]
Thank you ❤️

**Comment by CodeWithOz** [comment]
@Jusstas how did you structure your code so that the webhooks got picked up and included in the generated yaml file? I can't figure out how to do it. ☹️

**Comment by nitsujri** [comment]
@CodeWithOz how did you do the `webhook` part? I copied the test_callbacks.py + yml and it looks good for callbacks but did you get ti like the webhooks? 

I was hoping for this and maybe I'm doing something wrong?

<img width="827" alt="ReDoc_Interactive_Demo" src="https://user-images.githubusercontent.com/224840/237033970-70210f21-3d16-4632-9b7d-d727a87730a1.png">

**Comment by CodeWithOz** [comment]
<img width="598" alt="Screenshot 2023-05-09 at 10 41 34 AM" src="https://user-images.githubusercontent.com/28525986/237058413-d3ac4f8d-589b-4d2c-9978-af843ac180cd.png">

This is what I did and it worked. By the way I'm using readme.io to generate my API documentation so I can't comment on the tool you're using. @nitsujri

**Comment by tfranzel** [comment]
Looks like **webhook** and **callback** are not the same thing. **webhook** was added in OpenAPI 3.1 and is not available in 3.0.3 (which we produce). So we only have **callback** at the moment.

excerpt from the 3.1 spec:

> The incoming webhooks that MAY be received as part of this API and that the API consumer MAY choose to implement. Closely related to the callbacks feature, this section describes requests initiated other than by an API call, for [example](https://swagger.io/specification/examples/v3.1/webhook-example.yaml) by an out of band registration. The key name is a unique string to refer to each webhook, while the (optionally referenced) Path Item Object describes a request that may be initiated by the API provider and the expected responses. An example is available.`


Redoc reference:
https://redocly.com/docs/openapi-visual-reference/webhooks/
https://redocly.com/docs/openapi-visual-reference/callbacks/
