### ISSUE TITLE
Multiple header parameter on Swagger ui Authentication

### ISSUE THREAD

**Issue by nathanmrtns** [tfranzel/drf-spectacular#671]
Is it possible to use multiple header keys in the authorization schema?

I tried using [this example](https://github.com/tfranzel/drf-spectacular/commit/bbc6023a5a8903d2e7c2b28e7a53d1193a2fba59#diff-2155b115d700e8f39a57e254d9e5ab9825b17ca3d8ba5b6acf9b2654bba7f83eR130) coming from the issue #537 and when I run, the ui doesn't show anything inside the popup.

I wanted to set 2: an api key and another parameter like version

Here is my implementation:

```python
class MyAuthenticationScheme(OpenApiAuthenticationExtension):
    target_class = "mx.api.authentication.MySessionAuthentication"
    name = "Authentication"

    def get_security_definition(self, auto_schema):
        return [
            {"type": "apiKey", "in": "header", "name": "X-API-KEY"},
            {"type": "apiKey", "in": "cookie", "name": "Version"},
        ]
```

**Comment by tfranzel** [comment]
you only did a partial copy :smile: 

https://github.com/tfranzel/drf-spectacular/blob/d0dfdb4000fbce38e7694823c579212e476401ea/tests/test_extensions.py#L128-L134

makes this work. you specified a list of definitions, but you lack a **list of names** for those definitions.

**Comment by nathanmrtns** [comment]
> you only did a partial copy 😄
> 
> https://github.com/tfranzel/drf-spectacular/blob/d0dfdb4000fbce38e7694823c579212e476401ea/tests/test_extensions.py#L128-L134
> 
> makes this work. you specified a list of definitions, but you lack a **list of names** for those definitions.

ops 😝 Thanks, it worked.
