### ISSUE TITLE
AcceptHeaderVersioning, multiple versions on single endpoint, how to display this in the schema?

### ISSUE THREAD

**Issue by samwho** [tfranzel/drf-spectacular#672]
We use AcceptHeaderVersioning in order to have multiple versions of individual endpoints. We have created a helper class to make this easier to express:

```python
class VersionedAPIView(APIView):
    """
    This view allows you to define sub-views to dispatch to depending on what
    API version is in use.

    Example:

      class MyView(VersionedAPIView):
          versions = {
              "1": MyV1View,
              "2": MyV2View,
          }
    """

    versions: Dict[str, Type[APIView]] = {}

    def get_view_class(self) -> Optional[Type[APIView]]:
        return self.versions.get(self.request.version, None)

    def dispatch(self, request, *args, **kwargs):
        """
        The majority of this dispatch method mirrors the dispatch method on
        rest_framework.views.APIView, with the only modification being to
        look up the version number in the self.versions dict and dispatch to
        that.
        """
        self.args = args
        self.kwargs = kwargs
        self.request = self.initialize_request(request, *args, **kwargs)
        self.headers = self.default_response_headers

        try:
            self.initial(self.request, *args, **kwargs)

            view_class = self.get_view_class()
            if view_class is None:
                return self.finalize_response(
                    self.request, Response(status=404), *args, **kwargs
                )

            if not getattr(view_class, "as_view", None):
                raise ValueError(
                    "views passed in the versions dict of a VersionedAPIView must be have a method called .as_view()"
                )

            view = view_class.as_view()
            return view(request, *args, **kwargs)
        except Exception as exc:
            response = self.handle_exception(exc)

        self.response = self.finalize_response(self.request, response, *args, **kwargs)
        return self.response
```

Each sub-view is also an APIView, and can behave in whatever way it wants. What I'd love to be able to do is basically forward all of the schema generation to the sub-view depending on what the API version is, but I haven't found a way to do that.

I tried exposing our schema with a dynamic version parameter, e.g `?version=1` on the end of the URL, but no matter what I set the version to it always just returns the same set of endpoints. Even if I put `@extend_schema(versions=["1"])` or `@extend_schema(versions=["2"])` on some views, it doesn't appear to make a difference.
 
Here are the settings I've tried:

```
SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_SETTINGS": """{
        deepLinking: true,
        displayOperationId: true,
        persistAuthorization: true,
        urls: [
            {url: "/openapi/?version=1", name: "v1 endpoints"},
            {url: "/openapi/?version=2", name: "v2 endpoints"},
        ],
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
    }""",
}
```

The end result that I want is that it's possible to select between v1, v2, v3, and on each page _only_ endpoints that have an option for that version are shown. Is this possible? As it stands, nothing I do trims down the number of endpoints depending on version. I've tried `@extend_schema(versions=["2"])` on some of my views but that doesn't appear to do anything.

**Comment by tfranzel** [comment]
Hi @samwho,

so from what I have gathered is that you have built your own versioning mechanism. Spectacular cannot be aware of your custom mechanics. Your views appear to be regular views that internally handle dynamically build views. 

We achieve versioning by looking out for the `versioning_class` attribute on the view class. If that is the default `None`, we treat the view as unversioned. I guess you have to somehow expose what you are doing to the DRF interface. For AcceptHeaderVersioning you would need to provide the view's `versioning_class` with `rest_framework.versioning.AcceptHeaderVersioning`. 

Sidenote: I believe your versioned views are hidden behind the container view and `urlpatterns` is not aware of those hidden views. When we parse all available API views in `urlpatterns`, we can only parse what we see.

**Comment by tfranzel** [comment]
versioning is determined here: 

https://github.com/tfranzel/drf-spectacular/blob/0fff18a3e6b94e6a7f53d3f8a1f47d0b66b1f489/drf_spectacular/generators.py#L216

**Comment by samwho** [comment]
Thank you for the extremely quick response!

I'm using AcceptHeaderVersioning as my DEFAULT_VERSIONING_CLASS in DRF. So I believe we're not using a custom versioning scheme, we're just handling the dispatching to specific version code in a custom way.

I don't believe it's possible to expose two views on one URL, is it? If it is, I'd be extremely keen to know how.

If I were using AcceptHeaderVersioning and then an "if" statement on request.version inside my view, and using a different serializer depending on version, what's the expected way drf-spectacular would be able to handle that?

**Comment by tfranzel** [comment]
> I'm using AcceptHeaderVersioning as my DEFAULT_VERSIONING_CLASS in DRF. So I believe we're not using a custom versioning scheme, we're just handling the dispatching to specific version code in a custom way.

Then I suppose we (spectacular) only see the default view returned by your logic and we never encounter the other (versioned) views (decorators included) that you dynamically generate. That would be my educated guess.

> I don't believe it's possible to expose two views on one URL, is it? If it is, I'd be extremely keen to know how.

I don't think there is an easy way to do this. certainly hackable but your mileage may vary.

> If I were using AcceptHeaderVersioning and then an "if" statement on request.version inside my view, and using a different serializer depending on version, what's the expected way drf-spectacular would be able to handle that?

yes, afaik that is the way DRF is telling you how to handle versioning. This approach certainly has limitations, but it is what it is. We can only use what the DRF interface gives us.

**Comment by samwho** [comment]
> yes, afaik that is the way DRF is telling you how to handle versioning. This approach certainly has limitations, but it is what it is. We can only use what the DRF interface gives us.

If I were doing that, and each version used different response serialisers, how would I expose that fact in the OpenAPI schema? At the moment I don't see a way to do that. I sort of expected the `versions` parameter of `@extend_schema` to be involved but regardless what I do, that parameter doesn't seem to do anything.

**Comment by samwho** [comment]
Had a small realisation.

With path based versioning, each endpoint has a definite version that can be determined in the URL of the endpoint.

With header based versioning, the version of an endpoint depends on the headers in the request. 

With path based versioning, every endpoint serves just one version of itself.

With header based versioning, a theoretically infinite number of versions could be hiding behind one URL.

Is this why, when I try to set ?version=2, it doesn't appear to have any affect on the schema? Because all of my endpoints technically could serve a version 2, because of how header based versioning works?

Would there be some overriding I could do to reach in and look at the view behind each endpoint to determine if I know it has a v2 or not based on my custom dispatching code in the initial bug?

**Comment by tfranzel** [comment]
- when doing`@extend_schema(versions=...)`, `versions` is a scope. the decorator is only applied if the requested version is in the list. this requires the `AcceptHeaderVersioning` (or other versioning) to be present.

- the expected mechanics are like so:

```python
    class X2Viewset(mixins.ListModelMixin, viewsets.GenericViewSet):
        ....
        def get_serializer_class(self):
            if self.request.version == 'v2':
               return V2Serializer
           else:
               return V1Serializer # default
```

- when `request_serializer==response_serializer`, spectacular already takes care of this. otherwise you need the `extend_schema(versions=...)`

**Comment by tfranzel** [comment]
> With path based versioning, every endpoint serves just one version of itself.

not necessarily. the path version might be a variable: `re_path(r'^api/pv/(?P<version>[v1|v2]+)/', include(urlpatterns_path)),`

> Is this why, when I try to set ?version=2, it doesn't appear to have any affect on the schema? 

no. this works for path/header/namespace versioning. this works and is fully covered in the tests. However we 100% rely on what the versioning class determined as the version for this request. If the `versioning_class` detected `v2` then the `extend_schema(versions=['v2'])` would take effect. 

On schema generation, we create a mock request. When you request a `v2` schema from the generator, the mock request will take that into account and inject the headers that the versioning_class was configured to use.

my guess is something is still creating problems in your dispatching. When you correctly make DRF aware of the version, spectacular will pick it up. You can test this in your view when you check `self.request.version`. This is what we rely on.

**Comment by samwho** [comment]
That's super helpful and I think has helped me figure out what I need to do!

I think I need to override determine_version and make sure to raise a rest_framework.exceptions.NotAcceptable if the view itself cannot serve the version requested. This makes the endpoint disappear from the schema depending on the ?version= param!

Thank you so much for your patience with me. I think we can mark this as resolved now.
