### ISSUE TITLE
Output version into schema for subclasses of AcceptHeaderVersioning

### ISSUE THREAD

**Issue by samwho** [tfranzel/drf-spectacular#673]
In https://github.com/tfranzel/drf-spectacular/commit/61cf160a3685f5c5bd67cabc25c41084d373a32f support was added to output the version part of the Accept header into the schema, but only if the versioning class is AcceptHeaderVersioning. I think this check should instead look for subclasses of AcceptHeaderVersioning, like the check in `modify_for_versioning`. We use a subclass of AcceptHeaderVersioning in our Django projects, so we get no `version=X` header when we use the `Try it Out` feature on the Swagger UI.

**Comment by tfranzel** [comment]
this has been fixed in https://github.com/tfranzel/drf-spectacular/commit/b535caac7bbf9f0bc39965f581bc6787f066d897 

it's on master and not yet released.

**Comment by samwho** [comment]
<3

Is there an ETA on the next release that would contain this fix?

**Comment by tfranzel** [comment]
probably some time next week. I want to look at another issue before doing a y-stream release.

**Comment by samwho** [comment]
Awesome, thanks so much again.
