### ISSUE TITLE
Callback schema with read-only/write-only fields

### ISSUE THREAD

**Issue by Jusstas** [tfranzel/drf-spectacular#680]
I think the generated schema is not desired when using callbacks with serializers containing read-only/write-only fields and having the `COMPONENT_SPLIT_REQUEST` setting set to `True`.

For example, we have a test serializer:
``` Python
class TestSerializer(serializers.Serializer):
    test_field = serializers.CharField()
    test_readonly_field = serializers.CharField(read_only=True)
    test_writeonly_field = serializers.CharField(write_only=True)
```
We extend callbacks schema using test serializer from above:
``` Python
@extend_schema(
    callbacks=[
        OpenApiCallback(
            'test_callback',
            'test/path/',
            extend_schema(request=TestSerializer, responses=TestSerializer),
        )
    ]
)
@api_view(['POST'])
def test(request):
    return Response()
```
Then the generated schema is:
``` YAML
openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /test/:
    post:
      operationId: test_create
      tags:
      - test
      responses:
        '200':
          description: No response body
      callbacks:
        test_callback:
          test/path/:
            post:
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/TestRequest'
                required: true
              responses:
                '200':
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Test'
                  description: ''
components:
  schemas:
    Test:
      type: object
      properties:
        test_field:
          type: string
        test_readonly_field:
          type: string
          readOnly: true
      required:
      - test_field
      - test_readonly_field
    TestRequest:
      type: object
      properties:
        test_field:
          type: string
          minLength: 1
        test_writeonly_field:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - test_field
      - test_writeonly_field
```
The current behavior is: on the request body we have write-only fields and on responses, we have read-only fields because that's how normal operation schema works, but for callbacks, it does not make sense.

I think desired behavior for callbacks should be: the request body contains read-only fields and responses have write-only fields.

**Comment by tfranzel** [comment]
> having the COMPONENT_SPLIT_REQUEST setting set to True

I don't think this makes a difference here. It behaves the same with or without.

> I think desired behavior for callbacks should be: the request body contains read-only fields and responses have write-only fields.

It is a bit confusing but I disagree. There not much explanation in the OpenAPI specification but SwaggerUI displays the callbacks as I would assume. I tested this without `COMPONENT_SPLIT_REQUEST` so SwaggerUI can choose itself what to display.

callback request (from us to them): SwaggerUI only shows `RW` and `writeOnly` fields

callback response (from them to us): SwaggerUI only shows `RW` and ``readOnly`` fields

So SwaggerUI is understanding this as I did when implementing it. It helped me to think about request/response from the **opposite side** as we are now the client in the callback scenario.

**Comment by Jusstas** [comment]
How about this example:
Django model's default `id` field is read-only. We are using `ModelSerializer` to generate callback's request/response bodies. It makes sense to send the read-only `id` field to the external API and do not accept that field from them, because it is read-only on our side.

**Comment by tfranzel** [comment]
>  It makes sense to send the read-only id field to the external API and do not accept that field from them, because it is read-only on our side.

absolutely, which makes it a `writeOnly` field. That is a write operation from server to callback recipient. The server, while doing a callback, will only write out that `id` field and will not accept and process that field when the callback response is received.

At least that is the terminology and "perspective" the OpenAPI people apparently decided on. :shrug: 

**However**, I believe I do get your point now. That serializer would be the wrong way round:

```python
class EventSerializer(serializers.Serializer):
    id = serializers.CharField(write_only=True)
    ack = serializers.CharField(read_only=True)

callback_outgoing = EventSerializer(instance={'id': 'someid'}).data  # bad result: {}
callback_incoming_ser = EventSerializer(data={'ack': True})
callback_incoming_ser.is_valid()
callback_incoming = callback_incoming_ser.data  # bad result: {} 
```

One could flip `read_only`/`write_only` AND `data=`/`instance=` for those dedicated callback serializers, but they would not really be usable as validation only runs on inbound `data`. 

Damn! Ok so this does not really work like that. The question is what to do now? This was a rather light feature because I was able to reuse almost all of spectacular's `extend_schema` mechanics. I'm not really up for rewriting half of the codebase to accommodate this feature :disappointed: Maybe there is non-invasive way of flipping the serializer but I'm not sure yet.
