### ISSUE TITLE
`externalDocs` for operation schema

### ISSUE THREAD

**Issue by Jusstas** [tfranzel/drf-spectacular#681]
I have missed the `externalDocs` field for the operation object. Is there any intended way I can add this for my views? If not, I think there should be an `external_docs`  argument in the `extend_scema` (and `extend_schema_serializer` I guess?) decorator for this purpose.

**Comment by Jusstas** [comment]
As I understand, the `EXTERNAL_DOCS` setting is only for the root [OpenAPI object](https://swagger.io/specification/#openapi-object), but there are also `externalDocs` fields for [operation](https://swagger.io/specification/#operation-object) and [schema](https://swagger.io/specification/#schema-object) objects.

**Comment by tfranzel** [comment]
Excellent point! Sry, I missed that you were referring to the operation.

Should be doable, however not sure yet where exactly it is the best fit. operation or schema objects.

**Comment by tfranzel** [comment]
That should do it. It is only for the operation for now. Let's wait if someone will ask for the schema object.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
