### ISSUE TITLE
Setting format on Schema

### ISSUE THREAD

**Issue by chgad** [tfranzel/drf-spectacular#683]
Hello,

as of the spec [here](https://spec.openapis.org/oas/v3.0.3#properties) it is allowed to set a `format` on a schema.

Well, how can i set it on a Serializer/Schema ?

**Comment by tfranzel** [comment]
Hi,

by choosing the correct serializer fields, the `format` property gets filled automagically with the right value. If you want a different format than generated, you will likely need provide in raw form via decorators.

**Comment by tfranzel** [comment]
I see. I have no idea what `format` is supposed to mean in the context of an `object`. The spec does not explicitly forbid it, but at least SwaggerUI completely ignores it. I would bet code generators too. 

https://spec.openapis.org/oas/v3.0.3#dataTypeFormat only mentions primitives and that is how we use it. 

What is it you are trying to achieve with this? I'm quite confident you are "holding it wrong".

**Comment by chgad** [comment]
We are building a frontend component based on this Schema which is only used through reference in another Schema.

To paint the Picture suppose a "main" schema A:

    A:
        type: object
        properties: {
             b:
                $ref: '#/components/schemas/B'
             c:
                $ref: '#/components/schemas/C'

So now... we need a way to tell our Frontend to build B in a different way than C. You can imagine it like "Populate a Navbar from B" and "Build a dropdown form C".
This has to work without the Frontend knowing how exactly those Schemes are named.

That's where I came up with the `format` for an object. We could just say for instance `format: navbar` and `format: dropdown` and check the `format` keyword in our Schema parser in the Frontend.

**Comment by tfranzel** [comment]
I see. Don't do that in `format`. It may unexpectedly stop working when tooling changes. For this exact purpose there are vendor extensions: https://spec.openapis.org/oas/v3.0.3#specification-extensions


https://github.com/tfranzel/drf-spectacular/blob/66086cf2d18ca007224a79269efdfa74f1a035e1/tests/test_specification_extensions.py#L115-L118

your can do what you want there as long as it starts with `x-`

**Comment by chgad** [comment]
Ooooooooooh now i get the "extensions" part too!

And by using
    @extend_schema_serializer(extensions={'x-build-as: "nacbar"})

i can provide what i want? That would be a lot cleaner.

**Comment by tfranzel** [comment]
yes anything that can be serialized into json or yaml. its a dict so multiple key are also possible as long as the keys start with `x-`

fyi those are OpenAPI vendor extensions which are simply tacked onto the schema as is. Don't confuse them with [Spectacular extensions](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions), which modify how the schema is generated.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
