### ISSUE TITLE
Declare list of serialized data in `extend_schema` -> `Response`

### ISSUE THREAD

**Issue by kmehran1106** [tfranzel/drf-spectacular#691]
Hi! I've been using this for documenting my DRF APIs, and this has been a really enjoyable experience.

I was trying to define in my `extend_schema` that the API returns a list of serialized objects. Now I can declare the serializer and see the required fields, but I couldn't find any way to state that this API will be returning a list of objects. Is there any way to achieve this?

**Comment by tfranzel** [comment]
Hi @kmehran1106, glad to hear that.

Of course! There are multiple ways to influence "list" detection, but the most basic example would be for example

```python
@extend_schema(
    request=ASerializer(many=True),
    responses=ASerializer(many=True)
)
def get(self, request):
   ...
```

**Comment by kmehran1106** [comment]
@tfranzel thanks a lot for the quick response! Closing the issue.
