### ISSUE TITLE
Support request parameter in ApiView

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#7]
When I used `swagger_auto_schema` I was getting a schema with request parameters like this
```python
from rest_framework.views import APIView


class RequestSerializer(serializers.Serializer):
    device_uuid = UUIDField()
    email = EmailField()

class MyView(views.APIView):
    renderer_classes = [JSONRenderer]

    @swagger_auto_schema(
        request_body=RequestSerializer,
        responses={'200': empty_response}, # None
    )
    def post(self, request, *args, **kwargs):
        serializer = RequestSerializer(data=request.data)
        ...
        return Response()
```
And in swagger it looks like this
![image](https://user-images.githubusercontent.com/6458407/76506333-13ca1100-645c-11ea-82c8-e2c7c61fc07d.png)

When i try to use extend_schema it is not working
```python
class MyView(views.APIView):
    renderer_classes = [EnvelopedJSONRenderer]

    @extend_schema(
        request=RequestSerializer,
        responses={200: None},
    )
    def post(self, request, *args, **kwargs):
        serializer = RequestSerializer(data=request.data)
        ...
        return Response()
```
I got empty body
![image](https://user-images.githubusercontent.com/6458407/76506927-fcd7ee80-645c-11ea-8ba6-743d8dec7cff.png)

How can I also do as I did before?

**Comment by tfranzel-cashlink** [comment]
i think this is just a swagger-ui thing. maybe different swagger-ui version or it looks a bit different for OpenAPI2 and 3.
the parameter section is for ``query, header, path`` parameters. in fact, the request body is displayed below, just without the "request body" section header.

see ``./helper/swagger-ui.sh tests/test_extend_schema.ym`` as example

**Comment by tfranzel-cashlink** [comment]
as far as the schema is concerned, i think it is generated correctly here

**Comment by MissiaL** [comment]
The last example with a picture is an error. I meant that there is no `data` parameter 
How I can add `data` parameter?

**Comment by MissiaL** [comment]
I see something like this solution to the problem

```python
    class DoesItAllViewset(viewsets.GenericViewSet):
        serializer_class = AlphaSerializer

        @extend_schema(
            operation_id='customname_create',
            request=AlphaSerializer,
            responses={
                201: BetaSerializer(many=True),
                200: GammaSerializer,
                500: ErrorSerializer,
            },
                ExtraParameter('data', AlphaSerializer, location=ExtraParameter.BODY, description='creation will be in the sandbox'),
            ],
            description='this weird endpoint needs some explaining',
            deprecated=True,
            tags=['custom_tag'],
        )
        def create(self, request, *args, **kwargs):
            return Response({})

        @extend_schema(operation={})
        def list(self, request, *args, **kwargs):
            return Response([])
```

**Comment by MissiaL** [comment]
Maybe I'm still wrong. Let me think

**Comment by MissiaL** [comment]
Oh, I was wrong. Everything works as it should. You were right
