### ISSUE TITLE
Enable oneOf on nested schema

### ISSUE THREAD

**Issue by rui-lomba** [tfranzel/drf-spectacular#701]
I am trying to use PolymorphicProxySerializer on a nested schema field with annotation `@extend_schema_field` but it is not working, I can use it just fine as an entry level of the endpoint however it is not possible on nested component.
Is this a bug or is this not implemented?

Thank you!

**Comment by tfranzel** [comment]
> I can use it just fine as an entry level of the endpoint however it is not possible on nested component

can you elaborate what not possible means? error/stacktrace/warning?

In theory it should be possible. I believe it is even covered by some test somewhere but I could be wrong. Just to clarify, `PolymorphicProxySerializer` is only allowed as part of an annotation and not as "real" serializer serving real requests.

**Comment by rui-lomba** [comment]
Hello @tfranzel and thank you for quick response.

I had a look at the unit tests and now I understand that I was not using the `PolymorphicProxySerializer` properly.
However I quickly gave up trying and opened the ticket because I was afraid that it was not supported since on the [documentation](https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html?highlight=PolymorphicProxySerializer#drf_spectacular.utils.PolymorphicProxySerializer) it only mentions that this is used on `@extend_schema`.
Maybe mentioning that we can also use it with `@extend_schema_field` and also add an example, would be helpful!

I will close this ticket.
Thank you for help
