### ISSUE TITLE
OpenApiSerializerFieldExtension for drf-extra-fields PresentablePrimaryKeyRelatedField

### ISSUE THREAD

**Issue by tspanos** [tfranzel/drf-spectacular#707]
I wrote an OpenApiSerializerFieldExtension to correct the generated schema for PresentablePrimaryKeyRelatedField in the drf-extra-field package. The purpose of the PresentablePrimaryKeyRelatedField is to accept foreign keys on requests and use nested seriazliers in responses. 

The issue I ran into was that my customization not only applied to the GET method, but to also the POST and PUT methods on the ModelViewSet. The PATCH method received the correct result. The custom `map_serializer_field` method would run twice. Once with the `direction` set to "response" and `auto_schema.method` set to "GET", and again with the `direction` set to "request" and `auto_schema.method` set to "PATCH". 

I eventually fixed the issue by changing the setting `COMPONENT_SPLIT_REQUEST` to True. This allowed `map_serializer_field` to correct the response result three times, once for GET, once for POST and once for PATCH. 

drf-spectacular has a blue print for drf-extra-field Base64FileField. Is this worth creating a PR and adding PresentablePrimaryKeyRelatedField to the drf-extra-field blueprints? My solution won't work unless `COMPONENT_SPLIT_REQUEST` is set to True so I'm not sure how useful it is. Also, if there is a cleaner way to handle this, I'd love to know.

```
class FixPresentablePrimaryKeyRelatedField(OpenApiSerializerFieldExtension):
    target_class = PresentablePrimaryKeyRelatedField

    def map_serializer_field(self, auto_schema, direction):
        if direction == "response":
            return auto_schema._map_serializer_field(self.target.presentation_serializer, direction,
                                                     bypass_extensions=True)
        else:
            return auto_schema._map_serializer_field(self.target, direction, bypass_extensions=True)

```

**Comment by tfranzel** [comment]
Hi @tspanos,

I'm not familiar with all of `drf-extra-fields`, but it it behaves differently on request and response this would be the way to do it. You could do 

```python
from drf_spectacular.settings import spectacular_settings

...

if direction == ''response" and spectacular_settings.COMPONENT_SPLIT_REQUEST`:
```

to account for that. A PR for the blueprint is welcome in any case. It can't hurt and might help others.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by tomashchuk** [comment]
Thanks, @tspanos @tfranzel for this blueprint. It helped me
