### ISSUE TITLE
Using a list for SERVE_URLCONF parameter inside SPECTACULAR_SETTINGS

### ISSUE THREAD

**Issue by anoirak** [tfranzel/drf-spectacular#709]
**Describe the bug**
When using a tuple or a list for SERVE_URLCONF parameter , an error is raised : `AttributeError: 'str' object has no attribute 'pattern'`

**To Reproduce**
```
SPECTACULAR_SETTINGS = {
    'SERVE_URLCONF':  ("app1.urls", "app2.urls"),
}
```
**Expected behavior**
It should include only those urls in the generated schema. 
When using a String variable instead of a list , all is working well.
```
SPECTACULAR_SETTINGS = {
    'SERVE_URLCONF':  "app1.urls",
}
```

**Comment by tfranzel** [comment]
closed by #711
