### ISSUE TITLE
Get versioned schema ui

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#71]
I have several versioned schemas. How can I get schema-ui views for each version?

**Comment by tfranzel** [comment]
that is i think the only thing that the tests do not explicitly cover. congratulations on finding the hole 😄 

it should be possible though. the ``SpectacularAPIView`` honors the same versioning as the regular views (based on the request and the default versioning class). have you tested this?

```
urlpatterns = [
    re_path(r'^(?P<version>[v1|v2]+)/schema', SpectacularAPIView.as_view(), name='schema')),
    re_path(r'^(?P<version>[v1|v2]+)/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'))
]
```

otherwise you could always do it explicitly with 

```
path('api/v2/schema/', SpectacularAPIView.as_view(api_version='v2'), name='schema_v2'),
path('api/v2/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema_v2'))
```

i believe the first one works. the second definitely works.

**Comment by tfranzel** [comment]
correction. the first one cannot work. its needs to be explicit as in the second example i'm afraid. at least currently.

**Comment by MissiaL** [comment]
Yes. You right
But I think we can update base template, which will proxifying request version
@tsouvarev What do you think about it?

**Comment by tsouvarev** [comment]
What if we move reverse of URL for scheme to view from template? It will allow you to add version to args of reverse easily via subclassing. Template will stay the same for versioned and unversioned schemes.

**Comment by tfranzel** [comment]
i think its a reasonable addition to make that work. the idea for implementation does go in the right direction. on first glace i saw that the ``TemplateView`` is coming from Django, which means there are no DRF versioning mechanics present. its true that the template is agnostic of the versioning, but the enclosing view has to deal with that fact. so this might have to be solved differently. would have to investigate further.

**Comment by tfranzel** [comment]
that should do it. was easier than expected. could have been even easier without that DRF "bug".

I discovered that DRF has its own `reverse()` that honors versioning. unfortunately, DRF's ``TemplateHTMLRenderer`` does not use it though. :confused: had to call it explicitly.

that should fix this for all supported versioning types. close the issue if it works as expected.

**Comment by tfranzel** [comment]
@MissiaL could you check if that works for you?

**Comment by MissiaL** [comment]
Yes. I will check

**Comment by MissiaL** [comment]
It works! Thanks!
