### ISSUE TITLE
Support for x-displayName

### ISSUE THREAD

**Issue by pkariz** [tfranzel/drf-spectacular#710]
I can't find a way to make `x-displayName` extension work. I've tried doing:
```py
@extend_schema(
    tags=['x'],
    extensions={
        'x-displayName': 'y',
    },
)
```
but it puts `x-displayName` at the top (same level as `tags`) like this:
```
tags:
  - x
x-displayName: y
```
when it should be nested inside tags, like this:
```
tags:
  - name: x
    x-displayName: y
```
Is there a way to use this extension today and if not, can we expect this feature in the future? Thanks!

**Comment by tfranzel** [comment]
extensions on `@extend_schema` go into the operation as designed.  Using that argument also for tags there would be a functional collision.

You would likely need to pre-define tags in the settings to achieve this. 

```python
SPECTACULAR_SETTINGS = {
    ....
    "TAGS" [
        {"name": "x", "x-displayName": "y"},
        ....
    ]
```

and then just use `@extend_schema(tags=['x'],...)`

**Comment by pkariz** [comment]
Thanks for the answer, this does indeed solve my problem so i'm closing the issue :+1:
