### ISSUE TITLE
multiple endpoint sets

### ISSUE THREAD

**Issue by alexgustafson** [tfranzel/drf-spectacular#717]
I am trying to move from drf_yasg to drf_spectacular. 

I have a very complex app with multiple endpoints "areas" based on use and client types. There is a "members" area, a "partner" area, and an "administration" area. with drf_yasg I could "place" multiple schemas behind various endpoints. 

- /partner/api/schema/  has endpoints for partners
- /manager/api/schema/ has endpoints for managers

drf_spectacular seems too eager. If I load it behind the /partner/ url it will scan for serializers and routers in other apps. 

I also get a NoReverseMatch error that no reverse for 'schema' is found, indicating that drf_spectacular expects to be loaded in the root url pattern.

Is there a configuration that allows me to have multiple drf_spectacular schemas that are limited to only those routes at that endpoint?

**Comment by tfranzel** [comment]
> I also get a NoReverseMatch error that no reverse for 'schema' is found, indicating that drf_spectacular expects to be loaded in the root url pattern.

not exactly sure what you mean by that, but spectular does not need to run on all endpoints.

> drf_spectacular seems too eager. If I load it behind the /partner/ url it will scan for serializers and routers in other apps.

thats a good thing, right? :smile: no matter where you mount the `SpectacularAPIView`, it will by default use the root urlconf. 

> Is there a configuration that allows me to have multiple drf_spectacular schemas that are limited to only those routes at that endpoint?

You can influence what sub-section of your schema is exposed by `SpectacularAPIView`. There is a setting for that too, but you need multiple values so it need to be set on each schema endpoint individually:

```python
path('manager/api/schema/', SpectacularAPIView.as_view(urlconf='manager.urls'), name='schema_manager'),
path('manager/api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema_manager'), name='swagger_ui_manager'),

path('partner/api/schema/ ', SpectacularAPIView.as_view(urlconf='partner.urls'), name='schema_partner'),
path('partner/api/schema/swagger ', SpectacularSwaggerView.as_view(url_name='schema_partner'), name='swagger_ui_partner'),
```

that assumes your have django apps called `partner` and `manager`. `urlconf` can be

* actual list of `path()` objects (simulating urlpatterns)
* string importable path which must contains `urlpatterns` 
* same as above as a list of strings of import paths
