### ISSUE TITLE
DEFAULT_METADATA_CLASS

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#72]
The DRF default for DEFAULT_METADATA_CLASS is documented at https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/metadata.md .  The `OPTIONS` action allows any type of response, but I guess the content-type should be negotiated.  It seems reasonable that drf-spectacular would provide an OpenAPI provider for this.

Or, perhaps find some metadata interchange mechanism with https://github.com/drf-forms/drf-schema-adapter for them to expose/maintain it as part of larger effort.  If you dont like the idea of providing a `DEFAULT_METADATA_CLASS` here, I will create an issue there pointing back here recommending they use this as the basis of their openapi adapter.

**Comment by jayvdb** [comment]
Note I ran into one oddity with DRF's metadata
https://gitlab.com/thelabnyc/django-oscar/django-oscar-bundles/-/issues/4 , where it isnt including `GET` in metadata yet it serves a `GET` response.

**Comment by tfranzel** [comment]
that looks interesting. never used the OPTIONS myself.  though i'm not quite sure how the response should look like (partially due to the components). the result would have to somehow adhere to the OpenAPI 3 specification. at the end of the day that is the focus of spectacular.

**Comment by jayvdb** [comment]
The Metadata provider here would be the OpenAPI 3 equivalent of
https://github.com/django-json-api/django-rest-framework-json-api/blob/9d42d9b/rest_framework_json_api/metadata.py

I guess it would be a subset relevant for the URL.

Also note there is a different response for `OPTIONS` on the API root. c.f. https://github.com/drf-forms/drf-schema-adapter/blob/master/drf_auto_endpoint/metadata.py#L53

**Comment by tfranzel** [comment]
there has been no progress here. currently i also don't see the benefits given the severity and amount of changes it would require. closing this for now.
