### ISSUE TITLE
How do I specify a file request-body parameter?

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#720]
I have an POST endpoint that expects a string field, an integer field and a file field (ie, a file should be uploaded). The string and integer fields are not a problem. However, I can't figure out how to define a file field and have the SwaggerUI provide an Upload File functionality.

Here is what I've got so far. The `@extend_schema` below just results in a textbox where I can provide a string for the `file_field` in SwaggerUI. However, that doesn't work even if I provide a path to a file. Ideally, I'd like SwaggerUI to provide an Upload File functionality and for the files sent with the POST request to contain the `file_field` with its name and data. 

Is this possible with drf-spectacular? How do I do it? Thanks!

```py
  @extend_schema(
    request=inline_serializer(
        name="InlineFormSerializer",
        fields={
            "str_field": serializers.CharField(),
            "int_field": serializers.IntegerField(),
            "file_field": serializers.FileField(),
        },
    ),
  )
  def create(self, request, *args, **kwargs):
```

I took a look at https://github.com/tfranzel/drf-spectacular/issues/476, but with that approach, I'm unclear how to also incorporate the `str_field` and `int_field` alongside the `file_field`. Also, I believe I need the name `file_field` to be used.

**Comment by bluelight773** [comment]
I think I figured it out. I used the following value for `request`:
```py
        request={
            "multipart/form-data": {
                "type": "object",
                "properties": {
                    "str_field": {"type": "string"},
                    "int_field": {"type": "int"},
                    "file_field": {"type": "string", "format": "binary"}},
            },
        },
```

If possible, I'd like all those fields to be required and to not allow sending an empty value in SwaggerUI. Is that possible?
Trying to set `"required": True` didn't seem to work.

However, the main issue of providing a file is solved.

**Comment by bluelight773** [comment]
I tried the suggested approach and set `parser_classes` as suggested.
```py
  @extend_schema(
    request=inline_serializer(
        name="InlineFormSerializer",
        fields={
            "str_field": serializers.CharField(),
            "int_field": serializers.IntegerField(),
            "file_field": serializers.FileField(),
        },
    ),
  )
  def create(self, request, *args, **kwargs):
```

This does make all the fields required. However, the `file_field` shows up as `string($uri)` in SwaggerUI and there's no upload file button. Also, even if I provide a local path to a file, that doesn't work. Is there a way to define an upload-file field in an `inline_serializer`?

**Comment by tfranzel** [comment]
`FileField`s are asymmetric and cannot be represented by one OpenAPI component alone. By default it will be simplified and shown as string. For those cases we have the setting `'COMPONENT_SPLIT_REQUEST': True`, which allows for better representation of components at the cost of increased number of components (request/response pairs). Then its a `binary` on request, and a `str` on response!


> This does make all the fields required. 

that is what DRF expects, isn't it? Can't you just do `"int_field": serializers.IntegerField(required=False),` where needed?

**Comment by bluelight773** [comment]
It worked! The missing piece was `'COMPONENT_SPLIT_REQUEST': True`.  

The other two pieces were as you'd suggested setting `parser_classes = [parsers.MultiPartParser]` and using the following:
```py
  @extend_schema(
    request=inline_serializer(
        name="InlineFormSerializer",
        fields={
            "str_field": serializers.CharField(),
            "int_field": serializers.IntegerField(),
            "file_field": serializers.FileField(),
        },
    ),
  )
  def create(self, request, *args, **kwargs):
```

Thanks!

**Comment by Mr3rf1** [comment]
@bluelight773 How can i add a value to serializers.CharField()?
i mean how can i customize response (sth like below):

responses={
            200: inline_serializer(name="OK", fields={"success": serializers.BooleanField(default=True),
                                                      "message": serializers.CharField()}),
            400: inline_serializer(name="NOK", fields={"success": serializers.BooleanField(),
                                                       "message": serializers.CharField()}),
            401: inline_serializer(name="NOK", fields={"success": serializers.BooleanField(),
                                                       "message": serializers.CharField()}),
        }
        
        how can i set a value for each of status codes?
