### ISSUE TITLE
Specifying a response leads to undesired parameters added automatically

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#723]
The following code works as expected whereby I end up with only a "some_id" parameter showing up in SwaggerUI for the endpoint.
```py
    @extend_schema(
        description="Lists items",
        parameters=[
            OpenApiParameter(
                "some_id",
                required=True,
            ),
        ],
    )
    def list(self, request):
```

However, if I want to specify any type of minimal documentation for the response, such as the following, automatically a `page` and a `search` parameter are added. Is it possible to somehow prevent/disable those automatically added parameters (`page` and/or `search`) while still providing documentation for a response?
```py
    @extend_schema(
        description="Lists items",
        parameters=[
            OpenApiParameter(
                "id",
                required=True,
            ),
        ],
        responses={
            200: OpenApiResponse(description="Results"),
        },
    )
    def list(self, request):
```

**Comment by tfranzel** [comment]
closed for #720

**Comment by bluelight773** [comment]
I should clarify that there may be 2 separate issues here:
1. That, for some reason, providing a `response` (even if just a description) leads to some parameters to be automatically picked up that aren't otherwise. I'm guessing this behavior doesn't make sense.
2. Is it possible to "delete" automatically picked-up query parameters? As far as I can tell, we can override query parameters (eg, to provide a different description), but we can't delete them.

**Comment by tfranzel** [comment]
1. yes, that sounds like an unintended effect and thus likely a bug. I will look into it.

2. Yes that is possible. parameters behave much like class method overrides. just use the discovered name and set `OpenApiParameter('YOURNAME', exclude=True)`, which will nullify a previous parameter detection.

**Comment by bluelight773** [comment]
Thanks!
________________________________

**Comment by tfranzel** [comment]
Closing this as I cannot reproduce the issue mentioned in point 1. 

`page` paramter suggests pagination is used. both `@extend_schema()` snippets properly show the pagination parameter. The only difference is the response, which got disabled by `OpenApiResponse(description="Results")` due to the implicit `responses=None` that this entails. From my perspective this all behaves as expected.  If you disagree, please provide a reproduction so we can argue about the details.
