### ISSUE TITLE
Turn off database query

### ISSUE THREAD

**Issue by piotrj353** [tfranzel/drf-spectacular#726]
Hi in another project we are using drf-yasg but in current we have drf-spectacural. We noticed that during shot on endpoint connected to view - SpectacularAPIView.as_view(...) it run queries to database. Is any option to turn off queries to database? I found info like this abotu DjangoFilterBackend that is connected with queries about choices field: "AllValuesFilter: skip choices to prevent DB query" but in version which we are using there is no DjangoFilterExtension class. Any sugestions?

**Comment by tfranzel** [comment]
we attempt to prevent DB queries as much as possible, but depending on your code it may not be able to catch all of it. 

this issue has not enough info. Is your query happening in `django-filter` or not? 

You may find this [FAQ entry ](https://drf-spectacular.readthedocs.io/en/latest/faq.html?highlight=swagger_fake_view#my-get-queryset-depends-on-some-attributes-not-available-at-schema-generation-time)useful. That if statement allows you write special handling for schema generation.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
