### ISSUE TITLE
Is it possible to change the path parameter name and have it update in the endpoint path in SwaggerUI?

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#730]
I have an endpoint that appears in SwaggerUI as something like `/items/{id}/do/`. As expected the `id` path parameter is listed in the parameters list in SwaggerUI.

However, I want to rename the parameter to `item_id`. I'm able to do the following in `extend_schema`:
```python
            OpenApiParameter(
                "id",
                location="path",
                exclude=True,
            ),
            OpenApiParameter(
                "item_id",
                location="path",
                required=True,
            ),
```
This does make it so that in SwaggerUI, I no longer see the `id` path parameter listed and see just the `item_id` path parameter listed. However, the endpoint path still appears as `/items/{id}/do/` in SwaggerUI. Is it possible for me to somehow make the endpoint path appear as `/items/{item_id}/do/`?

Thanks!

**Comment by tfranzel** [comment]
Hi,

> However, the endpoint path still appears as /items/{id}/do/ in SwaggerUI.

well that is out of our control. The DRF router fixes how the path is called. Your approach to removal is correct for all parameters types except for `path`, as the parameter is indeed removed but the path itself remains untouched.

I think the proper way of changing that name would be to set the attribute `lookup_url_kwarg = "item_id"` on your view. Then spectacular should pick it up automatically.

**Comment by bluelight773** [comment]
Thanks, that worked. I ended up using `lookup_field = "item_id"` and updating refrences in the view from `id` to `item_id`.

**Comment by tfranzel** [comment]
that is the way! 

please be aware that `lookup_field` and `lookup_url_kwarg` are related but do slightly different things. `lookup_field` is geared towards which model field to use and `lookup_url_kwarg` is merely the external name of that.
