### ISSUE TITLE
Refer to a serializers.ChoiceField in OpenApiParameter

### ISSUE THREAD

**Issue by mdefeche** [tfranzel/drf-spectacular#733]
I'd like to refer to a serializers.ChoiceField as a OpenApiParameter's type to list supported enum values for a query param.
```OpenApiParameter("status", type=serializers.ChoiceField(choices=Response.ResponseStatus), location=OpenApiParameter.QUERY),```

It looks like _FieldType is not in the union for OpenApiParameter's type.

Is there another way to do this ?

**Comment by tfranzel** [comment]
this is by design. yeah sure you can do this, you just have to write it a bit different with

```python
OpenApiParameter("status", type=str, enum=Response.ResponseStatus, location=OpenApiParameter.QUERY)
```

assuming `Response.ResponseStatus` is a list of choices.

**Comment by mdefeche** [comment]
Perfect, thank you for your answer :-)
