### ISSUE TITLE
Document how to annotate a generated file response

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#734]
For a read-only `ViewSet` like the following:

```py
from django.http import HttpResponse

class FileViewSet(RetrieveModelMixin, GenericViewSet):
    ...

    def retrieve(self, request, *args: Any, **kwargs: str) -> HttpResponse:
        ...
        export_data = b"..."
        return HttpResponse(
            export_data,
            headers={
                "Content-Type": "text/plain",
                "Content-Disposition": f"attachment; filename=out.txt",
            },
        )
```

I am using an [`HttpResponse`](https://docs.djangoproject.com/en/4.0/ref/request-response/#httpresponse-objects) to support in-memory generated files to serve to clients.

I am following their instructions to [treat the response as a file](https://docs.djangoproject.com/en/4.0/ref/request-response/#telling-the-browser-to-treat-the-response-as-a-file-attachment).

What is the best way to annotate that this is returning a binary file into a `drf-spectacular` schema? I didn't see any mention of this in the docs. I would be happy to contribute the docs if we are able to find a good solution.

**Comment by tfranzel** [comment]
Hey @johnthagen,

yes I believe that is the proper way to model this. I just think it could be more concise. Since `media_type` from the renderer is already utilized, that part should be superfluous. 

```python
    @extend_schema(parameters=[format_param], responses=bytes)
```
should yield the exact same result.

Regarding the documentation: Sure we can always use improvements there, but on that page I tried not to overload an already long page with more edge cases. I opted for just showing that there are more possibilities in that regard. I thought more examples there would distract from the topic but I might be wrong on that one. Open to suggestions there.

**Comment by tfranzel** [comment]
just a quick thought: a FAQ entry might be a good place to put a more thorough explanation. idk

**Comment by johnthagen** [comment]
@tfranzel Thanks for the simplification! I actually worked on the `@extend_schema` part first before realized that DRF would also reject clients that asked for `"application/octet-stream"` unless I overrode the `Renderer`. It's cool that `drf-spectacular` automatically parses that from the `Renderer`.

A complete simplified example:

```py
from rest_framework.renderers import BaseRenderer


class BinaryRenderer(BaseRenderer):
    media_type = "application/octet-stream"
    format = "bin"


class FileViewSet(RetrieveModelMixin, GenericViewSet):
    ...
    renderer_classes = [BinaryRenderer]

    @extend_schema(responses=bytes)
    def retrieve(self, request: Request, *args: Any, **kwargs: str) -> HttpResponse:
        export_data = b"..."
        return HttpResponse(
            export_data,
            content_type=BinaryRenderer.media_type,
            headers={
                "Content-Disposition": "attachment; filename=out.bin",
            },
        )
```

> just a quick thought: a FAQ 

Yes, I was thinking this would be an FAQ as well. I will put together a PR.
