### ISSUE TITLE
Is it possible to define a path parameter using a serializer?

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#737]
I know you can define a query parameter using a serializer. Example:
```python
    @extend_schema(parameters=[ParamSerializer])
```

However, how can I define a path parameter using a serializer. 

If I try the following, I get a nested field, which is not what I want.

```python
    @extend_schema(parameters=[OpenApiParameter("path_param", location="path", type=ParamSerializer)]
```

Say I want the one path parameter, `path_param` to be defined as a `serializers.CharField(max_length=128)`.

**Comment by tfranzel** [comment]
there are 3 ways if using this interface. 

* `parameters=[OpenApiParameter("foo", type=str,...), ...]` : regular usage
* `parameters=[OpenApiParameter("foo", type=ParamSerializer), ...]` : serializer fields represented as nested object. 
* `parameters=[ParamSerializer,...]` : exploded serializer. each field is exposed as `QUERY` parameter. convenience usage pattern.

these all can be mixed and matched. later definitions override previous definitions.

if you want a individual `path_param` your need to do it by hand as exploded serializers are limited to `QUERY`
