### ISSUE TITLE
How to create parameters with regex patterns?

### ISSUE THREAD

**Issue by PaulWay** [tfranzel/drf-spectacular#738]
Hi there!

I'm just coming to `drf_spectacular` after using `drf_yasg` for many years, and I'm having to change all my `openapi.Parameter` definitions over to `OpenApiParameter`.  What's really puzzling me is that I can set `type=OpenApiTypes.REGEX`, but I cannot set a pattern when initialising the parameter.  I understand that serializers can use Regex validators, but I can't see how to add a regex pattern to a parameter.

I'm prepared to write the code to support it, but I thought I'd check first the correct way of setting a regex pattern on a parameter.

Thanks in advance,

Paul

**Comment by PaulWay** [comment]
OK, interesting.  I'd have to check my code at work, but I did try to add the `pattern` keyword to the `OpenApiParameter` declaration and it stopped with an error that `pattern` wasn't a recognised argument.

**Comment by tfranzel** [comment]
@PaulWay you are reading it wrong :smile: I just added the parameter with above commit. You refer to the `pattern` that is part of the dict that I gave to the `type` argument.

you can write arbitrary schemas into a dict and pass it to `type`. this is a fallback mechanism available all throughout spectacular.

**Comment by PaulWay** [comment]
Ah - I'm with you now :-)

**Comment by aupi0** [comment]
On a similar note would it be possible/is there already a method to put a max_length constraint on OpenApiParameters (similar to fields)?

**Comment by tfranzel** [comment]
@aupi0 no sry there is not. You would need to write a small custom schema dict as outlined above. The interface is already somewhat large and I don't want to dilute it further. `max_length` would not be the only potential addition, and adding all other possibilities simply does not scale. `max_length` is not special in that regard.

**Comment by tfranzel** [comment]
I'll close this issue as the initial ask as added
