### ISSUE TITLE
Empty schema

### ISSUE THREAD

**Issue by DarkAbhi** [tfranzel/drf-spectacular#740]
**Describe the bug**
Hi, I'm getting an empty schema.yaml file. I checked around the repo to find many issues with versioning, I've gone through my implementation I don't understand what could be wrong. I've just followed what's on the documentation now.

Added this
```
'drf_spectacular'
```
and this
```
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 16,
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
```
And this
```
SPECTACULAR_SETTINGS = {
    'TITLE': 'Backend API',
    'DESCRIPTION': 'Here\'s the API documentation for the backend.',
    'VERSION': 'v1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}
```
This is how my urls.py looks
```
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.users.urls")),
    path("", include("apps.groups.urls")),
    path("", include("apps.adminsite.urls")),
    path("", include("apps.messaging.urls")),
    path("", include("apps.homesite.urls")),
    path("", include("apps.challenges.urls")),
    path("", include("apps.swmaudit.urls")),
    path("v1.0/", include("apps.courses.urls", namespace='v1.0')),
    # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    
]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
```

**To Reproduce**
Follow the documentation step by step and this is how my urls.py looks if it helps.

**Expected behavior**
Automatically detect endpoints and generate schema

**Comment by DarkAbhi** [comment]
Hi, thanks for the reply.
Do you mean like this

```
    # YOUR PATTERNS
    path('v1.0/api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('v1.0/api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('v1.0/api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
```
This didn't seem to work

**Comment by DarkAbhi** [comment]
> 3\. you can also do `api/schema/swagger-ui/version=YOUR_VERSION` to request a specific version.

Oh well this worked :smile: 

`api/schema/swagger-ui/?version=v1.0`

Forgot the question mark as it's a query param

**Comment by tfranzel** [comment]
> Forgot the question mark as it's a query param

ups. sry

> Do you mean like this

no not like this. in that case it needs to be treated like your other namespace versioning views. that means it must be nested under a version namespace like `path("v1.0/", include("apps.courses.urls", namespace='v1.0')),`. then this use case would work, otherwise its just some random part of the path.

there is one more option: https://github.com/tfranzel/drf-spectacular/issues/650#issuecomment-1032956841
swagger-ui has a top-bar selector if you want. you can easily list mutliple versions like that.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
