### ISSUE TITLE
Is it possible to provide an example value for a multipart/form-data serializer?

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#741]
Let's say I annotate a view with:
```python
    @extend_schema(
        request={
            "multipart/form-data": PostSerializer,
        },
   )
```

And I define the serializer as follows:

```python
@extend_schema_serializer(
    examples=[
        OpenApiExample(
            "An example",
            value={
                "param1": "foo",
                "param2": "bar"
            },
            request_only=True,
            response_only=False,
        ),
    ],
)
class PostSerializer(serializers.Serializer):
    param1 = serializers.CharField()
    param2 = serializers.CharField()
```

When I go to SwaggerUI or ReDoc, I don't see the example nor do I see evidence of it in the OpenAPI schema yaml.

However, if I were to say use `application/json` instead of `multipar/form-data`, the example appears.

Is it simply not possible to provide an example when providing a serializer for `multipart/form-data`?

**Comment by tfranzel** [comment]
Hi,

since the values of the examples are kind of a raw value, we only expose the example if the media type matches. Examples without explicit content type default to `application/json`. If you set the proper `media_type` on the example, it will show up in the schema. What SwaggerUI does then is another topic.

To my knowledge, SwaggerUI does not show examples other than `application/json` for some reason. So even if you add it by hand, it does not show up for other media types. tested this with https://editor.swagger.io

**Comment by bluelight773** [comment]
Thanks for the quick response. I specified `media_type="multipart/form-data"` but still no example appears in SwaggerUI though the examples show up in the generated OpenAPI yaml. 

Is it because I need to specify `value` in the `multipart/form-data` form? If so, any tips on how to formulate it?

I tried different ways of specifying the value including using `multiplify` function provided by https://gist.github.com/kazqvaizer/4cebebe5db654a414132809f9f88067b but that didn't work.

Also, is it possible to just provide an example value for one parameter (and not others even if they're required)?

Thanks

**Comment by tfranzel** [comment]
as i said:

> To my knowledge, SwaggerUI does not show examples other than `application/json` for some reason. 

not sure if it is simply not supported by SwaggerUI or we use it wrong, however I strongly believe it is the former. When it is in the schema AND the schema itself validates, then this is as far as we can go. Everything else would be an upstream issue.

**Comment by tfranzel** [comment]
> Also, is it possible to just provide an example value for one parameter (and not others even if they're required)?

I don't believe so. Its all or nothing afaik.

**Comment by bluelight773** [comment]
I see, I guess it's a SwaggerUI issue.

The example actually shows in Redoc even if only one of several required parameters is specified in the example though I'm not sure if that's proper or misleading documentation.
