### ISSUE TITLE
swagger-ui 500 ,Error during template rendering 

### ISSUE THREAD

**Issue by chaoyifei** [tfranzel/drf-spectacular#745]
TemplateDoesNotExist at /api/schema/swagger-ui/

Error during template rendering 

in template /home/.env/lib/python3.8/site-packages/drf_spectacular/templates/drf_spectacular/swagger-ui.html,error at line 23

23 {% include templatename_js %}

**Comment by tfranzel** [comment]
this seems wrong. looks like you manually changed drf-spectacular incorrectly.

`swagger-ui.html`  the name is wrong, it's an underscrore

`{% include templatename_js %}` there is an underscore missing there

**Comment by chaoyifei** [comment]
sorry ，error log is typed incorrectly。

![lADPJxf-xVZ8F9PNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/29864662/169490250-1d6edf08-136d-40ec-8757-116998802e17.jpg)

**Comment by tfranzel** [comment]
I see. thx for the screenshot. It sounds weird though, as this has not been changed for well over a year and a lot of people are using this at the moment. Also the tests cover multiple python versions as well as django versions and there are no failing tests. 

have you changed something? which django version? does your config look similar to this?

https://github.com/tfranzel/drf-spectacular/blob/403c2fb3b7b497a05710d7d9bbec219c9602f26d/tests/conftest.py#L50-L61

**Comment by chaoyifei** [comment]
thx for your reply ,my environment like this :

python 3.8.10  venv
django==3.2.12
djangorestframework==3.12.1
drf-spectacular==0.22.1
drf-spectacular-sidecar==2022.5.1

oh,spectacular is uninstalled and reinstalled,  changed nothing.

My settings like this:
```python
 TEMPLATES=[ 
     { 
         'BACKEND': 'django.template.backends.django.DjangoTemplates', 
         'DIRS': [], 
         'APP_DIRS': True, 
         'OPTIONS': { 
             'context_processors': [ 
               'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',         
             ], 
         }, 
     }, 
 ], 

STATIC_URL='/static/'
STATIC_ROOT=os.path.join(BASE_DIR,‘static’)

SPECTACULAR_SETTINGS={
    'SWAGGER_UI_DIST':'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF':'SIDECAR',
    'REDOC_DIST':'SIDECAR'
}
DEBUG=True
```
When i entry /api/schema/redoc/, 

Static js files return 404

Url like this :ip:8000 /bundles/redoc.standalone.js

**Comment by chaoyifei** [comment]
when  I  create a new project ,this problem disappear
