### ISSUE TITLE
Is it possible to change the theme of Swagger here?

### ISSUE THREAD

**Issue by magedhelmy1** [tfranzel/drf-spectacular#750]
More of a question than a bug, is it possible to change the theme of the swagger?
For example, to any of [these here]( https://ostranme.github.io/swagger-ui-themes/).

**Comment by tfranzel** [comment]
Hi, that is a modification for which we do not have a setting. However, you can easily patch the used template. There are two options. If you are familiar with djangos templating, this should be easy for you.

1. default django template override. copy and edit https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/templates/drf_spectacular/swagger_ui.html then put it in `templates/drf_spectacular/swagger_ui`. your app must precede `drf_spectacular` in installed apps.
2. `SpectacularSwaggerView.as_view(template_name="XXX")`. provide a modified copy of that template under a different name.

**Comment by magedhelmy1** [comment]
Thank you for the steps! I appreciate the time you have put into this.
I followed the steps and themes ( .css) are not loaded correctly. I think must been swagger UI version issue 3.x.
Which swagger ui version is used in the latest version of drf_spectacular?

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/blob/df9e115ca9b9a3ec84d60df942be28ce3cda13fa/drf_spectacular/settings.py#L74

our link points to the CDN's latest version, which is 4.12 at the moment. You can change our the setting to `https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.52.5`.
