### ISSUE TITLE
Question: How to deal with a generated API ?

### ISSUE THREAD

**Issue by glamothe9** [tfranzel/drf-spectacular#752]
Hi! Thanks for your project, it works well out of the box.

This is not an issue but more a request for help to properly integrate drf-spectacular into my project.

I have this special endpoint that asks for a query parameter. According to these parameters which are stored in base (they are model names), the endpoint will have very different validation criteria according to the chosen model.

I know I can define parameters with @extend_schema only I don't know them in advance since they are user-defined models in a multi-tenant environment.

Is it possible to automatically generate documentation with drf-spectacular based on data in databases?

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
