### ISSUE TITLE
Generated schema is not expected

### ISSUE THREAD

**Issue by shubhambajad** [tfranzel/drf-spectacular#754]
Hi Team,

Actually I am using a drf spectacular library for shema generation using django framework.
In schema file for POST request three formats are present like application/json, application/x-www-form-urlencoded, multi/form-data
But I want only application/json so is their any way to exclude other content type and only keep specific one?

I check docs but I haven't found anything can you guys please help its urgent.

**Comment by tfranzel** [comment]
this is what your API is accepting by default. Just change your default renderers via setting and the others will disappear. If you need something different for specific views, set the `renderer_classes` on your view directly. spectacular will honor that too.

https://www.django-rest-framework.org/api-guide/renderers/#setting-the-renderers

**Comment by shubhambajad** [comment]
@tfranzel Actually I tried solution given by you but it is not working for me.

So, currently my schema consist of three payloads application/json, application/x-www-form-urlencoded, multi/form-data
like given below in screenshot.
<img width="442" alt="SchemaActual" src="https://user-images.githubusercontent.com/95845909/173337554-6fee7667-a00f-481e-8f1e-3498e40d902a.png">

and I am expecting schema file with only application/json content like below in screenshot

<img width="453" alt="SchemaExpected" src="https://user-images.githubusercontent.com/95845909/173337638-6b93c040-96c6-4eb2-8fb3-94b4b4688085.png">

So do we have any solution for this ?

**Comment by tfranzel** [comment]
As I said, the content types are solely based on the `renderer_classes` either from the view or from the default setting. Spectacular only shows what the view accepts. You can check this my making a request with those other types and I have a strong feeling that your API will accept it. There must be something else wrong on your side.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
