### ISSUE TITLE
authorization type changes using drf spectacular library

### ISSUE THREAD

**Issue by shubhambajad** [tfranzel/drf-spectacular#763]
Hi Team,

Actually using drf spectacular library we are generating one schema file in which by default authorization is coming as 
 tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: Token

but we want a authorization type as 'API Key' so is there is any way to change the authorization type using a drf spectacular library so that once we create a schema file "API key" appears as a authorization type instead of bearer token?

**Comment by shubhambajad** [comment]
@tfranzel @ngnpope @jayvdb

**Comment by tfranzel** [comment]
hi @shubhambajad. this is open source with the help of unpaid volunteers, thus there is no SLA for <24h response. please be patient as this is a free for you.

If you see `tokenAuth` it means you are using `rest_framework.authentication.TokenAuthentication` on those views, which is the correct auth method. Its `http` when keyword is `Bearer` and `apiKey` when keyword is something else. In general, `http` is preferrable over `apiKey` so the default makes sense in the vast majority of cases.

If you want something different, subclass and  https://github.com/tfranzel/drf-spectacular/blob/df9e115ca9b9a3ec84d60df942be28ce3cda13fa/drf_spectacular/authentication.py#L32 and set priority to >0.

**Comment by shubhambajad** [comment]
@tfranzel Thank you for your response I will try this.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
