### ISSUE TITLE
SpectacularRedocView and SpectacularSwaggerView are looking for the openapi yaml at the wrong path when FORCE_SCRIPT_NAME and a subdomain are involved

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#769]
I have `urlpatterns` defined as follows:
```py
urlpatterns += [
    path("api.yaml", SpectacularYAMLAPIView.as_view(), name="api-yaml"),
    path(
        "swaggerui/",
        SpectacularSwaggerView.as_view(url_name="api-yaml"),
        name="swaggerui",
    ),
    path(
        "redoc/",
        SpectacularRedocView.as_view(url_name="api-yaml"),
        name="redoc",
    ),
]
```

This works fine locally. However, it doesn't work in production when trying to access the endpoint at `api.example.com/swaggerui` or `api.example.com/redoc`.

The situation in production is as follows:
- `FORCE_SCRIPT_NAME` is used, say set to `/api` whereby the endpoints can be accessed at `www.example.com/swaggerui` and `www.example.com/redoc`. These endpoints work OK as they seem to look for `api.yaml` at `www.example.com/api/api.yaml`. Thus, the documentation shows as expected (though there is a separate issue pertaining to the API server URL called out below).
- A subdomain is used whereby the endpoints can also be accessed at `api.example.com/swaggerui` and `api.example.com/redoc`. These endpoints produce errors as `api.yaml` is looked for at `api.example.com/api/api.yaml` rather than `api.example.com/api.yaml`.

Is there a way to somehow ensure that `api.example.com/swaggerui` and `api.example.com/redoc` look for `api.yaml` at `api.example.com/api.yaml` (rather than at `api.example.com/api/api.yaml`)?

A second problem is that ideally, I'd want `SPECTACULAR_SETTINGS["SERVERS"]` to be set to  `https://api.example.com` if users go to the `api.example.com` endpoints, and to `https://www.example.com/api` if users to go to the `www.example.com/api` endpoints. At the moment, I only know to provide both options and leave it up to the user to pick the right one:
```py
SPECTACULAR_SETTINGS["SERVERS"]: [
        {"url": "https://api.example.com"},
        {"url": "https://www.example.com/api"},
    ]
```

Is it possible to vary the value of `SPECTACULAR_SETTINGS["SERVERS"]` depending on where the Swagger/Redoc endpoint is accessed?

Any pointers that may help with either problem are appreciated.

**Comment by tfranzel** [comment]
Hi @bluelight773,

I never used `FORCE_SCRIPT_NAME`. Do I understand correctly that this introduces a prefix on the path? The thing is we use Djangos utils for building the URLs:

https://github.com/tfranzel/drf-spectacular/blob/fe13dae2d5b60a8682ec727b8c0668aeb0318f53/drf_spectacular/views.py#L151

I would assume that using `reverse` should yield the correct path, if Django was setup properly? I mean Django uses this internally also. Not sure where this breaks exactly for you. `reverse` is supposed to work for you, right?

Regarding your second problem. If you serve the swagger-ui without `SERVERS`, it should take the (sub)-domain from which it was served from. So if above problem would be resolved the second one would resolve itself I guess. 
What you can do however is writing a hook (`POSTPROCESSING_HOOKS`) to change the servers 

https://github.com/tfranzel/drf-spectacular/blob/fe13dae2d5b60a8682ec727b8c0668aeb0318f53/drf_spectacular/settings.py#L89

This should only take a couple of lines to accomplish.

**Comment by tfranzel** [comment]
would you care to explain how you fixed the `FORCE_SCRIPT_NAME` issue? you got me curious there.

**Comment by bluelight773** [comment]
This wasn't my fix and I don't entirely understand it, but what seemed to do the trick was a modification to the `nginx` configuration file adding an entry for `/api`:

```
server {
    # Server configurations

    # This block was required
    location /api {
        # Block config
    }

   location / {
    ...
```
