### ISSUE TITLE
Failed to obtain model through view's queryset due to raised exception.

### ISSUE THREAD

**Issue by lexicalunit** [tfranzel/drf-spectacular#773]
**Describe the bug**
```
Warning #1: BankAccountViewSet: Failed to obtain model through view's queryset due to raised exception.
Prevent this either by setting "queryset = Model.objects.none()" on the view, checking for 
"getattr(self, "swagger_fake_view", False)" in get_queryset() or by simply using @extend_schema.
(Exception: 'AnonymousUser' object has no attribute 'provider')
```

We've got code that looks a bit like this (omitted code marked by `[...]`:
```python
class BankAccountViewSet([...]):
    serializer_class = BankAccountSerializer
    lookup_field = "public_id"

    def get_queryset(self) -> QuerySet[BankAccount]:
        if not self.request.user.provider:
            raise Exception(f"No provider set for user '{self.request.user}'")
        [...]
```

Since DRF Spectacular is using `AnonymousUser` which does not have a provider, we get an exception here when trying to access `self.request.user.provider`.

I've tried to use `@extend_schema(responses=[BankAccountSerializer(many=True)])` here on the `get_queryset()` method, but that doesn't seem to help anything.

**To Reproduce**
Given the above code, running `python manage.py spectacular --file schema.yaml`.

**Expected behavior**
I understand why the error happens due to `AnonymousUser` not having a provider. But with the `@extend_schema(responses=[BankAccountSerializer(many=True)])` override, shouldn't this be resolved?

**Comment by tfranzel** [comment]
Hey Amy, yeah that advice is a bit dense as it covers several different things.

> I've tried to use @extend_schema(responses=[BankAccountSerializer(many=True)]) here on the get_queryset() method, but that doesn't seem to help anything.

on the `get_queryset()` method itself? no that cannot work. `@extend_schema` will only work on "action" methods like `get` `post`, `retrieve` `list`, .... 

Not much we can do about the `AnonymousUser` thing I suppose, but the fix itself shouldn't be too complicated.


```python
class BankAccountViewSet([...]):
    serializer_class = BankAccountSerializer
    lookup_field = "public_id"
    queryset = BankAccount.objects.none()   # <<<1<<< we look here first. 

    def get_queryset(self) -> QuerySet[BankAccount]:
        if getattr(self, "swagger_fake_view", False): # <<<2<<< that is the fallback fix in case we need to call get_queryset
             return BankAccount.objects.none() 
        if not self.request.user.provider:
            raise Exception(f"No provider set for user '{self.request.user}'")
        [...]
```

We essentially need to get to the model itself somehow. having the "empty" `queryset` attribute provides that for us. If we cannot find the `queryset` attribute, we need to call `get_queryset`. Either change should fix your problem.

I prefer solution 1 as it is cleaner, but in some circumstances the 2nd option is necessary. I believe you are set with Option 1.

**Comment by lexicalunit** [comment]
Thanks! I didn't realize that `@extend_schema` was for actions only. My mistake!
