### ISSUE TITLE
Docs should explain that djangorestframework_camel_case needs installing to use CAMEL_CASE

### ISSUE THREAD

**Issue by pjrobertson** [tfranzel/drf-spectacular#774]
**Describe the bug**

EDIT: Scratch that, I didn't realise `djangorestframework_camel_case` was its own package.

Docs should explain that djangorestframework_camel_case would need to be installed to use 'CAMEL_CASE' 

------

OLD ISSUE BELOW:

Import error when using camel_case postprocessor.

**To Reproduce**
Follow the docs to set CAMELIZE_NAME and add the camel_case postprocessor hooks:

```
  # Camelize names like operationId and path parameter names
    # Camelization of the operation schema itself requires the addition of
    # 'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields'
    # to POSTPROCESSING_HOOKS
    'CAMELIZE_NAMES': False,
```

Settings.py:
```
...
    'CAMELIZE_NAMES': True,
    'POSTPROCESSING_HOOKS': ['drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields'],
...
```

2. Try to load up the /redoc/ api view.
3. See the error: `ModuleNotFoundError: No module named 'djangorestframework_camel_case'`

I think the code should read:

```python
 from .util import camelize, camelize_re, underscore_to_camel
```

**Comment by tfranzel** [comment]
Hi @pjrobertson. Improved the doc. The flag itself does not depend on that package, but the hook does. A fine distinction. That should make it clearer

**Comment by pjrobertson** [comment]
Thanks @tfranzel! Your attention to detail, and care for the docs is incredible!
