### ISSUE TITLE
gdal in now required?

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [tfranzel/drf-spectacular#775]
**Describe the bug**
Is `gdal` now required for package usage? Because currently, we have GitHub actions that are failing because gdal is not installed by default.

![image](https://user-images.githubusercontent.com/43534015/180922565-e87907ce-aef9-4735-80fd-dfd0cd2329ee.png)
![image](https://user-images.githubusercontent.com/43534015/180922719-6c9dd5e1-d133-4883-a4f1-0c09c33c5f29.png)

**To Reproduce**
Try to run on the system(container) without `gdal` installed

**Expected behavior**
`gdal` is required only if `rest_framework_gis` is installed

**Comment by Bidaya0** [comment]
Can you help me review this pr? I had the same problem.
I don't really understand how the plugin mode of this project works, so just made a simple change to fix it.

[https://github.com/tfranzel/drf-spectacular/pull/777](https://github.com/tfranzel/drf-spectacular/pull/777)

**Comment by colinschwegmann** [comment]
Pretty big breaking change unless there was a warning?

**Comment by tfranzel** [comment]
looking into it right now. no, GDAL is not a new requirement! it is supposed to be optional in case it is actually used. This goes for all the contrib packages we support.

I tested this in a project without GIS and it did not occur. Trying to find out why atm. Will merge #777 asap and do a hotfix release today.

**Comment by tfranzel** [comment]
Ok so thanks to @Bidaya0 for providing the hotfix. I just released `0.23.1`. Sorry about the inconvenience. 

Poetry fooled me good into believing I was testing the new version.

**Comment by TheSuperiorStanislav** [comment]
With `0.23.1` it works as expected. Thank you @Bidaya0 and @tfranzel
