### ISSUE TITLE
DRF models.DurationField warning

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#78]
**Describe the bug**
DRF DurationField is a string, but is showing a warning.
`Warning #35: could not resolve serializer field DurationField(). defaulting to "string"`

https://github.com/encode/django-rest-framework/blob/aed7496/rest_framework/fields.py#L1363

https://github.com/django/django/blob/1f817da/django/utils/dateparse.py#L125

**Expected behavior**
No warnings for core DRF fields.

**Comment by tfranzel** [comment]
congratulations on finding probably the last missing field. i guess it got past me because it has not direct mapping in `rest_framework.serializers.ModelSerializer.serializer_field_mapping`

easy fix

**Comment by jayvdb** [comment]
> congratulations

thx. I try.

> rest_framework.serializers.ModelSerializer.serializer_field_mapping

should that omission be raised upstream?

fwiw, I am happy to do a bunch of these easy fixes so you can focus on that harder ones.
I'm just raising the things I see as I investigate the result on this new generation; only the exception is important, the rest are just ways to reduce the length of the output for the next adoptee.

**Comment by tfranzel** [comment]
i found that it is not in the list but appended later. so no upstream issue. 

sure thing. thanks.

**Comment by tfranzel** [comment]
@jayvdb could have added a regex for it but would have been the cherry on top. please close on fix confirmation.

**Comment by jayvdb** [comment]
Plain string is good enough; can always revisit later.  Much appreciated.
