### ISSUE TITLE
does this support group list of tags ?

### ISSUE THREAD

**Issue by bboyadao** [tfranzel/drf-spectacular#781]
![Screenshot_2022-08-02-15:42:31-1659429751](https://user-images.githubusercontent.com/25122065/182341774-4d3b1e1b-73fe-41dc-96a2-9c8ae07934e9.png)

1.I am not a redoc talent but found this https://github.com/tfranzel/drf-spectacular/issues/727.
however i dont know what input "..." he described.
2. And one more thing i wanna create blank page like that https://redocly.github.io/redoc/#section/Introduction.
please instruction me.
THANKS!

**Comment by tfranzel** [comment]
1. #727 is only needed if you serve multiple different schema endpoints. Otherwise you just use the regular `SPECTACULAR_SETTINGS` in `settings.py`. You can influence global tagging with `SCHEMA_PATH_PREFIX` while you can also change tags on a view/method level with `@extend_schema` on either the view itself or on the methods (get/post/list/etc)

2. I'm not a redoc expert myself. We just serve a wrapper. How to configure redoc is out of scope for us. Just refer to their doc.

**Comment by tfranzel** [comment]
as a matter of fact, we currently have no equivalence to `SWAGGER_UI_SETTINGS` for redoc. we might need to add this.

**Comment by bboyadao** [comment]
Just found `"EXTENSIONS_ROOT": {"x-tagGroups":`
![Screenshot_2022-08-02-23:08:25-1659456505](https://user-images.githubusercontent.com/25122065/182422209-3a8b6f1b-4590-4a73-81c0-a515948b04b3.png)
File config below, we can put it in settings file but load to runtime very first so i put it in to urls file.
![Screenshot_2022-08-02-23:09:23-1659456563](https://user-images.githubusercontent.com/25122065/182422221-5990ddc1-5259-4f7c-89e5-33808a6444dd.png)

**Comment by tfranzel** [comment]
yeah that works too. that is the second reason one would use `custom_settings`. Good stuff. I think I can close this.

**Comment by bboyadao** [comment]
> yeah that works too. that is the second reason one would use `custom_settings`. Good stuff. I think I can close this.


2 resolved also with `x-traitTag`. Code below might helpful for someone.
```
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView
from django.urls import path
from rest_framework import permissions
from django.conf import settings
from chuthe.roles import Privacy
from docs.utils import get_md_docs

INSTRUCTION = "INSTRUCTION"
sub_instruction = ["overview", "define"]

urlpatterns = [
    path("", SpectacularRedocView.as_view(), name="redoc"),
    path("api/schema", SpectacularAPIView.as_view(
        permission_classes=[permissions.IsAuthenticated],
        custom_settings={
            "EXTENSIONS_ROOT": {
                "x-tagGroups": [
                    {"name": INSTRUCTION,
                     "tags": sub_instruction},
                    {
                        "name": Privacy.ADMIN,
                        "tags": settings.DOCS_TAG[Privacy.ADMIN.value],
                    },
                    {
                        "name": Privacy.STAFF,
                        "tags": settings.DOCS_TAG[Privacy.STAFF.value],
                    },
                    {
                        "name": Privacy.USER,
                        "tags": settings.DOCS_TAG[Privacy.USER.value],
                    },
                    {
                        "name": Privacy.PUBLIC,
                        "tags": settings.DOCS_TAG[Privacy.PUBLIC.value],
                    },

                ],

            },
            "TAGS": [
                {"name": "overview",
                 "description": get_md_docs("instruction.md"),
                 "x-traitTag": True
                 },
                {"name": "define",
                 "description": get_md_docs("define.md"),
                 "x-traitTag": True
                 },
            ],

        }
    ),
         name="schema"
         ),
]

```
