### ISSUE TITLE
Can swagger show different API version in a single UI?

### ISSUE THREAD

**Issue by Sahayana** [tfranzel/drf-spectacular#784]
Hello,

During a migration process into `drf-spectacular` from `yasg` on my project, I have a wonder of showing schema for different versioned API in one single swagger UI.

When the project goes bigger and sometimes it comes with many apis different versioned and mixed.

This is the best practice to tell different versions by configuring them on the endpoint when given namespaces.  (as far as I know)

```
path("docs/v2/swagger/", SpectacularSwaggerView.as_view(url_name="schema-v2"), name="swagger-v2",),
path("docs/v3/swagger/", SpectacularSwaggerView.as_view(url_name="schema-v3"), name="swagger-v3",),
```

I find myself in trouble digging a way to show all versions in one swagger or just wonder it would be technically wrong.

**Comment by tfranzel** [comment]
Hi,

what you do there is certainly possible and this pattern is also used in the tests. Generally it is not a good practice to stuff everything into one schema. What if some serializer (with identical name) is different from v2 to v3. That cannot be easily modeled in the schema.  SwaggerUI provides a dropdown for versions. I have answered this before somewhere in the issues. 

How to enable swagger-ui topbar

```python
SPECTACULAR_SETTINGS = {
    ////
    'SWAGGER_UI_SETTINGS':  '''{
        deepLinking: true,
        urls: [{url: "/backend/api/schema/v2", name: "v2"}, {url: "/backend/api/schema/v3", name: "v3"}],
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
    }''',
}
```

If you properly setup your API `SpectacularSchemaView` will do the heavy lifting. Requesting `api/schema?version=v3` will fillter your schema to only include unversioned and `v3`


There are multiple ways of doing this with spectacular, but they are not that obvious from the start I think. I think I should write a doc page dedicated to versioning as those questions are recurring.

**Comment by Sahayana** [comment]
@tfranzel 

oh I'm sorry I might have passed to finding issues but thanks for getting me detail anyway.

but Should I put extra settings more like touching JS or templates?

I've been seeing around issues you mentioned and I guess they put more attempt in touching JS or something.

I've tried your instruction as above :
```
"SWAGGER_UI_SETTINGS": 
    '''{
        deepLinking: true,
        urls: [{url: "/v3/schema", name: "v3}, {url: "/v2/schema", name: "v2"}],
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
        dom_id": "#swagger-ui",
        
    }'''
```

and my URL conf looks:
(It gets dirty as I dive into the practice.)
```
urlpatterns += [
    path("v2/schema/", SpectacularAPIView.as_view(api_version="v2"), name="schema-v2"),
    path("v3/schema/", SpectacularAPIView.as_view(api_version="v3"), name="schema-v3"),
    path("docs/json/", SpectacularJSONAPIView.as_view(), name="schema-json"),
    path("docs/yaml/", SpectacularYAMLAPIView.as_view(), name="swagger-yaml"),
    path(
        "docs/v2/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema-v2"),
        name="swagger-v2",
    ),
    path(
        "docs/v2/redoc/",
        SpectacularRedocView.as_view(url_name="schema-v2"),
        name="redoc-v2",
    ),
    path(
        "docs/v3/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema-v3"),
        name="swagger-v3",
    ),
    path(
        "docs/v3/redoc/",
        SpectacularRedocView.as_view(url_name="schema-v3"),
        name="redoc-v3",
    ),
]
```

Apparently I can access swagger UI with no errors
and **nothing comes out but grey screen.**

**Comment by tfranzel** [comment]
> Apparently I can access swagger UI with no errors and nothing comes out but grey screen.

that means that no views are matching `v2` or `v3` given the `Versioning` classes you use on your views. What versioning class are you using (namespace/path/header versioning)? The view must know which version it is, otherwise spectacular cannot filter based on that info.

> but considering your advice that It's not a good idea to gather all up, maybe better off step back from this?

no you can do it like that, but there are more elegant ways. 

`SpectacularAPIView` takes a version url param. your can do `/schema?version=v3` `schema?version=v2` in the `SWAGGER_UI_SETTINGS`. Then you only need one schema in the `urlpatterns`:

```python
path("schema/", SpectacularAPIView.as_view(), name="schema"),
```

also if you use the swagger-ui topbar selector, you also only need one `SpectacularSwaggerView`.

**Comment by Sahayana** [comment]
> What versioning class are you using (namespace/path/header versioning)? The view must know which version it is, otherwise spectacular cannot filter based on that info.

I'm using **namespace** versioning and it worked fine.

> SpectacularAPIView takes a version url param.

This came successful when I set like this:

```python
'SWAGGER_UI_SETTINGS': {
        'dom_id': '#swagger-ui',  
        'layout': 'BaseLayout',  
        'deepLinking': True,  
        'persistAuthorization': True, 
        'displayOperationId': True,
        'filter': True, 
    },
```
and `urls.py`:

```python
urlpatterns += [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
]
```
with this set up, **I can surely access** to the swagger with version parms of `/docs/swagger/?version=v3` and `/docs/swagger/?version=v2`


The next stage is to apply top bar plugin setup so I changed `'SWAGGER_UI_SETTINGS'` as instructed like below:

```python
"SWAGGER_UI_SETTINGS": 
    '''{
        deepLinking: true,
        urls: [{url: "/schema/?version=v3", name: "v3"}, {url: "/schema/?version=v2", name: "v2"}]
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
        dom_id": "#swagger-ui",
        persistAuthorization: true,  
        displayOperationId: true, 
    }''',
```

and I tried my approach to swagger with 3 patterns as below:
 - `/docs/swagger`.  **(failed)**
 - `/docs/swagger/?version=v3`. **(failed)**
 - `/docs/swagger/?version=v2`. **(failed)**

I found a completed issue #650 and not to bother you anymore,  I have started to change `urls` field in `'SWAGGER_UI_SETTINGS'` and my `urls.py` like 100 times just in order to figure out what's wrong and happening but still failed.

What have I missed?

**Comment by tfranzel** [comment]
> I found a completed issue https://github.com/tfranzel/drf-spectacular/issues/650 and not to bother you anymore

that was mainly about a a custom versioning class. Also you cannot use versioned request `/docs/swagger/?version=v2` at the same time with `SWAGGER_UI_SETTINGS.urls`. **they are mutually exclusive due to the way swagger-ui handles this.**

> with this set up, I can surely access to the swagger with version params of /docs/swagger/?version=v3 and /docs/swagger/?version=v2

Does this mean it worked and you got a  versioned schema? So you have to clarify what exactly worked. It easier to understand the problem when we better locate the issue. 

The schema endpoint and the swagger endpoint are 2 different things. We need the understand where the problem is. It helps inspecting whether the schema endpoint returned a versioned schema or not **and then** look if the UI displays it properly.

> with this set up, I can surely access to the swagger with version params of /docs/swagger/?version=v3 and /docs/swagger/?version=v2

again to that point. `/docs/swagger/?version=v3` is just passed through as `schema/?version=v3`. If you say that this works, there is no reason for it to not work in the `SWAGGER_UI_SETTINGS.urls` setting, as it is literally the same thing.

**Comment by Sahayana** [comment]
- `Versioning class`: **namespace**

> with this set up, I can surely access to the swagger with version params of /docs/swagger/?version=v3 and /docs/swagger/?version=v2

**This is how it works.**

```python
# "SWAGGER_UI_SETTINGS"
"SWAGGER_UI_SETTINGS" = {
    'dom_id': '#swagger-ui',  
    'layout': 'BaseLayout',  
    'deepLinking': True,  
    'persistAuthorization': True, 
    'displayOperationId': True,
    'filter': True, 
}

# urls.py
urlpatterns += [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
]

```
**Output**:
 -  url:` /docs/swagger/?version=v3`
 ![스크린샷 2022-08-11 오후 6 22 00](https://user-images.githubusercontent.com/91467403/184103023-45af9f27-04d0-458c-a793-438578a969ed.png)

 - `?version=v2` also works well.

**This is how it does not work**
> your can do /schema?version=v3 schema?version=v2 in the SWAGGER_UI_SETTINGS. Then you only need one schema in the urlpatterns:
> also if you use the swagger-ui topbar selector, you also only need one SpectacularSwaggerView.


```python
# "SWAGGER_UI_SETTINGS"
"SWAGGER_UI_SETTINGS" = '''{
    deepLinking: true,
    urls: [{url: "/schema/?version=v3", name: "v3"}] 
    presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
    layout: "StandaloneLayout",
    dom_id": "#swagger-ui",
    persistAuthorization: true,  
    displayOperationId: true,
    filter: true 
}'''

# urls.py
urlpatterns += [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
]

```

 **Output**:
  - /docs/swagger **(failed)**
  - /docs/swagger/?version=v3 **(failed)**
  - /docs/swagger/?version=v2 **(failed)**

 **What I have tried in `SWAGGER_UI_SETTINGS.urls`:**
  - /schema
  - /schema/?version=v3
  - /docs/schema
  - /docs/swagger
  - /docs/swagger/?version=v3

**but still stuck.**

**Comment by tfranzel** [comment]
> Output: grey screen

does this mean "no schema shown" or "the screen is completely blank". Is the topbar still showing up?

In principle this looks all ok and should work. I cant see any issue with your setup. 

You have too look into the browser debug console and compare what the `schema/` endpoint returns. Maybe something changed with swagger-ui and that `SWAGGER_UI_SETTINGS` does not work like that anymore.

> /docs/swagger (failed)

the fact that this works in your first try, but fails in the second try with topbar is very suspicious and points to swagger. as they are literally using the same schema endpoint.

**Comment by Sahayana** [comment]
> does this mean "no schema shown" or "the screen is completely blank". Is the topbar still showing up?

It's completely blank.
I guess it gets no view as you said before and I've never seen a top bar showing up during this process.

> You have too look into the browser debug console and compare what the schema/ endpoint returns. Maybe something changed with swagger-ui and that SWAGGER_UI_SETTINGS does not work like that anymore.


I will follow your instruction and check against everything to see what I've been missing.

Thanks for your support and will share the result after.

**Comment by tfranzel** [comment]
all your code samples have a syntax error. You could have seen this by looking in the browser console. There was a `,` missing after the urls row.

I tested this exact configuration and it works with swagger-ui. Even if the schema is empty, something will be shown.

```python
SPECTACULAR_SETTINGS = {
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": '''{
        deepLinking: true,
        urls: [{url: "/api/schema/?version=v1", name: "v1"}, {url: "/api/schema/?version=v2", name: "v2"}],
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: "StandaloneLayout",
        persistAuthorization: true,  
        displayOperationId: true,
        filter: true 
    }''',
```

**Comment by Sahayana** [comment]
> all your code samples have a syntax error. You could have seen this by looking in the browser console. There was a `,` missing after the urls row.

I don't even wanna believe that I've been putting my hardest and time to figure out what's been wrong that it was a simple comma missing.

I've finished checking UI showing up as expected.

I'm sorry for making you confused and taking your time.

Thanks 👍
