### ISSUE TITLE
Multiple input/output types for an endpoint

### ISSUE THREAD

**Issue by zhiltsov-max** [tfranzel/drf-spectacular#785]
Hi. I have several endpoints that have a similar pattern - they accept multiple input or output types in request or response data depending on the query parameter value. I've tried to use `PolymorphicProxySerializer`, but it only seem to support serializer classes. Also, it requires structures to have a discriminator field and to provide an explicit name for the resulting union type (when it could be anonymous). In my cases, I have a file as one of the options, and `PolymorphicProxySerializer` doesn't seem to support both DRF Field (tried `rest_framework.serializers.FileField`) and `OpenApiTypes.BINARY` in the serializers list. If I pass an `OpenApiTypes` entry into a list, it doesn't get into the resulting schema (a `PolymorphicProxySerializer: PolymorphicProxySerializer's serializer argument contained unknown objects.` error is generated). How such endpoints could be described with `@extend_schema`?

To be more specific, the cases:
1. An endpoint that accepts either nothing or a serializer, depending on the query parameter value/presence (the action parameter). (I didn't find any other way to describe an optional request body or response body for the same status code)
2. An endpoint that accepts either a serializer or a file, depending on the query parameter value/presence (the `format` parameter).
3. An endpoint that responds with a serializer or a file, depending on the query parameter value/presence (the `format` parameter) 
4. An endpoint that responds with one or another serializer, but they have no discriminator field which could describe the response type. The types have some overlap - a simple and an extended views of the same structure. 
  (Seemed like I need to just obtain `anyOf` instead of `oneOf` in the resulting schema. Solved with a custom `PolymorphicProxySerializer` extension)

**Comment by zhiltsov-max** [comment]
It seems that I was able to workaround these issues with few extensions. Not sure if it is supposed to be implemented this way, but it works. I'll share the reusable part of my implementation.

```python
from drf_spectacular.plumbing import build_basic_type
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.serializers import PolymorphicProxySerializerExtension

class OpenApiTypeProxySerializerExtension(PolymorphicProxySerializerExtension):
    """
    Provides support for OpenApiTypes in the PolymorphicProxySerializer list
    """
    priority = 0 # normal priority, higher than in the parent class

    def _process_serializer(self, auto_schema, serializer, direction):
        # Covers case #2 and #3
        if isinstance(serializer, OpenApiTypes):
            schema = build_basic_type(serializer)
            return (None, schema)
        else:
            return super()._process_serializer(auto_schema=auto_schema,
                serializer=serializer, direction=direction)

    def map_serializer(self, auto_schema, direction):
        """ custom handling for @extend_schema's injection of PolymorphicProxySerializer """
        result = super().map_serializer(auto_schema=auto_schema, direction=direction)

        # Covers case #1
        if isinstance(self.target.serializers, dict):
            required = OpenApiTypes.NONE not in self.target.serializers.values()
        else:
            required = OpenApiTypes.NONE not in self.target.serializers

        if not required:
            result['nullable'] = True

        return result

class CustomProxySerializerExtension(OpenApiTypeProxySerializerExtension):
    """
    Allows to patch PolymorphicProxySerializer-based schema.

    Override "target_component" in children classes.
    """
    priority = 1 # higher than in the parent class

    target_component: str = ''

    @classmethod
    def _matches(cls, target) -> bool:
        if cls == __class__:
            return False

        if not super()._matches(target):
            return False

        return target.component_name == cls.target_component

class AnyOfProxySerializerExtension(CustomProxySerializerExtension):
    """
    Replaces oneOf with anyOf in the generated schema. Useful when
    no disciminator field is available, and the options are
    not mutually-exclusive.
    """

    def map_serializer(self, auto_schema, direction):
        schema = super().map_serializer(auto_schema, direction)
        schema['anyOf'] = schema.pop('oneOf') # Covers case #4
        return schema

class MetaUserSerializerExtension(AnyOfProxySerializerExtension):
    # Need to replace oneOf to anyOf for MetaUser variants
    # Otherwise, clients cannot distinguish between classes
    # using just input data. Also, we can't use discrimintator
    # field here, because these serializers don't have such.
    target_component = '<your component name>'

```

**Comment by tfranzel** [comment]
Hi, 

> they accept multiple input or output types in request or response data depending on the query parameter value

the schema is generated once. It cannot vary based on dynamic inputs. In general, you can only cover those cases with an `oneOf` "union"

> PolymorphicProxySerializer, but it only seem to support serializer classes

that is true. The type hint for the `serializer` argument clearly states that too. 

> 1. An endpoint that accepts either nothing or a serializer, depending on the query parameter value/presence (the action parameter). (I didn't find any other way to describe an optional request body or response body for the same status code)

I would have recommended to do `@extend_schema(responses={200: XSerializer, 204: None})`, but it is a different status code. It is not that easy to model this with a `oneOf`.

> 2/3

I believe we do not support `FileUploadParser` automatically at the moment, only `MultiPartParser`.

However, I think you attempted to shoehorn your use-case into the component mechanics, which are not a good fit imho. I think you can handle this less painfully one step further up.

```python
    @extend_schema(
        request={
            'application/json': XSerializer,
            'application/octet-stream': OpenApiTypes.BINARY,
        },
        responses={
            (200, 'application/json'): XSerializer,
            (200, 'application/octet-stream'): OpenApiTypes.BINARY

        }
    )
```

> 4. An endpoint that responds with one or another serializer, but they have no discriminator field which could describe the response type. 

The documentation for `PolymorphicProxySerializer` states: "Setting ``resource_type_field_name`` to ``None`` will remove the discriminator altogether. ...."
Compound component with `anyOf` are not supported as this really hard to model correctly in a generic way.

spectacular more or less guides you to use named components, as client code generators have a really hard time generating functioning code when there are "anonymous" components directly mounted into to request/response section.

**Comment by zhiltsov-max** [comment]
Thank you for the answers!

>> they accept multiple input or output types in request or response data depending on the query parameter value

> the schema is generated once. It cannot vary based on dynamic inputs. In general, you can only cover those cases with an oneOf "union"

In these cases, the list of possible parameter values is fixed and known during schema generation time, and is described by an enum, so no dynamic schema is supposed.

>> PolymorphicProxySerializer, but it only seem to support serializer classes

> that is true. The type hint for the serializer argument clearly states that too.

Is there any reason why it doesn't support other types, while in other places they are available? I mean, `request`, `responses`, parameters - all allow `OpenApiTypes` elements as values.

>> 1. [...]

> I would have recommended to do @extend_schema(responses={200: XSerializer, 204: None}), but it is a different status code.

Thank you for the idea. Yeah, it can work, but unfortunately, I'm working on the code that is already being used extensively, so I try to have only documentation changes and keep the existing behavior at this point. But, even without this, the endpoint already uses several other response codes, and if we use something except 200 in this case, we're going to deviate from the established [HTTP logic](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

> 2/3

It's an interesting idea, I need to check. I have one possible doubt here though - I suspect the content type is just a transfer property, meaning we transfer the same data in different ways. But in our cases, we have different data passed: if no `format` specified - a json, or a file, if the `format` is specified. Maybe, we should just try to split the endpoint, need to think if it is reasonable.

**Comment by tfranzel** [comment]
> In these cases, the list of possible parameter values is fixed and known during schema generation time, and is described by an enum, so no dynamic schema is supposed.

not sure if we ever had that case. You will likely have to resort to extensions, where you can run code while the schema is generated. All other mechanics do not take into account dynamic behavior like that.

> Is there any reason why it doesn't support other types, while in other places they are available? I mean, request, responses, parameters - all allow OpenApiTypes elements as values.

Yes there is. That is why I said "one level up". When you do `request` with `PolymorphicProxySerializer`, this is implicitly mounted under each content type that the view's `renderer_classes`/`parser_classes` support (usually `application/json` or mixed). It would no make no sense to mount a binary blob under `application/json` for example, which is why we do not allow it. By doing a `request={...}` you modify the schema one level further up, compared to `PolymorphicProxySerializer`, which is where those `OpenApiType`s actually make sense.

> , I'm working on the code that is already being used extensively,

Just thought to bring it up, but I figured that much.

> It's an interesting idea, I need to check. I have one possible doubt here though - I suspect the content type is just a transfer property, meaning we transfer the same data in different ways. But in our cases, we have different data passed: if no format specified - a json, or a file, if the format is specified. 

I see. spectacular is limited by the capabilites of OpenAPI3. I believe you can model this like I outlined, but you will have no strong connection to the `format` parameter. It is just a list of choices that are not directly connected to `format`. Afais, there is no way in OpenAPI to make that relationship explicit like that. You would need to duplicate the endpoint for each variation, which is most likely not well supported (or even alllowed) in OpenAPI.
