### ISSUE TITLE
Read only fields included in required list for input serializer

### ISSUE THREAD

**Issue by PaulWay** [tfranzel/drf-spectacular#787]
**Describe the bug**
In a serializer with a field defined as `read_only=True`, the field is also in the 'required' list.  This means that it must be supplied as input, when it is read-only and cannot be changed.

**To Reproduce**
```python
class TopicSerializer(serializers.ModelSerializer):
    impacted_systems_count = serializers.IntegerField(read_only=True)

    class Meta:
        model = models.RuleTopic
        fields = (
            'name', 'slug', 'description', 'featured',
            'enabled', 'impacted_systems_count',
        )
```
Generates (compressed for clarity):
```json
            "Topic": {
                "type": "object",
                "description": "Topics group rules by a tag shared by all the rules.",
                "properties": {
                    "name": {"type": "string", "maxLength": 80},
                    "slug": {"type": "string", "maxLength": 20},
                    "description": {"type": "string"},
                    "tag": {"type": "string"},
                    "featured": {"type": "boolean"},
                    "enabled": {"type": "boolean"},
                    "impacted_systems_count": {"type": "integer", "readOnly": true}
                },
                "required": [
                    "description", "impacted_systems_count", "name", "slug", "tag"
                ]
            },
```
**Expected behavior**
The schema I expect this to generate is:
```json
            "Topic": {
                "type": "object",
                "description": "Topics group rules by a tag shared by all the rules.",
                "properties": {
                    "name": {"type": "string", "maxLength": 80},
                    "slug": {"type": "string", "maxLength": 20},
                    "description": {"type": "string"},
                    "tag": {"type": "string"},
                    "featured": {"type": "boolean"},
                    "enabled": {"type": "boolean"},
                    "impacted_systems_count": {"type": "integer", "readOnly": true}
                },
                "required": [
                    "description", "name", "slug", "tag"
                ]
            },
```
The `impacted_systems_count` field is not required.

I also tried using: 
```python
    impacted_systems_count = serializers.IntegerField(read_only=True, required=False)
```
But this made no difference to the output schema.

**Comment by PaulWay** [comment]
Ah.  I've just discovered the page:

https://drf-spectacular.readthedocs.io/en/latest/client_generation.html#component-issues

And the COMPONENT_SPLIT_REQUEST and COMPONENT_NO_READ_ONLY_REQUIRED options.  OK, I think I've got it now :-)

**Comment by tfranzel** [comment]
technically, it is correct that a read_only field is required as required is default on with DRF.

try `'COMPONENT_SPLIT_PATCH': True` only first, as it yields a more correct schema. 

>     impacted_systems_count = serializers.IntegerField(read_only=True, required=False)

from the top of my head, this should have removed `impacted_systems_count` from the required list though, even without the component split. 

In any case it is preferable to use component split for client generation. It makes a lot of things easier.
