### ISSUE TITLE
drf-spectacular issue with django rest framework 3.10

### ISSUE THREAD

**Issue by fannyhub** [tfranzel/drf-spectacular#791]
**Bug description**
The rest framework's version  3.10 PageNumberPagination does not have a get_paginated_response_schema method and ./manage.py spectacular --file schema.yml returns an error. The error does not occur in the case of version 3.13.
full traceback:
![image](https://user-images.githubusercontent.com/5873729/186342321-169abeab-0ad8-4900-8aca-b76d3628be63.png)

**To reproduce**
stack: Django 2.2 + Python 3.9.11 + drf-spectacular 0.23.1 + djangorestframework 3.10.1 + docker
run the project and type in the container  ./manage.py spectacular --file schema.yml

**Expected behavior**
Schema gets generated without issues

**Comment by tfranzel** [comment]
Hi, ` 3.10.1` does indeed miss `get_paginated_response_schema`. However we won't complicate our code base for a severely outdated and unsupported version. Please consider using `3.10.3`. DRF only supports the latest dot release btw.
