### ISSUE TITLE
Responses Inheritence

### ISSUE THREAD

**Issue by sumanth-manchala** [tfranzel/drf-spectacular#793]
Hi!!!, I want to make the error message schema to be consistent across all my viewsets. Is there a way I can define my 40x and 500 responses to have a particular schema across the entire Viewset instead of duplicating it for every view? I tried defining like below, but this doesn't work.

````
@extend_schema(
       responses = {400: BadRequestSerializer, 403: InvalidPermissionSerializer}
    )
class SomeViewSet(mixins.ListModelMixin, GenericViewSet):
    queryset = SomeModel.objects.all()
    serializer = SomeSerializer

    @extend_schema(
       responses = {200: SomeOtherSerializer}
    )
    def some_other(self, request, *args, **kwargs):
        return Response(SomeOtherSerializer(some_other_qs).data)
````
**Expected behavior**
some_other view should also have the 400 and 403 responses inherited since they are not overridden. Is there any other way of achieving this?

**Comment by tfranzel** [comment]
Hi, we have an ongoing discussion on how to handle those error cases (#101) in a generic way. 

You are layering `@extend_schema` which indeed does work like that. However, each parameter (`responses`) is overridden in it's entirety. So `list` is missing `SomeSerializer` and `some_other` is missing the error serializers. For practical reasons it needs to behave like that.

I would recommend doing something like this atm:

```python
ERRORS = {400: BadRequestSerializer, 403: InvalidPermissionSerializer}

@extend_schema_view(
 list=extend_schema(responses={200: SomeSerializer, **ERRORS})
)
class SomeViewSet(mixins.ListModelMixin, GenericViewSet):
    queryset = SomeModel.objects.all()
    serializer = SomeSerializer

    @extend_schema(
        responses={200: SomeOtherSerializer, **ERRORS}
    )
    def some_other(self, request, *args, **kwargs):
        return Response(SomeOtherSerializer(some_other_qs).data)
```

I chose to use `extend_schema_view` as it gives you control over the individual viewset methods, however your approach can also work given the added `**ERRORS`.

**Comment by sumanth-manchala** [comment]
Thanks, @tfranzel, this is what I was thinking to do, just wanted to check if I was missing something. I will look out for https://github.com/tfranzel/drf-spectacular/issues/101, closing this for now.
