### ISSUE TITLE
@extend_schema_field does not apply when serializer is used at the top level

### ISSUE THREAD

**Issue by mwhansen** [tfranzel/drf-spectacular#798]
**Describe the bug**
Maybe this is by design (since `extend_schema_field` can take basic types), but it feels like the following should work. If we have a serializer that is decorated with `@extend_schema_field`, then that is used only when the serializer appears as a field (sub-serializer) on another serializer as  `has_override(serializer, 'field')` is only checked in `_map_serializer_field`. This makes is difficult to use a polymorphic serializer as a `serializer_class` on a `GenericAPIView`.

**To Reproduce**
You can include this code in `tests/test_polymorphic.py`:
```
def test_polymorphic_serializer_as_generic_api_view_serializer_class(no_warnings):
    @extend_schema_field(
        PolymorphicProxySerializer(
            component_name='MetaPerson',
            serializers=[LegalPersonSerializer, NaturalPersonSerializer],
            resource_type_field_name='type',
        )
    )
    class XSerializer(serializers.Serializer):
        pass  # pragma: no cover

    class XView(GenericAPIView):
        serializer_class = XSerializer

        def get(self, request):
            pass  # pragma: no cover

    schema = generate_schema('x', view_function=XView.as_view())
    assert 'MetaPerson' in schema['components']['schemas']
```

**Expected behavior**
I would expect the above tests to pass and that we'd have a schema like this generated:
```
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaPerson'
          description: ''
```

**Comment by tfranzel** [comment]
> Maybe this is by design (since extend_schema_field can take basic types), but it feels like the following should work.

This is indeed by design. `@extend_schema_field` is intended to be used on field classes as well as serializer fields / `SerializerMethodField` functions. The interface is designed to make sense in that context.

More appropriately, you would use `@extend_schema_serializer`, which is intended for serializer decoration. You can do a lot there, **however** we currently do not support to replace the serializer schema in it's entirety there. 

Usually people would attach that `PolymorphicProxySerializer` to a view method via `@extend_schema(request=...,responses=...)`. Unless I'm missing something, that approach should usually make more sense. Imho replacing the serializer structure from the get-go kind of defeats the purpose of having that serializer in the first place. 

As a sidenote: If you intend to have some crazy dynamic serializer class, you would usually resort to writing a `OpenApiSerializerExtension` for that.

**Comment by mwhansen** [comment]
> Usually people would attach that `PolymorphicProxySerializer` to a view method via `@extend_schema(request=...,responses=...)`. Unless I'm missing something, that approach should usually make more sense. Imho replacing the serializer structure from the get-go kind of defeats the purpose of having that serializer in the first place.

Yeah, that works, but you do need to reference the polymorphic proxy serializer in multiple places (`@extend_schema` and `@extend_schema_field`). 

The case we have is just dispatching between multiple serializers depending on the type of the object being serialized so all of the work is in `to_representation` -- there isn't anything to introspect so any schema-related information needs to come from an additional annotation.

**Comment by tfranzel** [comment]
> Yeah, that works, but you do need to reference the polymorphic proxy serializer in multiple places 

I see, that is true. 

> The case we have is just dispatching between multiple serializers depending on the type of the object being serialized so all of the work is in to_representation -- there isn't anything to introspect so any schema-related information needs to come from an additional annotation.

From what I have seen, a custom `to_representation` almost always points to writing a `OpenApiSerializerExtension`. At least that would be my recommendation then. Is this a one-off or a generic approach in your code base? I would either write a extension for that serializer explicitly, or write a generic one that targets some common base class.

`rest_polymorphic` is doing the same thing with a custom `to_representation`. Here is our extension that resolves that: https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/contrib/rest_polymorphic.py

Your generic case could look like: 
```python
    class CustomToRep:
        def to_representation(self):
            pass

    class XSerializer(CustomToRep, serializers.Serializer):
        class Meta:
            schema_serializer = PolymorphicProxySerializer(
                component_name='MetaPerson',
                serializers=[NaturalPersonSerializer, LegalPersonSerializer],
                resource_type_field_name='type',
            )

    class CustomToRepExtension(OpenApiSerializerExtension):
        target_class = CustomToRep  # import string is also fine.
        match_subclasses = True

        def map_serializer(self, auto_schema, direction):
            # get the custom Meta field
            schema_serializer = self.target.Meta.schema_serializer
            # run mapping for that PolymorphicProxySerializer
            mapped = auto_schema._map_serializer(schema_serializer, direction)
            return mapped
            # for more complicated things this is also a way:
            # component = auto_schema.resolve_serializer(schema_serializer, direction)
            # some more massaging
            # return component.ref
```

**Comment by tfranzel** [comment]
I mean we could add that capability to `extend_schema_serializer`, but it seem like a rather rare case where it is actually the right thing to do. It just so happens to be that your case is easily solvable with a `PolymorphicProxySerializer`. Other custom `to_representation` might not be easily solved that way. 

I am primarily concerned with giving users the wrong idea on how/when to use the decorators. The interface is already quite involved. If that issue comes up again, we can certainly reevaluate it.

**Comment by mwhansen** [comment]
@tfranzel Sorry to bring up an old issue, but we ended up adding the following to our `AutoSchema` subclass since it gives us the desired behavior we want in all of the cases we've encountered so far:
```
   def _map_basic_serializer(self, serializer, direction):
        if has_override(serializer, 'field'):
            return self._map_serializer_field(serializer, direction)
        return super()._map_basic_serializer(serializer, direction)
```
It also fixes an issue where you have something like
```
@extend_schema_field(PolymorphicProxySerializer(...))
class MyPolymorphicSerializer(...):
    ...

class ParentSerializer(...):
    children = MyPolymorphicSerializer(many=True)
```
When we run `_upwrap_list_serializer`, it calls `resolve_serializer` which treats `MyPolymorphicSerializer` as a "top-level serializer" and doesn't use `_map_serializer_field`.

**Comment by tfranzel** [comment]
Hey Mike,

no worries. Glad that this works out for you. Not sure if would include it officially though. Have you by any chance tried out my proposal? I thought this to be quite compact and expressive.

**Comment by mwhansen** [comment]
> Hey Mike,
> 
> no worries. Glad that this works out for you. Not sure if would include it officially though. Have you by any chance tried out my proposal? I thought this to be quite compact and expressive.

Yep, that totally works, but it adds a bit more mental overhead for a large team when to use that over `@extend_schema_field`.
