### ISSUE TITLE
Register additional components from an extension

### ISSUE THREAD

**Issue by RasmusAntons** [tfranzel/drf-spectacular#801]
I want to use pydantic to generate the schema for one specific serializer. There might be a better method, but my approach was to create an OpenApiSerializerExtension that overrides map_serializer to return the schema dict generated by pydantic. The problem with this is that the pydantic schema contains its own referenced schema definitions. I wrote some awkward code that moves those definitions to the AutoSchema registry and it works at first, but the cached version of the schema is missing those definitions.

Is there a way to force the inclusion of my own components when using the cache or is there maybe a better way to achieve this?

This is what I'm doing now:
```py
class FixTaskSchema(OpenApiSerializerExtension):
    target_class = 'tasks.api.serializers.TaskSerializer'

    @staticmethod
    def update_refs(schema, ref_map):
        for key in schema.keys():
            if type(schema[key]) == dict:
                FixTaskSchema.update_refs(schema[key], ref_map)
            elif type(schema[key]) == list:
                for entry in schema[key]:
                    if type(entry) == dict:
                        FixTaskSchema.update_refs(entry, ref_map)
            elif key == '$ref' and schema[key] in ref_map:
                schema[key] = ref_map[schema[key]]

    def map_serializer(self, auto_schema: openapi.AutoSchema, direction):
        schema = TaskSchema.schema()
        schema_definitions = schema.get('definitions')
        if schema_definitions:
            ref_map = {}
            for key in schema_definitions.keys():
                component = ResolvedComponent(key, ResolvedComponent.SCHEMA, schema_definitions[key], True)
                auto_schema.registry.register_on_missing(component)
                ref_map[f'#/definitions/{key}'] = component.ref['$ref']
            del schema['definitions']
            FixTaskSchema.update_refs(schema, ref_map)
        return schema
```

**Comment by tfranzel** [comment]
sounds interesting. I once played with the idea myself.

> I wrote some awkward code that moves those definitions to the AutoSchema registry and it works at first, but the cached version of the schema is missing those definitions.

you lost me there. What do you mean by cached?

> Is there a way to force the inclusion of my own components when using the cache or is there maybe a better way to achieve this?

`auto_schema.registry` is the global registry. everything added with `register_on_missing` should show up in the schema. 

What you are doing there looks fairly reasonable to me. What exactly is the problem then?

**Comment by RasmusAntons** [comment]
The problem is that the first time I request the schema after starting the server it works, but when I request it a second time it's missing the components I created with register_on_missing.

**Comment by tfranzel** [comment]
I see. It is important to know that every schema request starts with a clean slate, i.e. the registry is empty.

I have not completely understood `update_refs`, but is all this running every time `map_serializer` is called? 

is `schema.get('definitions')` cached? are you modifying a cached value there? is that `if schema_definitions` statement only run the first time round?

**Comment by RasmusAntons** [comment]
`schema.get('definitions')` should return the same dictionary each time. `update_refs` is just used to translate the references from `#/definitions/something` which is what pydantic generates to `#/components/schema/something`. I'll have to test this again but I assumed that the schema for my `TaskSerializer` is cached and `map_serializer` isn't called at all after the first request.

**Comment by tfranzel** [comment]
`map_serializer` is indeed called only once, but that is for each schema generation. A fresh registry instance is created for each request (`SchemaGenerator.__init__`)

When we see a component a second time (in the scope of one schema request), we re-use the already generated component. That is true.

**Comment by tfranzel** [comment]
I can only guess that that `if` statement only runs the first time. Otherwise it has to show up in the second run also.

**Comment by RasmusAntons** [comment]
Oops you're right, the caching issue was in pydantic. Should've checked earlier but I was sure it just gave me the full schema every time. I found a function that circumvents caching, turns out the `update_refs` wasn't even necessary since pydantic has a `ref_prefix` parameter.

Thanks for your help, this is what worked in the end:
```py
class FixTaskSchema(OpenApiSerializerExtension):
    target_class = 'tasks.api.serializers.TaskSerializer'

    def map_serializer(self, auto_schema: openapi.AutoSchema, direction):
        schema = pydantic.schema.model_schema(TaskSchema, ref_prefix='#/components/schemas/')
        schema_definitions = schema.get('definitions')
        if schema_definitions:
            for key in schema_definitions.keys():
                component = ResolvedComponent(key, ResolvedComponent.SCHEMA, schema_definitions[key], True)
                auto_schema.registry.register_on_missing(component)
            del schema['definitions']
        return schema
```

**Comment by tfranzel** [comment]
Please have a look at #1006 and #1021. In the interim, we fixed 3 roadblocks for using extensions with non-DRF classes ( e.g. Pydantic). Not sure how you got this to fully work without those fixes on a recent spectacular version, but you should definitely update and have a look at the PR.

cheers.
