### ISSUE TITLE
SafeString causes yaml.representer.RepresenterError for SpectacularAPIView and SpectacularRedocView

### ISSUE THREAD

**Issue by fancydancing** [tfranzel/drf-spectacular#802]
We use `format_html("somestring")` as `help_text` in some of our models which returns an object of `django.utils.safestring.SafeString` type.

`SpectacularAPIView` and `SpectacularRedocView` both fail to build schema for these models, failing with the same error:
`yaml.representer.RepresenterError: ('cannot represent an object', 'somestring')`

`SpectacularSwaggerView` handles this object properly and does not produce any errors.

I have found the related issue in the [drf-yasg](https://github.com/axnsan12/drf-yasg/issues/159) project. Maybe this could help.

**Comment by tfranzel** [comment]
great catch! YAML will bail on unknown classes. Added a representener for the `SafeString` class.

> SpectacularSwaggerView handles this object properly and does not produce any errors.

probably because it request the schema in JSON? This should fail for both Redoc and Swagger if schema is requested as a YAML.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
