### ISSUE TITLE
How can we specify a global header/parameter?

### ISSUE THREAD

**Issue by jerinpetergeorge** [tfranzel/drf-spectacular#804]
I want to add the following header information to all my endpoints.

```python
OpenApiParameter(
    name="accept-language",
    type=str,
    location=OpenApiParameter.HEADER,
    description="`fa` or `en`. The default value is en",
)
```
I've managed to do this by adding a custom [post-processing hook](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks)
```python
def post_hook__add_global_header(result, generator, request, public):
    header_scheme = {
        "in": "header",
        "name": "accept-language",
        "schema": {"type": "string"},
        "description": "`fa` or `en`. The default value is en",
    }
    paths = result["paths"]
    for path, path_conf in paths.items():
        for method, method_conf in path_conf.items():
            if "parameters" in method_conf:
                method_conf["parameters"].append(header_scheme)
            else:
                method_conf["parameters"] = [header_scheme]
    return result
```

I feel this solution is a bit sloppy, do we have any other way to obtain a better result?

**Comment by tfranzel** [comment]
Yes you have. You can subclass `drf_spectacular.openapi.AutoSchema` and override `get_override_parameters()`.  This will provide a base for further decoration.  This does basically the same as you did, but you have a bit more control and utilities at your disposal.

**Comment by jerinpetergeorge** [comment]
Great, thanks.

For those who are coming here for the solution, here is what I have written
```
# somefile.py
from drf_spectacular.openapi import AutoSchema as _AutoSchema

from drf_spectacular.utils import OpenApiParameter


class AutoSchema(_AutoSchema):
    global_params = [
        OpenApiParameter(
            name="accept-language",
            type=str,
            location=OpenApiParameter.HEADER,
            description="`fa` or `en`. The default value is en",
        )
    ]

    def get_override_parameters(self):
        params = super().get_override_parameters()
        return params + self.global_params


# settings.py
REST_FRAMEWORK = {
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "core.drf_spectacular.hooks.AutoSchema",
}
```

**Comment by tfranzel** [comment]
thats exactly what I meant. This is the recommended way of augmenting functionality not covered by the existing settings. This has the added benefit of having the option to dynamically add stuff depending on `self.path`/`self.view`/`self.method`
