### ISSUE TITLE
Is it possible to customize OpenAPI schema of the 3rd party package views?

### ISSUE THREAD

**Issue by ahmetfarukyilmaz** [tfranzel/drf-spectacular#805]
Hi, I use https://github.com/wagnerdelima/drf-social-oauth2 for oauth2 and social authentication for my app but I want to customize the request and responses that are shown in the OpenAPI schema. Is it possible to do it without touching the source code of the package?

**Comment by tfranzel** [comment]
Hi,

absolutely! That is the whole point of our extension system: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions 

Have a look at our shipped extensions for other 3rd party libraries: https://github.com/tfranzel/drf-spectacular/tree/master/drf_spectacular/contrib

The extensions you can write behave exactly the same as the shipped ones. No change to drf-spectacular or the 3rd party library required. All you need to do is make sure the python interpreter loads those extension classes and they will register themselves.

**Comment by ahmetfarukyilmaz** [comment]
Great! Thanks for the quick response.

**Comment by MariaMozgunova** [comment]
And if I have a `ModelSerializer`, where the model is the model from 3rd party package? And then on this custom serializer, I have a field, which is a function on the 3rd party model.

Like this:
```
class CustomModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = Model  # model from 3rd party package
        fields = ["fun"]  # Model has a function fun
```

How can I customize the return value for that function?

The most straightforward way is to make a field into `serializers.SerializerMethodField`:
```
@extend_schema_field(OpenAPITypes.BOOL)
def get_fun(self, obj):
    return obj.fun()
```

But I was wondering if there is any better solution.
