### ISSUE TITLE
How to Generate Docs for Comma Separated query param.

### ISSUE THREAD

**Issue by nikhilbadyal** [tfranzel/drf-spectacular#808]
I have a query param  in my URL like 
`myUrl?status=1,2,3,4`. 
And I have defined this field like 
```
status = CharacterSeparatedField(
        child=serializers.ChoiceField(choices=[1, 2, 3, 4, 5, 6]),
        required=False,
        allow_null=True,
    )
```
CharacterSeparatedField is a custom serializer that looks like this.

```
class CharacterSeparatedField(serializers.ListField):
    """Character separated ListField.

    A field that separates a string with a given separator into a native
    list and reverts a list into a string separated with a given
    separator.
    """

    def __init__(self, *args, **kwargs):
        self.separator = kwargs.pop("separator", ",")
        super().__init__(**kwargs)

    def to_internal_value(self, data):
        data = data.split(self.separator)
        return super().to_internal_value(data)

    def get_value(self, dictionary):
        # We override the default field access in order to support
        # lists in HTML forms.
        if html.is_html_input(dictionary):
            # Don't return [] if the update is partial
            if self.field_name not in dictionary:
                if getattr(self.root, "partial", False):
                    return empty
            return dictionary.get(self.field_name)

        return dictionary.get(self.field_name, empty)

    def to_representation(self, data):
        data = super().to_representation(data)
        return self.separator.join(data)
```

For this Swagger Ui is generated like 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/59223300/189543183-b27c0022-93be-401a-8431-b7614e280070.png">

and the generated Request URLs are like
<img width="484" alt="image" src="https://user-images.githubusercontent.com/59223300/189543117-b358ce4d-ecc4-46da-bc8f-e6274ed918d2.png">

How can I generate it like 
`myUrl?status=1,2,3,4`. 

Normally [this ](https://stackoverflow.com/questions/50538138/swagger-take-one-or-more-values-from-enum)can be done

**Comment by tfranzel** [comment]
Hi, in theory we do support extensions for custom list serializers, but you are not using a `ListSerializer` but instead a `ListField`, which is quite similar but still different. If that were a custom `ListSerializer`, you would write a custom `OpenApiSerializerExtension` and specify your custom list behavior. Secondly we currently only support `ListSerializer` extensions on the outermost serializer, i.e. not on a field. That would be the second blocker. 

By default query param arrays are `style=form explode=True`, but your example is `style=form explode=False`.

https://swagger.io/docs/specification/serialization/

It looks like you are putting your serializer in the parameters directly in `@extend_schema(parameters=[XSerializer])`. That is perfectly fine, but given the complexity to model your case in a  generic way, I would recommend overriding that one parameters by hand with 

```python
@extend_schema(parameters=[
    XSerializer, 
    OpenApiParameter('status', type=int, many=True, style="form", explode=False, enum=[1,2,3])
])
```

which should do the trick, while leaving the other parameters unchanged.

**Comment by nikhilbadyal** [comment]
It worked. But I can also send values that are not supported like `9` in the case. It was that status field can only have `1,2,3`. It not get restricted though.
<img width="180" alt="image" src="https://user-images.githubusercontent.com/59223300/190688603-6149fb29-d228-473d-b879-ed2f50f4e689.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/59223300/190688363-e116160f-246e-4969-8f98-f4b0db94c8bc.png">
