### ISSUE TITLE
Support TypedDict in older python via typing_extensions

### ISSUE THREAD

**Issue by dk-mi** [tfranzel/drf-spectacular#819]
Thank you for this very useful program.

I have been trying to incorporate drf-spectacular into a large codebase on python 3.6. I encountered a failure to resolve a `typing_extensions.TypedDict` type hint and noticed that adding something like
```python
    ...
    elif hasattr(typing, 'Literal') and origin is typing.Literal:
        # python >= 3.8
        schema = {'enum': list(args)}
        if all(type(args[0]) is type(choice) for choice in args):
            schema.update(build_basic_type(type(args[0])))
        return schema
    elif hasattr(typing, 'TypedDict') and isinstance(hint, typing._TypedDictMeta):
        return build_object_type(
            properties={
                k: resolve_type_hint(v) for k, v in typing.get_type_hints(hint).items()
            }
        )

    # Fallback for python <3.8 using typing_extensions
    try:
        import typing_extensions
        if hasattr(typing_extensions, 'TypedDict') and isinstance(hint, typing_extensions._TypedDictMeta):
            return build_object_type(
                properties={
                    k: resolve_type_hint(v) for k, v in typing.get_type_hints(hint).items()
                }
            )
        elif hasattr(typing_extensions, 'Literal') and origin is typing_extensions.Literal:
            schema = {'enum': list(args)}
            if all(type(args[0]) is type(choice) for choice in args):
                schema.update(build_basic_type(type(args[0])))
            return schema
    except ImportError:
        pass
    ...
```
to `plumbing.resolve_type_hint` resolves my problem. Unless there are reasons why this would be bad, I can work on a PR for this.

**Comment by tfranzel** [comment]
Hi @dk-mi,

thanks! would you mind providing your versions (`py/Django/DRF/typing-extensions`) and a stacktrace?

the tests do pass for the supported 3.6 versions

```
py36-django2.2-drf3.10
py36-django2.2-drf3.11
```

I have not fully understood the problem yet, but I'm pretty certain that 

```python
elif hasattr(typing, 'Literal') and origin is typing.Literal:
```
will break the tests as we do a conditional import for different python versions. We do not specify a minimal version for `typing-extensions` (which we maybe should), so maybe your problem goes away if you update that dependency?

**Comment by dk-mi** [comment]
Apologies, I didn't pay attention to my versions (I was on drf-spectacular 0.17). Such a fallback is already there after bumping drf-spectacular and typing-extensions, and it Just Works. Thanks.
