### ISSUE TITLE
Contact in spectacular settings renders 'URL' instead of name provided

### ISSUE THREAD

**Issue by mugane-dj** [tfranzel/drf-spectacular#822]
```
    'CONTACT': {
        "name": "Email",
        "url": "email@domain.io"
    },
```
![Screenshot from 2022-09-28 16-49-59](https://user-images.githubusercontent.com/85606106/192797409-e16f4f7a-66f9-47aa-8bef-13799ea3e805.png)

**Comment by tfranzel** [comment]
```python
    "CONTACT": {
        'name': "Foo Bar",
        'url': "https://foo.com",
        'email': "foo@example.com",
    }
```

![image](https://user-images.githubusercontent.com/13507857/192816040-94f43110-79f6-4c74-a014-24c2a9366d7a.png)

looks ok to me but it would be an issue for redoc anyway as this has very little to do with spectacular.
