### ISSUE TITLE
Unable to use serializer extensions to indicate a `None` field

### ISSUE THREAD

**Issue by awbacker** [tfranzel/drf-spectacular#823]
I have written a custom hidden field, based off the DRF hidden field.  For those curious, just reads from the serializer context to add to `attrs`. Since this field is part of a shared package, I am separating the `drf_spectacular` code and making it optional, so this means using extensions.  

For consistency with all fields, I was hoping to keep all my overrides as extensions.  

The following both work as expected:
```
@extend_schema_field(OpenApiTypes.NONE)
class HiddenContextField(Field):
    ...

# in separate file file (or call set_override() directly
extend_schema_field(OpenApiTypes.NONE)(HiddenContextField)
```

There does not appear to be a way to do this using the `OpenApiSerializerFieldExtension` point.  Returning `None` causes a crash, and I am curious if there is a reason for this not being supported here, or if a change would be welcomed?

```
class HiddenContextFieldExtension(OpenApiSerializerFieldExtension):
    def map_serializer_field(self, auto_schema, direction):
        return None # same as build_basic_type(OpenApiTypes.NONE)

>>> File "drf_spectacular/plumbing.py", line 462, in append_meta
    return safe_ref({**schema, **meta})
TypeError: 'NoneType' object is not a mapping
```

This follows naturally from the code, which checks the schema extensions **after** it checks for the overrides:

```
def _map_serializer_field(self, field, direction, bypass_extensions=False):
    meta = self._get_serializer_field_meta(field, direction)
    if has_override(field, 'field'):
        override = get_override(field, 'field')
        if is_basic_type(override):
            schema = build_basic_type(override)
            if schema is None:
                return None     # <== perfect, causes the field to be totally ignored
        ...

    serializer_field_extension = OpenApiSerializerFieldExtension.get_match(field)
    if serializer_field_extension and not bypass_extensions:
        schema = serializer_field_extension.map_serializer_field(self, direction)
        if serializer_field_extension.get_name():
            ...
        else:            
            return append_meta(schema, meta)  # <== raises the error, schema is None
    ...
```

Would a PR be accepted that does one of the following 2 changes?

```
    if serializer_field_extension and not bypass_extensions:
        schema = serializer_field_extension.map_serializer_field(self, direction)
        if serializer_field_extension.get_name():
            ...
+++     elif schema is None:
+++         return None  # causes entire field to be dropped
        else:            
            return append_meta(schema, meta)  
```

```
+++      elif schema is None:
+++         raise Exception(
+++             "%s.map_serializer_field() returned None.\n"
+++             "If you want this field to be ignored you can annotate the field:\n"
+++             ">>> @extend_schema_field(None)\n"
+++             ">>> class %s(...):"
+++             ">>>    ..." % (
+++                 serializer_field_extension.__class__.__name__,
+++                 field.__class__.__name__
+++             )
+++         )
```

**Comment by tfranzel** [comment]
Hi @awbacker,

yes that looks like an oversight. There is no reason, as far as I can remember, for not allowing this.

```diff
+++     elif schema is None:
```

that looks reasonable, however I think it should come first and the `if serializer_field_extension.get_name():` after that.

Regarding your second diff, I have not understood where and why.

A PR would be appreciated. Ideally with a regression test.

Just as a sidenote. Why haven't you derived your field from the hidden field `class CustomField(HiddenField)`? I believe that should have been caught by spectacular already, but I have probably not fully grasped what you did there.

**Comment by awbacker** [comment]
Thanks for the feedback.  I'll make a PR for the first, and see about a test.

The 2nd diff just tries to raise a descriptive error, in the case that the extension point was not meant to return `None`.  If the user did it accidentally, as I did, that way you'd get a message telling you have to possibly fix it, if it was a mistake.

**Comment by awbacker** [comment]
As for the "why" on the class not inheriting from hidden field:

That is where I started, actually.  I found it doesn't work for `partial_update`, since that relies on `default=...`, and `get_default()` then in this case.  That automatically marks the field not required, which is then skipped since it is `partial` and missing from validated_data.  Basically, i have  required field in a `partial_update` since this is not _really_ a field, but a convenience. 

I may spend more time trying to understand better.  This does what I need right now, The full field is:

```
class HiddenContextField(Field):
    """
    Populates a field in validated_data by reading from serializer.context
    """

    def __init__(self, key, **kwargs):
        super().__init__(write_only=True, **kwargs)
        self.context_key = key

    def get_value(self, dictionary):
        try:
            return self.context[self.context_key]
        except KeyError:
            raise Exception(...)

    def to_internal_value(self, data): # required implementation
        return data

class MySerializer(...):
    thing = HiddenContextField("thing")

class MyViewSet(...):
    ...
    def get_serializer_context(self):
        return {
            **super().get_serializer_context(),
            "thing": self.get_thing() # this is reused in other viewset logic
        }
```

For more back story, all this exists because I'm doing nested routes with manual path kwargs, since the errors I'm required to return mean I can't simply do a 404 if there is a mismatch, as would happen with nested serializers/routers.

**Comment by tfranzel** [comment]
> As for the "why" on the class not inheriting from hidden field:

I see. makes sense. that kind of stuff is the nitty gritty DRF knowledge.

> The 2nd diff just tries to raise a descriptive error, 

when we will add the `None` option, we officially support it. For some people annotation is not an option, hence the extensions. Having an exception for something that might not be doable seems wrong. I think there is no need for it, once we support it imho.

**Comment by tfranzel** [comment]
I think we should be done here. thx @awbacker
