### ISSUE TITLE
@extend_schema has no effect on GET/retrieve extra actions in a ModelViewSet 

### ISSUE THREAD

**Issue by cantus-firmus** [tfranzel/drf-spectacular#824]
DRF v3.11.1
drf-spectacular v0.15.0

When adding an extra `GET` action (not merely overriding `create` or `retrieve`) in a `ModelViewSet` and decorating it with `@extend_schema`, the specified request serializer is not represented as a `component` in the generated schema. 

In the example below, the `search/` endpoint shows up under `paths`, but the fields under `SearchRequestSerializer` are not included under `components/schemas`.  Changing the action to a `POST` method instead of a `GET` resolves the issue, but I believe the method really should be a `GET`.

Example View and method:
```
  class MyObjectViewSet(viewsets.ModelViewSet):

    http_method_names = ['get', 'post']
    serializer_class = MyObjectSerializer

    
    @sensitive_variables('access_token')
    @extend_schema(
        request=SearchRequestSerializer,
        responses={
            (200,'application/gzip'): OpenApiTypes.BINARY,
            401: OpenApiResponse(response=GeneralResponseSerializer),
            404: OpenApiResponse(response=GeneralResponseSerializer)
        },
    )
    @action(detail=False, methods=['GET'])
    def search(self, request):
      data = SearchRequestSerializer(data=self.request.query_params)
      data.is_valid(raise_exception=True)

      ...

      return response
```

Excerpt from the generated schema (as a GET):
```
paths:
/api/documents/search/:
    get:
      operationId: documents_search_retrieve
      tags:
      - documents
      security:
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/gzip:
              schema:
                type: string
                format: binary
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: null
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: null
```
Excerpt from the generated schema (if I change it to a POST):
```
  /api/documents/search/:
    post:
      operationId: documents_search_create
      tags:
      - documents
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SearchRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SearchRequest'
        required: true
      security:
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/gzip:
              schema:
                type: string
                format: binary
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: null
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: null

...

components:
  schemas:
    SearchRequest:
      <details from the SearchRequest serializer>

```

I would expect a `component`called `SearchRequest` to be included in the schema, along with the field metadata defined in `SearchRequestSerializer`. 

I realize I may be misunderstanding the expected behavior here. If so, I could really use a pointer in the right direction.

**Comment by tfranzel** [comment]
> drf-spectacular v0.15.0

that is severely outdated. we are at 0.24.2

> When adding an extra GET action (not merely overriding create or retrieve) in a ModelViewSet and decorating it with @extend_schema, the specified request serializer is not represented as a component in the generated schema.

Some methods (DELETE, GET, HEAD) do not "officially" support bodies. The HTTP standard says providing a body there is undefined behavior. 

>    A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

(https://www.rfc-editor.org/rfc/rfc7231#section-4.3.1)

**Also, OpenAPI 3.0.3 straight up prohibits it.** OpenAPI 3.1 will allow it but we do not support that yet. Generally, it is a design smell and most seasoned devs will encouraged you to not do that. You will likely break caching and potentially proper handling of reverse proxies. tl;dr don't do it.

**Comment by cantus-firmus** [comment]
Thanks for the reply. Updating to a newer release of drf is in our roadmap.

I'm struggling a little bit with your advice with regard to the message body. I don't believe I am including a body with the GET request- rather, my request looks like this:

```
GET /path/search/?var1=value1&var2=value2&access_token=123hjkl123hjkl HTTP/1.1
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 2a7fe4f2-f9cb-4d89-b202-292269dfd830
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: http://domain.com/path/search/?var1=value1&var2=value2&access_token=123hjkl123hjkl
Host: domain.com
```

To access these variables from the ViewSet, I use the following: `self.request.query_params`. For @extend_schema, is the the `request` intended only to apply to form parameters?

I really appreciate your time and response.

**Comment by tfranzel** [comment]
> I'm struggling a little bit with your advice with regard to the message body. I don't believe I am including a body with the GET request- rather, my request looks like this:

I must have misunderstood because of the way you used `extend_schema` and framed the question.

`requestBody` is the is the actual body for e.g. a `POST` request. That has nothing to do with request parameters and those are put in a [different location](https://github.com/tfranzel/drf-spectacular/blob/2cef14d55cda2a3537809a11bf027bba901d97f2/tests/test_basic.yml#L55). `@extend_schema(request=...)` is for the request body only. **You probably want to use** `@extend_schema(parameters=[SearchRequestSerializer])`

Here is an example for a exploded serializer. Ignore the nested case for now but notice you can add more parameters with `OpenApiParameter`. Straight up putting a serializer in the list is basically a shorthand for exploding the fields into separate parameters.

https://github.com/tfranzel/drf-spectacular/blob/2cef14d55cda2a3537809a11bf027bba901d97f2/tests/test_extend_schema.py#L160-L166

 Does that answer your question?

**Comment by tfranzel** [comment]
> Thanks for the reply. Updating to a newer release of drf is in our roadmap.

you can update spectacular regardless. Our latest version supports `DRF>=3.10.4` which is clearly the case for your DRF version.

**Comment by cantus-firmus** [comment]
Yes it does- thank you very much! I didn't understand the distinction between the `request` and `parameters` args and how they correlate to the HTTP structures. 

I assumed versions would be more tightly coupled, but I'll go ahead and update in my dev environment today.

Thanks for your help!
