### ISSUE TITLE
how to customize the request or requestBody for POST/PUT request in @extend_schema for OpenAPI 3 file

### ISSUE THREAD

**Issue by pshk04** [tfranzel/drf-spectacular#834]
We are required to customize the Create/Update request for our project, below is the request body:

  ```
    "data": 
        {
        "type": "collection",
        "attributes": {
          "emailId": "peter@gmail.com",
          "fname": "peter",
          "lname": "king",
        },
        "links": {
            "books": { 
                "data": [
                    {   
                        "kind": "book",
                        "id": "100"
                    }
                ]
            }
        },
```

Below is what I tried:

```
@extend_schema(
operation_id="author_update",
        description="Update author",
           request={
                'data': {
                            "type": "author",
                            "attributes": {
                                "emailId": {"type": "string", "format": "email"},
                                "fname": {"type": "string"},
                                "lname": {"type": "string"},
                            },
                            "links": {
                                "books": {
                                    "data": {
                                        "type": "books",
                                        "id": {"type": "string"},
                                    }
                                }
                            }
                }
        },
        parameters=[
            OpenApiParameter("id", OpenApiTypes.STR, OpenApiParameter.PATH),
        ],
        methods=["put"],
        responses={
            200: OpenApiResponse(
                response=SimpleSerializer, description="Author data is Updated"
            ),
            403: OpenApiResponse(
                response=None,
                description="Forbidden, Author update failed",
            ),
            412: OpenApiResponse(response=None, description="Precondition Failed"),
        },
)
def update_author(self, request):
```

I'm okay if anyone can post a basic example. Thank you!

**Comment by tfranzel** [comment]
Do you have a serializer for that data? Your `@extend_schema` looks way to complicated overriding the defaults. What exactly is the problem here?

**Comment by pshk04** [comment]
The body mentioned above is for a PUT request. In order to obtain the above request body structure in the swagger UI, I had to complicate the request argument in the @extend_schema decorator.

Serializer:

   class AuthorSerializer(serializers.HyperlinkedModelSerializer):
    """ Author
    """

    fname = serializers.CharField()
    lname = serializers.CharField()
    books = BookSerializer(source="bookId", read_only=True)
    is_active = serializers.BooleanField(required=False)
    last_publish = serializers.DateTimeField(read_only=True)
    authorId = serializers.CharField(source="id", default=None, read_only=True)
    emailId = serializers.EmailField()

    

    included_serializers = {
        "book": BookSerializer,
    }

Is there a way to simplify this requirement?

**Comment by pshk04** [comment]
@tfranzel Please let me know for any suggestions. Thanks

**Comment by Keivan-Mi** [comment]
Does it work for you? I want to put dict inside the request field instead of a serializer but the swagger UI doesn't show it in the request section.

**Comment by Cloverxue** [comment]
I also have the problem

**Comment by tfranzel** [comment]
I have trouble understanding the question exactly. All I can say is 

* `@extend_schmea(request={})`: that raw dict must an actual OpenAPI schema, not an example.
* generally the use of raw schema is not advisable, unless you know what you are doing.
* I think this is answered in the FAQ with https://drf-spectacular.readthedocs.io/en/latest/faq.html?highlight=envelope#how-do-i-wrap-my-responses-my-endpoints-are-wrapped-in-a-generic-envelope

I'll close this. If anyone is interested open a new issue.
