### ISSUE TITLE
Add Code Samples to Documentation

### ISSUE THREAD

**Issue by moluwole** [tfranzel/drf-spectacular#836]
Awesome work on this library guys. Really a life saver.. 

On another note, I'll like to add Code Samples to my Django Endpoints in order to show how to make the requests in multiple ways (curl, python requests, php). Something like what we have here: https://redocly.github.io/redoc/#tag/pet/operation/addPet

![image](https://user-images.githubusercontent.com/23439463/195542038-90efd504-bea2-4390-a53b-bb359839db3d.png)

Is there any way to achieve this?

**Comment by tfranzel** [comment]
thx!

so you can do this but it's gonna be a lot of work. redoc doesn't generate that info automatically and also that feature depends on extensions. 

have a look at the spec for your link (https://redocly.github.io/redoc/openapi.yaml) and search for `x-codeSamples` 

Here is how to get that with spectacular:

https://github.com/tfranzel/drf-spectacular/blob/edab4be1b1499cb032bab09e87ee9eeb3a1f61e1/tests/test_specification_extensions.py#L63-L80

**Comment by moluwole** [comment]
This is really helpful @tfranzel. I can confirm that this works. Thanks
