### ISSUE TITLE
Dataclass Extension does not avoid serializer name collisions

### ISSUE THREAD

**Issue by ford-carta** [tfranzel/drf-spectacular#839]
**Describe the bug**
This is how we `get_name` for a Dataclass Serializer
`self.target.dataclass_definition.dataclass_type.__name__`
This will lead to collisions when you have multiple dataclasses with the same name or different serializers that use the same dataclass as the base
**To Reproduce**
```py
class MySerializer(DataclassSerializer):
    class Meta:
        dataclass = MyDataclass
class MyOtherSerializer(DataclassSerializer):
    my_field = serializers.CharField()
    class Meta:
        dataclass = MyDataclass
```
Issue: There is no collision avoidance when it comes to using dataclass serializers.

**Expected behavior**
I'm not sure how collisions are avoided with normal serializers (I think a postfix of some kind is applied), but I would expect a similar collision avoidance scheme to be used if the extension is unable to provide a unique component name.

Some ideas:
1. Prefix with some combination of the dataclass module, the serializer module, the serializer name, the serializer ref name
2. Generate some unique postfix if the name is already present
3. Allow support for ref_name in Dataclass itself, or dataclass serializer (currently ignored)
4. Add a get unique name field to the OpenApiDataclassSerializerExtensions and let the extension determine how to get a unique name for the component

**Comment by ford-carta** [comment]
cc @oxan

**Comment by ford-carta** [comment]
Here is my current workaround, which is unideal 
```
MyNamespacedDomain = MyDomain
MyNamespacedDomain.__name__ = "MyNamespacedDomain"
```

**Comment by oxan** [comment]
I agree this is less than ideal behaviour. 

From a quick look, it looks like by default components are named after the serializer classname, so that automatically guards against name collisions (as long as they are in the same module). The drf-dataclasses extension deviates from that and names components after the dataclass (because drf-dataclasses is often implicitly or explicitly used in "anonymous" mode, where it has no user-defined serializer class), but that can introduce clashes as you've experienced. Thus, this problem seems to be introduced by and specific to the drf-dataclasses extension, and it probably doesn't make sense to introduce a generic solution for this.

I suspect the simplest solution is for the extension to check whether the name is already used for a different serializer class, and use some kind of deduplicating scheme in that case. Since this problem only applies when using user-defined serializer classes, we always have a sensible serializer classname available, and we can just use that. In fact, we might as well do that by default for user-defined serializers, though that'll be a backward compatibility break as component names might change.

@tfranzel Does that sound like a good approach? What's your opinion on the backward compatibility break?

**Comment by ford-carta** [comment]
I think using the serializer name, in non-anonymous mode, makes a lot of sense. If we are in anonymous mode, we could revert back to the dataclass name. That would fix the majority of the issues here.

**Comment by ford-carta** [comment]
Still though, I think its worth considering implementing a more generic deduping scheme in the case that we have
 two serializers with the same name or two different data classes with the same name (my org is running into the latter issue)

**Comment by ford-carta** [comment]
cc @tfranzel Bumping this guy

**Comment by ford-carta** [comment]
cc @tfranzel hello! mind sharing a few thoughts, happy to post a PR with your permission

**Comment by ford-carta** [comment]
@tfranzel 🙏 https://github.com/tfranzel/drf-spectacular/issues/839#issuecomment-1292544845

**Comment by tfranzel** [comment]
Sry @ford-carta but this was no simple answer and so I had to set aside extra time.

> Issue: There is no collision avoidance when it comes to using dataclass serializers.

There is no collision avoidance for Serializer either. We only have collision avoidance for the [enum postprocessing hook](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/hooks.py#L13).

As a matter of fact this is more complicated to do consistently than meets the eye. That much I learned writing that avoidance. The discovery order may matter and you can't just fix an added class as we don't know which one was there first. So for avoidance you must change names of *all* affected classes that share a collision, which might break e.g. a generated client. For that exact reason we emit warnings/errors if serializer collisions are detected, leaving it to the user to come up with a sensible resolution.

> Thus, this problem seems to be introduced by and specific to the drf-dataclasses extension, and it probably doesn't make sense to introduce a generic solution for this.

I think so too.

> though that'll be a backward compatibility break as component names might change.

Yes, that would be a problem and we need to make a very strong argument for that.

I got to admit that I am not a user of this library and so I have not thoroughly considered all cases in depth or rather in what different ways this library can be used. 

Aside from a breaking change, I think it would make sense to consider `Meta.ref_name` as a name override as we do this also for regular serializers. I see no harm in supporting this, and it would be more consistent imho.

As for changing the default naming scheme, I will look into `djangorestframework-dataclasses` more thoroughly and get a more informed opinion. I don't want to change it haphazardly.

And now that I think about it, nested dataclasses is probably another shortcoming of the current implementation.

**Comment by tfranzel** [comment]
@oxan Can you help me understand why you chose to use the dataclass name instead of the Serializer name as basis? 

You must have had a reason for this. I can't really remember and #639 did not jump start my memory either.

**Comment by oxan** [comment]
> @oxan Can you help me understand why you chose to use the dataclass name instead of the Serializer name as basis?

Honestly, I don't remember it either. Part of it might be that the motivation behind the extension was that people using drf-dataclasses in anonymous mode were getting components named just "Dataclass", and reporting bugs for that. 

> Aside from a breaking change, I think it would make sense to consider `Meta.ref_name` as a name override as we do this also for regular serializers. I see no harm in supporting this, and it would be more consistent imho.

Sounds sensible to me.

> And now that I think about it, nested dataclasses is probably another shortcoming of the current implementation.

I think they just get named after the innermost class, which is not ideal but will probably work most of the time.

**Comment by tfranzel** [comment]
>> And now that I think about it, nested dataclasses is probably another shortcoming of the current implementation.

> I think they just get named after the innermost class, which is not ideal but will probably work most of the time.

Nevermind. This already works quite well imho. I thought this case was covered.


> Honestly, I don't remember it either. Part of it might be that the motivation behind the extension was that people using drf-dataclasses in anonymous mode were getting components named just "Dataclass", and reporting issues about that.

Yes, exactly that was the reasons. I think using the serializer name for explicit usages and `dataclass` name for anonymous usages feels inconsistent and potentially buggy. Thus, imho the current implementation makes the most sense.

Added 2 mechanims for review:

```python
    class GroupSerializer2(DataclassSerializer):
        class Meta:
            dataclass = Group
            ref_name = "CustomGroupNameFromRefName"
```

and 

```python
    @extend_schema_serializer(component_name='CustomGroupNameFromDecoration')
    @dataclass
    class Group2:
        name: str
        leader: Person
        members: typing.List[Person]
```

Let me know what you think @oxan @ford-carta

**Comment by oxan** [comment]
> Yes, exactly that was the reason. I think using the serializer name for explicit usages and `dataclass` name for anonymous usages feels inconsistent and potentially buggy. Thus, imho the current implementation makes the most sense.

That's reasonable.

> Let me know what you think @oxan @ford-carta

Both look good to me!

**Comment by ford-carta** [comment]
Thanks for working on this! Really helped out my team. Our schema 23k lines long, we love the tool. We implemented a view decorator to do DDD like Fast API
```py
  @exposed()
  def post(self, request, body: BodyDomain, query_params: QueryParamsDomain) -> List[ResponseDomain]
      # return domain object, serialization boilerplate taken care of
```
