### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jairhenrique** [tfranzel/drf-spectacular#84]
**Describe the bug**
After update to 0.9.7 I receive `403 Forbidden` on `swagger-ui` view.

On my rest_framework settings I have:

```python
"DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
 ]
```

And in `SPECTACULAR_SETTINGS`

```python
"SERVE_PERMISSIONS": ['rest_framework.permissions.AllowAny']
```
---
Schema view works.

**Comment by tfranzel** [comment]
thank you that was an oversight on my part. testing with mocked settings is tricky so this case was not tested.

i fixed it slighly different. can you confirm that it works?

**Comment by jairhenrique** [comment]
@tfranzel that's works!
