### ISSUE TITLE
operation_id in Swagger-UI

### ISSUE THREAD

**Issue by creyD** [tfranzel/drf-spectacular#844]
Is there a way to show the operation_id in the Swagger-UI? If yes how would one go about this? We are migrating from drf_yasg to drf_spectacular currently and are curious, as the code generators use this id, so it would be pretty useful to see.

**Comment by creyD** [comment]
Yes this is possible, just not very visibly documented:```
 'SWAGGER_UI_SETTINGS': {
        'displayOperationId': True,
    },
``` is the setting I was looking for.

**Comment by tfranzel** [comment]
hi, this is a swagger-ui setting. we just pass it through:

```python
SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_SETTINGS": """{
        deepLinking: true,
        displayOperationId: true,
    }""",
}
```

> Yes this is possible, just not very visibly documented:

yes. it is in the swagger-ui doc. no point for us in duplicating their doc

**Comment by tfranzel** [comment]
please refer to https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/ for additional settings
