### ISSUE TITLE
Unable to determine how to add parameter with multiple types

### ISSUE THREAD

**Issue by Crateros** [tfranzel/drf-spectacular#845]
I have been reading over the docs looking for information or examples regarding support for query params that can conform to more than one type. For example:
```
OpenApiParameter('id', [OpenApiTypes.INT, OpenApiTypes.UUID], OpenApiParameter.QUERY, required=True,
            description='The item ID',
            examples=['123', 'c30bef26-afd5-4233-abaa-a2318ed65bf2']
        )
```
`id` query param can be an integer or a UUID in this example. But I am not seeing how to properly annotate this or how to provide multiple examples (1 for INT and one for UUID).

I was hoping a list of types and examples would provide multiple types and a dropdown containing the examples, but the resulting spec file only shows the first type and 1 example. I do not see any support for the `oneOf` syntax mentioned in the OpenAPI spec docs.

Overall I am enjoying the package, thank you so much for the contributions!

**Comment by tfranzel** [comment]
hi @Crateros, we do not have a dedicated feature for that. so a list is not a valid argument, the type hints should indicate that much. however, you can drop down to a raw schema in those instances.

```python
OpenApiParameter('id', {"oneOf": [{"type": "integer"}, {"type": "string", "format": "uuid"}]}, ...)
```

**Comment by Crateros** [comment]
@tfranzel thank you!
