### ISSUE TITLE
Swagger/Redoc Sidecar breaks when using a Manifest storage backend

### ISSUE THREAD

**Issue by axieum** [tfranzel/drf-spectacular#847]
**Introduced by** #718 

**Describe the bug**

The `swagger-ui-dist/` directory is not a static file but rather a directory resulting in the following error when using the manifest storage backend. A manifest storage backend will suffix files with a hash, meaning static concatenation will not work, it needs to use `{% static 'file.css' %}` tag.

> Missing staticfiles manifest entry for 'drf_spectacular_sidecar/swagger-ui-dist'.

Affected code:

https://github.com/tfranzel/drf-spectacular/blob/f8b9c1b9134fb9e04bdca023c2f15640626feedf/drf_spectacular/views.py#L116-L117

https://github.com/tfranzel/drf-spectacular/blob/f8b9c1b9134fb9e04bdca023c2f15640626feedf/drf_spectacular/views.py#L174-L182

https://github.com/tfranzel/drf-spectacular/blob/f8b9c1b9134fb9e04bdca023c2f15640626feedf/drf_spectacular/views.py#L252-L255

**To Reproduce**

```py
# https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-STATICFILES_STORAGE
# https://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
```

**Expected behavior**

For it to only query `{% static 'file.css' %}` instead of directories.

**Comment by tfranzel** [comment]
This hasn't been forgotten, just didn't have the time yet.

Given that `static` may work on a file basis only (e.g. adding a hash suffix), probably the right course of action is refactoring the current calls so that they are only executed on literal files and not on path prefixes anymore.

I would appreciate a PR, though I would kindly ask to make the change as minimally invasive as possible.

**Comment by demisgech** [comment]
**Issue:** `collectstatic` fails due to missing source map file from `drf_spectacular_sidecar`

When running `python3 manage.py collectstatic --noinput`, the process fails with the following error:

```
ValueError: The file 'drf_spectacular_sidecar/redoc/bundles/redoc.standalone.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x76e4dc6fcc80>.
```

**Context:**
The `drf_spectacular_sidecar` package includes a JavaScript file (`redoc.standalone.js`) that contains a reference to its source map (`redoc.standalone.js.map`). During static files collection, Django's `ManifestStaticFilesStorage` attempts to process and hash these referenced files, but the `.map` file appears to be missing from the package.

**Impact:**
- Prevents successful deployment as `collectstatic` cannot complete
- Blocks the static file collection process
- Affects any environment using `ManifestStaticFilesStorage`

**Error Log:**
```
python3 manage.py collectstatic --noinput
Post-processing 'drf_spectacular_sidecar/redoc/bundles/redoc.standalone.js' failed!

Traceback (most recent call last):
  File "/home/yohannes/projects/django_projects/deboethiopia/manage.py", line 22, in <module>
    main()
  ...
  File "/home/yohannes/snap/code/225/.local/share/virtualenvs/deboethiopia-GQNuMGyB/lib/python3.12/site-packages/django/contrib/staticfiles/storage.py", line 145, in hashed_name
    raise ValueError(
ValueError: The file 'drf_spectacular_sidecar/redoc/bundles/redoc.standalone.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x76e4dc6fcc80>.
```

**Comment by dheitzer** [comment]
still broken in 2026

**Comment by axieum** [comment]
> still broken in 2026

Is this in reference to this original issue or the comment from @demisgech?

This issue has been closed as resolved, I'd suggest opening a new issue. 😊

**Comment by demisgech** [comment]
I was able to resolve this issue by switching the Django Cloudinary configuration in the installed apps/settings configuration.

After adjusting the `cloudinary_storage` and related Django static/media settings, `collectstatic` completed successfully and the missing manifest/staticfiles error was resolved.

However, I still noticed a few related issues around static asset handling and configuration consistency, so I’ll continue investigating and update here if I find a cleaner or more stable solution.
```py
# ... other settings config
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'debug_toolbar',
    'rest_framework',
    'django_filters',
    'djoser',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',
    'core',
    'operations',
    'contents',
    'engagements',
    'insights'
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'Debo Ethiopia API',
    'DESCRIPTION': 'API documentation for Debo Ethiopia Media and Operations.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',  # Use the sidecar assets
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

# Cloudinary Credentials
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
    "SECURE":env("CLOUDINARY_SECURE") or True,
    "UPLOAD_PRESET":env("CLOUDINARY_UPLOAD_PRESET"),
    'IMG_TRANSFORMATION': {
        'width': 1200,          # Resize to a max width
        'height': 1200,         # Resize to a max height
        'crop': 'limit',        # Don't upscale small images
        'quality': 'auto',      # Smart compression
        'fetch_format': 'auto', # Serves WebP to Chrome, etc.
    },
}

# Tells Django to use Cloudinary for all Media files
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
# To satisfy the Cloudinary storage package requirements(for backward compatibility)
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

MEDIA_URL = "/media/"
```
