### ISSUE TITLE
How to enable https scheme for urls?

### ISSUE THREAD

**Issue by MrMika96** [tfranzel/drf-spectacular#848]
Hello, i`m trying to go from drf_yasg to drf-spectacular and i have a question:
Is there a way to enable https for your urls, in drf_yash it was done like this:
```python
class APISchemeGenerator(SchemaGenerator):
    def get_schema(self, request=None, public=False):
        if not request:
            print("NET")
        try:
            schema = super().get_schema(request, public)
        except Exception as e:
            print(e)
            return e
        schema.schemes = ['http', 'https'] # this allows me to use http and https for my requests
        if not LOCAL:
            schema.base_path = '/api/'
        return schema
```

**Comment by tfranzel** [comment]
Hi, I think by default the schema will use `http` or `https` depending in how you serve your schema/UI. If you want to deviate from the way you serve the schema itself, you may need to use the `servers` settings. This should give you a dropdown in the UI

```python
SPECTACULAR_SETTINGS = {
    "VERSION": "0.0.1",
    "TITLE": "Your API",
    "DESCRIPTION": "your desc",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVERS": [{"url": "http://yourserver"}, {"url": "https://yourserver"}] # <-----
}
```

**Comment by MrMika96** [comment]
So there is no way to do something like this?
<img width="1424" alt="Снимок экрана 2022-11-03 в 13 50 27" src="https://user-images.githubusercontent.com/47847377/199702544-d5ac827d-7ad4-4861-8063-8471432e5dc7.png">
<img width="1433" alt="Снимок экрана 2022-11-03 в 13 52 07" src="https://user-images.githubusercontent.com/47847377/199702766-477b9dc3-899e-4f46-bb5e-fa2a06c543dc.png">

**Comment by tfranzel** [comment]
I see. It looks like this is a difference between OpenAPI 2/3. the `scheme` option apparently went away in favor of `servers`

> In OpenAPI 3.0, you use the servers array to specify one or more base URLs for your API. servers replaces the host, basePath and schemes keywords used in OpenAPI 2.0.

https://swagger.io/docs/specification/api-host-and-base-path/

Not sure if we can do anything about that, given that we only support OpenAPI 3.

**Comment by tfranzel** [comment]
I mean you can get roughly the same outcome, but you have to provide the actual server URL. Though that information might be easily retrieved, given your django settings. likely an f-string that utilizes your `hosts` setting.

**Comment by MrMika96** [comment]
Ok, thank you for answers, i will try to come up with something for that case

**Comment by MrMika96** [comment]
Hello again, i was able to do what i needed with protocols. The documentation says that if your servers variable in empty 'url' will be set to '/' by default, so i just added variables and scheme selector appeared.
```python
'SERVERS': [{'url': '{protocol}:/', 'variables': {'protocol': {'enum': ['http', 'https'], 'default': 'https'}}}]
```

![image](https://user-images.githubusercontent.com/47847377/200242910-6fb2dcaf-72d3-4fc9-9e90-5b8090f249d3.png)
