### ISSUE TITLE
Unable to guess serializer on apidoc schema endpoint

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#849]
**Describe the bug**
drf-spectacular complains, that it's unable to guess serializer for `/api/schema` endpoint which returns the schema for the apidoc

**To Reproduce**
* Add to `urls.py`
  * ```py
    path("api/schema", SpectacularAPIView.as_view(), name="schema")
    ```
* Go to `localhost:8001/api/schema`
* Error entry in Django console:
  * `Error #107: schema: unable to guess serializer. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. Ignoring view for now. `

`"SERVE_INCLUDE_SCHEMA": False` has been overridden, but changing it back to `True` does not seem to make a difference

**Comment by tfranzel** [comment]
Seems to me that you are making the wrong connection. `SpectacularAPIView` is properly decorated and has been for a long while. It is unlikely that this would come this late, given that almost every user does this. Maybe that error message is referring to some other endpoint you have. `SERVE_INCLUDE_SCHEMA` "not working" is another indicator that this references some other view of yours.

**Comment by HansAarneLiblik** [comment]
Regarding `SERVE_INCLUDE_SCHEMA`, I meant that changing this value does not remove the error 😅

You're right actually - I have another endpoint
```py
path("/<entity:path>/schema", views.schema, name="entity-schema")
```
and while the `"name"` is different, drf-spectacular still says `Error #0: schema: unable to guess serializer`.

Sorry about the trouble!
