### ISSUE TITLE
Paginating one action on a Viewset

### ISSUE THREAD

**Issue by creyD** [tfranzel/drf-spectacular#851]
**Describe the bug**
I am paginating one action of my GenericViewset, but not another. On the GenericViewset itself I provide `pagination_class = None` and on the action I provide a different pagination. `drf_spectacular` doesn't paginate both views. In `drf_yasg` I did supply an autoschema.

**To Reproduce**
- Create a GenericViewset
- Add ListModelMixin and `pagination_class = None`
- Add custom action with a pagination

**Expected behavior**
I would like the swagger to represent pagination correctly.

**Comment by creyD** [comment]
@tfranzel Could you please take a look?

**Comment by tfranzel** [comment]
As far as I know, this works.

https://github.com/tfranzel/drf-spectacular/blob/f8b9c1b9134fb9e04bdca023c2f15640626feedf/tests/test_regressions.py#L1203
https://github.com/tfranzel/drf-spectacular/blob/f8b9c1b9134fb9e04bdca023c2f15640626feedf/tests/test_regressions.py#L1182

The test only cover the reverse case, but I'm pretty sure your case works too.

The pagination class is dormant for non-list responses. You need to signal the action returns a list with a `@extend_schema(responses=XSerializer(many=True))`. The list property is undefined for actions (we default to non-list) and thus you need to explicitly state that it is a list, and then pagination will work as expected.

fyi detail is irrelevant here: https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-m-using-action-detail-false-but-the-response-schema-is-not-a-list

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
