### ISSUE TITLE
A library serializer `__init__` calls `kwargs['context']['request']` - how to skip/ignore?

### ISSUE THREAD

**Issue by chrispreee** [tfranzel/drf-spectacular#853]
**Describe the bug**
We use a package called `django_comments_xtd`. In it, `django_comments_xtd.api.serializers.ReadCommentSerializer.__init__` calls `self.request = kwargs['context']['request']`. How can I work round this or simply skip introspection of this class?

```
from drf_spectacular.plumbing import get_lib_doc_excludes as original_get_lib_doc_excludes

def get_lib_doc_excludes():
    from django_comments_xtd.api import serializers as comment_serializers
    from django_comments_xtd.api import views as comment_views

    return (
        original_get_lib_doc_excludes()
        + [getattr(comment_serializers, c) for c in dir(comment_serializers) if isclass(c)]
        + [getattr(comment_views, c) for c in dir(comment_views) if isclass(c)]
    )

SPECTACULAR_SETTINGS = {
    "GET_LIB_DOC_EXCLUDES": "path.to.above.build_docs.get_lib_doc_excludes",
}
```

**To Reproduce**
pip install django_comments_xtd
./manage.py spectacular --file openapi.yml

**Expected behavior**
I need a way of skipping this serializer. I have tried returning the class from a custom `get_lib_doc_excludes`, or all of the package's view classes. I have tried to figure out a way with `OpenApiSerializerExtension`. I have even tried monkey-patching. Apologies if I missed something.

**Comment by tfranzel** [comment]
Hi,

`get_lib_doc_excludes` only removes discovered docstrings from serializers/views, not the classes themselves.

Are you using the most recent version? https://github.com/tfranzel/drf-spectacular/commit/8e9bc23991126afd4a00103da135db0ac22ad91e introduced a mock context including request. This was further extended for lists with https://github.com/tfranzel/drf-spectacular/commit/1358493045ffd54c07b94304a9db0f7a5097649b but that second part is not released yet.

So in theory that error should go away with the current version and if not with the current master. Though there might be corner cases I am not aware of.

`OpenApiSerializerExtension` would be another route that can bypass the constructor. Not sure why this is not working for you.

Another option is using the schema generation signal. You can use https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-get-queryset-depends-on-some-attributes-not-available-at-schema-generation-time in ``__init__`` and early exit when schema generation is detected.

**Comment by chrispreee** [comment]
I am using 0.24.2, the reason the context stub is not working is because the serializer is being initialized by line 99 of plumbing.py:

def get_list_serializer(obj):
    return force_instance(obj) if is_list_serializer(obj) else get_class(obj)(many=True)

The instantiation `(many=True)` after `get_class` needs the context kwarg too, ie, `(many=True, context=build_serializer_context(view))`. I experimented adding a `view` parameter to `get_list_serializer` and passing it from the schema `self.view` and got much further, but I suspect there is a cleaner approach.

**Comment by chrispreee** [comment]
Apologies, I am trying to work off your example patches for packages, but getting nowhere.

```
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"

    def map_serializer(self, auto_schema, direction):
        class Fixed(self.target_class):
            def __init__(self):
                pass

        return auto_schema._map_serializer(Fixed, direction)

# raises AttributeError: 'Fixed' object has no attribute 'parent'

class Fix2(OpenApiViewExtension):
    target_class = "django_comments_xtd.api.views.ToggleFeedbackFlag"

    def view_replacement(self):
        from common.openapi import CustomDrfSpectacularSchema

        class Fixed(self.target_class):
            schema = CustomDrfSpectacularSchema()

        return Fixed

# Raises AssertionError: Incompatible AutoSchema used on View <class 'django_comments_xtd.api.views.CreateReportFlag'>
```

Is there something I'm missing? Huge thanks.

**Comment by tfranzel** [comment]
> I am using 0.24.2, the reason the context stub is not working is because the serializer is being initialized by line 99 of plumbing.py - exactly the subject of your second unreleased commit.

I'll try to release as soon as I find the time the clear a couple of remaining todos. Does it mean that this particular issue would be solved then?

> Fix1

Your `__init__ pass` breaks DRF, as it skips the vital boilerplate in the background. You need to call the DRF constructor from one (two for the fix)  level up, i.e. `super(ReadCommentSerializer, self).__init__(*args, **kwargs)`

> Fix2

That looks ok as far as I can tell. This is a bug in django_comments_xtd. They should have used the `AutoSchema` class from the DRF settings instead of hardcoding. 

But the extensions should work like that. The error is from another view though. They have done this twice. Is this error persisting when you fix both `ToggleFeedbackFlag` and `CreateReportFlag`?

**Comment by chrispreee** [comment]
Amazing help, thank you very much indeed.

`CustomDrfSpectacularSchema` is indeed derived from `drf_spectacular.openapi.AutoSchema`, and is has been working fine for months. Problems only arose when we added the `django-comments-xtd` package (and when we tried to use `operation_id_base`).

`django-comments-xtd` are using vanilla `AutoSchema` explicitly because they want to provide the `operation_id_base` `__init__` parameter for the toggle and create flag views. We've had a few of these in our internal code I've just had to remove. Might be nice to shadow this in `drf-spectacular`, although I haven't seen how this ends up in the openapi spec so I may be mistaken.

Having fixed the `__init__` override (sorry, that was a dumb oversight), I am now getting a new missing context error.

```
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 1502, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 886, in _map_serializer
    schema = serializer_extension.map_serializer(self, direction)
  File "/usr/src/app/fdw/settings/build_docs.py", line 67, in map_serializer
    return auto_schema._map_serializer(Fixed, direction)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 882, in _map_serializer
    serializer = force_instance(serializer)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 81, in force_instance
    return serializer_or_field()
  File "/usr/src/app/fdw/settings/build_docs.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_comments_xtd/api/serializers.py", line 263, in __init__
    self.request = kwargs['context']['request']
KeyError: 'context'
```

I am not sure how to cleanly get the context from the serializer class, so just changed line 81 of `plumbing.py` to:

```python
return serializer_or_field(context={"request": "dummy"})
```

and got through a full run. Would the right answer be to pass `self.view` into `force_instance` then make the above `return serializer_or_field(context=build_serializer_context(view))`?

My full django_comments_xtd patch is now (thanks very much):

```python
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"

    def map_serializer(self, auto_schema, direction):
        class Fixed(self.target_class):
            def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)

        return auto_schema._map_serializer(Fixed, direction)


class Fix2(OpenApiViewExtension):
    target_class = "django_comments_xtd.api.views.ToggleFeedbackFlag"

    def view_replacement(self):
        from common.openapi import CustomDrfSpectacularSchema

        class Fixed(self.target_class):
            schema = CustomDrfSpectacularSchema()

        return Fixed


class Fix3(OpenApiViewExtension):
    target_class = "django_comments_xtd.api.views.CreateReportFlag"

    def view_replacement(self):
        from common.openapi import CustomDrfSpectacularSchema

        class Fixed(self.target_class):
            schema = CustomDrfSpectacularSchema()

        return Fixed
```

**Comment by tfranzel** [comment]
> django-comments-xtd are using vanilla AutoSchema explicitly

exactly and that destroys the flexibility intended by DRF.

> Fix1

your fix is doing nothing. it calls the default init, removing your init would have exactly the same outcome. You need to call the grandparent instead of the parent (default). The goal is to bypass that offending line. Try this instead:

```diff
- super().__init__(*args, **kwargs)
+ super(self.target_class, self).__init__(*args, **kwargs)
```

which call the `ModelSerializer` init instead of the `ReadCommentSerializer` init. 

It is **VERY** rarely the case that you need to patch something in spectacular's internals. The extensions system should provide all the tools necessary. At least that is the design goal.

**Comment by chrispreee** [comment]
I am really sorry, and extremely grateful, there is something I am still missing.

The following code is hit, but the class is not replaced. None of the commented attempts worked either, nor did monkey patching.

```python
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"

    def map_serializer(self, auto_schema, direction):
        from django_comments_xtd.api.serializers import ReadCommentSerializer

        # class Fixed(ReadCommentSerializer):
        class Fixed(self.target_class):
            def __init__(self, *args, **kwargs):
                super(ReadCommentSerializer, self).__init__(*args, **kwargs)
                # super(self.__class__.__mro__[1], self).__init__(*args, **kwargs)
                # kwargs["context"] = {"request": {"GET": "dummy"}}
                # super().__init__(*args, **kwargs)
                # serializers.ModelSerializer.__init__(self, *args, **kwargs)

        # if hasattr(ReadCommentSerializer, "__init__"):
        #     # delattr(ReadCommentSerializer, "__init__")
        return auto_schema._map_serializer(Fixed, direction)
```

**Comment by tfranzel** [comment]
ahh i think i see it now. are you subclassing that `ReadCommentSerializer`? By default `OpenApiSerializerExtension` will not trigger on subclasses of `target_class`  prevent unwanted triggers. you have to enable this explicitly

```python
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"
    match_subclasses = True

    def map_serializer(self, auto_schema, direction):
        ...
```

**Comment by chrispreee** [comment]
We are getting closer! `Fixed` is a subclass of the `ReadCommentSerializer` so probably triggers the exclusion. However I now get an infinite recursion, suggesting that the class is patched repeatedly, perhaps?

```python
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"
    match_subclasses = True

    def map_serializer(self, auto_schema, direction):
        from django_comments_xtd.api.serializers import ReadCommentSerializer

        class Fixed(self.target_class):
            def __init__(self, *args, **kwargs):
                super(ReadCommentSerializer, self).__init__(*args, **kwargs)

        return auto_schema._map_serializer(Fixed, direction)
```

```
    return auto_schema._map_serializer(Fixed, direction)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 886, in _map_serializer
    schema = serializer_extension.map_serializer(self, direction)
  File "/usr/src/app/fdw/settings/build_docs.py", line 89, in map_serializer
    return auto_schema._map_serializer(Fixed, direction)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 886, in _map_serializer
    schema = serializer_extension.map_serializer(self, direction)
  File "/usr/src/app/fdw/settings/build_docs.py", line 68, in map_serializer
    class Fixed(self.target_class):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 312, in __new__
    attrs['_declared_fields'] = cls._get_declared_fields(bases, attrs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 303, in _get_declared_fields
    base_fields = [
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 304, in <listcomp>
    (visit(name), f)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 300, in visit
    known.add(name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by tfranzel** [comment]
Since you are also running on subclasses due to `match_subclasses = True`m the extension will also trigger on `Fixed`, which will create an infinite loop. Use `auto_schema._map_serializer(Fixed, direction, bypass_extensions=True)` to break the cycle.

**Comment by chrispreee** [comment]
Huge thanks for your perseverance, that was why my monkey patching wasn't working.

The standard approach didn't work though - with the below, `ReadCommentSerializer.__init__` still raised error `KeyError: 'context'`:

```python
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"
    match_subclasses = True

    def map_serializer(self, auto_schema, direction):

        class Fixed(self.target_class):
            def __init__(self, *args, **kwargs):
                from django_comments_xtd.api.serializers import ReadCommentSerializer
        
                kwargs["context"] = {"request": {"GET": "dummy"}}
                super(ReadCommentSerializer, self).__init__(*args, **kwargs)

        return auto_schema._map_serializer(Fixed, direction, bypass_extensions=True)
```

Full stack trace:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 58, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 94, in get_operation
    operation['responses'] = self._get_response_bodies()
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 1275, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/openapi.py", line 1359, in _get_response_for_code
    is_list_serializer_customized(serializer)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 105, in is_list_serializer_customized
    and get_class(get_list_serializer(obj)).to_representation  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/plumbing.py", line 99, in get_list_serializer
    return force_instance(obj) if is_list_serializer(obj) else get_class(obj)(many=True) #, context=obj.context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_comments_xtd/api/serializers.py", line 263, in __init__
    self.request = kwargs['context']['request']
KeyError: 'context'
```

So drf-spectacular still seems to be introspecting the unaffected class.

What does work however is a monkey-patch, which will do for now:

```python
class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"
    match_subclasses = True

    def map_serializer(self, auto_schema, direction):
        from django_comments_xtd.api.serializers import ReadCommentSerializer

        def init_patch(self, *args, **kwargs):
            super(ReadCommentSerializer, self).__init__(*args, **kwargs)

        ReadCommentSerializer.__init__ = init_patch
        return auto_schema._map_serializer(ReadCommentSerializer, direction, bypass_extensions=True)
```

I am essentially just (ab)using the extension to get something run after Django is set up but before the introspection management command.

**Comment by tfranzel** [comment]
This was bugging me, because it was supposed to work. Took me a moment to understand. 

- Your Fix1 will likely break the library as you change the actual class.
- If you comment out Fix1, it will work on the current master branch. It contains the bugfix that is required here. Fixing `__init__` in the extension is only half the solution and thus does not work.
- However, you want a Fix1 as there are other warnings. It will work on the master branch without the extension, but if the extensions is present, it also needs to contain the `__init__` fix for some stupid reason I just discovered.

Here is my proposal. I confirmed this on **drf-spectacular@master** and it has 0 warnings/errors:

```python
from typing import Optional

from drf_spectacular.extensions import (
    OpenApiSerializerExtension, OpenApiViewExtension, OpenApiSerializerFieldExtension
)
from drf_spectacular.openapi import AutoSchema
from drf_spectacular.plumbing import build_object_type, build_basic_type
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import extend_schema_field, extend_schema
from rest_framework import serializers


class Fix1(OpenApiSerializerExtension):
    target_class = "django_comments_xtd.api.serializers.ReadCommentSerializer"
    match_subclasses = True

    def map_serializer(self, auto_schema, direction):
        from django_comments_xtd.api.serializers import ReadCommentSerializer

        class Fixed(self.target_class):
            def __init__(self, *args, **kwargs):
                super(ReadCommentSerializer, self).__init__(*args, **kwargs)

            def get_user_moderator(self, obj) -> Optional[bool]:
                pass

            def get_comment(self, obj) -> str:
                pass

            def get_allow_reply(self) -> bool:
                pass

            @extend_schema_field(OpenApiTypes.URI)
            def get_user_avatar(self):
                pass

            @extend_schema_field(OpenApiTypes.URI)
            def get_permalink(self):
                pass

            @extend_schema_field(OpenApiTypes.DATETIME)
            def get_submit_date(self):
                pass

        return auto_schema._map_serializer(Fixed, direction, bypass_extensions=True)


class Fix2(OpenApiViewExtension):
    target_class = "django_comments_xtd.api.views.ToggleFeedbackFlag"

    def view_replacement(self):
        class Fixed(self.target_class):
            schema = AutoSchema()

        return Fixed


class Fix3(OpenApiViewExtension):
    target_class = "django_comments_xtd.api.views.CreateReportFlag"

    def view_replacement(self):
        class Fixed(self.target_class):
            schema = AutoSchema()

        return Fixed


class Fix4(OpenApiViewExtension):
    target_class = "django_comments_xtd.api.views.preview_user_avatar"

    def view_replacement(self):
        class PreviewUserAvatar(serializers.Serializer):
            url = serializers.URLField(read_only=True)
            email = serializers.EmailField(write_only=True)

        fixed = extend_schema(request=PreviewUserAvatar, responses=PreviewUserAvatar)(
            self.target_class
        )
        return fixed


class Fix5(OpenApiSerializerFieldExtension):
    target_class = "django_comments_xtd.api.serializers.ReadFlagField"

    def map_serializer_field(self, auto_schema, direction):
        return build_object_type(
            properties={
                "flag": build_basic_type(OpenApiTypes.BOOL),
                "user": build_basic_type(OpenApiTypes.OBJECT),  # TODO can be improved
                "id": build_basic_type(OpenApiTypes.UUID),
            }
        )

```

**Comment by tfranzel** [comment]
you also may want to use 

```python
SPECTACULAR_SETTINGS = {
    'PREPROCESSING_HOOKS': ['drf_spectacular.hooks.preprocess_exclude_path_format'],
}
```

to exclude the duplicated format endpoints.

**Comment by chrispreee** [comment]
Amazing thank you. Have updated my pip requirement to last commit on master:

```
git+https://github.com/tfranzel/drf-spectacular.git@3292d9db957aaa60ccfeb8e14d91ac9ab42d4110
```

Will post back here once this is released (will be version of drf-spectacular after 0.24.2).

I can break packages as we only ever use `drf-spectacular` as a management command (as our API is too large to introspect live), and I only apply these fixes then, but forgot this is not standard usage.

Enormous thanks for sticking with this, your help is very much appreciated, and I've learned several useful new things.

**Comment by tfranzel** [comment]
> I gather the extension isn't a wholesale replacement of the class then, given even with the init fix it still raises the context KeyError on 0.24.2.

Well, it is kind of. It is a wholesale replacement in the context of schema generation. (no changes to real view that is serving requests). 

However, we currently do init the original class to check for some meta info prior to generating the schema from the replacement class. That is the reason for the error. If we wouldn't check for `is_list_serializer_customized` by the user, there would be no prior usage. Not exactly sure thought if that is fixable.
