### ISSUE TITLE
Annotate SlugRelatedField when field is a UUID

### ISSUE THREAD

**Issue by kaimcpheeters** [tfranzel/drf-spectacular#854]
This is related to [Annotate SlugRelatedField](https://github.com/tfranzel/drf-spectacular/issues/15) but specific to when the field is a UUID. 

With the below model example, is it possible to annotate that the SlugRelatedField is a UUID rather than a just a string?

```
class TagSerializer(serializers.ModelSerializer):
    """Serializer for Tags"""
    workspace = serializers.SlugRelatedField(slug_field='uuid',  queryset=Workspace.objects.all(),)
    tag = serializers.UUIDField(source='uuid', read_only=True)

    class Meta (object):
        model = Tag
        fields = ('workspace', 'tag', 'name')
```

In the workspace view the schema specifies the workspace field to be a UUID
` workspace | string <uuid>`

In the tag  view the schema specifies the workspace field to only be a string (through the SlugRelatedField)
`workspace | string`
 `tag  | string <uuid>`

**Comment by tfranzel** [comment]
Hi, as I tried to convey in the other issue,  the `SlugRelatedField` field is by definition a plain string. At least that is my understanding of what DRF is intending. Departing from that may require some decorator trickery.

You can override the type of that field by using `extend_schema_field`. This is usually meant to be used as a decorator but also works in those rarer cases. You can then provide (among other things) a custom raw schema that fits your needs. 

```python
class TagSerializer(serializers.ModelSerializer):
    """Serializer for Tags"""
    workspace = extend_schema_field(field={'oneOf': [{'type': 'string'}, {'type': 'string', 'format': 'uuid'}]})(
        serializers.SlugRelatedField(slug_field='uuid', queryset=Workspace.objects.all())
    )

    tag = serializers.UUIDField(source='uuid', read_only=True)

    class Meta (object):
        model = Tag
        fields = ('workspace', 'tag', 'name')
```

**Comment by StopMotionCuber** [comment]
I'm having an API making extensive use of the `SlugRelatedField`. From the [documentation](https://www.django-rest-framework.org/api-guide/relations/#slugrelatedfield) I don't have the impression that a `SlugRelatedField` needs to always be a string. Instead, my understanding (and also my usage) is that we want to do something similar as with a `PrimaryKeyRelatedField`, but we don't want to use the PrimaryKey, but an arbitary field.

To obtain the correct type for a field, we can handle it similarly to a `PrimaryKeyRelatedField`, we would just need to append [here](https://github.com/tfranzel/drf-spectacular/blob/c70d20947abdaced78b6ab471af0f6d69674849c/drf_spectacular/openapi.py#L684) a `source.append(field.slug_field)`.

**Comment by tfranzel** [comment]
Looking at the doc, I may have been to quick to dismiss. The word slug usually means a string in the context of django, but given this, I think it is reasonable to look further. 

It seems that `SlugRelatedField` is the less strict cousin of `PrimaryKeyRelatedField` and that any unique field in the related model is a candidate for it.

I will have a look at this again.

**Comment by tfranzel** [comment]
I think this is actually quite neat, given that `SlugRelatedField` is simply a non-pk version of `PrimaryKeyRelatedField` after all.

@kaimcpheeters @StopMotionCuber I would appreciate if you could test PR #893
