### ISSUE TITLE
Automatic authentication in dev environment

### ISSUE THREAD

**Issue by nickdf-imrsv** [tfranzel/drf-spectacular#859]
Hi! Thank you for sharing such a useful library. You make my life easier every day.

Does `drf-spectacular` supply a way to programmatically automate authentication? Considering the following image:
![image](https://user-images.githubusercontent.com/98340233/201787013-c1c43352-9b73-41df-ae56-111f35b82989.png)

I would like to supply `<value>` and click `Authorize` (should say "authenticate"?) automatically in my dev environment. The only related documentation I've been able to find has been [`OpenApiAuthenticationExtension`](https://drf-spectacular.readthedocs.io/en/latest/customization.html?highlight=api_key#specify-authentication-with-openapiauthenticationextension) which relates to security _definitions_ rather than handling.

Is this already implemented? Outside the focus or scope of `drf-spectacular`? Thanks for your time :beers:

**Comment by nickdf-imrsv** [comment]
The multiple title edits were due to personal confusion; "authentication" and "authorization" appear to be used interchangeably across OpenAPI, DRF, and SwaggerUI documentation & UI.

**Comment by tfranzel** [comment]
Hi and thanks. OpenAPI itself does not have such a mechanism. It is merely a "declaration" of the API. This is more in the realm of swagger-ui than drf-spectacular. However, I think you can get close by funneling through some swagger configs:

```python
SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_SETTINGS": """{
        deepLinking: true,
        persistAuthorization: true,
        onComplete: function() {
            ui.preauthorizeApiKey("nodeAuth", "abcde12345");
        },
    }""",
}
```

If you want to do this only on dev you might need to come up with some more logic in `onComplete`.

https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
https://stackoverflow.com/a/50181701/2399008

> The multiple title edits were due to personal confusion; "authentication" and "authorization" appear to be used interchangeably across OpenAPI, DRF, and SwaggerUI documentation & UI.

yeah, it is not used in the text book way.

**Comment by nickdf-imrsv** [comment]
Thank you! :pray: I'll try to make use of this and will let you know if I discover anything useful.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by callumgare** [comment]
Using the `preauthorizeApiKey` function in `onComplete` I setup def-spectactular to automatically configure session cookie authentication if a user has logged in. Depending on your setup you might find this a useful way to reduce the need to manually configure authentication every time the docs are loaded without needing to hard code an API token.

https://github.com/tfranzel/drf-spectacular/issues/1099#issuecomment-1920345459
