### ISSUE TITLE
Is creating a schema.yml file obligatory?

### ISSUE THREAD

**Issue by fannyhub** [tfranzel/drf-spectacular#860]
this isn't probably a bug, just a question but I don't know where else to ask it. 
I have noticed that a brand new project (python3.9, django in docker container) with drf-spectacular configuration has a working SpectacularSwaggerView even if ./manage.py spectacular --file schema.yml has not been executed. So schema gets generated.
Could you explain it? Also please let me know if there is another place to ask such questions about your library :)

**Comment by tfranzel** [comment]
This is as intended.

`SpectacularSwaggerView` generates a fresh schema on every request. No previously generated `schema.yml` is used there.

`./manage.py spectacular --file schema.yml` is an alternate way of getting a schema without having to start a server and doing a HTTP request. This is usually used in build pipelines, when you need a schema to generate client code with `openapi-generator`.

You can also ask questions on stackoverflow with the `drf-spectacular` tag. Though I only look there occasionally.
