### ISSUE TITLE
Using TypeDict with djangorestframework_camel_case sets required fields to optional

### ISSUE THREAD

**Issue by saschametz** [tfranzel/drf-spectacular#861]
Hi, when using `TypeDict` in combination with the `drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields` hook all fields that are converted from snake_case to camelCase are set to optional.

Serializer:
```py
class RankData(TypedDict):
    value: int
    created_at: str
    name: str
    rank_by_value: bool


class RankSerializer(serializers.Serializer):
    rank_data = serializers.SerializerMethodField()

    def get_rank_data(self) -> RankData:
        return RankData(
            value=290,
            created_at="2022-01-01",
            name="Checkpoint A",
            rank_by_value=False,
        )
```

Settings:
```py
SPECTACULAR_SETTINGS = {
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields",
    ],
}
```

This produces the following schema:
![Screenshot 2022-11-16 at 08 54 12](https://user-images.githubusercontent.com/37977643/202120268-530eec86-011f-4fb4-b15e-6dec141fd568.png)

-> All names that are converted from snake_case to camelCase are set to optional.

Removing `"drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields"` from the settings produces the correct schema (all fields are required):
![Screenshot 2022-11-16 at 08 56 05](https://user-images.githubusercontent.com/37977643/202120659-f26fb537-6544-45fa-aa73-fa11528b2559.png)

**Comment by tfranzel** [comment]
Looks like the string replacement does not account for nested objects properly. It goes through the nested props properly, but it fails on nested required list.

**Comment by saschametz** [comment]
Thanks for the quick fix @tfranzel 
I can confirm it's working now.

**Comment by saschametz** [comment]
I just noticed one small issue. After adding a nested `child_rank` it doesn't convert to camelCase anymore. That's only the case when using `List[ChildRankData]`, but not `ChildRankData` (without a list).

Serializer:
```py
class ChildRankData(TypedDict):
    value: int
    created_at: str


class RankData(TypedDict):
    value: int
    created_at: str
    name: str
    rank_by_value: bool
    child_rank: List[ChildRankData]


class RankSerializer(serializers.Serializer):
    rank_data = serializers.SerializerMethodField()

    def get_rank_data(self) -> RankData:
        return RankData(
            value=290,
            created_at="2022-01-01",
            name="Checkpoint A",
            rank_by_value=False,
            child_rank=[ChildRankData(value=123, created_at="022-02-02")],
        )
```

Schema:
![Screenshot 2022-11-16 at 17 19 19](https://user-images.githubusercontent.com/37977643/202235270-04f0bc43-1067-4ea6-b554-005163247ee8.png)

**Comment by tfranzel** [comment]
did a drive-by bugfix that came to my attention. this should work now as expected.

**Comment by saschametz** [comment]
Everything works perfectly now 👍
