### ISSUE TITLE
RFC: Planning on removing schema support from django-filter. 

### ISSUE THREAD

**Issue by carltongibson** [tfranzel/drf-spectacular#862]
Hiya 👋 

I want to deprecate the schema generation in the next version of django-filter, rather pointing folks directly to drf-spectacular. 

https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#module-drf_spectacular.contrib.django_filters

I thought DRF was already pointing this way but I guess the docs PR never go made: https://github.com/encode/django-rest-framework/discussions/8453

Before I just do this, @tfranzel any concerns I need to consider? 

I plan to have `get_schema_operation_parameters` raise a deprecation warning saying "go use drf-spectacular", with a link, etc. 

Thanks 🎁

**Comment by tfranzel** [comment]
Hey Carlton,

thanks for the heads-up. 

> I thought DRF was already pointing this way but I guess the docs PR never go made: https://github.com/encode/django-rest-framework/discussions/8453

Yeah, sry about that. I never really found enough time to do it. It has been bugging me though.

I don't have any concerns. I just had a quick look at our code and I don't think we depend on anything non-essential in django-filter. Also, we implement our own `get_schema_operation_parameters` and so there shouldn't be any dependency there too. 

If you ping this issue with a RC commit/branch, I'll run the test suite to make sure nothing is broken.

**Comment by carltongibson** [comment]
@tfranzel Just FYI, I've released django-filter 23.2 which deprecated the schema related methods of the DRF Filter Backend. 
(They won't be removed until 25.1, so no rush)🤔

I'm going to close this I think.

**Comment by tfranzel** [comment]
Good stuff @carltongibson! I checked that we do not depend on those deprecations. All ready from our side.
