### ISSUE TITLE
Using nested field in resource_type_field_name while using PolymorphicProxySerializer

### ISSUE THREAD

**Issue by microHoffman** [tfranzel/drf-spectacular#863]
Hello, I'm wondering if it is possible to use attribute on nested object for `resource_type_field_name` while using `PolymorphicProxySerializer`? Minimal example here:

```py
class AssetType(Enum):
  ERC20 = "ERC20",
  ERC721 = "ERC721",
  ERC1155 = "ERC1155"

class AssetContract:
  category: AssetType
  ...

class Asset:
  contract: AssetContract
  ...

class ERC20Asset(Asset):
  ...

class NFTAsset(Asset):
  ...

@extend_schema_field(
    PolymorphicProxySerializer(
        component_name="SpecificAsset",
        serializers=[ERC20AssetSerializer, NFTAssetSerializer],
        resource_type_field_name="contract.category",  # <-- here I'd like to use "contract.category"
    )
)
class AssetSerializer(serializers.Serializer):

      def to_representation(self, instance):
        if isinstance(instance, ERC20Asset):
            return ERC20AssetSerializer(instance=instance).data
        elif isinstance(instance, NFTAsset):
            return NFTAssetSerializer(instance=instance).data
```

In the example above, I'd like to use `contract.category` as a `resource_type_field_name`, is it somehow possible please? I've tried `contract.category`, but it told me that the sub-serializer must contain the discriminator field "contract.category".

Thanks for any help!

**Comment by tfranzel** [comment]
Hi, in theory it would could possible but I doubt that OpenAPI 3 does support it. Never seen a dotted notation anywhere inside a schema. You could put anything you want in `resource_type_field_name` (in manual mode: `serializers={...}` not `[...]`). The question is if downstream tools gonna understand it (swagger-ui, openapi-generator). 

Why not just put the type field on `ERC20AssetSerializer` `NFTAssetSerializer`? This is how we do it usually.

https://github.com/tfranzel/drf-spectacular/blob/2aabb8b7c527f793aa71f483500d7ebcdd3b370e/tests/test_polymorphic.py#L43

**Comment by microHoffman** [comment]
Hey @tfranzel , thanks for the answer. Actually I've started using `django-typed-models` for a single-table-inheritance on asset models and it internally uses `type` field, so I will use that, as you also described. Thanks!:)
