### ISSUE TITLE
Add support for DRF >= 3.14.0

### ISSUE THREAD

**Issue by victorperezai** [tfranzel/drf-spectacular#865]
`NullBooleanField` was removed in `DRF 3.14.0` which affect `drf-spectacular` ( see [PR](https://github.com/encode/django-rest-framework/pull/8599) ). The latest `drf-spectacular,` or any previous releases for that matter are incompatible with `DRF>=3.14.0`. More specifically, `drf-spectacular` should stop using `NullBooleanField` as it's been deprecated in `DRF>=3.14.0` and start using `BooleanField` with `allow_null=True`.

I'm unaware wether there are further incompatibility issues with DRF >= 3.14.0 besides `NullBooleanField`.

**Comment by tfranzel** [comment]
> drf-spectacular should stop using NullBooleanField

Unfortunately it is not that easy as we need to support Django REST Framework (3.10.3, 3.11, 3.12, 3.13, 3.14). We do keep supporting it where it is available.

**Comment by victorperezai** [comment]
@tfranzel thanks will close. I am concerned now with dependency resolution. I had run `poetry update`, which bumped def to 3.14, but the drf-spectacular was not bumped to 0.24.x.

Is this something I should report somewhere else?

**Comment by victorperezai** [comment]
Got it! Appreciate the quick response. Keep up the good work 😄
