### ISSUE TITLE
Path to view on error or warning

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#866]
Not a bug, but rather a feature-request

When generating the schema and there are errors for some views, it is difficult to track down the view as there may be views with same name in multiple apps

`Error #0: task_list: unable to guess serializer. ...`

It would be really great, if the path to the `view` was also printed out, e.g. `url` from `self.path` or somehow the full filepath `myapp/views.py`

```
Error #0: task_list: unable to guess serializer. ... Ignoring view for now (myapp/app1/views.py)
...
Error #12: task_list: unable to guess serializer. ... Ignoring view for now (myapp/app4/views.py)
```

**Comment by HansAarneLiblik** [comment]
For me, covering just these 3 cases is enough (I edited your source locally for testing)

https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L870
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L1075
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L1133

**Comment by tfranzel** [comment]
Hey @HansAarneLiblik, that is an interesting suggestion. Certainly useful for people migrating and having lots of warnings.

The meat of the matter lies here:

https://github.com/tfranzel/drf-spectacular/blob/2aabb8b7c527f793aa71f483500d7ebcdd3b370e/drf_spectacular/drainage.py#L83

https://github.com/tfranzel/drf-spectacular/blob/2aabb8b7c527f793aa71f483500d7ebcdd3b370e/drf_spectacular/contrib/django_filters.py#L60

https://github.com/tfranzel/drf-spectacular/blob/2aabb8b7c527f793aa71f483500d7ebcdd3b370e/drf_spectacular/generators.py#L238

I'm open to suggestions on how to make this work.

**Comment by HansAarneLiblik** [comment]
I created a PR https://github.com/tfranzel/drf-spectacular/pull/868

Don't really know how I feel about the duplication of `_TRACES` logic though
