### ISSUE TITLE
ListAPIView wrapping examples issue

### ISSUE THREAD

**Issue by diego351** [tfranzel/drf-spectacular#872]
Hello! I'm having 2 response schemas for response, wanted to add examples to document error codes.

Wanted error code response example:

```
{
    "api_status_code": "DATE_PARSE_ERROR",
      "extra": {
        "details": "asdf"
      }
}
```

but in swagger-ui I'm getting wrapped my error code object with paginated schema within results key:

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/1809191/203841677-53f2ae70-ce08-4c31-853f-f1c725d81913.png">

```
class ExceptionSerializer(serializers.Serializer):
    api_status_code = serializers.CharField()
    extra = serializers.DictField(required=False)

@extend_schema_view(
    get=extend_schema(
        responses={
            200: OpenApiResponse(
                response=s.ArchiveListViewSerializer,
                examples=[],
            ),
            400: OpenApiResponse(
                response=ExceptionSerializer,
                examples=[
                    OpenApiExample(
                        "DATE_PARSE_ERROR",
                        value={"api_status_code": "DATE_PARSE_ERROR", "extra": {"details": "asdf"}},
                        status_codes=[400],
                        response_only=True,
                    )
                ],
            ),
        },
    )
)
class ArchiveListView(LoginRequiredMixin, ListAPIView):
    model = m.Archive
    serializer_class = s.ArchiveListViewSerializer
    pagination_class = LimitOffsetPagination

```

I checked what drf spectacular generates and the example is wrong.

```
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedArchiveListViewList'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
              examples:
                DATEPARSEERROR:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?offset=400&limit=100
                    previous: http://api.example.org/accounts/?offset=200&limit=100
                    results:
                    - api_status_code: DATE_PARSE_ERROR
                      extra:
                        details: asdf
                  summary: DATE_PARSE_ERROR
          description: ''

```

However the response schemas are looking good, it's all about example:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1809191/203842086-e9f2d801-03a4-444c-817b-0d7f8de3fa3f.png">

Can I get some help?

**Comment by tfranzel** [comment]
fixed a bug where example list detection was missing a condition which was present for response list detection.

your code contained a bit more stuff that was not really necessary, e.g.

```python          
200: OpenApiResponse(
   response=s.ArchiveListViewSerializer,
   examples=[],
),
# same as 
200: s.ArchiveListViewSerializer
```

noticed another bug though. `status_codes=[400],` was not supposed to be necessary when you already nest this under the `400` response. Will deal with this in a separate issue I think.

**Comment by diego351** [comment]
@tfranzel Just tested this and it's working beautifully!

**Comment by diego351** [comment]
> noticed another bug though. `status_codes=[400],` was not supposed to be necessary when you already nest this under the `400` response. Will deal with this in a separate issue I think.

I've seen that too. Do you want me to create an issue for this?

**Comment by tfranzel** [comment]
sure. please do
