### ISSUE TITLE
How Can I Set camelCase for drf-spectacular

### ISSUE THREAD

**Issue by chaule97** [tfranzel/drf-spectacular#877]
I read the document how to set camel case, it's just a guide to set 'CAMELIZE_NAMES': True in Settings. But It doesn't work

May you guide me? Thank you

**Comment by tfranzel** [comment]
I think the settings help text should have explained that sufficiently:

https://github.com/tfranzel/drf-spectacular/blob/b696cca339f792eb20ec0fe10e43795dcec99b91/drf_spectacular/settings.py#L124-L129

Full camelization has two components.

1. To camelize operationIds and parameter names: `'CAMELIZE_NAMES': True`
2. To camelize serializer component field names: 
    ```python
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
        'drf_spectacular.hooks.postprocess_schema_enums'
    ],
    ```

**Comment by chaule97** [comment]
Thank you so much
