### ISSUE TITLE
Specify JSON Schema for JSONFields

### ISSUE THREAD

**Issue by mateokurti** [tfranzel/drf-spectacular#879]
I have a few JSON Fields specified on one of my models. I have defined JSON Schemas for those fields, which I use to validate the data. I'd like to include those JSON Schemas on the OpenAPI schema generated by drf-spectacular. I know that it is possible to convert the JSON Schema to OpenAPI, but I was unable to find a way to do it with `drf-spectacular`. Is this supported somehow?

**Comment by tfranzel** [comment]
short answer: yes with `@extend_schema_field(MANUALSCHEMA)`

long answer: we currently generate OpenAPI 3.0.3 which is not fully JSON schema compliant. OpenAPI 3.1's biggest change is that is fully compliant now, but the tooling ecosystem has not caught up completely.

see this for reference: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-3-extend-schema-field-and-type-hints

you can drop down to manual by passing in a dict with your raw schema structure instead of a `Serializer` or `OpenApiTypes`

**Comment by tfranzel** [comment]
if you want to go even further in automating this, you may create a `JSONField` with a link to your schema that you use for validation and write a `OpenApiSerializerExtension` that does away with the decorator and does all this automatically via introspection.

**Comment by mateokurti** [comment]
Thank you for your quick answer, it was really helpful. Writing it manually is not a nice approach since the schema is large, is versioned and gets adjusted from time to time, but the second option you proposed looks quite interesting.

I searched for `OpenApiSerializerFieldExtension` and ended up [here](https://drf-spectacular.readthedocs.io/en/latest/customization.html?highlight=OpenApiSerializerFieldExtension#declare-field-output-with-openapiserializerfieldextension). I can see that it works similar to the decorator, but I didn't get the part of linking the schema to the `JSONField` and doing it automatically via introspection.

Currently, the only link that the `JSONField` has to the schema is because of the validator, and still, how could it be converted from JSON Schema to dict with raw schema structure?

**Comment by tfranzel** [comment]
If you define a JSONField and set a schema on there you can retrieve that later in an extension. Or retrieve the schema out of the validator inside the extension.

Here is a slightly modified example of some related question:

```python
# model field
class MdTextField(models.JSONField):
   # make this class accept a json_schema parameter!
    pass

# serializer field
class MdCharField(serializers.JSONField):
   # or alternatively make this class accept a json_schema parameter!
   # if your go the model path, you may need to somehow hand over the json_schema from the model to the serializer field to make it acessible in the extension.
    pass

# base class for all your modelserializers. you can also inject that entry into that original 
# class property but but it is a bit more hacky.
class CustomModelSerializer(serializers.ModelSerializer):
    serializer_field_mapping = {
        **serializers.ModelSerializer.serializer_field_mapping,
        MdTextField: MdCharField
    }

# and just use it
class XModel(models.Model):
    foo = MdTextField(json_schema=YOURSCHEMA)

class XSerializer(CustomModelSerializer):
    class Meta:
        model = XModel
        fields = '__all__'

# spectacular extension that listens to that custom field and adds the format
class MdFieldExtension(OpenApiSerializerFieldExtension):
    target_class = "PATH.TO.YOUR.MdCharField"

    def map_serializer_field(self, auto_schema, direction):
        # the default
        # schema = auto_schema._map_serializer_field(self.target, direction, bypass_extensions=True

        # your previously injected schema can be use here
       return self.target.json_schema
```

this is just a rough example, but you would generally approach this in a similar way.

**Comment by tfranzel** [comment]
Scratch that last example.I have another package that basically does this already.

https://github.com/tfranzel/django-seriously/blob/9254c027c522a01e8e1ae2150fc3d8248bc38522/django_seriously/utils/fields.py#L8

```python
class Foo(PydanticBaseModel):
    a: int
    b: str
    c: float

class XXX(models.Model):
    bar = ValidatedJSONField(
        structure=Foo
    )
```

I was just missing an extension for get the schema out:

```python
class PydanticJsonFieldExtensions(OpenApiSerializerFieldExtension):
    target_class = "rest_framework.fields.JSONField"

    def map_serializer_field(self, auto_schema, direction):
        if hasattr(self.target.parent, 'Meta'):
            model = self.target.parent.Meta.model
            source = self.target.source.split('.')
            model_field = follow_field_source(model, source)
            
            if hasattr(model_field, 'structure'):
                # let pydantic generate as JSON Schema
                return model_field.structure.schema()
            else:
                return build_basic_type(OpenApiTypes.OBJECT)
        else:
            return build_basic_type(OpenApiTypes.OBJECT)
```

Will get you:

```yaml
    Article:
      type: object
      properties:
        foo:
          title: Foo
          type: object
          properties:
            a:
              title: A
              type: integer
            b:
              title: B
              type: string
            c:
              title: C
              type: number
          required:
          - a
          - b
          - c
      required:
      - foo
```

You can use this or draw inspiration from it

**Comment by mateokurti** [comment]
That was truly helpful. Thanks a lot, I'll be able to solve it with the information you sent. 🎉

**Comment by mateokurti** [comment]
@tfranzel Sorry for pinging you again. The only way I could found for creating a Pydantic Model from JSON Schema is https://github.com/koxudaxi/datamodel-code-generator which generates the code. Do you think this is a good idea?

**Comment by tfranzel** [comment]
I did not mean that you need to use pydantic. it is just an option that I like to use for structured data.

This was meant as an example. You can simply subclass `models.JSONField` and add a parameter that lets you save your defined JSON Schema object on that field instance. Then adapt `PydanticJsonFieldExtensions` to just retrieve that schema on the model field and return it in the extension. This was all just meant as an example how to write attach data to model fields and write an extension for it.

**Comment by mateokurti** [comment]
Yes, the example was clear. However, the issue is that the JSON Schema is not represented as an object in Python but as a [JSON file instead](https://json-schema.org/draft/2020-12/release-notes.html) and in order for `drf-spectacular` to be able to be able to "understand" it, it should be represented as a Python object somehow. That's why I ask about the combination with pydantic and [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator)

**Comment by tfranzel** [comment]
ok so the schema is inside a file. that shouldn't be a problem though as it is just json. just load that file with `schema = json.load(open('json_file'))` and you have a schema as a python dict object. I see no need for any externals tool given that you already have a json structure inside a file.

**Comment by mateokurti** [comment]
Well, it is able to include it within the generated schema, but the $refs of json schema do not seem to work correctly in swagger

**Comment by tfranzel** [comment]
i thought you have one file per component. If you have refs you need to put those those in the `auto_schema.registry` of course. If you don't take care the the used refs are properly injected into the OpenAPI schema, it will of course not work properly in Swagger UI

Also note that OpenAPI 3.0.3 is not fully JSON Schema compliant, so your mileage may vary.

**Comment by mateokurti** [comment]
I think what you've mentioned to the beginning that OpenAPI 3.0.3 is not fully JSON schema compliant, might be the main reason why I'm having issues. Can I generate OpenAPI 3.3 even though it might not be compliant with SwaggerUI?

**Comment by tfranzel** [comment]
`$refs` are totally fine in 3.0.3 you just need to wire them in properly. Look at the generated schema. If you have no targets for your refs in the schema, this obviously cannot work. You need to manually make sure your ref targets are available (via injection into the registry)

swagger UI does not yet support 3.1 features. So if your JSON schemas use features that are not in OpenAPI 3.0.3 your are likely out of luck. Though if you are not doing crazy stuff it should work. They are 95% compatible.

**Comment by mateokurti** [comment]
Hmm interesting, thanks again. Sorry if some of the questions are dummy though, I'm quite new on JSON Schema and OpenAPI concepts and I'm trying to understand. I'll continue with it tomorrow. The discussion and samples on issue #801 also seem interesting and kind of related.
