### ISSUE TITLE
File as a Response seems not to be possible

### ISSUE THREAD

**Issue by jonaskonig** [tfranzel/drf-spectacular#880]
**Describe the bug**
An API endpoint with a response as a CSV or png can not be properly defined. 
The docs state to use the OpenApiTypes.BINARY Type but this seems  only to be a disguised String, which if used returns: Could not satisfy the request Accept header.

**To Reproduce**
```python
@extend_schema(
    methods=['GET'], tags=['company'], responses={(200,"text/csv"):OpenApiTypes.BINARY}, operation_id='get_csv, summary='returns a csv'
)
@action(methods=['GET'], detail=True, url_path='get_csv', url_name='get_csv')
def get_csv(self, request, *args, **kwargs):
    devicelist = [["123","Test Manufacturer","Globe","10","3"]]
    devlist = pd.DataFrame(devicelist, columns=['ID','Manufacturer', 'Type', 'TypeID', 'Unit'])
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': f'attachment; filename="your.csv"'},
    )
    devlist.to_csv(mode="wb", path_or_buf=response, index=False, encoding="UTF-8")
    return response
```

**Expected behavior**
There should probably be a type that can be used in this scenario.

**Comment by tfranzel** [comment]
> responses={(200,"text/csv"):OpenApiTypes.BINARY}

that looks ok to me. I have used this e.g. with `application/pdf` without issue.

> Type but this seems only to be a disguised String, which if used returns: Could not satisfy the request Accept header.

I don't think it's a disguised string. Where does this error come from? swagger-ui or some API client? Please try the generic `application/octet-stream` with `OpenApiTypes.BINARY` and see what the client says then.

**Comment by jonaskonig** [comment]
I mean it says in the description of the Type:
```
Converted to {"type": "string", "format": "binary"}.
Equivalent to :py:class:`bytes`.
Use this for raw binary data.
```
But I need type txt or csv. The error is in the swagger UI where I can see that the return type is String(binary), which is not what I need.

**Comment by tfranzel** [comment]
That is the only way to specify binary data in OpenAPI

https://swagger.io/docs/specification/data-models/data-types/#file

There is no OpenAPI type "csv". You provide the content/MIME type  as `text/csv` and mark the contents itself `BINARY`. This is the only way. Not sure why swagger-ui complains but then this may be an upstream bug if you made no other mistake.
