### ISSUE TITLE
Authorization header is truncated when a valid JWT is used in Swagger authorization form

### ISSUE THREAD

**Issue by jbhoorasingh** [tfranzel/drf-spectacular#884]
**Describe the bug**
When I try to use the Authorized button on the swagger/openapi page receive the following error
`{
  "detail": "Given token not valid for any token type",
  "code": "token_not_valid",
  "messages": [
    {
      "token_class": "AccessToken",
      "token_type": "access",
      "message": "Token has wrong type"
    }
  ]
}`

This same JWT works if i use Postman (Header Authoization: Bearer <token>)

This link is a packet capture of two request

[Packet Capture](https://www.cloudshark.org/captures/a0a47337f9f9)

First request is just some random text. Second is a valid JWT

**To Reproduce**
*settings.py*
`
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API',
    'DESCRIPTION': 'Tool',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
`

*pip freeze*
`asgiref==3.5.2
attrs==22.1.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
coreapi==2.3.3
coreschema==0.0.4
cryptography==38.0.3
cssselect2==0.7.0
decorator==5.1.1
Django==4.1.2
django-filer==2.2.3
django-js-asset==2.0.0
django-mptt==0.14.0
django-polymorphic==3.1.0
django-rest-knox==4.2.0
djangorestframework==3.14.0
djangorestframework-simplejwt==5.2.2
drf-spectacular==0.24.2
easy-thumbnails==2.8.3
idna==3.4
inflection==0.5.1
itypes==1.2.0
Jinja2==3.1.2
jsonschema==4.17.3
lxml==4.9.1
Markdown==3.4.1
MarkupSafe==2.1.1
packaging==21.3
Pillow==9.2.0
pycparser==2.21
PyJWT==2.6.0
pyparsing==3.0.9
pyrsistent==0.19.2
pytz==2022.4
PyYAML==6.0
reportlab==3.6.11
requests==2.28.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
sqlparse==0.4.3
svglib==1.4.1
tinycss2==1.2.0
Unidecode==1.1.2
uritemplate==4.1.1
urllib3==1.26.12
validators==0.20.0
webencodings==0.5.1
`

**To Reproduce**
It would be most helpful to provide a small snippet to see how the bug was provoked.

**Expected behavior**
I am able to paste the JWT token into the Authorization field and authenticate projected api endpoints

**Comment by tfranzel** [comment]
I cannot reproduce this. Also I think this has very little to do with spectacular but rather with swagger-ui. 

I checked if maybe some truncation is going on but it worked for me:

jwt example: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

Added `rest_framework.authentication.TokenAuthentication` to an example view and droped above token in the `Autorize` window.

```
curl -X 'GET' \
  'http://127.0.0.1:8000/articles/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
```

and the `Try it out` request in swagger ui contained the full token:

```
accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-DE,en;q=0.9,de-DE;q=0.8,de;q=0.7,en-US;q=0.6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
Cache-Control: no-cache
...
```

Please provide reproduction.

**Comment by jbhoorasingh** [comment]
I compared your token with mine and some some reason mine a lot longer.
**Mine**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY3MDA3NTk5MCwiaWF0IjoxNjY5OTg5NTkwLCJqdGkiOiI2OGY2NjJlY2EyOWM0NTIwOTEwOWFlYTg2NGU0ZWUyMSIsInVzZXJfaWQiOjF9eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY3MDA3NTk5MCwiaWF0IjoxNjY5OTg5NTkwLCJqdGkiOiI2OGY2NjJlY2EyOWM0NTIwOTEwOWFlYTg2NGU0ZWUyMSIsInVzZXJfaWQiOjF9.hyuovqfoWi4Q2w_01OT7viodausKmhh-xo9tLvGEucg
**Mine TRUNC**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY3MDA3NTk5MCwiaWF0IjoxNjY5OTg5NTkwLCJqdGkiOiI2OGY2NjJlY2EyOWM0NTIwOTEwOWFlYTg2NGU0ZWUyMSIsInVzZXJfaWQiOjF9.hyuovqfoWi4Q2w_01OT7viodausKmhh-xo9tLvGEucg
**Yours**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

------


Now you have me thinking. I when to jwt.io and started to look at my payload of the token... *My stupidity is realized* I was using the refresh token. Sorry to waste your time.
