### ISSUE TITLE
Custom serializer field type could be taken from type hint

### ISSUE THREAD

**Issue by tienne-B** [tfranzel/drf-spectacular#886]
When generating a schema including a custom field directly subclassing `serializers.Field`, we get the "could not resolve serializer field. Defaulting to 'string'" warning.

If we have a return type hint on `to_representation()` or on the `data` parameter of `to_internal_value()`, _spectacular_ should be able to use that for schema generation like it does with type hints on `SerializerMethodField` methods. To avoid inconsistencies, we could require both aforementioned type hints to be the same. 

Thoughts? I should be able to draft a PR for this.

**Comment by tfranzel** [comment]
Hi @tienne-B,

interesting, that thought never crossed my mind. Although possible, type hints are quite limited if you don't want mypy to not fail here and "require both aforementioned type hints to be the same" would be an arbitrary and thus awkward restriction.

Please consider that we already have a couple of options and adding another one may lead to more confusion. Here are the usual steps:

1. If applicable, use an existing base class like `FloatField`, `IntegerField`, etc
2. Use `@extend_schema_field` on your field class. [First code example in the docs](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-3-extend-schema-field-and-type-hints)
3. If the request/response is more complicated, write a [OpenApiSerializerFieldExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-field-output-with-openapiserializerfieldextension) 

Does that make sense?
