### ISSUE TITLE
Extension for django-parler

### ISSUE THREAD

**Issue by AFusco** [tfranzel/drf-spectacular#887]
I'm using https://github.com/django-parler/django-parler for model translation.
So, basically this question is exactly the same as [this one in drf-yasg](https://github.com/axnsan12/drf-yasg/issues/284)

The best I've got is this.

my model looks like:

```

class Menu(TranslatableModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    position = models.CharField(max_length=20, blank=True, default='')

    translations = TranslatedFields(
        title = models.CharField(_("Title"), max_length=100),
        description = models.TextField(_("Description"))
    )

    class Meta:
        ordering = ['position']
```

my serializer:
```
class MenuSerializer(TranslatableModelSerializer):
    translations = TranslatedFieldsField(shared_model=Menu)

    class Meta:
        model = Menu
        fields = ['id', 'translations']
```

This is the best I've got: (it's my first time using this library so I don't really know what I'm doing)
```
class TranslationsFieldFix(OpenApiSerializerFieldExtension):
    target_class = 'parler_rest.fields.TranslatedFieldsField'
    match_subclasses = True

    def map_serializer_field(self, auto_schema, direction):

        serializer = auto_schema.get_request_serializer()
        properties = {}
        print(serializer.fields)

        component = auto_schema.resolve_serializer(self.target, direction, bypass_extensions=True)
        if not component:
            return {}
        for l in PARLER_LANGUAGES[None]:
            properties[l['code']] = build_basic_type(OpenApiTypes.OBJECT)

        return build_object_type(properties=properties)
```

The thing is, I don't really know what to put in the second to last line instead of `build_basic_type(OpenApiTypes.OBJECT)`.
I'd like it to be the OpenApi definition of whatever is the `shared_model` of the `TranslatedFieldsField`

Thanks for any help.

**Comment by tfranzel** [comment]
Hi @AFusco, I think you were already pretty close. `self.target` is the class in `target_class` and that is a field in this case. You want to create the component from the `rest_parler` autogenerated translations serializer that is stored in the field (`self.target`) itself.

This looks ok to me, but might not be 100% complete. Not sure if you need the empty component check. I did not see a way to mark translated fields RO/WO and unless you have only read-only fields for request (or only write-only for response), the component cannot be empty.

```python
class TranslationsFieldFix(OpenApiSerializerFieldExtension):
    target_class = 'parler_rest.fields.TranslatedFieldsField'

    def map_serializer_field(self, auto_schema, direction):
        # Obtain auto-generated sub-serializer from parler_rest
        # Contains the fields wrapped in parler.models.TranslatedFields()
        translation_serializer = self.target.serializer_class
        # resolve translation sub-serializer into reusable component.
        translation_component = auto_schema.resolve_serializer(
            translation_serializer, direction
        )
        # advertise each language provided in PARLER_LANGUAGES
        return build_object_type(
            properties={
                i['code']: translation_component.ref for i in settings.PARLER_LANGUAGES[None]
            }
        )
```

**Comment by AFusco** [comment]
Thank you, it's working perfectly.
I hope this will also help other django-parler users.

Have a great day
