### ISSUE TITLE
Oauth2 authorization problem

### ISSUE THREAD

**Issue by fannypwr** [tfranzel/drf-spectacular#888]
Hello
I don't know if it is a bug or if I am missing something.  I cannot configure the oauth2 authorization. I have tried various tips found online, e.g. https://stackoverflow.com/questions/71115774/how-to-include-oauth2-auth-urls-in-swagger

The error that is raised is JSONDecodeError. The authorization form sends a **byte string in a form of query params** and my view cannot cope with it. I enclose a stack trace, my form (should the client secret and client id be displayed?), my settings and the view. Do I need an extend_schema with inline_serializer if I provide my custom serializer_class? Also, I have provided some data (like client id) twice - either in SWAGGER_UI_OAUTH2_CONFIG or directly in SPECTACULAR_SETTINGS. I would be grateful for any hints :)
```
**b'grant_type=password&scope=read+write&username=abc%40gmail.com&password=secretpass&client_id=abc&client_secret=abcdefgh'**
[07/Dec/2022 08:10:27] ERROR [django.request:222] Internal Server Error: /myapi/v1/auth/token/
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/src/accounts/views/authentication.py", line 103, in post
    data = json.loads(request.body)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
{'request_uuid': '273d8341-fdf8-4330-823f-0174ff666dce', 'time': '2022-12-07 08:10:27', 'user': 'AnonymousUser', 'url': '/myapi/v1/auth/token/', 'method': 'POST', 'get_data': {}, 'post_data': {}, 'response_status': 500, 'response_content': "b'JSONDecodeError at /myapi/v1/auth/token/\\nExpecting value: line 1 column 1 (char 0)\\n\\nRequest Metho", 'django_duration_ms': 750}
[pid: 339|app: 0|req: 1/1] 172.20.0.1 () {54 vars in 1183 bytes} [Wed Dec  7 08:10:26 2022] POST /myapi/v1/auth/token/ => generated 33008 bytes in 763 msecs (HTTP/1.1 500) 6 headers in 230 bytes (1 switches on core 0)

```

![image](https://user-images.githubusercontent.com/23384006/206127150-29d54d6a-d90e-418f-8a52-ce20f2349c40.png)

```
class MyTokenView(TokenView, APIView):
    
    serializer_class = MyAuthTokenSerializer
    schema = AutoSchema()

   

    @extend_schema(
        request=inline_serializer(
            name="InlineTokenSerializer",
            fields={
                "username": serializers.CharField(),
                "password": serializers.CharField(),
                "grant_type": serializers.CharField(required=False),
                "Scope": serializers.CharField(required=False),
                "client_id": serializers.CharField(),
                **"client_secret": serializers.CharField(),**
            },
        )
    )
    def post(self, request, *args, **kwargs):
        data = **json.loads(request.body)** #this line is not to be changed
```

    SPECTACULAR_SETTINGS = {
        'TITLE': 'My name 2',
        'DESCRIPTION': 'Test spectacular',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
        'OAUTH2_FLOWS': [**'client_credentials'**], # I have tried 'email', 'password' , too
        'OAUTH2_AUTHORIZATION_URL': '/myapi/v1/login/',
        'OAUTH2_TOKEN_URL': '/myapi/v1/auth/token/',
        'OAUTH2_REFRESH_URL': '/myapi/v1/auth/token/',
        'OAUTH2_CLIENT_ID': CLIENT_ID,
        'OAUTH2_CLIENT_SECRET': CLIENT_SECRET,
        'OAUTH2_SCOPES': {
            'read': 'Read scope',
            'write': 'Write scope',
        },
        'SWAGGER_UI_OAUTH2_CONFIG': {'OAUTH_APP_NAME': 'My name 1',
                                     'OAUTH_CLIENT_ID': CLIENT_ID,
                                     'OAUTH_CLIENT_SECRET': CLIENT_SECRET},
    }

**Comment by tfranzel** [comment]
Hi @fannypwr, I don't think this is a bug on our side. If anything, it's an issue with Swagger UI or Django OAuth.

SwaggerUI attempts to send the credentials in the POST body. The `TokenView` assumes the payload is JSON, but I believe SwaggerUI prepares it as `multipart/form-data`.

Not sure how to make SwaggerUI change behavior, but I personally solved this before by patching `TokenView` to also accept form data and not just JSON. I believe SwaggerUI does it like that because the standard says this interaction is form-encoded.

I can't comment on whether the stackoverflow answers work. In theory, this endpoint does not need to be part of the schema, given that it very well may have been on another (auth) server, which is the whole point of OAuth.
