### ISSUE TITLE
Ability to control request body type

### ISSUE THREAD

**Issue by MahmoudAljabary** [tfranzel/drf-spectacular#89]
Is there a way to control request body type per endpoint or swagger wide setting? say i want only to enable application/json.

![swagger](https://user-images.githubusercontent.com/3123672/84244649-3d9ade80-ab04-11ea-9522-9ef57304543a.png)

**Comment by tfranzel** [comment]
well that is what your API is actually supporting. have a look at your DRF settings 
```
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
```

the output is very likely correct given your API.

**Comment by tfranzel** [comment]
though i should mention that usually the order is honored and Swagger select the first by default. usually that should be JSON as by the default setting.

**Comment by MahmoudAljabary** [comment]
indeed DEFAULT_PARSER_CLASSES order is respected.
