### ISSUE TITLE
Including custom_settings in spectacular management command

### ISSUE THREAD

**Issue by ampuerod** [tfranzel/drf-spectacular#892]
How can I pass `custom_settings` when generating an OpenAPI schema file using `spectacular` management command? `SpectacularAPIView` allows it, however, the management command seems like doesn't. The command is useful when it is required to generate a static file and store it for later delivery.

I've wrote a small command adding that option here:

```python
from drf_spectacular.management.commands.spectacular import Command as SpectacularCommand
from drf_spectacular.settings import patched_settings

from django.utils.module_loading import import_string


class Command(SpectacularCommand):
    def add_arguments(self, parser):
        super().add_arguments(parser)
        parser.add_argument('--custom-settings', dest="custom_settings", default=None, type=str)

    def handle(self, *args, **options):
        custom_settings = None
        if options['custom_settings']:
            custom_settings = import_string(options['custom_settings'])

        with patched_settings(custom_settings):
            super().handle(*args, **options)
```

**Comment by tfranzel** [comment]
This was not implemented because nobody ever asked for it given the available options. May I ask which settings you intend to override? Can't you set those in `settings.py` with `SPECTACULAR_SETTINGS = {...}`?

The CLI contains `--urlconf`, `--api-version` and `--lang`, which are usually the only settings that one may need to change on the fly.

**Comment by ampuerod** [comment]
The use case: we have a big application with different APIs. We use different settings for each API and for that reason we do this to generate the OAS file using a `SpectacularAPIView`:

```python
SpectacularAPIView.as_view(urlconf=f'{app_name}.urls', custom_settings=spectacular_settings)
```

**Comment by ampuerod** [comment]
Thank you for implementing this! Do you have a date for release so we can get rid of our custom command and use the `drf-spectacular` one?

**Comment by tfranzel** [comment]
it is planned very soon. just need to take care of two more minors.

**Comment by tfranzel** [comment]
new version released
