### ISSUE TITLE
Get examples for custom schema

### ISSUE THREAD

**Issue by nour-bouzid** [tfranzel/drf-spectacular#903]
**Describe the bug**
I am writing my own `CustomAutoSchema` class that inherits from `AutoSchema`. In one of my tests I check if every endpoint my API has a functional example. However, when I try to get the example from the custom schema I get an empty list. in `openapi.py Autoschema` there is the following function:
```
def get_examples(self):
        """ override this for custom behaviour """
        return []
 ```

How can I get the examples set in `extend_schema_view` decorator from a CustomAutoSchema object?

**To Reproduce**
This is the test:
```
def helper_test_open_api_examples_work(
    viewset_class, user, objects, object_names, method="POST", view_kwargs=None
):
    if view_kwargs is None:
        view_kwargs = {}
    schema = viewset_class().schema
    schema.method = method
    schema.view.request = MagicMock()
    schema.view.kwargs = {}
    examples = schema.get_examples()
    assert len(examples) > 0
```

**Expected behavior**
Get correct examples from decorator

**Comment by tfranzel** [comment]
Hi @nour-bouzid, the fact that you use a `CustomAutoSchema` is not really relevant to your problem. Every time you use `@extend_schema` decorator, the AutoSchema is subclassed and patched. You are simply looking in the wrong place.

- default `ViewSet.schema` MRO:
 `CustomAutoSchema, AutoSchema, ViewInspector`
- With retrieve decoration e.g. `ViewSet.retrieve.kwargs['schema']` MRO:  
  `ExtendedSchema, CustomAutoSchema, AutoSchema, ViewInspector`


https://github.com/tfranzel/drf-spectacular/blob/7bfcfb16fe63556f0c6044a4fda4d41cca058051/drf_spectacular/utils.py#L473

So your decorated examples can be found in the `ExtendedSchema.get_examples` method.

---

Endpoint methods -- if applicable -- each have their own schema class. When the view is initialized, the class from `kwargs` gets taken and put into the `view.schema`. Each view is initialized once for **each** endpoint.

However, I must warn you, the rabbit hole goes deeper than that. There is more initialization magic going on behind the scenes in both DRF and spectacular. Your mileage may vary.

https://github.com/tfranzel/drf-spectacular/blob/7bfcfb16fe63556f0c6044a4fda4d41cca058051/drf_spectacular/generators.py#L104

**Comment by nour-bouzid** [comment]
@tfranzel My apologies for the late answer. It took me a while to dive back into this issue. Thank you very much for your fast and thorough response. When I tried to get the examples  using`ExtendedSchema.get_examples` I get an error e.g  `AttributeError: 'DepartmentViewSet' object has no attribute 'request'`

**Comment by tfranzel** [comment]
Not sure where this error is originating exactly, but I suppose it is coming from `is_in_scope` ([code](https://github.com/tfranzel/drf-spectacular/blob/6b8f8e93a6c4d98119aa95ffbdc5ff206b38d8a1/drf_spectacular/utils.py#L349)) It is like I said: 

> However, I must warn you, the rabbit hole goes deeper than that. There is more initialization magic going on behind the scenes in both DRF and spectacular. Your mileage may vary.

You may need to do some extra initialization if you want to mess with the internals. Those methods are not designed to be called independently without the surrounding magic.
