### ISSUE TITLE
Custom Versioning support in DRF Swagger doesn't work

### ISSUE THREAD

**Issue by johnugeorge** [tfranzel/drf-spectacular#907]
For versioning in my code, I was planning to use AcceptHeaderVersioning in DRF but got into a roadblock as described in this [issue](https://github.com/encode/django-rest-framework/issues/8823).

The option left for me would be using `CustomVersioning`  with a [new header](https://www.django-rest-framework.org/api-guide/versioning/#custom-versioning-schemes) sent for every request. I added `DEFAULT_VERSIONING_CLASS` to be the custom versioning. But, I see that DRF-spectacular swagger produces a warning - `"Warning: using unsupported versioning class" `  and swagger points to page saying "No operations defined in spec!"

What I am looking for is to set a common custom version header in the request for all APIs in the swagger which can be set globally in the swagger top bar(Similar to authorizations button) and server reads the header in the middleware to take actions. Can we do that?

**Comment by tfranzel** [comment]
> For versioning in my code, I was planning to use AcceptHeaderVersioning in DRF but got into a roadblock as described in this https://github.com/encode/django-rest-framework/issues/8823.

hmm, I think the version is initialized somewhere in the early stages of the view, since the versioning class does originate there. In that context I find it sensible that there is no version in the middleware which is processed prior to the view.

We do not support custom versioning classes. Only these: https://github.com/tfranzel/drf-spectacular/blob/350529ad8f670e4d5e288218f582a48715d05d41/drf_spectacular/plumbing.py#L921 

But it looks like you don't even need a custom versioning. Just use `AcceptHeaderVersioning` and be aware that 

1. You can force a version on a schema request via `/api/schema?version=1.0`, which you can use as an item in the topbar.
2. You can force a version in the schema view declaration 
    ```python
    path('api/schema-v2/', SpectacularAPIView.as_view(api_version='v2')),
    ```
    , which you can use to define multiple version endpoints and use them in the topbar.

**Comment by johnugeorge** [comment]
@tfranzel Thanks for your reply.

Since you confirmed that there will be no version in the middleware which is processed prior to the view, are you suggesting to manually parse version from accept header `Accept': 'application/json; version=xxx` instead of using `request.version`  in my middle ware after enabling `AcceptHeaderVersioning`? 

In my middleware,  I want to do the version check like

```
if request.version != SERVERVERSION:
        raise 400
else
       continue
```

**Comment by tfranzel** [comment]
You could manually parse the `accept` header (we do it too). If this all your middleware is doing, then this is the just shoehorning the wrong thing in the wrong place. 

If you just want to raise a version error, why not subclass `AcceptHeaderVersioning` (which we do support) and add that check? As a matter of fact that functionality is already existing in `BaseVersioning.is_allowed_version()`. Why reinvent the wheel?

> Also in this case, I have to skip the above check for urls for /schema, /redoc and /swagger as versions are not added in accept header. Any better way to handle this?

no. we take care of mocking the header when you force-override the version in the schema request. That is the reason we only support a few select versioning classes, since this is manually wired.

**Comment by johnugeorge** [comment]
That makes sense. Thanks for your input. I will try that. I will have to override `determine_version` as well in order to filter out swagger urls.

One separate question:
Is it possible to `REQUEST BODY SCHEMA` to be  defaulted to `application/json`?. Currently, I see 3 schemas which are not valid for me. 

<img width="1326" alt="Screenshot 2023-01-03 at 7 11 31 PM" src="https://user-images.githubusercontent.com/2171903/210368724-13b0aee4-e5e6-4ad7-a936-4dc937448f00.png">

**Comment by johnugeorge** [comment]
> > I will have to override determine_version as well in order to filter out swagger urls.
> 
> hmm not sure why that is needed. All I heard to this point does not require any weird hacks.
> 

As you described, I subclassed `AcceptHeaderVersioning` and it worked for all except spectacular urls. 

I have 3 paths added in urls.py
```
    path("schema/", SpectacularAPIView.as_view(api_version="1.0.0"), name="schema"),
    path("swagger/", SpectacularSwaggerView.as_view(), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(), name="redoc"),
```

When I am trying to load schema or swagger or redoc  urls, I see that the initial calls to  /schema/ or /swagger/ or  /redoc/ do not have version in the  request and hence version cannot be determined(Ref: [code](https://github.com/encode/django-rest-framework/blob/069c701ebf3c9b7cb77b9f2f6e80eb0aa60fcc77/rest_framework/versioning.py#L43) ) 

So, I have to skip these urls if request.path matches these urls by overriding determine versions. 


```
     
     self.urls_to_exclude = ["schema","swagger-ui", "redoc"]

    def determine_version(self, request, *args, **kwargs):
        if any(request.path.startswith(reverse(s)) for s in self.urls_to_exclude):
            return default_version
        version = super().determine_version(request, args, kwargs)
        return version
```


> > Is it possible to REQUEST BODY SCHEMA to be defaulted to application/json?. Currently, I see 3 schemas in the generated schema
> 
> Not sure what that means. the first entry is usually the default. have a look at the order of DRF's `DEFAULT_PARSER_CLASSES`

Adding more context. I have already set `DEFAULT_PARSER_CLASSES`  to JsonParser in REST_FRAMEWORK settings.  

```
    "DEFAULT_PARSER_CLASSES": [
        'rest_framework.parsers.JSONParser',
    ],
```
However, I am seeing all parsers in my rest_framework AuthToken url. This is because, parsers are overriden   in [AuthToken view code](https://github.com/encode/django-rest-framework/blob/069c701ebf3c9b7cb77b9f2f6e80eb0aa60fcc77/rest_framework/authtoken/views.py#L14).  I don't know the motivation behind this. Is there some way that I can fix it to JSONParser itself?

**Comment by tfranzel** [comment]
Well, then the schema is correct after all. Spectacular will show what is supported in that exact order even if that does not line up with the users expectations :laughing: 

So either adapt that view to align your expectation with the exposed functionality or maybe use our whitelist feature. Note however this applies globally.

https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/settings.py#L162
