### ISSUE TITLE
Function similar to COMPONENT_SPLIT_REQUEST but for responses?

### ISSUE THREAD

**Issue by tsepulvedacaroca01** [tfranzel/drf-spectacular#912]
I have tried to find out if there is a way to generate a different component for each response from my endpoints, since I have implemented the dynamic fields of the serializers (https://www.django-rest-framework.org/api-guide/serializers/#example). My problem occurs when a serializer is reused and the component always gives the same response, but it must change based on the fields to be used in the serializer.

My `PermissionSerializer ` uses the `RoleSerializer` and should display the `id` and `name` fields as shown in the image and there are no problems with this.

![image](https://user-images.githubusercontent.com/26793623/210912082-f1f40c9e-a6b6-4e03-abe2-c2225f4db673.png)

Instead my main endpoint for my `RoleSerializer` should display all the fields but it doesn't because it should be using the record stored by the `RoleSerializer`.

![image](https://user-images.githubusercontent.com/26793623/210912596-9e9d51a1-1161-4d0c-9e72-0ce68acdce2e.png)

Removing the `PermissionSerializer` endpoint documentation found the `RoleSerializer` documentation correct.

![image](https://user-images.githubusercontent.com/26793623/210912820-c86f8237-9ee8-48cb-96bf-4db9a65ec99a.png)

It should be noted that the serializer used by `PermissionSerializer` is the same as `RoleSerializer`, only that the fields are filtered through the fields attribute as shown in the link provided above.

```py
class RoleSerializer(DynamicFieldsModelSerializer):
    class Meta:
        model = Role
        fields = (
            'id',
            'name',
            'description',
            'order',
            'administrator',
            'permissions',
            'groups'
        )

class PermissionSerializer(DynamicFieldsModelSerializer):
    roles = RoleSerializer(fields=['id', 'name'])
    class Meta:
        model = Permission
        fields = (
            'id',
            'app',
            'name',
            'display_name',
            'description',
            'order',
            'roles'
        )
```

I hope to explain my question and problem in detail

**Comment by tfranzel** [comment]
Ok, so this is completely unrelated to `COMPONENT_SPLIT_REQUEST`. This setting already means one component for request and one component for response.

This is basically a duplicate of https://github.com/tfranzel/drf-spectacular/issues/375#issuecomment-1255634229

The expectation is that serializers don't change their form under the same class (name). We have not attempted to solve this as there is no optimal solution. You can however fix this with a [OpenApiSerializerExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-serializer-magic-with-openapiserializerextension)

Add another arg for `name` to `DynamicFieldsModelSerializer` and use that in `OpenApiSerializerExtension.get_name`. This should resolve the comonent naming conflict.

**Comment by tfranzel** [comment]
since this has been asked before and writing that extension is non-trivial, I added a test/example. please refer to this commit on how to solve the issue.

**Comment by tsepulvedacaroca01** [comment]
Thanks for the help!
