### ISSUE TITLE
DjangoOAuthToolkit Integration

### ISSUE THREAD

**Issue by sabitrakhl** [tfranzel/drf-spectacular#922]
From the doc, I can see that  drf-spectacular included support for DjangoOAuthToolkit. I believe this means I do not have to create custom AuthenticationScheme class by extending OpenApiAuthenticationExtension. But my swagger view is not working:

![response](https://user-images.githubusercontent.com/33543168/213770919-08bec220-daa3-4b51-9450-f34ca02c8635.png)
![auth](https://user-images.githubusercontent.com/33543168/213770924-205adc11-b935-47f6-939f-7ee65a649b92.png)

What could be the potential fix for this?

**Comment by tfranzel** [comment]
> From the doc, I can see that drf-spectacular included support for DjangoOAuthToolkit. I believe this means I do not have to create custom AuthenticationScheme class by extending OpenApiAuthenticationExtension

Yes and yes.

The fact that you see Oauth2 in SwaggerUI means the support is indeed working or at least the schema includes the necessary details. 

The second question is whether SwaggerUI will make use of the credentials received. That part apparently is not working for you. We do reload the schema (with auth) from the server after successful authentication for the simpler auth methods (`bearer`, `basic`, `apiKey` header). 

Could you set 

```python
    SPECTACULAR_SETTINGS = {
        "SWAGGER_UI_SETTINGS": {
            "persistAuthorization": True,
       }
     }
```
and F5 reload the SwaggerUI after auth, and see if the schema is non-empty then?

**Comment by sabitrakhl** [comment]
Thank you @tfranzel.

For me I had to include IsAuthenticatedOrTokenHasScope permission class for this to work.
