### ISSUE TITLE
Error using `AUTHENTICATION_WHITELIST` to disable auth in OpenAPI schema

### ISSUE THREAD

**Issue by niccolomineo** [tfranzel/drf-spectacular#923]
Hi @tfranzel, as you suggested [here](https://github.com/tfranzel/drf-spectacular/pull/916#issuecomment-1397765978), I tried to pass:

```
'AUTHENTICATION_WHITELIST': [None]
```

in `SPECTACULAR_SETTINGS` to suppress the security scheme, but I am getting:

```
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

I am using drf 3.14.

**Comment by niccolomineo** [comment]
A workaround I just found out to be working is passing an authentication backend that is not currently in use in the project, and the security schema is returned empty / the button is not shown.

**Comment by tfranzel** [comment]
Good point. I just tried to come up with a value that was supposed to satisfy your requirement. This was not an official feature, but I think is worth adding.

**Comment by niccolomineo** [comment]
I agree it would be nice to have. I think just a `None` value for `AUTHENTICATION_WHITELIST `would suffice. What do you think?

**Comment by niccolomineo** [comment]
@tfranzel, I tested it and passing an empty list hides the Authorization button on the GUI. May I suggest that this be documented, also?

**Comment by tfranzel** [comment]
@niccolomineo awesome!

I think this is kinda documented here:

https://github.com/tfranzel/drf-spectacular/commit/0dfa1dc7b5c1e58c452a138d5f6c47018cedea59#diff-9748fb54622c822b7d9a2e29ff074cd8ed22d17b8de898f1ea6d69afcef82c75R160

I would refrain from documenting implementation details of SwaggerUI though. That would be a bottomless pit and I won't even try to 😆
