### ISSUE TITLE
Using custom pagination with APIView

### ISSUE THREAD

**Issue by VaZark** [tfranzel/drf-spectacular#924]
**Describe the bug**

Within an APIView, when returning a manually generated paginated response, there are no clear ways to merge the pagination schema with the child serializer

**To Reproduce**

```python
class StdPagination(PageNumberPagination):
    def get_paginated_response(self, data):
        return Response({
            'page_no': self.page.number,
            'num_pages': self.page.paginator.num_pages,
            'page_size': self.page.paginator.per_page,
            'count': self.page.paginator.count,
            'next': self.get_next_link(),
            'previous': self.get_previous_link(),
            'results': data
        })

class ParrainageView(views.APIView, StdPagination):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        responses=ParrainageSerializer(many=True), 
        # The error is probably here but I have no idea what to actually pass here
    )
    def get(self, request):
        params = request.GET
        qs = UserReferral.objects.all()
        results = self.paginate_queryset(qs, request, view=self)
        srl = ParrainageSerializer(results, many=True)
        return self.get_paginated_response(srl.data)
```
**Actual behaviour**

Returns

```json
[]
```

**Expected behavior**

Returns

```json
{
    "page_no": 1,
    "num_pages": 1,
    "page_size": 20,
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```

**Comment by tfranzel** [comment]
Hi @VaZark,

this is not how pagination usually works in DRF, at least how it is designed work. 

1. It is this:

```python
class ParrainageView(views.APIView):
    permission_classes = [IsAuthenticated]
    pagination_class = StdPagination
```

instead of:

```python
class ParrainageView(views.APIView, StdPagination):
    permission_classes = [IsAuthenticated]
```

2. Then you need to write or adapt `StdPagination.get_paginated_response_schema()` to fit your custom response body. 
3. Make sure you have the field examples present in `get_paginated_response_schema`, we depend on it.

Then it should work. Pagination works a bit different compared to the other mechanics in DRF.

**Comment by VaZark** [comment]
Thank you. That was exactly what I had been searching for.

**Comment by VaZark** [comment]
Can this be mentioned somewhere in the docs please ? or shall I send in a PR for it?

**Comment by tfranzel** [comment]
not entirely sure where to put it... maybe a FAQ entry. sure, you can submit a PR.
