### ISSUE TITLE
'format' query parameter being appended to all endpoints 

### ISSUE THREAD

**Issue by Crateros** [tfranzel/drf-spectacular#932]
**Describe the bug**
A `format` entry of type string with enum set ["json", "multipart"] is being appended to all of the request query parameter sections of each endpoint. After some reading and code exploration I assume this is being appended due to Django setting the default parsers as JSON and form data, the codebase I am working on does not explicitly define default parsers in settings.py. Some of the @extend_schema() annotations have no defined query parameters, yet the addition of the `format` entry causes the section to be rendered in the UI (redoc in this case). I am guessing this is a consequence of not properly following best practices when writing API views; just trying to make the most of the inherited codebase without increasing scope beyond what is feasible.

**To Reproduce**
```
    @extend_schema(
        summary='...',
        description='...',
        tags=['Tag'],
        auth=[{'tokenAuth': []}],
        parameters=[
            OpenApiParameter('admin_group_id', OpenApiTypes.INT, OpenApiParameter.PATH,
                description='The admin group id',
                required=True,
            ),
        ],
        responses={
            (200, 'application/json'): OpenApiResponse(
                description='Successful response', response=ApiAdminGroupSerializer
            ),
            (400, 'application/json'): OpenApiResponse(description='Invalid group_id'),
            (403, 'application/json'): common_response_schemas['403']
        }
    )
```

<img width="769" alt="Screenshot_2023-02-07_at_1_30_25_PM" src="https://user-images.githubusercontent.com/17658464/217370947-80851704-82a8-46ce-be65-3a9aecaf4f14.png">

**Suggested behavior**
A way to hide the `format` for the request query parameters section when it is implied or unnecessary.

**Comment by tfranzel** [comment]
ok so this is basically what your API supports, which in itself is not wrong. It is only shown because you have more than one renderer and you allow overwrites via the DRF setting `URL_FORMAT_OVERRIDE`.

https://github.com/tfranzel/drf-spectacular/blob/24b8a9890d59900d102490a48e286d08cdcc7ab5/drf_spectacular/openapi.py#L218

3 choices:

1. turn off `"URL_FORMAT_OVERRIDE": None`
2. remove the multipart renderer from `DEFAULT_RENDERER_CLASSES`
3. subclass our `AutoSchema` with `def _get_format_parameters(self): return []` and use it in `DEFAULT_SCHEMA_CLASS`

1 and 2 actually remove functionality to align your expectation with reality and no 3. just hides the parameter.

**Comment by tfranzel** [comment]
oh shoot... forgot another option:

4. set `RENDERER_WHITELIST` (spectacular setting), that does only include e.g. the json renderer. This will also hide.

**Comment by Crateros** [comment]
@tfranzel Thank you! Option 4 seems like the most straightforward solution to hide the section since we currently only support json parsing and rendering in our public API, but...

After thinking about it some more I began to worry that I was saddling any future developer with tech debt because they would have to garner all of the context that I now have about the issue. I could solve this with documentation but it seems so specific that I was hoping a more explicit way of marking the view renderers existed. It turns out that since we inherit from ApiView the renderers can be defined **at the class level**. So doing something like:
```
class MyApiView(ApiView):
    renderer_classes = [JSONRenderer]
```
actually solved the erroneous section being displayed in the docs 👍 This also means that in the future a multipart form view would not be out of luck as I understand it as long as it is defined in it's own class that does not also describe views relying on `JSONRenderer`.

**Comment by tfranzel** [comment]
Sure thing, that is the most basic solution (No. 5), which I didn't even think to mention. 

You can certainly override `renderer_classes` on every view. However, if you don't want to repeat it on every view, just set the DRF setting `DEFAULT_RENDERER_CLASSES` to have a global default. That one takes effect as long as you don't manually set `renderer_classes` on the view.

**Comment by Crateros** [comment]
Ah, so the default gets utilized unless otherwise stated explicitly at the view level, this might be the most elegant solution for my current setup!

Thanks for the continued work supporting this package, our API has benefited from it greatly 🙏
