### ISSUE TITLE
Getting error generating schema with rest_framework_social_oauth2

### ISSUE THREAD

**Issue by MehdiDRISSIB** [tfranzel/drf-spectacular#933]
Hello

Here is the error:
```
site-packages\rest_framework_social_oauth2\views.py: Error [TokenView]: unable to guess serializer. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. Either way you may want to add a serializer_class (or method). Ignoring view for now.
```
This error has already been reported in spring boot: https://stackoverflow.com/questions/42054384/how-to-configure-oauth2-with-password-flow-with-swagger-ui-in-spring-boot-rest-a
and in swagger-codegen : https://github.com/swagger-api/swagger-codegen/issues/11959

Any help please ?

**Comment by tfranzel** [comment]
Some libraries do not work out of the box. We have build-in extensions for some (see README).  We intent to only support  popular libraries as it incurs a maintenance overhead. 

In either case, extensions hosted by you or us are exactly the same: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

see https://github.com/tfranzel/drf-spectacular/tree/master/drf_spectacular/contrib for reference

**Comment by tfranzel** [comment]
Last commit in this repo was 4 years ago. I will not invest time there. If you like, you can write the extensions and do a PR for our blueprint section.

 I'll close this for now, but feel free to open a blueprint PR if you like
