### ISSUE TITLE
Getting bug when generating schema, possible reason dj_rest_auth version 3.0.0 release leads to breaking changes

### ISSUE THREAD

**Issue by Danane84** [tfranzel/drf-spectacular#937]
When I try to create a schema via the command `python manage.py spectacular --file schema.yml` I get the following error message: 
`ImportError: cannot import name 'JWTSerializer' from 'dj_rest_auth.app_settings'`

I am using `dj_rest_auth==3.0.0`, which was released three days ago. I compared the `dj_rest_auth.app_settings.py` file of version 3.0.0 with the latest major version before that (version 2.2.8) and if I am not mistaken, `JWTSerializer` was indeed renamed to `JWT_Serializer` in the 3.0.0 version. So it seems to me that this variable name change in `dj_rest_auth` is causing an bug in `drf-spectacular`

If my assumption regarding the cause for the bug is correct, could you please fix it?

**Comment by tfranzel** [comment]
Ahh, I see. They cleaned up their awkward setup in favor of something more idiomatic for DRF. nice! will have a fix soon.

**Comment by browser-bug** [comment]
Thanks for this @tfranzel 
Are you planning on releasing on PyPi soon?

**Comment by tfranzel** [comment]
yes. I'll want to look at another issue first but I plan in the next couple of days.

**Comment by mostaszewski** [comment]
@tfranzel I don't want to push you, but are you able to estimate when this fix will be released? Thank you!

**Comment by tfranzel** [comment]
no worries. there were a couple of issues raised. currently working on a long pending feature. took longer than anticipated. end of week at the latest.

**Comment by tfranzel** [comment]
closed with release `0.26.0`
