### ISSUE TITLE
`read_only` attribute of `Paginated*List` schemas is not camelized

### ISSUE THREAD

**Issue by alekz** [tfranzel/drf-spectacular#938]
**Describe the bug**
Starting with version 0.25.0, `read_only` attribute of `Paginated*List` schemas is not camelized in generated JSON schema files.

**To Reproduce**
`camelize_serializer_fields` is added to postprocessing hooks:
```python
SPECTACULAR_SETTINGS = {
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields"
    ],
}
```

Simplified examples of a view and a serializer:
```python
class MyView(generics.ListCreateAPIView):
    serializer_class = SomeSerializer
    def post(): ...
    def get(): ...
```

I then run this command to generate a schema file:
```bash
django spectacular --file schema.json --format openapi-json
```

The resulting `schema.json` file now has `PaginatedSomeList` included, with all `read_only` keys non-camelized.

```json
    "components": {
        "schemas": {
            "PaginatedSomeList": {
                "type": "object",
                "properties": {
                    "count": {
                        "type": "integer",
                        "example": 123,
                        "read_only": true
                    },
                    "next": {
                        "type": "string",
                        "read_only": true,
                        "format": "uri",
                        "nullable": true,
                        "example": "http://api.example.org/accounts/?page=4"
                    },
                    "previous": {
                        "type": "string",
                        "read_only": true,
                        "nullable": true,
                        "format": "uri",
                        "example": "http://api.example.org/accounts/?page=2"
                    },
                    "results": {
                        "read_only": true,
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Some"
                        }
                    }
                }
            }
        }
    }
```

This happens only in `Paginated*List` schemas, all other schemas have all their attributes properly camelized (including `readOnly`).

This was working as expected in version 0.24.2 and started behaving as described above from version 0.25.0.

**Expected behavior**

All attributes are camelized, specifically in this case `read_only` is expected to be `readOnly`.

**Comment by tfranzel** [comment]
This actually looks like a user error from the looks of it, not a bug in spectacular. That `read_only` is supposed to be a OpenAPI keyword and must always be camelized regardless of the hook or camelization options.

It is possible that a bugfix in the meantime brought this to light for you, but it is not bug in itself. We only camelize user strings, not already camelized (and fixed) schema keywords.

https://github.com/encode/django-rest-framework/blob/34953774f34e2dc980c522f32000587ea7edb6a6/rest_framework/pagination.py#L234

I'm asuming you are subclassing `PageNumberPagination`? The original class is identical except for the added `read_only` (`readOnly`). Where is this coming from? I'm pretty sure it is not us adding it. 

Can you elaborate?

**Comment by alekz** [comment]
> I'm asuming you are subclassing `PageNumberPagination`? The original class is identical except for the added `read_only` (`readOnly`). Where is this coming from? I'm pretty sure it is not us adding it.

You're actually right, this `read_only` attribute is indeed coming from a subclass of `PageNumberPagination`, I didn't realize that myself before.

And I agree with you, this custom code should've been `readOnly` in the first place, especially assuming that the purpose of `camelize_serializer_fields` is to camelize field names (as per its name) but not such keywords.

That was helpful though, thanks for pointing this out! I assume this issue can be closed then?
