### ISSUE TITLE
Requirements list is incomplete

### ISSUE THREAD

**Issue by adamsmietanka** [tfranzel/drf-spectacular#940]
**Describe the bug**
It looks like `djangorestframework-simplejwt` is one of the requirements when using spectacular with `dj_rest_auth`.

**To Reproduce**
1. Generate schema with `dj_rest_auth` installed

**Expected behavior**
I expected no errors logged, but got: 

- `registered extensions CookieTokenRefreshSerializerExtension for "dj_rest_auth.jwt_auth.CookieTokenRefreshSerializer" has an installed app but target class was not found.`
- `registered extensions SimpleJWTCookieScheme for "dj_rest_auth.jwt_auth.JWTCookieAuthentication" has an installed app but target class was not found.`

This all stems from the fact `drf-spectacular` tries to load all the extensions' code including `djangorestframework-simplejwt`which is not present in the environment.

**Comment by tfranzel** [comment]
> It looks like djangorestframework-simplejwt is one of the requirements when using spectacular with dj_rest_auth.

no it is not, it is optional. just like `simplejwt` is optional to `dj_rest_auth`

> This all stems from the fact drf-spectacular tries to load all the extensions' code including djangorestframework-simplejwtwhich is not present in the environment.

by default spectacular tries to load all extensions, even those that have not installed apps. However, it only **warns** when there is an entry in `INSTALLED_APPS` and the according classes cannot be loaded. 

I'm just wondering whether something broke with the recent `dj_rest_auth==3.0.0` release or has this been throwing warnings from the start.

Will look into into it, but this is just a informational warning and should NOT impact the schema in any way.

**Comment by tfranzel** [comment]
so `dj_rest_auth` is a bit special in that it provides optional integrations for `allauth` and `djangorestframework-simplejwt`. We support those integrations too, but emitted an erroneous warning when `dj_rest_auth` is present but not their integrations. This had zero impact on the schema, just an ugly warning. Added the concept of optional extensions where there is no warning emitted.

interestingly no one ever raised this before, even though I know people are using this and not everyone is also using the aux packages. 🤔

**Comment by tfranzel** [comment]
closed with release `0.26.0`
