### ISSUE TITLE
help_text is not properly taken from ImageField, ForeignKey, ManyToManyField field.

### ISSUE THREAD

**Issue by diego351** [tfranzel/drf-spectacular#941]
**Describe the bug**
help_text is not properly taken from ImageField, ForeignKey, ManyToManyField field. Other fields work

**To Reproduce**
Create model serialiser based on model having ImageField, ForeignKey, ManyToManyField fields with help_text field set. No description for this fields is generated

**Expected behavior**
help_text is properly generated

**Comment by tfranzel** [comment]
cannot reproduce, please provide a reproduction. 

`models.ImageField(storage=fs, help_text='test test')` on the model shows up as expected in the schema, when used with a `ModelSerializer`.

**Comment by diego351** [comment]
What about ForeignKey and ManyToManyField?

**Comment by tfranzel** [comment]
those are actually covered by the tests and are working as expected (i.e. it shows up in the schema):

https://github.com/tfranzel/drf-spectacular/blob/f03b14185a404db651f0d3d1296727f09c9db65e/tests/test_fields.py#L100-L105

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/blob/f03b14185a404db651f0d3d1296727f09c9db65e/tests/test_fields.yml#L296

you need to provide a reproduction that shows the issue. have a look at `test_regressions.py` for examples.

**Comment by diego351** [comment]
Python 3.11.0

Django==4.1.2
djangorestframework==3.14.0
drf-spectacular==0.25.1


```

class Trade(models.Model):
    name = models.TextField(db_index=True, help_text='Name')
    class Meta:
        unique_together = ("name",)

class Sponsor(models.Model):
    main_trade = models.ForeignKey("Trade", related_name="sponsors_with_main_trade_set", on_delete=models.PROTECT, help_text="Main trade ID")
    trades = models.ManyToManyField("Trade", related_name="sponsors_with_any_trade_set", help_text='List of associated trade IDs')
    name = models.TextField(db_index=True, help_text='Name')

    class Meta:
        unique_together = ("name",)

class SponsorSerializer(s.ModelSerializer):
    main_trade = TradeSerializer()
    trades = TradeSerializer(many=True)

    class Meta:
        model = m.Sponsor
        fields = ("id", "name", "main_trade", "trades")
        
class SponsorListView(ListAPIView):

    model = Sponsor
    permission_classes = (IsAdminUser,)
    pagination_class = LimitOffsetPagination
    filterset_class = SponsorFilter
    serializer_class = SponsorSerializer

    def get_queryset(self):
        return self.model.objects.all()
        
```
produces this 

```
 Sponsor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: Name
        main_trade:
          $ref: '#/components/schemas/Trade'
        trades:
          type: array
          items:
            $ref: '#/components/schemas/Trade'
      required:
      - id
      - main_trade
      - name
      - trades
```

**Comment by diego351** [comment]
```
class Brand(models.Model):
    image = models.ImageField(blank=True, upload_to="images", help_text='asdasdasd')
    name = models.TextField(db_index=True, help_text='Name')

    class Meta:
        unique_together = ("name",)
        

class BrandSerializer(ModelSerializer):
    image = Base64ImageField(required=False)
   
    class Meta:
        model = Brand
        fields = ('id', 'name', 'image')


class BrandListView(ListAPIView):
    """
    Endpoint to retrieve Brand list. params: limit: int, offset: int, name_contains: str
    """

    model = Brand
    serializer_class = BrandSerializer
    pagination_class = LimitOffsetPagination
    queryset = model.objects.all()
```
    
produces: 

```
 Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: Name
        image:
          type: string
          format: uri
      required:
      - id
      - name
```

**Comment by diego351** [comment]
Is this related to: https://drf-spectacular.readthedocs.io/en/latest/faq.html#filefield-imagefield-is-not-handled-properly-in-the-schema ?

**Comment by tfranzel** [comment]
> Is this related to: https://drf-spectacular.readthedocs.io/en/latest/faq.html#filefield-imagefield-is-not-handled-properly-in-the-schema ?

totally unrelated. 

`trades = TradeSerializer(many=True)` is the "problem".  DRF will generate a `ModelSerializer` for you given a subset of fields. If you then go ahead and overwrite those fields, DRFs preconfigured fields are replaced with your version. This should also be clear given that you replace a `ForeignKeyField` with a `TradeSerializer` field.

Thats how subclassing works and is the expected behavior.

**Comment by diego351** [comment]
Maybe they shouldn't be cleared if there is a model based help_text and there's no serializer based help_text?

And they should be replaced by serializer based help_text only if there's one defined by one?

Please don't close the issue. I think that shadowing behavior is important thing, we should at least have a discussion about it. There's valuable information lost in the process and it doesn't have to be like that.

**Comment by diego351** [comment]
@tfranzel 
I think for most of the cases these will make sense, and for minority of cases you can always redefine on serializer level. I think overshadowing empty help_text on serialiser level with existing valid help_text on model level doesn't make sense.

**Comment by tfranzel** [comment]
> Please don't close the issue. I think that shadowing behavior is important thing, we should at least have a discussion about it. There's valuable information lost in the process and it doesn't have to be like that.

Well, this is simply how DRF's `ModelSerializer` work. I did not come up with those choices.

@diego351 I understand your motivation and it makes sense for you specific case. However, you are basically redefining the foundational principle of object-oriented programming. What you call overshadowing is overwriting super-class behavior in a derived class. The essence of OO.

Also, there are more properties that are forwarded from the model. `help_text` is informational and might not hurt, but what about the others? Imagine only carrying over the `help_text`. How is this then consistent when only leaking through `help_text` and not the other properties? Defining an awkward mechanism to back back-peddle when you actually don't want the the string to bleed through is not gonna help either. That would need to behave consistently with the other bled-through properties. I would argue that most users will not understand those non-standard mechanics without a lengthy explanation.

I think your are looking at this from your narrow use-case perspective, while being blissfully ignorant of the bigger picture. You are free to hack spectacular in this way, but there is a zero chance of this being accepted into the project.
