### ISSUE TITLE
PolymorphicProxySerializer with primitive serializer

### ISSUE THREAD

**Issue by jkarstens** [tfranzel/drf-spectacular#944]
**Describe the bug**
I have to deal with a field that may either be a simple string or a list of strings. I tried using `serializers.CharField()` as the primitive string:
```python
PolymorphicProxySerializer(
  component_name="StringOrListOfStrings"
  serializers=[
    serializers.CharField(),
    serializers.ListSerializer(child=serializers.CharField())
  ]
  resource_type_field_name=None,
  many=False,
)
```
and `OpenApiTypes.STR` as the primitive string:
```python
PolymorphicProxySerializer(
  component_name="StringOrListOfStrings"
  serializers=[
    OpenApiTypes.STR,
    serializers.ListSerializer(child=serializers.CharField())
  ]
  resource_type_field_name=None,
  many=False,
)
```

Alas, both give the following error on schema generation: `PolymorphicProxySerializer's serializer argument contained unknown objects.`

I even tried creating a custom `StringSerializer` to represent the primitive string:
```python
class StringSerializer(serializers.Serializer):
    def create(self, validated_data):
        return validated_data

    def update(self, instance, validated_data):
      return validated_data

    def to_internal_value(self, data):
        return data

    def to_representation(self, instance):
        return instance


PolymorphicProxySerializer(
  component_name="StringOrListOfStrings"
  serializers=[
    StringSerializer(),
    serializers.ListSerializer(child=serializers.CharField())
  ]
  resource_type_field_name=None,
  many=False,
)
```

But that resulted in this error: `To control sub-serializer's "many" attribute, following usage pattern is necessary: PolymorphicProxySerializer(serializers=[...], resource_type_field_name=None, many=False). Ignoring serializer as it is not processable in this configuration.` 
This error seems off to me since `resource_type_field_name=None` and `many=False` are indeed part of the corresponding `PolymorphicProxySerializer` definition

**To Reproduce**
```python
PolymorphicProxySerializer(
  component_name="StringOrListOfStrings"
  serializers=[
    OpenApiTypes.STR,  # what goes here for a primitive string?
    serializers.ListSerializer(child=serializers.CharField())
  ]
  resource_type_field_name=None,
  many=False,
)
```

**Expected behavior**
Perhaps this is available and I couldn't figure out from reading the docs and going through the repo - expecting a PolymorphicProxySerializer to able to receive a primitive serializer (not a dictionary) in the serializers list

**Comment by tfranzel** [comment]
Yep, sry that cannot work. `PolymorphicProxySerializer` requires its polymorphic types to be actual `Serializer`s due to the way this is structured in the schema. We need a named object component, which we can only get from serializers and not anonymous types or standalone fields. The typing and doc suggests that it can only be `Serializers` and `mypy` should actually complain about your usage. 

https://github.com/tfranzel/drf-spectacular/blob/6300b1258b008b557da879ac5c58cb0b2c97fa4d/drf_spectacular/utils.py#L71

So if you only use serializers this will work, but that is of cource not what you are after.

Can you post more context, because there might be other ways to achieve what you want. Without it it is hard to tell.

**Comment by jkarstens** [comment]
Thanks, yeah, I saw the type errors, thought that was just the clearest way to describe what I was looking for - wondering if there was anything that I was missing.

Got around the type error with the custom serializer (`StringSerializer` in the opening comment) approach, but that approach fails with the `many=False` error message - can you explain that? I'm confused since `many=False` was included in the `PolymorphicProxySerializer` (contrary to the error message's assertion).

Afraid there isn't much more context to provide. While perhaps not the optimal API design, this pattern does exist out there (for backwards compatibility purposes or who knows what else). [Here's an example in the wild](https://dev.bandwidth.com/docs/messaging/webhooks)
![image](https://user-images.githubusercontent.com/8845273/220764895-fa38a5be-d72a-4a72-8702-b77bd2649bed.png)
How would you use drf-spectacular to generate a schema that describes this behavior?

**Comment by tfranzel** [comment]
>  can you explain that? 

https://github.com/tfranzel/drf-spectacular/blob/6300b1258b008b557da879ac5c58cb0b2c97fa4d/tests/test_polymorphic.py#L328-L333

This is meant as manual way to mix and match both many=True and False manually (i.e. to disable auto list detection). Have a look at that example usage. Not sure why this message is emitted, but all your examples have at least one invalid list entry. Use it with `[StringSerializer(), StringSerializer(many=True)]` and it should work.

> Afraid there isn't much more context to provide. 

I was asking for the location. Is this the response of one serializer field or the response of the whole endpoint? Solution depends on that:

```python
# for field in serializer:
class XSerializer(serializers.Serializer):
    field_i = serializers.SerializerMethodField()
    
    def get_field_i(self, object) -> Union[str, List[str]]:  # modern notation will also work
      return ...

# you can also use below raw schema and use it above with a @extend_schema_field() decorator instead of the hint.

# for a REST endpoint
class YAPIView(APIView):
    @extend_schema(responses={
        200: {'oneOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}}
    )
    def get(self, request):
        pass  # pragma: no cover
```

The endpoint version uses raw schema notation. This is one of the very rare situations where it is easier to just write a small raw schema snippet.

**Comment by jkarstens** [comment]
> Use it with [StringSerializer(), StringSerializer(many=True)]

How is that different than `[StringSerializer(), ListSerializer(child=serializers.CharField())]`? `many=True` is set on `ListSerializer`.


> I was asking for the location.

Ah, the location is a request serializer (`@extend_schema(request=PolymorphicProxySerializer(...))`) on a REST endpoint: this is a requst the app receives from a third party. The second example you provide. Ok, will use a raw schema then. Thanks for your help

**Comment by tfranzel** [comment]
> How is that different than [StringSerializer(), ListSerializer(child=serializers.CharField())]? many=True is set on ListSerializer. Is it required that the list elements all be the same type?

The problem is your usage of `CharField`. No its not required to be the same type. However, they all need to be **named** serializer classes in the end, i.e. you cannot use anonymous field classes. The difference is that you gave `StringSerializer` an actual name: `String`. All "user" serializers have a name by virtue of their class name. We need that name to create a component.

Usage of `ListSerializer` is ok as long you use it with a actual serializer class since 

```python
serializers.ListSerializer(child=XSerializer()) == XSerializer(many=True)
``` 

Don't be confused by this special case of `PolymorphicProxySerializer `. This manual many mode is very rarely needed. It just happens to be that this looked useful to you, but it is meant for something else.

**Comment by jkarstens** [comment]
Ah, ok, no anonymous field classes. Makes sense, thank you
