### ISSUE TITLE
Hide schema endpoint and return it as json response

### ISSUE THREAD

**Issue by MahmoudAljabary** [tfranzel/drf-spectacular#95]
is this feasible to achieve using drf-spectacular? drf-yasg included it by default.
1. hide /schema endpoint.
2. return schema.json as json response and not downloadable file.

**Comment by MahmoudAljabary** [comment]
i fixed number 2 by using SpectacularJSONAPIView

**Comment by tfranzel** [comment]
1: https://drf-spectacular.readthedocs.io/en/latest/settings.html -> ``'SERVE_INCLUDE_SCHEMA': False``
2: that is the correct way to do it in the browser. yaml is the default and for the generic renderer you would need to set the ``Accept`` header explicitly.
