### ISSUE TITLE
Header parameters were not send to the server

### ISSUE THREAD

**Issue by Wissperwind** [tfranzel/drf-spectacular#956]
![1](https://user-images.githubusercontent.com/20759873/223117986-70bd6a33-194c-4d04-9260-e76d907a3750.PNG)

Hi,
We are working on the swagger page containing our token refresh endpoint. To access this endpoint no authorisation is needed. @authentication_classes([]) Because of course you have to access it if your token is expired and thus not valid.
But our endpoint in Django reuires the HTTP_AUTHORISATION header to be set to get the old token there.
We tried to set an AUTHORISATION header parameter with spectacular. But it is not send to the server as you can see in the curl example. Why?

**Comment by tfranzel** [comment]
Hi @Wissperwind, this has nothing to do with the new release yesterday, right?

I believe this is a SwaggerUI thing and has little to do with us. SwaggerUI treats `Accept`, `Authorization` and `Content-Type` headers differently as they are sourced from the schema itself. I think we, as schema provider, have basically zero influence over SwaggerUI's curl command generator.

We do some light patching in the SwaggerUI template, but I doubt if that is even related to this or if we even should do anything here.

**Comment by Wissperwind** [comment]
No, nothing to do with the release from yesterday.

**Comment by Wissperwind** [comment]
OK, I see that you can not do anything here. Thanks for the fast reply.

**Comment by Wissperwind** [comment]
Is there a swagger Github repository?
