### ISSUE TITLE
Extension docstring magic

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#96]
When the user has overridden a view, they are very likely to change the serializer, and not copy the docstring.

It would be nice if the extension system here used the main view docstring, unless the replacement provided its own docstring.

**Comment by tfranzel** [comment]
actually i was under the impression that this was already being done. ``inspect.getdoc`` will follow the MRO until it finds a docstring. at least that is what i understood from a quick glance over the implementation. 

can you give an example where this is not the case?

**Comment by jayvdb** [comment]
Is it being done on `Fixed` and/or `Fixed.post` ?  It needs to be both.

**Comment by tfranzel** [comment]
that was the cruial piece of information. i'll have a look at the methods again. for the classes it should already work as expected

**Comment by tfranzel** [comment]
``inspect.getdoc`` was used improperly. on fixing it, it gave too much though. i still need to stop the discovery on the DRF base classes, because it would otherwise emit the generic DRF documentation if there is do docstring on one's own classes. almost there

**Comment by jayvdb** [comment]
Something like https://github.com/jayvdb/django-dunder/blob/1c589e3/django_dunder/_register.py#L36 ?

**Comment by tfranzel** [comment]
@jayvdb that is not enough to do it properly. check out this. i think that should solve your problem. please close if issue is resolved.

**Comment by tfranzel** [comment]
reopen if it does not work as expected

**Comment by jayvdb** [comment]
I cant re-open; I dont have permission to do that.
