### ISSUE TITLE
Replace path parameters with a set of values, and individual serializer gets picked dynamically

### ISSUE THREAD

**Issue by shashank-workb** [tfranzel/drf-spectacular#961]
Hey

I have my url like this

`path('/data/<str:kind_id>')`

the view is like this (general factory design pattern)
```
serializer_map = {
    "kind_id1": kind_id1serializer,
    "kind_id2": kind_id1serializer,
}


class KindCreate(CreateAPIView):
    def get_serializer_class(self, *args, **kwargs):
        serializer = serializer_map.get(self.kwargs["kind_id"]).get(
            "serializer"
        )
        if not serializer:
            raise serializers.ValidationError(
                {"kind_id": "Invalid kind_id!"}
            )
        return serializer
```

Every replacement of "kind_id" can be one of multiple values ['kind1', 'kind2'.....], and it takes the value from the serializer_map.

Can I use the parameters in @extend_schema to pass the list ['kind1', 'kind2'.....], and get the library to replace the <str: kind_id> and figure out docs for its respective serializer? 

I can see I can use pre-processing hooks but how do I pass the "kind_id" in the kwargs of the request?
Or is there any hook via which I can modify the path to serializer mapping, so that if I get [(<kind_id>, None)], I can modify it to [('kind_id1', kind_id1ser), ('kind_id2', kind_id2ser)]?

**Comment by tfranzel** [comment]
I think we have this already covered, you were just not aware how it is called. Preprocessing hooks are not appropriate here.

The keyword is polymorphic. There is a Django/DRF library `django-rest-polymorphic` that supports that seamlessly (for which we have support). We also have support to do this manually without that library.

You would use something like this:

```python
@extend_schema(responses=PolymorphicProxySerializer(
        component_name='MetaPerson',
        serializers=[LegalPersonSerializer, NaturalPersonSerializer],
        resource_type_field_name='type',
    )
```
and use the facilites provided by OpenAPI. `resource_type_field_name=None` removes the discriminator and is easier to handle if you don't need it. Please read the doc for `PolymorphicProxySerializer` for more info.

This is all realized as [SerializerExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-serializer-magic-with-openapiserializerextension). You could either use our class with the decorator OR write an extensions
similar to [this](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/serializers.py) that deals with your custom polymorphic handling automatically. Your class wouldn't need to be as complicated though.

**Comment by shashank-workb** [comment]
So sorry to query again, tried the whole day but was still stuck

I am still doubtful about this

My code will be having two seperate urls
path('/data/<str:kind_id>') -----> /data/kind1/     and    /data/kind2/

so I am actually calling these two APIs seperately, and each url will use just one serializer for its request/response. 
I get this error if I run directly
```
exception raised while getting serializer. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'kind_id')
```

I am trying to tell the code that kind_id should be replaced by two seperate values i.e. kind1 and kind2, and thus the get_serializer_class will return the appropriate serializer. 


Also,
the doc I got is this, https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html?highlight=polymorphic#drf_spectacular.utils.PolymorphicProxySerializer
Its hinting towards making decisions based on the discriminator field in the serializer. I am trying to get the value in url be replaced.

Are there any more docs where I get to know the meaning of `component`, any basic examples of how this is used?

**Comment by tfranzel** [comment]
sry I had to re-read the thing. 

> The error is basically that the self.kwargs that goes with request, does not have 'kind_id' in it. Is there a way to send kwargs in the request via any util in this library?

yes this cannot work. we will call this method to get the serializer class and we do not know this custom parameter so it will throw. 

> Its hinting towards making decisions based on the discriminator field in the serializer.

this is how I understood your question. Usually people want to have polymorphism on that level, and it is usually not bound to the path. 

With that knowledge, a preprocessing hook is not unreasonable. It would expand the `kind_id` into all case, "duplicating" endpoint entries. That can work if that is what you want. You would just need to rewrite `get_serializer_class ` to get that info from the path in `self.request` instead. this would be available live as well as schema generation.

> the doc I got is this, https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html?highlight=polymorphic#drf_spectacular.utils.PolymorphicProxySerializer
Its hinting towards making decisions based on the discriminator field in the serializer. I am trying to get the value in url be replaced.

The discriminator cannot reference the path as far as I know. It is internal to the component. If you insist on having an explicit link between the path var and the serializer type like that, `PolymorphicProxySerializer` might not be the right solution for you. I don't think OpenAPI can you that level of flexibility here.

**Comment by shashank-workb** [comment]
Got it, thanks for taking your time out and replying in such short time T.Franzel!!

Amazing library, appreciate it a lot !! ⭐️

**Comment by shashank-workb** [comment]
@tfranzel Hey in `ListCreateApiView`

I have this code
```
class Kindness(ListCreateAPIView):
    
    @extend_schema(
        parameters=[
            OpenApiParameter(
                name='kind_id',
                type=OpenApiTypes.UUID,
                location=OpenApiParameter.PATH,
                description='The kind UUID',
                required=True
            ),
        ],
        request=LinkedInLearningConnectionSerializer
    )

    def get_serializer_class(self, *args, **kwargs):
        serializer = connection_serializers.get(self.kwargs["kind_id"])
        if not serializer:
            raise serializers.ValidationError(
                {"kind_id": "Invalid kind_id!"}
            )
        return serializer
```

The doc for extend_schema says that
```
 request –
replaces the discovered Serializer.
```

But when I generate schema, it goes into the code of get_serializer_class. Is there anyway that I can bypass it and stop the spectacular code go into the get_serializer_class, and take what has been given in the 'request' in extend schema??

**Comment by tfranzel** [comment]
`get_serializer_class` is bypassed if there is no missing information. You do override `request`, but for `response`, something has still to be determined. 

If you decorate all request (where applicable) & response endpoints for the view, the method is not called anymore. Notice you have `list` and `create`


that link is the same problem in a differetn context, e.g. when we need to find the type of the path parameter `id` for retrieve operations. This can be fixed like above with a parameter and then the method is not called anymore.

**Comment by shashank-workb** [comment]
:)

Feeling embarassed now. That was the solution all along. 

Thank you so much T.Franzel.

Can I keep this issue open for just a few more days, in case I get stuck?

**Comment by tfranzel** [comment]
does not need to stay open. comment if you like, I'll get notified anyway.
