### ISSUE TITLE
Custom types within inline_serializer

### ISSUE THREAD

**Issue by roman-certn** [tfranzel/drf-spectacular#964]
Looking for ability to use `OpenApiTypes` inside `inline_serializer`. Currently those custom fields re being ignored by schema.
```
@extend_schema(
    responses={
        200: inline_serializer(
            name="Response",
            fields={
                "key": serializers.CharField(),
                "value": OpenApiTypes.ANY
            }
        )
)
```

**Comment by tfranzel** [comment]
You can't. `inline_serializer` is a simple helper function that builds an actual serializer and feed it to the machinery.  It is meant as a quick helper for simple one-off solution.

If you have more complicated requirements, you actually need to build a serializer and decorate it properly.

**Comment by roman-certn** [comment]
Found a workaround:
```
@extend_schema_field(OpenApiTypes.ANY)
class AnyField(serializers.Field):
    pass

@extend_schema(
    responses={
        200: inline_serializer(
            name="Response",
            fields={
                "key": serializers.CharField(),
                "value": AnyField()
            }
        )
)
```
