### ISSUE TITLE
MultipleChoiceField not exploding choices in Swagger UI

### ISSUE THREAD

**Issue by sparktx-adam-gleason** [tfranzel/drf-spectacular#965]
**Describe the bug**
drf-spectacular version `0.26.1`

`serializers.MultipleChoiceField` in a request Serializer results in `invalid choice` 400 error when selecting more than one option using the Swagger UI view. 

**To Reproduce**
```python
# serializers.py
choices = [
    "option1",
    "option2",
    "option3",
]

class MyCreateSerializer(serializers.Serializer):
    """Create serializer for saving my choices""""
    my_choices = serializers.MultipleChoiceField(choices=choices)

# views.py
@extend_schema(
    methods=["post"],
    request=serializers.MyCreateSerializer,
)
def save_choices(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            my_choices = serializer.validated_data.get("my_choices", [])
            services.save_choices(choices=my_choices)
            return Response({"success": True }, status=status.HTTP_200_OK)
```

In the Swagger UI, I see the multiple select widget with my choice options. Selecting one choice works but selecting more than one produces this error

status code: 400 Bad Request
```json
{
  "my_choices": [
    "\"option1,option2,option3\" is not a valid choice."
  ]
}
```

Here is a cURL example
```shell
curl -X 'POST' \
  '<MY ENDPOINT URL>' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic REDACTED' \
  -H 'Content-Type: multipart/form-data' \
  -H 'X-CSRFTOKEN: REDACTED' \
  -F 'my_choices=option1,option2,option3'
```

**Expected behavior**
Selecting more than one option for MultipleChoiceField would explode the choices by default

```shell
curl -X 'POST' \
  '<MY ENDPOINT URL>' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic REDACTED' \
  -H 'Content-Type: multipart/form-data' \
  -H 'X-CSRFTOKEN: REDACTED' \
  -F 'my_choices=option1' \
  -F 'my_choices=option2' \
  -F 'my_choices=option3'
```

**Comment by tfranzel** [comment]
Hi @sparktx-adam-gleason, on first glace this looks like a SwaggerUI issue to me. I don't even think we could do anything different. Afais OpenAPI only provides those `explode`/`style` switches on query parameters. 

The way this is translated into a curl command is outside of our reach. The schema itself seems correct and I suppose you can only provoke this if the content type is `form-data`.

**Comment by sparktx-adam-gleason** [comment]
Hi @tfranzel 

I was able to tweak the Swagger yaml file to produce the desired result.

```yaml
/ENDPOINT/:
    post:
      operationId: operationId
      description: "description"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MyCreateSerializer'
            encoding:
              'my_choices':
                style: form
                explode: true
```
I added this manually and it produced the desired result
```yaml
encoding:
    'my_choices':
        style: form
        explode: true
```

Ref https://github.com/swagger-api/swagger-ui/issues/5106

Is there some way to add the encoding information to `@extend_schema`?

**Comment by tfranzel** [comment]
Your example has a point there. it has a syntax error but I think I get it. Something to that effect is probably the only reasonable solution.

**Comment by sparktx-adam-gleason** [comment]
I agree a global param for `@extend_schema` seems like overkill since this generally related to `requestBody`.

There is functionality to define a custom `dict` for `request` param in `@extend_schema`. The issue I'm seeing is the `dict` value always maps to the `schema` key. 
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/plumbing.py#L311-L315

There would need to be functionality to add this extra content and map to `content` directly
```python
@extend_schema(
...,
request={
   "multipart/form-data": {
        "schema": serializers.MyCreateSerializer
        # NOTE: Other custom keys can go after "schema" and would be included in the path `content`
        "encoding": { "field_name": { "explode": True }}  # User defined additional data
    }  
}
)
```

**Comment by tfranzel** [comment]
this breaks existing functionality. for `{"multipart/form-data": XXX}` XXX can either be a dict which means raw schema or the heap of other choices.
```python
# A
@extend_schema(request={"multipart/form-data": (xxx, {"field_name": {...}})
# B
@extend_schema(request={"multipart/form-data": OpenApiRequest(xxx, encoding={"field_name": {...}})})
```

A would be a less problematic solution. So a tuple instance, which does not collide with existing functionality. However I'm leaning more towards B with `OpenApiRequest()` because we already have an equivalent `OpenApiResponse()` and it would be awkward to break symmetry.

**Comment by sparktx-adam-gleason** [comment]
I like the idea of having `OpenApiRequest` functionality to be able to define the custom responseBody in a structured and consistent manner
