### ISSUE TITLE
Function Based Views - unable to guess serializer

### ISSUE THREAD

**Issue by rain-anglehealth** [tfranzel/drf-spectacular#969]
**Describe the bug**
I'm adding drf-spectacular to our project.

I'm getting the following error when trying to generate the schema:
" Error [get_token]: unable to guess serializer. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. Either way you may want to add a serializer_class (or method)"

I'm using a function based view, snippet below:
```
from .serializers.auth import GetTokenSerializer

@api_view(["POST"])
@authentication_classes([UserTypeBasicAuthentication])
@permission_classes([IsAuthenticated])
@check_request(GetTokenSerializer)
@extend_schema(
    request=GetTokenSerializer,
    responses=None
)
def get_token(request: Request) -> Response:
...
```

**Expected behavior**
After passing a function based view an extend_schema decorator with the serializer, spectacular should be able to find the serializer

Thank you!

**Comment by tfranzel** [comment]
decorator order matters. put `@extend_schema` on top i.e. as the outermost decorator. `@api_view` does certain transformations to the function on which our decorators depends on. Like this, the `get_token` function is **not yet** a view and our decorator therefore has undefined behavior.
