### ISSUE TITLE
I don't want to sort on the filter parameter enum.

### ISSUE THREAD

**Issue by devnine99** [tfranzel/drf-spectacular#977]
https://github.com/tfranzel/drf-spectacular/blob/28b858e83e8341c806cc23e7cb09ea1f06b2b357/drf_spectacular/plumbing.py#L373-L378

**Comment by tfranzel** [comment]
Everything in the schema is sorted in some way to ensure reproducibility so the schema does not change between runs. 

I can see that there might be cases where an unsorted list ist preferred, but it is difficult to change now and consistency definitely wins here.
