### ISSUE TITLE
Feature: support templating in `redoc.html`

### ISSUE THREAD

**Issue by dhruvkb** [tfranzel/drf-spectacular#978]
**Describe the feature**
The `redoc.html` file included in the project templates (https://github.com/tfranzel/drf-spectacular/blob/28b858e83e8341c806cc23e7cb09ea1f06b2b357/drf_spectacular/templates/drf_spectacular/redoc.html) is great as a Redoc site starting point, but a mature project needs to also include some custom code.

**Expected behavior**
Changing the HTML template to include some blocks would project a lot of benefits such as the ability to

- include some custom CSS
  - possibly implement a dark theme
- add a favicon to the site
- add open-graph meta tags 

Currently there is no known or documented way to achieve these goals.

**Comment by tfranzel** [comment]
We added a lot of customization for swagger-ui and it was never really enough. I would prefer to not add 3-4 more settings just for redoc.

We finally added `blocks` in #918, which is flexible and not that settings-heavy. I could image having the same for redoc. 

In any case, you can always override a template (via app ordering) for any django app yourself. Nothing special going on here. The `blocks` version is just a less copy&pasty version of that.

**Comment by dhruvkb** [comment]
Yes, my requests was precisely to support blocks in the Redoc template. 

As a user, we could overwrite the entire template, but that would mean losing out on any improvements brought by future updates to `drf-spectacular` unless we manually check and keep comparing the two versions.
