### ISSUE TITLE
extend_schema summary is missing

### ISSUE THREAD

**Issue by MahmoudAljabary** [tfranzel/drf-spectacular#98]
I'm able to set a description for each endpoint, however i can't find a way to set a summary attribute in extend_schema.

2 Description (can be rather long text) vs 1 summary
![Screenshot - 2020-06-17T011914 452](https://user-images.githubusercontent.com/3123672/84837520-a0c2ce80-b038-11ea-906d-f57e49e37d2b.png)

**Comment by tfranzel** [comment]
#97 deals with this issue

**Comment by tfranzel** [comment]
should be done with #97 and 0241c10. reopen if something is missing

**Comment by MahmoudAljabary** [comment]
looks good. whats about in https://pypi.org/project/drf-spectacular version bump?
