### ISSUE TITLE
Custom pagination_class cannot be initialized in _get_paginator

### ISSUE THREAD

**Issue by fancydancing** [tfranzel/drf-spectacular#980]
**Describe the bug**
We are using custom pagination class in a ViewSet. The problem is that this class requires `request` for initialization, and `_get_paginator` fails to initialize it since it does it with no parameters (and does not provide any request at all). We are getting an error: `CustomPagination.__init__() missing 1 required positional argument: 'request'`.  

**To Reproduce**

This is how our custom pagination class is initialized
```
class CustomPagination(BasePagination):
    def __init__(
        self,
        request,
        page_query_param="page",
        page_size_query_param="per_page",
        default_page_size=None
    ):
      ...
```

And this is where the crash happens
```
    def _get_paginator(self):
        pagination_class = getattr(self.view, 'pagination_class', None)
        if pagination_class:
            return pagination_class()
        return None
```

**Expected behavior**
Would be enough to be able to provide some another (default) `pagination_class` (or just `None`) for the `list` method of a viewset.

I tried to override the `pagination_class` for a viewset (or for a `list` method of a viewset) but did not succeed. Should I use `@extend_schema` decorator? But in which exact way? Or should I define and use a `CustomAutoSchema(AutoSchema)` class to override `_get_paginator`? But I only need to override `pagination_class` for a couple of viewsets, not for each of them. Is this possible?

Thank you for your help in advance.

**Comment by tfranzel** [comment]
Hi @fancydancing,

I would call that expected behavior since you are breaking DRF's interface, which is perfectly fine but unexpected. 
The decorators won't help because the error happens before they would take effect in this particular case.

Having a custom schema for this is the correct thing to do:

```python
    from drf_spectacular.plumbing import filter_supported_arguments

    class CustomAutoSchema(AutoSchema):
        def _get_paginator(self):
            pagination_class = getattr(self.view, 'pagination_class', None)
            if pagination_class:
                return pagination_class(
                    **filter_supported_arguments(pagination_class.__init__, request=self.view.request)
                )
            return None
```

This checks if `request` is a supported parameter and provides it if supported. The request itself is the mock request we use throughout.

Just set this schema class in the global setting `DEFAULT_SCHEMA_CLASS` and you should be good to go.

**Comment by fancydancing** [comment]
@tfranzel Thanks so much for your quick response, it worked! So `filter_supported_arguments` was the thing :)
