### ISSUE TITLE
parameters supporting lazy strings are not typed as accepting them

### ISSUE THREAD

**Issue by nils-van-zuijlen** [tfranzel/drf-spectacular#982]
**Describe the bug**
Updating to django-stubs to 1.13.0 and later, the `lazy` string functions from the translations module are declared as returning `Promise` objects instead of `str`.

Most classes / functions in drf_spectacular are typed as accepting `str` only, but work well with lazy strings, and are now flagged by mypy.

**To Reproduce**
Declare a response with the description set to a lazy translatable string.
```py
from django.utils.translations import gettext_lazy as _
from drf_spectacular.utils import OpenApiResponse
OpenApiResponse(description=_("Parsing and validation errors."))
```
Typecheck the code with mypy and django-stubs 1.13.0 or later.
```text
foo.py:3: error: Argument "description" to "OpenApiResponse" has incompatible type "_StrPromise"; expected "str"  [arg-type]
```

**Expected behavior**
No typecheck error is raised, the translatable arguments are declared as allowing `StrOrPromise`

**References**
https://github.com/typeddjango/django-stubs#why-am-i-getting-incompatible-argument-type-mentioning-_strpromise

**Comment by nils-van-zuijlen** [comment]
This does not currently cause errors when type checking drf-spectacular itself because the django-stubs dependency was pinned to the version before that change: https://github.com/tfranzel/drf-spectacular/pull/693#issuecomment-1080022209 and https://github.com/tfranzel/drf-spectacular/commit/799f3941586e47c7e97f489f26dd6e1c941bcf85

But since that was more than one year ago, would it be possible to unpin it?

**Comment by tfranzel** [comment]
Yes, we should check and lift the stubs pinning. 

Yes, accounting for promise str we should definitely support in the typing. Question is which type is the best here? We can't use something from the stubs package directly, as it may not be available in production. Conditional import might be an option. 

Or maybe just `_LazyStrType = Union[str, Promise[str]]` and use that in utils.py. Looks like they basically do the same.

**Comment by nils-van-zuijlen** [comment]
The django-stubs-ext could be added as a typecheck dependency and the import conditioned on `typing.TYPE_CHECKING`?

**Comment by tfranzel** [comment]
Although I lean towards DIY for this seemingly simple thing, there is likely something more going on through the mypy django plugin. `_StrPromise` does not exist outside of mypy.

https://github.com/typeddjango/django-stubs/blob/master/django_stubs_ext/django_stubs_ext/aliases.py

We also have to make sure we don't break users relying on other static type checkers like pyright.

**Comment by nils-van-zuijlen** [comment]
As they are defined in https://github.com/typeddjango/django-stubs/blob/master/django-stubs/utils/functional.pyi#L30 I don't see why they would not exist for those users.

And if I understand correctly https://github.com/typeddjango/django-stubs/issues/579, pyright does not break when django-stubs are applied without extension.

Another option would be to try importing from `django-stubs` directly at typechecking time, and if it not available to define `StrOrPromise` as being `str`.

**Comment by tfranzel** [comment]
I know this is not exactly what was discussed, but I thought I give the minimal version a try before introducing conditional importing and type checking branching.

@nils-van-zuijlen, can you confirm this behaves as expected?
