### ISSUE TITLE
can i filter endpoints?

### ISSUE THREAD

**Issue by stanhjr** [tfranzel/drf-spectacular#983]
I have many applications in django for different commands, this is not very convenient for testers

is it possible to add a field to the swagger that filtered my endpoints?

**Comment by stanhjr** [comment]
solved!

1. add to SPECTACULAR_SETTINGS 
'SWAGGER_UI_SETTINGS': {
        'docExpansion': 'list',
        'filter': True,
        'tagsSorter': 'alpha',
    },
    
2. add decorator to viewset
@extend_schema(tags=['some_tag'])

**Comment by tfranzel** [comment]
great! you are aware that setting `SCHEMA_PATH_PREFIX ` for your setup may remove the need for having to manually add `some_tag`. It uses the first non-common path segment as a tag.


https://github.com/tfranzel/drf-spectacular/blob/ea31d9062ede9e83a01021e7a80c3a7fbbecbad1/drf_spectacular/settings.py#L8-L13

**Comment by stanhjr** [comment]
cool! Thanks! its worked
