### ISSUE TITLE
Standard headers properties to all endpoints in one project 

### ISSUE THREAD

**Issue by barak-payem** [tfranzel/drf-spectacular#984]
Hi, 

We have a custom header for our project that should be on all endpoints, 
Is there a way to configure it in one place (Not on every "extend_scheme")? 
I tried looking for a configuration that adds headers by default to all endpoints but failed to find one.

**Comment by tfranzel** [comment]
Hi @barak-payem,

that is a customization not covered by the decorators or settings. Best course of action is a small patch of the `AutoSchema`. This is a duplicate of  #804

Please take this example https://github.com/tfranzel/drf-spectacular/issues/804#issuecomment-1234469766 as starting point.

**Comment by barak-payem** [comment]
Thanks for the quick response
