### ISSUE TITLE
Are nested serializers in multipart/form-data supported?

### ISSUE THREAD

**Issue by MatejMijoski** [tfranzel/drf-spectacular#987]
I want to allow file uploads in nested objects. I have 2 nested serializers but the Swagger docs do not reflect that and just show the nested serializer as a JSON object. Is there a way to adjust this?

```
class UserPatchSerializer(serializers.ModelSerializer):
    picture = FileUploadSerializer(required=False)

class FileUploadSerializer(serializers.Serializer):
    file = serializers.FileField()
```

If this is not supported, is there a way to overwrite the default behaviour?

**Comment by tfranzel** [comment]
I think this is supported, or rather the schema should reflect that already. Whether the auto-generated example in swagger does reflect this is another question. 

Please check the schema tab in swagger to confirm that nothing is missing.
