### ISSUE TITLE
Nested serializer schema not showing a field

### ISSUE THREAD

**Issue by armanckeser** [tfranzel/drf-spectacular#988]
**Describe the bug**
Very possible that I am misunderstanding how something should work, but in case I am not:

These serializers
```python
class ResponseNodeSerializer(serializers.Serializer):
    type: serializers.ChoiceField(choices=["text"])
    content: serializers.CharField(max_length=5000)

class CreatedResponseSerializer(serializers.Serializer):
    response_body = ResponseNodeSerializer(many=True)
```
On a function view:
```python
@extend_schema(responses=CreatedResponseSerializer)
@api_view(["POST"])
@permission_classes([])
def responses_view(request: Request) -> Response:
```

Gives completely empty example and swagger definition.

Code | Description | Links
-- | -- | --
200 | No response body

**To Reproduce**
Simple example provided

**Expected behavior**
Expected the schema to have 
```json
{
	"response_body": [
		"type": "text",
		"content": "string"
	]
}
```

**Comment by tfranzel** [comment]
This is expected behavior because your serializer is broken

```python
type: serializers.ChoiceField(choices=["text"])
content: serializers.CharField(max_length=5000)
```

should be

```python
type = serializers.ChoiceField(choices=["text"])
content = serializers.CharField(max_length=5000)
```

That is basically doing nothing. So serializers having no fields are filtered out and discarded. Since `CreatedResponseSerializer` has no other valid (non-empty) fields, it gets removed.

**Comment by armanckeser** [comment]
Well I am blind. Thanks for pointing that out!
