### ISSUE TITLE
response example is always an array instead of dict with status code 2xx

### ISSUE THREAD

**Issue by ChunxueLin** [tfranzel/drf-spectacular#990]
I used the **extend_schema** decorator to generate swagger ui documentation. when I use status code 200(or other 2xx), the example value always has a '[]' outside, it becomes an **array**! and the **schema** is also like **[Report].**
```
@extend_schema(
        parameters=...,
        description=...,
        responses={
                200: OpenApiResponse(response=ReportSerializer,
                    description='successful operation',
                    examples=[
                        OpenApiExample(
                            'example',
                            value={"start": "2023-01-30T00:00:00+00:00",
                                "end": "2023-02-06T00:00:00+00:00",
                                "rvmTransactions": [{
                                    "id": 1,
                                    "storeId": "123",
                                    "transactions": [{
                                        "id": 1024,
                                        "voucherId": 518,
                                        "voucherCreatedAt": "2023-02-01T08:30:12+00:00",
                                        "receivedAt": "2023-02-01T07:30:12+00:00",
                                        "count": 23
                                    }]
                                }]
                            }
                        )
                    ])
        }
)
```
![response_200](https://github.com/tfranzel/drf-spectacular/assets/35669092/44a43b30-8bb2-4ade-a6da-323f054fb7aa)
![schema_200](https://github.com/tfranzel/drf-spectacular/assets/35669092/b072343e-8d2f-48d7-a3a2-f75a2720b047)
but when I **only** change the status code to 300(or3xx, 4xx, 5xx), the response example becomes normal.   the example value is a **dict** and the schema is simply **Report** instead of **[Report]**
```
@extend_schema(
        parameters=...,
        description=...,
        responses={
                300: OpenApiResponse(response=ReportSerializer,
                    description='successful operation',
                    examples=[
                        OpenApiExample(
                            'example',
                            value={"start": "2023-01-30T00:00:00+00:00",
                                "end": "2023-02-06T00:00:00+00:00",
                                "rvmTransactions": [{
                                    "id": 1,
                                    "storeId": "123",
                                    "transactions": [{
                                        "id": 1024,
                                        "voucherId": 518,
                                        "voucherCreatedAt": "2023-02-01T08:30:12+00:00",
                                        "receivedAt": "2023-02-01T07:30:12+00:00",
                                        "count": 23
                                    }]
                                }]
                            }
                        )
                    ])
        }
)
```

![response_300](https://github.com/tfranzel/drf-spectacular/assets/35669092/48d8569e-73fc-49ce-bbe2-87894a189f0c)
![schema_300](https://github.com/tfranzel/drf-spectacular/assets/35669092/8ca9e8cf-03b6-4bec-9f9f-aee6c9077e81)
The same format is used in the response examples for 200 and 300 status codes, but why the result in swagger ui is not the same?  
Actually the example value I want is to get a **dict** when the status code is **200**.

btw. requirements.txt
asgiref==3.6.0
attrs==23.1.0
Django==4.2.1
django-filter==23.1
djangorestframework==3.14.0
drf-spectacular==0.26.2
drf-spectacular-sidecar==2023.4.1
inflection==0.5.1
jsonschema==4.17.3
Markdown==3.4.3
psycopg2-binary==2.9.6
pyrsistent==0.19.3
pytz==2023.3
PyYAML==6.0
sqlparse==0.4.4
uritemplate==4.1.1

**Comment by tfranzel** [comment]
Hi,

you are decorating a Viewset `list` which is **almost always** a list of items, so we convert it to a list. Notice that this is only done for Viewset's `list` and nowhere else.

A non-`2XX` response is usually a error response, which is why we don't convert it a list. (this can be controlled with the setting `ENABLE_LIST_MECHANICS_ON_NON_2XX`)

What you do here is non-default behavior for DRF's viewsets. We call wrapping a list response in a dict extra fields an **envelope**. We have some useful helpers to model this specific use-case:

https://drf-spectacular.readthedocs.io/en/latest/faq.html#how-do-i-wrap-my-responses-my-endpoints-are-wrapped-in-a-generic-envelope

I strongly recommend using that helper function. However. if you want to do it yourself, the magic happens with `@extend_schema_serializer(many=False)` on the `ReportSerializer`. It forcefully turns off the automatic list detection.

**Comment by ChunxueLin** [comment]
it works, thank you
