### ISSUE TITLE
Version 0.26.0 breaks the content generation for schema responses

### ISSUE THREAD

**Issue by kylepollina** [tfranzel/drf-spectacular#993]
**Describe the bug**
In version 0.26.0 something changed that breaks the 'Request Samples' section in the Redoc viewer.

Using version 0.25.0, I see this for one of my endpoints:

<img width="453" alt="Screenshot 2023-05-30 at 12 02 37 AM" src="https://github.com/tfranzel/drf-spectacular/assets/13981456/f78d40e4-3e91-4735-8cc0-71367d512339">

After upgrading to 0.26.0, I am missing this section for all endpoints:

<img width="453" alt="Screenshot 2023-05-30 at 12 04 19 AM 1" src="https://github.com/tfranzel/drf-spectacular/assets/13981456/16154ed3-2926-499b-871c-f9c605d7f731">

 

**To Reproduce**
Use `drf-spectacular==0.25.0` and the `Redoc` viewer

**Expected behavior**
I expect the 'Request Samples' to be built out the same way it has in versions <= 0.25.0

**Comment by kylepollina** [comment]
I only could do a little digging, and found that the `content` section of the schemas are not being generated anymore.

v0.25.0:

<img width="1207" alt="Screenshot 2023-05-30 at 12 13 24 AM" src="https://github.com/tfranzel/drf-spectacular/assets/13981456/dce7b9a1-f03a-47d7-93d1-f12b5058db0b">


v0.26.2:

<img width="1207" alt="Screenshot 2023-05-30 at 12 13 52 AM" src="https://github.com/tfranzel/drf-spectacular/assets/13981456/1745d84e-ebb1-440f-8623-6cd4c6542b1b">

**Comment by tfranzel** [comment]
Hi,

that seems strange because nothing major changed: https://github.com/tfranzel/drf-spectacular/compare/0.25.0...0.26.2

Are there any warning emitted on the console?
Are you sure nothing else changed on your side? 
Are you using a library for the auth endpoint?

**Comment by tfranzel** [comment]
can't reproduce with the given information
