### ISSUE TITLE
Defining a static dict for an error response in @extend_schema returns "string" as the response body

### ISSUE THREAD

**Issue by dashdanw** [tfranzel/drf-spectacular#996]
**Describe the bug**
In instances where there is no available serializer, or the response returns a dict, I would like to be able to specify that dict as the response in my responses list under `extend_schema`. I understand this is not maybe how it should be expected to behave but I was also unable to figure out a solution for this via the documentation.

**To Reproduce**
```
class RequestAPIView(APIView):
    @extend_schema(
        responses={
            200: ResponseSerializer,
            404: {"id": "not_found", "message": "User not found"}
        },
    )
    def get(self, request, format=None):
         ...
         except:
             return  Response(data={"id": "not_found", "message": "User not found"})
         ....
 ```

output the following openapi spec 
<img width="547" alt="image" src="https://github.com/tfranzel/drf-spectacular/assets/1347347/ab0d801f-e171-4ef8-80d6-8c7c12845cd1">

**Expected behavior**
It would be nice to either have documentation on how to return a static dict response such as this, or to be able to specify as defined.

Thanks in advance for any and all help

**Comment by dashdanw** [comment]
I will try to add some info to the docs.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
